# Segment 0: Importing Libraries - LOCAL

In [ ]:
# 1. System / Installation (run once in Colab)
!pip install pandas numpy scikit-learn matplotlib seaborn shap -q

!pip install optuna --quiet
!pip install lightgbm --quiet
!pip install catboost --quiet
!pip install imbalanced-learn --quiet
!pip install xgboost --upgrade --quiet

!pip install pyarrow beautifulsoup4 joblib -q

In [ ]:
# 2. Standard Library Imports
import os
import json
import zipfile
import pickle
import warnings
import subprocess
from pathlib import Path

warnings.filterwarnings('ignore')

In [ ]:
import numpy as np
import pandas as pd
import scipy
import sklearn

# 4. Visualization
import matplotlib.pyplot as plt
# import seaborn as sns

In [ ]:
%pip install optuna

Requirement already satisfied: optuna in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (1.20.0)
Requirement already satisfied: colorlog in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (2.5.3)
Requirement already satisfied: packaging>=20.0 in .\AppData\Roaming\Python\Python314\site-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (2.0.54)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (4.70.1)
Requirement already satisfied: PyYAML in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from alembic>=1.5.0->optuna) (1.4.1)
Requirement already satisfied: typing-extensions>=4.12 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.6)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python314\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install optuna

Requirement already satisfied: optuna in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (1.20.0)
Requirement already satisfied: colorlog in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (2.5.3)
Requirement already satisfied: packaging>=20.0 in .\AppData\Roaming\Python\Python314\site-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (2.0.54)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (4.70.1)
Requirement already satisfied: PyYAML in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from alembic>=1.5.0->optuna) (1.4.1)
Requirement already satisfied: typing-extensions>=4.12 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.6)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python314\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import optuna
print(optuna.__version__)

import optuna.visualization as ov

optuna.logging.set_verbosity(optuna.logging.WARNING)

5.0.0

In [ ]:
#6. Data Processing / Utilities
from bs4 import BeautifulSoup
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.base import clone

# 7. Model Selection / Validation
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
    cross_val_predict
)

# 8. Metrics (clean unified block)
from sklearn.metrics import (
    roc_auc_score,
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score,
    confusion_matrix,
    classification_report,
    accuracy_score,
    f1_score,
    brier_score_loss
)

# 9. Statistical Tests
from scipy import stats
from scipy.stats import chi2_contingency, ttest_ind

# 10. Classical ML Models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    AdaBoostClassifier,
    StackingClassifier,
    VotingClassifier
)

from sklearn.neural_network import MLPClassifier

# 11. Calibration
from sklearn.calibration import CalibratedClassifierCV, calibration_curve

# 12. Imbalanced Learning
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

# 13. Gradient Boosting Frameworks
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier

# 14. Explainability
import shap

# Segment 0: Importing Libraries

In [ ]:
# 1. System / Installation (run once in Colab)
!pip install pandas numpy scikit-learn matplotlib seaborn shap -q

!pip install -q pandas==2.2.3 pyarrow==23.0.1 numpy==2.1.3
!pip install optuna --quiet
!pip install lightgbm --quiet
!pip install catboost --quiet
!pip install imbalanced-learn --quiet
!pip install xgboost --upgrade --quiet

!pip install pyarrow beautifulsoup4 joblib -q

In [ ]:
# 2. Standard Library Imports
import os
import json
import zipfile
import pickle
import warnings
import subprocess
from pathlib import Path

warnings.filterwarnings('ignore')

In [ ]:
# 3. Core Scientific Stack
import numpy as np
import pandas as pd
import scipy
import sklearn

# 4. Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# 5. Hyperparameter Optimization (Optuna)
import optuna
import optuna.visualization as ov

optuna.logging.set_verbosity(optuna.logging.WARNING)

In [ ]:
#6. Data Processing / Utilities
from bs4 import BeautifulSoup
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.base import clone

# 7. Model Selection / Validation
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
    cross_val_predict
)

# 8. Metrics (clean unified block)
from sklearn.metrics import (
    roc_auc_score,
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score,
    confusion_matrix,
    classification_report,
    accuracy_score,
    f1_score,
    brier_score_loss
)

# 9. Statistical Tests
from scipy import stats
from scipy.stats import chi2_contingency, ttest_ind

# 10. Classical ML Models
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    AdaBoostClassifier,
    StackingClassifier,
    VotingClassifier
)

from sklearn.neural_network import MLPClassifier

# 11. Calibration
from sklearn.calibration import CalibratedClassifierCV, calibration_curve

# 12. Imbalanced Learning
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

# 13. Gradient Boosting Frameworks
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier

# 14. Explainability
import shap

# Segment 0: MOUNTING DATASET - LOCAL

In [ ]:
# =========================
# Step 0: Mounting Dataset & unzipping it
# =========================

zip_path = r"D:\STAR_Delimited-selected2.zip"
base_path = r"D:\STAR_Delimited-selected2"

os.makedirs(base_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(base_path)

print("Dataset extracted successfully.")

for file in os.listdir(base_path):
    if file.endswith(".zip"):
        file_path = os.path.join(base_path, file)
        print("Extracting:", file_path)

        with zipfile.ZipFile(file_path, "r") as zip_ref:
            zip_ref.extractall(base_path)

for root, dirs, files in os.walk(base_path):
    print(root, "contains:", files)

from pathlib import Path

base_path = Path(r"D:\STAR_Delimited-selected2")

t_htm_path = (
    base_path
    / "STAR_Delimited-selected2"
    / "Delimited Text File 202509"
    / "Thoracic"
    / "THORACIC_DATA.htm"
)

tf_htm_path = (
    base_path
    / "STAR_Delimited-selected2"
    / "Delimited Text File 202509"
    / "Thoracic"
    / "Individual Follow-up Records"
    / "THORACIC_FOLLOWUP_DATA.htm"
)

t_dat_path = (
    base_path
    / "STAR_Delimited-selected2"
    / "Delimited Text File 202509"
    / "Thoracic"
    / "THORACIC_DATA.DAT"
)

tf_dat_path = (
    base_path
    / "STAR_Delimited-selected2"
    / "Delimited Text File 202509"
    / "Thoracic"
    / "Individual Follow-up Records"
    / "THORACIC_FOLLOWUP_DATA.DAT"
)

print(t_dat_path)
print(t_dat_path.exists())

print(tf_dat_path)
print(tf_dat_path.exists())

Dataset extracted successfully.
D:\STAR_Delimited-selected2 contains: []
D:\STAR_Delimited-selected2\STAR_Delimited-selected2 contains: []
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\CODE DICTIONARY - FORMATS 202509 contains: ['sample_code_FORMATS.sas', 'sample_code_FORMATS.txt']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\CODE DICTIONARY - FORMATS 202509\Thoracic contains: ['THORACIC_FORMATS_FLATFILE.DAT', 'THORACIC_FORMATS_FLATFILE.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509 contains: []
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic contains: ['THORACIC_DATA.DAT', 'THORACIC_DATA.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\HLA Additional contains: ['THORACIC_ADDTL_HLA.DAT', 'THORACIC_ADDTL_HLA.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\Immunosuppression contains: ['THORACIC_IMMUNO_DISCHARGE_DATA.DAT', 'THORACIC_IMMUNO_DISCHARGE_DATA.htm', 'THORACIC_IMMUNO_FOLLOWUP_DATA.DAT', 'THORACIC_IMMUNO_FOLLOWUP_DATA.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\Individual Follow-up Records contains: ['THORACIC_FOLLOWUP_DATA.DAT', 'THORACIC_FOLLOWUP_DATA.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\PRA and Crossmatch contains: ['THORACIC_PRA_CROSSMATCH_DATA.DAT', 'THORACIC_PRA_CROSSMATCH_DATA.htm']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\STAR File User Guide contains: ['National STAR file user guide V1.0.pdf', 'README FIRST.txt', 'STAR File Data Dictionary.xlsx']
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\THORACIC_DATA.DAT
True
D:\STAR_Delimited-selected2\STAR_Delimited-selected2\Delimited Text File 202509\Thoracic\Individual Follow-up Records\THORACIC_FOLLOWUP_DATA.DAT
True

# Segment 0: MOUNTING DATASET

In [ ]:
# =========================
# Step 0: Mounting Dataset & unzipping it
# =========================

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!unzip "/content/drive/MyDrive/Thesis/STAR_Delimited-selected2.zip" -d "/content/STAR_Delimited-selected2"
base_path = "/content/STAR_Delimited-selected2"

for file in os.listdir(base_path):
    if file.endswith(".zip"):
        file_path = os.path.join(base_path, file)
        print("Extracting:", file_path)
        zipfile.ZipFile(file_path).extractall(base_path)

for root, dirs, files in os.walk("/content/STAR_Delimited-selected2"):
    print(root, "contains:", files)

# =========================

t_htm_path = "/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/THORACIC_DATA.htm"
tf_htm_path = "/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Individual Follow-up Records/THORACIC_FOLLOWUP_DATA.htm"

t_dat_path = "/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/THORACIC_DATA.DAT"
tf_dat_path = "/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Individual Follow-up Records/THORACIC_FOLLOWUP_DATA.DAT"

Mounted at /content/drive
Archive:  /content/drive/MyDrive/Thesis/STAR_Delimited-selected2.zip
replace /content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/sample_code_FORMATS.sas? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/sample_code_FORMATS.sas
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/sample_code_FORMATS.txt
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/Thoracic/THORACIC_FORMATS_FLATFILE.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/Thoracic/THORACIC_FORMATS_FLATFILE.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/HLA Additional/THORACIC_ADDTL_HLA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/HLA Additional/THORACIC_ADDTL_HLA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Immunosuppression/THORACIC_IMMUNO_DISCHARGE_DATA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Immunosuppression/THORACIC_IMMUNO_DISCHARGE_DATA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Immunosuppression/THORACIC_IMMUNO_FOLLOWUP_DATA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Immunosuppression/THORACIC_IMMUNO_FOLLOWUP_DATA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Individual Follow-up Records/THORACIC_FOLLOWUP_DATA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Individual Follow-up Records/THORACIC_FOLLOWUP_DATA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/PRA and Crossmatch/THORACIC_PRA_CROSSMATCH_DATA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/PRA and Crossmatch/THORACIC_PRA_CROSSMATCH_DATA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/THORACIC_DATA.DAT
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/THORACIC_DATA.htm
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/STAR File User Guide/National STAR file user guide V1.0.pdf
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/STAR File User Guide/README FIRST.txt
  inflating: /content/STAR_Delimited-selected2/STAR_Delimited-selected2/STAR File User Guide/STAR File Data Dictionary.xlsx
/content/STAR_Delimited-selected2 contains: []
/content/STAR_Delimited-selected2/STAR_Delimited-selected2 contains: []
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509 contains: ['sample_code_FORMATS.sas', 'sample_code_FORMATS.txt']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/CODE DICTIONARY - FORMATS 202509/Thoracic contains: ['THORACIC_FORMATS_FLATFILE.DAT', 'THORACIC_FORMATS_FLATFILE.htm']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509 contains: []
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic contains: ['THORACIC_DATA.htm', 'THORACIC_DATA.DAT']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Immunosuppression contains: ['THORACIC_IMMUNO_DISCHARGE_DATA.htm', 'THORACIC_IMMUNO_FOLLOWUP_DATA.htm', 'THORACIC_IMMUNO_FOLLOWUP_DATA.DAT', 'THORACIC_IMMUNO_DISCHARGE_DATA.DAT']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/Individual Follow-up Records contains: ['THORACIC_FOLLOWUP_DATA.htm', 'THORACIC_FOLLOWUP_DATA.DAT']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/PRA and Crossmatch contains: ['THORACIC_PRA_CROSSMATCH_DATA.DAT', 'THORACIC_PRA_CROSSMATCH_DATA.htm']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/Delimited Text File 202509/Thoracic/HLA Additional contains: ['THORACIC_ADDTL_HLA.DAT', 'THORACIC_ADDTL_HLA.htm']
/content/STAR_Delimited-selected2/STAR_Delimited-selected2/STAR File User Guide contains: ['STAR File Data Dictionary.xlsx', 'README FIRST.txt', 'National STAR file user guide V1.0.pdf']

# Segment 1: EXTRACTING SCHEMA & LOADING DATASET

In [ ]:
# =========================
# Segment 1: Extracting schema & Loading dataset
# =========================

# Prior to modeling, schema definitions were frozen based on the OPTN STAR Thoracic July 2023 release.
# Variable-level missingness and near-constant features were quantified on the baseline adult heart-transplant cohort to guide downstream preprocessing decisions.

t_df_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df.parquet"
tf_df_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df.parquet"

t_schema_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_schema.parquet"
tf_schema_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_schema.parquet"

USE_CACHED_DATA = False

if USE_CACHED_DATA and os.path.exists(t_df_parquet_path) and os.path.exists(tf_df_parquet_path) and os.path.exists(t_schema_parquet_path) and os.path.exists(tf_schema_parquet_path):
    # Load cached parquet
    t_df = pd.read_parquet(t_df_parquet_path, engine='pyarrow')
    tf_df = pd.read_parquet(tf_df_parquet_path, engine='pyarrow')

    t_schema = pd.read_parquet(t_schema_parquet_path, engine='pyarrow')
    tf_schema = pd.read_parquet(tf_schema_parquet_path, engine='pyarrow')

else:
    # STEP 1: Extract schema from THORACIC_DATA.HTM
    def extract_schema(htm_path):
        with open(htm_path, "r", encoding="latin-1") as f:
            soup = BeautifulSoup(f.read(), "html.parser")

        table = soup.find("table")
        rows = table.find_all("tr")

        schema = []
        for row in rows[1:]:
            cells = [c.get_text(strip=True) for c in row.find_all(["td", "th"])]
            if len(cells) >= 7:
                schema.append({"Obs": cells[0], "LABEL": cells[1], "FORMAT": cells[2], "LENGTH": cells[3], "TYPE": cells[4], "START": int(cells[5]), "END": int(cells[6])})

        schema_df = pd.DataFrame(schema)
        return schema_df

    # Load datasets
    t_schema = extract_schema(t_htm_path)
    tf_schema = extract_schema(tf_htm_path)

    # STEP 2: Load the .DAT file using the extracted schema
    def load_dat(dat_path, schema_df):
        colnames = schema_df["LABEL"].tolist()
        # Load the .DAT file, loading all columns as strings to prevent conversion errors
        df = pd.read_csv(dat_path, sep="\t", header=None, names=colnames, dtype=str, encoding="latin-1", low_memory=False)

        return df

    thoracic_df = load_dat(t_dat_path, t_schema)
    thoracic_followup_df = load_dat(tf_dat_path, tf_schema)

    # Make sure index is clean and meaningless
    thoracic_df = thoracic_df.reset_index(drop=True)
    thoracic_followup_df = thoracic_followup_df.reset_index(drop=True)

    # SAVE & LOAD FROZEN DATASET
    thoracic_df.to_parquet(t_df_parquet_path, engine='pyarrow')
    thoracic_followup_df.to_parquet(tf_df_parquet_path, engine='pyarrow')

    t_schema.to_parquet(t_schema_parquet_path, engine='pyarrow')
    tf_schema.to_parquet(tf_schema_parquet_path, engine='pyarrow')

    t_df = pd.read_parquet(t_df_parquet_path, engine='pyarrow')
    tf_df = pd.read_parquet(tf_df_parquet_path, engine='pyarrow')

    t_schema = pd.read_parquet(t_schema_parquet_path, engine='pyarrow')
    tf_schema = pd.read_parquet(tf_schema_parquet_path, engine='pyarrow')

    print("t_df:", thoracic_df.shape)
    print("tf_df:", thoracic_followup_df.shape)

t_df: (234975, 625)
tf_df: (1156190, 81)

# Segment 1 Complete

In [ ]:
t_df_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df.parquet"
tf_df_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df.parquet"

t_schema_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_schema.parquet"
tf_schema_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_schema.parquet"

t_df = pd.read_parquet(t_df_parquet_path, engine='pyarrow')
tf_df = pd.read_parquet(tf_df_parquet_path, engine='pyarrow')

t_schema = pd.read_parquet(t_schema_parquet_path, engine='pyarrow')
tf_schema = pd.read_parquet(tf_schema_parquet_path, engine='pyarrow')

print("t_df:", t_df.shape)
print("tf_df:", tf_df.shape)
assert t_df.shape[1] == len(t_schema), "Column count mismatch"

t_df: (234975, 625)
tf_df: (1156190, 81)

In [ ]:
# t_df.to_csv('1.t_df.csv', index=False)
# tf_df.to_csv('1.tf_df.csv', index=False)

# Segment 2: PREPROCESSING - SENTINEL HANDLING & TYPE CONVERSION

In [ ]:
# ==============================================================================
# SEGMENT 2: PREPROCESSING — SENTINEL HANDLING & TYPE CONVERSION
# ==============================================================================
#
# PURPOSE
# -------
# Convert all raw-string UNOS columns to their correct dtypes, replace every
# UNOS sentinel value with NaN, create binary missingness indicator flags,
# enforce physical plausibility bounds, remap coded categoricals to
# human-readable labels, and drop early-removable administrative columns.
#
# INPUTS  (from Segment 1 parquets)
#   t_df   — THORACIC_DATA baseline, all object dtype, 234,975 × 625
#   tf_df  — THORACIC_FOLLOWUP_DATA, all object dtype, 1,156,190 × 81

# OUTPUTS
#   t_df2, t_df2_with_missing    — cleaned baseline
#   tf_df2, tf_df2_with_missing  — cleaned follow-up
#   t_audit, tf_audit            — per-column conversion quality reports
#
# CHRONOLOGICAL ORDER
#   Phase 1  — Constants & lookup tables
#   Phase 2  — clean_with_schema() function definition
#   Phase 3  — apply_plausibility_bounds() function definition
#   Phase 4  — Inspection helper functions
#   Phase 5  — Execution (cleaning + plausibility)
#   Phase 6  — Post-cleaning character inspection
#   Phase 7  — Value remaps (ABO_MAT etc.)
#   Phase 8  — Final save & round-trip verification
#
# ==============================================================================

import os
import numpy as np
import pandas as pd

# CRITICAL: Set False after any code change. Set True only when you have verified the output is correct.
USE_CACHED_DATA = False   # ← default FALSE

# ==============================================================================
# PHASE 1 — CONSTANTS & LOOKUP TABLES
# ==============================================================================

# ── 1A. Sentinel value definitions ────────────────────────────────────────────
#
# UNIVERSAL_SENTINELS  : applied to EVERY non-protected column.
#   '.'    = SAS missing (dominant — 56 M cells in baseline alone)
#   'U'    = Unknown
#   'ND'   = Not Done
#   'UNK'  = Unknown (alternate form)
#   'I'    = Indeterminate (serology results)
#   'PD'   = Pending
#   '9999' = Uncoded sentinel (appears in GTIME, PTIME, DONOR_ID)
#   'UNKNOWN' = free-text unknown
#
# CODED_UNKNOWN_SENTINELS : applied ONLY to CODED_CATEGORICAL_COLS (see 1C).
#   These integers encode "Unknown/Not reported" in UNOS ordinal/nominal fields,
#   but are REAL measurements in continuous fields (eGFR of 9, SGOT of 99, etc.).
#   NEVER apply these universally to all numeric columns.

UNIVERSAL_SENTINELS      = ['.', 'U', 'ND', 'UNK', 'I', 'PD', '9999', 'UNKNOWN']
CODED_UNKNOWN_SENTINELS  = ['998', '999', '9', '98', '99']

# ── 1B. Protected columns — NO sentinel replacement, NO missing flags ──────────
#
# HLA allele columns: integers like 9, 99, 997 ARE valid allele identifiers.
# Join keys & center codes: must survive intact for cohort filtering in Seg 3.

PROTECTED_COLUMNS = {
    # Primary join keys
    'PT_CODE', 'DONOR_ID', 'WL_ID_CODE', 'TRR_ID_CODE',
    # HLA allele codes — donor
    'DA1', 'DA2', 'DB1', 'DB2', 'DDR1', 'DDR2',
    # HLA allele codes — recipient
    'RA1', 'RA2', 'RB1', 'RB2', 'RDR1', 'RDR2',
    # HLA complement / DQ / DR alleles
    'C1', 'C2', 'DQ1', 'DQ2',
    'DR51', 'DR51_2', 'DR52', 'DR52_2', 'DR53', 'DR53_2',
    # Center & OPO codes (string identifiers, not clinical values)
    'INIT_OPO_CTR_CODE', 'END_OPO_CTR_CODE', 'LISTING_CTR_CODE', 'TRR_FOL_ID_CODE'
}

# ── 1C. Coded categorical columns ─────────────────────────────────────────────
#
# Source: Inspection 5 "Likely coded-nominal" list (95 baseline + 11 follow-up)
#         plus sentinel survey columns where 998/999/9 definitively = "Unknown".
#
# Rule: a column belongs here if its integers represent CATEGORIES (diagnosis
#       codes, ordinal scales, enumerated types) rather than real measurements.
# All others (creatinine, SGOT, DAYSWAIT, eGFR, etc.) are continuous —
#       coded sentinels must NOT be applied to them.

# In CODED_CATEGORICAL_COLS, next to FUNC_STAT_TCR / FUNC_STAT_TRR, add:
# ENCODING NOTE FOR SEGMENT 5:
#   These use Karnofsky scale: 10, 20, 30 ... 100 (998=Unknown, now NaN).
#   Treat as ordinal integer (divide by 10 → 1–10 scale).
#   Do NOT one-hot encode — this destroys ordinal information.

CODED_CATEGORICAL_COLS = {
    # ── Recipient demographics ─────────────────────────────────────────────
    'CITIZENSHIP', 'EDUCATION', 'ETHCAT',
    'ACADEMIC_PRG_TCR', 'ACADEMIC_LEVEL_TCR',
    'ACADEMIC_PRG_TRR', 'ACADEMIC_LEVEL_TRR',

    # ── Recipient clinical status (ordinal/enumerated) ─────────────────────
    'DIAB', 'DIAL_TY_TCR', 'TCR_DUR_ABSTAIN',
    'STERNOTOMY_TCR', 'INIT_PRIORITY', 'END_PRIORITY',
    'PRIOR_STERNO_TCR', 'PRIOR_THORACO_TCR',
    'VAD_DEVICE_TY_TCR', 'VAD_TAH_TCR',
    'MED_COND_TRR', 'COGNITIVE_DEV_TRR', 'MOTOR_DEV_TRR',
    'VAD_DEVICE_TY_TRR', 'VENT_TIMEFRAME_TRR',
    'STERNOTOMY_TRR', 'PREV_TX_ANY_N',
    'PRIOR_STERNO_TRR', 'PRIOR_THORACO_TRR',
    'POST_TX_VENT_SUPPORT',

    # ── Functional status (UNOS ordinal codes, not raw values) ────────────
    'FUNC_STAT_TCR', 'FUNC_STAT_TRR',

    # ── Payment / insurance type (enumerated) ─────────────────────────────
    'PRI_PAYMENT_TCR', 'PRI_PAYMENT_TRR',

    # ── Diagnosis / cause-of-death codes (categorical) ────────────────────
    'COD_WL', 'THORACIC_DGN',

    # ── Donor characteristics (ordinal/enumerated) ────────────────────────
    'CITIZENSHIP_DON', 'ETHCAT_DON', 'LIV_DON_TY',
    'HYPERTENS_DUR_DON', 'DIABDUR_DON', 'INSULIN_DUR_DON',
    'HIST_DIABETES_DON', 'COD_CAD_DON', 'DEATH_CIRCUM_DON',
    'LV_EJECT_METH', 'CORONARY_ANGIO', 'BIOPSY_DGN',
    'INO_PROCURE_AGENT_1', 'INO_PROCURE_AGENT_2', 'INO_PROCURE_AGENT_3',
    'BRONCHO_LT_DON', 'BRONCHO_RT_DON', 'CHEST_XRAY_DON',
    'EDUCATION_DON', 'REASONNOHBVVACCINATIONID',

    # ── Transplant procedure codes ────────────────────────────────────────
    'TX_PROCEDUR_TY', 'PROC_TY_HR', 'SHARE_TY',
    'PERFUSION_LOCATION', 'PERFUSED_BY', 'LU_RECEIVED', 'LU2_RECEIVED',
    'TRANSPLANTTIMEZONEID', 'HEARTCHECKINTIMEZONEID',
    'LEFTLUNGCHECKINTIMEZONEID', 'RIGHTLUNGCHECKINTIMEZONEID',
    'ENBLOCLUNGCHECKINTIMEZONEID',

    # ── Titer codes (ordinal scale, not raw numeric) ──────────────────────
    'TITERA', 'TITERB', 'PRETITERB',

    # ── Country code (enumerated) ─────────────────────────────────────────
    'TRANSPLANT_COUNTRY',

    # ── Outcome / rejection codes (leakage — but need correct sentinel
    #    handling before they are dropped in Segment 3) ────────────────────
    'ACUTE_REJ_EPI', 'GRF_FAIL_CAUSE',

    # ── Post-transplant hemodynamic coded scales (leakage — same reason) ──
    'LVEFPOSTTX24', 'LVEFPOSTTX72',
    'VADDEVICETYPEPOSTTX24', 'VADDEVICETYPEPOSTTX72',
    'VADBRAND1POSTTX24', 'VADBRAND2POSTTX24', 'VADBRAND2POSTTX72',
    'EPINEPHRINEPOSTTX24', 'MILRINONEPOSTTX24', 'DOBUTAMINEPOSTTX24',
    'DOPAMINEPOSTTX24', 'LEVOUNITPOSTTX24', 'LEVODOSAGEMCGMIN24',
    'LEVODOSAGEMCGKGMIN24', 'NEOUNITPOSTTX24', 'NEODOSAGEMCGMIN24',
    'NEODOSAGEMCGKGMIN24', 'VASODOSEPOSTTX24',
    'EPINEPHRINEPOSTTX72', 'MILRINONEPOSTTX72', 'DOBUTAMINEPOSTTX72',
    'DOPAMINEPOSTTX72', 'LEVOUNITPOSTTX72', 'LEVODOSAGEMCGMIN72',
    'LEVODOSAGEMCGKGMIN72', 'NEOUNITPOSTTX72', 'NEODOSAGEMCGMIN72',
    'NEODOSAGEMCGKGMIN72', 'VASODOSEPOSTTX72', 'VAD_TAH_TRR',

    # ── Follow-up specific coded categoricals ─────────────────────────────
    'CARE_PROVIDED_BY', 'ACADEMIC_PRG', 'ACADEMIC_LEVEL',
    'IMMUNO_MAINT_MED', 'COGNITIVE_DEV', 'MOTOR_DEV', 'BRONC_OBLIT',
    'GRF_STAT_CAUSE', 'PRI_PAYMENT', 'TRT_REJ_NUM',
    'COD', 'COD2', 'COD3', 'FUNC_STAT', 'FOL_CD',
}

# ── 1D. Known value fixes ──────────────────────────────────────────────────────
#
# Applied to CHARACTER columns AFTER sentinel removal, BEFORE category cast.
# Source: Inspection 6 — INOTROPIC has '0' (1,640 rows) in a Y/N column.
# '0' encodes "No" in this field based on UNOS data convention.
# Add additional fixes here if remap audit in Phase 6 reveals new cases.

KNOWN_FIXES = {
    'INOTROPIC': {'0': 'N'},
    'ABO':     {'Z': pd.NA},
    'ABO_DON': {'Z': pd.NA},
}

# ── 1E. Columns requiring case normalisation to uppercase ─────────────────────
#
# Inspection 6 confirmed: PERM_STATE in follow-up has upper/lower case mix
# (65 unique values — impossible for a 50-state code without case conflict).
# GENDER, ABO, ABO_DON, GENDER_DON: precautionary for binary enums.

CASE_UPPER_COLS = {
    'GENDER', 'GENDER_DON',
    'ABO', 'ABO_DON',
    'PERM_STATE', 'PERM_STATE_TRR', 'HOME_STATE_DON',
    'WL_ORG',
}

# ── 1F. Physical plausibility bounds ──────────────────────────────────────────
#
# Values OUTSIDE [min_valid, max_valid] → NaN.
# Applied ONLY to columns with confirmed impossible values from inspection 5.
# Conservative list — do NOT over-restrict clinical extremes.
# E.g., SGOT=24,758 is physiologically possible in acute liver injury.
# Values → NaN (not winsorized): impossible medical data should be missing,
# not truncated to an arbitrary boundary value.
#
# Confirmed problematic from inspection:
#   BMI_TCR max = 371,608   (decimal-point data entry error)
#   BMI     max = 1,016,100 (same error, follow-up table)
#   INIT_AGE min = -1       (UNOS sentinel for unknown age)

PLAUSIBILITY_BOUNDS = {
    # column        : (min_valid, max_valid)
    'INIT_AGE'      : (0,   100),   # -1 is UNOS sentinel; adult range 18-100
    'BMI_TCR'       : (10,   70),   # physiologically impossible outside this range
    'BMI'           : (10,   70),   # follow-up BMI
    'HGT_CM_TCR'    : (100, 230),   # adult height in cm
    'WGT_KG_TCR'    : (20,  300),   # adult weight in kg
    'HGT_CM'        : (100, 230),   # follow-up height
    'WGT_KG'        : (20,  300),   # follow-up weight
}

# ── 1G. File paths ────────────────────────────────────────────────────────────

BASE = "/content/drive/MyDrive/Thesis_parquet"

PATHS = {
    # Inputs (Segment 1 output)
    "t_raw"          : f"{BASE}/t_df.parquet",
    "tf_raw"         : f"{BASE}/tf_df.parquet",
    "t_schema"       : f"{BASE}/t_schema.parquet",
    "tf_schema"      : f"{BASE}/tf_schema.parquet",

    # Outputs (this segment)
    "t_clean"        : f"{BASE}/t_df2.parquet",
    "t_with_missing" : f"{BASE}/t_df2_with_missing.parquet",
    "t_audit"        : f"{BASE}/t_audit.parquet",
    "tf_clean"       : f"{BASE}/tf_df2.parquet",
    "tf_with_missing": f"{BASE}/tf_df2_with_missing.parquet",
    "tf_audit"       : f"{BASE}/tf_audit.parquet",

    # Inspection outputs
    "t_char_inspect" : f"{BASE}/2_t_char_inspection.csv",
    "tf_char_inspect": f"{BASE}/2_tf_char_inspection.csv",
    "remap_t"        : f"{BASE}/2_remap_candidates_baseline.csv",
    "remap_tf"       : f"{BASE}/2_remap_candidates_followup.csv",
}

# ==============================================================================
# PHASE 2 — CORE CLEANING FUNCTION
# ==============================================================================

def clean_with_schema(df, schema_df, protected_columns, known_fixes,
                      coded_categorical_cols, case_upper_cols):
    """
    Cleans a raw-string UNOS dataframe according to its schema.

    For each column (numeric or character):
      1. Determines correct sentinel set (universal-only or all)
      2. Computes binary missingness indicator BEFORE any mutation
      3. Replaces sentinels with NaN / pd.NA
      4. Converts to correct dtype (datetime, timedelta, float32, category)
      5. Applies known value fixes and case normalisation (character only)
      6. Records conversion quality in an audit trail

    Parameters
    ----------
    df                   : raw object-dtype DataFrame
    schema_df            : schema with LABEL, TYPE, FORMAT columns
    protected_columns    : set — skip entirely (no sentinel replacement)
    known_fixes          : dict of {col: {old_val: new_val}}
    coded_categorical_cols: set — apply coded sentinels (9/98/99/998/999)
    case_upper_cols      : set — force values to uppercase

    Returns
    -------
    df_with_missing : DataFrame — cleaned data + uint8 missingness flag cols
    df_clean        : DataFrame — cleaned data only
    audit_df        : DataFrame — per-column conversion report
    """
    df = df.copy()
    missing_flags    = {}
    conversion_audit = []

    all_sentinels  = UNIVERSAL_SENTINELS + CODED_UNKNOWN_SENTINELS
    univ_only      = UNIVERSAL_SENTINELS

    # ──────────────────────────────────────────────────────────────────────
    # 2A  NUMERIC COLUMNS
    # ──────────────────────────────────────────────────────────────────────
    numeric_schema = schema_df.query("TYPE == 'Numeric'")[["LABEL", "FORMAT"]]

    for _, row in numeric_schema.iterrows():
        col = row["LABEL"]

        if col not in df.columns:
            continue
        if col in protected_columns:
            continue

        fmt = str(row["FORMAT"]).strip().upper()

        # KEY DECISION: coded sentinels only for categorical columns.
        # For continuous measurements (creatinine=9, SGOT=99, etc.),
        # applying '9'/'99' as sentinels destroys real clinical values.
        effective_sentinels = (
            all_sentinels if col in coded_categorical_cols else univ_only
        )

        # ── Missingness indicator — computed BEFORE any value mutation ────
        is_missing = (
            df[col].isna()
            | df[col].isin(effective_sentinels)
            | (df[col] == "")
        )
        miss_rate = is_missing.mean()
        # Flag columns with non-trivial missingness only.
        # Threshold 0.005 / 0.995 (not 0.01/0.99) to catch low-miss clinicals.
        if 0.005 < miss_rate < 0.995:
            missing_flags[f"{col}_missing"] = is_missing.astype("uint8")

        original_values = int((~is_missing).sum())

        # ── Sentinel → NaN ────────────────────────────────────────────────
        df[col] = df[col].replace(effective_sentinels, np.nan).replace("", np.nan)

        # ── Type conversion ───────────────────────────────────────────────
        if fmt == "MMDDYY":
            # BUG FIX (vs original): preserve raw strings BEFORE first
            # pd.to_datetime call. After the first call the column becomes
            # datetime dtype — fallback formats would receive NaT, not the
            # original strings, so they would never recover any dates.
            raw_backup = df[col].copy()

            df[col] = pd.to_datetime(raw_backup, format="%m/%d/%Y", errors="coerce")

            mask = df[col].isna() & raw_backup.notna()
            if mask.any():
                df.loc[mask, col] = pd.to_datetime(
                    raw_backup[mask], format="%m/%d/%y", errors="coerce"
                )

            mask = df[col].isna() & raw_backup.notna()
            if mask.any():
                df.loc[mask, col] = pd.to_datetime(
                    raw_backup[mask], format="%m%d%y", errors="coerce"
                )

            del raw_backup

        elif fmt == "DATETIME":
            # SAS DATETIME format: '09MAR1988:00:00:00'
            # Inspection 7: VAL_DT_LDR has this format, flagged 0% parse
            # in the audit script (which auto-detects) — explicit format here
            # is correct and handles it properly.
            raw_backup = df[col].copy()

            df[col] = pd.to_datetime(
                df[col], format="%d%b%Y:%H:%M:%S", errors="coerce"
            )

            # Fallback: rare variant with fractional seconds
            mask = df[col].isna() & raw_backup.notna()
            if mask.any():
                df.loc[mask, col] = pd.to_datetime(
                    raw_backup[mask], format="%d%b%Y:%H:%M:%S.%f", errors="coerce"
                )

            del raw_backup

        elif fmt == "TIME":
            # Transplant time, checkin times — stored as HH:MM:SS strings
            df[col] = pd.to_timedelta(df[col], errors="coerce")

        else:
            # Blank FORMAT = plain numeric (continuous or integer measurement)
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("float32")

        # ── Audit ─────────────────────────────────────────────────────────
        converted_values = int(df[col].notna().sum())
        if original_values > 0:
            loss_pct = round(
                100 * (original_values - converted_values) / original_values, 4
            )
            conversion_audit.append({
                "column"          : col,
                "type"            : "Numeric",
                "format"          : fmt,
                "original_non_null": original_values,
                "converted_non_null": converted_values,
                "loss_pct"        : loss_pct,
            })

    # ──────────────────────────────────────────────────────────────────────
    # 2B  CHARACTER COLUMNS
    # ──────────────────────────────────────────────────────────────────────
    char_schema = schema_df.query("TYPE == 'Character'")[["LABEL", "FORMAT"]]

    for _, row in char_schema.iterrows():
        col = row["LABEL"]

        if col not in df.columns:
            continue
        if col in protected_columns:
            continue

        # For character columns, apply all sentinels.
        # ABO_MAT (values '1','2','3') is the only non-protected character
        # column with purely numeric values — its values do NOT appear in
        # any sentinel list, so they survive correctly.
        is_missing = (
            df[col].isna()
            | df[col].isin(all_sentinels)
            | (df[col].astype(str).str.strip() == "")
        )
        miss_rate = is_missing.mean()
        if 0.005 < miss_rate < 0.995:
            missing_flags[f"{col}_missing"] = is_missing.astype("uint8")

        original_values = int((~is_missing).sum())

        # ── Sentinel → pd.NA, whitespace normalisation ────────────────────
        df[col] = (
            df[col]
            .replace(all_sentinels, pd.NA)
            .astype("string")
            .str.strip()
            .replace("", pd.NA)
            .str.replace(r"\s+", " ", regex=True)
        )

        # ── Known value fixes (AFTER sentinel removal) ────────────────────
        if col in known_fixes:
            df[col] = df[col].replace(known_fixes[col])

        # ── Case normalisation ────────────────────────────────────────────
        # Inspection 6: PERM_STATE in follow-up has confirmed upper/lower
        # case mix. ABO, GENDER, WL_ORG are precautionary.
        if col in case_upper_cols:
            df[col] = df[col].str.upper()

        # ── Cast to category ──────────────────────────────────────────────
        df[col] = df[col].astype("category")

        # ── Audit ─────────────────────────────────────────────────────────
        retained_values = int(df[col].notna().sum())
        if original_values > 0:
            loss_pct = round(
                100 * (original_values - retained_values) / original_values, 4
            )
            conversion_audit.append({
                "column"           : col,
                "type"             : "Character",
                "format"           : row["FORMAT"],
                "original_non_null": original_values,
                "converted_non_null": retained_values,
                "loss_pct"         : loss_pct,
            })

    # ──────────────────────────────────────────────────────────────────────
    # 2C  ASSEMBLY
    # ──────────────────────────────────────────────────────────────────────
    missing_df      = pd.DataFrame(missing_flags, index=df.index)
    df_with_missing = pd.concat([df, missing_df], axis=1)
    df_clean        = df   # same object — flag columns never added to df itself
    audit_df        = pd.DataFrame(conversion_audit)

    return df_with_missing, df_clean, audit_df



# ==============================================================================
# PHASE 3 — PHYSICAL PLAUSIBILITY CORRECTION
# ==============================================================================

def apply_plausibility_bounds(df, bounds):
    """
    Sets float32 values outside the physically valid range to NaN.
    Operates in-place equivalent (returns modified copy).

    Design choice — NaN not clip:
      Clipping (winsorizing) a BMI of 371,608 to 70 preserves the row with a
      fabricated value. Medical data with impossible values should be missing,
      not fabricated. NaN correctly propagates uncertainty downstream.
    """
    df = df.copy()
    for col, (lo, hi) in bounds.items():
        if col not in df.columns:
            continue
        if not pd.api.types.is_float_dtype(df[col]):
            continue
        mask = (df[col] < lo) | (df[col] > hi)
        n = int(mask.sum())
        if n > 0:
            df.loc[mask, col] = np.nan
            print(f"    {col:<20s} : {n:>6,} values outside [{lo}, {hi}] → NaN")
    return df



# ==============================================================================
# PHASE 4 — INSPECTION HELPER FUNCTIONS
# ==============================================================================

def inspect_character_cols(df, name, key_cols=None):
    """
    Surveys all category-dtype columns.
    Prints detailed value counts for key_cols immediately.
    Returns summary DataFrame.

    Note: check is_categorical_dtype (not is_string_dtype) because
    clean_with_schema casts all character columns to category.
    Checking string dtype after that cast would find zero columns.
    """
    cat_cols = [
        c for c in df.columns
        if pd.api.types.is_categorical_dtype(df[c])
    ]
    print(f"\n{'='*70}")
    print(f"{name}: {len(cat_cols)} category columns")
    print(f"{'='*70}")

    if key_cols:
        for col in sorted(key_cols):
            if col in df.columns:
                print(f"\n── {col} ──")
                print(df[col].value_counts(dropna=False).to_string())

    results = []
    for col in cat_cols:
        vc   = df[col].value_counts(dropna=False)
        top5 = " | ".join(
            f"{str(v) if pd.notna(v) else 'NaN'}:{c}"
            for v, c in vc.head(5).items()
        )
        results.append({
            "column"  : col,
            "n_unique": int(df[col].nunique(dropna=True)),
            "n_null"  : int(df[col].isna().sum()),
            "top_5"   : top5[:120],
        })
    return pd.DataFrame(results)


def find_remap_candidates(df, name):
    """
    Identifies category columns whose non-null values are ALL purely numeric
    strings — meaning they encode categories as integers and likely need
    human-readable label remapping before analysis.

    Uses .replace() not .map() in remap_category to preserve unmapped values.
    """
    print(f"\n{'='*70}")
    print(f"REMAP CANDIDATES — {name}")
    print(f"{'='*70}")

    candidates = []
    cat_cols = [c for c in df.columns if pd.api.types.is_categorical_dtype(df[c])]

    for col in cat_cols:
        non_null = df[col].dropna()
        if len(non_null) == 0:
            continue
        unique_strs = [str(v) for v in non_null.unique()]
        # Strip one decimal point and any leading minus sign, then check digits.
        # Correctly handles '1', '1.0', '-1', '10', '998' etc.
        all_numeric = all(
            s.replace('.', '', 1).lstrip('-').isdigit()
            for s in unique_strs if s
        )
        if all_numeric:
            candidates.append({
                "column"       : col,
                "n_unique"     : len(unique_strs),
                "unique_values": sorted(unique_strs, key=lambda x: float(x)),
            })

    if not candidates:
        print("None found — all category columns already have non-numeric labels.")
        return pd.DataFrame()

    result_df = pd.DataFrame(candidates)
    for _, row in result_df.iterrows():
        print(f"\n  {row['column']} ({row['n_unique']} unique):")
        print(f"    Values: {row['unique_values']}")

    print(f"\nTotal: {len(candidates)} candidates — review against UNOS codebook.")
    return result_df



# ==============================================================================
# PHASE 5 — EXECUTION
# ==============================================================================

# ── Load raw inputs ───────────────────────────────────────────────────────────
print("Loading raw parquets from Segment 1...")
t_df      = pd.read_parquet(PATHS["t_raw"],    engine="pyarrow")
tf_df     = pd.read_parquet(PATHS["tf_raw"],   engine="pyarrow")

t_schema  = pd.read_parquet(PATHS["t_schema"], engine="pyarrow")
tf_schema = pd.read_parquet(PATHS["tf_schema"],engine="pyarrow")

all_outputs_exist = all(os.path.exists(PATHS[k]) for k in ["t_clean", "t_with_missing", "tf_clean", "tf_with_missing"])

if USE_CACHED_DATA and all_outputs_exist:
    # ── Cache load ────────────────────────────────────────────────────────
    print("Loading cleaned data from cache (USE_CACHED_DATA=True)...")
    t_df2               = pd.read_parquet(PATHS["t_clean"],        engine="pyarrow")
    t_df2_with_missing  = pd.read_parquet(PATHS["t_with_missing"], engine="pyarrow")
    tf_df2              = pd.read_parquet(PATHS["tf_clean"],       engine="pyarrow")
    tf_df2_with_missing = pd.read_parquet(PATHS["tf_with_missing"],engine="pyarrow")
    print(f"  Baseline  : {t_df2.shape}")
    print(f"  Follow-up : {tf_df2.shape}")

else:
    # ── 5A. Core cleaning ─────────────────────────────────────────────────
    print("\nCleaning baseline (t_df)...")
    t_df2_with_missing, t_df2, t_audit = clean_with_schema(
        t_df, t_schema,
        PROTECTED_COLUMNS, KNOWN_FIXES,
        CODED_CATEGORICAL_COLS, CASE_UPPER_COLS,
    )

    print("Cleaning follow-up (tf_df)...")
    tf_df2_with_missing, tf_df2, tf_audit = clean_with_schema(
        tf_df, tf_schema,
        PROTECTED_COLUMNS, KNOWN_FIXES,
        CODED_CATEGORICAL_COLS, CASE_UPPER_COLS,
    )

    # ── 5B. Physical plausibility bounds ──────────────────────────────────
    print("\nApplying plausibility bounds to baseline...")
    t_df2              = apply_plausibility_bounds(t_df2,              PLAUSIBILITY_BOUNDS)
    t_df2_with_missing = apply_plausibility_bounds(t_df2_with_missing, PLAUSIBILITY_BOUNDS)

    print("Applying plausibility bounds to follow-up...")
    tf_df2              = apply_plausibility_bounds(tf_df2,              PLAUSIBILITY_BOUNDS)
    tf_df2_with_missing = apply_plausibility_bounds(tf_df2_with_missing, PLAUSIBILITY_BOUNDS)

    # Place this block immediately after BOTH apply_plausibility_bounds() calls.
    # Reason: missing flags are computed inside clean_with_schema() before bounds
    # are applied. Values set to NaN by plausibility correction are not reflected
    # in the existing flags. This refresh corrects that gap.
    # Confirmed by audit: BMI_TCR delta=487, BMI delta=657, HGT_CM delta=13,038.

    print("\nRefreshing missing flags for plausibility-corrected columns...")
    for col in PLAUSIBILITY_BOUNDS:
        flag_col = f"{col}_missing"
        if col in t_df2.columns and flag_col in t_df2_with_missing.columns:
            t_df2_with_missing[flag_col] = t_df2[col].isna().astype("uint8")
            print(f"    t  {col:<20s}: flag refreshed"
                  f" ({t_df2_with_missing[flag_col].sum():,} missing)")
        if col in tf_df2.columns and flag_col in tf_df2_with_missing.columns:
            tf_df2_with_missing[flag_col] = tf_df2[col].isna().astype("uint8")
            print(f"    tf {col:<20s}: flag refreshed"
                  f" ({tf_df2_with_missing[flag_col].sum():,} missing)")

    # ── 5C. Audit reports ─────────────────────────────────────────────────
    print("\n── Baseline conversion losses > 5%: ──")
    high_loss = t_audit[t_audit["loss_pct"] > 5].sort_values("loss_pct", ascending=False)
    if len(high_loss):
        print(high_loss[["column","format","original_non_null","loss_pct"]].to_string(index=False))
    else:
        print("  None.")

    print("\n── Follow-up conversion losses > 5%: ──")
    high_loss_tf = tf_audit[tf_audit["loss_pct"] > 5].sort_values("loss_pct", ascending=False)
    if len(high_loss_tf):
        print(high_loss_tf[["column","format","original_non_null","loss_pct"]].to_string(index=False))
    else:
        print("  None.")

    # ── 5D. Reset indices ─────────────────────────────────────────────────
    for frame in [t_df2, t_df2_with_missing, tf_df2, tf_df2_with_missing]:
        frame.reset_index(drop=True, inplace=True)

    # ── 5E. Intermediate save (before remaps/drops) ───────────────────────
    # These are overwritten in Phase 9 with the final clean version.
    # Saved here so Phase 6-8 can be re-run without re-cleaning if needed.
    t_df2.to_parquet(              PATHS["t_clean"],        engine="pyarrow")
    t_df2_with_missing.to_parquet( PATHS["t_with_missing"], engine="pyarrow")
    tf_df2.to_parquet(             PATHS["tf_clean"],       engine="pyarrow")
    tf_df2_with_missing.to_parquet(PATHS["tf_with_missing"],engine="pyarrow")
    t_audit.to_parquet(            PATHS["t_audit"],        engine="pyarrow")
    tf_audit.to_parquet(           PATHS["tf_audit"],       engine="pyarrow")

    print(f"\n✅ Phase 5 complete")
    print(f"   Baseline  : {t_df2.shape[0]:,} rows × {t_df2.shape[1]} cols")
    print(f"   Follow-up : {tf_df2.shape[0]:,} rows × {tf_df2.shape[1]} cols")



# ==============================================================================
# PHASE 6 — POST-CLEANING CHARACTER INSPECTION
# (Always runs — fast, verifies cleaning was correct)
# ==============================================================================

# Clinically important baseline columns to print in full
KEY_BASELINE_COLS = {
    'GENDER', 'ABO', 'ABO_MAT', 'WL_ORG',
    'TRTREJ1Y',     # 1-year rejection flag (target variable validation)
    'GRF_STAT',     # graft status (leakage — confirm it's present before drop)
    'INOTROPIC',    # confirm '0' was remapped to 'N'
    'PREV_TX', 'MALIG', 'DIABETES_DON', 'LIFE_SUP_TCR',
    'PERM_STATE',   # confirm case normalised
}

KEY_FOLLOWUP_COLS = {
    'HOSP_REJ',     # pre-2004 rejection outcome
    'GRF_STAT',
    'DIAB', 'CORART', 'PERM_STATE',
}

t_char_inspection  = inspect_character_cols(t_df2,  "BASELINE",  KEY_BASELINE_COLS)
tf_char_inspection = inspect_character_cols(tf_df2, "FOLLOW-UP", KEY_FOLLOWUP_COLS)

remap_candidates_t  = find_remap_candidates(t_df2,  "BASELINE")
remap_candidates_tf = find_remap_candidates(tf_df2, "FOLLOW-UP")

t_char_inspection.to_csv( PATHS["t_char_inspect"],  index=False)
tf_char_inspection.to_csv(PATHS["tf_char_inspect"], index=False)
remap_candidates_t.to_csv( PATHS["remap_t"],  index=False)
remap_candidates_tf.to_csv(PATHS["remap_tf"], index=False)
print("\n✅ Inspection CSVs saved.")



# ==============================================================================
# PHASE 7 — VALUE REMAPS
# ==============================================================================

def remap_category(df, col, mapping):
    """
    Remaps category-dtype column values using a dict.

    Uses .replace() not .map():
      .map()     — unmapped values become NaN (data loss)
      .replace() — unmapped values are preserved (safe)

    Breaks category dtype to object first, then re-casts.
    This avoids silent pandas CategoryIndex propagation failures where
    the new labels are not in the existing category set.
    """
    if col not in df.columns:
        return
    if not pd.api.types.is_categorical_dtype(df[col]):
        return
    df[col] = df[col].astype(object).replace(mapping).astype("category")


# Define ALL value remaps here.
# Source: inspection 6 + find_remap_candidates output.
#
# ABO_MAT is the ONLY non-protected character column with purely numeric values.
# (INIT_OPO_CTR_CODE etc. are protected; ACUTE_REJ_EPI etc. are numeric-schema.)
COLUMN_REMAPS = {
    'ABO_MAT': {
        '1': 'Identical',    # exact blood type match
        '2': 'Compatible',   # compatible but not identical
        '3': 'Incompatible', # ABO incompatible
    },
    # Add further remaps here if remap_candidates reveals new columns.
    # Common pattern: 'ETHCAT' numeric → label, 'DIAB' numeric → label, etc.
    # (ETHCAT is a numeric-schema column → converted to float32, not category,
    #  so it does NOT appear in remap candidates. Recode it in Segment 3.)
}

for col, mapping in COLUMN_REMAPS.items():
    remap_category(t_df2,              col, mapping)
    remap_category(t_df2_with_missing, col, mapping)
    remap_category(tf_df2,             col, mapping)
    remap_category(tf_df2_with_missing,col, mapping)

    if col in t_df2.columns:
        print(f"\nBaseline {col} after remap:")
        print(t_df2[col].value_counts(dropna=False).to_string())



# ==============================================================================
# PHASE 8 — FINAL SAVE & ROUND-TRIP VERIFICATION
# ==============================================================================

for frame in [t_df2, t_df2_with_missing, tf_df2, tf_df2_with_missing]:
    frame.reset_index(drop=True, inplace=True)

t_df2.to_parquet(              PATHS["t_clean"],        engine="pyarrow")
t_df2_with_missing.to_parquet( PATHS["t_with_missing"], engine="pyarrow")
tf_df2.to_parquet(             PATHS["tf_clean"],       engine="pyarrow")
tf_df2_with_missing.to_parquet(PATHS["tf_with_missing"],engine="pyarrow")

# ── Round-trip verification ────────────────────────────────────────────────────
t_verify  = pd.read_parquet(PATHS["t_clean"],  engine="pyarrow")
tf_verify = pd.read_parquet(PATHS["tf_clean"], engine="pyarrow")

print("\n" + "="*70)
print("SEGMENT 2 COMPLETE — FINAL VERIFICATION")
print("="*70)

print(f"\n  Baseline  : {t_verify.shape[0]:,} rows × {t_verify.shape[1]} cols")
print(f"  Follow-up : {tf_verify.shape[0]:,} rows × {tf_verify.shape[1]} cols")

print(f"\n  Dtype distribution — Baseline:")
print(t_verify.dtypes.value_counts().to_string())

print(f"\n  Dtype distribution — Follow-up:")
print(tf_verify.dtypes.value_counts().to_string())

# Key column presence checks
print(f"\n  Key ID columns:")
for col in ['TRR_ID_CODE', 'PT_CODE', 'WL_ID_CODE']:
    present = col in t_verify.columns
    print(f"    {col:<20s}: {'✓ present' if present else '✗ MISSING — CRITICAL ERROR'}")

# Plausibility verification
print(f"\n  Plausibility check — INIT_AGE:")
if 'INIT_AGE' in t_verify.columns:
    s = t_verify['INIT_AGE']
    print(f"    min={s.min():.0f}  max={s.max():.0f}  "
          f"null={s.isna().sum():,}  (expect min≥0)")

print(f"\n  Plausibility check — BMI_TCR:")
if 'BMI_TCR' in t_verify.columns:
    s = t_verify['BMI_TCR']
    print(f"    min={s.min():.1f}  max={s.max():.1f}  "
          f"null={s.isna().sum():,}  (expect max≤70)")

# ABO_MAT remap verification
print(f"\n  ABO_MAT remap verification:")
if 'ABO_MAT' in t_verify.columns:
    print(t_verify['ABO_MAT'].value_counts(dropna=False).to_string())
    assert 'Identical' in t_verify['ABO_MAT'].cat.categories.tolist(), \
        "ERROR: ABO_MAT remap failed — numeric codes still present"

# INOTROPIC fix verification
print(f"\n  INOTROPIC value fix verification (expect no '0'):")
if 'INOTROPIC' in t_verify.columns:
    vc = t_verify['INOTROPIC'].value_counts(dropna=False)
    print(vc.to_string())
    assert '0' not in vc.index.tolist(), \
        "ERROR: INOTROPIC still has '0' values — KNOWN_FIXES not applied"

# PERM_STATE case verification (follow-up)
print(f"\n  PERM_STATE case verification — follow-up (expect uppercase only):")
if 'PERM_STATE' in tf_verify.columns:
    unique_vals = tf_verify['PERM_STATE'].dropna().unique().tolist()
    has_lower = any(str(v) != str(v).upper() for v in unique_vals)
    print(f"    Mixed case present: {'YES — ERROR' if has_lower else 'No ✓'}")

# Target variable spot-check (validation against TRTREJ1Y)
print(f"\n  TRTREJ1Y (1-year rejection flag — use to validate outcome in Seg 3):")
if 'TRTREJ1Y' in t_verify.columns:
    print(t_verify['TRTREJ1Y'].value_counts(dropna=False).to_string())
    print(f"    (Expected approx: Y~27,263  N~78,012  from inspection 6)")

print(f"\n✅ Segment 2 verified. Parquets ready for Segment 3 cohort filtering.")

Loading raw parquets from Segment 1...

Cleaning baseline (t_df)...
Cleaning follow-up (tf_df)...

Applying plausibility bounds to baseline...
    INIT_AGE             :     83 values outside [0, 100] → NaN
    BMI_TCR              :    487 values outside [10, 70] → NaN
    HGT_CM_TCR           : 10,612 values outside [100, 230] → NaN
    WGT_KG_TCR           : 12,339 values outside [20, 300] → NaN
    INIT_AGE             :     83 values outside [0, 100] → NaN
    BMI_TCR              :    487 values outside [10, 70] → NaN
    HGT_CM_TCR           : 10,612 values outside [100, 230] → NaN
    WGT_KG_TCR           : 12,339 values outside [20, 300] → NaN
Applying plausibility bounds to follow-up...
    BMI                  :    657 values outside [10, 70] → NaN
    HGT_CM               : 13,038 values outside [100, 230] → NaN
    WGT_KG               : 21,949 values outside [20, 300] → NaN
    BMI                  :    657 values outside [10, 70] → NaN
    HGT_CM               : 13,038 values outside [100, 230] → NaN
    WGT_KG               : 21,949 values outside [20, 300] → NaN

Refreshing missing flags for plausibility-corrected columns...
    t  BMI_TCR             : flag refreshed (7,557 missing)
    tf BMI                 : flag refreshed (918,632 missing)
    t  HGT_CM_TCR          : flag refreshed (17,851 missing)
    t  WGT_KG_TCR          : flag refreshed (18,421 missing)
    tf HGT_CM              : flag refreshed (927,035 missing)
    tf WGT_KG              : flag refreshed (852,664 missing)

── Baseline conversion losses > 5%: ──
  None.

── Follow-up conversion losses > 5%: ──
  None.

✅ Phase 5 complete
   Baseline  : 234,975 rows × 625 cols
   Follow-up : 1,156,190 rows × 81 cols

======================================================================
BASELINE: 230 category columns
======================================================================

── ABO ──
ABO
O       105958
A        89265
B        29430
AB        9643
A1         518
A2          91
A1B         42
A2B         23
<NA>         5

── ABO_MAT ──
ABO_MAT
1       138817
<NA>     75150
2        20367
3          641

── DIABETES_DON ──
DIABETES_DON
N       136393
<NA>     91902
Y         6680

── GENDER ──
GENDER
M    155260
F     79715

── GRF_STAT ──
GRF_STAT
Y       111440
<NA>    103526
N        20009

── INOTROPIC ──
INOTROPIC
<NA>    214926
N        11406
Y         8643

── LIFE_SUP_TCR ──
LIFE_SUP_TCR
N       146778
Y        78665
<NA>      9532

── MALIG ──
MALIG
N       131112
<NA>     93490
Y        10373

── PERM_STATE ──
PERM_STATE
CA      23514
TX      19450
FL      14043
NY      13942
PA      12679
IL       9780
OH       8941
NJ       7528
NC       7451
MI       7414
VA       6715
IN       5721
<NA>     5513
GA       5507
WI       5198
MD       4990
TN       4801
ZZ       4740
MO       4587
AZ       4360
MA       4241
MN       4199
KY       3998
LA       3940
WA       3845
CO       3001
SC       2942
CT       2815
OK       2684
AL       2524
IA       2333
KS       2116
AR       1986
MS       1964
OR       1898
UT       1573
WV       1503
NE       1422
NV       1183
NM        922
DE        897
ME        882
NH        771
ID        753
RI        628
SD        503
MT        440
DC        416
PR        362
HI        350
VT        343
WY        327
AK        316
VI         20
GU          2
BC          1
MP          1

── PREV_TX ──
PREV_TX
N       154547
<NA>     75144
Y         5284

── TRTREJ1Y ──
TRTREJ1Y
<NA>    129700
N        78012
Y        27263

── WL_ORG ──
WL_ORG
HR      149578
LU       81169
HL        3799
<NA>       429

======================================================================
FOLLOW-UP: 27 category columns
======================================================================

── CORART ──
CORART
N       555990
<NA>    500714
Y        99486

── DIAB ──
DIAB
N       571401
<NA>    511708
Y        73081

── GRF_STAT ──
GRF_STAT
Y       901389
<NA>    236893
N        17908

── HOSP_REJ ──
HOSP_REJ
<NA>    944422
N       174982
Y        36786

── PERM_STATE ──
PERM_STATE
<NA>    203029
CA      100874
TX       78170
FL       64528
PA       53487
NY       53278
IL       38553
OH       37139
NC       36331
NJ       31900
MI       31800
VA       26140
IN       24372
WI       23737
GA       22973
WA       22036
MO       21189
TN       20546
AZ       20516
MN       18938
MD       18333
MA       17622
KY       14293
CO       13633
SC       13607
LA       12585
CT       11129
IA       10130
AL        9957
OK        9291
OR        9276
KS        8913
UT        8749
AR        8495
MS        7911
WV        6720
NE        5756
NV        4881
DE        3981
ID        3885
NM        3660
NH        3640
ME        3436
RI        2635
SD        2323
MT        2233
PR        2075
WY        1682
HI        1341
VT        1317
DC        1169
AK        1156
ZZ         742
VI          69
AS          21
GU           6
MP           2

======================================================================
REMAP CANDIDATES — BASELINE
======================================================================

  ABO_MAT (3 unique):
    Values: ['1', '2', '3']

Total: 1 candidates — review against UNOS codebook.

======================================================================
REMAP CANDIDATES — FOLLOW-UP
======================================================================

  FOL_CTR_CODE (235 unique):
    Values: ['00031', '00124', '00248', '00279', '00310', '00372', '00403', '00465', '00651', '00682', '00868', '00899', '00961', '01240', '01271', '01395', '01612', '01674', '01860', '01953', '01984', '02108', '02201', '02418', '02573', '02666', '02697', '02728', '02883', '02976', '03193', '03379', '03410', '03503', '03534', '03627', '03751', '03813', '03906', '04154', '04464', '04557', '04712', '04774', '04867', '04960', '05053', '05084', '05332', '05394', '05487', '05549', '05642', '05673', '05704', '05890', '06014', '06107', '06231', '06293', '06417', '06510', '06572', '06603', '06727', '06820', '06975', '07161', '07223', '07347', '07471', '07533', '07719', '07750', '07905', '08277', '08339', '08401', '08463', '08494', '08587', '08742', '09021', '09114', '09176', '09269', '09362', '09548', '09827', '09951', '10044', '10478', '10571', '10881', '11067', '11129', '11191', '11253', '11470', '11532', '11718', '11749', '11935', '12028', '12152', '12245', '12524', '12586', '12834', '12896', '12958', '13051', '13237', '13268', '13454', '13485', '13609', '13640', '13795', '13826', '13857', '13919', '14074', '14229', '14415', '14477', '14539', '14694', '14880', '14942', '15159', '15283', '15407', '15438', '15531', '15593', '15717', '15748', '15810', '15872', '16213', '16244', '16430', '16523', '16616', '16678', '16709', '16864', '16957', '17081', '17112', '17391', '17546', '17608', '17918', '18104', '18135', '18166', '18228', '18259', '18352', '18414', '18507', '18755', '18786', '18972', '19034', '19065', '19096', '19344', '19437', '19468', '19499', '19530', '19592', '19716', '19964', '20274', '20522', '20553', '20677', '20708', '20863', '21018', '21080', '21266', '21359', '21514', '21731', '21762', '21793', '21917', '22072', '22196', '22289', '22320', '22382', '22444', '22568', '22692', '22878', '23033', '23064', '23312', '23436', '23467', '23591', '23622', '23808', '23839', '23901', '24025', '24087', '24304', '24335', '24366', '24521', '24552', '24707', '24769', '24800', '25110', '25420', '25518', '25545', '25590', '25644', '25657', '25711', '25721', '25778', '25841', '25861', '26505', '26537']

Total: 1 candidates — review against UNOS codebook.

✅ Inspection CSVs saved.

Baseline ABO_MAT after remap:
ABO_MAT
Identical       138817
NaN              75150
Compatible       20367
Incompatible       641

======================================================================
SEGMENT 2 COMPLETE — FINAL VERIFICATION
======================================================================

  Baseline  : 234,975 rows × 625 cols
  Follow-up : 1,156,190 rows × 81 cols

  Dtype distribution — Baseline:
float32            333
category           151
object              29
datetime64[ns]      28
category            23
category            11
category             9
timedelta64[ns]      5
category             4
category             3
category             2
category             2
category             2
category             2
category             2
category             2
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1
category             1

  Dtype distribution — Follow-up:
float32           39
category          15
datetime64[ns]    12
category           7
object             3
category           1
category           1
category           1
category           1
category           1

  Key ID columns:
    TRR_ID_CODE         : ✓ present
    PT_CODE             : ✓ present
    WL_ID_CODE          : ✓ present

  Plausibility check — INIT_AGE:
    min=0  max=87  null=519  (expect min≥0)

  Plausibility check — BMI_TCR:
    min=10.0  max=69.8  null=7,557  (expect max≤70)

  ABO_MAT remap verification:
ABO_MAT
Identical       138817
NaN              75150
Compatible       20367
Incompatible       641

  INOTROPIC value fix verification (expect no '0'):
INOTROPIC
NaN    214926
N       11406
Y        8643

  PERM_STATE case verification — follow-up (expect uppercase only):
    Mixed case present: No ✓

  TRTREJ1Y (1-year rejection flag — use to validate outcome in Seg 3):
TRTREJ1Y
NaN    129700
N       78012
Y       27263
    (Expected approx: Y~27,263  N~78,012  from inspection 6)

✅ Segment 2 verified. Parquets ready for Segment 3 cohort filtering.

# Segment 2 Complete

In [ ]:
t_df2_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df2.parquet"
tf_df2_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df2.parquet"
t_df2_with_missing_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df2_with_missing.parquet"
tf_df2_with_missing_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df2_with_missing.parquet"

t_df2 = pd.read_parquet(t_df2_parquet_path, engine='pyarrow')
tf_df2 = pd.read_parquet(tf_df2_parquet_path, engine='pyarrow')
t_df2_with_missing = pd.read_parquet(t_df2_with_missing_parquet_path, engine='pyarrow')
tf_df2_with_missing = pd.read_parquet(tf_df2_with_missing_parquet_path, engine='pyarrow')

print("t_df2 (2: Missing-Value Handled - no missing):", t_df2.shape)
print("tf_df2 (2: Missing-Value Handled - no missing):", tf_df2.shape)

t_df2 (2: Missing-Value Handled - no missing): (234975, 625)
tf_df2 (2: Missing-Value Handled - no missing): (1156190, 81)

In [ ]:
# t_df2.to_csv('2.t_df2.csv', index=False)
# t_df2_with_missing.to_csv('2.t_df2_with_missing.csv', index=False)

# tf_df2.to_csv('2.tf_df2.csv', index=False)
# tf_df2_with_missing.to_csv('2.tf_df2_with_missing.csv', index=False)

# Segment 3: COHORT DEFINITION

In [ ]:
# =============================================================================
# SEGMENT 3 — COHORT DEFINITION
# =============================================================================
#
# PURPOSE
# -------
# Filter the cleaned UNOS tables to the final study cohort, remove all
# post-transplant leakage columns, drop near-zero variance columns
# (re-evaluated after cohort filter), and align follow-up tables.
#
# COHORT CRITERIA (FROZEN — do not change after this segment)
#   Inclusion : AGE ≥ 18 at transplant, heart-only (WL_ORG='HR'),
#               TX_DATE 2000-01-01 – 2023-12-31
#   Exclusion : Waitlist-only (TX_DATE null), multi-organ (MULTIORG='Y'),
#               re-transplants (PREV_TX_ANY='Y' or NUM_PREV_TX > 0),
#               unknown transplant age
#
# TEMPORAL SPLIT NOTE
#   Train / test split (≤ 2018 / 2019–2023) is applied in Segment 4.
#   This segment retains ALL cohort years in one table.
#
# UPPER BOUND RATIONALE
#   Patients transplanted in 2024+ cannot have complete 1-year follow-up
#   by the data extraction date. 2023-12-31 is the "lag fix" boundary
#   identified in Inspection 10.
#   Horizon-specific cutoffs (≤ 2021 for 3-year, ≤ 2019 for 5-year) are
#   applied during outcome variable construction in Segment 4.
#
# INPUTS  : t_df2, tf_df2   (Segment 2 parquets)
# OUTPUTS : t_df3, tf_df3   (cohort-filtered, leakage-removed)
#           trtrej1y_val.parquet  (saved separately for Segment 4)
#           pra_source
#           SUS_COLS
# =============================================================================

import os
import numpy as np
import pandas as pd

USE_CACHED_DATA = False   # ← set True only after first verified run

# Paths
t_df2_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df2.parquet"
tf_df2_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df2.parquet"

t_df3_parquet_path = "/content/drive/MyDrive/Thesis_parquet/t_df3.parquet"
tf_df3_parquet_path = "/content/drive/MyDrive/Thesis_parquet/tf_df3.parquet"

trtrej1y_val_path = "/content/drive/MyDrive/Thesis_parquet/trtrej1y_validation.parquet"
pra_source_path = "/content/drive/MyDrive/Thesis_parquet/pra_source.parquet"
SUS_COLS_path = "/content/drive/MyDrive/Thesis_parquet/SUS_COLS.parquet"

if USE_CACHED_DATA and os.path.exists(t_df3_parquet_path) and os.path.exists(tf_df3_parquet_path):
    # Load cached parquet
    t_df3 = pd.read_parquet(t_df3_parquet_path, engine='pyarrow')
    tf_df3 = pd.read_parquet(tf_df3_parquet_path, engine='pyarrow')

    # Segment 2 verdict: 29 baseline + 2 follow-up object columns lose
    # CategoricalDtype on parquet serialisation. Re-cast before any operation.

    for label, frame in [("t_df3", t_df3), ("tf_df3", tf_df3)]:
        obj_cols = [
            c for c in frame.columns
            if frame[c].dtype == object and c not in PROTECTED_COLUMNS
        ]
        for col in obj_cols:
            frame[col] = frame[col].astype("category")
        if obj_cols:
            print(f"  {label}: re-cast {len(obj_cols)} object → category")

    print(f"  t_df3  : {t_df3.shape}")
    print(f"  tf_df3 : {tf_df3.shape}")



else:
    print("Loading Segment 2 parquets...")
    t_df2 = pd.read_parquet(t_df2_parquet_path, engine='pyarrow')
    tf_df2 = pd.read_parquet(tf_df2_parquet_path, engine='pyarrow')



    # =========================================================================
    # PHASE 1 — ROW FILTERS
    # =========================================================================

    print("\n" + "="*70)
    print("PHASE 1 — Cohort row filters")
    print("="*70)
    print(f"  Start                               : {len(t_df2):>7,}")

    # ── 1A. Transplanted patients only ───────────────────────────────────────
    # TX_DATE is NaT for waitlist-only patients (never received a transplant).
    # They have no transplant event to compute outcomes for.
    n = len(t_df2)
    t_df2 = t_df2[t_df2['TX_DATE'].notna()].copy()
    print(f"  After TX_DATE not null              : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} waitlist-only)")

    # ── 1B. Adult recipients (age ≥ 18 at transplant) ───────────────────────
    # AGE = age at transplant time (float32 after Segment 2 cleaning).
    # INIT_AGE = age at listing — a different column; not used here.
    # NaN ages evaluate as False in comparisons → automatically excluded.
    # This removes pediatric patients AND patients with unknown age.
    n = len(t_df2)
    n_null_age     = int(t_df2['AGE'].isna().sum())
    n_pediatric    = int((t_df2['AGE'] < 18).sum())
    t_df2 = t_df2[t_df2['AGE'] >= 18].copy()
    print(f"  After AGE ≥ 18                      : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,}: {n_pediatric:,} pediatric"
          f" + {n_null_age:,} age-unknown)")

    # ── 1C. Heart-only transplants ───────────────────────────────────────────
    # WL_ORG = 'HR' (heart) is the waitlist organ code. Lung (LU) and
    # heart-lung (HL) waitlist registrations are excluded.
    n = len(t_df2)
    print(f"\n  WL_ORG distribution (pre-filter):")
    print(t_df2['WL_ORG'].value_counts(dropna=False).to_frame().to_string())
    t_df2 = t_df2[t_df2['WL_ORG'] == 'HR'].copy()
    print(f"\n  After WL_ORG == 'HR'                : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} non-heart)")

    # ── 1D. Single-organ transplant only ────────────────────────────────────
    # MULTIORG == 'Y' flags patients who received a heart + other organ(s)
    # simultaneously (e.g., heart-kidney). These have different immunological
    # trajectories and are excluded in all major UNOS heart rejection studies.
    # Encoding: 'Y' = multi-organ; NaN = single organ (flag not set).
    n = len(t_df2)
    n_multiorg = 0
    if 'MULTIORG' in t_df2.columns:
        n_multiorg = int((t_df2['MULTIORG'] == 'Y').sum())
        t_df2 = t_df2[t_df2['MULTIORG'] != 'Y'].copy()
    else:
        print("  WARNING: MULTIORG column not found — multi-organ exclusion skipped.")
    print(f"  After single-organ filter           : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} multi-organ [MULTIORG='Y': {n_multiorg:,}])")

    # ── 1E. First transplant only (exclude re-transplants) ──────────────────
    # All major UNOS heart rejection studies exclude re-transplant patients.
    # Rationale: sensitised immune history makes rejection biology different.
    #
    # Three complementary flags — OR logic to be conservative:
    #   PREV_TX_ANY : 'Y' = any previous transplant (any organ)
    #   PREV_TX     : 'Y' = previous transplant (any organ, slightly different coding)
    #   NUM_PREV_TX : > 0 = count of previous heart transplants
    #
    # NaN in any flag is treated as "no previous transplant" (inclusive default).
    n = len(t_df2)
    retx_mask = pd.Series(False, index=t_df2.index)
    if 'PREV_TX_ANY' in t_df2.columns:
        retx_mask |= (t_df2['PREV_TX_ANY'] == 'Y')
    if 'PREV_TX' in t_df2.columns:
        retx_mask |= (t_df2['PREV_TX'] == 'Y')
    if 'NUM_PREV_TX' in t_df2.columns:
        retx_mask |= (t_df2['NUM_PREV_TX'].fillna(0) > 0)
    t_df2 = t_df2[~retx_mask].copy()
    print(f"  After re-transplant exclusion       : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} re-transplants)")

    # ── 1F. Modern era — lower bound ─────────────────────────────────────────
    # Pre-2000: different immunosuppression protocols, older HLA typing methods,
    # different UNOS allocation policy. Consistent with Killian et al. and
    # all comparable published studies using UNOS data.
    n = len(t_df2)
    t_df2 = t_df2[t_df2['TX_DATE'] >= '2000-01-01'].copy()
    print(f"  After TX_DATE ≥ 2000-01-01          : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} pre-2000)")

    # ── 1G. Upper bound lag fix ───────────────────────────────────────────────
    # Patients transplanted in 2024/2025 cannot have complete 1-year follow-up
    # by the data collection date (~late 2024/early 2025).
    # Cap at 2023-12-31 — consistent with Inspection 10 "lag fix" boundary.
    # IMPORTANT: This is the COHORT upper bound (1-year outcome coverage).
    # The 3-year and 5-year outcome analyses are further restricted in Segment 4:
    #   3-year outcomes : cohort TX_DATE ≤ 2021-12-31
    #   5-year outcomes : cohort TX_DATE ≤ 2019-12-31
    # Those subsets are derived from tf_df3 during outcome construction —
    # not applied here to avoid creating multiple partial baseline tables.
    n = len(t_df2)
    t_df2 = t_df2[t_df2['TX_DATE'] <= '2023-12-31'].copy()
    print(f"  After TX_DATE ≤ 2023-12-31          : {len(t_df2):>7,}"
          f"  (−{n - len(t_df2):,} post-2023)")

    print(f"\n  ── FINAL COHORT : {len(t_df2):,} patients ──")
    print(f"     Columns remaining : {t_df2.shape[1]}")

    # PHASE 1 ASSERTIONS

    assert t_df2['TX_DATE'].isna().sum() == 0, "TX_DATE nulls remain after filter"
    assert float(t_df2['AGE'].min()) >= 18.0,  "Under-18 patient found in cohort"
    assert (t_df2['WL_ORG'] == 'HR').all(),    "Non-heart patient in cohort"
    assert t_df2['TX_DATE'].min() >= pd.Timestamp('2000-01-01'), "Pre-2000 transplant found"
    assert t_df2['TX_DATE'].max() <= pd.Timestamp('2023-12-31'), "Post-2023 transplant found"
    if 'MULTIORG' in t_df2.columns:
        assert (t_df2['MULTIORG'] == 'Y').sum() == 0, "Multi-organ patient in cohort"
    if 'PREV_TX_ANY' in t_df2.columns:
        assert (t_df2['PREV_TX_ANY'] == 'Y').sum() == 0, "Re-transplant patient in cohort"

    print("\n  ✓ All PHASE 1 assertions passed.")





    # =========================================================================
    # PHASE 2 — Column FILTERS
    # =========================================================================

    print("\n" + "="*70)
    print("PHASE 2 — Cohort column filters")
    print("="*70)

    print(f"baseline columns: {len(t_df2.columns)}")

    # Protected columns — must not be re-cast or dropped by NZV logic
    PROTECTED_COLUMNS = ['PT_CODE', 'DONOR_ID', 'WL_ID_CODE', 'INIT_OPO_CTR_CODE', 'END_OPO_CTR_CODE', 'LISTING_CTR_CODE']



    # AT_TX_COLS is the list of variables that are from TRR and/or TRR-related variables. But their description is "@ TRANSPLANT" or "BETWEEN LISTING AND TRANSPLANT"
    # Only blanks for 'VAR END DATE', and 'is before or equal to 30/6/2004' for 'VAR START DATE'
    # TBILI is a flagship predictor cited by both Ayers 2021 and Kampaktsis 2021
    # ACADEMIC_LEVEL_TRR, ACADEMIC_PRG_TRR (school-progress constructs, near-meaningless for age≥18 patients — will self-resolve via missingness anyway, no harm dropping now)
    # FEV1_TRR, FVC_TRR, PCO2_TRR (pulmonary function tests, more central to lung transplantation than isolated heart, but not impossible for a heart candidate's pre-op workup — let t_df3's actual missingness rate decide rather than guessing)
    # PERM_STATE_TRR (geographic, possible SES/distance proxy, low stakes either way)
    # TX_DATE. It must be force-retained regardless of any "keep as feature" debate, exactly as we agreed three turns ago

    AT_TX_COLS = ['ACADEMIC_LEVEL_TRR', 'ACADEMIC_PRG_TRR', 'DIAL_AFTER_LIST', 'ECMO_TRR', 'END_STAT', 'EBV_SEROSTATUS', 'FEV1_TRR', 'FUNC_STAT_TRR', 'FVC_TRR', 'HCV_SEROSTATUS', 'HEMO_CO_TRR', 'HEMO_PA_DIA_TRR', 'HEMO_PA_MN_TRR',
                  'HEMO_PCW_TRR', 'HEMO_SYS_TRR', 'HIV_SEROSTATUS', 'IABP_TRR', 'MED_COND_TRR', 'OTH_LIFE_SUP_TRR', 'PCO2_TRR', 'PERM_STATE_TRR', 'PGE_TRR',
                  'PRI_PAYMENT_TRR', 'STERNOTOMY_TRR', 'STEROID', 'TBILI', 'TRANSFUSIONS',
                  'VENT_TIMEFRAME_TRR', 'VENT_SUPPORT_TRR', 'VENT_SUPPORT_AFTER_LIST', 'VENTILATOR_TRR', 'WORK_INCOME_TRR', 'LIFE_SUP_TRR']



    # BASELINE_COLS = No TRR and/or TRR-related variables
    # Only blanks for 'VAR END DATE', and 'is before or equal to 30/6/2004' for 'VAR START DATE'

    BASELINE_COLS = ['ABN_CONGEN_DON', 'ABN_LVH_DON', 'ABN_VALVES_DON', 'ABO', 'ABO_DON', 'ABO_MAT', 'ACADEMIC_LEVEL_TCR', 'ACADEMIC_PRG_TCR', 'ACTIVATE_DATE', 'AGE', 'AGE_DON', 'ALCOHOL_HEAVY_DON', 'ANTIHYPE_DON', 'ARGININE_DON',
                      'BIOPSY_DGN', 'BLOOD_INF_DON', 'BMI_TCR', 'BRONCHO_LT_DON', 'BRONCHO_RT_DON', 'BUN_DON', 'BW4', 'BW6', 'C1', 'C2', 'CANCER_FREE_INT_DON', 'CANCER_SITE_DON', 'CARD_IDX_INIT_DON', 'CARD_IDX_POST_DON',
                      'CARDARREST_NEURO', 'CARDIAC_OUTPUT_CATH_INIT_DON', 'CARDIAC_OUTPUT_CATH_POST_DON', 'CDC_RISK_HIV_DON', 'CHEST_XRAY_DON', 'CIG_USE', 'CITIZENSHIP', 'CITIZENSHIP_DON', 'CLIN_INFECT_DON',
                      'COD_CAD_DON', 'COD_WL', 'CONTIN_CIG_DON', 'CONTIN_COCAINE_DON', 'CONTIN_OTH_DRUG_DON', 'CONTROLLED', 'CORONARY_ANGIO',
                      'CREAT_DON', 'CRSMATCH_DONE', 'CVP_CATH_INIT_DON', 'CVP_CATH_POST_DON',
                      'DA1', 'DA2', 'DB1', 'DB2', 'DDAVP_DON', 'DDR1', 'DDR2', 'DEATH_CIRCUM_DON', 'DEATH_DATE', 'DEATH_MECH_DON', 'DIAB', 'DIAG', 'DIABDUR_DON',
                      'DIABETES_DON', 'DIAL_PRIOR_TX', 'DIAL_TY_TCR', 'DIAST_PA_CATH_INIT_DON', 'DIAST_PA_CATH_POST_DON', 'DIET_DON', 'DISTANCE', 'DIURETICS_DON', 'DON_RETYP', 'DQ1', 'DQ2', 'DR51', 'DR51_2', 'DR52', 'DR52_2', 'DR53', 'DR53_2',
                      'EBV_IGG_CAD_DON', 'EBV_IGM_CAD_DON', 'ECD_DONOR', 'ECMO_TCR', 'EDUCATION', 'END_DATE', 'ETHNICITY', 'EXERCISE_O2', 'EXTRACRANIAL_CANCER_DON',
                      'FUNC_STAT_TCR', 'GENDER', 'GENDER_DON',
                      'HEMATOCRIT_DON', 'HEMO_CO_TCR', 'HEMO_PA_DIA_TCR', 'HEMO_PA_MN_TCR', 'HEMO_PCW_TCR', 'HEMO_SYS_TCR', 'HEP_C_ANTI_DON', 'HEPARIN_DON', 'HGT_CM_TCR', 'HGT_CM_CALC', 'HGT_CM_DON_CALC',
                      'HIST_CANCER_DON', 'HIST_CIG_DON', 'HIST_COCAINE_DON', 'HIST_DIABETES_DON', 'HIST_HYPERTENS_DON', 'HIST_INSULIN_DEP_DON', 'HIST_MI', 'HIST_OTH_DRUG_DON', 'HLAMIS', 'HOME_STATE_DON', 'HTLV2_OLD_DON', 'HYPERTENS_DUR_DON',
                      'IABP_TCR', 'ICU', 'IMPL_DEFIBRIL', 'INFECT_IV_DRUG_TRR', 'INHALED_NO', 'INHALED_NO_TCR',
                      'INIT_AGE', 'INIT_BMI_CALC', 'INIT_DATE', 'INIT_HGT_CM_CALC', 'INIT_O2', 'INIT_STAT',
                      'INO_PROCURE_AGENT_1', 'INO_PROCURE_AGENT_2', 'INO_PROCURE_AGENT_3', 'INOTROP_SUPPORT_DON', 'INOTROP_VASO_CO_TCR', 'INOTROP_VASO_DIA_TCR', 'INOTROP_VASO_MN_TCR', 'INOTROP_VASO_PCW_TCR', 'INOTROP_VASO_SYS_TCR', 'INOTROPES_TCR',
                      'INSULIN_DON', 'INSULIN_DUR_DON', 'INTRACRANIAL_CANCER_DON', 'INUTERO', 'ISCHTIME',
                      'LIFE_SUP_TCR', 'LISTYR', 'LV_EJECT', 'LV_EJECT_METH',
                      'MALIG', 'MALIG_TCR', 'MALIG_TY', 'MALIG_TY_TCR', 'MAP_INIT_DON', 'MAP_POST_DON',
                      'NON_HRT_DON', 'ONVENT', 'OTH_LIFE_SUP_TCR', 'OTHER_HYPERTENS_MED_DON', 'OTHER_INF_DON', 'PALL_SURG_TCR', 'PCO2_DON', 'PCWP_INIT_DON', 'PCWP_POST_DON', 'PERM_STATE', 'PH_DON', 'PO2', 'PO2_DONE_DON', 'PO2_FIO2_DON',
                      'PRI_PAYMENT_TCR', 'PRIOR_CARD_SURG_TCR', 'PRIOR_CARD_SURG_TYPE_TCR', 'PRIOR_CONGEN_TCR', 'PRIOR_STERNO_TCR', 'PRIOR_THORACO_TCR', 'PROC_TY_HR', 'PROS_INFUS_TCR', 'PROSTACYCLIN_TCR', 'PROTEIN_URINE',
                      'PT_DIURETICS_DON', 'PT_STEROIDS_DON', 'PT_T3_DON', 'PT_T4_DON', 'PULM_CATH_DON', 'PULM_INF_DON',
                      'RA1', 'RA2', 'RB1', 'RB2', 'RDR1', 'RDR2', 'RECOV_OUT_US', 'RECOVERY_DATE_DON', 'REFERRAL_DATE', 'REGION', 'RESIST_INF', 'RESUSCIT_DUR',
                      'SGOT_DON', 'SGPT_DON', 'SHARE_TY', 'SINGLE_VENT_PHYSIOLOGY_TCR', 'SKIN_CANCER_DON', 'SUD_DEATH', 'SVR_INIT_DON', 'SVR_POST_DON',
                      'SYST_PA_CATH_INIT_DON', 'SYST_PA_CATH_POST_DON', 'TAH', 'TATTOOS', 'TBILI_DON', 'TCR_CDC_GROWTH_BMI', 'TCR_CDC_GROWTH_HGT', 'TCR_CDC_GROWTH_WGT', 'TCR_DGN', 'TCR_DUR_ABSTAIN', 'THORACIC_DGN', 'TOT_SERUM_ALBUM',
                      'TRANSFUS_TERM_DON', 'TRANSPLANT_COUNTRY', 'TX_PROCEDUR_TY', 'URINE_INF_DON', 'VAD_BRAND1_TCR', 'VAD_BRAND2_TCR', 'VAD_DEVICE_TY_TCR', 'VAS', 'VASODIL_DON', 'VDRL_DON', 'VENTILATOR_TCR', 'VESSELS_50STEN',
                      'WALL_ABN_GLOB_DON', 'WALL_ABN_SEG_DON', 'WGT_KG_CALC', 'WGT_KG_DON_CALC', 'WGT_KG_TCR', 'WORK_INCOME_TCR', 'YR_ENTRY_US_TCR', 'HBSAB_DON', 'TRR_ID_CODE']





    # REMAINING_COLS = Other variables that are necessary to be included in the main df
    # Only blanks for 'VAR END DATE', and only blanks for 'VAR START DATE'
    REMAINING_COLS = ['AMIS', 'BMI_CALC', 'BMI_DON_CALC', 'BMIS', 'CALC_LAS_LISTDATE', 'CORRECT_SURG_TCR', 'CREAT_TRR', 'DAYSWAIT_CHRON', 'DRMIS',
                      'END_BMI_CALC', 'END_O2', 'ETHCAT', 'ETHCAT_DON', 'TX_TYPE', 'HBV_CORE', 'HBV_CORE_DON', 'HBV_SUR_ANTIGEN', 'HBV_SUR_ANTIGEN_DON']

    # Keeping COHORT_COLS for cohort definition
    COHORT_COLS = ['PREV_TX_ANY', 'PREV_TX', 'NUM_PREV_TX', 'MULTIORG', 'TX_DATE', 'WL_ORG']

    # My own filter would erase the raw materials for sensitization_severity
    # Pull these out BEFORE primary selection touches anything. They will never appear in the final feature matrix on their own;

    # they exist solely to construct peak_sensitization / recent_sensitization
    PRA_LINEAGE_RAW = ['PRAPK', 'PRAMR', 'PRAPK_CL1', 'PRAPK_CL2',
                        'PRAMR_CL1', 'PRAMR_CL2', 'CPRA', 'CPRA_PEAK']

    # ========================================================================= =========================================================================
    # build peak_sensitization / recent_sensitization here

    print("PHASE 2.1 — Peak_sensitization as pra_source df")
    pra_source = t_df2[['TRR_ID_CODE', 'TX_DATE'] + PRA_LINEAGE_RAW].copy()   #$1
    pra_source.to_parquet(pra_source_path, engine='pyarrow')
    print(f"\n  pra_source extracted:")
    print(pra_source['PRAPK'].value_counts(dropna=False).to_string())

    # ========================================================================= =========================================================================
    # Build a rejection outcome constructor df from the baseline table.

    # TRTREJ1Y:
    #   TRTREJ1Y is the pre-computed UNOS 1-year rejection flag. It is a post-transplant outcome (leakage for the feature matrix) but a critical VALIDATION REFERENCE for the outcome we build in Segment 4.
    #   → Extracted to a separate parquet BEFORE being dropped.

    # ACUTE_REJ_EPI:
    #     ACUTE_REJ_EPI is the rejection flag for acute rejection occurred pre-discharge after transplant (for t_df). It is a post-transplant outcome (leakage for the feature matrix) but a critical VALIDATION REFERENCE for the outcome we build in Segment 4.
    #     → Extracted to a separate parquet BEFORE being dropped.

    print("PHASE 2.2 — Rename 'ACUTE_REJ_EPI' for both & Construct trtrej1y_validation df from t_df2")
    # Extract TRTREJ1Y & ACUTE_REJ_EPI as validation reference BEFORE any column removal

    t_df2 = t_df2.rename(columns={'ACUTE_REJ_EPI': 'ACUTE_REJ_EPI_PREDISCHARGE'})
    tf_df2 = tf_df2.rename(columns={'ACUTE_REJ_EPI': 'ACUTE_REJ_EPI_FOLLOWUP'})

    if 'TRTREJ1Y' in t_df2.columns and 'ACUTE_REJ_EPI_PREDISCHARGE' in t_df2.columns:
        trtrej1y_val = t_df2[['TRR_ID_CODE', 'TRTREJ1Y', 'ACUTE_REJ_EPI_PREDISCHARGE', 'TX_DATE', 'PX_STAT', 'PX_STAT_DATE']].copy()   #$2
        trtrej1y_val.to_parquet(trtrej1y_val_path, engine='pyarrow')
        print(f"\n  TRTREJ1Y & ACUTE_REJ_EPI_PREDISCHARGE extracted as validation reference:")
        print(t_df2['TRTREJ1Y'].value_counts(dropna=False).to_string())
        print(f"  Saved → {trtrej1y_val_path}")
        print(t_df2['ACUTE_REJ_EPI_PREDISCHARGE'].value_counts(dropna=False).to_string())
        print(f"  Saved → {trtrej1y_val_path}")
    else:
        print("  WARNING: TRTREJ1Y and/or ACUTE_REJ_EPI_PREDISCHARGE not found — validation reference unavailable.")

    # ========================================================================= =========================================================================
    # Keep only the selected columns in the baseline df

    print("PHASE 2.3 — Keeping only the necessary vals in t_df2: AT_TX_COLS + BASELINE_COLS + REMAINING_COLS")

    t_df2 = t_df2[AT_TX_COLS + BASELINE_COLS + REMAINING_COLS + COHORT_COLS].copy()   #$3



    # =========================================================================
    # PHASE 3 — LEAKAGE COLUMNS REMOVAL
    # =========================================================================

    # APPROACH: keyword matching + explicit list for columns the scanner misses.
    # Source: Inspection 12 identified 78 keyword-matched columns. Additional columns identified in prior segment reviews. These encode events that occur AFTER the transplant decision and cannot be known at prediction time.
    # Keyword-based leakage detection (matches Inspection 12 + expanded set)
    LEAKAGE_KEYWORDS = [
        'POSTTX',       # post-transplant hemodynamics at 24h / 72h
        'POST_TX',      # post-transplant support variables
        # 'POST_DON',     # post-donation hemodynamics (not available at allocation)
        'GSTATUS',      # graft status (outcome)
        'GTIME',        # graft survival time (outcome)
        'PSTATUS',      # patient survival (outcome)
        'PTIME',        # patient survival time (outcome)
        'PX_STAT',      # patient status at data extraction (outcome)
        'GRF_FAIL',     # graft failure (outcome)
        'GRF_STAT',     # graft functioning flag (outcome)
        # 'DEATH_DATE',   # date of death (outcome)
        'RETXDATE',     # re-transplant date (outcome)
    ]

    # Explicit extras — not caught by any keyword substring match
    EXTRA_LEAKAGE_KEYWORDS = [
        'TRTREJ1Y',      # 1-year rejection flag (primary outcome proxy — extracted above)
        'ACUTE_REJ_EPI', 'ACUTE_REJ_EPI_PREDISCHARGE',
        'REINTUBATED', 'DISCHARGE_DATE', 'LOS',
        'PST_DIAL',      # post-transplant dialysis
        'PST_STROKE',    # post-transplant stroke
        'PST_AIRWAY',    # post-transplant airway complication
        'PST_PACEMAKER', # post-transplant pacemaker
        'MALIG_TRR',     # malignancy at transplant record time (post-tx)
    ]

    # =========================================================================

    print('Extra leakage columns found in t_df')
    for i in EXTRA_LEAKAGE_KEYWORDS:
        if i in t_df2.columns:
            print(i, end = ',')
    print('')

    keyword_leakage = [
        col for col in t_df2.columns
        if any(kw.upper() in col.upper() for kw in LEAKAGE_KEYWORDS)
    ]
    extra_keyword_leakage = [c for c in EXTRA_LEAKAGE_KEYWORDS if c in t_df2.columns]
    all_leakage   = list(set(keyword_leakage + extra_keyword_leakage))

    t_df2 = t_df2.drop(columns=all_leakage, errors='ignore')

    print(f"\n  Keyword-matched columns : {len(keyword_leakage)}")
    print(f"  Explicit extras         : {len(extra_keyword_leakage)}")
    print(f"  Total dropped           : {len(all_leakage)}")
    print(f"  Baseline after removal  : {t_df2.shape}")

    # Verify nothing slipped through
    remaining = [
        c for c in t_df2.columns
        if any(kw.upper() in c.upper() for kw in LEAKAGE_KEYWORDS)
        or c in EXTRA_LEAKAGE_KEYWORDS
    ]

    if remaining:
        print(f"  WARNING: {len(remaining)} leakage cols remain: {remaining}")
    else:
        print("  ✓ No leakage keyword columns remain.")

    # ==============================================================================
    # EARLY ADMINISTRATIVE COLUMN DROPS (Moved this section from segment 2)
    # ==============================================================================
    #
    # PHILOSOPHY: Drop at this stage ONLY columns that are:
    #   (a) 100% administrative with zero clinical predictive value, OR
    #   (b) Organ-waitlist flags rendered useless by the heart-only filter
    #       (Segment 3 filters on WL_ORG, not WLHR, so WLHR is safe to drop now)

    #   PT_CODE, WL_ID_CODE              → needed for retransplant exclusion Seg 3
    #   INIT_OPO_CTR_CODE etc.           → protected, kept for Seg 3 filtering
    #   TRTREJ1Y                         → target variable, never drop
    # ==============================================================================

    DROP_COLS_BASELINE = [
        # Administrative center/OPO codes — high cardinality, non-clinical
        'CTR_CODE', 'OPO_CTR_CODE',

        # Country codes and payment geography — >99% missing or non-actionable
        'RECOV_COUNTRY', 'CITIZEN_COUNTRY',
        'PRI_PAYMENT_CTRY_TCR', 'PRI_PAYMENT_CTRY_TRR',

        # Pure admin presence flags — no clinical value
        'DATA_TRANSPLANT', 'DATA_WAITLIST',

        # Organ waitlist flags — Segment 3 filters on WL_ORG='HR', not these flags.
        # After heart-only filter all survivors would have WLHR='Y' (zero variance).
        'WLHR', 'WLHL', 'WLIN', 'WLKI', 'WLKP',
        'WLLI', 'WLLU', 'WLPA', 'WLPI', 'WLVC',

        # Completely empty column (0 non-null values, confirmed in inspection 6)
        'TXVCA',
    ]

    DROP_COLS_FOLLOWUP = [
        'TRR_FOL_ID_CODE',   # row-level ID, not a join key after this point
        'PRI_PAYMENT_CTRY',  # >99.9% missing
        'FOL_CTR_CODE',      # ← ADDED: administrative center code, 235 unique values,
                            # no clinical predictive value
    ]

    for frames, drop_list, label in [
        ([t_df2],   DROP_COLS_BASELINE, "Baseline"),
        ([tf_df2],  DROP_COLS_FOLLOWUP, "Follow-up"),
    ]:
        actually_present = [c for c in drop_list if c in frames[0].columns]
        for frame in frames:
            frame.drop(columns=actually_present, errors='ignore', inplace=True)
        print(f"{label}: dropped {len(actually_present)} columns → "
              f"{frames[0].shape[1]} remaining")
        if len(actually_present) < len(drop_list):
            missing_from_df = set(drop_list) - set(actually_present)
            print(f"  WARNING: these were not found (already absent): {missing_from_df}")





    # =========================================================================
    # PHASE 4 — TEMPORAL DISTRIBUTION REPORT
    # =========================================================================

    t_df2['_TX_YEAR'] = t_df2['TX_DATE'].dt.year
    yr = t_df2['_TX_YEAR'].value_counts().sort_index()
    print(f"\nTransplants per year:")
    print(yr.to_string())
    t_df2 = t_df2.drop(columns=['_TX_YEAR'])

    # =========================================================================
    # PHASE 5 — ALIGN FOLLOW-UP
    # =========================================================================

    cohort_ids = set(t_df2['TRR_ID_CODE'])

    tf_df2 = tf_df2[tf_df2['TRR_ID_CODE'].isin(cohort_ids)].copy()

    ids_with_followup = tf_df2['TRR_ID_CODE'].nunique()
    print(f"\n  Follow-up aligned:")
    print(f"    tf_df2 : {tf_df2.shape[0]:,} rows for {ids_with_followup:,} patients")
    print(f"    Cohort patients with NO follow-up: "
          f"{len(cohort_ids) - ids_with_followup:,}")

    # =========================================================================
    # PHASE 6 — NEAR-ZERO VARIANCE DROP (post-cohort-filter)
    # =========================================================================
    # Segment 2 explicitly deferred NZV removal to this phase.
    # Rationale: columns with meaningful variance across 234,975 rows (all
    # organs, all ages) may become constant in the 56k heart-only adult cohort.
    # Example: WL_ORG = 100% 'HR', TXHRT = 100% 'Y' after heart filter.
    #
    # Threshold: ≥ 99.5% of non-null values share the same value.
    # Protected columns and date/time columns are excluded from this check.
    # =========================================================================

    DATE_TIME_DTYPES = {'datetime64[ns]', 'timedelta64[ns]'}
    nzv_cols = []

    for col in t_df2.columns:
        if col in PROTECTED_COLUMNS:
            continue
        if str(t_df2[col].dtype) in DATE_TIME_DTYPES:
            continue
        non_null = t_df2[col].dropna()
        if len(non_null) == 0:
            nzv_cols.append(col)   # 100% missing → drop
            continue
        if non_null.value_counts(normalize=True).iloc[0] >= 0.995:
            nzv_cols.append(col)

    t_df2 = t_df2.drop(columns=nzv_cols, errors='ignore')
    print(f"\n  NZV columns dropped : {len(nzv_cols)}")
    if nzv_cols:
        print(f"  Columns: {nzv_cols}")
    print(f"  Baseline after NZV  : {t_df2.shape}")



    # =========================================================================
    # PHASE 7 — RESET INDICES, SAVE & FINAL VERIFICATION (round-trip read)
    # =========================================================================

    for frame in [t_df2, tf_df2]:
        frame.reset_index(drop=True, inplace=True)

    t_df2.to_parquet(t_df3_parquet_path,  engine='pyarrow')
    tf_df2.to_parquet(tf_df3_parquet_path, engine='pyarrow')

    BASE = "/content/drive/MyDrive/Thesis_parquet"

    t_df3  = pd.read_parquet(f"{BASE}/t_df3.parquet",  engine='pyarrow')
    tf_df3 = pd.read_parquet(f"{BASE}/tf_df3.parquet", engine='pyarrow')
    trtrej1y_val = pd.read_parquet(f"{BASE}/trtrej1y_validation.parquet", engine='pyarrow')

    print("\n" + "="*70)
    print("SEGMENT 3 COMPLETE — FINAL VERIFICATION")
    print("="*70)

    print(f"\n  Baseline  : {t_df3.shape[0]:>7,} rows × {t_df3.shape[1]} cols")
    print(f"  Follow-up : {tf_df3.shape[0]:>7,} rows × {tf_df3.shape[1]} cols")

    # Leakage check
    leakage_remaining = [
        c for c in t_df3.columns
        if any(kw.upper() in c.upper() for kw in LEAKAGE_KEYWORDS)
        or c in EXTRA_LEAKAGE_KEYWORDS
    ]
    print(f"\n  Leakage columns remaining : {len(leakage_remaining)}"
          + (f"\n    {leakage_remaining}" if leakage_remaining else " ✓"))

    # Age check
    print(f"\n  AGE — min={t_df3['AGE'].min():.0f}  max={t_df3['AGE'].max():.0f}"
          f"  mean={t_df3['AGE'].mean():.1f}  null={t_df3['AGE'].isna().sum()}")

    # TX_DATE range
    print(f"  TX_DATE — min={t_df3['TX_DATE'].min().date()}"
          f"  max={t_df3['TX_DATE'].max().date()}")

    # WL_ORG — correctly dropped by NZV after heart-only filter (all 'HR')
    # Verified in Phase 3 assertion before NZV drop; no re-check needed here.
    if 'WL_ORG' in t_df3.columns:
        print(f"\n  WL_ORG distribution:")
        print(t_df3['WL_ORG'].value_counts(dropna=False).to_string())
    else:
        print(f"\n  WL_ORG : dropped by NZV ✓ (constant 'HR' after heart-only filter —"
              f" zero model signal, verified in Phase 3 assertion)")

    # PHASE 2 — ASSERTIONS
    assert t_df3['TX_DATE'].isna().sum() == 0, "TX_DATE nulls remain after filter"
    assert float(t_df3['AGE'].min()) >= 18.0,  "Under-18 patient found in cohort"
    assert t_df3['TX_DATE'].min() >= pd.Timestamp('2000-01-01'), "Pre-2000 transplant found"
    assert t_df3['TX_DATE'].max() <= pd.Timestamp('2023-12-31'), "Post-2023 transplant found"
    if 'MULTIORG' in t_df3.columns:
        assert (t_df3['MULTIORG'] == 'Y').sum() == 0, "Multi-organ patient in cohort"
    if 'PREV_TX_ANY' in t_df3.columns:
        assert (t_df3['PREV_TX_ANY'] == 'Y').sum() == 0, "Re-transplant patient in cohort"

    if 'PREV_TX' in t_df3.columns:
        assert (t_df3['PREV_TX'] == 'Y').sum() == 0

    assert t_df3['TRR_ID_CODE'].notna().all()
    assert t_df3['TRR_ID_CODE'].is_unique
    if 'PT_CODE' in t_df3.columns:
      assert t_df3['PT_CODE'].is_unique, "Duplicate patient — retransplant exclusion incomplete"

    print("\n  ✓ All final t_df3 & tf_df3 assertions passed.")

    # Follow-up coverage
    t_ids  = set(t_df3['TRR_ID_CODE'])
    tf_ids = set(tf_df3['TRR_ID_CODE'])
    print(f"\n  Patients with ≥1 follow-up visit : {len(tf_ids):,} / {len(t_ids):,}"
          f"  ({100*len(tf_ids)/len(t_ids):.1f}%)")
    print(f"  Patients with NO follow-up       : {len(t_ids - tf_ids):,}")

    print(f"\n✅ Segment 3 complete. Ready for Segment 4 — outcome construction.")



# =============================================================================
# SEGMENT 3 — PATCH B: DISCHARGE / PERI-OPERATIVE LEAKAGE CHECK
# =============================================================================
# STEROID and TRANSFUSIONS in the UNOS THORACIC_DATA baseline refer to
# treatment during or at discharge from the transplant hospitalization —
# post-transplant events that constitute leakage.
# Verify against your UNOS THORACIC_DATA codebook before dropping.
#   STEROID:      "Steroids at discharge" — immunosuppression at discharge → POST-TX
#   TRANSFUSIONS: "Blood transfusions during hospitalization" → PERI/POST-TX
# =============================================================================

print("="*60)
print("SEGMENT 3 PATCH B — Discharge Variable Leakage Check")
print("="*60)
t_df3  = pd.read_parquet(t_df3_parquet_path,  engine='pyarrow')
tf_df3 = pd.read_parquet(tf_df3_parquet_path, engine='pyarrow')
TARGET_COLS = ['STEROID', 'TRANSFUSIONS']

for col in TARGET_COLS:
    present = col in t_df3.columns
    print(f"\n  {col}: {'PRESENT in t_df3' if present else 'not present (already absent)'}")
    if present:
        vc = t_df3[col].value_counts(dropna=False)
        print(f"  Distribution:\n{vc.to_string()}")
        non_null_rate = t_df3[col].notna().mean()
        print(f"  Non-null rate: {non_null_rate:.1%}")
        print(f"  ACTION: Verify in UNOS THORACIC_DATA codebook.")
        print(f"          If confirmed post-transplant → will be dropped below.")

# ─────────────────────────────────────────────────────────────────────────────
# STOP HERE and check your UNOS THORACIC_DATA codebook for STEROID and
# TRANSFUSIONS. Confirm they refer to discharge/peri-operative data (not
# pre-transplant status).
#
# If CONFIRMED post-transplant: uncomment the drop block below and re-run.
# If CONFIRMED pre-transplant (e.g., pre-tx steroid therapy): do NOT drop.
# ─────────────────────────────────────────────────────────────────────────────

# ── DROP BLOCK — uncomment ONLY after UNOS codebook verification ─────────────
# DISCHARGE_LEAKAGE = [c for c in ['STEROID', 'TRANSFUSIONS'] if c in t_df3.columns]
# if DISCHARGE_LEAKAGE:
#     t_df3 = t_df3.drop(columns=DISCHARGE_LEAKAGE)
#     t_df3.reset_index(drop=True, inplace=True)
#     t_df3.to_parquet(f"{BASE}/t_df3.parquet", engine='pyarrow', index=False)
#     print(f"\n  Dropped {DISCHARGE_LEAKAGE}")
#     print(f"  t_df3 updated: {t_df3.shape}")
# else:
#     print("\n  No target columns present — no action needed.")
print("\nPatch B inspection complete. Verify codebook before uncommenting drop block.")

Loading Segment 2 parquets...

======================================================================
PHASE 1 — Cohort row filters
======================================================================
  Start                               : 234,975
  After TX_DATE not null              : 159,831  (−75,144 waitlist-only)
  After AGE ≥ 18                      : 145,102  (−14,729: 14,719 pediatric + 10 age-unknown)

  WL_ORG distribution (pre-filter):
        count
WL_ORG
HR      87262
LU      56112
HL       1395
NaN       333

  After WL_ORG == 'HR'                :  87,262  (−57,840 non-heart)
  After single-organ filter           :  82,563  (−4,699 multi-organ [MULTIORG='Y': 4,699])
  After re-transplant exclusion       :  80,126  (−2,437 re-transplants)
  After TX_DATE ≥ 2000-01-01          :  57,751  (−22,375 pre-2000)
  After TX_DATE ≤ 2023-12-31          :  51,506  (−6,245 post-2023)

  ── FINAL COHORT : 51,506 patients ──
     Columns remaining : 625

  ✓ All PHASE 1 assertions passed.

======================================================================
PHASE 2 — Cohort column filters
======================================================================
baseline columns: 625
PHASE 2.1 — Peak_sensitization as pra_source df

  pra_source extracted:
PRAPK
NaN      44454
0.0       4846
2.0        297
4.0        212
3.0        142
5.0        135
7.0        102
99.0        78
1.0         65
8.0         57
9.0         56
11.0        47
6.0         46
16.0        44
10.0        42
13.0        39
12.0        38
14.0        32
18.0        31
15.0        30
20.0        27
17.0        26
25.0        21
23.0        21
38.0        18
28.0        18
30.0        17
21.0        17
24.0        16
19.0        16
33.0        15
36.0        15
32.0        14
43.0        14
93.0        13
26.0        13
22.0        13
100.0       12
35.0        12
27.0        11
34.0        11
63.0        10
98.0        10
41.0        10
50.0        10
31.0        10
58.0         9
95.0         9
29.0         9
73.0         9
94.0         8
64.0         8
62.0         8
70.0         8
60.0         8
48.0         8
83.0         8
72.0         7
37.0         7
86.0         7
77.0         7
89.0         7
57.0         7
96.0         7
69.0         7
59.0         7
53.0         7
97.0         7
56.0         7
40.0         7
67.0         6
85.0         6
47.0         6
39.0         6
92.0         6
65.0         6
45.0         6
80.0         5
79.0         5
82.0         5
46.0         5
90.0         5
91.0         5
84.0         5
76.0         5
54.0         5
66.0         4
87.0         4
49.0         4
81.0         4
71.0         4
74.0         4
44.0         4
51.0         4
52.0         3
75.0         3
88.0         3
78.0         3
55.0         3
61.0         3
42.0         2
68.0         1
PHASE 2.2 — Rename 'ACUTE_REJ_EPI' for both & Construct trtrej1y_validation df from t_df2

  TRTREJ1Y & ACUTE_REJ_EPI_PREDISCHARGE extracted as validation reference:
TRTREJ1Y
N      34209
Y       9750
NaN     7547
  Saved → /content/drive/MyDrive/Thesis_parquet/trtrej1y_validation.parquet
ACUTE_REJ_EPI_PREDISCHARGE
3.0    36138
NaN     7485
1.0     4588
2.0     3295
  Saved → /content/drive/MyDrive/Thesis_parquet/trtrej1y_validation.parquet
PHASE 2.3 — Keeping only the necessary vals in t_df2: AT_TX_COLS + BASELINE_COLS + REMAINING_COLS
Extra leakage columns found in t_df


  Keyword-matched columns : 0
  Explicit extras         : 0
  Total dropped           : 0
  Baseline after removal  : (51506, 290)
  ✓ No leakage keyword columns remain.
Baseline: dropped 0 columns → 290 remaining
  WARNING: these were not found (already absent): {'WLIN', 'DATA_TRANSPLANT', 'PRI_PAYMENT_CTRY_TRR', 'TXVCA', 'DATA_WAITLIST', 'WLVC', 'WLHR', 'WLPI', 'WLKP', 'WLLI', 'CITIZEN_COUNTRY', 'CTR_CODE', 'WLPA', 'WLLU', 'WLKI', 'OPO_CTR_CODE', 'WLHL', 'RECOV_COUNTRY', 'PRI_PAYMENT_CTRY_TCR'}
Follow-up: dropped 3 columns → 78 remaining

Transplants per year:
_TX_YEAR
2000    1840
2001    1844
2002    1771
2003    1686
2004    1607
2005    1685
2006    1769
2007    1759
2008    1654
2009    1722
2010    1843
2011    1779
2012    1852
2013    1952
2014    2071
2015    2132
2016    2526
2017    2538
2018    2622
2019    2697
2020    2792
2021    2861
2022    3066
2023    3438

  Follow-up aligned:
    tf_df2 : 425,670 rows for 48,733 patients
    Cohort patients with NO follow-up: 2,773

  NZV columns dropped : 36
  Columns: ['FEV1_TRR', 'FVC_TRR', 'HIV_SEROSTATUS', 'PCO2_TRR', 'PGE_TRR', 'BIOPSY_DGN', 'COD_WL', 'CONTROLLED', 'EXTRACRANIAL_CANCER_DON', 'HTLV2_OLD_DON', 'INHALED_NO', 'INHALED_NO_TCR', 'INIT_O2', 'INTRACRANIAL_CANCER_DON', 'INUTERO', 'ONVENT', 'PROS_INFUS_TCR', 'PROSTACYCLIN_TCR', 'RECOV_OUT_US', 'RESIST_INF', 'SKIN_CANCER_DON', 'TAH', 'TCR_CDC_GROWTH_BMI', 'TCR_CDC_GROWTH_HGT', 'TCR_CDC_GROWTH_WGT', 'TRANSPLANT_COUNTRY', 'TX_PROCEDUR_TY', 'CALC_LAS_LISTDATE', 'END_O2', 'TX_TYPE', 'HBV_SUR_ANTIGEN_DON', 'PREV_TX_ANY', 'PREV_TX', 'NUM_PREV_TX', 'MULTIORG', 'WL_ORG']
  Baseline after NZV  : (51506, 254)

======================================================================
SEGMENT 3 COMPLETE — FINAL VERIFICATION
======================================================================

  Baseline  :  51,506 rows × 254 cols
  Follow-up : 425,670 rows × 78 cols

  Leakage columns remaining : 0 ✓

  AGE — min=18  max=79  mean=53.0  null=0
  TX_DATE — min=2000-01-01  max=2023-12-31

  WL_ORG : dropped by NZV ✓ (constant 'HR' after heart-only filter — zero model signal, verified in Phase 3 assertion)

  ✓ All final t_df3 & tf_df3 assertions passed.

  Patients with ≥1 follow-up visit : 48,733 / 51,506  (94.6%)
  Patients with NO follow-up       : 2,773

✅ Segment 3 complete. Ready for Segment 4 — outcome construction.
============================================================
SEGMENT 3 PATCH B — Discharge Variable Leakage Check
============================================================

  STEROID: PRESENT in t_df3
  Distribution:
STEROID
N      46877
Y       3610
NaN     1019
  Non-null rate: 98.0%
  ACTION: Verify in UNOS THORACIC_DATA codebook.
          If confirmed post-transplant → will be dropped below.

  TRANSFUSIONS: PRESENT in t_df3
  Distribution:
TRANSFUSIONS
N      39444
Y      10349
NaN     1713
  Non-null rate: 96.7%
  ACTION: Verify in UNOS THORACIC_DATA codebook.
          If confirmed post-transplant → will be dropped below.

Patch B inspection complete. Verify codebook before uncommenting drop block.

# Segment 3 Complete

In [ ]:
t_df3_path = "/content/drive/MyDrive/Thesis_parquet/t_df3.parquet"
tf_df3_path = "/content/drive/MyDrive/Thesis_parquet/tf_df3.parquet"

t_df3 = pd.read_parquet(t_df3_path, engine='pyarrow')
tf_df3 = pd.read_parquet(tf_df3_path, engine='pyarrow')

print("t_df3 (3: Missing-Value Handled, COHORT Defined - no missing):", t_df3.shape)
print("tf_df3 (3: Missing-Value Handled, COHORT Defined - no missing):", tf_df3.shape)

print(f"Main cohort: {len(t_df3):,} transplants")
print(f"Followup records: {len(tf_df3):,} records")
print(f"Unique patients in followup: {tf_df3['TRR_ID_CODE'].nunique():,}")

# These should match:
assert t_df3['TRR_ID_CODE'].nunique() == len(t_df3), "Main cohort has duplicates!"
assert tf_df3['TRR_ID_CODE'].nunique() <= len(t_df3), "Followup has patients not in cohort!"

t_df3 (3: Missing-Value Handled, COHORT Defined - no missing): (51506, 254)
tf_df3 (3: Missing-Value Handled, COHORT Defined - no missing): (425670, 78)
Main cohort: 51,506 transplants
Followup records: 425,670 records
Unique patients in followup: 48,733

In [ ]:
# t_df3.to_csv('3.t_df3.csv', index=False)
# tf_df3.to_csv('3.tf_df3.csv', index=False)

# Segment: Tabulation

In [ ]:
t_df3_path = "/content/drive/MyDrive/Thesis_parquet/t_df3.parquet"
tf_df3_path = "/content/drive/MyDrive/Thesis_parquet/tf_df3.parquet"
trtrej1y_val_path = "/content/drive/MyDrive/Thesis_parquet/trtrej1y_validation.parquet"

t_df3 = pd.read_parquet(t_df3_path, engine='pyarrow')
tf_df3 = pd.read_parquet(tf_df3_path, engine='pyarrow')
trtrej1y_val = pd.read_parquet(trtrej1y_val_path)

In [ ]:
print(trtrej1y_val['ACUTE_REJ_EPI_PREDISCHARGE'].value_counts(dropna=False))

ACUTE_REJ_EPI_PREDISCHARGE
3.0    36138
NaN     7485
1.0     4588
2.0     3295
Name: count, dtype: int64

In [ ]:
print(trtrej1y_val['TRTREJ1Y'].value_counts(dropna=False))

TRTREJ1Y
N      34209
Y       9750
NaN     7547
Name: count, dtype: int64

In [ ]:
ct = pd.crosstab(
    trtrej1y_val['TRTREJ1Y'].astype('object').fillna('NaN'),
    trtrej1y_val['ACUTE_REJ_EPI_PREDISCHARGE'].astype('object').fillna('NaN'),
    margins=True
)

ct

ACUTE_REJ_EPI_PREDISCHARGE   1.0   2.0    3.0   NaN    All
TRTREJ1Y
N                              0  2677  28420  3112  34209
NaN                          544   275   4714  2014   7547
Y                           4044   343   3004  2359   9750
All                         4588  3295  36138  7485  51506

In [ ]:
pd.crosstab(trtrej1y_val['TRTREJ1Y'], trtrej1y_val['ACUTE_REJ_EPI_PREDISCHARGE'], dropna=True, margins=True)

ACUTE_REJ_EPI_PREDISCHARGE   1.0   2.0    3.0    All
TRTREJ1Y
N                              0  2677  28420  31097
Y                           4044   343   3004   7391
All                         4044  3020  31424  38488

In [ ]:
BASE = "/content/drive/MyDrive/Thesis_parquet"

OUTPUT_COHORT_PATH = f"{BASE}/final_cohort_1yr.parquet"
OUTPUT_OUTCOMES_PATH = f"{BASE}/patient_outcomes_1yr.parquet"

trtrej1y_val = pd.read_parquet(trtrej1y_val_path)

# SEGMENT 4A: 1-YEAR TARGET DEFINITION & PREDICTION HORIZON

In [ ]:
# ============================================================
# SEGMENT 4A (CORRECTED): 1-YEAR TARGET DEFINITION
# ============================================================
# FIX vs. the previous run: FOL_CD-based day bounds are now applied
# UNIFORMLY to the row set used for has_1/has_2/n_informative/last_day,
# not just to the separate has_clean_fol10 flag. Previously, FOL_CD=10
# rows with implausible DAYS_SINCE_TX (observed max: 4613) or FOL_CD=6
# rows (observed max: 572) could still satisfy the day>=300 FALLBACK
# rule even though they were excluded from the PRIMARY has_clean_fol10
# check -- an inconsistency, not an intended design choice. Fixed by
# building checkpoint_rows from a single, per-FOL_CD-bounded function
# used for both the aggregation and the primary-path check.
#
# ADDED: a permanent "narrow / treated-rejection-only" rate diagnostic,
# computed automatically instead of by hand -- this is the number to
# compare against Gemelli et al. (2024)'s 22.7%, not the broad
# OUTCOME_1Y rate.
#
# Everything else (branch logic, Changes 1/2, EFFECTIVE_CODE
# construction, TX_DATE anchor) is unchanged from the last verified run.
# ============================================================

import pandas as pd
import numpy as np

PARQUET_DIR = "/content/drive/MyDrive/Thesis_parquet/"

trtrej1y_validation = pd.read_parquet(PARQUET_DIR + "trtrej1y_validation.parquet")
t_df3  = pd.read_parquet(PARQUET_DIR + "t_df3.parquet")
tf_df3 = pd.read_parquet(PARQUET_DIR + "tf_df3.parquet")

print("Loading Segment 3 outputs...")

FOL_CD_6MO, FOL_CD_1YR = 6, 10
# Per-FOL_CD day bounds -- generous margins around each checkpoint's
# observed IQR, excluding the long outlier tails (FOL_CD=10 max seen: 4613;
# FOL_CD=6 max seen: 572). Verify FOL_CD's exact meaning against the
# official data dictionary; these values are inferred from the observed
# DAYS_SINCE_TX distribution, not from documentation.
FOL_CD_DAY_BOUNDS = {FOL_CD_6MO: (60, 300), FOL_CD_1YR: (300, 500)}
COVERAGE_MIN_DAY_FALLBACK = 300


def build_bounded_checkpoint_rows(out_label_df, fol_cd_values, day_bounds):
    """Single source of truth for 'is this row a usable checkpoint
    observation' -- used identically for aggregation AND the primary
    clean-checkpoint flag, so no downstream path can accidentally see
    an unbounded row the other path excluded."""
    frames = []
    for fc in fol_cd_values:
        lo, hi = day_bounds[fc]
        sub = out_label_df[(out_label_df["FOL_CD"] == fc) &
                            (out_label_df["DAYS_SINCE_TX"].between(lo, hi))]
        frames.append(sub)
    return pd.concat(frames, ignore_index=True) if frames else out_label_df.iloc[0:0]


# ---------------- PHASE 1 ----------------
label_df = trtrej1y_validation[trtrej1y_validation["TRTREJ1Y"].isin(["Y", "N"]) |
                                trtrej1y_validation["TRTREJ1Y"].isna()].copy()

# Selects rows where the condition is NOT true
invalid_df = trtrej1y_validation[~(trtrej1y_validation["TRTREJ1Y"].isin(["Y", "N"]) |
                                   trtrej1y_validation["TRTREJ1Y"].isna())].copy()


label_df["OUTCOME_1Y"] = np.nan
label_df["OUTCOME_1Y_SOURCE"] = ""

n_total = len(label_df)
n_y = (label_df["TRTREJ1Y"] == "Y").sum()
n_n = (label_df["TRTREJ1Y"] == "N").sum()
n_nan = label_df["TRTREJ1Y"].isna().sum()
n_invalid = len(invalid_df)

print(f"PHASE 1 — full cohort : {n_total:,}  (Y={n_y:,}, N={n_n:,}, NaN={n_nan:,})")
print(f"Excluded patients: {n_invalid}")


# ---------------- PHASE 2: discharge-stage resolution (unchanged) ----------------
epi_pre = pd.to_numeric(label_df["ACUTE_REJ_EPI_PREDISCHARGE"], errors="coerce")
y_mask = label_df["TRTREJ1Y"] == "Y"
n_mask = label_df["TRTREJ1Y"] == "N"
nan_mask = label_df["TRTREJ1Y"].isna()

m_2a = y_mask & epi_pre.isin([1, 2])
label_df.loc[m_2a, "OUTCOME_1Y"] = 1
label_df.loc[m_2a, "OUTCOME_1Y_SOURCE"] = "discharge_direct_Y"
print(f"PHASE 2a — Y, discharge 1/2 -> 1 : {m_2a.sum():,}")

m_2b = n_mask & (epi_pre == 1)
label_df.loc[m_2b, "OUTCOME_1Y_SOURCE"] = "DROP_contradiction_discharge"
print(f"PHASE 2b — N, discharge=1 -> contradiction, drop : {m_2b.sum():,}")

m_2c = n_mask & (epi_pre == 2)
label_df.loc[m_2c, "OUTCOME_1Y"] = 1
label_df.loc[m_2c, "OUTCOME_1Y_SOURCE"] = "discharge_direct_N_code2"
print(f"PHASE 2c — N, discharge=2 -> 1 (primary occurrence evidence) : {m_2c.sum():,}")

m_2d = nan_mask & epi_pre.isin([1, 2])
label_df.loc[m_2d, "OUTCOME_1Y"] = 1
label_df.loc[m_2d, "OUTCOME_1Y_SOURCE"] = "discharge_direct_trtrej1y_nan"
print(f"PHASE 2d — TRTREJ1Y=NaN, discharge 1/2 -> 1 : {m_2d.sum():,} (of {n_nan:,})")

# Keep the discharge-code split for the narrow-rate diagnostic later.
nan_disch_code1 = (nan_mask & (epi_pre == 1)).sum()
print(f"TRTREJ1Y = NaN & ACUTE_REJ_EPI_PREDISCHARGE = 1 total: {nan_disch_code1}")
nan_disch_code2 = (nan_mask & (epi_pre == 2)).sum()
print(f"TRTREJ1Y = NaN & ACUTE_REJ_EPI_PREDISCHARGE = 2 total: {nan_disch_code2}")

needs_followup = label_df["OUTCOME_1Y_SOURCE"] == ""
print(f"PHASE 2e — remaining, need follow-up lookup : {needs_followup.sum():,}")


# ---------------- PHASE 3: out_label_df ----------------
out_label_df = tf_df3[["TRR_ID_CODE", "ACUTE_REJ_EPI_FOLLOWUP", "PX_STAT_DATE",
                        "HOSP_REJ", "PX_STAT", "FOL_CD"]].merge(
    t_df3[["TRR_ID_CODE", "TX_DATE"]], on="TRR_ID_CODE", how="left")
out_label_df["DAYS_SINCE_TX"] = (out_label_df["PX_STAT_DATE"] - out_label_df["TX_DATE"]).dt.days

neg_days = (out_label_df["DAYS_SINCE_TX"] < 0).sum()
print(f"PHASE 3 — out_label_df : {out_label_df.shape}  (DAYS_SINCE_TX<0: {neg_days})")

epi = pd.to_numeric(out_label_df["ACUTE_REJ_EPI_FOLLOWUP"], errors="coerce")
epi_valid = epi.isin([1, 2, 3])
eff = pd.Series(np.where(epi_valid, epi, np.nan), index=out_label_df.index)
fb = ~epi_valid
eff.loc[fb & (out_label_df["HOSP_REJ"] == "Y")] = 1
eff.loc[fb & (out_label_df["HOSP_REJ"] == "N")] = 3
out_label_df["EFFECTIVE_CODE"] = eff


# ---------------- PHASE 5: FOL_CD-anchored, uniformly bounded checkpoint window ----------------
checkpoint_rows = build_bounded_checkpoint_rows(
    out_label_df, [FOL_CD_6MO, FOL_CD_1YR], FOL_CD_DAY_BOUNDS)

agg = checkpoint_rows.groupby("TRR_ID_CODE").agg(
    has_1=("EFFECTIVE_CODE", lambda s: (s == 1).any()),
    has_2=("EFFECTIVE_CODE", lambda s: (s == 2).any()),
    n_informative=("EFFECTIVE_CODE", lambda s: s.isin([1, 2, 3]).sum()),
    last_day=("DAYS_SINCE_TX", "max"),
).reset_index()

fol10_clean_ids = set(
    checkpoint_rows.loc[(checkpoint_rows["FOL_CD"] == FOL_CD_1YR) &
                         (checkpoint_rows["EFFECTIVE_CODE"] == 3),
                         "TRR_ID_CODE"])
agg["has_clean_fol10"] = agg["TRR_ID_CODE"].isin(fol10_clean_ids)

print(f"PHASE 5a — {len(agg):,} patients with >=1 bounded row at FOL_CD in {{6,10}}; "
      f"{len(fol10_clean_ids):,} have a clean FOL_CD==10 row")

pending = label_df.loc[needs_followup, ["TRR_ID_CODE", "TRTREJ1Y"]].merge(
    agg, on="TRR_ID_CODE", how="left")
for c in ["has_1", "has_2", "has_clean_fol10"]:
    pending[c] = pending[c].fillna(False)
pending["n_informative"] = pending["n_informative"].fillna(0)
pending["last_day"] = pending["last_day"].fillna(-1)

sufficient = pending["has_clean_fol10"] | (
    (pending["n_informative"] > 0) & (pending["last_day"] >= COVERAGE_MIN_DAY_FALLBACK))

src = pd.Series("", index=pending.index)
out1y = pd.Series(np.nan, index=pending.index)
y_p = pending["TRTREJ1Y"] == "Y"
n_p = pending["TRTREJ1Y"] == "N"
nan_p = pending["TRTREJ1Y"].isna()
any_pos = pending["has_1"] | pending["has_2"]

a1 = y_p & any_pos
src.loc[a1] = "followup_confirmed_Y"; out1y.loc[a1] = 1
a2 = y_p & ~any_pos & sufficient
src.loc[a2] = "DROP_contradiction_confirmed_negative_Y"
a3 = y_p & ~any_pos & ~sufficient & (pending["n_informative"] > 0)
src.loc[a3] = "DROP_stale_followup_only_Y"
a4 = y_p & (pending["n_informative"] == 0) & ~pending["has_clean_fol10"]
src.loc[a4] = "DROP_no_informative_followup_Y"

b1 = n_p & pending["has_1"]
src.loc[b1] = "DROP_contradiction_followup_N"
b2 = n_p & ~pending["has_1"] & pending["has_2"]
src.loc[b2] = "followup_positive_N"; out1y.loc[b2] = 1
b3 = n_p & ~any_pos & sufficient
src.loc[b3] = "followup_confirmed_negative_N"; out1y.loc[b3] = 0
b4 = n_p & ~any_pos & ~sufficient & (pending["n_informative"] > 0)
src.loc[b4] = "DROP_stale_followup_only_N"
b5 = n_p & (pending["n_informative"] == 0) & ~pending["has_clean_fol10"]
src.loc[b5] = "DROP_no_informative_followup_N"

c1 = nan_p & any_pos
src.loc[c1] = "followup_positive_trtrej1y_nan"; out1y.loc[c1] = 1
c2 = nan_p & ~any_pos & sufficient
src.loc[c2] = "followup_confirmed_negative_trtrej1y_nan"; out1y.loc[c2] = 0
c3 = nan_p & ~any_pos & ~sufficient & (pending["n_informative"] > 0)
src.loc[c3] = "DROP_stale_followup_only_trtrej1y_nan"
c4 = nan_p & (pending["n_informative"] == 0) & ~pending["has_clean_fol10"]
src.loc[c4] = "DROP_no_informative_followup_trtrej1y_nan"

pending["OUTCOME_1Y_SOURCE"] = src
pending["OUTCOME_1Y"] = out1y

label_df = label_df.set_index("TRR_ID_CODE")
p_idx = pending.set_index("TRR_ID_CODE")
label_df.loc[p_idx.index, "OUTCOME_1Y"] = p_idx["OUTCOME_1Y"]
label_df.loc[p_idx.index, "OUTCOME_1Y_SOURCE"] = p_idx["OUTCOME_1Y_SOURCE"]
label_df = label_df.reset_index()

print("\nFull OUTCOME_1Y_SOURCE breakdown:")
print(label_df["OUTCOME_1Y_SOURCE"].value_counts())

nan_followup_pos_rows = checkpoint_rows[checkpoint_rows["TRR_ID_CODE"].isin(
    pending.loc[c1, "TRR_ID_CODE"])]
nan_followup_code1 = nan_followup_pos_rows.loc[
    nan_followup_pos_rows["EFFECTIVE_CODE"] == 1, "TRR_ID_CODE"].nunique()
print("\nfollowup_positive_trtrej1y_nan, EFFECTIVE_CODE composition (expect both 1.0 and 2.0):")
print(nan_followup_pos_rows.loc[nan_followup_pos_rows["EFFECTIVE_CODE"].isin([1, 2]),
                                  "EFFECTIVE_CODE"].value_counts())

final_1y = label_df[label_df["OUTCOME_1Y"].isin([0, 1])].copy()
final_1y["OUTCOME_1Y"] = final_1y["OUTCOME_1Y"].astype(int)

print(f"\nFINAL 1-YEAR COHORT : {len(final_1y):,} / {n_total:,}")
print(final_1y["OUTCOME_1Y"].value_counts(normalize=True))

# ---------------- NARROW ("treated-rejection-only") rate: permanent diagnostic ----------------
narrow_y = final_1y["OUTCOME_1Y_SOURCE"].isin(["discharge_direct_Y", "followup_confirmed_Y"]).sum()
narrow_n = 0  # both N-branch positive pathways are code=2-only by construction
narrow_nan = nan_disch_code1 + nan_followup_code1
narrow_total = narrow_y + narrow_n + narrow_nan
narrow_rate = narrow_total / len(final_1y)

print(f"\nNARROW (treated-rejection-only) rate -- compare THIS to Gemelli et al. (2024), not the broad rate:")
print(f"  Y-branch (TRTREJ1Y=Y is itself a treatment claim): {narrow_y:,}")
print(f"  N-branch (both positive pathways are code=2-only):  {narrow_n:,}")
print(f"  NaN-branch code=1-driven: discharge={nan_disch_code1:,}, followup={nan_followup_code1:,}")
print(f"  Narrow positive: {narrow_total:,} / {len(final_1y):,} = {narrow_rate:.4f}")
print(f"  Gemelli et al. (2024): 0.227 (9,946/43,763)")

final_1y[["TRR_ID_CODE", "OUTCOME_1Y", "OUTCOME_1Y_SOURCE"]].to_parquet(
    PARQUET_DIR + "outcome_1y.parquet", index=False)
print(f"\nSaved -> {PARQUET_DIR}outcome_1y.parquet")

Loading Segment 3 outputs...
PHASE 1 — full cohort : 51,506  (Y=9,750, N=34,209, NaN=7,547)
Excluded patients: 0
PHASE 2a — Y, discharge 1/2 -> 1 : 4,387
PHASE 2b — N, discharge=1 -> contradiction, drop : 0
PHASE 2c — N, discharge=2 -> 1 (primary occurrence evidence) : 2,677
PHASE 2d — TRTREJ1Y=NaN, discharge 1/2 -> 1 : 819 (of 7,547)
TRTREJ1Y = NaN & ACUTE_REJ_EPI_PREDISCHARGE = 1 total: 544
TRTREJ1Y = NaN & ACUTE_REJ_EPI_PREDISCHARGE = 2 total: 275
PHASE 2e — remaining, need follow-up lookup : 43,623
PHASE 3 — out_label_df : (425670, 8)  (DAYS_SINCE_TX<0: 0)
PHASE 5a — 45,949 patients with >=1 bounded row at FOL_CD in {6,10}; 32,191 have a clean FOL_CD==10 row

Full OUTCOME_1Y_SOURCE breakdown:
OUTCOME_1Y_SOURCE
followup_confirmed_negative_N                26577
DROP_no_informative_followup_trtrej1y_nan     6136
discharge_direct_Y                            4387
followup_confirmed_Y                          3600
discharge_direct_N_code2                      2677
followup_positive_N                           2575
DROP_no_informative_followup_N                2366
DROP_no_informative_followup_Y                1072
discharge_direct_trtrej1y_nan                  819
DROP_contradiction_confirmed_negative_Y        691
followup_confirmed_negative_trtrej1y_nan       440
followup_positive_trtrej1y_nan                 152
DROP_contradiction_followup_N                   14
Name: count, dtype: int64

followup_positive_trtrej1y_nan, EFFECTIVE_CODE composition (expect both 1.0 and 2.0):
EFFECTIVE_CODE
1.0    111
2.0     41
Name: count, dtype: int64

FINAL 1-YEAR COHORT : 41,227 / 51,506
OUTCOME_1Y
0    0.655323
1    0.344677
Name: proportion, dtype: float64

NARROW (treated-rejection-only) rate -- compare THIS to Gemelli et al. (2024), not the broad rate:
  Y-branch (TRTREJ1Y=Y is itself a treatment claim): 7,987
  N-branch (both positive pathways are code=2-only):  0
  NaN-branch code=1-driven: discharge=544, followup=111
  Narrow positive: 8,642 / 41,227 = 0.2096
  Gemelli et al. (2024): 0.227 (9,946/43,763)

Saved -> /content/drive/MyDrive/Thesis_parquet/outcome_1y.parquet

In [ ]:
Loaded shapes:
  trtrej1y_validation: (51506, 6)
  t_df3:               (51506, 256)
  tf_df3:               (425670, 78)
  outcome_1y (saved):  (21078, 3)
  outcome_3y (saved):  (35032, 4)

Dtype / raw-value sanity check -- STOP and fix dtypes below before
continuing if these don't look like {'Y','N'} strings and 1/2/3 codes:
  trtrej1y_validation.TRTREJ1Y: dtype=category, sample=['Y', 'N']
  trtrej1y_validation.ACUTE_REJ_EPI_PREDISCHARGE: dtype=float32, sample=[np.float32(3.0), np.float32(1.0), np.float32(2.0)]
  trtrej1y_validation.PX_STAT: dtype=category, sample=['D', 'L', 'A', 'R']
  trtrej1y_validation.TX_DATE: dtype=datetime64[ns], sample=[Timestamp('2002-01-23 00:00:00'), Timestamp('2000-08-09 00:00:00'), Timestamp('2001-03-28 00:00:00'), Timestamp('2001-08-10 00:00:00'), Timestamp('2002-02-09 00:00:00'), Timestamp('2000-07-05 00:00:00')]
  tf_df3.ACUTE_REJ_EPI_FOLLOWUP: dtype=float32, sample=[np.float32(3.0), np.float32(2.0), np.float32(1.0)]
  tf_df3.HOSP_REJ: dtype=category, sample=['Y', 'N']
  tf_df3.PX_STAT_DATE: dtype=datetime64[ns], sample=[Timestamp('2024-05-16 00:00:00'), Timestamp('2024-12-04 00:00:00'), Timestamp('2024-06-21 00:00:00'), Timestamp('2024-12-17 00:00:00'), Timestamp('2024-08-13 00:00:00'), Timestamp('2025-02-03 00:00:00')]
  tf_df3.PX_STAT: dtype=category, sample=['A', 'D', 'N', 'R', 'L']
  PHASE 1 -- TRTREJ1Y usable: 43959 / 51506
  PHASE 2a -- discharge_direct: 4387
  PHASE 2b -- DROP_contradiction_discharge: 0
  PHASE 2c -- remaining, need follow-up lookup: 39572
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  PHASE 5a -- patients with >=1 follow-up row in window: 42296

  Full OUTCOME_1Y_SOURCE breakdown:
OUTCOME_1Y_SOURCE
DROP_no_informative_followup               18470
followup_confirmed_negative_N              13583
discharge_direct                            4387
DROP_no_informative_followup_Y              3494
followup_positive_N                         1568
followup_confirmed_Y                        1540
DROP_stale_followup_only_N                   581
DROP_contradiction_confirmed_negative_Y      312
DROP_stale_followup_only_Y                    17
DROP_contradiction_followup_N                  7
Name: count, dtype: int64

Re-derived final 1-year cohort: 21078 (expected 21,078 -- MATCH)
Re-derived positive rate: 0.355584 (expected 0.355584)
Saved -> label_1y_audit_full.parquet (full audit trail, drops included)
ITEM 1 -- Crude vs. resolved-cohort rejection rate
  Crude TRTREJ1Y='Y' rate (pre-resolution): 9750/43959 = 0.2218
  Resolved-cohort OUTCOME_1Y=1 rate:        7495/21078 = 0.3556
  Relative inflation: 60.3%
  Gemelli et al. (2024): 22.7% (9,946/43,763), same TRTREJ1Y variable, adult UNOS
  2000-2021 -- compare against the CRUDE rate above, not the resolved-cohort rate,
  when citing that benchmark in the thesis.
ITEM 2 -- Construct broadening beyond 'treated rejection'
  followup_positive_N cases (code=2-only override of TRTREJ1Y=N): 1568
  Share of final positive class: 0.2092

  Strict-definition variant (recode 1568 cases to negative):
  OUTCOME_1Y_STRICT positive rate: 0.2812 (vs. broad definition 0.3556)
  Saved -> outcome_1y_strict.parquet
  ACTION: re-run your best 1yr model with OUTCOME_1Y_STRICT swapped in as a
  robustness check; report whether AUROC/SHAP ranking materially change.
ITEM 3 -- Concordance among cases with conclusive evidence on both sides
COMPARABILITY
agree                   19510
construct_broadening     1568
hard_contradiction        319
Name: count, dtype: int64

  Total comparable: 21397
  Agreement rate:            0.9118
  Construct-broadening rate: 0.0733
  Hard contradiction rate:   0.0149
  Cite the HARD CONTRADICTION rate (isolates genuine logical conflicts) as your
  triangulation-validity statistic -- not the raw agreement rate, which folds in
  the construct-broadening cases from Item 2.
ITEM 4 -- EFFECTIVE_CODE missingness, stratified by era and PX_STAT

  By era:
ERA
post_2004-06-30    0.548032
pre_2004-06-30     0.597777
Name: EFFECTIVE_CODE_NA, dtype: float64

  By era x PX_STAT:
                             mean   count
ERA             PX_STAT
post_2004-06-30 A        0.528631  380878
                D        0.627474   17180
pre_2004-06-30  A        0.611042   11991
post_2004-06-30 N        0.961343    9468
                L        1.000000    1704
pre_2004-06-30  D        0.282993     735
post_2004-06-30 R        0.576087     552
pre_2004-06-30  L        1.000000     128
                N        1.000000      77
                R        0.136364      22

  Overall NaN rate: 0.5495 (expected ~0.5497, i.e. 233925/425670)
  If NaN concentrates in pre-2004 rows and/or Died/ReTx/Lost PX_STAT categories:
  this is registry structure, document it with these numbers, not a bug.
  If NaN is still high among post-2004 'Alive' rows: real data-quality flag,
  needs its own limitations paragraph.
ITEM 5 -- Era-cutover (2004-06-30) fallback logic, empirical impact
  % of POST-cutover rows with non-null HOSP_REJ:              0.1475
  % of PRE-cutover rows with non-null ACUTE_REJ_EPI_FOLLOWUP: 0.0963
  Near-zero first number -> unconditional fallback is functionally harmless,
  document and leave code as-is. Non-trivial -> quantifying label impact below.
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)

  Rows whose EFFECTIVE_CODE would change if the era-gate were enforced: 943 of 425670 (0.2215%)
ITEM 6a -- 1-year window boundary sensitivity (baseline: 365 days / 300-day coverage)
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=365, coverage_min_day=300: n=21078, positive_rate=0.3556, delta_n_vs_baseline=+0
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=395, coverage_min_day=300: n=36539, positive_rate=0.2954, delta_n_vs_baseline=+15461
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=395, coverage_min_day=330: n=35122, positive_rate=0.3073, delta_n_vs_baseline=+14044
  PHASE 1 -- 3yr-eligible population: 45002
    of which OUTCOME_1Y=1  : 6654
    of which OUTCOME_1Y=0  : 11479
    of which OUTCOME_1Y NaN: 26869
  PHASE 2 -- carried forward as 3yr=1: 6654
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)

  PHASE 3 -- resolution breakdown:
OUTCOME_3Y_SOURCE
independent_3yr_negative           19024
independent_3yr_positive            9354
DROP_stale_followup_only_3y         8837
DROP_no_informative_followup_3y     1133
Name: count, dtype: int64

Re-derived final 3-year cohort: 35032 (expected 35,032 -- MATCH)
Re-derived positive rate: 0.456954 (expected 0.456954)
ITEM 6b -- 3-year window boundary sensitivity (baseline: 1095 days / 730-day coverage)
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=1095, coverage_min_day=730: n=35032, positive_rate=0.4570, delta_n_vs_baseline=+0
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=1125, coverage_min_day=730: n=38131, positive_rate=0.4308, delta_n_vs_baseline=+3099
  DAYS_SINCE_TX < 0 : 0 rows (should be ~0 -- investigate before trusting the window filter)
  window_end=1095, coverage_min_day=700: n=37343, positive_rate=0.4287, delta_n_vs_baseline=+2311
ITEM 7 -- Data-extraction snapshot date (empirical LOWER-BOUND estimate only)
  Max TX_DATE in t_df3:       2023-12-31 00:00:00
  Max PX_STAT_DATE in tf_df3: 2025-10-03 00:00:00
  CAVEAT: the true extraction date is >= max(PX_STAT_DATE) but could be later --
  this is a lower bound, not a confirmed date. Cross-check against the STAR file
  User Guide / your data-request confirmation for the authoritative 'data as of' date.

  Latest TX_DATE with a full 3-year window observable given the data seen: 2022-10-04
  Segment 4B currently uses eligible_cutoff = 2021-12-31 -- CONSISTENT

ITEM 8 -- Follow-up touchpoint pattern (thoracic 6-month-form question)
  Rows with DAYS_SINCE_TX in [150,210] (6-month cluster):        29504
  Rows with DAYS_SINCE_TX in [335,365] (1-year, strict):         17500
  Rows with DAYS_SINCE_TX in [335,400] (1-year, +35d admin lag): 37901
  cluster_6mo near zero relative to the 1yr cluster -> heart-transplant recipients
  get essentially ONE touchpoint in the 1yr window; admin lag on that single form
  disproportionately drives DROP_no_informative_followup*.
  cluster_6mo comparable in size -> two touchpoints exist; re-examine Item 4 instead.
Saved -> segment4_diagnostics_report.txt

ALL 9 ITEMS COMPUTED. Review printed output above before writing the
corresponding methods/limitations paragraphs.

# SEGMENT 4B: 3-YEAR TARGET DEFINITION & PREDICTION HORIZON

In [ ]:
# ============================================================
# SEGMENT 4B (CORRECTED): 3-YEAR TARGET DEFINITION
# Mirrors Segment 4A's FOL_CD-checkpoint architecture, extended
# to cover the full 0-3yr window via complementary interval
# reports at FOL_CD 6/10/20/30.
# ============================================================
import pandas as pd
import numpy as np

PARQUET_DIR = "/content/drive/MyDrive/Thesis_parquet/"

print("Loading Segment 3 + 4A outputs...")
t_df3 = pd.read_parquet(PARQUET_DIR + "t_df3.parquet")
tf_df3 = pd.read_parquet(PARQUET_DIR + "tf_df3.parquet")
final_1y = pd.read_parquet(PARQUET_DIR + "outcome_1y.parquet")

FOL_CD_6MO, FOL_CD_1YR, FOL_CD_2YR, FOL_CD_3YR = 6, 10, 20, 30
# 6/10 bounds are the verified ones from 4A. 20/30 bounds below are a reasoned
# EXTENSION of the same generous-margin philosophy, built from the FOL_CD
# distribution table pulled earlier in this project (FOL_CD=20: IQR 711-745;
# FOL_CD=30: IQR 1067-1109) -- NOT yet independently re-verified with a fresh
# describe() the way 6/10 were. Run that check before citing these in methods.
FOL_CD_DAY_BOUNDS = {
    FOL_CD_6MO: (60, 300), FOL_CD_1YR: (300, 500),
    FOL_CD_2YR: (600, 900), FOL_CD_3YR: (950, 1300),
}
COVERAGE_MIN_DAY_FALLBACK = 950  # 3-year equivalent of 4A's 300-day fallback


def build_bounded_checkpoint_rows(out_label_df, fol_cd_values, day_bounds):
    frames = []
    for fc in fol_cd_values:
        lo, hi = day_bounds[fc]
        sub = out_label_df[(out_label_df["FOL_CD"] == fc) &
                            (out_label_df["DAYS_SINCE_TX"].between(lo, hi))]
        frames.append(sub)
    return pd.concat(frames, ignore_index=True) if frames else out_label_df.iloc[0:0]


# ---------------- PHASE 1: 3-year eligible population, by date alone ----------------
label_3y = t_df3.loc[t_df3["TX_DATE"] <= "2021-12-31", ["TRR_ID_CODE", "TX_DATE"]].copy()
label_3y = label_3y.merge(
    final_1y[["TRR_ID_CODE", "OUTCOME_1Y", "OUTCOME_1Y_SOURCE"]], on="TRR_ID_CODE", how="left")
print(f"PHASE 1 — 3yr-eligible population : {len(label_3y):,}")
print(f"  OUTCOME_1Y=1 : {(label_3y['OUTCOME_1Y']==1).sum():,}")
print(f"  OUTCOME_1Y=0 : {(label_3y['OUTCOME_1Y']==0).sum():,}")
print(f"  OUTCOME_1Y unresolved (NaN) : {label_3y['OUTCOME_1Y'].isna().sum():,}")

# ---------------- PHASE 2: cumulative shortcut ----------------
label_3y["OUTCOME_3Y"] = np.nan
label_3y["OUTCOME_3Y_SOURCE"] = ""
m = label_3y["OUTCOME_1Y"] == 1
label_3y.loc[m, "OUTCOME_3Y"] = 1
label_3y.loc[m, "OUTCOME_3Y_SOURCE"] = "cumulative_from_1y_positive"
print(f"PHASE 2 — carried forward as 3yr=1 : {m.sum():,}")

# ---------------- PHASE 3: out_label_df (self-contained, defensive column check) ----------------
epi_col = "ACUTE_REJ_EPI_FOLLOWUP" if "ACUTE_REJ_EPI_FOLLOWUP" in tf_df3.columns else "ACUTE_REJ_EPI"
out_label_df = tf_df3[["TRR_ID_CODE", epi_col, "PX_STAT_DATE", "HOSP_REJ", "PX_STAT", "FOL_CD"]].copy()
if epi_col != "ACUTE_REJ_EPI_FOLLOWUP":
    out_label_df = out_label_df.rename(columns={epi_col: "ACUTE_REJ_EPI_FOLLOWUP"})
out_label_df = out_label_df.merge(t_df3[["TRR_ID_CODE", "TX_DATE"]], on="TRR_ID_CODE", how="left")
out_label_df["DAYS_SINCE_TX"] = (out_label_df["PX_STAT_DATE"] - out_label_df["TX_DATE"]).dt.days

epi = pd.to_numeric(out_label_df["ACUTE_REJ_EPI_FOLLOWUP"], errors="coerce")
epi_valid = epi.isin([1, 2, 3])
eff = pd.Series(np.where(epi_valid, epi, np.nan), index=out_label_df.index)
fb = ~epi_valid
eff.loc[fb & (out_label_df["HOSP_REJ"] == "Y")] = 1
eff.loc[fb & (out_label_df["HOSP_REJ"] == "N")] = 3
out_label_df["EFFECTIVE_CODE"] = eff
print(f"PHASE 3 — out_label_df : {out_label_df.shape}")

# ---------------- PHASE 4: extended checkpoint set, 0-3yr ----------------
checkpoint_rows_3y = build_bounded_checkpoint_rows(
    out_label_df, [FOL_CD_6MO, FOL_CD_1YR, FOL_CD_2YR, FOL_CD_3YR], FOL_CD_DAY_BOUNDS)

agg_3y = checkpoint_rows_3y.groupby("TRR_ID_CODE").agg(
    has_1=("EFFECTIVE_CODE", lambda s: (s == 1).any()),
    has_2=("EFFECTIVE_CODE", lambda s: (s == 2).any()),
    n_informative=("EFFECTIVE_CODE", lambda s: s.isin([1, 2, 3]).sum()),
    last_day=("DAYS_SINCE_TX", "max"),
).reset_index()

fol30_clean_ids = set(
    checkpoint_rows_3y.loc[(checkpoint_rows_3y["FOL_CD"] == FOL_CD_3YR) &
                            (checkpoint_rows_3y["EFFECTIVE_CODE"] == 3), "TRR_ID_CODE"])
agg_3y["has_clean_fol30"] = agg_3y["TRR_ID_CODE"].isin(fol30_clean_ids)
print(f"PHASE 4 — {len(agg_3y):,} patients with >=1 bounded row at FOL_CD in {{6,10,20,30}}; "
      f"{len(fol30_clean_ids):,} have a clean FOL_CD==30 row")

# ---------------- PHASE 5: independent check for everyone not carried forward ----------------
needs_3y = label_3y["OUTCOME_3Y_SOURCE"] == ""
pending = label_3y.loc[needs_3y, ["TRR_ID_CODE"]].merge(agg_3y, on="TRR_ID_CODE", how="left")
for c in ["has_1", "has_2", "has_clean_fol30"]:
    pending[c] = pending[c].fillna(False)
pending["n_informative"] = pending["n_informative"].fillna(0)
pending["last_day"] = pending["last_day"].fillna(-1)

sufficient = pending["has_clean_fol30"] | (
    (pending["n_informative"] > 0) & (pending["last_day"] >= COVERAGE_MIN_DAY_FALLBACK))
any_pos = pending["has_1"] | pending["has_2"]

src, out3y = pd.Series("", index=pending.index), pd.Series(np.nan, index=pending.index)
m = any_pos; src.loc[m] = "independent_3yr_positive"; out3y.loc[m] = 1
m = ~any_pos & sufficient; src.loc[m] = "independent_3yr_negative"; out3y.loc[m] = 0
m = ~any_pos & ~sufficient & (pending["n_informative"] > 0); src.loc[m] = "DROP_stale_followup_only_3y"
m = ~any_pos & (pending["n_informative"] == 0) & ~pending["has_clean_fol30"]; src.loc[m] = "DROP_no_informative_followup_3y"

pending["OUTCOME_3Y"], pending["OUTCOME_3Y_SOURCE"] = out3y, src
print(pending["OUTCOME_3Y_SOURCE"].value_counts().to_string())

label_3y = label_3y.set_index("TRR_ID_CODE"); p_idx = pending.set_index("TRR_ID_CODE")
label_3y.loc[p_idx.index, "OUTCOME_3Y"] = p_idx["OUTCOME_3Y"]
label_3y.loc[p_idx.index, "OUTCOME_3Y_SOURCE"] = p_idx["OUTCOME_3Y_SOURCE"]
label_3y = label_3y.reset_index()

# ---------------- PHASE 6: finalize ----------------
final_3y = label_3y[label_3y["OUTCOME_3Y"].isin([0, 1])].copy()
final_3y["OUTCOME_3Y"] = final_3y["OUTCOME_3Y"].astype(int)

print(f"\nFINAL 3-YEAR COHORT : {len(final_3y):,} / {len(label_3y):,}")
print(final_3y["OUTCOME_3Y"].value_counts(normalize=True).to_string())

recovered = final_3y[final_3y["OUTCOME_1Y"].isna()]
clean_incident = final_3y[final_3y["OUTCOME_1Y"] == 0]
print(f"\nRecovered (1yr never resolved) : {len(recovered):,}, rate {recovered['OUTCOME_3Y'].mean():.3f}")
print(f"Clean incident pool (1yr=0 confirmed, for cross-horizon SHAP): {len(clean_incident):,}, "
      f"rate {clean_incident['OUTCOME_3Y'].mean():.3f}")

narrow_y_carried = final_3y["OUTCOME_1Y_SOURCE"].isin(["discharge_direct_Y", "followup_confirmed_Y"]).sum()
print(f"\nNARROW rate LOWER BOUND (1yr-treated carried forward only): "
      f"{narrow_y_carried:,} / {len(final_3y):,} = {narrow_y_carried/len(final_3y):.4f}")
print("  Not yet the full narrow rate — independent_3yr_positive isn't split by code 1/2 "
      "the way 4A's NaN-branch was. Apply the same corroboration split to checkpoint_rows_3y "
      "before citing an exact 3-year narrow figure.")

final_3y[["TRR_ID_CODE", "OUTCOME_1Y", "OUTCOME_3Y", "OUTCOME_3Y_SOURCE"]].to_parquet(
    PARQUET_DIR + "outcome_3y.parquet", index=False)
print(f"\nSaved -> {PARQUET_DIR}outcome_3y.parquet")

Loading Segment 3 + 4A outputs...
PHASE 1 — 3yr-eligible population : 45,002
  OUTCOME_1Y=1 : 12,605
  OUTCOME_1Y=0 : 22,701
  OUTCOME_1Y unresolved (NaN) : 9,696
PHASE 2 — carried forward as 3yr=1 : 12,605
PHASE 3 — out_label_df : (425670, 9)
PHASE 4 — 46,629 patients with >=1 bounded row at FOL_CD in {6,10,20,30}; 30,881 have a clean FOL_CD==30 row
OUTCOME_3Y_SOURCE
independent_3yr_negative           20593
DROP_no_informative_followup_3y     5868
DROP_stale_followup_only_3y         2970
independent_3yr_positive            2966

FINAL 3-YEAR COHORT : 36,164 / 45,002
OUTCOME_3Y
0    0.569434
1    0.430566

Recovered (1yr never resolved) : 3,480, rate 0.158
Clean incident pool (1yr=0 confirmed, for cross-horizon SHAP): 20,079, rate 0.120

NARROW rate LOWER BOUND (1yr-treated carried forward only): 7,122 / 36,164 = 0.1969
  Not yet the full narrow rate — independent_3yr_positive isn't split by code 1/2 the way 4A's NaN-branch was. Apply the same corroboration split to checkpoint_rows_3y before citing an exact 3-year narrow figure.

Saved -> /content/drive/MyDrive/Thesis_parquet/outcome_3y.parquet

# Segment 5: FEATURE ENGINEERING & PREPROCESSING — CONSOLIDATED

In [ ]:
BASE = Path(r"D:\Thesis\Thesis_parquet")
t_df3 = BASE / "t_df3.parquet"
t_df3 = pd.read_parquet(t_df3, engine='pyarrow')

print(t_df3.shape)


import pandas as pd

FEATURES_TO_REMOVE = ['VENT_SUPPORT_TRR', 'INIT_HGT_CM_CALC', 'INIT_AGE', 'INIT_BMI_CALC', 'BMI_TCR', 'END_BMI_CALC', 'INOTROP_VASO_DIA_TCR', 'HGT_CM_TCR', 'HGT_CM_CALC', 'PERM_STATE_TRR', 'REGION', 'BMI_CALC']

# Loop to safely drop columns if they exist in the DataFrame
for var in FEATURES_TO_REMOVE:
    if var in t_df3.columns:
        t_df3 = t_df3.drop(columns=[var])
    else:
      print(f"Variable: {var} not found")

print(t_df3.shape)

(51506, 254)
(51506, 242)

In [ ]:
BASE_ROOT = Path("/content/drive/MyDrive/Thesis_parquet")

T_DF3_PATH = BASE_ROOT / "t_df3.parquet"

In [ ]:

import pandas as pd

FEATURES_TO_REMOVE = ['VENT_SUPPORT_TRR', 'INIT_HGT_CM_CALC', 'INIT_AGE', 'INIT_BMI_CALC', 'BMI_TCR', 'END_BMI_CALC', 'INOTROP_VASO_DIA_TCR', 'HGT_CM_TCR', 'HGT_CM_CALC', 'PERM_STATE_TRR', 'REGION', 'BMI_CALC']

# Loop to safely drop columns if they exist in the DataFrame
for var in FEATURES_TO_REMOVE:
    if var in t_df3.columns:
        t_df3 = t_df3.drop(columns=[var])
    else:
      print(f"Variable: {var} not found")

print(t_df3.shape)

Variable: VENT_SUPPORT_TRR not found
Variable: INIT_HGT_CM_CALC not found
Variable: INIT_AGE not found
Variable: INIT_BMI_CALC not found
Variable: BMI_TCR not found
Variable: END_BMI_CALC not found
Variable: INOTROP_VASO_DIA_TCR not found
Variable: HGT_CM_TCR not found
Variable: HGT_CM_CALC not found
Variable: PERM_STATE_TRR not found
Variable: REGION not found
Variable: BMI_CALC not found
(51506, 242)

In [ ]:
'VENT_SUPPORT_TRR' in t_df3.columns

False

In [ ]:
# ==============================================================================
# SEGMENT 5 — CONSOLIDATED, BUG-FIXED
# FEATURE ENGINEERING & PREPROCESSING
# ==============================================================================
#
# This replaces V3. Two confirmed bugs are fixed at the root, not patched:
#
#   BUG 1 (join-order): t_df3 is now indexed by TRR_ID_CODE immediately after
#   loading (Phase 2), not deferred to Phase 6. V3 joined the sensitization
#   features (Phase 4O) BEFORE t_df3 had a real index, silently matching row
#   POSITION against pra_source's real TRR_ID_CODE index -- which is why every
#   SENSITIZATION_TIER came back NaN in V3's run. Indexing early means every
#   downstream join in Phase 4 lines up correctly.
#
#   BUG 2 (wrong source): CPRA/PRA1/PRA2 do not exist in t_df3 -- confirmed
#   back in Segment 3, they were deliberately routed to pra_source only.
#   Removed from the whitelist. Phase 4D (sensitization_severity) is REMOVED
#   entirely rather than patched: once Bug 1 is fixed, it would just be a
#   redundant, highly-correlated duplicate of SENSITIZATION_PEAK/RECENT below.
#
# DESIGN DECISION (not a bug fix): the 3-year matrices reuse the 1-year
# TRAIN-FITTED preprocessing pipeline rather than fitting independently.
# 3-year training patients are a confirmed subset of 1-year training patients
# (same pre-2018-10-18 window), so this introduces no population mismatch --
# and it removes a real confound from the cross-horizon SHAP comparison in
# Segment 7: if each horizon had its own independently-fit imputation and
# scaling, an observed SHAP difference between horizons could partly reflect
# different representations rather than a genuine difference in what the
# model learned. One shared fitted pipeline rules that out.
#
# SIDE EFFECT: because TRR_ID_CODE is the DataFrame index throughout (never
# discarded via reset_index(drop=True)), Segment 6's prediction-CSV ID bug
# fixes itself automatically on the next retrain, with no changes to Segment
# 6's code. The separate segment5_id_patch.py given previously is superseded
# by this file -- do not apply both.
#
# Everything below marked "VERIFIED WORKING" reproduces V3 logic unchanged,
# confirmed correct by V3's own printed run output.
# ==============================================================================

import json
import pickle
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer, SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)


# ==============================================================================
# PHASE 0 — PATHS / INPUTS
# ==============================================================================

BASE_ROOT = Path("/content/drive/MyDrive/Thesis_parquet")

T_DF3_PATH = BASE_ROOT / "t_df3.parquet"
OUTCOME_1Y_PATH = BASE_ROOT / "outcome_1y.parquet"
OUTCOME_3Y_PATH = BASE_ROOT / "outcome_3y.parquet"
PRA_SOURCE_PATH = BASE_ROOT / "pra_source.parquet"

MODEL_READY_ROOT = BASE_ROOT / "model_ready"

SPLIT_DATE = pd.Timestamp("2018-10-18")
MISSING_THRESHOLD = 0.75
RARE_THRESHOLD = 0.01
NZV_THRESHOLD = 0.995
RANDOM_STATE = 42
MICE_MAX_ITER = 5  # trimmed from V3's 10, disclosed time-saving compromise --
                   # revert to 10 after the defense if you want the fuller fit


# ==============================================================================
# PHASE 1 — EXPLICIT FEATURE WHITELIST
# ==============================================================================
# CPRA/PRA1/PRA2 REMOVED here (Bug 2) -- they are not in t_df3 by design.
# Sensitization enters modeling only via the correctly-sourced Phase 4O
# features below, computed from pra_source.
# ==============================================================================

RECIPIENT_CLINICAL = [
    "INIT_AGE", "GENDER", "BMI_TCR", "DIAB", "DIAL_PRIOR_TX",
    "DIAL_AFTER_LIST", "DAYSWAIT_CHRON", "INOTROPIC", "LIFE_SUP_TCR",
    "IMPL_DEFIBRIL", "PREV_TX", "MALIG_TCR", "CEREB_VASC",
    "MED_COND_TRR", "FUNC_STAT_TRR", "VENT_SUPPORT_TRR",
    "VAD_DEVICE_TY_TRR", "WORK_INCOME_TCR", "PRI_PAYMENT_TCR", "ETHCAT",
    "CREAT_TRR", "TBILI_TRR", "ALBUMIN_TRR", "SGPT_TRR",
    "INOTROP_VASO_SYS_TRR", "INOTROP_VASO_CO_TRR", "INFECT_IV_DRUG_TRR",
]

RECIPIENT_IMMUNOLOGIC = [
    "DON_RETYP", "CRSMATCH_DONE",
]  # CPRA/PRA1/PRA2 removed -- see Bug 2 note above

DONOR_CHARACTERISTICS = [
    "AGE_DON", "GENDER_DON", "ETHCAT_DON", "BMI_DON", "COD_CAD_DON",
    "DIABETES_DON", "HIST_HYPERTENS_DON", "HIST_COCAINE_DON",
    "ALCOHOL_HEAVY_DON", "HIST_CIG_DON", "CDC_RISK_HIV_DON",
    "INOTROP_SUPPORT_DON", "ANTIHYPE_DON", "CREAT_DON", "SGOT_DON",
    "SGPT_DON", "NON_HRT_DON", "TATTOOS", "PROTEIN_URINE",
    "CARDARREST_NEURO", "PT_DIURETICS_DON", "PT_STEROIDS_DON",
    "DDAVP_DON", "HEPARIN_DON", "LV_EJECT_METH",
]

DONOR_RECIPIENT_PAIR = ["ISCHTIME"]

OPERATIVE_SOCIAL = [
    "SHARE_TY", "TX_PROCEDUR_TY", "PRIOR_CARD_SURG_TCR", "STERNOTOMY_TCR",
]

ALL_BASE_FEATURE_COLS = list(dict.fromkeys(
    RECIPIENT_CLINICAL + RECIPIENT_IMMUNOLOGIC + DONOR_CHARACTERISTICS
    + DONOR_RECIPIENT_PAIR + OPERATIVE_SOCIAL
))


# ==============================================================================
# PHASE 1B — EXPLICIT LEAKAGE / AUDIT / ID EXCLUSIONS  [VERIFIED WORKING]
# ==============================================================================

LEAKAGE_COLUMNS = {
    "TRTREJ1Y", "TRTREJ3Y", "TRTREJ5Y",
    "GSTATUS", "GTIME", "PSTATUS", "PTIME",
    "PX_STAT", "PX_STAT_DATE", "DEATH_DATE", "COMPOSITE_DEATH_DATE",
    "GRF_FAIL_CAUSE", "GRF_FAIL_DATE", "RETXDATE", "GRF_STAT",
    "DISCHARGE_DATE",
    "PGDPOSTTX24", "PGDPOSTTX72", "LVEFPOSTTX24", "LVEFPOSTTX72",
    "ECMOPOSTTX24", "ECMOPOSTTX72", "IABPPOSTTX24", "IABPPOSTTX72",
    "PST_AIRWAY", "PST_STROKE", "PST_DIAL", "PST_PACEMAKER",
    "ECMO_72HOURS", "INTUBATED_72HOURS", "REINTUBATED", "INHALEDNO_72HOURS",
    "REJECTION_1YR", "REJECTION_3YR", "EVALUABLE_1YR", "EVALUABLE_3YR",
    "OUTCOME_SOURCE", "OUTCOME_SOURCE_3YR",
    "MAX_FOLLOWUP_DAYS", "CASE_TYPE", "DATA_CONFIDENCE", "ERA", "TX_YEAR",
    "TX_DATE",
    "ABO_MAT",
    "CMV_STATUS_SOURCE", "SENSITIZATION_SOURCE",
}

ID_COLUMNS = {
    "TRR_ID_CODE", "PT_CODE", "DONOR_ID",
    "INIT_OPO_CTR_CODE", "END_OPO_CTR_CODE", "LISTING_CTR_CODE",
}

LEAKAGE_KEYWORDS = [
    "POSTTX", "GSTATUS", "GTIME", "PSTATUS", "PTIME",
    "PX_STAT", "GRF_FAIL", "GRF_STAT", "RETXDATE",
]


# ==============================================================================
# PHASE 2 — LOAD DATA, INDEX BY TRR_ID_CODE IMMEDIATELY (BUG 1 FIX), PRE-FLIGHT
# ==============================================================================

print("=" * 78)
print("SEGMENT 5 — CONSOLIDATED, BUG-FIXED")
print("=" * 78)

for path in [T_DF3_PATH, OUTCOME_1Y_PATH, OUTCOME_3Y_PATH, PRA_SOURCE_PATH]:
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")

t_df3 = pd.read_parquet(T_DF3_PATH, engine="pyarrow")
outcome_1y_df = pd.read_parquet(OUTCOME_1Y_PATH, engine="pyarrow")
outcome_3y_df = pd.read_parquet(OUTCOME_3Y_PATH, engine="pyarrow")
pra_source = pd.read_parquet(PRA_SOURCE_PATH, engine="pyarrow")

print(f"\nInput t_df3        : {t_df3.shape}")
print(f"Input outcome_1y   : {outcome_1y_df.shape}")
print(f"Input outcome_3y   : {outcome_3y_df.shape}")
print(f"Input pra_source   : {pra_source.shape}")

for name, df_check, col in [
    ("t_df3", t_df3, "TRR_ID_CODE"), ("outcome_1y", outcome_1y_df, "TRR_ID_CODE"),
    ("outcome_3y", outcome_3y_df, "TRR_ID_CODE"), ("pra_source", pra_source, "TRR_ID_CODE"),
]:
    assert col in df_check.columns, f"{col} missing from {name}."
    assert df_check[col].is_unique, f"Duplicate {col} in {name}."

assert "OUTCOME_1Y" in outcome_1y_df.columns, "OUTCOME_1Y missing."
assert "OUTCOME_3Y" in outcome_3y_df.columns, "OUTCOME_3Y missing."
assert "TX_DATE" in t_df3.columns, "TX_DATE missing; temporal split cannot be performed."

for c in ["DEATH_DATE", "LIV_DON_TY"]:
    if c in t_df3.columns:
        print(f"  Defensive drop: {c}")
        t_df3 = t_df3.drop(columns=[c])

suspect = [c for c in t_df3.columns if any(k.upper() in c.upper() for k in LEAKAGE_KEYWORDS)]
print(f"\nLeakage-keyword scan found {len(suspect)} source columns:")
print(suspect if suspect else "  None")

assert not (set(ALL_BASE_FEATURE_COLS) & LEAKAGE_COLUMNS), (
    "Internal configuration error: a whitelisted base feature is listed as leakage."
)

# --- BUG 1 FIX: index by TRR_ID_CODE HERE, before any feature engineering,
#     not deferred to a later phase. Every join below now lines up correctly. ---
t_df3 = t_df3.set_index("TRR_ID_CODE", verify_integrity=True)
print(f"\nt_df3 indexed by TRR_ID_CODE: {t_df3.shape}")

# --- Fuzzy-match helper for whitelisted columns that may exist under a
#     different name. This SUGGESTS candidates for manual review only --
#     it does not assert a rename. Verify each suggestion against the real
#     data dictionary before trusting it. ---
def suggest_aliases(missing_cols, real_columns, min_token_len=4):
    real_upper = {c: c.upper() for c in real_columns}
    suggestions = {}
    for missing in missing_cols:
        tokens = [t for t in missing.upper().replace("_", " ").split() if len(t) >= min_token_len]
        candidates = [c for c, cu in real_upper.items() if any(t in cu for t in tokens)]
        suggestions[missing] = candidates
    return suggestions


# ==============================================================================
# PHASE 3 — HLA MISMATCH COMPUTATION  [VERIFIED WORKING -- unchanged from V3]
# ==============================================================================
# Kept as a row-wise loop rather than vectorized. A vectorized rewrite would
# need to correctly reproduce the homozygous-donor deduplication behavior
# (len(donor_set - recipient_set), not a naive per-allele sum, which would
# double-count a homozygous donor's single mismatched antigen). This is
# already confirmed correct by its own prior run (plausible 2/1/0 mismatch
# distribution across ~45,000 computed patients per locus) -- not worth the
# risk of a quiet bug under time pressure. Revisit for speed after the defense.
# ==============================================================================

print("\n" + "=" * 78)
print("PHASE 3 — HLA MISMATCH COMPUTATION")
print("=" * 78)

HLA_UNKNOWN_CODES = {0, 95, 96, 97, 98, 99}
HLA_UNKNOWN_THRESHOLD = 1000

HLA_LOCI = {
    "A": ("DA1", "DA2", "RA1", "RA2"),
    "B": ("DB1", "DB2", "RB1", "RB2"),
    "DR": ("DDR1", "DDR2", "RDR1", "RDR2"),
}


def _code_to_numeric(series):
    s = pd.to_numeric(series, errors="coerce")
    s = s.where(~s.isin(HLA_UNKNOWN_CODES), np.nan)
    s = s.where(s < HLA_UNKNOWN_THRESHOLD, np.nan)
    s = s.where(s > 0, np.nan)
    return s


def _locus_mismatch(d1, d2, r1, r2):
    mm = pd.Series(np.nan, index=d1.index, dtype="float32")
    for idx in d1.index:
        donor = {a for a in [d1.loc[idx], d2.loc[idx]] if pd.notna(a)}
        recip = {a for a in [r1.loc[idx], r2.loc[idx]] if pd.notna(a)}
        if donor and recip:
            mm.loc[idx] = float(len(donor - recip))
    return mm


for locus, (d1c, d2c, r1c, r2c) in HLA_LOCI.items():
    required = [d1c, d2c, r1c, r2c]
    if all(c in t_df3.columns for c in required):
        mm = _locus_mismatch(
            _code_to_numeric(t_df3[d1c]), _code_to_numeric(t_df3[d2c]),
            _code_to_numeric(t_df3[r1c]), _code_to_numeric(t_df3[r2c]),
        )
        t_df3[f"HLA_{locus}_mismatch"] = mm
        print(f"  HLA-{locus}: computed={mm.notna().sum():,}, "
              f"distribution={mm.value_counts(dropna=True).to_dict()}")
    else:
        missing = [c for c in required if c not in t_df3.columns]
        print(f"  WARNING HLA-{locus}: missing source columns: {missing}")
        print(f"    Candidates: {suggest_aliases(missing, t_df3.columns)}")

if all(f"HLA_{l}_mismatch" in t_df3.columns for l in ["A", "B", "DR"]):
    W_A, W_B, W_DR = 0.5, 1.0, 2.0
    W_TOTAL = W_A + W_B + W_DR
    hla_a, hla_b, hla_dr = t_df3["HLA_A_mismatch"], t_df3["HLA_B_mismatch"], t_df3["HLA_DR_mismatch"]
    weight_known = (W_DR * hla_dr.notna().astype(float) + W_B * hla_b.notna().astype(float)
                    + W_A * hla_a.notna().astype(float))
    raw_sum = W_DR * hla_dr.fillna(0) + W_B * hla_b.fillna(0) + W_A * hla_a.fillna(0)
    t_df3["HLA_total_mismatch_weighted"] = raw_sum.where(weight_known > 0, np.nan).astype("float32")
    print(f"  Weighted HLA total: all_loci={(weight_known == W_TOTAL).sum():,}, "
          f"partial={((weight_known > 0) & (weight_known < W_TOTAL)).sum():,}, "
          f"none={(weight_known == 0).sum():,}")
else:
    print("  WARNING: HLA_total_mismatch_weighted not created; one or more loci unavailable.")


# ==============================================================================
# PHASE 4 — FEATURE ENGINEERING
# ==============================================================================

print("\n" + "=" * 78)
print("PHASE 4 — FEATURE ENGINEERING")
print("=" * 78)

# ---- 4A. Ischemic-time alias discovery  [VERIFIED WORKING] ----
_isch_aliases = ["ISCHTIME", "ISCH_TIME", "COLD_ISCH_TIME", "ISCHEMIC_TIME", "COLD_ISCH", "ISCH_TIME_MIN"]
_isch_col = next((c for c in _isch_aliases if c in t_df3.columns), None)
if _isch_col and _isch_col != "ISCHTIME":
    t_df3 = t_df3.rename(columns={_isch_col: "ISCHTIME"})
    if _isch_col in ALL_BASE_FEATURE_COLS:
        ALL_BASE_FEATURE_COLS[ALL_BASE_FEATURE_COLS.index(_isch_col)] = "ISCHTIME"
    elif "ISCHTIME" not in ALL_BASE_FEATURE_COLS:
        ALL_BASE_FEATURE_COLS.append("ISCHTIME")
    print(f"  Renamed ischemic-time alias: {_isch_col} -> ISCHTIME")
elif _isch_col is None:
    print(f"  WARNING: no ischemic-time column found; tried {_isch_aliases}")

# ---- 4B. Ischemic time x HLA weighted mismatch  [VERIFIED WORKING] ----
if "ISCHTIME" in t_df3.columns and "HLA_total_mismatch_weighted" in t_df3.columns:
    isch = pd.to_numeric(t_df3["ISCHTIME"], errors="coerce").clip(0, 600)
    t_df3["ischemic_time_HLA_interaction"] = (isch * t_df3["HLA_total_mismatch_weighted"]).astype("float32")
    print("  Built ischemic_time_HLA_interaction")
else:
    print("  WARNING: ischemic_time_HLA_interaction not built.")

# ---- 4C. Donor-recipient age gap  [VERIFIED WORKING] ----
if "AGE_DON" in t_df3.columns and "INIT_AGE" in t_df3.columns:
    t_df3["donor_recipient_age_gap"] = (
        pd.to_numeric(t_df3["AGE_DON"], errors="coerce") - pd.to_numeric(t_df3["INIT_AGE"], errors="coerce")
    ).abs().astype("float32")
    print("  Built donor_recipient_age_gap")
else:
    print("  WARNING: donor_recipient_age_gap not built.")

# ---- 4D. [REMOVED] sensitization_severity ----
# Removed entirely (Bug 2). It depended on CPRA/PRA1 existing directly in
# t_df3, which they never did (Segment 3 routed them to pra_source only).
# Once Bug 1's join fix is applied, this would just duplicate
# SENSITIZATION_PEAK/RECENT below at high correlation. If your old SHAP
# table's "sensitization_severity" line reappears, it will do so as
# SENSITIZATION_PEAK or SENSITIZATION_RECENT under correct computation --
# not under this name, and this response does not claim to have reconstructed
# the exact original formula.
print("  sensitization_severity: intentionally removed (see Bug 2 note in header).")

# ---- 4E. Metabolic burden  [VERIFIED conditional logic; source cols may be misnamed] ----
_creat_col = next((c for c in ["CREAT_TRR", "CREATININE_TRR", "CREAT_TCR"] if c in t_df3.columns), None)
_tbili_col = next((c for c in ["TBILI_TRR", "BILIRUBIN_TRR", "TBILI_TCR"] if c in t_df3.columns), None)
if _creat_col and _tbili_col:
    creat = pd.to_numeric(t_df3[_creat_col], errors="coerce").clip(0, 30)
    tbili = pd.to_numeric(t_df3[_tbili_col], errors="coerce").clip(0, 50)
    diab_num = pd.to_numeric(t_df3.get("DIAB", pd.Series(np.nan, index=t_df3.index)), errors="coerce")
    diab_bin = diab_num.isin([2.0, 3.0, 4.0]).astype("float32")
    t_df3["metabolic_burden"] = (creat + tbili + diab_bin).astype("float32")
    print("  Built metabolic_burden")
else:
    print(f"  WARNING: metabolic_burden not built ({_creat_col=}, {_tbili_col=})")
    if not _tbili_col:
        print(f"    TBILI candidates: {suggest_aliases(['TBILI_TRR'], t_df3.columns)}")

# ---- 4F. Waitlist severity score  [VERIFIED WORKING] ----
if "DAYSWAIT_CHRON" in t_df3.columns:
    days = pd.to_numeric(t_df3["DAYSWAIT_CHRON"], errors="coerce").clip(0)
    if "MED_COND_TRR" in t_df3.columns:
        cond = pd.to_numeric(t_df3["MED_COND_TRR"], errors="coerce")
        cond_w = cond.map({1.0: 3.0, 2.0: 2.0, 3.0: 1.0})
        t_df3["waitlist_severity_score"] = (days * cond_w).astype("float32")
        print("  Built waitlist_severity_score using MED_COND_TRR")
    else:
        t_df3["waitlist_severity_score"] = days.astype("float32")
        print("  Built waitlist_severity_score using DAYSWAIT_CHRON only")
else:
    print("  WARNING: waitlist_severity_score not built.")

# ---- 4G. Exact-policy transplant era indicator  [VERIFIED WORKING] ----
# NOTE: this correctly gets dropped by the train-only constant-feature filter
# in Phase 7 (train = pre-2018-10-18 only, so this is 0 for the entire
# training partition by construction). That is expected, not a bug.
tx_dt_full = pd.to_datetime(t_df3["TX_DATE"], errors="coerce")
assert tx_dt_full.notna().all(), "TX_DATE contains null/unparseable values after cohort construction."
t_df3["era_post_2018"] = (tx_dt_full >= SPLIT_DATE).astype("float32")
print(f"  Built era_post_2018: pre={(t_df3['era_post_2018'] == 0).sum():,}, "
      f"post={(t_df3['era_post_2018'] == 1).sum():,} (will be dropped as train-constant, expected)")

# ---- 4H. Donor-recipient sex mismatch  [VERIFIED WORKING] ----
if "GENDER" in t_df3.columns and "GENDER_DON" in t_df3.columns:
    g_r, g_d = t_df3["GENDER"].astype(object), t_df3["GENDER_DON"].astype(object)
    sex_f_to_m = ((g_d == "F") & (g_r == "M")).astype("float32")
    sex_any_mm = (g_d != g_r).astype("float32")
    null_m = g_r.isna() | g_d.isna()
    sex_f_to_m.loc[null_m] = np.nan
    sex_any_mm.loc[null_m] = np.nan
    t_df3["sex_mismatch_F_to_M"] = sex_f_to_m
    t_df3["sex_mismatch_any"] = sex_any_mm
    print("  Built sex_mismatch_F_to_M and sex_mismatch_any")
else:
    print("  WARNING: sex mismatch features not built.")

# ---- 4I. Donor-recipient weight ratio  [conditional; source col may be misnamed] ----
if "WGT_KG_TCR" in t_df3.columns:
    _don_wgt_col = next((c for c in ["WGT_KG_DON", "DON_WGT_KG", "DONOR_WGT_KG"] if c in t_df3.columns), None)
    if _don_wgt_col:
        don_w = pd.to_numeric(t_df3[_don_wgt_col], errors="coerce").clip(20, 300)
        rec_w = pd.to_numeric(t_df3["WGT_KG_TCR"], errors="coerce")
        with np.errstate(divide="ignore", invalid="ignore"):
            ratio = don_w / rec_w
        t_df3["donor_recipient_weight_ratio"] = ratio.replace([np.inf, -np.inf], np.nan).clip(0.3, 3.0).astype("float32")
        print("  Built donor_recipient_weight_ratio")
    else:
        print(f"  WARNING: donor weight source column not found. "
              f"Candidates: {suggest_aliases(['WGT_KG_DON'], t_df3.columns)}")
else:
    print("  WARNING: recipient weight WGT_KG_TCR not found.")

# ---- 4J. eGFR, CKD-EPI 2021 race-free equation  [VERIFIED WORKING] ----
if _creat_col and "INIT_AGE" in t_df3.columns and "GENDER" in t_df3.columns:
    scr = pd.to_numeric(t_df3[_creat_col], errors="coerce").clip(0.1, 30)
    age = pd.to_numeric(t_df3["INIT_AGE"], errors="coerce")
    female = t_df3["GENDER"].astype(object).eq("F")
    kappa = np.where(female, 0.7, 0.9)
    alpha = np.where(female, -0.241, -0.302)
    sex_multiplier = np.where(female, 1.012, 1.0)
    scr_k = scr / kappa
    egfr = (142 * np.minimum(scr_k, 1.0) ** alpha * np.maximum(scr_k, 1.0) ** (-1.200)
            * (0.9938 ** age) * sex_multiplier)
    t_df3["eGFR_CKD_EPI"] = egfr.clip(0, 200).astype("float32")
    print("  Built eGFR_CKD_EPI")
else:
    print("  WARNING: eGFR_CKD_EPI not built.")

# ---- 4K. Diagnosis recoding  [VERIFIED WORKING] ----
if "THORACIC_DGN" in t_df3.columns:
    dgn = pd.to_numeric(t_df3["THORACIC_DGN"], errors="coerce")
    t_df3["diagnosis_group"] = "Other"
    t_df3.loc[dgn.isin([1007, 1200]), "diagnosis_group"] = "Ischemic_CMP"
    DILATED_CODES = [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1008, 1009, 1010, 1049]
    t_df3.loc[dgn.isin(DILATED_CODES), "diagnosis_group"] = "Dilated_CMP"
    RESTRICTIVE_CODES = [1050, 1051, 1052, 1053, 1054, 1099]
    t_df3.loc[dgn.isin(RESTRICTIVE_CODES), "diagnosis_group"] = "Restrictive_CMP"
    RETX_CODES = [1100, 1101, 1102, 1103, 1104, 1105, 1106, 1199]
    t_df3.loc[dgn.isin(RETX_CODES), "diagnosis_group"] = "Retransplant"
    t_df3.loc[dgn == 1201, "diagnosis_group"] = "Hypertrophic_CMP"
    t_df3.loc[dgn == 1202, "diagnosis_group"] = "Valvular"
    t_df3.loc[dgn.isin([1203, 1205, 1206, 1207]), "diagnosis_group"] = "Congenital"
    t_df3.loc[dgn.isna(), "diagnosis_group"] = np.nan
    t_df3["diagnosis_group"] = t_df3["diagnosis_group"].astype("category")
    print("  diagnosis_group distribution:", t_df3["diagnosis_group"].value_counts(dropna=False).to_dict())
else:
    print("  WARNING: THORACIC_DGN not present; diagnosis_group not built.")

# ---- 4L. ABO compatibility score  [VERIFIED WORKING] ----
if "ABO_MAT" in t_df3.columns:
    abo_raw = t_df3["ABO_MAT"].astype(object)
    abo_norm = abo_raw.map(lambda x: x.upper() if isinstance(x, str) else x)
    t_df3["ABO_compatibility_score"] = abo_norm.map(
        {"IDENTICAL": 0, "COMPATIBLE": 1, "INCOMPATIBLE": 2}
    ).astype("float32")
    n_source, n_mapped = int(abo_raw.notna().sum()), int(t_df3["ABO_compatibility_score"].notna().sum())
    print(f"  ABO_compatibility_score mapped {n_mapped:,}/{n_source:,} non-null ABO_MAT values")
else:
    print("  WARNING: ABO_MAT not present; ABO_compatibility_score not built.")

# ---- 4M. Sensitization-availability flags  [VERIFIED WORKING] ----
# NOTE: sources here are pra_source's own fields, checked by name only for
# an availability flag -- the values themselves are still pulled correctly
# from pra_source in Phase 4O below, not from t_df3.
for src, resolved_in_pra in [("CPRA", "CPRA"), ("PRA1", "PRAMR"), ("PRA2", "PRAPK")]:
    if resolved_in_pra in pra_source.columns:
        avail = pra_source.set_index("TRR_ID_CODE")[resolved_in_pra].notna().astype("float32")
        t_df3[f"{src}_available"] = avail.reindex(t_df3.index)
        print(f"  Built {src}_available ({t_df3[f'{src}_available'].mean() * 100:.1f}% present)")

# ---- 4N. CMV unified status  [VERIFIED WORKING] ----
if all(c in t_df3.columns for c in ["CMV_IGG", "CMV_IGM", "CMV_STATUS"]):
    cmv = t_df3["CMV_STATUS"].astype(object)
    cmv = cmv.map(lambda x: "POSITIVE" if x == "P" else "NEGATIVE" if x == "N" else x)
    legacy = t_df3["CMV_STATUS"].isna() & (t_df3["CMV_IGG"].notna() | t_df3["CMV_IGM"].notna())

    def _derive_cmv(igg, igm):
        if igg == "P" or igm == "P":
            return "POSITIVE"
        if igg == "N" or igm == "N":
            return "NEGATIVE"
        return np.nan

    derived = t_df3.loc[legacy].apply(lambda r: _derive_cmv(r["CMV_IGG"], r["CMV_IGM"]), axis=1)
    cmv.loc[legacy] = derived
    t_df3["CMV_STATUS_UNIFIED"] = cmv.astype("category")
    t_df3["CMV_STATUS_SOURCE"] = np.where(t_df3["CMV_STATUS"].notna(), "unified_field", "derived_igg_igm")
    t_df3 = t_df3.drop(columns=["CMV_IGG", "CMV_IGM", "CMV_STATUS"])
    print("  Built CMV_STATUS_UNIFIED:", t_df3["CMV_STATUS_UNIFIED"].value_counts(dropna=False).to_dict())
else:
    print("  CMV unified feature skipped: one or more CMV source columns absent.")

# ---- 4O. Recent/peak sensitization features  [BUG 1 FIXED: t_df3 now pre-indexed] ----
pra_required = ["TRR_ID_CODE", "CPRA", "CPRA_PEAK", "PRAMR", "PRAPK"]
missing_pra = [c for c in pra_required if c not in pra_source.columns]
if missing_pra:
    print(f"  WARNING: pra_source is missing required columns: {missing_pra}. Skipping.")
else:
    sens = pra_source[["TRR_ID_CODE", "CPRA", "CPRA_PEAK", "PRAMR", "PRAPK"]].copy()
    sens = sens.set_index("TRR_ID_CODE", verify_integrity=True)

    sens["SENSITIZATION_RECENT"] = sens["CPRA"].where(sens["CPRA"].notna(), sens["PRAMR"]).clip(0, 100)
    sens["SENSITIZATION_PEAK"] = sens["CPRA_PEAK"].where(sens["CPRA_PEAK"].notna(), sens["PRAPK"]).clip(0, 100)

    def _sens_tier(x):
        if pd.isna(x):
            return np.nan
        if x >= 80:
            return "highly_sensitized"
        if x >= 10:
            return "moderately_sensitized"
        return "nonsensitized"

    sens["SENSITIZATION_TIER"] = pd.to_numeric(sens["SENSITIZATION_PEAK"], errors="coerce").apply(_sens_tier).astype("category")
    sens["SENSITIZATION_SOURCE"] = np.where(sens["CPRA"].notna(), "CPRA", "PRA_legacy")
    sens = sens[["SENSITIZATION_RECENT", "SENSITIZATION_PEAK", "SENSITIZATION_TIER", "SENSITIZATION_SOURCE"]]

    # t_df3 is ALREADY indexed by TRR_ID_CODE (Phase 2) -- this join now
    # correctly matches real patient IDs on both sides, unlike V3.
    t_df3 = t_df3.join(sens, how="left", validate="one_to_one")
    print("  Built SENSITIZATION_TIER:", t_df3["SENSITIZATION_TIER"].value_counts(dropna=False).to_dict())
    n_matched = t_df3["SENSITIZATION_PEAK"].notna().sum()
    print(f"  Sensitization join matched {n_matched:,}/{len(t_df3):,} patients "
          f"(expect a large majority, NOT the all-NaN failure seen in V3)")

# ---- 4P. Donor hemodynamic delta features  [VERIFIED WORKING] ----
HEMO_PAIRS = [
    ("CARD_IDX_INIT_DON", "CARD_IDX_POST_DON", "CARD_IDX_DELTA_DON"),
    ("CARDIAC_OUTPUT_CATH_INIT_DON", "CARDIAC_OUTPUT_CATH_POST_DON", "CARDIAC_OUTPUT_DELTA_DON"),
    ("CVP_CATH_INIT_DON", "CVP_CATH_POST_DON", "CVP_DELTA_DON"),
    ("DIAST_PA_CATH_INIT_DON", "DIAST_PA_CATH_POST_DON", "DIAST_PA_DELTA_DON"),
    ("MAP_INIT_DON", "MAP_POST_DON", "MAP_DELTA_DON"),
    ("PCWP_INIT_DON", "PCWP_POST_DON", "PCWP_DELTA_DON"),
    ("SVR_INIT_DON", "SVR_POST_DON", "SVR_DELTA_DON"),
    ("SYST_PA_CATH_INIT_DON", "SYST_PA_CATH_POST_DON", "SYST_PA_DELTA_DON"),
]
hemo_built = []
for init_col, post_col, delta_col in HEMO_PAIRS:
    if init_col in t_df3.columns and post_col in t_df3.columns:
        t_df3[delta_col] = (pd.to_numeric(t_df3[post_col], errors="coerce")
                             - pd.to_numeric(t_df3[init_col], errors="coerce")).astype("float32")
        hemo_built.append(delta_col)
print(f"  Donor hemodynamic deltas built: {len(hemo_built)}/{len(HEMO_PAIRS)} "
      f"(expect most dropped later for >75% missingness in train, matches V3)")


# ==============================================================================
# PHASE 5 — FINAL EXPLICIT MODEL FEATURE LIST
# ==============================================================================

ENGINEERED_FEATURES = [
    "HLA_A_mismatch", "HLA_B_mismatch", "HLA_DR_mismatch", "HLA_total_mismatch_weighted",
    "ischemic_time_HLA_interaction", "donor_recipient_age_gap", "metabolic_burden",
    "waitlist_severity_score", "era_post_2018", "sex_mismatch_F_to_M", "sex_mismatch_any",
    "donor_recipient_weight_ratio", "eGFR_CKD_EPI", "diagnosis_group", "ABO_compatibility_score",
    "CPRA_available", "PRA1_available", "PRA2_available",
    "CMV_STATUS_UNIFIED", "SENSITIZATION_RECENT", "SENSITIZATION_PEAK", "SENSITIZATION_TIER",
    *hemo_built,
]
ENGINEERED_FEATURES = list(dict.fromkeys(
    c for c in ENGINEERED_FEATURES if c in t_df3.columns and c not in LEAKAGE_COLUMNS and c not in ID_COLUMNS
))

PRESENT_BASE = [c for c in ALL_BASE_FEATURE_COLS if c in t_df3.columns]
ABSENT_BASE = [c for c in ALL_BASE_FEATURE_COLS if c not in t_df3.columns]

print(f"\nBase features present : {len(PRESENT_BASE)}/{len(ALL_BASE_FEATURE_COLS)}")
if ABSENT_BASE:
    print("Absent whitelisted columns and fuzzy-match candidates (VERIFY before trusting):")
    alias_suggestions = suggest_aliases(ABSENT_BASE, t_df3.columns)
    for c in ABSENT_BASE:
        print(f"  - {c}  ->  candidates: {alias_suggestions.get(c, [])}")

print(f"Engineered features   : {len(ENGINEERED_FEATURES)}")
for c in ENGINEERED_FEATURES:
    print(f"  + {c}")

CANDIDATE_FEATURES = list(dict.fromkeys(PRESENT_BASE + ENGINEERED_FEATURES))
CANDIDATE_FEATURES = [c for c in CANDIDATE_FEATURES if c not in LEAKAGE_COLUMNS and c not in ID_COLUMNS and c != "TX_DATE"]

keyword_in_candidates = [c for c in CANDIDATE_FEATURES if any(k.upper() in c.upper() for k in LEAKAGE_KEYWORDS)]
if keyword_in_candidates:
    raise RuntimeError(f"Leakage-keyword features survived explicit selection: {keyword_in_candidates}")

print(f"\nFinal candidate feature count before split: {len(CANDIDATE_FEATURES)}")


# ==============================================================================
# PHASE 6 — OUTCOME ALIGNMENT
# ==============================================================================
# t_df3 is already indexed by TRR_ID_CODE (Phase 2) -- only the outcome
# frames need indexing here now.
# ==============================================================================

print("\n" + "=" * 78)
print("PHASE 6 — OUTCOME ALIGNMENT")
print("=" * 78)

out1 = outcome_1y_df.set_index("TRR_ID_CODE", verify_integrity=True)
out3 = outcome_3y_df.set_index("TRR_ID_CODE", verify_integrity=True)

missing_1y_features = [idx for idx in out1.index if idx not in t_df3.index]
if missing_1y_features:
    raise RuntimeError(f"{len(missing_1y_features)} outcome_1y IDs are absent from t_df3.")

dataset_1y = t_df3.join(out1[["OUTCOME_1Y"]], how="inner", validate="one_to_one")
assert len(dataset_1y) == len(out1), "1-year outcome merge changed row count."
assert dataset_1y["OUTCOME_1Y"].notna().all(), "OUTCOME_1Y contains null labels."

print(f"1-year modeling cohort : {len(dataset_1y):,}")
print(f"1-year outcome rate    : {dataset_1y['OUTCOME_1Y'].mean() * 100:.2f}% rejection")

common_3y = out3.index.intersection(t_df3.index)
print(f"3-year IDs              : {len(out3):,}")
print(f"3-year IDs absent t_df3 : {len(set(out3.index) - set(t_df3.index)):,}")


# ==============================================================================
# PHASE 7 — TEMPORAL SPLIT, TRAIN-ONLY CONSTANT / MISSINGNESS RULES
# [VERIFIED WORKING -- unchanged from V3]
# ==============================================================================

def split_and_clean(df, outcome_col, label):
    print("\n" + "=" * 78)
    print(f"PHASE 7 — {label}: TEMPORAL SPLIT & TRAIN-ONLY CLEANING")
    print("=" * 78)

    df = df.copy()
    tx_dt = pd.to_datetime(df["TX_DATE"], errors="coerce")
    if tx_dt.isna().any():
        raise RuntimeError(f"{label}: TX_DATE contains null/unparseable values.")

    train_mask = tx_dt <= SPLIT_DATE
    test_mask = tx_dt > SPLIT_DATE
    if not train_mask.any() or not test_mask.any():
        raise RuntimeError(f"{label}: empty train or test split.")

    X_all = df[CANDIDATE_FEATURES].copy()
    y_all = df[outcome_col].astype(int).copy()

    X_train, X_test = X_all.loc[train_mask].copy(), X_all.loc[test_mask].copy()
    y_train, y_test = y_all.loc[train_mask].copy(), y_all.loc[test_mask].copy()

    assert X_train.index.is_unique and X_test.index.is_unique
    assert set(X_train.index).isdisjoint(X_test.index)

    print(f"  Boundary : {SPLIT_DATE.date()}\n  Train    : {len(X_train):,}\n  Test     : {len(X_test):,}")
    print(f"  Train dates: {tx_dt.loc[train_mask].min().date()} to {tx_dt.loc[train_mask].max().date()}")
    print(f"  Test dates : {tx_dt.loc[test_mask].min().date()} to {tx_dt.loc[test_mask].max().date()}")
    print(f"  Train rejection rate: {y_train.mean() * 100:.2f}%\n  Test rejection rate : {y_test.mean() * 100:.2f}%")

    train_unique = X_train.nunique(dropna=True)
    constant_cols = train_unique[train_unique <= 1].index.tolist()
    if constant_cols:
        print(f"\n  Train-constant features dropped: {len(constant_cols)}")
        for c in constant_cols:
            print(f"    - {c}")
        X_train = X_train.drop(columns=constant_cols)
        X_test = X_test.drop(columns=[c for c in constant_cols if c in X_test.columns])

    miss_rate = X_train.isna().mean().sort_values(ascending=False)
    report = pd.DataFrame({
        "feature": miss_rate.index,
        "dtype": [str(X_train[c].dtype) for c in miss_rate.index],
        "n_missing_train": [int(X_train[c].isna().sum()) for c in miss_rate.index],
        "pct_missing_train": [round(float(miss_rate[c] * 100), 3) for c in miss_rate.index],
    })
    report["missing_band"] = pd.cut(
        miss_rate.values, bins=[-np.inf, 0.10, MISSING_THRESHOLD, np.inf],
        labels=["<10%", "10-<75%", ">=75%"], right=False,
    ).astype(str)

    high_missing = miss_rate[miss_rate >= MISSING_THRESHOLD].index.tolist()
    if high_missing:
        print(f"\n  High-missing features dropped (>= {MISSING_THRESHOLD:.0%} in TRAIN): {len(high_missing)}")
        for c in high_missing:
            print(f"    - {c}: {miss_rate[c] * 100:.2f}%")
        X_train = X_train.drop(columns=high_missing)
        X_test = X_test.drop(columns=[c for c in high_missing if c in X_test.columns])

    excluded_from_generic_missing_flags = {"CPRA_available", "PRA1_available", "PRA2_available"}
    remaining_missing = [c for c in X_train.columns if X_train[c].isna().any()]
    generic_missing_cols = []
    for c in remaining_missing:
        if c in excluded_from_generic_missing_flags:
            continue
        flag = f"{c}_MISSING"
        X_train[flag] = X_train[c].isna().astype("float32")
        X_test[flag] = X_test[c].isna().astype("float32")
        generic_missing_cols.append(c)
    print(f"  Generic missingness-indicator columns created: {len(generic_missing_cols)}")

    assert X_train.index.equals(y_train.index)
    assert X_test.index.equals(y_test.index)

    return {
        "X_train": X_train, "X_test": X_test, "y_train": y_train, "y_test": y_test,
        "tx_train": tx_dt.loc[train_mask], "tx_test": tx_dt.loc[test_mask],
        "report": report, "constant_cols": constant_cols,
        "high_missing_cols": high_missing, "generic_missing_cols": generic_missing_cols,
    }


# ==============================================================================
# PHASE 8 — FEATURE TYPE CLASSIFICATION  [VERIFIED WORKING -- unchanged from V3]
# ==============================================================================

ORDINAL_KNOWN = {
    "DIAB", "FUNC_STAT_TRR", "FUNC_STAT_TCR", "MED_COND_TRR", "VAD_DEVICE_TY_TRR",
    "PRI_PAYMENT_TCR", "SHARE_TY", "COD_CAD_DON", "LV_EJECT_METH", "TX_PROCEDUR_TY",
    "ABO_compatibility_score", "SENSITIZATION_TIER",
}
NOMINAL_KNOWN = {
    "ETHCAT", "ETHCAT_DON", "STERNOTOMY_TCR", "diagnosis_group",
    "CMV_STATUS_UNIFIED", "SENSITIZATION_SOURCE", "CMV_STATUS_SOURCE",
}


def classify_feature_types(X_train):
    binary_yn, ordinal, nominal, continuous = [], [], [], []
    for col in X_train.columns:
        s = X_train[col]
        dtype = str(s.dtype)
        if col in LEAKAGE_COLUMNS or col in ID_COLUMNS or col == "TX_DATE":
            continue
        if col in NOMINAL_KNOWN:
            nominal.append(col)
        elif col in ORDINAL_KNOWN:
            ordinal.append(col)
        elif dtype in ("bool", "boolean"):
            binary_yn.append(col)
        elif dtype in ("float16", "float32", "float64", "int8", "int16", "int32", "int64",
                       "uint8", "uint16", "uint32", "uint64"):
            continuous.append(col)
        elif "category" in dtype or dtype in ("object", "string"):
            vals = set(s.dropna().astype(str).unique())
            if vals <= {"Y", "N"} or vals <= {"0", "1"}:
                binary_yn.append(col)
            else:
                nominal.append(col)
        else:
            continuous.append(col)
    covered = set(binary_yn) | set(ordinal) | set(nominal) | set(continuous)
    assert covered == set(X_train.columns), "Feature type classification does not cover all model input columns."
    return binary_yn, ordinal, nominal, continuous


# ==============================================================================
# PHASE 9 — PRE-PIPELINE CATEGORY PREPARATION  [VERIFIED WORKING -- unchanged]
# ==============================================================================

def encode_binary_yn(df_in, cols):
    out = df_in.copy()
    for c in cols:
        if c not in out.columns:
            continue
        s = out[c].astype(object)
        normalized = s.map(lambda x: x.upper() if isinstance(x, str) else x)
        out[c] = normalized.map({"Y": 1.0, "N": 0.0, "1": 1.0, "0": 0.0, 1: 1.0, 0: 0.0,
                                  True: 1.0, False: 0.0}).astype("float32")
    return out


def consolidate_rare(train_df, test_df, cat_cols, threshold=RARE_THRESHOLD):
    tr, te, rare_map = train_df.copy(), test_df.copy(), {}
    for c in cat_cols:
        if c not in tr.columns:
            continue
        freq = tr[c].value_counts(normalize=True, dropna=True)
        rare = freq[freq < threshold].index.tolist()
        if rare:
            tr[c] = tr[c].astype(object).replace(rare, "Other")
            te[c] = te[c].astype(object).replace(rare, "Other")
            rare_map[c] = [str(v) for v in rare]
    return tr, te, rare_map


def cast_cats_to_str(df_in, cols):
    out = df_in.copy()
    for c in cols:
        if c in out.columns:
            out[c] = out[c].map(str, na_action="ignore")
    return out


def ordered_categories_from_train(train_df, cols, ordinal_cols):
    result = []
    for c in cols:
        if c not in train_df.columns:
            result.append([])
            continue
        s = train_df[c].astype(object)
        if s.dropna().empty:
            filled = pd.Series(["MISSING"] * len(s), index=s.index, dtype=object)
        else:
            mode = s.mode(dropna=True)
            filled = s.fillna(mode.iloc[0] if not mode.empty else "MISSING")
        values = list(dict.fromkeys(filled.astype(str).tolist()))

        if c in ordinal_cols:
            if c == "SENSITIZATION_TIER":
                preferred = ["nonsensitized", "moderately_sensitized", "highly_sensitized"]
                ordered = [v for v in preferred if v in values]
                remainder = [v for v in values if v not in ordered]
                numeric_r, text_r = [], []
                for v in remainder:
                    try:
                        numeric_r.append((float(v), v))
                    except (TypeError, ValueError):
                        text_r.append(v)
                ordered += [v for _, v in sorted(numeric_r)] + sorted(text_r)
                result.append(ordered)
                continue
            numeric, text = [], []
            for v in values:
                try:
                    numeric.append((float(v), v))
                except (TypeError, ValueError):
                    text.append(v)
            result.append([v for _, v in sorted(numeric)] + sorted(text))
        else:
            result.append(sorted(values))
    return result


# ==============================================================================
# PHASE 10 — CLINICAL BOUNDS TRANSFORMER
# ==============================================================================
# CPRA and sensitization_severity entries removed (neither is a direct
# t_df3 feature any more -- see Bug 2). SENSITIZATION_RECENT/PEAK bounds
# kept as a post-MICE safety net, in addition to the pre-clip already
# applied in Phase 4O.
# ==============================================================================

PHYSIO_BOUNDS = {
    "INIT_AGE": (18, 90), "AGE_DON": (1, 90),
    "CREAT_TRR": (0.1, 20), "CREAT_DON": (0.1, 20),
    "TBILI_TRR": (0, 50), "ALBUMIN_TRR": (0.5, 7),
    "BMI_TCR": (10, 70), "BMI_DON": (10, 70),
    "ISCHTIME": (0, 600), "DAYSWAIT_CHRON": (0, 3650),
    "SENSITIZATION_RECENT": (0, 100), "SENSITIZATION_PEAK": (0, 100),
    "eGFR_CKD_EPI": (5, 200), "donor_recipient_age_gap": (0, 80),
}


class ClinicalBoundsClipper(BaseEstimator, TransformerMixin):
    def __init__(self, columns, bounds):
        self.columns = columns
        self.bounds = bounds

    def fit(self, X, y=None):
        arr = np.asarray(X)
        if arr.ndim != 2:
            raise ValueError("ClinicalBoundsClipper expects a 2D array.")
        self.n_features_in_ = arr.shape[1]
        if len(self.columns) != self.n_features_in_:
            raise ValueError("ClinicalBoundsClipper column count mismatch.")
        return self

    def transform(self, X):
        arr = np.asarray(X, dtype=float).copy()
        if arr.ndim != 2 or arr.shape[1] != self.n_features_in_:
            raise ValueError("Unexpected feature shape in ClinicalBoundsClipper.")
        for i, col in enumerate(self.columns):
            if col in self.bounds:
                lo, hi = self.bounds[col]
                arr[:, i] = np.clip(arr[:, i], lo, hi)
        return arr


# ==============================================================================
# PHASE 11 — BUILD TREE / LINEAR MATRICES  [VERIFIED WORKING -- MICE max_iter trimmed]
# ==============================================================================

def _build_pipeline_matrices(X_train_raw, X_test_raw, label):
    print("\n" + "=" * 78)
    print(f"PHASE 11 — {label}: PREPROCESSING PIPELINES")
    print("=" * 78)

    binary_cols, ordinal_cols, nominal_cols, continuous_cols = classify_feature_types(X_train_raw)
    print(f"  Continuous: {len(continuous_cols)}  Binary: {len(binary_cols)}  "
          f"Ordinal: {len(ordinal_cols)}  Nominal: {len(nominal_cols)}")
    print("  Binary:", sorted(binary_cols))
    print("  Ordinal:", sorted(ordinal_cols))
    print("  Nominal:", sorted(nominal_cols))

    X_train_enc = encode_binary_yn(X_train_raw, binary_cols)
    X_test_enc = encode_binary_yn(X_test_raw, binary_cols)

    cat_cols = ordinal_cols + nominal_cols
    X_train_enc, X_test_enc, rare_map = consolidate_rare(X_train_enc, X_test_enc, cat_cols, threshold=RARE_THRESHOLD)
    X_train_enc = cast_cats_to_str(X_train_enc, cat_cols)
    X_test_enc = cast_cats_to_str(X_test_enc, cat_cols)

    category_lists = ordered_categories_from_train(X_train_enc, cat_cols, ordinal_cols)
    ordinal_categories = category_lists[:len(ordinal_cols)]
    nominal_categories = category_lists[len(ordinal_cols):]

    mice_kwargs = dict(max_iter=MICE_MAX_ITER, random_state=RANDOM_STATE,
                        n_nearest_features=10, initial_strategy="median")

    pipe_cont_tree = Pipeline([
        ("mice", IterativeImputer(**mice_kwargs)),
        ("clinical_clip", ClinicalBoundsClipper(continuous_cols, PHYSIO_BOUNDS)),
    ])
    pipe_cont_linear = Pipeline([
        ("mice", IterativeImputer(**mice_kwargs)),
        ("clinical_clip", ClinicalBoundsClipper(continuous_cols, PHYSIO_BOUNDS)),
        ("scaler", StandardScaler()),
    ])
    pipe_binary = Pipeline([("imputer", SimpleImputer(strategy="most_frequent"))])
    pipe_ordinal_tree = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OrdinalEncoder(categories=ordinal_categories, handle_unknown="use_encoded_value",
                                    unknown_value=-1, encoded_missing_value=np.nan)),
    ])
    pipe_ordinal_linear = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(categories=ordinal_categories, handle_unknown="ignore",
                                   sparse_output=False, drop="if_binary")),
    ])
    pipe_nominal_tree = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OrdinalEncoder(categories=nominal_categories, handle_unknown="use_encoded_value", unknown_value=-1)),
    ])
    pipe_nominal_linear = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(categories=nominal_categories, handle_unknown="ignore",
                                   sparse_output=False, drop=None)),
    ])

    cont_cols = [c for c in continuous_cols if c in X_train_enc.columns]
    bin_cols = [c for c in binary_cols if c in X_train_enc.columns]
    ord_cols = [c for c in ordinal_cols if c in X_train_enc.columns]
    nom_cols = [c for c in nominal_cols if c in X_train_enc.columns]

    ct_tree = ColumnTransformer([
        ("continuous", pipe_cont_tree, cont_cols), ("binary", pipe_binary, bin_cols),
        ("ordinal", pipe_ordinal_tree, ord_cols), ("nominal", pipe_nominal_tree, nom_cols),
    ], remainder="drop", n_jobs=-1)
    pipeline_tree = Pipeline([("preprocessor", ct_tree)])
    print("  Fitting TREE pipeline on TRAIN only...")
    pipeline_tree.fit(X_train_enc)
    X_train_tree_np = pipeline_tree.transform(X_train_enc)
    X_test_tree_np = pipeline_tree.transform(X_test_enc)
    feature_names_tree = cont_cols + bin_cols + ord_cols + nom_cols
    X_train_tree = pd.DataFrame(X_train_tree_np, columns=feature_names_tree, index=X_train_raw.index)
    X_test_tree = pd.DataFrame(X_test_tree_np, columns=feature_names_tree, index=X_test_raw.index)

    ct_linear = ColumnTransformer([
        ("continuous", pipe_cont_linear, cont_cols), ("binary", pipe_binary, bin_cols),
        ("ordinal", pipe_ordinal_linear, ord_cols), ("nominal", pipe_nominal_linear, nom_cols),
    ], remainder="drop", n_jobs=-1)
    pipeline_linear = Pipeline([("preprocessor", ct_linear)])
    print("  Fitting LINEAR/NEURAL pipeline on TRAIN only...")
    pipeline_linear.fit(X_train_enc)
    X_train_linear_np = pipeline_linear.transform(X_train_enc)
    X_test_linear_np = pipeline_linear.transform(X_test_enc)

    ohe_ord_names = ct_linear.named_transformers_["ordinal"].named_steps["encoder"].get_feature_names_out(ord_cols).tolist()
    ohe_nom_names = ct_linear.named_transformers_["nominal"].named_steps["encoder"].get_feature_names_out(nom_cols).tolist()
    feature_names_linear = cont_cols + bin_cols + ohe_ord_names + ohe_nom_names
    X_train_linear = pd.DataFrame(X_train_linear_np, columns=feature_names_linear, index=X_train_raw.index)
    X_test_linear = pd.DataFrame(X_test_linear_np, columns=feature_names_linear, index=X_test_raw.index)

    def drop_train_nzv(Xtr, Xte):
        nzv = []
        for c in Xtr.columns:
            vc = Xtr[c].value_counts(normalize=True, dropna=False)
            if len(vc) == 0 or vc.iloc[0] >= NZV_THRESHOLD:
                nzv.append(c)
        Xtr2 = Xtr.drop(columns=nzv)
        Xte2 = Xte.drop(columns=[c for c in nzv if c in Xte.columns])
        return Xtr2, Xte2, nzv

    X_train_tree, X_test_tree, nzv_tree = drop_train_nzv(X_train_tree, X_test_tree)
    X_train_linear, X_test_linear, nzv_linear = drop_train_nzv(X_train_linear, X_test_linear)

    print(f"  Tree final matrix   : {X_train_tree.shape} train / {X_test_tree.shape} test")
    print(f"  Linear final matrix : {X_train_linear.shape} train / {X_test_linear.shape} test")
    print(f"  NZV dropped (tree)   : {len(nzv_tree)}")
    print(f"  NZV dropped (linear) : {len(nzv_linear)}")

    return {
        "pipeline_tree": pipeline_tree, "pipeline_linear": pipeline_linear,
        "X_train_tree": X_train_tree, "X_test_tree": X_test_tree,
        "X_train_linear": X_train_linear, "X_test_linear": X_test_linear,
        "feature_names_tree": X_train_tree.columns.tolist(), "feature_names_linear": X_train_linear.columns.tolist(),
        "binary_cols": binary_cols, "ordinal_cols": ordinal_cols, "nominal_cols": nominal_cols,
        "continuous_cols": continuous_cols, "rare_map": rare_map, "nzv_tree": nzv_tree, "nzv_linear": nzv_linear,
    }


# ==============================================================================
# PHASE 12 — 1-YEAR PREPARATION
# ==============================================================================

prep_1y = split_and_clean(dataset_1y, outcome_col="OUTCOME_1Y", label="1-YEAR")
mats_1y = _build_pipeline_matrices(prep_1y["X_train"], prep_1y["X_test"], label="1-YEAR")

X_train_tree, X_test_tree = mats_1y["X_train_tree"], mats_1y["X_test_tree"]
X_train_linear, X_test_linear = mats_1y["X_train_linear"], mats_1y["X_test_linear"]
y_train, y_test = prep_1y["y_train"], prep_1y["y_test"]

assert X_train_tree.index.equals(y_train.index)
assert X_test_tree.index.equals(y_test.index)
assert X_train_linear.index.equals(y_train.index)
assert X_test_linear.index.equals(y_test.index)


# ==============================================================================
# PHASE 13 — SAVE 1-YEAR OUTPUTS
# ==============================================================================

OUT_1Y = MODEL_READY_ROOT / "1yr"
OUT_1Y.mkdir(parents=True, exist_ok=True)
print("\n" + "=" * 78)
print("PHASE 13 — SAVE 1-YEAR OUTPUTS")
print("=" * 78)

X_train_tree.to_parquet(OUT_1Y / "X_train_tree.parquet", engine="pyarrow", index=True)
X_test_tree.to_parquet(OUT_1Y / "X_test_tree.parquet", engine="pyarrow", index=True)
X_train_linear.to_parquet(OUT_1Y / "X_train_linear.parquet", engine="pyarrow", index=True)
X_test_linear.to_parquet(OUT_1Y / "X_test_linear.parquet", engine="pyarrow", index=True)
y_train.to_frame(name="y").to_parquet(OUT_1Y / "y_train.parquet", engine="pyarrow", index=True)
y_test.to_frame(name="y").to_parquet(OUT_1Y / "y_test.parquet", engine="pyarrow", index=True)

with open(OUT_1Y / "pipeline_tree.pkl", "wb") as f:
    pickle.dump(mats_1y["pipeline_tree"], f)
with open(OUT_1Y / "pipeline_linear.pkl", "wb") as f:
    pickle.dump(mats_1y["pipeline_linear"], f)

pd.DataFrame({"feature": mats_1y["feature_names_tree"], "pipeline": "tree"}).to_csv(OUT_1Y / "5_feature_names_tree.csv", index=False)
pd.DataFrame({"feature": mats_1y["feature_names_linear"], "pipeline": "linear"}).to_csv(OUT_1Y / "5_feature_names_linear.csv", index=False)
prep_1y["report"].to_csv(OUT_1Y / "5_feature_report.csv", index=False)
with open(OUT_1Y / "5_rare_categories.json", "w") as f:
    json.dump(mats_1y["rare_map"], f, indent=2)

config = {
    "segment": "5", "version": "consolidated", "split_date": str(SPLIT_DATE.date()),
    "mice_max_iter": MICE_MAX_ITER, "missing_threshold": MISSING_THRESHOLD,
    "rare_threshold": RARE_THRESHOLD, "nzv_threshold": NZV_THRESHOLD, "random_state": RANDOM_STATE,
    "base_features_present": PRESENT_BASE, "base_features_absent": ABSENT_BASE,
    "engineered_features": ENGINEERED_FEATURES,
    "final_tree_features": mats_1y["feature_names_tree"], "final_linear_features": mats_1y["feature_names_linear"],
    "dropped_train_constant": prep_1y["constant_cols"], "dropped_train_high_missing": prep_1y["high_missing_cols"],
    "nzv_tree": mats_1y["nzv_tree"], "nzv_linear": mats_1y["nzv_linear"],
}
with open(OUT_1Y / "5_preprocessing_config.json", "w") as f:
    json.dump(config, f, indent=2)
print(f"  Saved 1-year artifacts -> {OUT_1Y}")


# ==============================================================================
# PHASE 14 — 3-YEAR ALIGNMENT ONTO THE 1-YEAR-FITTED FEATURE SPACE
# [VERIFIED WORKING -- design rationale explained in header]
# ==============================================================================

print("\n" + "=" * 78)
print("PHASE 14 — 3-YEAR OUTCOME ALIGNMENT")
print("=" * 78)

train_3y_idx = X_train_tree.index.intersection(common_3y)
test_3y_idx = X_test_tree.index.intersection(common_3y)

y_train_3yr = out3.loc[train_3y_idx, "OUTCOME_3Y"].astype(int)
y_test_3yr = out3.loc[test_3y_idx, "OUTCOME_3Y"].astype(int)

X_train_tree_3yr = X_train_tree.loc[train_3y_idx].copy()
X_test_tree_3yr = X_test_tree.loc[test_3y_idx].copy()
X_train_linear_3yr = X_train_linear.loc[train_3y_idx].copy()
X_test_linear_3yr = X_test_linear.loc[test_3y_idx].copy()

print(f"  1-year train patients : {len(X_train_tree):,}   Valid 3-year train : {len(X_train_tree_3yr):,}")
print(f"  1-year test patients  : {len(X_test_tree):,}   Valid 3-year test  : {len(X_test_tree_3yr):,}")
print(f"  3-year train rejection rate: {y_train_3yr.mean() * 100:.2f}%")
print(f"  3-year test rejection rate : {y_test_3yr.mean() * 100:.2f}%")

common_train = y_train.index.intersection(y_train_3yr.index)
common_test = y_test.index.intersection(y_test_3yr.index)
train_violations = int(((y_train.loc[common_train] == 1) & (y_train_3yr.loc[common_train] == 0)).sum())
test_violations = int(((y_test.loc[common_test] == 1) & (y_test_3yr.loc[common_test] == 0)).sum())
print("  1-year/3-year logical consistency check "
      + ("PASSED" if not (train_violations or test_violations) else f"FAILED: train={train_violations}, test={test_violations}"))

OUT_3Y = MODEL_READY_ROOT / "3yr"
OUT_3Y.mkdir(parents=True, exist_ok=True)
X_train_tree_3yr.to_parquet(OUT_3Y / "X_train_tree.parquet", engine="pyarrow", index=True)
X_test_tree_3yr.to_parquet(OUT_3Y / "X_test_tree.parquet", engine="pyarrow", index=True)
X_train_linear_3yr.to_parquet(OUT_3Y / "X_train_linear.parquet", engine="pyarrow", index=True)
X_test_linear_3yr.to_parquet(OUT_3Y / "X_test_linear.parquet", engine="pyarrow", index=True)
y_train_3yr.to_frame(name="y").to_parquet(OUT_3Y / "y_train.parquet", engine="pyarrow", index=True)
y_test_3yr.to_frame(name="y").to_parquet(OUT_3Y / "y_test.parquet", engine="pyarrow", index=True)

with open(OUT_3Y / "pipeline_tree.pkl", "wb") as f:
    pickle.dump(mats_1y["pipeline_tree"], f)
with open(OUT_3Y / "pipeline_linear.pkl", "wb") as f:
    pickle.dump(mats_1y["pipeline_linear"], f)
pd.DataFrame({"feature": mats_1y["feature_names_tree"], "pipeline": "tree"}).to_csv(OUT_3Y / "5_feature_names_tree.csv", index=False)
pd.DataFrame({"feature": mats_1y["feature_names_linear"], "pipeline": "linear"}).to_csv(OUT_3Y / "5_feature_names_linear.csv", index=False)
with open(OUT_3Y / "5_alignment_info.json", "w") as f:
    json.dump({
        "preprocessing_source": "1yr training-fitted pipelines (shared by design, see header)",
        "refitted_on_3yr": False,
        "train_3yr_ids": int(len(train_3y_idx)), "test_3yr_ids": int(len(test_3y_idx)),
        "train_1yr_to_3yr_violation_count": train_violations, "test_1yr_to_3yr_violation_count": test_violations,
    }, f, indent=2)
print(f"  Saved 3-year aligned artifacts -> {OUT_3Y}")


# ==============================================================================
# PHASE 15 — COMPREHENSIVE VALIDATION  [VERIFIED WORKING -- unchanged from V3]
# ==============================================================================

print("\n" + "=" * 78)
print("PHASE 15 — COMPREHENSIVE VALIDATION")
print("=" * 78)

for name, X in [("X_train_tree", X_train_tree), ("X_test_tree", X_test_tree),
                ("X_train_linear", X_train_linear), ("X_test_linear", X_test_linear),
                ("X_train_tree_3yr", X_train_tree_3yr), ("X_test_tree_3yr", X_test_tree_3yr),
                ("X_train_linear_3yr", X_train_linear_3yr), ("X_test_linear_3yr", X_test_linear_3yr)]:
    nan_count = int(X.isna().sum().sum())
    print(f"  {'OK' if nan_count == 0 else 'WARNING'} {name}: {nan_count:,} NaN")

assert not isinstance(X_train_tree.index, pd.RangeIndex), "TRR_ID_CODE index lost -- Bug 1 fix failed."
assert X_train_tree.index.name == "TRR_ID_CODE"
assert set(X_train_tree.index).isdisjoint(X_test_tree.index)
print("  OK train/test patient identity separation, TRR_ID_CODE confirmed as index.")

tree_leak = [c for c in X_train_tree.columns if c in LEAKAGE_COLUMNS or any(k.upper() in c.upper() for k in LEAKAGE_KEYWORDS)]
linear_leak = [c for c in X_train_linear.columns if c in LEAKAGE_COLUMNS or any(k.upper() in c.upper() for k in LEAKAGE_KEYWORDS)]
assert not tree_leak, f"Leakage in tree matrix: {tree_leak}"
assert not linear_leak, f"Leakage in linear matrix: {linear_leak}"
print("  OK no explicit leakage columns in final matrices.")

assert prep_1y["tx_train"].max() <= SPLIT_DATE
assert prep_1y["tx_test"].min() > SPLIT_DATE
print("  OK temporal integrity confirmed.")

assert len(X_train_tree) == len(y_train) == len(X_train_linear)
assert len(X_test_tree) == len(y_test) == len(X_test_linear)
assert len(X_train_tree_3yr) == len(y_train_3yr)
assert len(X_test_tree_3yr) == len(y_test_3yr)
print("  OK row counts and indices align with y labels, both horizons.")

sens_recovered = "SENSITIZATION_PEAK" in X_train_tree.columns or "SENSITIZATION_TIER" in X_train_tree.columns
print(f"  Sensitization features survived to final tree matrix: {sens_recovered} "
      f"({'Bug 1 fix confirmed effective' if sens_recovered else 'STILL MISSING -- investigate further'})")

print("\n" + "=" * 78)
print("SEGMENT 5 CONSOLIDATED — COMPLETE")
print("=" * 78)
print(f"1-year output directory: {OUT_1Y}")
print(f"3-year output directory: {OUT_3Y}")
print("TRR_ID_CODE preserved as index throughout -- Segment 6's ID bug is now")
print("automatically fixed on retrain, no Segment 6 code changes needed.")

==============================================================================
SEGMENT 5 — CONSOLIDATED, BUG-FIXED
==============================================================================

FileNotFoundError: Required input file not found: \content\drive\MyDrive\Thesis_parquet\t_df3.parquet

# ***6A: MODEL TRAINING, HYPERPARAMETER TUNING & EVALUATION-1YEAR

# 6A - BLOCK 1/4: LOGISTIC REGRESSION, LINEAR SVM, SGD, RANDOM FOREST - local

In [ ]:
# ==============================================================================
# BLOCK 1/4 — LOGISTIC REGRESSION, LINEAR SVM, SGD, RANDOM FOREST
# 1-YEAR REJECTION ONLY
# Tunes + evaluates 4 models x 3 imbalance strategies.
# Fully self-contained.
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

# --- CHANGE 5: count ConvergenceWarnings instead of hiding them entirely ---
warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')                      # suppress noise generally...
warnings.simplefilter('always', ConvergenceWarning)     # ...but always trigger this one
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000            # CHANGE 3: was 1500
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
CALIBRATION_CV = 3            # CHANGE 2: was implicit default (5)
EARLY_STOP_PATIENCE = 15      # CHANGE 4: stop a study if no improvement in this many trials

STRATEGIES = {
    'S1_SMOTE': 'SMOTE',
    'S2_BALANCED': 'class_weight=balanced',
    'S3_THRESHOLD': 'threshold_optimised'
}

BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (unchanged — already merge-safe)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(
                new_df.set_index(['model', 'strategy']).index
            )
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (unchanged)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    Xtr_lin  = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
    Xte_lin  = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(Xtr_lin) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(Xte_lin) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0 and Xtr_lin.shape[1] > 0, "Empty feature matrix."

    print("\n" + "=" * 70); print("1-YEAR REJECTION DATA LOADED"); print("=" * 70)
    print(f"Data directory : {DATA_DIR}")
    print(f"\nTree train     : {Xtr_tree.shape}")
    print(f"Tree test      : {Xte_tree.shape}")
    print(f"Linear train   : {Xtr_lin.shape}")
    print(f"Linear test    : {Xte_lin.shape}")
    print(f"\nTrain: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")
    print(f"\nPositive train: {int(y_train.sum()):,}   Negative train: {int((y_train==0).sum()):,}")
    print(f"Positive test : {int(y_test.sum()):,}   Negative test : {int((y_test==0).sum()):,}")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        Xl_train=Xtr_lin.values.astype('float32'),  Xl_test=Xte_lin.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, Xl_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac,
                               stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], Xl_train[idx], yt_arr[idx]


data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
Xl_train, Xl_test = data['Xl_train'], data['Xl_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, Xl_tune, yt_tune = get_tuning_subsample(Xt_train, Xl_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (unchanged)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(
        O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')
    ).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1'])**2 / hl['E1']) + ((hl['O0'] - hl['E0'])**2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0:
            continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf)
        ece += (n_m / len(y_true)) * gap
        mce = max(mce, gap)
        bins.append({'bin_lo': round(lo,3), 'bin_hi': round(hi,3), 'n': n_m,
                     'conf': round(conf,4), 'acc': round(acc,4), 'gap': round(gap,4)})
    return round(ece, 6), round(mce, 6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val >= t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)

    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)

    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn) / (denom + eps) if denom > 0 else 0.0

    return {
        'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3),
        'n_test': len(y_true), 'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
        'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
        'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
        'brier_score': round(brier, 4),
        'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
        'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
        'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
        'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
        'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
        'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
        'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn),
    }


# ------------------------------------------------------------------------------
# MODEL REGISTRY
# ------------------------------------------------------------------------------
def _lr_space(t):
    penalty = t.suggest_categorical('penalty', ['l1', 'l2', 'elasticnet'])
    params = {'C': t.suggest_float('C', 1e-4, 1e2, log=True), 'penalty': penalty}
    if penalty == 'elasticnet':
        params['l1_ratio'] = t.suggest_float('l1_ratio', 0.0, 1.0)
    return params

REGISTRY = {
    'LogisticRegression': {
        'class': LogisticRegression, 'data': 'linear',
        'fixed': {'max_iter': 500, 'solver': 'saga', 'random_state': RANDOM_STATE},
        'space': _lr_space,
    },
    'LinearSVM': {
        'class': CalibratedClassifierCV, 'data': 'linear', 'fixed': {},
        'inner_class': LinearSVC,
        'inner_fixed': {'random_state': RANDOM_STATE, 'max_iter': 1000},
        'space': lambda t: {
            'estimator__C': t.suggest_float('C', 1e-3, 1e2, log=True),
            'estimator__loss': t.suggest_categorical('loss', ['hinge', 'squared_hinge']),
        },
    },
    'SGD': {
        'class': SGDClassifier, 'data': 'linear',
        'fixed': {'loss': 'log_loss', 'max_iter': 100, 'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'alpha': t.suggest_float('alpha', 1e-6, 1e-1, log=True),
            'penalty': t.suggest_categorical('penalty', ['l2', 'l1', 'elasticnet']),
            'l1_ratio': t.suggest_float('l1_ratio', 0.0, 1.0),
        },
    },
    'RandomForest': {
        'class': RandomForestClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'n_estimators': t.suggest_int('n_estimators', 200, 1000),
            'max_depth': t.suggest_int('max_depth', 4, 20),
            'min_samples_split': t.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': t.suggest_int('min_samples_leaf', 1, 10),
            'max_features': t.suggest_categorical('max_features', ['sqrt', 'log2', 0.3]),
        },
    },
}

TRIAL_BUDGET = {'LogisticRegression': 50, 'LinearSVM': 45, 'SGD': 45, 'RandomForest': 75}


def build_model(model_name, params, strategy):
    cfg = REGISTRY[model_name]
    inner_params = {k.replace('estimator__', ''): v for k, v in params.items() if 'estimator__' in k}
    plain_params = {k: v for k, v in params.items() if 'estimator__' not in k}
    all_params = {**cfg['fixed'], **plain_params}

    def make_linear_svm(class_weight=None, use_smote=False):
        inner_kw = {**cfg['inner_fixed'], **inner_params}
        if class_weight is not None:
            inner_kw['class_weight'] = class_weight
        svm = cfg['inner_class'](**inner_kw)
        if use_smote:
            # --- CHANGE 1 (THE FIX): SMOTE now lives INSIDE the pipeline that
            # CalibratedClassifierCV wraps, exactly mirroring the SMOTE pattern
            # already used correctly for LR/SGD/RF below. Previously this branch
            # was unreachable — S1 fell through to the same code as S2.
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            estimator = ImblearnPipeline([('smote', smote), ('svm', svm)])
        else:
            estimator = svm
        return CalibratedClassifierCV(estimator, cv=CALIBRATION_CV)  # CHANGE 2: explicit cv=3

    if strategy == 'S1_SMOTE':
        if model_name == 'LinearSVM':
            return make_linear_svm(use_smote=True)
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', cfg['class'](**all_params))])

    elif strategy == 'S2_BALANCED':
        if model_name == 'LinearSVM':
            return make_linear_svm(class_weight='balanced')
        if model_name in ('RandomForest', 'LogisticRegression', 'SGD'):
            all_params['class_weight'] = 'balanced'
        return cfg['class'](**all_params)

    else:  # S3_THRESHOLD
        if model_name == 'LinearSVM':
            return make_linear_svm()
        return cfg['class'](**all_params)


# ------------------------------------------------------------------------------
# EARLY-STOPPING CALLBACK (CHANGE 4)
# ------------------------------------------------------------------------------
def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# GENERIC TUNE + EVAL RUNNER
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]
        data_kind = registry[model_name]['data']

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0   # CHANGE 5: reset per combination
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy, data_kind=data_kind):
                params = registry[model_name]['space'](trial)
                X_sub = Xl_tune if data_kind == 'linear' else Xt_tune
                scores = []
                for tr_idx, val_idx in skf_tune.split(X_sub, yt_tune):
                    try:
                        m = build_model_fn(model_name, params, strategy)
                        m.fit(X_sub[tr_idx], yt_tune[tr_idx])
                        proba = m.predict_proba(X_sub[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(
                direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10)
            )
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])   # CHANGE 4

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, "
                  f"{elapsed:.0f}s, {n_conv} convergence warnings)")   # CHANGE 5/6

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        X_tr = Xl_train if registry[model_name]['data'] == 'linear' else Xt_train
        X_te = Xl_test if registry[model_name]['data'] == 'linear' else Xt_test

        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy)
                model.fit(X_tr, yt_arr)
                y_prob = model.predict_proba(X_te)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy),
                                              X_tr, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({
                    'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                    'y_prob': y_prob, 'y_pred': y_pred
                }).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")   # CHANGE 7

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


# ------------------------------------------------------------------------------
# RUN — 1-YEAR REJECTION ONLY
# ------------------------------------------------------------------------------
block1_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)

print("\nBlock 1 complete.")
print(block1_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

======================================================================
1-YEAR REJECTION DATA LOADED
======================================================================
Data directory : D:\Thesis\Thesis_parquet\model_ready\1yr

Tree train     : (27431, 266)
Tree test      : (13796, 266)
Linear train   : (27431, 618)
Linear test    : (13796, 618)

Train: 27,431 (36.7% rejection)
Test : 13,796 (30.0% rejection)

Positive train: 10,069   Negative train: 17,362
Positive test : 4,141   Negative test : 9,655

Tuning subsample: 13,715 patients (36.7% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning LogisticRegression/S1_SMOTE (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6450  (trial 22/38, 2903s, 64 convergence warnings)

Tuning LogisticRegression/S2_BALANCED (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6485  (trial 46/50, 3401s, 100 convergence warnings)

Tuning LogisticRegression/S3_THRESHOLD (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6482  (trial 32/48, 3231s, 100 convergence warnings)

Tuning LinearSVM/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6415  (trial 19/35, 495s, 77 convergence warnings)

Tuning LinearSVM/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6439  (trial 5/21, 224s, 47 convergence warnings)

Tuning LinearSVM/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6435  (trial 20/36, 305s, 64 convergence warnings)

Tuning SGD/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6370  (trial 4/20, 156s, 23 convergence warnings)

Tuning SGD/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6401  (trial 4/20, 113s, 23 convergence warnings)

Tuning SGD/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6413  (trial 4/20, 113s, 24 convergence warnings)

Tuning RandomForest/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6467  (trial 34/50, 1032s, 0 convergence warnings)

Tuning RandomForest/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6544  (trial 15/31, 333s, 0 convergence warnings)

Tuning RandomForest/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6543  (trial 24/40, 494s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  LogisticRegression/S1_SMOTE... AUROC=0.6198  AUPRC=0.4024  F1=0.4775  Brier=0.3491  ECE=0.3780  (94s)

  LogisticRegression/S2_BALANCED... AUROC=0.6163  AUPRC=0.3976  F1=0.4699  Brier=0.3815  ECE=0.4198  (88s)

  LogisticRegression/S3_THRESHOLD... AUROC=0.6167  AUPRC=0.3988  F1=0.4643  Brier=0.3040  ECE=0.3121  (161s)

  LinearSVM/S1_SMOTE... AUROC=0.6033  AUPRC=0.3803  F1=0.4671  Brier=0.2962  ECE=0.3020  (81s)

  LinearSVM/S2_BALANCED... AUROC=0.6007  AUPRC=0.3779  F1=0.4640  Brier=0.3102  ECE=0.3240  (56s)

  LinearSVM/S3_THRESHOLD... AUROC=0.5986  AUPRC=0.3770  F1=0.4618  Brier=0.3216  ECE=0.3402  (101s)

  SGD/S1_SMOTE... AUROC=0.6175  AUPRC=0.4016  F1=0.4740  Brier=0.3320  ECE=0.3541  (10s)

  SGD/S2_BALANCED... AUROC=0.6073  AUPRC=0.3874  F1=0.4704  Brier=0.3718  ECE=0.4061  (9s)

  SGD/S3_THRESHOLD... AUROC=0.6071  AUPRC=0.3883  F1=0.4648  Brier=0.2902  ECE=0.2861  (12s)

  RandomForest/S1_SMOTE... AUROC=0.5965  AUPRC=0.3863  F1=0.2054  Brier=0.2154  ECE=0.1027  (42s)

  RandomForest/S2_BALANCED... AUROC=0.6177  AUPRC=0.3976  F1=0.4262  Brier=0.2318  ECE=0.1705  (26s)

  RandomForest/S3_THRESHOLD... AUROC=0.6152  AUPRC=0.3999  F1=0.4752  Brier=0.2100  ECE=0.0848  (104s)

Block 1 complete.
             model     strategy  auroc  auprc  f1_score
LogisticRegression     S1_SMOTE 0.6198 0.4024    0.4775
LogisticRegression  S2_BALANCED 0.6163 0.3976    0.4699
LogisticRegression S3_THRESHOLD 0.6167 0.3988    0.4643
         LinearSVM     S1_SMOTE 0.6033 0.3803    0.4671
         LinearSVM  S2_BALANCED 0.6007 0.3779    0.4640
         LinearSVM S3_THRESHOLD 0.5986 0.3770    0.4618
               SGD     S1_SMOTE 0.6175 0.4016    0.4740
               SGD  S2_BALANCED 0.6073 0.3874    0.4704
               SGD S3_THRESHOLD 0.6071 0.3883    0.4648
      RandomForest     S1_SMOTE 0.5965 0.3863    0.2054
      RandomForest  S2_BALANCED 0.6177 0.3976    0.4262
      RandomForest S3_THRESHOLD 0.6152 0.3999    0.4752

# 6A - BLOCK 2/4: ADABOOST, XGBOOST - local

In [ ]:
# ==============================================================================
# BLOCK 2/4 — ADABOOST, XGBOOST
# 1-YEAR REJECTION ONLY
# Fully self-contained — mirrors Block 1's architecture and diagnostics exactly.
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import xgboost as xgb

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')
warnings.simplefilter('always', ConvergenceWarning)
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG — identical constants to Block 1, so results stay comparable
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
EARLY_STOP_PATIENCE = 15

STRATEGIES = {'S1_SMOTE': 'SMOTE', 'S2_BALANCED': 'class_weight=balanced', 'S3_THRESHOLD': 'threshold_optimised'}
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"      # SAME file as Block 1 — merges in, doesn't overwrite
METRICS_PATH = OUT_DIR / "all_metrics.csv"           # SAME file as Block 1

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# GPU DETECTION FOR XGBOOST — tries modern API, then legacy API, then CPU.
# AdaBoost has no GPU path at all (sklearn CPU-only) — nothing to detect there.
# ------------------------------------------------------------------------------
def detect_xgb_gpu():
    dummy_X = np.random.rand(50, 5).astype('float32')
    dummy_y = np.random.randint(0, 2, 50)

    try:
        m = xgb.XGBClassifier(tree_method='hist', device='cuda', n_estimators=2, verbosity=0)
        m.fit(dummy_X, dummy_y)
        return {'tree_method': 'hist', 'device': 'cuda'}, 'GPU — modern API (device=cuda)'
    except Exception as e1:
        modern_error = str(e1)

    try:
        m = xgb.XGBClassifier(tree_method='gpu_hist', n_estimators=2, verbosity=0)
        m.fit(dummy_X, dummy_y)
        return {'tree_method': 'gpu_hist'}, 'GPU — legacy API (tree_method=gpu_hist)'
    except Exception as e2:
        legacy_error = str(e2)

    print(f"  GPU detection failed on both APIs:")
    print(f"    modern (device=cuda) error : {modern_error[:150]}")
    print(f"    legacy (gpu_hist) error    : {legacy_error[:150]}")
    return {'tree_method': 'hist'}, 'CPU fallback — no working GPU path found'

XGB_DEVICE_PARAMS, XGB_DEVICE_LABEL = detect_xgb_gpu()
print(f"XGBoost device : {XGB_DEVICE_LABEL}")
print(f"AdaBoost device: CPU only (sklearn has no GPU implementation)")


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (identical to Block 1)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(new_df.set_index(['model', 'strategy']).index)
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (identical to Block 1 — both models here use the TREE feature matrix only)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0, "Empty tree feature matrix."

    print("\n" + "=" * 70); print("1-YEAR REJECTION DATA LOADED (Block 2 — tree models only)"); print("=" * 70)
    print(f"Tree train : {Xtr_tree.shape}   Tree test : {Xte_tree.shape}")
    print(f"Train: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac, stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], yt_arr[idx]

data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, yt_tune = get_tuning_subsample(Xt_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (byte-identical to Block 1 — do not let these drift between blocks)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y','sum'), n=('y','count'), E1=('p','mean')).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1']-hl['E1'])**2/hl['E1']) + ((hl['O0']-hl['E0'])**2/hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl)-2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1-1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins+1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i+1]
        mask = (y_prob>=lo)&(y_prob<hi) if i<n_bins-1 else (y_prob>=lo)&(y_prob<=hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc-conf)
        ece += (n_m/len(y_true))*gap
        mce = max(mce, gap)
        bins.append({'bin_lo':round(lo,3),'bin_hi':round(hi,3),'n':n_m,'conf':round(conf,4),'acc':round(acc,4),'gap':round(gap,4)})
    return round(ece,6), round(mce,6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val>=t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: roc_auc_score(yt,yp) if len(np.unique(yt))>1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: average_precision_score(yt,yp) if yt.sum()>0 else np.nan)
    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape==(2,2) else (0,0,0,0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn)/(denom+eps) if denom>0 else 0.0
    return {'model':model_name,'strategy':strategy,'threshold':round(threshold,3),'n_test':len(y_true),
            'n_pos':int(y_true.sum()),'prevalence':round(float(y_true.mean()),4),
            'auroc':round(auroc,4),'auroc_ci_lo':round(auroc_lo,4),'auroc_ci_hi':round(auroc_hi,4),
            'auprc':round(auprc,4),'auprc_ci_lo':round(auprc_lo,4),'auprc_ci_hi':round(auprc_hi,4),
            'brier_score':round(brier,4),
            'ece':round(float(ece),6) if np.isfinite(ece) else np.nan,
            'mce':round(float(mce),6) if np.isfinite(mce) else np.nan,
            'hl_chi2':round(hl_chi2,3),'hl_p_value':round(hl_p,4),
            'sensitivity':round(float(sens),4),'specificity':round(float(spec),4),
            'ppv':round(float(ppv),4),'npv':round(float(npv),4),
            'f1_score':round(float(f1),4),'mcc':round(float(mcc),4),
            'tp':int(tp),'fp':int(fp),'fn':int(fn),'tn':int(tn)}


# ------------------------------------------------------------------------------
# MODEL REGISTRY — AdaBoost, XGBoost only
# ------------------------------------------------------------------------------
def _adaboost_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 50, 500),
        'learning_rate': t.suggest_float('learning_rate', 0.01, 2.0, log=True),
        'base_max_depth': t.suggest_int('base_max_depth', 1, 5),
        # NOTE: 'algorithm' deliberately excluded — removed from sklearn's API
        # (deprecated 1.4, restricted 1.6, removed 1.8). Modern AdaBoost only
        # implements SAMME; omitting the parameter is the version-safe choice.
    }

def _xgb_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 100, 1000),
        'max_depth': t.suggest_int('max_depth', 2, 10),
        'learning_rate': t.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'subsample': t.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': t.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': t.suggest_int('min_child_weight', 1, 10),
        'gamma': t.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': t.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': t.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }

REGISTRY = {
    'AdaBoost': {
        'class': AdaBoostClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE},
        'space': _adaboost_space,
    },
    'XGBoost': {
        'class': xgb.XGBClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'objective': 'binary:logistic',
                  'eval_metric': 'logloss', 'verbosity': 0, 'n_jobs': -1,
                  **XGB_DEVICE_PARAMS},
        'space': _xgb_space,
    },
}
TRIAL_BUDGET = {'AdaBoost': 55, 'XGBoost': 75}


def build_model(model_name, params, strategy, y_ref=None):
    """y_ref: the y-array this model will actually be fit on. Only used by
    XGBoost/S2_BALANCED to compute scale_pos_weight from the REAL class ratio
    of whatever data is being fit right now (fold subset, tuning subsample,
    or full training set) — mirrors what sklearn's class_weight='balanced'
    does automatically, since XGBoost has no built-in equivalent."""
    cfg = REGISTRY[model_name]
    all_params = {**cfg['fixed'], **params}

    if model_name == 'AdaBoost':
        base_depth = all_params.pop('base_max_depth')
        base_class_weight = 'balanced' if strategy == 'S2_BALANCED' else None
        base = DecisionTreeClassifier(max_depth=base_depth, class_weight=base_class_weight,
                                       random_state=RANDOM_STATE)
        ada = AdaBoostClassifier(estimator=base, **all_params)  # 'estimator', NOT 'base_estimator'
        if strategy == 'S1_SMOTE':
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            return ImblearnPipeline([('smote', smote), ('model', ada)])
        return ada

    else:  # XGBoost
        if strategy == 'S2_BALANCED':
            assert y_ref is not None, "XGBoost/S2_BALANCED requires y_ref to compute scale_pos_weight."
            n_pos = int(np.sum(y_ref == 1))
            n_neg = int(np.sum(y_ref == 0))
            all_params['scale_pos_weight'] = n_neg / max(n_pos, 1)
        model = cfg['class'](**all_params)
        if strategy == 'S1_SMOTE':
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            return ImblearnPipeline([('smote', smote), ('model', model)])
        return model


def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# RUNNER — same shape as Block 1, extended to pass y_ref through for XGBoost
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy):
                params = registry[model_name]['space'](trial)
                scores = []
                for tr_idx, val_idx in skf_tune.split(Xt_tune, yt_tune):
                    try:
                        y_fold = yt_tune[tr_idx]
                        m = build_model_fn(model_name, params, strategy, y_ref=y_fold)
                        m.fit(Xt_tune[tr_idx], y_fold)
                        proba = m.predict_proba(Xt_tune[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, {elapsed:.0f}s, "
                  f"{n_conv} convergence warnings)")

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy, y_ref=yt_arr)
                model.fit(Xt_train, yt_arr)
                y_prob = model.predict_proba(Xt_test)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy, y_ref=yt_arr),
                                              Xt_train, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                              'y_prob': y_prob, 'y_pred': y_pred}
                ).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


block2_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)
print("\nBlock 2 complete.")
print(block2_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

XGBoost device : GPU — modern API (device=cuda)
AdaBoost device: CPU only (sklearn has no GPU implementation)

======================================================================
1-YEAR REJECTION DATA LOADED (Block 2 — tree models only)
======================================================================
Tree train : (27431, 266)   Tree test : (13796, 266)
Train: 27,431 (36.7% rejection)
Test : 13,796 (30.0% rejection)

Tuning subsample: 13,715 patients (36.7% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning AdaBoost/S1_SMOTE (55 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6419  (trial 30/46, 10136s, 0 convergence warnings)

Tuning AdaBoost/S2_BALANCED (55 trials, early stop after 15 w/o improvement)... [WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
[WARN] AdaBoost/S2_BALANCED fold failed: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.
best CV AUROC = 0.6173  (trial 22/38, 216s, 0 convergence warnings)

Tuning AdaBoost/S3_THRESHOLD (55 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6428  (trial 29/45, 4753s, 0 convergence warnings)

Tuning XGBoost/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6627  (trial 27/43, 344s, 0 convergence warnings)

Tuning XGBoost/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6652  (trial 13/29, 156s, 0 convergence warnings)

Tuning XGBoost/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6664  (trial 41/57, 359s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  AdaBoost/S1_SMOTE... AUROC=0.5926  AUPRC=0.3791  F1=0.3695  Brier=0.2337  ECE=0.1681  (302s)

  AdaBoost/S2_BALANCED... AUROC=0.5974  AUPRC=0.3680  F1=0.4563  Brier=0.2733  ECE=0.2133  (140s)

  AdaBoost/S3_THRESHOLD... AUROC=0.6176  AUPRC=0.3958  F1=0.4742  Brier=0.2160  ECE=0.1144  (373s)

  XGBoost/S1_SMOTE... AUROC=0.6215  AUPRC=0.4137  F1=0.3434  Brier=0.2113  ECE=0.0966  (12s)

  XGBoost/S2_BALANCED... AUROC=0.6276  AUPRC=0.4162  F1=0.4646  Brier=0.2367  ECE=0.1884  (10s)

  XGBoost/S3_THRESHOLD... AUROC=0.6320  AUPRC=0.4217  F1=0.4845  Brier=0.2078  ECE=0.0862  (37s)

Block 2 complete.
   model     strategy  auroc  auprc  f1_score
AdaBoost     S1_SMOTE 0.5926 0.3791    0.3695
AdaBoost  S2_BALANCED 0.5974 0.3680    0.4563
AdaBoost S3_THRESHOLD 0.6176 0.3958    0.4742
 XGBoost     S1_SMOTE 0.6215 0.4137    0.3434
 XGBoost  S2_BALANCED 0.6276 0.4162    0.4646
 XGBoost S3_THRESHOLD 0.6320 0.4217    0.4845

In [ ]:
# ==============================================================================
# BLOCK 2-FIX — AdaBoost / S2_BALANCED ONLY  (1-YEAR REJECTION)
# Re-runs tuning + final test evaluation for this single cell of the model grid
# and overwrites its artefacts. Block 1 and the other Block 2 cells are untouched.
#
# ROOT-CAUSE FIX
#   OLD: DecisionTreeClassifier(class_weight='balanced') inside AdaBoost
#   NEW: plain base tree + balanced weights passed as AdaBoost's INITIAL sample_weight
#   Reason: AdaBoost computes its weighted error from sample_weight only. A tree that
#   internally uses class_weight='balanced' has a decision threshold at the class prior
#   (~0.37), while AdaBoost's error criterion implicitly assumes 0.5 -> the first weak
#   learner can score "error >= 0.5" and sklearn aborts ("worse than random").
#
# SECOND FIX (tuner honesty)
#   OLD: failed folds were silently dropped and the mean taken over survivors
#        (a trial with 1/3 folds alive looked like a valid score; 3/3 failed = 0.0)
#   NEW: any failed fold => the whole trial is scored FAIL_SCORE (0.5 = chance AUROC),
#        the error text is stored on the trial and counted in the final summary.
#
# SAFETY
#   Nothing shared is overwritten until the final test evaluation has succeeded.
#   Only the S2-specific study pickle is written early (so tuning hours are never lost).
#   Backups of best_params.pkl and all_metrics.csv are taken first.
# ==============================================================================

from pathlib import Path
import pickle, time, shutil, warnings
import numpy as np
import pandas as pd
from scipy import stats
from joblib import Parallel, delayed

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')


# ------------------------------------------------------------------------------
# CONFIG — identical constants to Block 1 / Block 2
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
CV_FOLDS_TUNE = 3
EARLY_STOP_PATIENCE = 15

MODEL_NAME, STRATEGY = 'AdaBoost', 'S2_BALANCED'
N_TRIALS = 55                  # same budget as the original run
FAIL_SCORE = 0.5               # a trial with any failed fold is scored as chance-level AUROC
N_JOBS_FOLDS = CV_FOLDS_TUNE   # folds are independent -> run in parallel; lower if <3 CPU cores

BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)

# --- backups of the two SHARED files (timestamped, never overwritten) ---------
_stamp = time.strftime('%Y%m%d_%H%M%S')
for _p in (BEST_PARAMS_PATH, METRICS_PATH):
    if _p.exists():
        shutil.copy2(_p, _p.with_name(_p.name + f".bak_{_stamp}"))
        print(f"Backup written: {_p.name}.bak_{_stamp}")


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (identical to Block 1 / Block 2)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    """Replaces any existing row with the same (model, strategy) key -> true override."""
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(new_df.set_index(['model', 'strategy']).index)
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (identical to Block 2 — tree feature matrix only)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0, "Empty tree feature matrix."

    print("\n" + "=" * 70); print("1-YEAR REJECTION DATA LOADED (AdaBoost/S2 fix)"); print("=" * 70)
    print(f"Tree train : {Xtr_tree.shape}   Tree test : {Xte_tree.shape}")
    print(f"Train: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac, stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], yt_arr[idx]

data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, yt_tune = get_tuning_subsample(Xt_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (byte-identical to Block 1 / Block 2 — do not let these drift)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y','sum'), n=('y','count'), E1=('p','mean')).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1']-hl['E1'])**2/hl['E1']) + ((hl['O0']-hl['E0'])**2/hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl)-2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1-1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins+1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i+1]
        mask = (y_prob>=lo)&(y_prob<hi) if i<n_bins-1 else (y_prob>=lo)&(y_prob<=hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc-conf)
        ece += (n_m/len(y_true))*gap
        mce = max(mce, gap)
        bins.append({'bin_lo':round(lo,3),'bin_hi':round(hi,3),'n':n_m,'conf':round(conf,4),'acc':round(acc,4),'gap':round(gap,4)})
    return round(ece,6), round(mce,6), bins

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: roc_auc_score(yt,yp) if len(np.unique(yt))>1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: average_precision_score(yt,yp) if yt.sum()>0 else np.nan)
    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape==(2,2) else (0,0,0,0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn)/(denom+eps) if denom>0 else 0.0
    return {'model':model_name,'strategy':strategy,'threshold':round(threshold,3),'n_test':len(y_true),
            'n_pos':int(y_true.sum()),'prevalence':round(float(y_true.mean()),4),
            'auroc':round(auroc,4),'auroc_ci_lo':round(auroc_lo,4),'auroc_ci_hi':round(auroc_hi,4),
            'auprc':round(auprc,4),'auprc_ci_lo':round(auprc_lo,4),'auprc_ci_hi':round(auprc_hi,4),
            'brier_score':round(brier,4),
            'ece':round(float(ece),6) if np.isfinite(ece) else np.nan,
            'mce':round(float(mce),6) if np.isfinite(mce) else np.nan,
            'hl_chi2':round(hl_chi2,3),'hl_p_value':round(hl_p,4),
            'sensitivity':round(float(sens),4),'specificity':round(float(spec),4),
            'ppv':round(float(ppv),4),'npv':round(float(npv),4),
            'f1_score':round(float(f1),4),'mcc':round(float(mcc),4),
            'tp':int(tp),'fp':int(fp),'fn':int(fn),'tn':int(tn)}


# ------------------------------------------------------------------------------
# MODEL — search space identical to Block 2; only the balancing mechanism changes
# ------------------------------------------------------------------------------
def _adaboost_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 50, 500),
        'learning_rate': t.suggest_float('learning_rate', 0.01, 2.0, log=True),
        'base_max_depth': t.suggest_int('base_max_depth', 1, 5),
    }

def build_adaboost_s2(params):
    p = dict(params)                       # never mutate the caller's dict
    depth = p.pop('base_max_depth')
    base = DecisionTreeClassifier(max_depth=depth, class_weight=None,   # <- NO class_weight here
                                  random_state=RANDOM_STATE)
    return AdaBoostClassifier(estimator=base, random_state=RANDOM_STATE, **p)

def fit_balanced(model, X, y):
    """Balanced weights enter as AdaBoost's initial sample distribution, so the booster's
    error, the tree's impurity and the class balance all use the SAME weights."""
    model.fit(X, y, sample_weight=compute_sample_weight('balanced', y))
    return model

def _fit_eval_fold(params, X, y, tr_idx, val_idx):
    """Returns AUROC (float) on success, or an error string on failure."""
    try:
        m = fit_balanced(build_adaboost_s2(params), X[tr_idx], y[tr_idx])
        proba = m.predict_proba(X[val_idx])[:, 1]
        return float(roc_auc_score(y[val_idx], proba))
    except Exception as e:
        return f"{type(e).__name__}: {e}"

def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# SNAPSHOT OF THE ROW THAT WILL BE REPLACED (for the before/after printout)
# ------------------------------------------------------------------------------
old_row = None
if METRICS_PATH.exists():
    _m = pd.read_csv(METRICS_PATH)
    _o = _m[(_m['model'] == MODEL_NAME) & (_m['strategy'] == STRATEGY)]
    if len(_o):
        old_row = _o.iloc[0]


# ------------------------------------------------------------------------------
# TUNING
# ------------------------------------------------------------------------------
print("\n" + "=" * 70); print(f"HYPERPARAMETER TUNING — {MODEL_NAME}/{STRATEGY}"); print("=" * 70)
failure_log = []
folds = list(skf_tune.split(Xt_tune, yt_tune))      # deterministic (shuffle + fixed seed)

def objective(trial):
    params = _adaboost_space(trial)
    res = Parallel(n_jobs=N_JOBS_FOLDS)(
        delayed(_fit_eval_fold)(params, Xt_tune, yt_tune, tr, va) for tr, va in folds
    )
    errs = [r for r in res if isinstance(r, str)]
    if errs:
        trial.set_user_attr('fold_error', errs[0])
        failure_log.append(errs[0])
        return FAIL_SCORE
    return float(np.mean(res))

t0 = time.time()
print(f"Tuning {MODEL_NAME}/{STRATEGY} ({N_TRIALS} trials, early stop after "
      f"{EARLY_STOP_PATIENCE} w/o improvement)...", flush=True)
study = optuna.create_study(direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=False, n_jobs=1,
               callbacks=[make_early_stop_callback()])

n_failed = len(failure_log)
print(f"best CV AUROC = {study.best_value:.4f}  "
      f"(trial {study.best_trial.number}/{len(study.trials)}, {time.time()-t0:.0f}s, "
      f"{n_failed} failed trials)")
print(f"best params   = {study.best_params}")
if n_failed:
    print(f"[WARN] first fold error: {failure_log[0]}")

# S2-specific artefact only -> safe to write now
with open(MDL_DIR / f"study_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(study, f)


# ------------------------------------------------------------------------------
# FINAL TEST-SET EVALUATION (no try/except: a failure must be loud and must
# leave all shared files untouched)
# ------------------------------------------------------------------------------
print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
t0 = time.time()
best_params = study.best_params
model = fit_balanced(build_adaboost_s2(best_params), Xt_train, yt_arr)
y_prob = model.predict_proba(Xt_test)[:, 1]
threshold = 0.5
y_pred = (y_prob >= threshold).astype(int)
metrics = evaluate_model(ytest_arr, y_prob, y_pred, MODEL_NAME, STRATEGY, threshold)

# boosting sanity diagnostics — AdaBoost can stop early WITHOUT raising
n_fit = len(model.estimators_)
print(f"Boosting rounds fitted : {n_fit} / {best_params['n_estimators']}")
print(f"Max weak-learner error : {model.estimator_errors_.max():.4f}  (must stay < 0.5)")
print(f"Predicted-positive rate: {y_pred.mean():.3f}   (test prevalence {ytest_arr.mean():.3f})")
if n_fit < best_params['n_estimators']:
    print("[WARN] boosting stopped early — the ensemble is smaller than the tuned n_estimators.")

# ------------------------------------------------------------------------------
# OVERRIDE ALL S2 ARTEFACTS (only reached if everything above succeeded)
# ------------------------------------------------------------------------------
pd.DataFrame({'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
              'y_prob': y_prob, 'y_pred': y_pred}
).to_csv(OUT_DIR / f"predictions_{MODEL_NAME}_{STRATEGY}.csv", index=False)

with open(MDL_DIR / f"model_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(model, f)

save_best_params({(MODEL_NAME, STRATEGY): best_params})   # merges, other entries intact
append_metrics([metrics])                                  # replaces the old S2 row

print(f"\nDone in {time.time()-t0:.0f}s. Overwritten: study, model, predictions, best_params entry, metrics row.")

keys = ['auroc', 'auprc', 'f1_score', 'brier_score', 'ece', 'sensitivity', 'specificity']
cmp = pd.DataFrame({'new': {k: metrics[k] for k in keys}})
if old_row is not None:
    cmp.insert(0, 'old', {k: old_row[k] for k in keys})
print("\nAdaBoost/S2_BALANCED — before vs after")
print(cmp.round(4).to_string())

Backup written: best_params.pkl.bak_20261002_132220
Backup written: all_metrics.csv.bak_20261002_132220

======================================================================
1-YEAR REJECTION DATA LOADED (AdaBoost/S2 fix)
======================================================================
Tree train : (27431, 266)   Tree test : (13796, 266)
Train: 27,431 (36.7% rejection)
Test : 13,796 (30.0% rejection)

Tuning subsample: 13,715 patients (36.7% rejection)

======================================================================
HYPERPARAMETER TUNING — AdaBoost/S2_BALANCED
======================================================================
Tuning AdaBoost/S2_BALANCED (55 trials, early stop after 15 w/o improvement)...
best CV AUROC = 0.6467  (trial 22/38, 1627s, 0 failed trials)
best params   = {'n_estimators': 487, 'learning_rate': 0.1463625109040994, 'base_max_depth': 5}

======================================================================
FINAL TEST-SET EVALUATION
======================================================================
Boosting rounds fitted : 487 / 487
Max weak-learner error : 0.4986  (must stay < 0.5)
Predicted-positive rate: 0.562   (test prevalence 0.300)

Done in 213s. Overwritten: study, model, predictions, best_params entry, metrics row.

AdaBoost/S2_BALANCED — before vs after
                old     new
auroc        0.5974  0.6193
auprc        0.3680  0.3992
f1_score     0.4563  0.4749
brier_score  0.2733  0.2469
ece          0.2133  0.2099
sensitivity  0.6032  0.6820
specificity  0.5535  0.4895

# 6A - BLOCK 3/4: LIGHTGBM - local

In [ ]:
# ==============================================================================
# BLOCK 3/4 — LIGHTGBM
# 1-YEAR REJECTION ONLY
# Mirrors Block 2's architecture exactly. Fixes the "GPU Tree Learner was not
# enabled in this build" crash by runtime-testing GPU support (both the modern
# CUDA path and the legacy OpenCL path) instead of trusting nvidia-smi alone,
# identical in spirit to Block 2's detect_xgb_gpu().
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import lightgbm as lgb

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')
warnings.simplefilter('always', ConvergenceWarning)
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG — identical constants to Blocks 1-2, so results stay comparable
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
EARLY_STOP_PATIENCE = 15

STRATEGIES = {'S1_SMOTE': 'SMOTE', 'S2_BALANCED': 'class_weight=balanced', 'S3_THRESHOLD': 'threshold_optimised'}
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"   # SAME file as Blocks 1-2 — merges, doesn't overwrite
METRICS_PATH = OUT_DIR / "all_metrics.csv"        # SAME file as Blocks 1-2

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# GPU DETECTION FOR LIGHTGBM — this is the fix. LightGBM raises "GPU Tree
# Learner was not enabled in this build" only at FIT time, not at import or
# instantiation time, and nvidia-smi reporting a GPU says nothing about
# whether THIS specific lightgbm wheel was compiled with GPU support. So we
# fit a 2-estimator dummy model on each candidate device and catch the
# failure, exactly mirroring Block 2's XGBoost pattern.
# ------------------------------------------------------------------------------
def detect_lgb_gpu():
    dummy_X = np.random.rand(50, 5).astype('float32')
    dummy_y = np.random.randint(0, 2, 50)

    try:
        m = lgb.LGBMClassifier(device_type='cuda', n_estimators=2, verbosity=-1)
        m.fit(dummy_X, dummy_y)
        return {'device_type': 'cuda'}, 'GPU — modern API (device_type=cuda)'
    except Exception as e1:
        modern_error = str(e1)

    try:
        m = lgb.LGBMClassifier(device='gpu', n_estimators=2, verbosity=-1)
        m.fit(dummy_X, dummy_y)
        return {'device': 'gpu'}, 'GPU — legacy OpenCL API (device=gpu)'
    except Exception as e2:
        legacy_error = str(e2)

    print(f"  GPU detection failed on both APIs:")
    print(f"    modern (device_type=cuda) error : {modern_error[:150]}")
    print(f"    legacy (device=gpu) error       : {legacy_error[:150]}")
    return {'device': 'cpu'}, 'CPU fallback — this is exactly the crash Block 3 exists to avoid'

LGB_DEVICE_PARAMS, LGB_DEVICE_LABEL = detect_lgb_gpu()
print(f"LightGBM device : {LGB_DEVICE_LABEL}")


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (byte-identical to Blocks 1-2)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(new_df.set_index(['model', 'strategy']).index)
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (identical to Block 2 — tree feature matrix only)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0, "Empty tree feature matrix."

    print("\n" + "=" * 70); print("1-YEAR REJECTION DATA LOADED (Block 3 — LightGBM)"); print("=" * 70)
    print(f"Tree train : {Xtr_tree.shape}   Tree test : {Xte_tree.shape}")
    print(f"Train: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac, stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], yt_arr[idx]

data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, yt_tune = get_tuning_subsample(Xt_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (byte-identical to Blocks 1-2 — do not let these drift)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y','sum'), n=('y','count'), E1=('p','mean')).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1']-hl['E1'])**2/hl['E1']) + ((hl['O0']-hl['E0'])**2/hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl)-2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1-1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins+1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i+1]
        mask = (y_prob>=lo)&(y_prob<hi) if i<n_bins-1 else (y_prob>=lo)&(y_prob<=hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc-conf)
        ece += (n_m/len(y_true))*gap
        mce = max(mce, gap)
        bins.append({'bin_lo':round(lo,3),'bin_hi':round(hi,3),'n':n_m,'conf':round(conf,4),'acc':round(acc,4),'gap':round(gap,4)})
    return round(ece,6), round(mce,6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val>=t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: roc_auc_score(yt,yp) if len(np.unique(yt))>1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: average_precision_score(yt,yp) if yt.sum()>0 else np.nan)
    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape==(2,2) else (0,0,0,0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn)/(denom+eps) if denom>0 else 0.0
    return {'model':model_name,'strategy':strategy,'threshold':round(threshold,3),'n_test':len(y_true),
            'n_pos':int(y_true.sum()),'prevalence':round(float(y_true.mean()),4),
            'auroc':round(auroc,4),'auroc_ci_lo':round(auroc_lo,4),'auroc_ci_hi':round(auroc_hi,4),
            'auprc':round(auprc,4),'auprc_ci_lo':round(auprc_lo,4),'auprc_ci_hi':round(auprc_hi,4),
            'brier_score':round(brier,4),
            'ece':round(float(ece),6) if np.isfinite(ece) else np.nan,
            'mce':round(float(mce),6) if np.isfinite(mce) else np.nan,
            'hl_chi2':round(hl_chi2,3),'hl_p_value':round(hl_p,4),
            'sensitivity':round(float(sens),4),'specificity':round(float(spec),4),
            'ppv':round(float(ppv),4),'npv':round(float(npv),4),
            'f1_score':round(float(f1),4),'mcc':round(float(mcc),4),
            'tp':int(tp),'fp':int(fp),'fn':int(fn),'tn':int(tn)}


# ------------------------------------------------------------------------------
# MODEL REGISTRY — LightGBM only
# ------------------------------------------------------------------------------
def _lgb_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 100, 1000),
        'num_leaves': t.suggest_int('num_leaves', 15, 255),
        'max_depth': t.suggest_int('max_depth', 3, 12),
        'learning_rate': t.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'min_child_samples': t.suggest_int('min_child_samples', 5, 100),
        'subsample': t.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': t.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': t.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': t.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }

REGISTRY = {
    'LightGBM': {
        'class': lgb.LGBMClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'verbosity': -1, 'n_jobs': -1, **LGB_DEVICE_PARAMS},
        'space': _lgb_space,
    },
}
TRIAL_BUDGET = {'LightGBM': 75}


def build_model(model_name, params, strategy, y_ref=None):
    cfg = REGISTRY[model_name]
    all_params = {**cfg['fixed'], **params}

    if strategy == 'S2_BALANCED':
        # LightGBM's sklearn wrapper supports class_weight natively — no manual
        # scale_pos_weight computation needed here, unlike XGBoost in Block 2.
        all_params['class_weight'] = 'balanced'

    model = cfg['class'](**all_params)
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model


def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# RUNNER — identical shape to Blocks 1-2
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy):
                params = registry[model_name]['space'](trial)
                scores = []
                for tr_idx, val_idx in skf_tune.split(Xt_tune, yt_tune):
                    try:
                        m = build_model_fn(model_name, params, strategy)
                        m.fit(Xt_tune[tr_idx], yt_tune[tr_idx])
                        proba = m.predict_proba(Xt_tune[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, {elapsed:.0f}s, "
                  f"{n_conv} convergence warnings)")

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy)
                model.fit(Xt_train, yt_arr)
                y_prob = model.predict_proba(Xt_test)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy),
                                              Xt_train, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                              'y_prob': y_prob, 'y_pred': y_pred}
                ).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


block3_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)
print("\nBlock 3 complete.")
print(block3_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

  GPU detection failed on both APIs:
    modern (device_type=cuda) error : CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1 (NVIDIA GPUs) or -DUSE_ROCM=1 (AMD GPUs)
    legacy (device=gpu) error       : GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
LightGBM device : CPU fallback — this is exactly the crash Block 3 exists to avoid

======================================================================
1-YEAR REJECTION DATA LOADED (Block 3 — LightGBM)
======================================================================
Tree train : (27431, 266)   Tree test : (13796, 266)
Train: 27,431 (36.7% rejection)
Test : 13,796 (30.0% rejection)

Tuning subsample: 13,715 patients (36.7% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning LightGBM/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6587  (trial 4/20, 275s, 0 convergence warnings)

Tuning LightGBM/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6605  (trial 21/37, 361s, 0 convergence warnings)

Tuning LightGBM/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6639  (trial 63/75, 1331s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  LightGBM/S1_SMOTE... AUROC=0.6289  AUPRC=0.4209  F1=0.3946  Brier=0.2147  ECE=0.1149  (12s)

  LightGBM/S2_BALANCED... AUROC=0.6321  AUPRC=0.4185  F1=0.4679  Brier=0.2372  ECE=0.1910  (12s)

  LightGBM/S3_THRESHOLD... AUROC=0.6338  AUPRC=0.4259  F1=0.4845  Brier=0.2064  ECE=0.0805  (36s)

Block 3 complete.
   model     strategy  auroc  auprc  f1_score
LightGBM     S1_SMOTE 0.6289 0.4209    0.3946
LightGBM  S2_BALANCED 0.6321 0.4185    0.4679
LightGBM S3_THRESHOLD 0.6338 0.4259    0.4845

# 6A - BLOCK 4/4: CATBOOST, MLP, ENSEMBLES, STATS, CALIBRATION, DCA, FIGURES - local

# 6A 4/4 1.MLP

In [ ]:
# ==============================================================================
# BLOCK — MLP TRAINING ONLY (S3_THRESHOLD strategy), fully self-contained
# 1-YEAR REJECTION.
#
# FIX vs. previous run: Optuna's study.best_params stores RAW suggest_*()
# names (n_layers, units_l0, units_l1) -- not the derived MLPClassifier
# constructor arg hidden_layer_sizes. Feeding that raw dict straight into
# MLPClassifier(**params) on reload crashes with an unexpected-keyword
# TypeError. Fixed by transforming raw params into a constructor-ready
# dict BEFORE saving to best_params.pkl, so every later reload is safe.
#
# LIGHTER: only S3_THRESHOLD strategy trained (S1_SMOTE/S2_BALANCED
# dropped by decision), and trial count cut 40->20 with a smaller early-
# stop patience, since we're no longer paying for 3 strategies at once.
# ==============================================================================
from pathlib import Path
import pickle, warnings
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore', category=ConvergenceWarning)

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
N_TRIALS_MLP = 40
EARLY_STOP_PATIENCE = 10    # cut from 15 to match smaller trial budget
MODEL_NAME, STRATEGY = 'MLP', 'S3_THRESHOLD'
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE HELPERS ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params(); params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

# ---------------- METRIC HELPERS (identical to rest of pipeline) ----------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception:
            continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val >= t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4),
            'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA (linear family only -- MLP doesn't need tree-encoded data) ----------------
Xtr_lin = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
Xte_lin = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
y_train = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test  = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xl_train, Xl_test = Xtr_lin.values.astype('float32'), Xte_lin.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values

print("=" * 70); print("MLP BLOCK -- DATA LOADED"); print("=" * 70)
print(f"Linear train {Xl_train.shape}  Train n={len(yt_arr):,} ({yt_arr.mean()*100:.1f}% rejection)")

# ---------------- THE FIX: raw Optuna params -> real constructor params ----------------
def _mlp_raw_to_ctor_params(raw):
    """study.best_params holds RAW suggest_*() names (n_layers, units_l0,
    units_l1) -- NOT the derived hidden_layer_sizes MLPClassifier actually
    needs. This is exactly what crashed last run. Rebuild the real
    constructor dict here, ONCE, before it ever touches best_params.pkl."""
    n_layers = raw['n_layers']
    sizes = tuple(raw[f'units_l{i}'] for i in range(n_layers))
    return {'hidden_layer_sizes': sizes, 'alpha': raw['alpha'],
            'learning_rate_init': raw['learning_rate_init']}

def build_mlp(params):
    # S3_THRESHOLD only -> plain model. No SMOTE wrap, no class_weight
    # (MLPClassifier has no class_weight kwarg at all).
    fixed = {'random_state': RANDOM_STATE, 'max_iter': 300, 'early_stopping': True,
              'n_iter_no_change': 15, 'validation_fraction': 0.1, 'activation': 'relu'}
    return MLPClassifier(**{**fixed, **params})

def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience: return
        if trial.number - study.best_trial.number >= patience: study.stop()
    return callback

# ---------------- TUNE (half the training data, 3-fold, S3_THRESHOLD only) ----------------
idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=0.5, stratify=yt_arr, random_state=RANDOM_STATE)
X_tune, y_tune = Xl_train[idx], yt_arr[idx]

print(f"\nTuning {MODEL_NAME}/{STRATEGY} ({N_TRIALS_MLP} trials)...", end=' ', flush=True)

def objective(trial):
    raw_n_layers = trial.suggest_int('n_layers', 1, 2)
    sizes = tuple(trial.suggest_int(f'units_l{i}', 32, 256) for i in range(raw_n_layers))
    params = {'hidden_layer_sizes': sizes,
              'alpha': trial.suggest_float('alpha', 1e-5, 1e-1, log=True),
              'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True)}
    scores = []
    for tr_idx, val_idx in skf_tune.split(X_tune, y_tune):
        try:
            m = build_mlp(params)
            m.fit(X_tune[tr_idx], y_tune[tr_idx])
            proba = m.predict_proba(X_tune[val_idx])[:, 1]
            if len(np.unique(y_tune[val_idx])) < 2: continue
            scores.append(roc_auc_score(y_tune[val_idx], proba))
        except Exception as e:
            print(f"[WARN] fold failed: {e}")
    return float(np.mean(scores)) if scores else 0.0

study = optuna.create_study(direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=N_TRIALS_MLP, show_progress_bar=False, n_jobs=1,
                callbacks=[make_early_stop_callback()])
print(f"best CV AUROC = {study.best_value:.4f}")

ctor_params = _mlp_raw_to_ctor_params(study.best_params)
save_best_params({(MODEL_NAME, STRATEGY): ctor_params})
print(f"Saved constructor-ready params: {ctor_params}")

# ---------------- FINAL FIT + OOF THRESHOLD (no leakage) + EVAL ----------------
model = build_mlp(ctor_params)
model.fit(Xl_train, yt_arr)
y_prob = model.predict_proba(Xl_test)[:, 1]

cv_p = cross_val_predict(build_mlp(ctor_params), Xl_train, yt_arr, cv=skf_eval,
                          method='predict_proba', n_jobs=-1)[:, 1]
threshold = find_optimal_threshold(yt_arr, cv_p)
y_pred = (y_prob >= threshold).astype(int)

metrics = evaluate_model(ytest_arr, y_prob, y_pred, MODEL_NAME, STRATEGY, threshold)
print(f"\n{MODEL_NAME}/{STRATEGY}  AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
      f"Brier={metrics['brier_score']:.4f}  ECE={metrics['ece']:.4f}")

pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': y_prob, 'y_pred': y_pred}
             ).to_csv(OUT_DIR / f"predictions_{MODEL_NAME}_{STRATEGY}.csv", index=False)
with open(MDL_DIR / f"model_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(model, f)
append_metrics([metrics])

print(f"\nSaved -> predictions_{MODEL_NAME}_{STRATEGY}.csv, model_{MODEL_NAME}_{STRATEGY}.pkl, "
      f"row appended to all_metrics.csv")
print("MLP block complete.")

======================================================================
MLP BLOCK -- DATA LOADED
======================================================================
Linear train (27431, 618)  Train n=27,431 (36.7% rejection)

Tuning MLP/S3_THRESHOLD (40 trials)... best CV AUROC = 0.6417
Saved constructor-ready params: {'hidden_layer_sizes': (183,), 'alpha': 0.002781857010763973, 'learning_rate_init': 0.0006666018811110477}

MLP/S3_THRESHOLD  AUROC=0.6069  AUPRC=0.3867  Brier=0.2424  ECE=0.1673

Saved -> predictions_MLP_S3_THRESHOLD.csv, model_MLP_S3_THRESHOLD.pkl, row appended to all_metrics.csv
MLP block complete.

# 6A 4/4 2.CATBOOST

In [ ]:
# ==============================================================================
# BLOCK — CATBOOST TRAINING ONLY (S1_SMOTE strategy), fully self-contained
# 1-YEAR REJECTION.
#
# SPEED, NOT SHORTCUT: (1) per-fold early stopping during Optuna tuning so
# weak trials die fast instead of running to the iteration cap; (2) the
# best-iteration count CatBoost itself found during tuning is reused as a
# FIXED iteration count for the final fit -- so the final model trains on
# 100% of the training data in one pass, no held-out early-stop slice
# needed, no overtraining either; (3) S1_SMOTE skips the extra CV pass
# S3_THRESHOLD needs for decision-threshold selection. None of this
# changes what the model learns -- it just stops wasting iterations/folds
# on things that don't move the answer.
#
# NOTE: switched from wrapping CatBoost in an ImblearnPipeline to manual
# SMOTE().fit_resample() calls, because eval_set/early_stopping_rounds
# can't cleanly pass through a generic sklearn Pipeline.fit() -- this is
# functionally identical SMOTE application, just restructured to allow
# early stopping.
# ==============================================================================
from pathlib import Path
import pickle, warnings
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)

from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
N_TRIALS_CATBOOST = 50        # cut from 60 -- only 1 strategy trained now
EARLY_STOP_PATIENCE_OPTUNA = 10   # Optuna-level: give up on the whole search after 10 stale trials
EARLY_STOPPING_ROUNDS_CB = 50     # CatBoost-level: stop a single fit if no improvement for 50 rounds
MODEL_NAME, STRATEGY = 'CatBoost', 'S1_SMOTE'
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE HELPERS ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params(); params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    # Dedup by (model, strategy) -- reruns of this block cleanly OVERWRITE
    # the old CatBoost/S1_SMOTE row, never duplicate it.
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

# ---------------- METRIC HELPERS (identical to the rest of the pipeline) ----------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception:
            continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4),
            'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA (tree family only -- CatBoost doesn't need linear-encoded data) ----------------
Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xt_train, Xt_test = Xtr_tree.values.astype('float32'), Xte_tree.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values

print("=" * 70); print("CATBOOST BLOCK -- DATA LOADED"); print("=" * 70)
print(f"Tree train {Xt_train.shape}  Train n={len(yt_arr):,} ({yt_arr.mean()*100:.1f}% rejection)")

# ---------------- SEARCH SPACE ----------------
def _cb_space(t):
    return {
        'iterations': t.suggest_int('iterations', 200, 800),
        'depth': t.suggest_int('depth', 3, 10),
        'learning_rate': t.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'l2_leaf_reg': t.suggest_float('l2_leaf_reg', 1e-2, 30.0, log=True),
        'border_count': t.suggest_int('border_count', 32, 255),
        'bagging_temperature': t.suggest_float('bagging_temperature', 0.0, 1.0),
    }

def make_early_stop_callback(patience=EARLY_STOP_PATIENCE_OPTUNA):
    def callback(study, trial):
        if trial.number < patience: return
        if trial.number - study.best_trial.number >= patience: study.stop()
    return callback

# ---------------- TUNE (half the training data, 3-fold, per-fold early stopping) ----------------
idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=0.5, stratify=yt_arr, random_state=RANDOM_STATE)
X_tune, y_tune = Xt_train[idx], yt_arr[idx]

print(f"\nTuning {MODEL_NAME}/{STRATEGY} ({N_TRIALS_CATBOOST} trials, early-stopping per fold)...", end=' ', flush=True)

def objective(trial):
    params = _cb_space(trial)
    scores, best_iters = [], []
    for tr_idx, val_idx in skf_tune.split(X_tune, y_tune):
        try:
            X_tr, y_tr = X_tune[tr_idx], y_tune[tr_idx]
            X_val, y_val = X_tune[val_idx], y_tune[val_idx]
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            X_tr_res, y_tr_res = smote.fit_resample(X_tr, y_tr)

            model = CatBoostClassifier(**params, random_seed=RANDOM_STATE, verbose=0, allow_writing_files=False)
            model.fit(X_tr_res, y_tr_res, eval_set=(X_val, y_val),
                      early_stopping_rounds=EARLY_STOPPING_ROUNDS_CB, use_best_model=True)

            if len(np.unique(y_val)) < 2: continue
            proba = model.predict_proba(X_val)[:, 1]
            scores.append(roc_auc_score(y_val, proba))
            bi = model.get_best_iteration()
            best_iters.append(bi if bi is not None else params['iterations'])
        except Exception as e:
            print(f"[WARN] fold failed: {e}")
    trial.set_user_attr('avg_best_iter', float(np.mean(best_iters)) if best_iters else float(params['iterations']))
    return float(np.mean(scores)) if scores else 0.0

study = optuna.create_study(direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=N_TRIALS_CATBOOST, show_progress_bar=False, n_jobs=1,
                callbacks=[make_early_stop_callback()])
print(f"best CV AUROC = {study.best_value:.4f}")

# ---------------- BAKE THE EARLY-STOPPED ITERATION COUNT INTO THE FINAL FIT ----------------
best_iterations = int(round(study.best_trial.user_attrs.get('avg_best_iter', study.best_params.get('iterations', 500))))
ctor_params = dict(study.best_params)
ctor_params['iterations'] = best_iterations   # fixed, no early-stop slice needed on the final fit
save_best_params({(MODEL_NAME, STRATEGY): ctor_params})
print(f"Saved constructor-ready params (iterations fixed to CV-observed best={best_iterations}): {ctor_params}")

# ---------------- FINAL FIT ON 100% OF TRAINING DATA, NO EARLY-STOP SPLIT NEEDED ----------------
smote_final = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
X_train_res, y_train_res = smote_final.fit_resample(Xt_train, yt_arr)

model = CatBoostClassifier(**ctor_params, random_seed=RANDOM_STATE, verbose=0, allow_writing_files=False)
model.fit(X_train_res, y_train_res)
y_prob = model.predict_proba(Xt_test)[:, 1]
threshold = 0.5   # S1_SMOTE strategy uses the plain 0.5 cutoff, same as the original run
y_pred = (y_prob >= threshold).astype(int)

metrics = evaluate_model(ytest_arr, y_prob, y_pred, MODEL_NAME, STRATEGY, threshold)
print(f"\n{MODEL_NAME}/{STRATEGY}  AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
      f"Brier={metrics['brier_score']:.4f}  ECE={metrics['ece']:.4f}")

pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': y_prob, 'y_pred': y_pred}
             ).to_csv(OUT_DIR / f"predictions_{MODEL_NAME}_{STRATEGY}.csv", index=False)
with open(MDL_DIR / f"model_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(model, f)
append_metrics([metrics])

print(f"\nSaved -> predictions_{MODEL_NAME}_{STRATEGY}.csv, model_{MODEL_NAME}_{STRATEGY}.pkl, "
      f"best_params.pkl updated, row appended/overwritten in all_metrics.csv")
print("CatBoost block complete.")

======================================================================
CATBOOST BLOCK -- DATA LOADED
======================================================================
Tree train (27431, 266)  Train n=27,431 (36.7% rejection)

Tuning CatBoost/S1_SMOTE (50 trials, early-stopping per fold)... best CV AUROC = 0.6486
Saved constructor-ready params (iterations fixed to CV-observed best=695): {'iterations': 695, 'depth': 4, 'learning_rate': 0.01855998084649059, 'l2_leaf_reg': 0.04342298948286135, 'border_count': 100, 'bagging_temperature': 0.5247564316322378}

CatBoost/S1_SMOTE  AUROC=0.6157  AUPRC=0.4071  Brier=0.2157  ECE=0.1144

Saved -> predictions_CatBoost_S1_SMOTE.csv, model_CatBoost_S1_SMOTE.pkl, best_params.pkl updated, row appended/overwritten in all_metrics.csv
CatBoost block complete.

# 6A 4/4 3.ENSEMBLE

In [ ]:
# ==============================================================================
# BLOCK — ENSEMBLE, fully self-contained. Repairs any missing all_metrics.csv
# rows first (CatBoost/S1_SMOTE + MLP/S3_THRESHOLD never got appended after
# the earlier crash, even though their predictions CSVs were already saved),
# then selects one best-strategy candidate per model family, builds Voting
# (simple average) and Stacking (LR meta-learner on out-of-fold predictions).
# ==============================================================================
from pathlib import Path
import pickle
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

from catboost import CatBoostClassifier
import xgboost as xgb
import lightgbm as lgb

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "1yr"
OUT_DIR = BASE / "results" / "1yr"
MDL_DIR = BASE / "models" / "1yr"
RANDOM_STATE = 42
SMOTE_K = 5
CV_FOLDS_EVAL = 5
N_BOOTSTRAP = 1000
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE + METRIC HELPERS (same as Block 1) ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f: return pickle.load(f)
    return {}

def append_metrics(rows: list):
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception: continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float); y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob); y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4), 'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA ----------------
Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
Xtr_lin  = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
Xte_lin  = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xt_train, Xt_test = Xtr_tree.values.astype('float32'), Xte_tree.values.astype('float32')
Xl_train, Xl_test = Xtr_lin.values.astype('float32'), Xte_lin.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values
DATA_BY_KIND = {'tree': (Xt_train, Xt_test), 'linear': (Xl_train, Xl_test)}
DATA_KIND_BY_MODEL = {
    'LogisticRegression': 'linear', 'LinearSVM': 'linear', 'SGD': 'linear', 'MLP': 'linear',
    'RandomForest': 'tree', 'AdaBoost': 'tree', 'XGBoost': 'tree', 'LightGBM': 'tree', 'CatBoost': 'tree',
}

# ---------------- REPAIR: recover any all_metrics.csv row lost to the earlier crash ----------------
# The MLP crash meant append_metrics() never ran for CatBoost OR MLP, even
# though both already had their predictions CSVs safely on disk. Recompute
# + append any missing row now -- otherwise best_per_family below silently
# drops a real, already-trained model (CatBoost, the current best single
# model) from ensemble candidacy and from the final results table.
def repair_missing_metric(model_name, strategy):
    existing = pd.read_csv(METRICS_PATH) if METRICS_PATH.exists() else pd.DataFrame(columns=['model', 'strategy'])
    already_there = ((existing['model'] == model_name) & (existing['strategy'] == strategy)).any() if len(existing) else False
    if already_there:
        return
    pred_csv = OUT_DIR / f"predictions_{model_name}_{strategy}.csv"
    if not pred_csv.exists():
        print(f"  [REPAIR] {model_name}/{strategy} missing from all_metrics.csv and no predictions CSV "
              f"found either -- this model must be retrained, cannot recover.")
        return
    preds = pd.read_csv(pred_csv)
    m = evaluate_model(preds['y_true'].values, preds['y_prob'].values, preds['y_pred'].values,
                        model_name, strategy, threshold=0.5)
    append_metrics([m])
    print(f"  [REPAIR] recovered {model_name}/{strategy} from saved predictions "
          f"(AUROC={m['auroc']:.4f}) -- appended to all_metrics.csv")

print("=" * 70); print("ENSEMBLE BLOCK -- REPAIR CHECK"); print("=" * 70)
repair_missing_metric('CatBoost', 'S1_SMOTE')
repair_missing_metric('MLP', 'S3_THRESHOLD')

# ---------------- SELECT BEST-PER-FAMILY (auto = "whichever strategy is better") ----------------
all_metrics = pd.read_csv(METRICS_PATH)
all_metrics = all_metrics[~all_metrics['model'].str.startswith('Ensemble')]
best_per_family = all_metrics.loc[all_metrics.groupby('model')['auroc'].idxmax()].reset_index(drop=True)
print("\n" + "=" * 70); print("BEST STRATEGY PER MODEL FAMILY (ensemble candidates)"); print("=" * 70)
print(best_per_family[['model', 'strategy', 'auroc', 'auprc', 'brier_score', 'ece']].to_string(index=False))

# ---------------- RECONSTRUCTORS ----------------
def build_catboost(params, strategy):
    all_params = {**params, 'random_seed': RANDOM_STATE, 'verbose': 0, 'allow_writing_files': False}
    if strategy == 'S2_BALANCED': all_params['auto_class_weights'] = 'Balanced'
    model = CatBoostClassifier(**all_params)
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model

def build_mlp(params, strategy):
    fixed = {'random_state': RANDOM_STATE, 'max_iter': 300, 'early_stopping': True,
              'n_iter_no_change': 15, 'validation_fraction': 0.1, 'activation': 'relu'}
    model = MLPClassifier(**{**fixed, **params})
    if strategy in ('S1_SMOTE', 'S2_BALANCED'):
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model

def generic_reconstruct(model_name, params, strategy):
    if model_name == 'RandomForest':
        p = {**params, 'random_state': RANDOM_STATE, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = RandomForestClassifier(**p)
    elif model_name == 'XGBoost':
        p = {**params, 'random_state': RANDOM_STATE, 'objective': 'binary:logistic',
             'eval_metric': 'logloss', 'verbosity': 0, 'n_jobs': -1}
        if strategy == 'S2_BALANCED':
            n_pos, n_neg = int((yt_arr == 1).sum()), int((yt_arr == 0).sum())
            p['scale_pos_weight'] = n_neg / max(n_pos, 1)
        base = xgb.XGBClassifier(**p)
    elif model_name == 'LightGBM':
        p = {**params, 'random_state': RANDOM_STATE, 'verbosity': -1, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = lgb.LGBMClassifier(**p)
    elif model_name == 'CatBoost':
        return build_catboost(params, strategy)
    elif model_name == 'AdaBoost':
        params = dict(params); depth = params.pop('base_max_depth', 3)
        cw = 'balanced' if strategy == 'S2_BALANCED' else None
        tree = DecisionTreeClassifier(max_depth=depth, class_weight=cw, random_state=RANDOM_STATE)
        base = AdaBoostClassifier(estimator=tree, random_state=RANDOM_STATE, **params)
    elif model_name == 'LogisticRegression':
        p = {**params, 'max_iter': 500, 'solver': 'saga', 'random_state': RANDOM_STATE}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = LogisticRegression(**p)
    elif model_name == 'SGD':
        p = {**params, 'loss': 'log_loss', 'max_iter': 100, 'random_state': RANDOM_STATE, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = SGDClassifier(**p)
    elif model_name == 'MLP':
        return build_mlp(params, strategy)
    else:
        raise ValueError(f"No reconstructor for {model_name} -- add one before including it in the ensemble.")
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', base)])
    return base

# ---------------- OOF (for stacking) + TEST PREDICTIONS (for both) PER MEMBER ----------------
all_best_params = load_best_params()
ensemble_members = best_per_family.to_dict('records')
oof_preds, test_preds, member_names = {}, {}, []

print("\n" + "=" * 70); print("GENERATING OOF + TEST PREDICTIONS PER MEMBER"); print("=" * 70)
for row in ensemble_members:
    name, strategy = row['model'], row['strategy']
    params = all_best_params.get((name, strategy), {})
    data_kind = DATA_KIND_BY_MODEL.get(name)
    if data_kind is None:
        print(f"  Skipping {name}: unknown data family, add it to DATA_KIND_BY_MODEL.")
        continue
    X_train, X_test = DATA_BY_KIND[data_kind]
    print(f"  {name}/{strategy}...", end=' ', flush=True)
    try:
        est = generic_reconstruct(name, dict(params), strategy)
        oof = cross_val_predict(est, X_train, yt_arr, cv=skf_eval, method='predict_proba', n_jobs=-1)[:, 1]
        oof_preds[name] = oof
        pred_csv = OUT_DIR / f"predictions_{name}_{strategy}.csv"
        test_preds[name] = pd.read_csv(pred_csv)['y_prob'].values
        member_names.append(name)
        print("done.")
    except Exception as e:
        print(f"SKIPPED -- {e}")

print(f"\nEnsemble members: {member_names}")
meta_X_train = np.column_stack([oof_preds[m] for m in member_names])
meta_X_test = np.column_stack([test_preds[m] for m in member_names])

# ---------------- VOTING (simple average) ----------------
voting_prob = meta_X_test.mean(axis=1)
voting_metrics = evaluate_model(ytest_arr, voting_prob, (voting_prob >= 0.5).astype(int), 'Ensemble_Voting', 'AVERAGE', 0.5)
print("\nVoting ensemble:", {k: voting_metrics[k] for k in ['auroc', 'auprc', 'brier_score', 'ece']})

# ---------------- STACKING (LR meta-learner on OOF features) ----------------
meta_learner = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)
meta_learner.fit(meta_X_train, yt_arr)
stacking_prob = meta_learner.predict_proba(meta_X_test)[:, 1]
stacking_metrics = evaluate_model(ytest_arr, stacking_prob, (stacking_prob >= 0.5).astype(int), 'Ensemble_Stacking', 'META_LR', 0.5)
print("Stacking ensemble:", {k: stacking_metrics[k] for k in ['auroc', 'auprc', 'brier_score', 'ece']})
print("Meta-learner coefficients (higher = more weight):", dict(zip(member_names, np.round(meta_learner.coef_[0], 3))))

for name, probs, m in [('Ensemble_Voting', voting_prob, voting_metrics), ('Ensemble_Stacking', stacking_prob, stacking_metrics)]:
    pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': probs}
                 ).to_csv(OUT_DIR / f"predictions_{name}.csv", index=False)
append_metrics([voting_metrics, stacking_metrics])
print("\nEnsemble block complete.")

======================================================================
ENSEMBLE BLOCK -- REPAIR CHECK
======================================================================

======================================================================
BEST STRATEGY PER MODEL FAMILY (ensemble candidates)
======================================================================
             model     strategy  auroc  auprc  brier_score      ece
          AdaBoost  S2_BALANCED 0.6193 0.3992       0.2469 0.209948
          CatBoost     S1_SMOTE 0.6157 0.4071       0.2157 0.114409
          LightGBM S3_THRESHOLD 0.6338 0.4259       0.2064 0.080487
         LinearSVM     S1_SMOTE 0.6033 0.3803       0.2962 0.301998
LogisticRegression     S1_SMOTE 0.6198 0.4024       0.3491 0.377964
               MLP S3_THRESHOLD 0.6069 0.3867       0.2424 0.167259
      RandomForest  S2_BALANCED 0.6177 0.3976       0.2318 0.170525
               SGD     S1_SMOTE 0.6175 0.4016       0.3320 0.354078
           XGBoost S3_THRESHOLD 0.6320 0.4217       0.2078 0.086234

======================================================================
GENERATING OOF + TEST PREDICTIONS PER MEMBER
======================================================================
  AdaBoost/S2_BALANCED... done.
  CatBoost/S1_SMOTE... done.
  LightGBM/S3_THRESHOLD... done.
  LinearSVM/S1_SMOTE... SKIPPED -- No reconstructor for LinearSVM -- add one before including it in the ensemble.
  LogisticRegression/S1_SMOTE... done.
  MLP/S3_THRESHOLD... done.
  RandomForest/S2_BALANCED... done.
  SGD/S1_SMOTE... done.
  XGBoost/S3_THRESHOLD... done.

Ensemble members: ['AdaBoost', 'CatBoost', 'LightGBM', 'LogisticRegression', 'MLP', 'RandomForest', 'SGD', 'XGBoost']

Voting ensemble: {'auroc': 0.635, 'auprc': 0.4246, 'brier_score': 0.238, 'ece': 0.194377}
Stacking ensemble: {'auroc': 0.6363, 'auprc': 0.4262, 'brier_score': 0.2169, 'ece': 0.108528}
Meta-learner coefficients (higher = more weight): {'AdaBoost': np.float64(-0.781), 'CatBoost': np.float64(-1.141), 'LightGBM': np.float64(5.079), 'LogisticRegression': np.float64(-0.043), 'MLP': np.float64(0.793), 'RandomForest': np.float64(0.441), 'SGD': np.float64(0.205), 'XGBoost': np.float64(3.145)}

Ensemble block complete.

# 6A 4/4 4.STATS

In [ ]:
# ==============================================================================
# BLOCK — STATS, CALIBRATION, DCA, FIGURES. Fully self-contained -- reloads
# all_metrics.csv + saved predictions CSVs, no in-memory dependency on
# Blocks 1/2.
# ==============================================================================
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve

BASE = Path(r"D:\Thesis\Thesis_parquet")
OUT_DIR = BASE / "results" / "1yr"
FIG_DIR = OUT_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# ---------------- IDENTIFY "BEST SINGLE" MODEL (excluding ensembles!) ----------------
# Block 2 already appended Ensemble_Voting/Ensemble_Stacking rows to
# all_metrics.csv -- must filter those out here or DeLong would end up
# comparing the ensemble against itself.
final_table = pd.read_csv(OUT_DIR / "all_metrics.csv")
non_ensemble = final_table[~final_table['model'].str.startswith('Ensemble')]
best_single = non_ensemble.loc[non_ensemble['auroc'].idxmax()]
best_single_probs = pd.read_csv(OUT_DIR / f"predictions_{best_single['model']}_{best_single['strategy']}.csv")['y_prob'].values
voting_df = pd.read_csv(OUT_DIR / "predictions_Ensemble_Voting.csv")
stacking_df = pd.read_csv(OUT_DIR / "predictions_Ensemble_Stacking.csv")
ytest_arr = voting_df['y_true'].values
voting_prob, stacking_prob = voting_df['y_prob'].values, stacking_df['y_prob'].values

print("=" * 70); print(f"BEST SINGLE MODEL: {best_single['model']}/{best_single['strategy']} "
                        f"(AUROC={best_single['auroc']:.4f})"); print("=" * 70)

# ---------------- DELONG'S TEST (self-verified against sklearn) ----------------
def _compute_midrank(x):
    J = np.argsort(x); Z = x[J]; N = len(x); T = np.zeros(N, dtype=float)
    i = 0
    while i < N:
        j = i
        while j < N and Z[j] == Z[i]: j += 1
        T[i:j] = 0.5 * (i + j - 1) + 1
        i = j
    T2 = np.empty(N, dtype=float); T2[J] = T
    return T2

def _fast_delong(preds_sorted_T, m):
    n = preds_sorted_T.shape[1] - m
    pos, neg = preds_sorted_T[:, :m], preds_sorted_T[:, m:]
    k = preds_sorted_T.shape[0]
    tx = np.empty([k, m]); ty = np.empty([k, n]); tz = np.empty([k, m + n])
    for r in range(k):
        tx[r, :] = _compute_midrank(pos[r, :]); ty[r, :] = _compute_midrank(neg[r, :]); tz[r, :] = _compute_midrank(preds_sorted_T[r, :])
    aucs = tz[:, :m].sum(axis=1) / m / n - (m + 1.0) / 2.0 / n
    v01 = (tz[:, :m] - tx) / n; v10 = 1.0 - (tz[:, m:] - ty) / m
    sx = np.cov(v01); sy = np.cov(v10)
    return aucs, sx / m + sy / n

def delong_roc_test(y_true, prob_a, prob_b, label_a="A", label_b="B"):
    y_true = np.asarray(y_true); order = np.argsort(-y_true); m = int(y_true.sum())
    preds_sorted_T = np.vstack([prob_a, prob_b])[:, order]
    aucs, cov = _fast_delong(preds_sorted_T, m)
    sk_auc_a, sk_auc_b = roc_auc_score(y_true, prob_a), roc_auc_score(y_true, prob_b)
    assert abs(aucs[0] - sk_auc_a) < 1e-9, f"DeLong/sklearn AUC mismatch for {label_a} -- DO NOT TRUST THIS P-VALUE"
    assert abs(aucs[1] - sk_auc_b) < 1e-9, f"DeLong/sklearn AUC mismatch for {label_b} -- DO NOT TRUST THIS P-VALUE"
    l = np.array([[1, -1]]); var = float(np.dot(np.dot(l, cov), l.T)[0, 0])
    z = abs(aucs[0] - aucs[1]) / np.sqrt(var) if var > 0 else 0.0
    p = 2 * (1 - stats.norm.cdf(z))
    return {'auc_a': aucs[0], 'auc_b': aucs[1], 'diff': aucs[0] - aucs[1], 'z': z, 'p_value': p, 'verified_against_sklearn': True}

print("\n" + "=" * 70); print("DELONG'S TEST (internal comparisons only -- same test set)"); print("=" * 70)
delong_results = []
for name, probs in [('Ensemble_Voting', voting_prob), ('Ensemble_Stacking', stacking_prob)]:
    res = delong_roc_test(ytest_arr, best_single_probs, probs, label_a=f"{best_single['model']}/{best_single['strategy']}", label_b=name)
    print(f"  {best_single['model']}/{best_single['strategy']} (AUROC={res['auc_a']:.4f}) vs {name} (AUROC={res['auc_b']:.4f}): "
          f"diff={res['diff']:+.4f}, p={res['p_value']:.4f} (verified: {res['verified_against_sklearn']})")
    delong_results.append({'comparison': f"best_single_vs_{name}", **res})
pd.DataFrame(delong_results).to_csv(OUT_DIR / "delong_tests.csv", index=False)

# ---------------- DECISION CURVE ANALYSIS ----------------
def decision_curve(y_true, y_prob, thresholds=np.arange(0.01, 0.99, 0.01)):
    n = len(y_true); prevalence = y_true.mean(); rows = []
    for pt in thresholds:
        pred_pos = y_prob >= pt
        tp = np.sum(pred_pos & (y_true == 1)); fp = np.sum(pred_pos & (y_true == 0))
        nb_model = (tp / n) - (fp / n) * (pt / (1 - pt))
        nb_all = prevalence - (1 - prevalence) * (pt / (1 - pt))
        rows.append({'threshold': pt, 'net_benefit_model': nb_model, 'net_benefit_treat_all': nb_all, 'net_benefit_treat_none': 0.0})
    return pd.DataFrame(rows)

dca_best = decision_curve(ytest_arr, best_single_probs)
dca_stack = decision_curve(ytest_arr, stacking_prob)
dca_best.to_csv(OUT_DIR / "dca_best_single.csv", index=False)
dca_stack.to_csv(OUT_DIR / "dca_stacking.csv", index=False)

plt.figure(figsize=(7, 5))
plt.plot(dca_best['threshold'], dca_best['net_benefit_model'], label=f"{best_single['model']} (best single)")
plt.plot(dca_stack['threshold'], dca_stack['net_benefit_model'], label="Stacking ensemble")
plt.plot(dca_best['threshold'], dca_best['net_benefit_treat_all'], '--', color='gray', label="Treat all")
plt.plot(dca_best['threshold'], dca_best['net_benefit_treat_none'], ':', color='black', label="Treat none")
plt.xlabel("Threshold probability"); plt.ylabel("Net benefit"); plt.legend()
plt.title("Decision Curve Analysis — 1-year rejection"); plt.ylim(bottom=-0.05)
plt.savefig(FIG_DIR / "dca_1yr.png", dpi=150, bbox_inches='tight'); plt.close()

# ---------------- ROC + CALIBRATION FIGURES ----------------
def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float); y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    edges = np.linspace(0, 1, n_bins + 1); bins = []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        bins.append({'conf': float(y_prob[mask].mean()), 'acc': float(y_true[mask].mean())})
    return bins

plt.figure(figsize=(6, 6))
for name, probs in [(f"{best_single['model']} (best single)", best_single_probs), ("Voting", voting_prob), ("Stacking", stacking_prob)]:
    fpr, tpr, _ = roc_curve(ytest_arr, probs)
    plt.plot(fpr, tpr, label=f"{name} (AUROC={roc_auc_score(ytest_arr, probs):.3f})")
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel("1 - Specificity"); plt.ylabel("Sensitivity"); plt.legend()
plt.title("ROC — 1-year rejection"); plt.savefig(FIG_DIR / "roc_1yr.png", dpi=150, bbox_inches='tight'); plt.close()

plt.figure(figsize=(6, 6))
for name, probs in [(f"{best_single['model']}", best_single_probs), ("Stacking", stacking_prob)]:
    bins = compute_ece_mce(ytest_arr, probs)
    if bins:
        bdf = pd.DataFrame(bins)
        plt.plot(bdf['conf'], bdf['acc'], marker='o', label=name)
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel("Predicted probability"); plt.ylabel("Observed frequency"); plt.legend()
plt.title("Calibration — 1-year rejection"); plt.savefig(FIG_DIR / "calibration_1yr.png", dpi=150, bbox_inches='tight'); plt.close()
print(f"\nFigures saved -> {FIG_DIR}")

# ---------------- PUBLICATION TABLE ----------------
final_table = pd.read_csv(OUT_DIR / "all_metrics.csv").sort_values('auroc', ascending=False).reset_index(drop=True)
final_table['auroc_display'] = final_table.apply(lambda r: f"{r['auroc']:.3f} ({r['auroc_ci_lo']:.3f}-{r['auroc_ci_hi']:.3f})", axis=1)
final_table['auprc_display'] = final_table.apply(lambda r: f"{r['auprc']:.3f} ({r['auprc_ci_lo']:.3f}-{r['auprc_ci_hi']:.3f})", axis=1)
final_table.to_csv(OUT_DIR / "publication_table_1yr.csv", index=False)

print("\n" + "=" * 70); print("FINAL PUBLICATION TABLE — 1-YEAR REJECTION"); print("=" * 70)
print(final_table[['model', 'strategy', 'auroc_display', 'auprc_display', 'brier_score', 'ece', 'hl_p_value']].to_string(index=False))
print("\nStats/Calibration/DCA/Figures block complete.")
print("\nFigures are: calibration_1yr.png, roc_1yr.png, dca_1yr.png saved in D:\Thesis\Thesis_parquet\results\1yr\figures")

======================================================================
BEST SINGLE MODEL: XGBoost/S2_BALANCED (AUROC=0.6487)
======================================================================

======================================================================
DELONG'S TEST (internal comparisons only -- same test set)
======================================================================
  XGBoost/S2_BALANCED (AUROC=0.6487) vs Ensemble_Voting (AUROC=0.6453): diff=+0.0034, p=0.1898 (verified: True)
  XGBoost/S2_BALANCED (AUROC=0.6487) vs Ensemble_Stacking (AUROC=0.6512): diff=-0.0025, p=0.1474 (verified: True)

Figures saved -> D:\Thesis\Thesis_parquet\results\1yr\figures

======================================================================
FINAL PUBLICATION TABLE — 1-YEAR REJECTION
======================================================================
             model     strategy       auroc_display       auprc_display  brier_score      ece  hl_p_value
 Ensemble_Stacking      META_LR 0.651 (0.641-0.661) 0.448 (0.431-0.464)     0.221100 0.138327         0.0
           XGBoost  S2_BALANCED 0.649 (0.639-0.658) 0.443 (0.427-0.459)     0.226619 0.168363         0.0
          LightGBM  S2_BALANCED 0.646 (0.636-0.655) 0.437 (0.420-0.453)     0.233800 0.188051         0.0
           XGBoost S3_THRESHOLD 0.645 (0.635-0.655) 0.434 (0.418-0.450)     0.205365 0.083740         0.0
   Ensemble_Voting      AVERAGE 0.645 (0.635-0.655) 0.440 (0.424-0.455)     0.261300 0.250016         0.0
          LightGBM     S1_SMOTE 0.645 (0.634-0.654) 0.432 (0.416-0.447)     0.210900 0.102658         0.0
          LightGBM S3_THRESHOLD 0.644 (0.634-0.654) 0.437 (0.421-0.453)     0.211500 0.112354         0.0
          CatBoost     S1_SMOTE 0.644 (0.634-0.654) 0.447 (0.431-0.463)     0.212100 0.116565         0.0
           XGBoost     S1_SMOTE 0.640 (0.630-0.650) 0.435 (0.419-0.451)     0.210404 0.104847         0.0
      RandomForest  S2_BALANCED 0.640 (0.630-0.650) 0.425 (0.409-0.440)     0.224900 0.157673         0.0
      RandomForest S3_THRESHOLD 0.639 (0.629-0.649) 0.425 (0.409-0.441)     0.207000 0.085040         0.0
          AdaBoost S3_THRESHOLD 0.626 (0.616-0.636) 0.403 (0.388-0.418)     0.218555 0.129400         0.0
LogisticRegression     S1_SMOTE 0.625 (0.615-0.635) 0.407 (0.392-0.421)     0.336600 0.359838         0.0
LogisticRegression S3_THRESHOLD 0.625 (0.615-0.634) 0.409 (0.394-0.424)     0.314800 0.329672         0.0
LogisticRegression  S2_BALANCED 0.625 (0.614-0.634) 0.407 (0.392-0.422)     0.391100 0.431942         0.0
               SGD     S1_SMOTE 0.621 (0.611-0.631) 0.408 (0.393-0.423)     0.314800 0.328227         0.0
      RandomForest     S1_SMOTE 0.618 (0.608-0.629) 0.418 (0.401-0.434)     0.214100 0.108173         0.0
               SGD  S2_BALANCED 0.613 (0.602-0.623) 0.401 (0.386-0.415)     0.352800 0.384975         0.0
          AdaBoost     S1_SMOTE 0.612 (0.601-0.623) 0.404 (0.388-0.419)     0.236775 0.180252         0.0
               SGD S3_THRESHOLD 0.612 (0.602-0.622) 0.399 (0.384-0.413)     0.268100 0.247332         0.0
         LinearSVM     S1_SMOTE 0.612 (0.601-0.622) 0.390 (0.375-0.404)     0.291500 0.295378         0.0
         LinearSVM  S2_BALANCED 0.609 (0.599-0.619) 0.388 (0.374-0.401)     0.315800 0.333446         0.0
          AdaBoost  S2_BALANCED 0.608 (0.597-0.618) 0.383 (0.369-0.395)     0.263231 0.183968         0.0
         LinearSVM S3_THRESHOLD 0.607 (0.597-0.617) 0.387 (0.373-0.400)     0.327600 0.349709         0.0
               MLP S3_THRESHOLD 0.602 (0.592-0.612) 0.388 (0.373-0.403)     0.339400 0.350057         0.0

Stats/Calibration/DCA/Figures block complete.

esultsyrigures

In [ ]:
             model     strategy       auroc_display       auprc_display  brier_score      ece  hl_p_value
 Ensemble_Stacking      META_LR 0.651 (0.641-0.661) 0.448 (0.431-0.464)     0.221100 0.138327         0.0
           XGBoost  S2_BALANCED 0.649 (0.639-0.658) 0.443 (0.427-0.459)     0.226619 0.168363         0.0
          LightGBM  S2_BALANCED 0.646 (0.636-0.655) 0.437 (0.420-0.453)     0.233800 0.188051         0.0
           XGBoost S3_THRESHOLD 0.645 (0.635-0.655) 0.434 (0.418-0.450)     0.205365 0.083740         0.0
   Ensemble_Voting      AVERAGE 0.645 (0.635-0.655) 0.440 (0.424-0.455)     0.261300 0.250016         0.0
          LightGBM     S1_SMOTE 0.645 (0.634-0.654) 0.432 (0.416-0.447)     0.210900 0.102658         0.0
          LightGBM S3_THRESHOLD 0.644 (0.634-0.654) 0.437 (0.421-0.453)     0.211500 0.112354         0.0
          CatBoost     S1_SMOTE 0.644 (0.634-0.654) 0.447 (0.431-0.463)     0.212100 0.116565         0.0
           XGBoost     S1_SMOTE 0.640 (0.630-0.650) 0.435 (0.419-0.451)     0.210404 0.104847         0.0
      RandomForest  S2_BALANCED 0.640 (0.630-0.650) 0.425 (0.409-0.440)     0.224900 0.157673         0.0
      RandomForest S3_THRESHOLD 0.639 (0.629-0.649) 0.425 (0.409-0.441)     0.207000 0.085040         0.0
          AdaBoost S3_THRESHOLD 0.626 (0.616-0.636) 0.403 (0.388-0.418)     0.218555 0.129400         0.0
LogisticRegression     S1_SMOTE 0.625 (0.615-0.635) 0.407 (0.392-0.421)     0.336600 0.359838         0.0
LogisticRegression S3_THRESHOLD 0.625 (0.615-0.634) 0.409 (0.394-0.424)     0.314800 0.329672         0.0
LogisticRegression  S2_BALANCED 0.625 (0.614-0.634) 0.407 (0.392-0.422)     0.391100 0.431942         0.0
               SGD     S1_SMOTE 0.621 (0.611-0.631) 0.408 (0.393-0.423)     0.314800 0.328227         0.0
      RandomForest     S1_SMOTE 0.618 (0.608-0.629) 0.418 (0.401-0.434)     0.214100 0.108173         0.0
               SGD  S2_BALANCED 0.613 (0.602-0.623) 0.401 (0.386-0.415)     0.352800 0.384975         0.0
          AdaBoost     S1_SMOTE 0.612 (0.601-0.623) 0.404 (0.388-0.419)     0.236775 0.180252         0.0
               SGD S3_THRESHOLD 0.612 (0.602-0.622) 0.399 (0.384-0.413)     0.268100 0.247332         0.0
         LinearSVM     S1_SMOTE 0.612 (0.601-0.622) 0.390 (0.375-0.404)     0.291500 0.295378         0.0
         LinearSVM  S2_BALANCED 0.609 (0.599-0.619) 0.388 (0.374-0.401)     0.315800 0.333446         0.0
          AdaBoost  S2_BALANCED 0.608 (0.597-0.618) 0.383 (0.369-0.395)     0.263231 0.183968         0.0
         LinearSVM S3_THRESHOLD 0.607 (0.597-0.617) 0.387 (0.373-0.400)     0.327600 0.349709         0.0
               MLP S3_THRESHOLD 0.602 (0.592-0.612) 0.388 (0.373-0.403)     0.339400 0.350057         0.0

# ***6B: MODEL TRAINING, HYPERPARAMETER TUNING & EVALUATION-3YEAR

# 6B - BLOCK 1/4: LOGISTIC REGRESSION, LINEAR SVM, SGD, RANDOM FOREST - local

In [ ]:
# ==============================================================================
# BLOCK 1/4 — LOGISTIC REGRESSION, LINEAR SVM, SGD, RANDOM FOREST
# 3-YEAR REJECTION ONLY
# Tunes + evaluates 4 models x 3 imbalance strategies.
# Fully self-contained.
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

# --- CHANGE 5: count ConvergenceWarnings instead of hiding them entirely ---
warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')                      # suppress noise generally...
warnings.simplefilter('always', ConvergenceWarning)     # ...but always trigger this one
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000            # CHANGE 3: was 1500
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
CALIBRATION_CV = 3            # CHANGE 2: was implicit default (5)
EARLY_STOP_PATIENCE = 15      # CHANGE 4: stop a study if no improvement in this many trials

STRATEGIES = {
    'S1_SMOTE': 'SMOTE',
    'S2_BALANCED': 'class_weight=balanced',
    'S3_THRESHOLD': 'threshold_optimised'
}

BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (unchanged — already merge-safe)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(
                new_df.set_index(['model', 'strategy']).index
            )
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (unchanged)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    Xtr_lin  = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
    Xte_lin  = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(Xtr_lin) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(Xte_lin) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0 and Xtr_lin.shape[1] > 0, "Empty feature matrix."

    print("\n" + "=" * 70); print("1-YEAR REJECTION DATA LOADED"); print("=" * 70)
    print(f"Data directory : {DATA_DIR}")
    print(f"\nTree train     : {Xtr_tree.shape}")
    print(f"Tree test      : {Xte_tree.shape}")
    print(f"Linear train   : {Xtr_lin.shape}")
    print(f"Linear test    : {Xte_lin.shape}")
    print(f"\nTrain: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")
    print(f"\nPositive train: {int(y_train.sum()):,}   Negative train: {int((y_train==0).sum()):,}")
    print(f"Positive test : {int(y_test.sum()):,}   Negative test : {int((y_test==0).sum()):,}")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        Xl_train=Xtr_lin.values.astype('float32'),  Xl_test=Xte_lin.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, Xl_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac,
                               stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], Xl_train[idx], yt_arr[idx]


data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
Xl_train, Xl_test = data['Xl_train'], data['Xl_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, Xl_tune, yt_tune = get_tuning_subsample(Xt_train, Xl_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (unchanged)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(
        O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')
    ).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1'])**2 / hl['E1']) + ((hl['O0'] - hl['E0'])**2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0:
            continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf)
        ece += (n_m / len(y_true)) * gap
        mce = max(mce, gap)
        bins.append({'bin_lo': round(lo,3), 'bin_hi': round(hi,3), 'n': n_m,
                     'conf': round(conf,4), 'acc': round(acc,4), 'gap': round(gap,4)})
    return round(ece, 6), round(mce, 6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val >= t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)

    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)

    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn) / (denom + eps) if denom > 0 else 0.0

    return {
        'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3),
        'n_test': len(y_true), 'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
        'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
        'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
        'brier_score': round(brier, 4),
        'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
        'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
        'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
        'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
        'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
        'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
        'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn),
    }


# ------------------------------------------------------------------------------
# MODEL REGISTRY
# ------------------------------------------------------------------------------
def _lr_space(t):
    penalty = t.suggest_categorical('penalty', ['l1', 'l2', 'elasticnet'])
    params = {'C': t.suggest_float('C', 1e-4, 1e2, log=True), 'penalty': penalty}
    if penalty == 'elasticnet':
        params['l1_ratio'] = t.suggest_float('l1_ratio', 0.0, 1.0)
    return params

REGISTRY = {
    'LogisticRegression': {
        'class': LogisticRegression, 'data': 'linear',
        'fixed': {'max_iter': 500, 'solver': 'saga', 'random_state': RANDOM_STATE},
        'space': _lr_space,
    },
    'LinearSVM': {
        'class': CalibratedClassifierCV, 'data': 'linear', 'fixed': {},
        'inner_class': LinearSVC,
        'inner_fixed': {'random_state': RANDOM_STATE, 'max_iter': 1000},
        'space': lambda t: {
            'estimator__C': t.suggest_float('C', 1e-3, 1e2, log=True),
            'estimator__loss': t.suggest_categorical('loss', ['hinge', 'squared_hinge']),
        },
    },
    'SGD': {
        'class': SGDClassifier, 'data': 'linear',
        'fixed': {'loss': 'log_loss', 'max_iter': 100, 'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'alpha': t.suggest_float('alpha', 1e-6, 1e-1, log=True),
            'penalty': t.suggest_categorical('penalty', ['l2', 'l1', 'elasticnet']),
            'l1_ratio': t.suggest_float('l1_ratio', 0.0, 1.0),
        },
    },
    'RandomForest': {
        'class': RandomForestClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'n_estimators': t.suggest_int('n_estimators', 200, 1000),
            'max_depth': t.suggest_int('max_depth', 4, 20),
            'min_samples_split': t.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': t.suggest_int('min_samples_leaf', 1, 10),
            'max_features': t.suggest_categorical('max_features', ['sqrt', 'log2', 0.3]),
        },
    },
}

TRIAL_BUDGET = {'LogisticRegression': 50, 'LinearSVM': 45, 'SGD': 45, 'RandomForest': 75}


def build_model(model_name, params, strategy):
    cfg = REGISTRY[model_name]
    inner_params = {k.replace('estimator__', ''): v for k, v in params.items() if 'estimator__' in k}
    plain_params = {k: v for k, v in params.items() if 'estimator__' not in k}
    all_params = {**cfg['fixed'], **plain_params}

    def make_linear_svm(class_weight=None, use_smote=False):
        inner_kw = {**cfg['inner_fixed'], **inner_params}
        if class_weight is not None:
            inner_kw['class_weight'] = class_weight
        svm = cfg['inner_class'](**inner_kw)
        if use_smote:
            # --- CHANGE 1 (THE FIX): SMOTE now lives INSIDE the pipeline that
            # CalibratedClassifierCV wraps, exactly mirroring the SMOTE pattern
            # already used correctly for LR/SGD/RF below. Previously this branch
            # was unreachable — S1 fell through to the same code as S2.
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            estimator = ImblearnPipeline([('smote', smote), ('svm', svm)])
        else:
            estimator = svm
        return CalibratedClassifierCV(estimator, cv=CALIBRATION_CV)  # CHANGE 2: explicit cv=3

    if strategy == 'S1_SMOTE':
        if model_name == 'LinearSVM':
            return make_linear_svm(use_smote=True)
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', cfg['class'](**all_params))])

    elif strategy == 'S2_BALANCED':
        if model_name == 'LinearSVM':
            return make_linear_svm(class_weight='balanced')
        if model_name in ('RandomForest', 'LogisticRegression', 'SGD'):
            all_params['class_weight'] = 'balanced'
        return cfg['class'](**all_params)

    else:  # S3_THRESHOLD
        if model_name == 'LinearSVM':
            return make_linear_svm()
        return cfg['class'](**all_params)


# ------------------------------------------------------------------------------
# EARLY-STOPPING CALLBACK (CHANGE 4)
# ------------------------------------------------------------------------------
def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# GENERIC TUNE + EVAL RUNNER
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]
        data_kind = registry[model_name]['data']

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0   # CHANGE 5: reset per combination
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy, data_kind=data_kind):
                params = registry[model_name]['space'](trial)
                X_sub = Xl_tune if data_kind == 'linear' else Xt_tune
                scores = []
                for tr_idx, val_idx in skf_tune.split(X_sub, yt_tune):
                    try:
                        m = build_model_fn(model_name, params, strategy)
                        m.fit(X_sub[tr_idx], yt_tune[tr_idx])
                        proba = m.predict_proba(X_sub[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(
                direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10)
            )
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])   # CHANGE 4

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, "
                  f"{elapsed:.0f}s, {n_conv} convergence warnings)")   # CHANGE 5/6

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        X_tr = Xl_train if registry[model_name]['data'] == 'linear' else Xt_train
        X_te = Xl_test if registry[model_name]['data'] == 'linear' else Xt_test

        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy)
                model.fit(X_tr, yt_arr)
                y_prob = model.predict_proba(X_te)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy),
                                              X_tr, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({
                    'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                    'y_prob': y_prob, 'y_pred': y_pred
                }).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")   # CHANGE 7

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


# ------------------------------------------------------------------------------
# RUN — 1-YEAR REJECTION ONLY
# ------------------------------------------------------------------------------
block1_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)

print("\nBlock 1 complete.")
print(block1_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

======================================================================
1-YEAR REJECTION DATA LOADED
======================================================================
Data directory : D:\Thesis\Thesis_parquet\model_ready\3yr

Tree train     : (28596, 269)
Tree test      : (7568, 269)
Linear train   : (28596, 623)
Linear test    : (7568, 623)

Train: 28,596 (44.0% rejection)
Test : 7,568 (39.3% rejection)

Positive train: 12,595   Negative train: 16,001
Positive test : 2,976   Negative test : 4,592

Tuning subsample: 14,298 patients (44.0% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning LogisticRegression/S1_SMOTE (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6539  (trial 45/50, 3779s, 93 convergence warnings)

Tuning LogisticRegression/S2_BALANCED (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6564  (trial 41/50, 3310s, 92 convergence warnings)

Tuning LogisticRegression/S3_THRESHOLD (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6563  (trial 31/47, 3227s, 93 convergence warnings)

Tuning LinearSVM/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6488  (trial 22/38, 427s, 70 convergence warnings)

Tuning LinearSVM/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6508  (trial 12/28, 246s, 51 convergence warnings)

Tuning LinearSVM/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6507  (trial 12/28, 245s, 49 convergence warnings)

Tuning SGD/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6474  (trial 9/25, 166s, 21 convergence warnings)

Tuning SGD/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6511  (trial 9/25, 130s, 19 convergence warnings)

Tuning SGD/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6500  (trial 9/25, 139s, 16 convergence warnings)

Tuning RandomForest/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6565  (trial 19/35, 573s, 0 convergence warnings)

Tuning RandomForest/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6578  (trial 60/75, 1118s, 0 convergence warnings)

Tuning RandomForest/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6596  (trial 51/67, 1085s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  LogisticRegression/S1_SMOTE... AUROC=0.6338  AUPRC=0.5183  F1=0.5768  Brier=0.2966  ECE=0.2618  (71s)

  LogisticRegression/S2_BALANCED... AUROC=0.6326  AUPRC=0.5191  F1=0.5753  Brier=0.2944  ECE=0.2574  (74s)

  LogisticRegression/S3_THRESHOLD... AUROC=0.6335  AUPRC=0.5210  F1=0.5682  Brier=0.2717  ECE=0.2089  (152s)

  LinearSVM/S1_SMOTE... AUROC=0.6102  AUPRC=0.4866  F1=0.5697  Brier=0.2678  ECE=0.1906  (63s)

  LinearSVM/S2_BALANCED... AUROC=0.6092  AUPRC=0.4868  F1=0.5696  Brier=0.2711  ECE=0.1985  (63s)

  LinearSVM/S3_THRESHOLD... AUROC=0.6088  AUPRC=0.4871  F1=0.5644  Brier=0.2744  ECE=0.2062  (131s)

  SGD/S1_SMOTE... AUROC=0.6330  AUPRC=0.5207  F1=0.5775  Brier=0.2871  ECE=0.2450  (9s)

  SGD/S2_BALANCED... AUROC=0.6207  AUPRC=0.5105  F1=0.5723  Brier=0.2913  ECE=0.2491  (7s)

  SGD/S3_THRESHOLD... AUROC=0.6208  AUPRC=0.5061  F1=0.5662  Brier=0.2574  ECE=0.1657  (10s)

  RandomForest/S1_SMOTE... AUROC=0.6356  AUPRC=0.5114  F1=0.5141  Brier=0.2346  ECE=0.0853  (31s)

  RandomForest/S2_BALANCED... AUROC=0.6456  AUPRC=0.5313  F1=0.5548  Brier=0.2375  ECE=0.1115  (31s)

  RandomForest/S3_THRESHOLD... AUROC=0.6468  AUPRC=0.5310  F1=0.5763  Brier=0.2308  ECE=0.0757  (130s)

Block 1 complete.
             model     strategy  auroc  auprc  f1_score
LogisticRegression     S1_SMOTE 0.6338 0.5183    0.5768
LogisticRegression  S2_BALANCED 0.6326 0.5191    0.5753
LogisticRegression S3_THRESHOLD 0.6335 0.5210    0.5682
         LinearSVM     S1_SMOTE 0.6102 0.4866    0.5697
         LinearSVM  S2_BALANCED 0.6092 0.4868    0.5696
         LinearSVM S3_THRESHOLD 0.6088 0.4871    0.5644
               SGD     S1_SMOTE 0.6330 0.5207    0.5775
               SGD  S2_BALANCED 0.6207 0.5105    0.5723
               SGD S3_THRESHOLD 0.6208 0.5061    0.5662
      RandomForest     S1_SMOTE 0.6356 0.5114    0.5141
      RandomForest  S2_BALANCED 0.6456 0.5313    0.5548
      RandomForest S3_THRESHOLD 0.6468 0.5310    0.5763

In [ ]:
# recovery

# ==============================================================================
# RANDOM FOREST S3_THRESHOLD — MODEL FILE RECOVERY ONLY
# Does NOT rerun Optuna.
# Does NOT rerun the complete Block 1.
# Reuses the already saved best hyperparameters.
# ==============================================================================

from pathlib import Path
import pickle
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# ----------------------------------------------------------------------
# PATHS
# ----------------------------------------------------------------------

BASE = Path(r"D:\Thesis\Thesis_parquet")

DATA_DIR = BASE / "model_ready" / "3yr"
MDL_DIR  = BASE / "models" / "3yr"

MODEL_PATH = MDL_DIR / "model_RandomForest_S3_THRESHOLD.pkl"
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"

# ----------------------------------------------------------------------
# CHECK AVAILABLE SPACE
# ----------------------------------------------------------------------

import shutil

free_gb = shutil.disk_usage("D:\\").free / (1024 ** 3)

print(f"Free space on D: {free_gb:.2f} GB")

if free_gb < 1:
    raise RuntimeError(
        "Less than 1 GB is free on D:. "
        "Free some disk space before fitting/saving the model."
    )

# ----------------------------------------------------------------------
# LOAD TREE DATA
# ----------------------------------------------------------------------

X_train = pd.read_parquet(
    DATA_DIR / "X_train_tree.parquet",
    engine="pyarrow"
)

y_train = pd.read_parquet(
    DATA_DIR / "y_train.parquet",
    engine="pyarrow"
).squeeze().astype(int)

print("Training data:", X_train.shape)
print("Training labels:", y_train.shape)

# ----------------------------------------------------------------------
# LOAD ALREADY-TUNED RF S3 PARAMETERS
# ----------------------------------------------------------------------

if not BEST_PARAMS_PATH.exists():
    raise FileNotFoundError(
        f"Missing:\n{BEST_PARAMS_PATH}"
    )

with open(BEST_PARAMS_PATH, "rb") as f:
    best_params = pickle.load(f)

rf_params = best_params[("RandomForest", "S3_THRESHOLD")]

print("\nLoaded Optuna-selected parameters:")
print(rf_params)

# ----------------------------------------------------------------------
# BUILD FINAL RANDOM FOREST
# S3 = no SMOTE / no class_weight; threshold is optimized separately.
# ----------------------------------------------------------------------

model = RandomForestClassifier(
    **rf_params,
    random_state=42,
    n_jobs=-1
)

print("\nFitting RandomForest/S3_THRESHOLD on full training set...")

# float32 is sufficient and reduces memory pressure
X_train_np = X_train.values.astype("float32")
y_train_np = y_train.values

model.fit(
    X_train_np,
    y_train_np
)

print("Model fitting completed.")

# ----------------------------------------------------------------------
# SAVE MODEL
# ----------------------------------------------------------------------

print(f"\nSaving model to:\n{MODEL_PATH}")

with open(MODEL_PATH, "wb") as f:
    pickle.dump(model, f, protocol=pickle.HIGHEST_PROTOCOL)

print("\nSUCCESS")
print(f"Saved: {MODEL_PATH}")
print(f"Size : {MODEL_PATH.stat().st_size / (1024**2):.2f} MB")

In [ ]:
# ==============================================================================
# BLOCK 1/4 — LOGISTIC REGRESSION, LINEAR SVM, SGD, RANDOM FOREST
# 3-YEAR REJECTION ONLY
# Tunes + evaluates 4 models x 3 imbalance strategies.
# Fully self-contained.
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

# --- CHANGE 5: count ConvergenceWarnings instead of hiding them entirely ---
warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')                      # suppress noise generally...
warnings.simplefilter('always', ConvergenceWarning)     # ...but always trigger this one
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000            # CHANGE 3: was 1500
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
CALIBRATION_CV = 3            # CHANGE 2: was implicit default (5)
EARLY_STOP_PATIENCE = 15      # CHANGE 4: stop a study if no improvement in this many trials

STRATEGIES = {
    'S1_SMOTE': 'SMOTE',
    'S2_BALANCED': 'class_weight=balanced',
    'S3_THRESHOLD': 'threshold_optimised'
}

BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (unchanged — already merge-safe)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(
                new_df.set_index(['model', 'strategy']).index
            )
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (unchanged)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    Xtr_lin  = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
    Xte_lin  = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(Xtr_lin) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(Xte_lin) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0 and Xtr_lin.shape[1] > 0, "Empty feature matrix."

    print("\n" + "=" * 70); print("3-YEAR REJECTION DATA LOADED"); print("=" * 70)
    print(f"Data directory : {DATA_DIR}")
    print(f"\nTree train     : {Xtr_tree.shape}")
    print(f"Tree test      : {Xte_tree.shape}")
    print(f"Linear train   : {Xtr_lin.shape}")
    print(f"Linear test    : {Xte_lin.shape}")
    print(f"\nTrain: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")
    print(f"\nPositive train: {int(y_train.sum()):,}   Negative train: {int((y_train==0).sum()):,}")
    print(f"Positive test : {int(y_test.sum()):,}   Negative test : {int((y_test==0).sum()):,}")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        Xl_train=Xtr_lin.values.astype('float32'),  Xl_test=Xte_lin.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, Xl_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac,
                               stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], Xl_train[idx], yt_arr[idx]


data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
Xl_train, Xl_test = data['Xl_train'], data['Xl_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, Xl_tune, yt_tune = get_tuning_subsample(Xt_train, Xl_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (unchanged)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(
        O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')
    ).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1'])**2 / hl['E1']) + ((hl['O0'] - hl['E0'])**2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0:
            continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf)
        ece += (n_m / len(y_true)) * gap
        mce = max(mce, gap)
        bins.append({'bin_lo': round(lo,3), 'bin_hi': round(hi,3), 'n': n_m,
                     'conf': round(conf,4), 'acc': round(acc,4), 'gap': round(gap,4)})
    return round(ece, 6), round(mce, 6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val >= t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)

    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob,
        lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)

    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn) / (denom + eps) if denom > 0 else 0.0

    return {
        'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3),
        'n_test': len(y_true), 'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
        'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
        'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
        'brier_score': round(brier, 4),
        'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
        'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
        'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
        'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
        'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
        'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
        'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn),
    }


# ------------------------------------------------------------------------------
# MODEL REGISTRY
# ------------------------------------------------------------------------------
def _lr_space(t):
    penalty = t.suggest_categorical('penalty', ['l1', 'l2', 'elasticnet'])
    params = {'C': t.suggest_float('C', 1e-4, 1e2, log=True), 'penalty': penalty}
    if penalty == 'elasticnet':
        params['l1_ratio'] = t.suggest_float('l1_ratio', 0.0, 1.0)
    return params

REGISTRY = {
    'LogisticRegression': {
        'class': LogisticRegression, 'data': 'linear',
        'fixed': {'max_iter': 500, 'solver': 'saga', 'random_state': RANDOM_STATE},
        'space': _lr_space,
    },
    'LinearSVM': {
        'class': CalibratedClassifierCV, 'data': 'linear', 'fixed': {},
        'inner_class': LinearSVC,
        'inner_fixed': {'random_state': RANDOM_STATE, 'max_iter': 1000},
        'space': lambda t: {
            'estimator__C': t.suggest_float('C', 1e-3, 1e2, log=True),
            'estimator__loss': t.suggest_categorical('loss', ['hinge', 'squared_hinge']),
        },
    },
    'SGD': {
        'class': SGDClassifier, 'data': 'linear',
        'fixed': {'loss': 'log_loss', 'max_iter': 100, 'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'alpha': t.suggest_float('alpha', 1e-6, 1e-1, log=True),
            'penalty': t.suggest_categorical('penalty', ['l2', 'l1', 'elasticnet']),
            'l1_ratio': t.suggest_float('l1_ratio', 0.0, 1.0),
        },
    },
    'RandomForest': {
        'class': RandomForestClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'n_jobs': -1},
        'space': lambda t: {
            'n_estimators': t.suggest_int('n_estimators', 200, 1000),
            'max_depth': t.suggest_int('max_depth', 4, 20),
            'min_samples_split': t.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': t.suggest_int('min_samples_leaf', 1, 10),
            'max_features': t.suggest_categorical('max_features', ['sqrt', 'log2', 0.3]),
        },
    },
}

TRIAL_BUDGET = {'LogisticRegression': 50, 'LinearSVM': 45, 'SGD': 45, 'RandomForest': 75}


def build_model(model_name, params, strategy):
    cfg = REGISTRY[model_name]
    inner_params = {k.replace('estimator__', ''): v for k, v in params.items() if 'estimator__' in k}
    plain_params = {k: v for k, v in params.items() if 'estimator__' not in k}
    all_params = {**cfg['fixed'], **plain_params}

    def make_linear_svm(class_weight=None, use_smote=False):
        inner_kw = {**cfg['inner_fixed'], **inner_params}
        if class_weight is not None:
            inner_kw['class_weight'] = class_weight
        svm = cfg['inner_class'](**inner_kw)
        if use_smote:
            # --- CHANGE 1 (THE FIX): SMOTE now lives INSIDE the pipeline that
            # CalibratedClassifierCV wraps, exactly mirroring the SMOTE pattern
            # already used correctly for LR/SGD/RF below. Previously this branch
            # was unreachable — S1 fell through to the same code as S2.
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            estimator = ImblearnPipeline([('smote', smote), ('svm', svm)])
        else:
            estimator = svm
        return CalibratedClassifierCV(estimator, cv=CALIBRATION_CV)  # CHANGE 2: explicit cv=3

    if strategy == 'S1_SMOTE':
        if model_name == 'LinearSVM':
            return make_linear_svm(use_smote=True)
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', cfg['class'](**all_params))])

    elif strategy == 'S2_BALANCED':
        if model_name == 'LinearSVM':
            return make_linear_svm(class_weight='balanced')
        if model_name in ('RandomForest', 'LogisticRegression', 'SGD'):
            all_params['class_weight'] = 'balanced'
        return cfg['class'](**all_params)

    else:  # S3_THRESHOLD
        if model_name == 'LinearSVM':
            return make_linear_svm()
        return cfg['class'](**all_params)


# ------------------------------------------------------------------------------
# EARLY-STOPPING CALLBACK (CHANGE 4)
# ------------------------------------------------------------------------------
def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# GENERIC TUNE + EVAL RUNNER
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]
        data_kind = registry[model_name]['data']

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0   # CHANGE 5: reset per combination
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy, data_kind=data_kind):
                params = registry[model_name]['space'](trial)
                X_sub = Xl_tune if data_kind == 'linear' else Xt_tune
                scores = []
                for tr_idx, val_idx in skf_tune.split(X_sub, yt_tune):
                    try:
                        m = build_model_fn(model_name, params, strategy)
                        m.fit(X_sub[tr_idx], yt_tune[tr_idx])
                        proba = m.predict_proba(X_sub[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(
                direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10)
            )
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])   # CHANGE 4

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, "
                  f"{elapsed:.0f}s, {n_conv} convergence warnings)")   # CHANGE 5/6

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        X_tr = Xl_train if registry[model_name]['data'] == 'linear' else Xt_train
        X_te = Xl_test if registry[model_name]['data'] == 'linear' else Xt_test

        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy)
                model.fit(X_tr, yt_arr)
                y_prob = model.predict_proba(X_te)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy),
                                              X_tr, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({
                    'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                    'y_prob': y_prob, 'y_pred': y_pred
                }).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")   # CHANGE 7

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


# ------------------------------------------------------------------------------
# RUN — 3-YEAR REJECTION ONLY
# ------------------------------------------------------------------------------
block1_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)

print("\nBlock 1 complete.")
print(block1_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

======================================================================
3-YEAR REJECTION DATA LOADED
======================================================================
Data directory : D:\Thesis\Thesis_parquet\model_ready\3yr

Tree train     : (28596, 284)
Tree test      : (7568, 284)
Linear train   : (28596, 673)
Linear test    : (7568, 673)

Train: 28,596 (44.0% rejection)
Test : 7,568 (39.3% rejection)

Positive train: 12,595   Negative train: 16,001
Positive test : 2,976   Negative test : 4,592

Tuning subsample: 14,298 patients (44.0% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning LogisticRegression/S1_SMOTE (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6608  (trial 36/50, 3066s, 110 convergence warnings)

Tuning LogisticRegression/S2_BALANCED (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6631  (trial 34/50, 2709s, 108 convergence warnings)

Tuning LogisticRegression/S3_THRESHOLD (50 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6630  (trial 34/50, 2709s, 110 convergence warnings)

Tuning LinearSVM/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6563  (trial 11/27, 434s, 52 convergence warnings)

Tuning LinearSVM/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6578  (trial 7/23, 276s, 49 convergence warnings)

Tuning LinearSVM/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6578  (trial 7/23, 323s, 48 convergence warnings)

Tuning SGD/S1_SMOTE (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6554  (trial 9/25, 173s, 21 convergence warnings)

Tuning SGD/S2_BALANCED (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6564  (trial 42/45, 190s, 24 convergence warnings)

Tuning SGD/S3_THRESHOLD (45 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6574  (trial 23/39, 176s, 25 convergence warnings)

Tuning RandomForest/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6720  (trial 28/44, 1479s, 0 convergence warnings)

Tuning RandomForest/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6751  (trial 23/39, 905s, 0 convergence warnings)

Tuning RandomForest/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6753  (trial 20/36, 845s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  LogisticRegression/S1_SMOTE... AUROC=0.6422  AUPRC=0.5309  F1=0.5791  Brier=0.2992  ECE=0.2700  (84s)

  LogisticRegression/S2_BALANCED... AUROC=0.6403  AUPRC=0.5309  F1=0.5794  Brier=0.2900  ECE=0.2518  (77s)

  LogisticRegression/S3_THRESHOLD... AUROC=0.6407  AUPRC=0.5317  F1=0.5687  Brier=0.2673  ECE=0.2017  (138s)

  LinearSVM/S1_SMOTE... AUROC=0.6167  AUPRC=0.4943  F1=0.5713  Brier=0.2724  ECE=0.2045  (45s)

  LinearSVM/S2_BALANCED... AUROC=0.6169  AUPRC=0.4951  F1=0.5703  Brier=0.2715  ECE=0.2023  (66s)

  LinearSVM/S3_THRESHOLD... AUROC=0.6170  AUPRC=0.4965  F1=0.5645  Brier=0.2751  ECE=0.2105  (130s)

  SGD/S1_SMOTE... AUROC=0.6397  AUPRC=0.5330  F1=0.5785  Brier=0.2901  ECE=0.2532  (8s)

  SGD/S2_BALANCED... AUROC=0.6319  AUPRC=0.5187  F1=0.5737  Brier=0.2687  ECE=0.2015  (5s)

  SGD/S3_THRESHOLD... AUROC=0.6336  AUPRC=0.5233  F1=0.5733  Brier=0.2379  ECE=0.1058  (6s)

  RandomForest/S1_SMOTE... AUROC=0.6598  AUPRC=0.5500  F1=0.5400  Brier=0.2306  ECE=0.0895  (59s)

  RandomForest/S2_BALANCED... FAILED — [Errno 28] No space left on device

  RandomForest/S3_THRESHOLD... FAILED — [Errno 28] No space left on device

Block 1 complete.
             model     strategy  auroc  auprc  f1_score
LogisticRegression     S1_SMOTE 0.6422 0.5309    0.5791
LogisticRegression  S2_BALANCED 0.6403 0.5309    0.5794
LogisticRegression S3_THRESHOLD 0.6407 0.5317    0.5687
         LinearSVM     S1_SMOTE 0.6167 0.4943    0.5713
         LinearSVM  S2_BALANCED 0.6169 0.4951    0.5703
         LinearSVM S3_THRESHOLD 0.6170 0.4965    0.5645
               SGD     S1_SMOTE 0.6397 0.5330    0.5785
               SGD  S2_BALANCED 0.6319 0.5187    0.5737
               SGD S3_THRESHOLD 0.6336 0.5233    0.5733
      RandomForest     S1_SMOTE 0.6598 0.5500    0.5400
      RandomForest  S2_BALANCED 0.6710 0.5591    0.5766
      RandomForest S3_THRESHOLD 0.6710 0.5625    0.5796

In [ ]:
xgboost.__version__

'3.4.1'

In [ ]:
sklearn.__version__

'1.9.1'

# 6B - BLOCK 2/4: ADABOOST, XGBOOST - local

In [ ]:
# ==============================================================================
# BLOCK 2/4 — ADABOOST, XGBOOST
# 3-YEAR REJECTION ONLY
# Fully self-contained — mirrors Block 1's architecture and diagnostics exactly.
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import xgboost as xgb

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')
warnings.simplefilter('always', ConvergenceWarning)
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG — identical constants to Block 1, so results stay comparable
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
EARLY_STOP_PATIENCE = 15

STRATEGIES = {'S1_SMOTE': 'SMOTE', 'S2_BALANCED': 'class_weight=balanced', 'S3_THRESHOLD': 'threshold_optimised'}
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"      # SAME file as Block 1 — merges in, doesn't overwrite
METRICS_PATH = OUT_DIR / "all_metrics.csv"           # SAME file as Block 1

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# GPU DETECTION FOR XGBOOST — tries modern API, then legacy API, then CPU.
# AdaBoost has no GPU path at all (sklearn CPU-only) — nothing to detect there.
# ------------------------------------------------------------------------------
def detect_xgb_gpu():
    dummy_X = np.random.rand(50, 5).astype('float32')
    dummy_y = np.random.randint(0, 2, 50)

    try:
        m = xgb.XGBClassifier(tree_method='hist', device='cuda', n_estimators=2, verbosity=0)
        m.fit(dummy_X, dummy_y)
        return {'tree_method': 'hist', 'device': 'cuda'}, 'GPU — modern API (device=cuda)'
    except Exception as e1:
        modern_error = str(e1)

    try:
        m = xgb.XGBClassifier(tree_method='gpu_hist', n_estimators=2, verbosity=0)
        m.fit(dummy_X, dummy_y)
        return {'tree_method': 'gpu_hist'}, 'GPU — legacy API (tree_method=gpu_hist)'
    except Exception as e2:
        legacy_error = str(e2)

    print(f"  GPU detection failed on both APIs:")
    print(f"    modern (device=cuda) error : {modern_error[:150]}")
    print(f"    legacy (gpu_hist) error    : {legacy_error[:150]}")
    return {'tree_method': 'hist'}, 'CPU fallback — no working GPU path found'

XGB_DEVICE_PARAMS, XGB_DEVICE_LABEL = detect_xgb_gpu()
print(f"XGBoost device : {XGB_DEVICE_LABEL}")
print(f"AdaBoost device: CPU only (sklearn has no GPU implementation)")


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (identical to Block 1)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(new_df.set_index(['model', 'strategy']).index)
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (identical to Block 1 — both models here use the TREE feature matrix only)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0, "Empty tree feature matrix."

    print("\n" + "=" * 70); print("3-YEAR REJECTION DATA LOADED (Block 2 — tree models only)"); print("=" * 70)
    print(f"Tree train : {Xtr_tree.shape}   Tree test : {Xte_tree.shape}")
    print(f"Train: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac, stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], yt_arr[idx]

data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, yt_tune = get_tuning_subsample(Xt_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (byte-identical to Block 1 — do not let these drift between blocks)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y','sum'), n=('y','count'), E1=('p','mean')).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1']-hl['E1'])**2/hl['E1']) + ((hl['O0']-hl['E0'])**2/hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl)-2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1-1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins+1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i+1]
        mask = (y_prob>=lo)&(y_prob<hi) if i<n_bins-1 else (y_prob>=lo)&(y_prob<=hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc-conf)
        ece += (n_m/len(y_true))*gap
        mce = max(mce, gap)
        bins.append({'bin_lo':round(lo,3),'bin_hi':round(hi,3),'n':n_m,'conf':round(conf,4),'acc':round(acc,4),'gap':round(gap,4)})
    return round(ece,6), round(mce,6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val>=t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: roc_auc_score(yt,yp) if len(np.unique(yt))>1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: average_precision_score(yt,yp) if yt.sum()>0 else np.nan)
    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape==(2,2) else (0,0,0,0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn)/(denom+eps) if denom>0 else 0.0
    return {'model':model_name,'strategy':strategy,'threshold':round(threshold,3),'n_test':len(y_true),
            'n_pos':int(y_true.sum()),'prevalence':round(float(y_true.mean()),4),
            'auroc':round(auroc,4),'auroc_ci_lo':round(auroc_lo,4),'auroc_ci_hi':round(auroc_hi,4),
            'auprc':round(auprc,4),'auprc_ci_lo':round(auprc_lo,4),'auprc_ci_hi':round(auprc_hi,4),
            'brier_score':round(brier,4),
            'ece':round(float(ece),6) if np.isfinite(ece) else np.nan,
            'mce':round(float(mce),6) if np.isfinite(mce) else np.nan,
            'hl_chi2':round(hl_chi2,3),'hl_p_value':round(hl_p,4),
            'sensitivity':round(float(sens),4),'specificity':round(float(spec),4),
            'ppv':round(float(ppv),4),'npv':round(float(npv),4),
            'f1_score':round(float(f1),4),'mcc':round(float(mcc),4),
            'tp':int(tp),'fp':int(fp),'fn':int(fn),'tn':int(tn)}


# ------------------------------------------------------------------------------
# MODEL REGISTRY — AdaBoost, XGBoost only
# ------------------------------------------------------------------------------
def _adaboost_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 50, 500),
        'learning_rate': t.suggest_float('learning_rate', 0.01, 2.0, log=True),
        'base_max_depth': t.suggest_int('base_max_depth', 1, 5),
        # NOTE: 'algorithm' deliberately excluded — removed from sklearn's API
        # (deprecated 1.4, restricted 1.6, removed 1.8). Modern AdaBoost only
        # implements SAMME; omitting the parameter is the version-safe choice.
    }

def _xgb_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 100, 1000),
        'max_depth': t.suggest_int('max_depth', 2, 10),
        'learning_rate': t.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'subsample': t.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': t.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': t.suggest_int('min_child_weight', 1, 10),
        'gamma': t.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': t.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': t.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }

REGISTRY = {
    'AdaBoost': {
        'class': AdaBoostClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE},
        'space': _adaboost_space,
    },
    'XGBoost': {
        'class': xgb.XGBClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'objective': 'binary:logistic',
                  'eval_metric': 'logloss', 'verbosity': 0, 'n_jobs': -1,
                  **XGB_DEVICE_PARAMS},
        'space': _xgb_space,
    },
}
TRIAL_BUDGET = {'AdaBoost': 55, 'XGBoost': 75}


def build_model(model_name, params, strategy, y_ref=None):
    """y_ref: the y-array this model will actually be fit on. Only used by
    XGBoost/S2_BALANCED to compute scale_pos_weight from the REAL class ratio
    of whatever data is being fit right now (fold subset, tuning subsample,
    or full training set) — mirrors what sklearn's class_weight='balanced'
    does automatically, since XGBoost has no built-in equivalent."""
    cfg = REGISTRY[model_name]
    all_params = {**cfg['fixed'], **params}

    if model_name == 'AdaBoost':
        base_depth = all_params.pop('base_max_depth')
        base_class_weight = 'balanced' if strategy == 'S2_BALANCED' else None
        base = DecisionTreeClassifier(max_depth=base_depth, class_weight=base_class_weight,
                                       random_state=RANDOM_STATE)
        ada = AdaBoostClassifier(estimator=base, **all_params)  # 'estimator', NOT 'base_estimator'
        if strategy == 'S1_SMOTE':
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            return ImblearnPipeline([('smote', smote), ('model', ada)])
        return ada

    else:  # XGBoost
        if strategy == 'S2_BALANCED':
            assert y_ref is not None, "XGBoost/S2_BALANCED requires y_ref to compute scale_pos_weight."
            n_pos = int(np.sum(y_ref == 1))
            n_neg = int(np.sum(y_ref == 0))
            all_params['scale_pos_weight'] = n_neg / max(n_pos, 1)
        model = cfg['class'](**all_params)
        if strategy == 'S1_SMOTE':
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            return ImblearnPipeline([('smote', smote), ('model', model)])
        return model


def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# RUNNER — same shape as Block 1, extended to pass y_ref through for XGBoost
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy):
                params = registry[model_name]['space'](trial)
                scores = []
                for tr_idx, val_idx in skf_tune.split(Xt_tune, yt_tune):
                    try:
                        y_fold = yt_tune[tr_idx]
                        m = build_model_fn(model_name, params, strategy, y_ref=y_fold)
                        m.fit(Xt_tune[tr_idx], y_fold)
                        proba = m.predict_proba(Xt_tune[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, {elapsed:.0f}s, "
                  f"{n_conv} convergence warnings)")

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy, y_ref=yt_arr)
                model.fit(Xt_train, yt_arr)
                y_prob = model.predict_proba(Xt_test)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy, y_ref=yt_arr),
                                              Xt_train, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                              'y_prob': y_prob, 'y_pred': y_pred}
                ).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


block2_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)
print("\nBlock 2 complete.")
print(block2_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

XGBoost device : GPU — modern API (device=cuda)
AdaBoost device: CPU only (sklearn has no GPU implementation)

======================================================================
3-YEAR REJECTION DATA LOADED (Block 2 — tree models only)
======================================================================
Tree train : (28596, 269)   Tree test : (7568, 269)
Train: 28,596 (44.0% rejection)
Test : 7,568 (39.3% rejection)

Tuning subsample: 14,298 patients (44.0% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning AdaBoost/S1_SMOTE (55 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6532  (trial 18/34, 5213s, 0 convergence warnings)

Tuning AdaBoost/S2_BALANCED (55 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6493  (trial 16/32, 1012s, 0 convergence warnings)

Tuning AdaBoost/S3_THRESHOLD (55 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6535  (trial 17/33, 3985s, 0 convergence warnings)

Tuning XGBoost/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6709  (trial 55/71, 692s, 0 convergence warnings)

Tuning XGBoost/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6732  (trial 62/75, 695s, 0 convergence warnings)

Tuning XGBoost/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6741  (trial 43/59, 482s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  AdaBoost/S1_SMOTE... AUROC=0.6182  AUPRC=0.5043  F1=0.5128  Brier=0.2393  ECE=0.0965  (207s)

  AdaBoost/S2_BALANCED... AUROC=0.6156  AUPRC=0.5044  F1=0.5542  Brier=0.2570  ECE=0.1514  (19s)

  AdaBoost/S3_THRESHOLD... AUROC=0.6327  AUPRC=0.5269  F1=0.5742  Brier=0.2337  ECE=0.0845  (292s)

  XGBoost/S1_SMOTE... AUROC=0.6540  AUPRC=0.5521  F1=0.5358  Brier=0.2296  ECE=0.0864  (11s)

  XGBoost/S2_BALANCED... AUROC=0.6639  AUPRC=0.5643  F1=0.5766  Brier=0.2349  ECE=0.1210  (10s)

  XGBoost/S3_THRESHOLD... AUROC=0.6629  AUPRC=0.5647  F1=0.5820  Brier=0.2260  ECE=0.0777  (40s)

Block 2 complete.
   model     strategy  auroc  auprc  f1_score
AdaBoost     S1_SMOTE 0.6182 0.5043    0.5128
AdaBoost  S2_BALANCED 0.6156 0.5044    0.5542
AdaBoost S3_THRESHOLD 0.6327 0.5269    0.5742
 XGBoost     S1_SMOTE 0.6540 0.5521    0.5358
 XGBoost  S2_BALANCED 0.6639 0.5643    0.5766
 XGBoost S3_THRESHOLD 0.6629 0.5647    0.5820

# 6B - BLOCK 3/4: LIGHTGBM - local

In [ ]:
# ==============================================================================
# BLOCK 3/4 — LIGHTGBM
# 3-YEAR REJECTION ONLY
# Mirrors Block 2's architecture exactly. Fixes the "GPU Tree Learner was not
# enabled in this build" crash by runtime-testing GPU support (both the modern
# CUDA path and the legacy OpenCL path) instead of trusting nvidia-smi alone,
# identical in spirit to Block 2's detect_xgb_gpu().
# ==============================================================================

from pathlib import Path
import pickle, time, warnings
from collections import defaultdict
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_predict
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                             f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

import lightgbm as lgb

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

warning_counts = defaultdict(int)
warnings.filterwarnings('ignore')
warnings.simplefilter('always', ConvergenceWarning)
def _warning_handler(message, category, filename, lineno, file=None, line=None):
    warning_counts[category.__name__] += 1
warnings.showwarning = _warning_handler


# ------------------------------------------------------------------------------
# CONFIG — identical constants to Blocks 1-2, so results stay comparable
# ------------------------------------------------------------------------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
EARLY_STOP_PATIENCE = 15

STRATEGIES = {'S1_SMOTE': 'SMOTE', 'S2_BALANCED': 'class_weight=balanced', 'S3_THRESHOLD': 'threshold_optimised'}
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"   # SAME file as Blocks 1-2 — merges, doesn't overwrite
METRICS_PATH = OUT_DIR / "all_metrics.csv"        # SAME file as Blocks 1-2

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)


# ------------------------------------------------------------------------------
# GPU DETECTION FOR LIGHTGBM — this is the fix. LightGBM raises "GPU Tree
# Learner was not enabled in this build" only at FIT time, not at import or
# instantiation time, and nvidia-smi reporting a GPU says nothing about
# whether THIS specific lightgbm wheel was compiled with GPU support. So we
# fit a 2-estimator dummy model on each candidate device and catch the
# failure, exactly mirroring Block 2's XGBoost pattern.
# ------------------------------------------------------------------------------
def detect_lgb_gpu():
    dummy_X = np.random.rand(50, 5).astype('float32')
    dummy_y = np.random.randint(0, 2, 50)

    try:
        m = lgb.LGBMClassifier(device_type='cuda', n_estimators=2, verbosity=-1)
        m.fit(dummy_X, dummy_y)
        return {'device_type': 'cuda'}, 'GPU — modern API (device_type=cuda)'
    except Exception as e1:
        modern_error = str(e1)

    try:
        m = lgb.LGBMClassifier(device='gpu', n_estimators=2, verbosity=-1)
        m.fit(dummy_X, dummy_y)
        return {'device': 'gpu'}, 'GPU — legacy OpenCL API (device=gpu)'
    except Exception as e2:
        legacy_error = str(e2)

    print(f"  GPU detection failed on both APIs:")
    print(f"    modern (device_type=cuda) error : {modern_error[:150]}")
    print(f"    legacy (device=gpu) error       : {legacy_error[:150]}")
    return {'device': 'cpu'}, 'CPU fallback — this is exactly the crash Block 3 exists to avoid'

LGB_DEVICE_PARAMS, LGB_DEVICE_LABEL = detect_lgb_gpu()
print(f"LightGBM device : {LGB_DEVICE_LABEL}")


# ------------------------------------------------------------------------------
# PERSISTENCE HELPERS (byte-identical to Blocks 1-2)
# ------------------------------------------------------------------------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params()
    params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows:
        return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[
            ~existing.set_index(['model', 'strategy']).index.isin(new_df.set_index(['model', 'strategy']).index)
        ]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)


# ------------------------------------------------------------------------------
# DATA (identical to Block 2 — tree feature matrix only)
# ------------------------------------------------------------------------------
def load_data():
    Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
    Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
    y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
    y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

    assert len(Xtr_tree) == len(y_train), "TRAIN row count mismatch."
    assert len(Xte_tree) == len(y_test), "TEST row count mismatch."
    assert Xtr_tree.shape[1] > 0, "Empty tree feature matrix."

    print("\n" + "=" * 70); print("3-YEAR REJECTION DATA LOADED (Block 3 — LightGBM)"); print("=" * 70)
    print(f"Tree train : {Xtr_tree.shape}   Tree test : {Xte_tree.shape}")
    print(f"Train: {len(y_train):,} ({y_train.mean()*100:.1f}% rejection)")
    print(f"Test : {len(y_test):,} ({y_test.mean()*100:.1f}% rejection)")

    return dict(
        Xt_train=Xtr_tree.values.astype('float32'), Xt_test=Xte_tree.values.astype('float32'),
        yt_arr=y_train.values, ytest_arr=y_test.values,
        y_train=y_train, y_test=y_test,
    )

def get_tuning_subsample(Xt_train, yt_arr, frac=0.5):
    idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=frac, stratify=yt_arr, random_state=RANDOM_STATE)
    return Xt_train[idx], yt_arr[idx]

data = load_data()
Xt_train, Xt_test = data['Xt_train'], data['Xt_test']
yt_arr, ytest_arr = data['yt_arr'], data['ytest_arr']
Xt_tune, yt_tune = get_tuning_subsample(Xt_train, yt_arr)
print(f"\nTuning subsample: {len(yt_tune):,} patients ({yt_tune.mean()*100:.1f}% rejection)")


# ------------------------------------------------------------------------------
# METRIC HELPERS (byte-identical to Blocks 1-2 — do not let these drift)
# ------------------------------------------------------------------------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed)
    vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v):
                vals.append(v)
        except Exception:
            continue
    if not vals:
        return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y','sum'), n=('y','count'), E1=('p','mean')).reset_index()
    hl['E1'] *= hl['n']
    hl['O0'] = hl['n'] - hl['O1']
    hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1']-hl['E1'])**2/hl['E1']) + ((hl['O0']-hl['E0'])**2/hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl)-2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1-1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2:
        return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins+1)
    ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i+1]
        mask = (y_prob>=lo)&(y_prob<hi) if i<n_bins-1 else (y_prob>=lo)&(y_prob<=hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc-conf)
        ece += (n_m/len(y_true))*gap
        mce = max(mce, gap)
        bins.append({'bin_lo':round(lo,3),'bin_hi':round(hi,3),'n':n_m,'conf':round(conf,4),'acc':round(acc,4),'gap':round(gap,4)})
    return round(ece,6), round(mce,6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val>=t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob)
    auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: roc_auc_score(yt,yp) if len(np.unique(yt))>1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt,yp: average_precision_score(yt,yp) if yt.sum()>0 else np.nan)
    brier = brier_score_loss(y_true, y_prob)
    ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel() if cm.shape==(2,2) else (0,0,0,0)
    eps = 1e-12
    sens, spec = tp/(tp+fn+eps), tn/(tn+fp+eps)
    ppv, npv = tp/(tp+fp+eps), tn/(tn+fn+eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
    mcc = (tp*tn - fp*fn)/(denom+eps) if denom>0 else 0.0
    return {'model':model_name,'strategy':strategy,'threshold':round(threshold,3),'n_test':len(y_true),
            'n_pos':int(y_true.sum()),'prevalence':round(float(y_true.mean()),4),
            'auroc':round(auroc,4),'auroc_ci_lo':round(auroc_lo,4),'auroc_ci_hi':round(auroc_hi,4),
            'auprc':round(auprc,4),'auprc_ci_lo':round(auprc_lo,4),'auprc_ci_hi':round(auprc_hi,4),
            'brier_score':round(brier,4),
            'ece':round(float(ece),6) if np.isfinite(ece) else np.nan,
            'mce':round(float(mce),6) if np.isfinite(mce) else np.nan,
            'hl_chi2':round(hl_chi2,3),'hl_p_value':round(hl_p,4),
            'sensitivity':round(float(sens),4),'specificity':round(float(spec),4),
            'ppv':round(float(ppv),4),'npv':round(float(npv),4),
            'f1_score':round(float(f1),4),'mcc':round(float(mcc),4),
            'tp':int(tp),'fp':int(fp),'fn':int(fn),'tn':int(tn)}


# ------------------------------------------------------------------------------
# MODEL REGISTRY — LightGBM only
# ------------------------------------------------------------------------------
def _lgb_space(t):
    return {
        'n_estimators': t.suggest_int('n_estimators', 100, 1000),
        'num_leaves': t.suggest_int('num_leaves', 15, 255),
        'max_depth': t.suggest_int('max_depth', 3, 12),
        'learning_rate': t.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'min_child_samples': t.suggest_int('min_child_samples', 5, 100),
        'subsample': t.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': t.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': t.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': t.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }

REGISTRY = {
    'LightGBM': {
        'class': lgb.LGBMClassifier, 'data': 'tree',
        'fixed': {'random_state': RANDOM_STATE, 'verbosity': -1, 'n_jobs': -1, **LGB_DEVICE_PARAMS},
        'space': _lgb_space,
    },
}
TRIAL_BUDGET = {'LightGBM': 75}


def build_model(model_name, params, strategy, y_ref=None):
    cfg = REGISTRY[model_name]
    all_params = {**cfg['fixed'], **params}

    if strategy == 'S2_BALANCED':
        # LightGBM's sklearn wrapper supports class_weight natively — no manual
        # scale_pos_weight computation needed here, unlike XGBoost in Block 2.
        all_params['class_weight'] = 'balanced'

    model = cfg['class'](**all_params)
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model


def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience:
            return
        if trial.number - study.best_trial.number >= patience:
            study.stop()
    return callback


# ------------------------------------------------------------------------------
# RUNNER — identical shape to Blocks 1-2
# ------------------------------------------------------------------------------
def run_pipeline(registry, trial_budget, build_model_fn):
    metric_rows = []
    print("\n" + "=" * 70); print("HYPERPARAMETER TUNING (Optuna)"); print("=" * 70)

    local_best = {}
    for model_name in registry:
        n_trials = trial_budget[model_name]

        for strategy in STRATEGIES:
            print(f"\nTuning {model_name}/{strategy} ({n_trials} trials, "
                  f"early stop after {EARLY_STOP_PATIENCE} w/o improvement)...", end=' ', flush=True)
            warning_counts['ConvergenceWarning'] = 0
            t0 = time.time()

            def objective(trial, model_name=model_name, strategy=strategy):
                params = registry[model_name]['space'](trial)
                scores = []
                for tr_idx, val_idx in skf_tune.split(Xt_tune, yt_tune):
                    try:
                        m = build_model_fn(model_name, params, strategy)
                        m.fit(Xt_tune[tr_idx], yt_tune[tr_idx])
                        proba = m.predict_proba(Xt_tune[val_idx])[:, 1]
                        if len(np.unique(yt_tune[val_idx])) < 2:
                            continue
                        scores.append(roc_auc_score(yt_tune[val_idx], proba))
                    except Exception as e:
                        print(f"[WARN] {model_name}/{strategy} fold failed: {e}")
                return float(np.mean(scores)) if scores else 0.0

            study = optuna.create_study(direction='maximize',
                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
            study.optimize(objective, n_trials=n_trials, show_progress_bar=False, n_jobs=1,
                            callbacks=[make_early_stop_callback()])

            local_best[(model_name, strategy)] = study.best_params
            elapsed = time.time() - t0
            n_conv = warning_counts['ConvergenceWarning']
            print(f"best CV AUROC = {study.best_value:.4f}  "
                  f"(trial {study.best_trial.number}/{len(study.trials)}, {elapsed:.0f}s, "
                  f"{n_conv} convergence warnings)")

            with open(MDL_DIR / f"study_{model_name}_{strategy}.pkl", 'wb') as f:
                pickle.dump(study, f)

    save_best_params(local_best)
    all_params = load_best_params()

    print("\n" + "=" * 70); print("FINAL TEST-SET EVALUATION"); print("=" * 70)
    for model_name in registry:
        for strategy in STRATEGIES:
            params = all_params.get((model_name, strategy), {})
            print(f"\n  {model_name}/{strategy}...", end=' ', flush=True)
            t0 = time.time()
            try:
                model = build_model_fn(model_name, params, strategy)
                model.fit(Xt_train, yt_arr)
                y_prob = model.predict_proba(Xt_test)[:, 1]

                if strategy == 'S3_THRESHOLD':
                    cv_p = cross_val_predict(build_model_fn(model_name, params, strategy),
                                              Xt_train, yt_arr, cv=skf_eval,
                                              method='predict_proba', n_jobs=-1)[:, 1]
                    threshold = find_optimal_threshold(yt_arr, cv_p)
                else:
                    threshold = 0.5

                y_pred = (y_prob >= threshold).astype(int)
                metrics = evaluate_model(ytest_arr, y_prob, y_pred, model_name, strategy, threshold)
                metric_rows.append(metrics)

                pd.DataFrame({'TRR_ID_CODE': data['y_test'].index, 'y_true': ytest_arr,
                              'y_prob': y_prob, 'y_pred': y_pred}
                ).to_csv(OUT_DIR / f"predictions_{model_name}_{strategy}.csv", index=False)

                with open(MDL_DIR / f"model_{model_name}_{strategy}.pkl", 'wb') as f:
                    pickle.dump(model, f)

                elapsed = time.time() - t0
                print(f"AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
                      f"F1={metrics['f1_score']:.4f}  Brier={metrics['brier_score']:.4f}  "
                      f"ECE={metrics['ece']:.4f}  ({elapsed:.0f}s)")

            except Exception as e:
                print(f"FAILED — {e}")

    append_metrics(metric_rows)
    return pd.DataFrame(metric_rows)


block3_results = run_pipeline(REGISTRY, TRIAL_BUDGET, build_model)
print("\nBlock 3 complete.")
print(block3_results[['model', 'strategy', 'auroc', 'auprc', 'f1_score']].to_string(index=False))

  GPU detection failed on both APIs:
    modern (device_type=cuda) error : CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1 (NVIDIA GPUs) or -DUSE_ROCM=1 (AMD GPUs)
    legacy (device=gpu) error       : GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
LightGBM device : CPU fallback — this is exactly the crash Block 3 exists to avoid

======================================================================
3-YEAR REJECTION DATA LOADED (Block 3 — LightGBM)
======================================================================
Tree train : (28596, 269)   Tree test : (7568, 269)
Train: 28,596 (44.0% rejection)
Test : 7,568 (39.3% rejection)

Tuning subsample: 14,298 patients (44.0% rejection)

======================================================================
HYPERPARAMETER TUNING (Optuna)
======================================================================

Tuning LightGBM/S1_SMOTE (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6668  (trial 4/20, 220s, 0 convergence warnings)

Tuning LightGBM/S2_BALANCED (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6731  (trial 36/52, 591s, 0 convergence warnings)

Tuning LightGBM/S3_THRESHOLD (75 trials, early stop after 15 w/o improvement)... best CV AUROC = 0.6756  (trial 68/75, 908s, 0 convergence warnings)

======================================================================
FINAL TEST-SET EVALUATION
======================================================================

  LightGBM/S1_SMOTE... AUROC=0.6516  AUPRC=0.5492  F1=0.5564  Brier=0.2330  ECE=0.1028  (9s)

  LightGBM/S2_BALANCED... AUROC=0.6661  AUPRC=0.5668  F1=0.5796  Brier=0.2358  ECE=0.1243  (9s)

  LightGBM/S3_THRESHOLD... AUROC=0.6664  AUPRC=0.5677  F1=0.5835  Brier=0.2272  ECE=0.0818  (24s)

Block 3 complete.
   model     strategy  auroc  auprc  f1_score
LightGBM     S1_SMOTE 0.6516 0.5492    0.5564
LightGBM  S2_BALANCED 0.6661 0.5668    0.5796
LightGBM S3_THRESHOLD 0.6664 0.5677    0.5835

# 6B - BLOCK 4/4: CATBOOST, MLP, ENSEMBLES, STATS, CALIBRATION, DCA, FIGURES - local

# 6B 4/4 1.CATBOOST

In [ ]:
# ==============================================================================
# BLOCK — CATBOOST TRAINING ONLY (S1_SMOTE strategy), fully self-contained
# 3-YEAR REJECTION.
#
# SPEED, NOT SHORTCUT: (1) per-fold early stopping during Optuna tuning so
# weak trials die fast instead of running to the iteration cap; (2) the
# best-iteration count CatBoost itself found during tuning is reused as a
# FIXED iteration count for the final fit -- so the final model trains on
# 100% of the training data in one pass, no held-out early-stop slice
# needed, no overtraining either; (3) S1_SMOTE skips the extra CV pass
# S3_THRESHOLD needs for decision-threshold selection. None of this
# changes what the model learns -- it just stops wasting iterations/folds
# on things that don't move the answer.
#
# NOTE: switched from wrapping CatBoost in an ImblearnPipeline to manual
# SMOTE().fit_resample() calls, because eval_set/early_stopping_rounds
# can't cleanly pass through a generic sklearn Pipeline.fit() -- this is
# functionally identical SMOTE application, just restructured to allow
# early stopping.
# ==============================================================================
from pathlib import Path
import pickle, warnings
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)

from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
SMOTE_K = 5
CV_FOLDS_TUNE = 3
N_TRIALS_CATBOOST = 40        # cut from 60 -- only 1 strategy trained now
EARLY_STOP_PATIENCE_OPTUNA = 10   # Optuna-level: give up on the whole search after 10 stale trials
EARLY_STOPPING_ROUNDS_CB = 50     # CatBoost-level: stop a single fit if no improvement for 50 rounds
MODEL_NAME, STRATEGY = 'CatBoost', 'S1_SMOTE'
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE HELPERS ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params(); params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    # Dedup by (model, strategy) -- reruns of this block cleanly OVERWRITE
    # the old CatBoost/S1_SMOTE row, never duplicate it.
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

# ---------------- METRIC HELPERS (identical to the rest of the pipeline) ----------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception:
            continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4),
            'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA (tree family only -- CatBoost doesn't need linear-encoded data) ----------------
Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xt_train, Xt_test = Xtr_tree.values.astype('float32'), Xte_tree.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values

print("=" * 70); print("CATBOOST BLOCK -- DATA LOADED"); print("=" * 70)
print(f"Tree train {Xt_train.shape}  Train n={len(yt_arr):,} ({yt_arr.mean()*100:.1f}% rejection)")

# ---------------- SEARCH SPACE ----------------
def _cb_space(t):
    return {
        'iterations': t.suggest_int('iterations', 200, 800),
        'depth': t.suggest_int('depth', 3, 10),
        'learning_rate': t.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'l2_leaf_reg': t.suggest_float('l2_leaf_reg', 1e-2, 30.0, log=True),
        'border_count': t.suggest_int('border_count', 32, 255),
        'bagging_temperature': t.suggest_float('bagging_temperature', 0.0, 1.0),
    }

def make_early_stop_callback(patience=EARLY_STOP_PATIENCE_OPTUNA):
    def callback(study, trial):
        if trial.number < patience: return
        if trial.number - study.best_trial.number >= patience: study.stop()
    return callback

# ---------------- TUNE (half the training data, 3-fold, per-fold early stopping) ----------------
idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=0.5, stratify=yt_arr, random_state=RANDOM_STATE)
X_tune, y_tune = Xt_train[idx], yt_arr[idx]

print(f"\nTuning {MODEL_NAME}/{STRATEGY} ({N_TRIALS_CATBOOST} trials, early-stopping per fold)...", end=' ', flush=True)

def objective(trial):
    params = _cb_space(trial)
    scores, best_iters = [], []
    for tr_idx, val_idx in skf_tune.split(X_tune, y_tune):
        try:
            X_tr, y_tr = X_tune[tr_idx], y_tune[tr_idx]
            X_val, y_val = X_tune[val_idx], y_tune[val_idx]
            smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
            X_tr_res, y_tr_res = smote.fit_resample(X_tr, y_tr)

            model = CatBoostClassifier(**params, random_seed=RANDOM_STATE, verbose=0, allow_writing_files=False)
            model.fit(X_tr_res, y_tr_res, eval_set=(X_val, y_val),
                      early_stopping_rounds=EARLY_STOPPING_ROUNDS_CB, use_best_model=True)

            if len(np.unique(y_val)) < 2: continue
            proba = model.predict_proba(X_val)[:, 1]
            scores.append(roc_auc_score(y_val, proba))
            bi = model.get_best_iteration()
            best_iters.append(bi if bi is not None else params['iterations'])
        except Exception as e:
            print(f"[WARN] fold failed: {e}")
    trial.set_user_attr('avg_best_iter', float(np.mean(best_iters)) if best_iters else float(params['iterations']))
    return float(np.mean(scores)) if scores else 0.0

study = optuna.create_study(direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=N_TRIALS_CATBOOST, show_progress_bar=False, n_jobs=1,
                callbacks=[make_early_stop_callback()])
print(f"best CV AUROC = {study.best_value:.4f}")

# ---------------- BAKE THE EARLY-STOPPED ITERATION COUNT INTO THE FINAL FIT ----------------
best_iterations = int(round(study.best_trial.user_attrs.get('avg_best_iter', study.best_params.get('iterations', 500))))
ctor_params = dict(study.best_params)
ctor_params['iterations'] = best_iterations   # fixed, no early-stop slice needed on the final fit
save_best_params({(MODEL_NAME, STRATEGY): ctor_params})
print(f"Saved constructor-ready params (iterations fixed to CV-observed best={best_iterations}): {ctor_params}")

# ---------------- FINAL FIT ON 100% OF TRAINING DATA, NO EARLY-STOP SPLIT NEEDED ----------------
smote_final = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
X_train_res, y_train_res = smote_final.fit_resample(Xt_train, yt_arr)

model = CatBoostClassifier(**ctor_params, random_seed=RANDOM_STATE, verbose=0, allow_writing_files=False)
model.fit(X_train_res, y_train_res)
y_prob = model.predict_proba(Xt_test)[:, 1]
threshold = 0.5   # S1_SMOTE strategy uses the plain 0.5 cutoff, same as the original run
y_pred = (y_prob >= threshold).astype(int)

metrics = evaluate_model(ytest_arr, y_prob, y_pred, MODEL_NAME, STRATEGY, threshold)
print(f"\n{MODEL_NAME}/{STRATEGY}  AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
      f"Brier={metrics['brier_score']:.4f}  ECE={metrics['ece']:.4f}")

pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': y_prob, 'y_pred': y_pred}
             ).to_csv(OUT_DIR / f"predictions_{MODEL_NAME}_{STRATEGY}.csv", index=False)
with open(MDL_DIR / f"model_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(model, f)
append_metrics([metrics])

print(f"\nSaved -> predictions_{MODEL_NAME}_{STRATEGY}.csv, model_{MODEL_NAME}_{STRATEGY}.pkl, "
      f"best_params.pkl updated, row appended/overwritten in all_metrics.csv")
print("CatBoost block complete.")

======================================================================
CATBOOST BLOCK -- DATA LOADED
======================================================================
Tree train (28596, 269)  Train n=28,596 (44.0% rejection)

Tuning CatBoost/S1_SMOTE (40 trials, early-stopping per fold)... best CV AUROC = 0.6584
Saved constructor-ready params (iterations fixed to CV-observed best=698): {'iterations': 698, 'depth': 4, 'learning_rate': 0.01855998084649059, 'l2_leaf_reg': 0.04342298948286135, 'border_count': 100, 'bagging_temperature': 0.5247564316322378}

CatBoost/S1_SMOTE  AUROC=0.6407  AUPRC=0.5408  Brier=0.2355  ECE=0.1046

Saved -> predictions_CatBoost_S1_SMOTE.csv, model_CatBoost_S1_SMOTE.pkl, best_params.pkl updated, row appended/overwritten in all_metrics.csv
CatBoost block complete.

# 6B 4/4 2.MLP

In [ ]:
# ==============================================================================
# BLOCK — MLP TRAINING ONLY (S3_THRESHOLD strategy), fully self-contained
# 3-YEAR REJECTION.
#
# FIX vs. previous run: Optuna's study.best_params stores RAW suggest_*()
# names (n_layers, units_l0, units_l1) -- not the derived MLPClassifier
# constructor arg hidden_layer_sizes. Feeding that raw dict straight into
# MLPClassifier(**params) on reload crashes with an unexpected-keyword
# TypeError. Fixed by transforming raw params into a constructor-ready
# dict BEFORE saving to best_params.pkl, so every later reload is safe.
#
# LIGHTER: only S3_THRESHOLD strategy trained (S1_SMOTE/S2_BALANCED
# dropped by decision), and trial count cut 40->20 with a smaller early-
# stop patience, since we're no longer paying for 3 strategies at once.
# ==============================================================================
from pathlib import Path
import pickle, warnings
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)
from sklearn.exceptions import ConvergenceWarning

import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore', category=ConvergenceWarning)

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
OUT_DIR.mkdir(parents=True, exist_ok=True)
MDL_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
N_BOOTSTRAP = 1000
CV_FOLDS_TUNE = 3
CV_FOLDS_EVAL = 5
N_TRIALS_MLP = 40
EARLY_STOP_PATIENCE = 10    # cut from 15 to match smaller trial budget
MODEL_NAME, STRATEGY = 'MLP', 'S3_THRESHOLD'
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"

skf_tune = StratifiedKFold(n_splits=CV_FOLDS_TUNE, shuffle=True, random_state=RANDOM_STATE)
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE HELPERS ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f:
            return pickle.load(f)
    return {}

def save_best_params(new_entries: dict):
    params = load_best_params(); params.update(new_entries)
    with open(BEST_PARAMS_PATH, 'wb') as f:
        pickle.dump(params, f)
    return params

def append_metrics(rows: list):
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

# ---------------- METRIC HELPERS (identical to rest of pipeline) ----------------
def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception:
            continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float)
    y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def find_optimal_threshold(y_val, y_prob_val):
    thresholds = np.linspace(0.05, 0.95, 100)
    f1s = [f1_score(y_val, (y_prob_val >= t).astype(int), zero_division=0) for t in thresholds]
    return float(thresholds[np.argmax(f1s)])

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)
    y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4),
            'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA (linear family only -- MLP doesn't need tree-encoded data) ----------------
Xtr_lin = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
Xte_lin = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
y_train = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test  = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xl_train, Xl_test = Xtr_lin.values.astype('float32'), Xte_lin.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values

print("=" * 70); print("MLP BLOCK -- DATA LOADED"); print("=" * 70)
print(f"Linear train {Xl_train.shape}  Train n={len(yt_arr):,} ({yt_arr.mean()*100:.1f}% rejection)")

# ---------------- THE FIX: raw Optuna params -> real constructor params ----------------
def _mlp_raw_to_ctor_params(raw):
    """study.best_params holds RAW suggest_*() names (n_layers, units_l0,
    units_l1) -- NOT the derived hidden_layer_sizes MLPClassifier actually
    needs. This is exactly what crashed last run. Rebuild the real
    constructor dict here, ONCE, before it ever touches best_params.pkl."""
    n_layers = raw['n_layers']
    sizes = tuple(raw[f'units_l{i}'] for i in range(n_layers))
    return {'hidden_layer_sizes': sizes, 'alpha': raw['alpha'],
            'learning_rate_init': raw['learning_rate_init']}

def build_mlp(params):
    # S3_THRESHOLD only -> plain model. No SMOTE wrap, no class_weight
    # (MLPClassifier has no class_weight kwarg at all).
    fixed = {'random_state': RANDOM_STATE, 'max_iter': 300, 'early_stopping': True,
              'n_iter_no_change': 15, 'validation_fraction': 0.1, 'activation': 'relu'}
    return MLPClassifier(**{**fixed, **params})

def make_early_stop_callback(patience=EARLY_STOP_PATIENCE):
    def callback(study, trial):
        if trial.number < patience: return
        if trial.number - study.best_trial.number >= patience: study.stop()
    return callback

# ---------------- TUNE (half the training data, 3-fold, S3_THRESHOLD only) ----------------
idx, _ = train_test_split(np.arange(len(yt_arr)), train_size=0.5, stratify=yt_arr, random_state=RANDOM_STATE)
X_tune, y_tune = Xl_train[idx], yt_arr[idx]

print(f"\nTuning {MODEL_NAME}/{STRATEGY} ({N_TRIALS_MLP} trials)...", end=' ', flush=True)

def objective(trial):
    raw_n_layers = trial.suggest_int('n_layers', 1, 2)
    sizes = tuple(trial.suggest_int(f'units_l{i}', 32, 256) for i in range(raw_n_layers))
    params = {'hidden_layer_sizes': sizes,
              'alpha': trial.suggest_float('alpha', 1e-5, 1e-1, log=True),
              'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True)}
    scores = []
    for tr_idx, val_idx in skf_tune.split(X_tune, y_tune):
        try:
            m = build_mlp(params)
            m.fit(X_tune[tr_idx], y_tune[tr_idx])
            proba = m.predict_proba(X_tune[val_idx])[:, 1]
            if len(np.unique(y_tune[val_idx])) < 2: continue
            scores.append(roc_auc_score(y_tune[val_idx], proba))
        except Exception as e:
            print(f"[WARN] fold failed: {e}")
    return float(np.mean(scores)) if scores else 0.0

study = optuna.create_study(direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=N_TRIALS_MLP, show_progress_bar=False, n_jobs=1,
                callbacks=[make_early_stop_callback()])
print(f"best CV AUROC = {study.best_value:.4f}")

ctor_params = _mlp_raw_to_ctor_params(study.best_params)
save_best_params({(MODEL_NAME, STRATEGY): ctor_params})
print(f"Saved constructor-ready params: {ctor_params}")

# ---------------- FINAL FIT + OOF THRESHOLD (no leakage) + EVAL ----------------
model = build_mlp(ctor_params)
model.fit(Xl_train, yt_arr)
y_prob = model.predict_proba(Xl_test)[:, 1]

cv_p = cross_val_predict(build_mlp(ctor_params), Xl_train, yt_arr, cv=skf_eval,
                          method='predict_proba', n_jobs=-1)[:, 1]
threshold = find_optimal_threshold(yt_arr, cv_p)
y_pred = (y_prob >= threshold).astype(int)

metrics = evaluate_model(ytest_arr, y_prob, y_pred, MODEL_NAME, STRATEGY, threshold)
print(f"\n{MODEL_NAME}/{STRATEGY}  AUROC={metrics['auroc']:.4f}  AUPRC={metrics['auprc']:.4f}  "
      f"Brier={metrics['brier_score']:.4f}  ECE={metrics['ece']:.4f}")

pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': y_prob, 'y_pred': y_pred}
             ).to_csv(OUT_DIR / f"predictions_{MODEL_NAME}_{STRATEGY}.csv", index=False)
with open(MDL_DIR / f"model_{MODEL_NAME}_{STRATEGY}.pkl", 'wb') as f:
    pickle.dump(model, f)
append_metrics([metrics])

print(f"\nSaved -> predictions_{MODEL_NAME}_{STRATEGY}.csv, model_{MODEL_NAME}_{STRATEGY}.pkl, "
      f"row appended to all_metrics.csv")
print("MLP block complete.")

======================================================================
MLP BLOCK -- DATA LOADED
======================================================================
Linear train (28596, 623)  Train n=28,596 (44.0% rejection)

Tuning MLP/S3_THRESHOLD (40 trials)... best CV AUROC = 0.6510
Saved constructor-ready params: {'hidden_layer_sizes': (219,), 'alpha': 1.2634909227706301e-05, 'learning_rate_init': 0.0002381234594199645}

MLP/S3_THRESHOLD  AUROC=0.6169  AUPRC=0.4995  Brier=0.2943  ECE=0.2387

Saved -> predictions_MLP_S3_THRESHOLD.csv, model_MLP_S3_THRESHOLD.pkl, row appended to all_metrics.csv
MLP block complete.

# 6B 4/4 3.ENSEMBLE

In [ ]:
# ==============================================================================
# BLOCK — ENSEMBLE, fully self-contained. Repairs any missing all_metrics.csv
# rows first (CatBoost/S1_SMOTE + MLP/S3_THRESHOLD never got appended after
# the earlier crash, even though their predictions CSVs were already saved),
# then selects one best-strategy candidate per model family, builds Voting
# (simple average) and Stacking (LR meta-learner on out-of-fold predictions).
# ==============================================================================
from pathlib import Path
import pickle
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (roc_auc_score, average_precision_score, brier_score_loss,
                              f1_score, confusion_matrix)

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImblearnPipeline

from catboost import CatBoostClassifier
import xgboost as xgb
import lightgbm as lgb

# ---------------- CONFIG ----------------
BASE = Path(r"D:\Thesis\Thesis_parquet")
DATA_DIR = BASE / "model_ready" / "3yr"
OUT_DIR = BASE / "results" / "3yr"
MDL_DIR = BASE / "models" / "3yr"
RANDOM_STATE = 42
SMOTE_K = 5
CV_FOLDS_EVAL = 5
N_BOOTSTRAP = 1000
BEST_PARAMS_PATH = MDL_DIR / "best_params.pkl"
METRICS_PATH = OUT_DIR / "all_metrics.csv"
skf_eval = StratifiedKFold(n_splits=CV_FOLDS_EVAL, shuffle=True, random_state=RANDOM_STATE)

# ---------------- PERSISTENCE + METRIC HELPERS (same as Block 1) ----------------
def load_best_params():
    if BEST_PARAMS_PATH.exists():
        with open(BEST_PARAMS_PATH, 'rb') as f: return pickle.load(f)
    return {}

def append_metrics(rows: list):
    if not rows: return
    new_df = pd.DataFrame(rows)
    if METRICS_PATH.exists():
        existing = pd.read_csv(METRICS_PATH)
        existing = existing[~existing.set_index(['model', 'strategy']).index.isin(
            new_df.set_index(['model', 'strategy']).index)]
        merged = pd.concat([existing, new_df], ignore_index=True)
    else:
        merged = new_df
    merged.to_csv(METRICS_PATH, index=False)

def bootstrap_metric(y_true, y_score, metric_fn, n=N_BOOTSTRAP, seed=RANDOM_STATE):
    rng = np.random.RandomState(seed); vals = []
    for _ in range(n):
        idx = rng.choice(len(y_true), len(y_true), replace=True)
        try:
            v = metric_fn(y_true[idx], y_score[idx])
            if np.isfinite(v): vals.append(v)
        except Exception: continue
    if not vals: return np.nan, np.nan
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))

def hosmer_lemeshow_test(y_true, y_prob, n_bins=10):
    df = pd.DataFrame({'y': y_true, 'p': y_prob})
    df['decile'] = pd.qcut(df['p'], n_bins, duplicates='drop')
    hl = df.groupby('decile', observed=False).agg(O1=('y', 'sum'), n=('y', 'count'), E1=('p', 'mean')).reset_index()
    hl['E1'] *= hl['n']; hl['O0'] = hl['n'] - hl['O1']; hl['E0'] = hl['n'] - hl['E1']
    hl = hl[hl['E1'] > 0]
    chi2 = float((((hl['O1'] - hl['E1']) ** 2 / hl['E1']) + ((hl['O0'] - hl['E0']) ** 2 / hl['E0'])).sum())
    p = 1 - stats.chi2.cdf(chi2, df=max(len(hl) - 2, 1))
    return chi2, p

def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float); y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    if len(y_true) == 0 or len(np.unique(y_true)) < 2: return np.nan, np.nan, []
    edges = np.linspace(0, 1, n_bins + 1); ece, mce, bins = 0.0, 0.0, []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        conf, acc = float(y_prob[mask].mean()), float(y_true[mask].mean())
        gap = abs(acc - conf); ece += (n_m / len(y_true)) * gap; mce = max(mce, gap)
        bins.append({'bin_lo': round(lo, 3), 'bin_hi': round(hi, 3), 'n': n_m,
                      'conf': round(conf, 4), 'acc': round(acc, 4), 'gap': round(gap, 4)})
    return round(ece, 6), round(mce, 6), bins

def evaluate_model(y_true, y_prob, y_pred, model_name, strategy, threshold=0.5):
    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob); y_pred = np.asarray(y_pred, dtype=int)
    auroc = roc_auc_score(y_true, y_prob); auprc = average_precision_score(y_true, y_prob)
    auroc_lo, auroc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: roc_auc_score(yt, yp) if len(np.unique(yt)) > 1 else np.nan)
    auprc_lo, auprc_hi = bootstrap_metric(y_true, y_prob, lambda yt, yp: average_precision_score(yt, yp) if yt.sum() > 0 else np.nan)
    brier = brier_score_loss(y_true, y_prob); ece, mce, _ = compute_ece_mce(y_true, y_prob)
    hl_chi2, hl_p = hosmer_lemeshow_test(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred); tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)
    eps = 1e-12
    sens, spec = tp / (tp + fn + eps), tn / (tn + fp + eps); ppv, npv = tp / (tp + fp + eps), tn / (tn + fn + eps)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    denom = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    mcc = (tp * tn - fp * fn) / (denom + eps) if denom > 0 else 0.0
    return {'model': model_name, 'strategy': strategy, 'threshold': round(threshold, 3), 'n_test': len(y_true),
            'n_pos': int(y_true.sum()), 'prevalence': round(float(y_true.mean()), 4),
            'auroc': round(auroc, 4), 'auroc_ci_lo': round(auroc_lo, 4), 'auroc_ci_hi': round(auroc_hi, 4),
            'auprc': round(auprc, 4), 'auprc_ci_lo': round(auprc_lo, 4), 'auprc_ci_hi': round(auprc_hi, 4),
            'brier_score': round(brier, 4), 'ece': round(float(ece), 6) if np.isfinite(ece) else np.nan,
            'mce': round(float(mce), 6) if np.isfinite(mce) else np.nan,
            'hl_chi2': round(hl_chi2, 3), 'hl_p_value': round(hl_p, 4),
            'sensitivity': round(float(sens), 4), 'specificity': round(float(spec), 4),
            'ppv': round(float(ppv), 4), 'npv': round(float(npv), 4),
            'f1_score': round(float(f1), 4), 'mcc': round(float(mcc), 4),
            'tp': int(tp), 'fp': int(fp), 'fn': int(fn), 'tn': int(tn)}

# ---------------- DATA ----------------
Xtr_tree = pd.read_parquet(DATA_DIR / "X_train_tree.parquet", engine="pyarrow")
Xte_tree = pd.read_parquet(DATA_DIR / "X_test_tree.parquet", engine="pyarrow")
Xtr_lin  = pd.read_parquet(DATA_DIR / "X_train_linear.parquet", engine="pyarrow")
Xte_lin  = pd.read_parquet(DATA_DIR / "X_test_linear.parquet", engine="pyarrow")
y_train  = pd.read_parquet(DATA_DIR / "y_train.parquet", engine="pyarrow").squeeze().astype(int)
y_test   = pd.read_parquet(DATA_DIR / "y_test.parquet", engine="pyarrow").squeeze().astype(int)

Xt_train, Xt_test = Xtr_tree.values.astype('float32'), Xte_tree.values.astype('float32')
Xl_train, Xl_test = Xtr_lin.values.astype('float32'), Xte_lin.values.astype('float32')
yt_arr, ytest_arr = y_train.values, y_test.values
DATA_BY_KIND = {'tree': (Xt_train, Xt_test), 'linear': (Xl_train, Xl_test)}
DATA_KIND_BY_MODEL = {
    'LogisticRegression': 'linear', 'LinearSVM': 'linear', 'SGD': 'linear', 'MLP': 'linear',
    'RandomForest': 'tree', 'AdaBoost': 'tree', 'XGBoost': 'tree', 'LightGBM': 'tree', 'CatBoost': 'tree',
}

# ---------------- REPAIR: recover any all_metrics.csv row lost to the earlier crash ----------------
# The MLP crash meant append_metrics() never ran for CatBoost OR MLP, even
# though both already had their predictions CSVs safely on disk. Recompute
# + append any missing row now -- otherwise best_per_family below silently
# drops a real, already-trained model (CatBoost, the current best single
# model) from ensemble candidacy and from the final results table.
def repair_missing_metric(model_name, strategy):
    existing = pd.read_csv(METRICS_PATH) if METRICS_PATH.exists() else pd.DataFrame(columns=['model', 'strategy'])
    already_there = ((existing['model'] == model_name) & (existing['strategy'] == strategy)).any() if len(existing) else False
    if already_there:
        return
    pred_csv = OUT_DIR / f"predictions_{model_name}_{strategy}.csv"
    if not pred_csv.exists():
        print(f"  [REPAIR] {model_name}/{strategy} missing from all_metrics.csv and no predictions CSV "
              f"found either -- this model must be retrained, cannot recover.")
        return
    preds = pd.read_csv(pred_csv)
    m = evaluate_model(preds['y_true'].values, preds['y_prob'].values, preds['y_pred'].values,
                        model_name, strategy, threshold=0.5)
    append_metrics([m])
    print(f"  [REPAIR] recovered {model_name}/{strategy} from saved predictions "
          f"(AUROC={m['auroc']:.4f}) -- appended to all_metrics.csv")

print("=" * 70); print("ENSEMBLE BLOCK -- REPAIR CHECK"); print("=" * 70)
repair_missing_metric('CatBoost', 'S1_SMOTE')
repair_missing_metric('MLP', 'S3_THRESHOLD')

# ---------------- SELECT BEST-PER-FAMILY (auto = "whichever strategy is better") ----------------
all_metrics = pd.read_csv(METRICS_PATH)
all_metrics = all_metrics[~all_metrics['model'].str.startswith('Ensemble')]
best_per_family = all_metrics.loc[all_metrics.groupby('model')['auroc'].idxmax()].reset_index(drop=True)
print("\n" + "=" * 70); print("BEST STRATEGY PER MODEL FAMILY (ensemble candidates)"); print("=" * 70)
print(best_per_family[['model', 'strategy', 'auroc', 'auprc', 'brier_score', 'ece']].to_string(index=False))

# ---------------- RECONSTRUCTORS ----------------
def build_catboost(params, strategy):
    all_params = {**params, 'random_seed': RANDOM_STATE, 'verbose': 0, 'allow_writing_files': False}
    if strategy == 'S2_BALANCED': all_params['auto_class_weights'] = 'Balanced'
    model = CatBoostClassifier(**all_params)
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model

def build_mlp(params, strategy):
    fixed = {'random_state': RANDOM_STATE, 'max_iter': 300, 'early_stopping': True,
              'n_iter_no_change': 15, 'validation_fraction': 0.1, 'activation': 'relu'}
    model = MLPClassifier(**{**fixed, **params})
    if strategy in ('S1_SMOTE', 'S2_BALANCED'):
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', model)])
    return model

def generic_reconstruct(model_name, params, strategy):
    if model_name == 'RandomForest':
        p = {**params, 'random_state': RANDOM_STATE, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = RandomForestClassifier(**p)
    elif model_name == 'XGBoost':
        p = {**params, 'random_state': RANDOM_STATE, 'objective': 'binary:logistic',
             'eval_metric': 'logloss', 'verbosity': 0, 'n_jobs': -1}
        if strategy == 'S2_BALANCED':
            n_pos, n_neg = int((yt_arr == 1).sum()), int((yt_arr == 0).sum())
            p['scale_pos_weight'] = n_neg / max(n_pos, 1)
        base = xgb.XGBClassifier(**p)
    elif model_name == 'LightGBM':
        p = {**params, 'random_state': RANDOM_STATE, 'verbosity': -1, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = lgb.LGBMClassifier(**p)
    elif model_name == 'CatBoost':
        return build_catboost(params, strategy)
    elif model_name == 'AdaBoost':
        params = dict(params); depth = params.pop('base_max_depth', 3)
        cw = 'balanced' if strategy == 'S2_BALANCED' else None
        tree = DecisionTreeClassifier(max_depth=depth, class_weight=cw, random_state=RANDOM_STATE)
        base = AdaBoostClassifier(estimator=tree, random_state=RANDOM_STATE, **params)
    elif model_name == 'LogisticRegression':
        p = {**params, 'max_iter': 500, 'solver': 'saga', 'random_state': RANDOM_STATE}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = LogisticRegression(**p)
    elif model_name == 'SGD':
        p = {**params, 'loss': 'log_loss', 'max_iter': 100, 'random_state': RANDOM_STATE, 'n_jobs': -1}
        if strategy == 'S2_BALANCED': p['class_weight'] = 'balanced'
        base = SGDClassifier(**p)
    elif model_name == 'MLP':
        return build_mlp(params, strategy)
    else:
        raise ValueError(f"No reconstructor for {model_name} -- add one before including it in the ensemble.")
    if strategy == 'S1_SMOTE':
        smote = SMOTE(k_neighbors=SMOTE_K, sampling_strategy=1.0, random_state=RANDOM_STATE)
        return ImblearnPipeline([('smote', smote), ('model', base)])
    return base

# ---------------- OOF (for stacking) + TEST PREDICTIONS (for both) PER MEMBER ----------------
all_best_params = load_best_params()
ensemble_members = best_per_family.to_dict('records')
oof_preds, test_preds, member_names = {}, {}, []

print("\n" + "=" * 70); print("GENERATING OOF + TEST PREDICTIONS PER MEMBER"); print("=" * 70)
for row in ensemble_members:
    name, strategy = row['model'], row['strategy']
    params = all_best_params.get((name, strategy), {})
    data_kind = DATA_KIND_BY_MODEL.get(name)
    if data_kind is None:
        print(f"  Skipping {name}: unknown data family, add it to DATA_KIND_BY_MODEL.")
        continue
    X_train, X_test = DATA_BY_KIND[data_kind]
    print(f"  {name}/{strategy}...", end=' ', flush=True)
    try:
        est = generic_reconstruct(name, dict(params), strategy)
        oof = cross_val_predict(est, X_train, yt_arr, cv=skf_eval, method='predict_proba', n_jobs=-1)[:, 1]
        oof_preds[name] = oof
        pred_csv = OUT_DIR / f"predictions_{name}_{strategy}.csv"
        test_preds[name] = pd.read_csv(pred_csv)['y_prob'].values
        member_names.append(name)
        print("done.")
    except Exception as e:
        print(f"SKIPPED -- {e}")

print(f"\nEnsemble members: {member_names}")
meta_X_train = np.column_stack([oof_preds[m] for m in member_names])
meta_X_test = np.column_stack([test_preds[m] for m in member_names])

# ---------------- VOTING (simple average) ----------------
voting_prob = meta_X_test.mean(axis=1)
voting_metrics = evaluate_model(ytest_arr, voting_prob, (voting_prob >= 0.5).astype(int), 'Ensemble_Voting', 'AVERAGE', 0.5)
print("\nVoting ensemble:", {k: voting_metrics[k] for k in ['auroc', 'auprc', 'brier_score', 'ece']})

# ---------------- STACKING (LR meta-learner on OOF features) ----------------
meta_learner = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)
meta_learner.fit(meta_X_train, yt_arr)
stacking_prob = meta_learner.predict_proba(meta_X_test)[:, 1]
stacking_metrics = evaluate_model(ytest_arr, stacking_prob, (stacking_prob >= 0.5).astype(int), 'Ensemble_Stacking', 'META_LR', 0.5)
print("Stacking ensemble:", {k: stacking_metrics[k] for k in ['auroc', 'auprc', 'brier_score', 'ece']})
print("Meta-learner coefficients (higher = more weight):", dict(zip(member_names, np.round(meta_learner.coef_[0], 3))))

for name, probs, m in [('Ensemble_Voting', voting_prob, voting_metrics), ('Ensemble_Stacking', stacking_prob, stacking_metrics)]:
    pd.DataFrame({'TRR_ID_CODE': y_test.index, 'y_true': ytest_arr, 'y_prob': probs}
                 ).to_csv(OUT_DIR / f"predictions_{name}.csv", index=False)
append_metrics([voting_metrics, stacking_metrics])
print("\nEnsemble block complete.")

# 6B 4/4 4.STATS

In [ ]:
# ==============================================================================
# BLOCK — STATS, CALIBRATION, DCA, FIGURES. Fully self-contained -- reloads
# all_metrics.csv + saved predictions CSVs, no in-memory dependency on
# Blocks 1/2.
# ==============================================================================
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve

BASE = Path(r"D:\Thesis\Thesis_parquet")
OUT_DIR = BASE / "results" / "3yr"
FIG_DIR = OUT_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# ---------------- IDENTIFY "BEST SINGLE" MODEL (excluding ensembles!) ----------------
# Block 2 already appended Ensemble_Voting/Ensemble_Stacking rows to
# all_metrics.csv -- must filter those out here or DeLong would end up
# comparing the ensemble against itself.
final_table = pd.read_csv(OUT_DIR / "all_metrics.csv")
non_ensemble = final_table[~final_table['model'].str.startswith('Ensemble')]
best_single = non_ensemble.loc[non_ensemble['auroc'].idxmax()]
best_single_probs = pd.read_csv(OUT_DIR / f"predictions_{best_single['model']}_{best_single['strategy']}.csv")['y_prob'].values
voting_df = pd.read_csv(OUT_DIR / "predictions_Ensemble_Voting.csv")
stacking_df = pd.read_csv(OUT_DIR / "predictions_Ensemble_Stacking.csv")
ytest_arr = voting_df['y_true'].values
voting_prob, stacking_prob = voting_df['y_prob'].values, stacking_df['y_prob'].values

print("=" * 70); print(f"BEST SINGLE MODEL: {best_single['model']}/{best_single['strategy']} "
                        f"(AUROC={best_single['auroc']:.4f})"); print("=" * 70)

# ---------------- DELONG'S TEST (self-verified against sklearn) ----------------
def _compute_midrank(x):
    J = np.argsort(x); Z = x[J]; N = len(x); T = np.zeros(N, dtype=float)
    i = 0
    while i < N:
        j = i
        while j < N and Z[j] == Z[i]: j += 1
        T[i:j] = 0.5 * (i + j - 1) + 1
        i = j
    T2 = np.empty(N, dtype=float); T2[J] = T
    return T2

def _fast_delong(preds_sorted_T, m):
    n = preds_sorted_T.shape[1] - m
    pos, neg = preds_sorted_T[:, :m], preds_sorted_T[:, m:]
    k = preds_sorted_T.shape[0]
    tx = np.empty([k, m]); ty = np.empty([k, n]); tz = np.empty([k, m + n])
    for r in range(k):
        tx[r, :] = _compute_midrank(pos[r, :]); ty[r, :] = _compute_midrank(neg[r, :]); tz[r, :] = _compute_midrank(preds_sorted_T[r, :])
    aucs = tz[:, :m].sum(axis=1) / m / n - (m + 1.0) / 2.0 / n
    v01 = (tz[:, :m] - tx) / n; v10 = 1.0 - (tz[:, m:] - ty) / m
    sx = np.cov(v01); sy = np.cov(v10)
    return aucs, sx / m + sy / n

def delong_roc_test(y_true, prob_a, prob_b, label_a="A", label_b="B"):
    y_true = np.asarray(y_true); order = np.argsort(-y_true); m = int(y_true.sum())
    preds_sorted_T = np.vstack([prob_a, prob_b])[:, order]
    aucs, cov = _fast_delong(preds_sorted_T, m)
    sk_auc_a, sk_auc_b = roc_auc_score(y_true, prob_a), roc_auc_score(y_true, prob_b)
    assert abs(aucs[0] - sk_auc_a) < 1e-9, f"DeLong/sklearn AUC mismatch for {label_a} -- DO NOT TRUST THIS P-VALUE"
    assert abs(aucs[1] - sk_auc_b) < 1e-9, f"DeLong/sklearn AUC mismatch for {label_b} -- DO NOT TRUST THIS P-VALUE"
    l = np.array([[1, -1]]); var = float(np.dot(np.dot(l, cov), l.T)[0, 0])
    z = abs(aucs[0] - aucs[1]) / np.sqrt(var) if var > 0 else 0.0
    p = 2 * (1 - stats.norm.cdf(z))
    return {'auc_a': aucs[0], 'auc_b': aucs[1], 'diff': aucs[0] - aucs[1], 'z': z, 'p_value': p, 'verified_against_sklearn': True}

print("\n" + "=" * 70); print("DELONG'S TEST (internal comparisons only -- same test set)"); print("=" * 70)
delong_results = []
for name, probs in [('Ensemble_Voting', voting_prob), ('Ensemble_Stacking', stacking_prob)]:
    res = delong_roc_test(ytest_arr, best_single_probs, probs, label_a=f"{best_single['model']}/{best_single['strategy']}", label_b=name)
    print(f"  {best_single['model']}/{best_single['strategy']} (AUROC={res['auc_a']:.4f}) vs {name} (AUROC={res['auc_b']:.4f}): "
          f"diff={res['diff']:+.4f}, p={res['p_value']:.4f} (verified: {res['verified_against_sklearn']})")
    delong_results.append({'comparison': f"best_single_vs_{name}", **res})
pd.DataFrame(delong_results).to_csv(OUT_DIR / "delong_tests.csv", index=False)

# ---------------- DECISION CURVE ANALYSIS ----------------
def decision_curve(y_true, y_prob, thresholds=np.arange(0.01, 0.99, 0.01)):
    n = len(y_true); prevalence = y_true.mean(); rows = []
    for pt in thresholds:
        pred_pos = y_prob >= pt
        tp = np.sum(pred_pos & (y_true == 1)); fp = np.sum(pred_pos & (y_true == 0))
        nb_model = (tp / n) - (fp / n) * (pt / (1 - pt))
        nb_all = prevalence - (1 - prevalence) * (pt / (1 - pt))
        rows.append({'threshold': pt, 'net_benefit_model': nb_model, 'net_benefit_treat_all': nb_all, 'net_benefit_treat_none': 0.0})
    return pd.DataFrame(rows)

dca_best = decision_curve(ytest_arr, best_single_probs)
dca_stack = decision_curve(ytest_arr, stacking_prob)
dca_best.to_csv(OUT_DIR / "dca_best_single.csv", index=False)
dca_stack.to_csv(OUT_DIR / "dca_stacking.csv", index=False)

plt.figure(figsize=(7, 5))
plt.plot(dca_best['threshold'], dca_best['net_benefit_model'], label=f"{best_single['model']} (best single)")
plt.plot(dca_stack['threshold'], dca_stack['net_benefit_model'], label="Stacking ensemble")
plt.plot(dca_best['threshold'], dca_best['net_benefit_treat_all'], '--', color='gray', label="Treat all")
plt.plot(dca_best['threshold'], dca_best['net_benefit_treat_none'], ':', color='black', label="Treat none")
plt.xlabel("Threshold probability"); plt.ylabel("Net benefit"); plt.legend()
plt.title("Decision Curve Analysis — 3-year rejection"); plt.ylim(bottom=-0.05)
plt.savefig(FIG_DIR / "dca_3yr.png", dpi=150, bbox_inches='tight'); plt.close()

# ---------------- ROC + CALIBRATION FIGURES ----------------
def compute_ece_mce(y_true, y_prob, n_bins=10):
    y_true = np.asarray(y_true, dtype=float); y_prob = np.clip(np.asarray(y_prob, dtype=float), 1e-7, 1 - 1e-7)
    edges = np.linspace(0, 1, n_bins + 1); bins = []
    for i in range(n_bins):
        lo, hi = edges[i], edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        n_m = int(mask.sum())
        if n_m == 0: continue
        bins.append({'conf': float(y_prob[mask].mean()), 'acc': float(y_true[mask].mean())})
    return bins

plt.figure(figsize=(6, 6))
for name, probs in [(f"{best_single['model']} (best single)", best_single_probs), ("Voting", voting_prob), ("Stacking", stacking_prob)]:
    fpr, tpr, _ = roc_curve(ytest_arr, probs)
    plt.plot(fpr, tpr, label=f"{name} (AUROC={roc_auc_score(ytest_arr, probs):.3f})")
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel("1 - Specificity"); plt.ylabel("Sensitivity"); plt.legend()
plt.title("ROC — 3-year rejection"); plt.savefig(FIG_DIR / "roc_3yr.png", dpi=150, bbox_inches='tight'); plt.close()

plt.figure(figsize=(6, 6))
for name, probs in [(f"{best_single['model']}", best_single_probs), ("Stacking", stacking_prob)]:
    bins = compute_ece_mce(ytest_arr, probs)
    if bins:
        bdf = pd.DataFrame(bins)
        plt.plot(bdf['conf'], bdf['acc'], marker='o', label=name)
plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel("Predicted probability"); plt.ylabel("Observed frequency"); plt.legend()
plt.title("Calibration — 3-year rejection"); plt.savefig(FIG_DIR / "calibration_3yr.png", dpi=150, bbox_inches='tight'); plt.close()
print(f"\nFigures saved -> {FIG_DIR}")

# ---------------- PUBLICATION TABLE ----------------
final_table = pd.read_csv(OUT_DIR / "all_metrics.csv").sort_values('auroc', ascending=False).reset_index(drop=True)
final_table['auroc_display'] = final_table.apply(lambda r: f"{r['auroc']:.3f} ({r['auroc_ci_lo']:.3f}-{r['auroc_ci_hi']:.3f})", axis=1)
final_table['auprc_display'] = final_table.apply(lambda r: f"{r['auprc']:.3f} ({r['auprc_ci_lo']:.3f}-{r['auprc_ci_hi']:.3f})", axis=1)
final_table.to_csv(OUT_DIR / "publication_table_3yr.csv", index=False)

print("\n" + "=" * 70); print("FINAL PUBLICATION TABLE — 3-YEAR REJECTION"); print("=" * 70)
print(final_table[['model', 'strategy', 'auroc_display', 'auprc_display', 'brier_score', 'ece', 'hl_p_value']].to_string(index=False))
print("\nStats/Calibration/DCA/Figures block complete.")
print('Figures are: calibration_3yr.png, roc_3yr.png, dca_3yr.png saved in D:\Thesis\Thesis_parquet\results\3yr\figures')

======================================================================
BEST SINGLE MODEL: LightGBM/S3_THRESHOLD (AUROC=0.6794)
======================================================================

======================================================================
DELONG'S TEST (internal comparisons only -- same test set)
======================================================================
  LightGBM/S3_THRESHOLD (AUROC=0.6794) vs Ensemble_Voting (AUROC=0.6764): diff=+0.0030, p=0.2610 (verified: True)
  LightGBM/S3_THRESHOLD (AUROC=0.6794) vs Ensemble_Stacking (AUROC=0.6848): diff=-0.0054, p=0.0025 (verified: True)

Figures saved -> D:\Thesis\Thesis_parquet\results\3yr\figures

======================================================================
FINAL PUBLICATION TABLE — 3-YEAR REJECTION
======================================================================
             model     strategy       auroc_display       auprc_display  brier_score      ece  hl_p_value
 Ensemble_Stacking      META_LR 0.685 (0.674-0.698) 0.591 (0.572-0.612)       0.2252 0.100468         0.0
          LightGBM S3_THRESHOLD 0.679 (0.668-0.692) 0.582 (0.563-0.602)       0.2223 0.077546         0.0
           XGBoost S3_THRESHOLD 0.679 (0.666-0.691) 0.581 (0.562-0.602)       0.2226 0.073764         0.0
          LightGBM  S2_BALANCED 0.678 (0.666-0.690) 0.577 (0.558-0.596)       0.2326 0.121805         0.0
          CatBoost     S1_SMOTE 0.677 (0.666-0.690) 0.584 (0.566-0.605)       0.2272 0.105135         0.0
           XGBoost  S2_BALANCED 0.677 (0.665-0.690) 0.578 (0.559-0.598)       0.2333 0.126791         0.0
   Ensemble_Voting      AVERAGE 0.676 (0.665-0.689) 0.580 (0.561-0.600)       0.2392 0.146321         0.0
           XGBoost     S1_SMOTE 0.674 (0.662-0.687) 0.575 (0.556-0.595)       0.2251 0.084703         0.0
      RandomForest  S2_BALANCED 0.671 (0.658-0.683) 0.559 (0.539-0.580)       0.2320 0.109350         0.0
      RandomForest S3_THRESHOLD 0.671 (0.658-0.684) 0.562 (0.543-0.583)       0.2257 0.077833         0.0
          LightGBM     S1_SMOTE 0.665 (0.653-0.678) 0.559 (0.540-0.580)       0.2276 0.088727         0.0
      RandomForest     S1_SMOTE 0.660 (0.647-0.673) 0.550 (0.531-0.570)       0.2306 0.089543         0.0
          AdaBoost S3_THRESHOLD 0.653 (0.641-0.666) 0.553 (0.534-0.573)       0.2321 0.098082         0.0
          AdaBoost  S2_BALANCED 0.652 (0.641-0.666) 0.546 (0.534-0.573)       0.2438 0.129700         0.0
LogisticRegression     S1_SMOTE 0.642 (0.630-0.655) 0.531 (0.513-0.551)       0.2992 0.269960         0.0
LogisticRegression S3_THRESHOLD 0.641 (0.628-0.653) 0.532 (0.513-0.552)       0.2673 0.201728         0.0
LogisticRegression  S2_BALANCED 0.640 (0.628-0.653) 0.531 (0.513-0.551)       0.2900 0.251841         0.0
               SGD     S1_SMOTE 0.640 (0.628-0.652) 0.533 (0.515-0.552)       0.2901 0.253207         0.0
          AdaBoost     S1_SMOTE 0.637 (0.641-0.666) 0.528 (0.534-0.573)       0.2395 0.107800         0.0
               SGD S3_THRESHOLD 0.634 (0.621-0.647) 0.523 (0.505-0.544)       0.2379 0.105775         0.0
               MLP S3_THRESHOLD 0.633 (0.621-0.647) 0.522 (0.504-0.542)       0.2818 0.208704         0.0
               SGD  S2_BALANCED 0.632 (0.620-0.645) 0.519 (0.500-0.538)       0.2687 0.201503         0.0
         LinearSVM S3_THRESHOLD 0.617 (0.604-0.630) 0.496 (0.477-0.516)       0.2751 0.210513         0.0
         LinearSVM  S2_BALANCED 0.617 (0.604-0.629) 0.495 (0.475-0.514)       0.2715 0.202262         0.0
         LinearSVM     S1_SMOTE 0.617 (0.604-0.629) 0.494 (0.475-0.513)       0.2724 0.204492         0.0

Stats/Calibration/DCA/Figures block complete.
esultsyrigures

In [ ]:
             model     strategy       auroc_display       auprc_display  brier_score      ece  hl_p_value
 Ensemble_Stacking      META_LR 0.685 (0.674-0.698) 0.591 (0.572-0.612)       0.2252 0.100468         0.0
          LightGBM S3_THRESHOLD 0.679 (0.668-0.692) 0.582 (0.563-0.602)       0.2223 0.077546         0.0
           XGBoost S3_THRESHOLD 0.679 (0.666-0.691) 0.581 (0.562-0.602)       0.2226 0.073764         0.0
          LightGBM  S2_BALANCED 0.678 (0.666-0.690) 0.577 (0.558-0.596)       0.2326 0.121805         0.0
          CatBoost     S1_SMOTE 0.677 (0.666-0.690) 0.584 (0.566-0.605)       0.2272 0.105135         0.0
           XGBoost  S2_BALANCED 0.677 (0.665-0.690) 0.578 (0.559-0.598)       0.2333 0.126791         0.0
   Ensemble_Voting      AVERAGE 0.676 (0.665-0.689) 0.580 (0.561-0.600)       0.2392 0.146321         0.0
           XGBoost     S1_SMOTE 0.674 (0.662-0.687) 0.575 (0.556-0.595)       0.2251 0.084703         0.0
      RandomForest  S2_BALANCED 0.671 (0.658-0.683) 0.559 (0.539-0.580)       0.2320 0.109350         0.0
      RandomForest S3_THRESHOLD 0.671 (0.658-0.684) 0.562 (0.543-0.583)       0.2257 0.077833         0.0
          LightGBM     S1_SMOTE 0.665 (0.653-0.678) 0.559 (0.540-0.580)       0.2276 0.088727         0.0
      RandomForest     S1_SMOTE 0.660 (0.647-0.673) 0.550 (0.531-0.570)       0.2306 0.089543         0.0
          AdaBoost S3_THRESHOLD 0.653 (0.641-0.666) 0.553 (0.534-0.573)       0.2321 0.098082         0.0
          AdaBoost  S2_BALANCED 0.652 (0.641-0.666) 0.546 (0.534-0.573)       0.2438 0.129700         0.0
LogisticRegression     S1_SMOTE 0.642 (0.630-0.655) 0.531 (0.513-0.551)       0.2992 0.269960         0.0
LogisticRegression S3_THRESHOLD 0.641 (0.628-0.653) 0.532 (0.513-0.552)       0.2673 0.201728         0.0
LogisticRegression  S2_BALANCED 0.640 (0.628-0.653) 0.531 (0.513-0.551)       0.2900 0.251841         0.0
               SGD     S1_SMOTE 0.640 (0.628-0.652) 0.533 (0.515-0.552)       0.2901 0.253207         0.0
          AdaBoost     S1_SMOTE 0.637 (0.641-0.666) 0.528 (0.534-0.573)       0.2395 0.107800         0.0
               SGD S3_THRESHOLD 0.634 (0.621-0.647) 0.523 (0.505-0.544)       0.2379 0.105775         0.0
               MLP S3_THRESHOLD 0.633 (0.621-0.647) 0.522 (0.504-0.542)       0.2818 0.208704         0.0
               SGD  S2_BALANCED 0.632 (0.620-0.645) 0.519 (0.500-0.538)       0.2687 0.201503         0.0
         LinearSVM S3_THRESHOLD 0.617 (0.604-0.630) 0.496 (0.477-0.516)       0.2751 0.210513         0.0
         LinearSVM  S2_BALANCED 0.617 (0.604-0.629) 0.495 (0.475-0.514)       0.2715 0.202262         0.0
         LinearSVM     S1_SMOTE 0.617 (0.604-0.629) 0.494 (0.475-0.513)       0.2724 0.204492         0.0

# xai

In [ ]:
# ==============================================================================
# SEGMENT 7 — XAI ANALYSIS
# 1-YEAR: XGBoost / S2_BALANCED
# 3-YEAR: LightGBM / S3_THRESHOLD
# ==============================================================================
#
# PURPOSE
# -------
# A reproducible, thesis-safe feature-level XAI pipeline:
#
#   1. Load the exact selected model for each horizon
#   2. Load the exact model-ready train/test matrices
#   3. Verify model family, feature count, feature order, IDs, and probabilities
#   4. Compute global TreeSHAP importance on the complete held-out test set
#   5. Generate SHAP bar and beeswarm plots
#   6. Generate SHAP directionality tables
#   7. Generate dependence plots for top features
#   8. Select representative TP/TN/FP/FN cases using the ACTUAL evaluation threshold
#   9. Generate SHAP waterfalls for those cases
#  10. Generate LIME local explanations using the training matrix as background
#  11. Compare 1-year and 3-year SHAP rankings
#  12. Quantify rank shifts, direction agreement, and Spearman rank correlation
#  13. Generate a normalized cross-horizon SHAP heatmap
#
# IMPORTANT
# ---------
# * XAI uses the SAME model-ready feature space used by Segment 6.
# * Prediction rows are aligned by TRR_ID_CODE, never by row count alone.
# * The 3-year S3_THRESHOLD threshold MUST be the threshold saved/used by
#   Segment 6. This script will NOT invent a threshold from the test set.
# * TreeSHAP is calculated on the model's RAW output scale.
#   For binary XGBoost/LightGBM this is generally the log-odds / margin scale,
#   not probability.
# * Cross-horizon SHAP magnitudes are compared after normalization and by rank,
#   not as raw model-output units.
#
# ==============================================================================

from pathlib import Path
import json
import pickle
import re
import warnings

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap

warnings.filterwarnings("default")

try:
    from lime.lime_tabular import LimeTabularExplainer
    LIME_AVAILABLE = True
except ImportError:
    LimeTabularExplainer = None
    LIME_AVAILABLE = False
    print("WARNING: LIME is not installed. LIME analysis will be skipped.")
    print("Install with: pip install lime")

try:
    from scipy.stats import spearmanr
    SCIPY_AVAILABLE = True
except ImportError:
    spearmanr = None
    SCIPY_AVAILABLE = False
    print("WARNING: SciPy is not installed. Spearman rank correlation will be skipped.")


# ==============================================================================
# 1. PATHS
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

RESULT_DIR = BASE / "results"
MODEL_ROOT = BASE / "models"
MODEL_READY_ROOT = BASE / "model_ready"

XAI_ROOT = RESULT_DIR / "XAI"
XAI_ROOT.mkdir(parents=True, exist_ok=True)

for horizon in ("1yr", "3yr"):
    (XAI_ROOT / horizon).mkdir(parents=True, exist_ok=True)


# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================

# --------------------------------------------------------------------------
# PREFERRED: fill these with the EXACT artifacts used by Segment 6.
# Leave as None only if you want the controlled discovery functions to find
# a unique matching file.
# --------------------------------------------------------------------------

MODEL_OVERRIDE = {
    "1yr": None,
    "3yr": None,
}

X_TRAIN_OVERRIDE = {
    "1yr": None,
    "3yr": None,
}

X_TEST_OVERRIDE = {
    "1yr": None,
    "3yr": None,
}

PREDICTION_OVERRIDE = {
    "1yr": None,
    "3yr": None,
}

# --------------------------------------------------------------------------
# THRESHOLDS
# --------------------------------------------------------------------------
# 1-year S2_BALANCED normally uses the standard 0.5 operating threshold
# unless Segment 6 explicitly used another threshold.
#
# 3-year S3_THRESHOLD MUST be replaced by the EXACT threshold saved/used
# in Segment 6.
#
# Do NOT optimize a threshold on this test set inside this script.
# --------------------------------------------------------------------------

THRESHOLD_OVERRIDE = {
    "1yr": 0.5,
    "3yr": None,  # <-- REQUIRED: insert the exact Segment 6 S3 threshold
}

CONFIG = {
    "1yr": {
        "model_name": "XGBoost",
        "strategy": "S2_BALANCED",
        "label": "1-Year Rejection",
        "expected_train_n": 27431,
        "expected_test_n": 13796,
    },
    "3yr": {
        "model_name": "LightGBM",
        "strategy": "S3_THRESHOLD",
        "label": "3-Year Rejection",
        "expected_train_n": 28596,
        "expected_test_n": 7568,
    },
}

# Plot settings
TOP_GLOBAL = 20
TOP_DEPENDENCE = 6
TOP_COMPARISON = 30
WATERFALL_MAX_DISPLAY = 15
LIME_MAX_FEATURES = 15
LIME_NUM_SAMPLES = 5000
RANDOM_STATE = 42

# Numerical tolerances for integrity checks
PREDICTION_ATOL = 1e-5
PREDICTION_RTOL = 1e-5
SHAP_ADDITIVITY_ATOL = 1e-4


# ==============================================================================
# 3. GENERIC HELPERS
# ==============================================================================

def safe_name(value):
    """Return a filesystem-safe feature name."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value))


def load_table(path):
    """Load a supported tabular artifact."""
    path = Path(path)
    suffix = path.suffix.lower()

    if suffix == ".parquet":
        return pd.read_parquet(path)

    if suffix == ".csv":
        return pd.read_csv(path)

    if suffix in {".pkl", ".pickle"}:
        return pd.read_pickle(path)

    if suffix == ".joblib":
        return joblib.load(path)

    raise ValueError(f"Unsupported tabular/model file type: {path}")


def load_model(path):
    """Load a joblib/pickle model."""
    path = Path(path)

    try:
        model = joblib.load(path)
    except Exception:
        with open(path, "rb") as f:
            model = pickle.load(f)

    print(f"\nLoaded model: {path}")
    print(f"Model class: {type(model).__module__}.{type(model).__name__}")

    return model


def normalize_ids(values):
    """
    Normalize TRR_ID_CODE values to comparable strings.

    Handles integer-like floats such as 123.0 -> '123'.
    """
    s = pd.Series(values)

    def one(x):
        if pd.isna(x):
            return None

        if isinstance(x, (np.integer, int)):
            return str(int(x))

        if isinstance(x, (np.floating, float)):
            if not np.isfinite(x):
                return None
            if float(x).is_integer():
                return str(int(x))
            return str(x)

        text = str(x).strip()

        if text.endswith(".0"):
            try:
                f = float(text)
                if f.is_integer():
                    return str(int(f))
            except Exception:
                pass

        return text

    return s.map(one).astype("string")


def identify_id_source(X):
    """
    Return TRR_ID_CODE and feature matrix without the identifier.

    Preferred representation:
      * X.index.name == 'TRR_ID_CODE'
    Also accepts:
      * a TRR_ID_CODE column
    """
    X = X.copy()

    if "TRR_ID_CODE" in X.columns:
        ids = normalize_ids(X["TRR_ID_CODE"])
        X = X.drop(columns=["TRR_ID_CODE"])
        source = "column"
        return ids, X, source

    if X.index.name == "TRR_ID_CODE":
        ids = normalize_ids(X.index)
        X.index = ids.to_numpy()
        source = "index"
        return ids, X, source

    raise ValueError(
        "X matrix has neither a 'TRR_ID_CODE' column nor an index named "
        "'TRR_ID_CODE'. Patient-level XAI alignment is therefore unsafe."
    )


def make_index(X, ids):
    """Set TRR_ID_CODE as the final feature-matrix index without using it as a predictor."""
    X = X.copy()
    ids = pd.Series(ids).astype("string")

    if ids.isna().any():
        raise ValueError("TRR_ID_CODE contains missing values.")

    if ids.duplicated().any():
        dup = ids[ids.duplicated()].head(10).tolist()
        raise ValueError(f"Duplicate TRR_ID_CODE values detected: {dup}")

    X.index = ids.to_numpy()
    X.index.name = "TRR_ID_CODE"
    return X


def ensure_numeric(X, matrix_name):
    """Require the final model-ready matrix to be numeric."""
    non_numeric = X.select_dtypes(exclude=[np.number]).columns.tolist()

    if non_numeric:
        raise TypeError(
            f"{matrix_name} still contains non-numeric columns:\n"
            f"{non_numeric[:50]}\n\n"
            "Do NOT convert these to category codes in Segment 7. "
            "The matrix must already contain the exact preprocessing/encoding "
            "used by model training."
        )

    if X.isna().any().any():
        missing_cols = X.columns[X.isna().any()].tolist()
        raise ValueError(
            f"{matrix_name} contains NaN values in "
            f"{len(missing_cols)} columns."
        )

    if np.isinf(X.to_numpy(dtype=np.float64, copy=False)).any():
        raise ValueError(f"{matrix_name} contains +/-inf values.")

    return X.astype(np.float32)


def print_matrix_summary(name, X):
    print(
        f"{name}: shape={X.shape}, "
        f"rows={len(X):,}, features={X.shape[1]:,}, "
        f"index={X.index.name!r}"
    )


# ==============================================================================
# 4. CONTROLLED ARTIFACT DISCOVERY
# ==============================================================================

def discover_unique_file(
    roots,
    patterns,
    expected_n=None,
    file_type="artifact",
):
    """Find exactly one plausible artifact."""
    candidates = []

    for root in roots:
        root = Path(root)

        if not root.exists():
            continue

        for pattern in patterns:
            candidates.extend(root.rglob(pattern))

    candidates = sorted(
        {Path(p).resolve() for p in candidates},
        key=lambda p: str(p).lower(),
    )

    if expected_n is not None:
        size_matched = []

        for path in candidates:
            try:
                obj = load_table(path)
                if isinstance(obj, pd.DataFrame) and len(obj) == expected_n:
                    size_matched.append(path)
            except Exception:
                continue

        if size_matched:
            candidates = size_matched

    if len(candidates) == 1:
        return candidates[0]

    if len(candidates) == 0:
        raise FileNotFoundError(
            f"No unique {file_type} artifact found.\n"
            f"Roots: {roots}\n"
            f"Patterns: {patterns}\n"
        )

    listing = "\n".join(str(p) for p in candidates[:30])

    raise RuntimeError(
        f"Ambiguous {file_type} discovery. More than one candidate exists:\n"
        f"{listing}\n\n"
        "Set the exact path in the corresponding *_OVERRIDE dictionary."
    )


def discover_model(horizon):
    cfg = CONFIG[horizon]

    roots = [
        MODEL_ROOT / horizon,
        RESULT_DIR / horizon,  # fallback only
    ]

    patterns = [
        f"*{cfg['model_name']}*{cfg['strategy']}*.pkl",
        f"*{cfg['model_name']}*{cfg['strategy']}*.joblib",
        f"*{cfg['strategy']}*{cfg['model_name']}*.pkl",
        f"*{cfg['strategy']}*{cfg['model_name']}*.joblib",
    ]

    override = MODEL_OVERRIDE.get(horizon)

    if override is not None:
        path = Path(override)
        if not path.exists():
            raise FileNotFoundError(f"MODEL_OVERRIDE does not exist: {path}")
        return path

    return discover_unique_file(
        roots=roots,
        patterns=patterns,
        file_type=f"{horizon} model",
    )


def discover_matrix(horizon, kind):
    cfg = CONFIG[horizon]
    expected_n = (
        cfg["expected_train_n"]
        if kind == "train"
        else cfg["expected_test_n"]
    )

    override_dict = (
        X_TRAIN_OVERRIDE
        if kind == "train"
        else X_TEST_OVERRIDE
    )

    override = override_dict.get(horizon)

    if override is not None:
        path = Path(override)
        if not path.exists():
            raise FileNotFoundError(
                f"{kind.upper()} matrix override does not exist: {path}"
            )
        return path

    if kind == "train":
        patterns = [
            "*X_train*.parquet",
            "*X_train*.csv",
            "*X_train*.pkl",
            "*X_train*.pickle",
            "*X_train*.joblib",
            "*train*features*.parquet",
            "*train*features*.csv",
        ]
    else:
        patterns = [
            "*X_test*.parquet",
            "*X_test*.csv",
            "*X_test*.pkl",
            "*X_test*.pickle",
            "*X_test*.joblib",
            "*test*features*.parquet",
            "*test*features*.csv",
        ]

    roots = [
        MODEL_READY_ROOT / horizon,
        RESULT_DIR / horizon,
    ]

    return discover_unique_file(
        roots=roots,
        patterns=patterns,
        expected_n=expected_n,
        file_type=f"{horizon} X_{kind}",
    )


def discover_prediction_file(horizon):
    cfg = CONFIG[horizon]
    override = PREDICTION_OVERRIDE.get(horizon)

    if override is not None:
        path = Path(override)
        if not path.exists():
            raise FileNotFoundError(
                f"PREDICTION_OVERRIDE does not exist: {path}"
            )
        return path

    path = (
        RESULT_DIR
        / horizon
        / f"predictions_{cfg['model_name']}_{cfg['strategy']}.csv"
    )

    if not path.exists():
        raise FileNotFoundError(
            "Prediction file not found:\n"
            f"{path}\n\n"
            "Set PREDICTION_OVERRIDE to the exact Segment 6 prediction CSV."
        )

    return path


# ==============================================================================
# 5. MODEL FEATURE NAME EXTRACTION / VALIDATION
# ==============================================================================

def get_model_feature_names(model):
    """Extract the exact feature order recorded by the fitted model."""
    if hasattr(model, "feature_names_in_"):
        names = list(model.feature_names_in_)
        if names:
            return names

    if hasattr(model, "get_booster"):
        try:
            names = model.get_booster().feature_names
            if names is not None:
                return list(names)
        except Exception:
            pass

    if hasattr(model, "feature_name_"):
        try:
            names = list(model.feature_name_)
            if names:
                return names
        except Exception:
            pass

    if hasattr(model, "booster_"):
        try:
            names = model.booster_.feature_name()
            if names is not None:
                return list(names)
        except Exception:
            pass

    return None


def validate_model_family(model, horizon):
    """Check that the loaded model matches the intended model family."""
    module = type(model).__module__.lower()
    class_name = type(model).__name__.lower()

    if horizon == "1yr":
        if not (
            hasattr(model, "get_booster")
            or "xgboost" in module
            or "xgb" in class_name
        ):
            raise TypeError(
                f"1-year configuration requires XGBoost, but loaded "
                f"{type(model).__module__}.{type(model).__name__}"
            )

    elif horizon == "3yr":
        if not (
            hasattr(model, "booster_")
            or "lightgbm" in module
            or "lgbm" in class_name
        ):
            raise TypeError(
                f"3-year configuration requires LightGBM, but loaded "
                f"{type(model).__module__}.{type(model).__name__}"
            )


def align_X_to_model(X, model):
    """
    Reorder the already-preprocessed feature matrix to the exact fitted-model
    feature order. Extra predictors are removed; missing predictors raise.
    """
    model_features = get_model_feature_names(model)

    if model_features is not None:
        model_features = list(model_features)

        missing = [f for f in model_features if f not in X.columns]
        extra = [f for f in X.columns if f not in model_features]

        if missing:
            raise ValueError(
                "X matrix is missing model features.\n"
                f"Missing ({len(missing)}): {missing[:50]}"
            )

        X_aligned = X.loc[:, model_features].copy()

        if extra:
            print(
                f"  Dropped {len(extra)} extra non-model columns "
                "(for example metadata/auxiliary columns)."
            )

        if X_aligned.columns.tolist() != model_features:
            raise RuntimeError("Failed to reproduce fitted model feature order.")

        return X_aligned

    n_features = getattr(model, "n_features_in_", None)

    if n_features is None:
        raise ValueError(
            "The fitted model exposes neither feature names nor n_features_in_. "
            "Cannot safely determine feature ordering."
        )

    if X.shape[1] != int(n_features):
        raise ValueError(
            f"X has {X.shape[1]} features, but model expects {n_features}."
        )

    print(
        "WARNING: model feature names are unavailable. "
        "Feature order is being trusted from the supplied matrix."
    )

    return X.copy()


# ==============================================================================
# 6. PREDICTION FILE LOADING / ID ALIGNMENT
# ==============================================================================

def find_column(df, candidates):
    lower_map = {str(c).lower(): c for c in df.columns}
    for candidate in candidates:
        if candidate.lower() in lower_map:
            return lower_map[candidate.lower()]
    return None


def identify_prediction_columns(pred):
    y_true_col = find_column(
        pred,
        ["y_true", "true", "actual", "target", "label"],
    )

    y_prob_col = find_column(
        pred,
        [
            "y_prob",
            "probability",
            "prob",
            "pred_prob",
            "prediction_probability",
        ],
    )

    y_pred_col = find_column(
        pred,
        [
            "y_pred",
            "predicted",
            "prediction",
            "class_prediction",
        ],
    )

    id_col = find_column(
        pred,
        ["TRR_ID_CODE", "trr_id_code", "TRR_ID", "id"],
    )

    if y_true_col is None:
        raise ValueError("Prediction file does not contain a recognizable y_true column.")

    if y_prob_col is None:
        raise ValueError("Prediction file does not contain a recognizable probability column.")

    if id_col is None:
        raise ValueError(
            "Prediction file does not contain TRR_ID_CODE. "
            "Prediction/X_test alignment cannot be performed safely."
        )

    return id_col, y_true_col, y_prob_col, y_pred_col


def align_predictions(X, pred):
    """
    Align predictions to X_test by TRR_ID_CODE.

    Returns:
      y_true, y_prob, y_pred_file, aligned_prediction_df
    """
    id_col, y_true_col, y_prob_col, y_pred_col = identify_prediction_columns(pred)

    x_ids = normalize_ids(X.index)

    pred = pred.copy()
    pred["__TRR_ID_NORMALIZED__"] = normalize_ids(pred[id_col])

    if pred["__TRR_ID_NORMALIZED__"].isna().any():
        raise ValueError("Prediction file contains missing TRR_ID_CODE values.")

    if pred["__TRR_ID_NORMALIZED__"].duplicated().any():
        duplicates = (
            pred.loc[
                pred["__TRR_ID_NORMALIZED__"].duplicated(),
                "__TRR_ID_NORMALIZED__",
            ]
            .head(10)
            .tolist()
        )
        raise ValueError(
            f"Prediction file has duplicate recipient IDs: {duplicates}"
        )

    if len(x_ids) != len(pred):
        raise ValueError(
            f"X_test rows ({len(x_ids):,}) != prediction rows ({len(pred):,})."
        )

    if set(x_ids) != set(pred["__TRR_ID_NORMALIZED__"]):
        missing_in_pred = sorted(
            set(x_ids) - set(pred["__TRR_ID_NORMALIZED__"])
        )[:20]

        missing_in_x = sorted(
            set(pred["__TRR_ID_NORMALIZED__"]) - set(x_ids)
        )[:20]

        raise ValueError(
            "X_test and prediction IDs do not match.\n"
            f"Missing from prediction file: {missing_in_pred}\n"
            f"Missing from X_test: {missing_in_x}"
        )

    pred = (
        pred.set_index("__TRR_ID_NORMALIZED__")
        .loc[x_ids]
        .reset_index()
    )

    y_true = pd.to_numeric(
        pred[y_true_col],
        errors="raise",
    ).astype(int).to_numpy()

    if not set(np.unique(y_true)).issubset({0, 1}):
        raise ValueError(
            f"y_true contains values outside {{0,1}}: "
            f"{sorted(np.unique(y_true).tolist())}"
        )

    y_prob = pd.to_numeric(
        pred[y_prob_col],
        errors="raise",
    ).astype(float).to_numpy()

    if not np.isfinite(y_prob).all():
        raise ValueError("Prediction probability contains NaN or inf.")

    if ((y_prob < 0.0) | (y_prob > 1.0)).any():
        raise ValueError("Prediction probability contains values outside [0,1].")

    y_pred_file = None

    if y_pred_col is not None:
        y_pred_file = (
            pd.to_numeric(pred[y_pred_col], errors="raise")
            .astype(int)
            .to_numpy()
        )

        if not set(np.unique(y_pred_file)).issubset({0, 1}):
            raise ValueError(
                f"Prediction file y_pred contains values outside {{0,1}}: "
                f"{sorted(np.unique(y_pred_file).tolist())}"
            )

    aligned = pred.drop(columns="__TRR_ID_NORMALIZED__").copy()

    return y_true, y_prob, y_pred_file, aligned


def validate_model_probabilities(model, X, y_prob, horizon):
    """
    Verify that the probability column in the saved prediction file matches
    the loaded model when run on the aligned X_test matrix.
    """
    print("\nValidating saved probabilities against the loaded model...")

    model_prob = np.asarray(
        model.predict_proba(X),
        dtype=np.float64,
    )

    if model_prob.ndim != 2 or model_prob.shape[1] < 2:
        raise ValueError(
            f"Unexpected predict_proba output shape: {model_prob.shape}"
        )

    model_prob = model_prob[:, 1]

    if len(model_prob) != len(y_prob):
        raise ValueError("Model probability length does not match prediction file.")

    max_abs_diff = float(np.max(np.abs(model_prob - y_prob)))
    mean_abs_diff = float(np.mean(np.abs(model_prob - y_prob)))

    print(f"  Maximum absolute probability difference: {max_abs_diff:.8e}")
    print(f"  Mean absolute probability difference:    {mean_abs_diff:.8e}")

    if not np.allclose(
        model_prob,
        y_prob,
        rtol=PREDICTION_RTOL,
        atol=PREDICTION_ATOL,
    ):
        raise ValueError(
            f"{horizon}: saved probabilities do not match the loaded model "
            "on the aligned X_test matrix.\n"
            "This indicates a model/data/prediction artifact mismatch."
        )

    print("  Probability validation: PASSED")


# ==============================================================================
# 7. THRESHOLD VALIDATION
# ==============================================================================

def get_threshold(horizon):
    threshold = THRESHOLD_OVERRIDE.get(horizon)

    if threshold is None:
        raise ValueError(
            f"No threshold supplied for {horizon}.\n"
            "For S3_THRESHOLD this value must be the exact threshold "
            "used during Segment 6 evaluation. Do not derive it from "
            "the test set in Segment 7."
        )

    threshold = float(threshold)

    if not 0.0 < threshold < 1.0:
        raise ValueError(
            f"{horizon} threshold must lie strictly between 0 and 1, got {threshold}"
        )

    print(f"\nOperating threshold for {horizon}: {threshold:.6f}")

    return threshold


def validate_file_predictions(
    y_true,
    y_prob,
    y_pred_file,
    threshold,
    horizon,
):
    y_pred_threshold = (y_prob >= threshold).astype(int)

    if y_pred_file is not None:
        matches = np.array_equal(y_pred_file, y_pred_threshold)

        print(
            f"Saved y_pred vs threshold-derived y_pred: "
            f"{'MATCH' if matches else 'MISMATCH'}"
        )

        if not matches:
            mismatch_count = int(np.sum(y_pred_file != y_pred_threshold))
            raise ValueError(
                f"{horizon}: saved y_pred does not correspond to the supplied "
                f"threshold {threshold:.6f} for {mismatch_count:,} observations.\n"
                "Use the exact Segment 6 threshold and prediction artifact."
            )

    return y_pred_threshold


# ==============================================================================
# 8. SHAP
# ==============================================================================

def calculate_shap(model, X):
    """
    Calculate TreeSHAP on the model RAW output scale.

    For binary classification, the returned matrix is:
        n_samples × n_features
    """
    print("\nCalculating TreeSHAP values...")

    explainer = shap.TreeExplainer(
        model,
        model_output="raw",
    )

    try:
        values = explainer.shap_values(
            X,
            check_additivity=False,
        )
    except TypeError:
        values = explainer.shap_values(X)

    if isinstance(values, list):
        if len(values) == 2:
            values = values[1]
        else:
            values = values[-1]

    if hasattr(values, "values"):
        values = values.values

    values = np.asarray(values)

    # Typical multiclass-style shape:
    # samples × features × classes
    if values.ndim == 3:
        if values.shape[-1] == 2:
            values = values[:, :, 1]
        else:
            values = values[:, :, -1]

    if values.ndim != 2:
        raise ValueError(f"Unexpected SHAP shape: {values.shape}")

    if values.shape != X.shape:
        raise ValueError(
            f"SHAP shape {values.shape} does not match X shape {X.shape}."
        )

    if not np.isfinite(values).all():
        raise ValueError("SHAP values contain NaN or inf.")

    print(f"SHAP shape: {values.shape}")

    return explainer, values


def get_base_value(explainer):
    value = np.asarray(explainer.expected_value)

    if value.ndim == 0:
        return float(value)

    flat = value.ravel()

    if flat.size == 1:
        return float(flat[0])

    # Binary/multiclass defensive fallback: positive-class convention
    return float(flat[-1])


def predict_raw_output(model, X):
    """
    Obtain the model's raw output on the same scale used by TreeSHAP.
    """
    if hasattr(model, "get_booster"):
        return np.asarray(
            model.predict(
                X,
                output_margin=True,
            ),
            dtype=np.float64,
        )

    module = type(model).__module__.lower()

    if "lightgbm" in module or hasattr(model, "booster_"):
        return np.asarray(
            model.predict(
                X,
                raw_score=True,
            ),
            dtype=np.float64,
        )

    raise TypeError(
        f"Unsupported tree model for raw-output validation: "
        f"{type(model).__module__}.{type(model).__name__}"
    )


def validate_shap_additivity(model, explainer, X, shap_values):
    """
    Verify:
        base_value + sum(SHAP values) ≈ model raw prediction
    """
    print("\nValidating SHAP additivity...")

    raw_pred = predict_raw_output(model, X)
    base_value = get_base_value(explainer)

    reconstructed = (
        base_value
        + np.sum(shap_values, axis=1)
    )

    if raw_pred.shape != reconstructed.shape:
        raise ValueError(
            f"Raw prediction shape {raw_pred.shape} != "
            f"SHAP reconstruction shape {reconstructed.shape}"
        )

    max_error = float(
        np.max(np.abs(reconstructed - raw_pred))
    )

    mean_error = float(
        np.mean(np.abs(reconstructed - raw_pred))
    )

    print(f"  Base value: {base_value:.8f}")
    print(f"  Maximum additivity error: {max_error:.8e}")
    print(f"  Mean additivity error:    {mean_error:.8e}")

    if max_error > SHAP_ADDITIVITY_ATOL:
        raise ValueError(
            "SHAP additivity validation failed. "
            "The SHAP values do not reconstruct the model raw output "
            f"within tolerance {SHAP_ADDITIVITY_ATOL}."
        )

    print("  SHAP additivity validation: PASSED")


def make_shap_explanation(explainer, X, shap_values):
    """
    Construct a reusable SHAP Explanation object for plotting.
    """
    base = get_base_value(explainer)

    return shap.Explanation(
        values=shap_values,
        base_values=np.repeat(base, len(X)),
        data=X.to_numpy(),
        feature_names=X.columns.tolist(),
    )


# ==============================================================================
# 9. GLOBAL SHAP TABLES
# ==============================================================================

def create_shap_table(X, shap_values):
    mean_abs = np.mean(
        np.abs(shap_values),
        axis=0,
    )

    mean_signed = np.mean(
        shap_values,
        axis=0,
    )

    positive_fraction = np.mean(
        shap_values > 0,
        axis=0,
    )

    negative_fraction = np.mean(
        shap_values < 0,
        axis=0,
    )

    zero_fraction = np.mean(
        shap_values == 0,
        axis=0,
    )

    table = pd.DataFrame(
        {
            "feature": X.columns,
            "mean_abs_shap": mean_abs,
            "mean_shap": mean_signed,
            "median_shap": np.median(shap_values, axis=0),
            "positive_fraction": positive_fraction,
            "negative_fraction": negative_fraction,
            "zero_fraction": zero_fraction,
        }
    )

    table["direction"] = np.select(
        [
            table["mean_shap"] > 0,
            table["mean_shap"] < 0,
        ],
        [
            "positive",
            "negative",
        ],
        default="neutral",
    )

    total = table["mean_abs_shap"].sum()

    if total > 0:
        table["normalized_importance_pct"] = (
            100.0
            * table["mean_abs_shap"]
            / total
        )
    else:
        table["normalized_importance_pct"] = 0.0

    table = (
        table
        .sort_values(
            "mean_abs_shap",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    table["rank"] = np.arange(1, len(table) + 1)

    return table


def create_direction_table(shap_values, X):
    return create_shap_table(X, shap_values)[
        [
            "feature",
            "mean_shap",
            "mean_abs_shap",
            "median_shap",
            "positive_fraction",
            "negative_fraction",
            "zero_fraction",
            "direction",
            "rank",
        ]
    ]


# ==============================================================================
# 10. PLOTS
# ==============================================================================

def plot_shap_bar(
    shap_values,
    X,
    horizon,
    model_name,
    output_dir,
):
    plt.figure(figsize=(10, 8))

    shap.summary_plot(
        shap_values,
        X,
        plot_type="bar",
        max_display=TOP_GLOBAL,
        show=False,
    )

    plt.title(
        f"{horizon} — SHAP Global Feature Importance\n"
        f"{model_name}"
    )

    plt.tight_layout()

    path = output_dir / "shap_global_bar.png"

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    print(f"Saved: {path}")


def plot_shap_beeswarm(
    shap_values,
    X,
    horizon,
    model_name,
    output_dir,
):
    plt.figure(figsize=(10, 9))

    shap.summary_plot(
        shap_values,
        X,
        max_display=TOP_GLOBAL,
        show=False,
    )

    plt.title(
        f"{horizon} — SHAP Beeswarm\n"
        f"{model_name}"
    )

    plt.tight_layout()

    path = output_dir / "shap_beeswarm.png"

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    print(f"Saved: {path}")


def create_dependence_plots(
    shap_values,
    X,
    shap_table,
    horizon,
    output_dir,
):
    dep_dir = output_dir / "dependence"
    dep_dir.mkdir(parents=True, exist_ok=True)

    top_features = (
        shap_table
        .head(TOP_DEPENDENCE)["feature"]
        .tolist()
    )

    for feature in top_features:
        try:
            plt.figure(figsize=(8, 6))

            shap.dependence_plot(
                feature,
                shap_values,
                X,
                interaction_index="auto",
                show=False,
            )

            plt.title(
                f"{horizon} — SHAP Dependence\n{feature}"
            )

            plt.tight_layout()

            path = (
                dep_dir
                / f"{safe_name(feature)}_dependence.png"
            )

            plt.savefig(
                path,
                dpi=300,
                bbox_inches="tight",
            )

            plt.close()

            print(f"Saved: {path}")

        except Exception as exc:
            plt.close()
            warnings.warn(
                f"Dependence plot failed for {feature}: {exc}"
            )


# ==============================================================================
# 11. LOCAL CASE SELECTION
# ==============================================================================

def select_cases(
    y_true,
    y_prob,
    threshold,
):
    """
    Select one representative case per confusion-matrix category.

    The selected observation is the most confidently classified within
    that category, based on distance from the ACTUAL operating threshold.
    """
    y_pred = (
        y_prob >= threshold
    ).astype(int)

    groups = {
        "TP": np.where((y_true == 1) & (y_pred == 1))[0],
        "TN": np.where((y_true == 0) & (y_pred == 0))[0],
        "FP": np.where((y_true == 0) & (y_pred == 1))[0],
        "FN": np.where((y_true == 1) & (y_pred == 0))[0],
    }

    selected = {}

    for case, indices in groups.items():
        if len(indices) == 0:
            selected[case] = None
            continue

        distance = np.abs(
            y_prob[indices] - threshold
        )

        selected[case] = int(
            indices[np.argmax(distance)]
        )

    return selected


def save_selected_cases(
    X,
    ids,
    y_true,
    y_prob,
    threshold,
    selected,
    output_dir,
):
    rows = []

    y_pred = (
        y_prob >= threshold
    ).astype(int)

    for case, idx in selected.items():
        if idx is None:
            continue

        rows.append(
            {
                "case": case,
                "row_index": int(idx),
                "TRR_ID_CODE": str(ids[idx]),
                "y_true": int(y_true[idx]),
                "y_prob": float(y_prob[idx]),
                "threshold": float(threshold),
                "y_pred": int(y_pred[idx]),
                "distance_from_threshold": float(
                    abs(y_prob[idx] - threshold)
                ),
            }
        )

    pd.DataFrame(rows).to_csv(
        output_dir / "selected_TP_TN_FP_FN_cases.csv",
        index=False,
    )


# ==============================================================================
# 12. SHAP WATERFALLS
# ==============================================================================

def create_waterfall(
    shap_explanation,
    row_idx,
    horizon,
    case_name,
    output_dir,
):
    one = shap.Explanation(
        values=shap_explanation.values[row_idx],
        base_values=shap_explanation.base_values[row_idx],
        data=shap_explanation.data[row_idx],
        feature_names=shap_explanation.feature_names,
    )

    plt.figure(figsize=(10, 8))

    shap.plots.waterfall(
        one,
        max_display=WATERFALL_MAX_DISPLAY,
        show=False,
    )

    plt.title(
        f"{horizon} — {case_name} SHAP Waterfall"
    )

    plt.tight_layout()

    path = (
        output_dir
        / f"waterfall_{case_name}.png"
    )

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    print(f"Saved: {path}")


# ==============================================================================
# 13. LIME
# ==============================================================================

def create_lime_explanations(
    model,
    X_train,
    X_test,
    y_true,
    y_prob,
    threshold,
    horizon,
    output_dir,
    ids,
):
    if not LIME_AVAILABLE:
        return

    print(f"\nGenerating LIME explanations for {horizon}...")

    selected = select_cases(
        y_true=y_true,
        y_prob=y_prob,
        threshold=threshold,
    )

    lime_dir = output_dir / "LIME"
    lime_dir.mkdir(parents=True, exist_ok=True)

    # LIME uses the training matrix as the background distribution.
    explainer = LimeTabularExplainer(
        training_data=X_train.to_numpy(dtype=np.float64),
        feature_names=X_train.columns.tolist(),
        class_names=["No Rejection", "Rejection"],
        mode="classification",
        discretize_continuous=True,
        random_state=RANDOM_STATE,
    )

    def predict_fn(data):
        data = np.asarray(
            data,
            dtype=np.float32,
        )

        probs = model.predict_proba(data)

        return np.asarray(
            probs,
            dtype=np.float64,
        )

    selected_meta = []

    for case, row_idx in selected.items():
        if row_idx is None:
            print(f"  No {case} case available.")
            continue

        explanation = explainer.explain_instance(
            X_test.iloc[row_idx].to_numpy(dtype=np.float64),
            predict_fn,
            num_features=LIME_MAX_FEATURES,
            top_labels=2,
            num_samples=LIME_NUM_SAMPLES,
        )

        html_path = (
            lime_dir
            / f"LIME_{case}.html"
        )

        csv_path = (
            lime_dir
            / f"LIME_{case}.csv"
        )

        explanation.save_to_file(
            str(html_path)
        )

        local_exp = explanation.as_list(label=1)

        lime_df = pd.DataFrame(
            local_exp,
            columns=["feature", "lime_weight"],
        )

        lime_df.insert(
            0,
            "case",
            case,
        )

        lime_df.to_csv(
            csv_path,
            index=False,
        )

        selected_meta.append(
            {
                "case": case,
                "row_index": int(row_idx),
                "TRR_ID_CODE": str(ids[row_idx]),
                "y_true": int(y_true[row_idx]),
                "y_prob": float(y_prob[row_idx]),
                "threshold": float(threshold),
            }
        )

        print(f"  Saved: {html_path}")
        print(f"  Saved: {csv_path}")

    pd.DataFrame(selected_meta).to_csv(
        lime_dir / "LIME_case_metadata.csv",
        index=False,
    )


# ==============================================================================
# 14. SAVE PRIMARY SHAP ARTIFACTS
# ==============================================================================

def save_shap_artifacts(
    X,
    shap_values,
    output_dir,
):
    X.to_parquet(
        output_dir / "X_test_model_order.parquet",
        index=True,
    )

    np.save(
        output_dir / "shap_values_raw.npy",
        shap_values,
    )


# ==============================================================================
# 15. RUN ONE HORIZON
# ==============================================================================

def run_horizon(horizon):
    cfg = CONFIG[horizon]

    print("\n")
    print("=" * 100)
    print(f"XAI ANALYSIS — {horizon.upper()}")
    print(
        f"Model: {cfg['model_name']} / {cfg['strategy']}"
    )
    print("=" * 100)

    output_dir = XAI_ROOT / horizon
    output_dir.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------------------------
    # Threshold
    # --------------------------------------------------------------------------
    threshold = get_threshold(horizon)

    # --------------------------------------------------------------------------
    # Model
    # --------------------------------------------------------------------------
    model_path = discover_model(horizon)
    model = load_model(model_path)

    validate_model_family(
        model,
        horizon,
    )

    # --------------------------------------------------------------------------
    # Load train/test matrices
    # --------------------------------------------------------------------------
    train_path = discover_matrix(
        horizon,
        "train",
    )

    test_path = discover_matrix(
        horizon,
        "test",
    )

    X_train_raw = load_table(train_path)
    X_test_raw = load_table(test_path)

    if not isinstance(X_train_raw, pd.DataFrame):
        raise TypeError(f"Training matrix is not a DataFrame: {train_path}")

    if not isinstance(X_test_raw, pd.DataFrame):
        raise TypeError(f"Test matrix is not a DataFrame: {test_path}")

    if len(X_train_raw) != cfg["expected_train_n"]:
        raise ValueError(
            f"{horizon}: expected {cfg['expected_train_n']:,} training rows, "
            f"got {len(X_train_raw):,}"
        )

    if len(X_test_raw) != cfg["expected_test_n"]:
        raise ValueError(
            f"{horizon}: expected {cfg['expected_test_n']:,} test rows, "
            f"got {len(X_test_raw):,}"
        )

    # --------------------------------------------------------------------------
    # Extract and preserve TRR_ID_CODE
    # --------------------------------------------------------------------------
    train_ids, X_train, _ = identify_id_source(X_train_raw)
    test_ids, X_test, _ = identify_id_source(X_test_raw)

    X_train = make_index(X_train, train_ids)
    X_test = make_index(X_test, test_ids)

    # Train/test IDs must be disjoint
    overlap = set(X_train.index) & set(X_test.index)

    if overlap:
        raise ValueError(
            f"{horizon}: {len(overlap)} TRR_ID_CODE values occur in both "
            "train and test matrices."
        )

    # --------------------------------------------------------------------------
    # Align test/train matrices to exact model feature order
    # --------------------------------------------------------------------------
    X_train = align_X_to_model(
        X_train,
        model,
    )

    X_test = align_X_to_model(
        X_test,
        model,
    )

    X_train = ensure_numeric(
        X_train,
        "X_train",
    )

    X_test = ensure_numeric(
        X_test,
        "X_test",
    )

    if X_train.columns.tolist() != X_test.columns.tolist():
        raise ValueError(
            f"{horizon}: train/test feature orders do not match."
        )

    print_matrix_summary("X_train", X_train)
    print_matrix_summary("X_test", X_test)

    # --------------------------------------------------------------------------
    # Prediction file
    # --------------------------------------------------------------------------
    prediction_path = discover_prediction_file(horizon)

    pred = pd.read_csv(
        prediction_path
    )

    print(f"\nPrediction file: {prediction_path}")
    print(f"Prediction shape: {pred.shape}")

    y_true, y_prob, y_pred_file, pred_aligned = align_predictions(
        X_test,
        pred,
    )

    # --------------------------------------------------------------------------
    # Validate prediction probabilities against loaded model
    # --------------------------------------------------------------------------
    validate_model_probabilities(
        model,
        X_test,
        y_prob,
        horizon,
    )

    # --------------------------------------------------------------------------
    # Validate threshold / prediction consistency
    # --------------------------------------------------------------------------
    y_pred = validate_file_predictions(
        y_true=y_true,
        y_prob=y_prob,
        y_pred_file=y_pred_file,
        threshold=threshold,
        horizon=horizon,
    )

    # --------------------------------------------------------------------------
    # SHAP
    # --------------------------------------------------------------------------
    explainer, shap_values = calculate_shap(
        model,
        X_test,
    )

    validate_shap_additivity(
        model,
        explainer,
        X_test,
        shap_values,
    )

    # Save raw SHAP + exact feature-order matrix
    save_shap_artifacts(
        X_test,
        shap_values,
        output_dir,
    )

    shap_explanation = make_shap_explanation(
        explainer,
        X_test,
        shap_values,
    )

    # --------------------------------------------------------------------------
    # Global tables
    # --------------------------------------------------------------------------
    shap_table = create_shap_table(
        X_test,
        shap_values,
    )

    direction_table = create_direction_table(
        shap_values,
        X_test,
    )

    shap_table.to_csv(
        output_dir / "shap_global_importance.csv",
        index=False,
    )

    direction_table.to_csv(
        output_dir / "shap_directionality.csv",
        index=False,
    )

    # --------------------------------------------------------------------------
    # Plots
    # --------------------------------------------------------------------------
    plot_shap_bar(
        shap_values,
        X_test,
        horizon,
        cfg["model_name"],
        output_dir,
    )

    plot_shap_beeswarm(
        shap_values,
        X_test,
        horizon,
        cfg["model_name"],
        output_dir,
    )

    create_dependence_plots(
        shap_values,
        X_test,
        shap_table,
        horizon,
        output_dir,
    )

    # --------------------------------------------------------------------------
    # TP / TN / FP / FN cases
    # --------------------------------------------------------------------------
    selected = select_cases(
        y_true=y_true,
        y_prob=y_prob,
        threshold=threshold,
    )

    save_selected_cases(
        X_test,
        test_ids.to_numpy(),
        y_true,
        y_prob,
        threshold,
        selected,
        output_dir,
    )

    for case, row_idx in selected.items():
        if row_idx is None:
            continue

        create_waterfall(
            shap_explanation,
            row_idx,
            horizon,
            case,
            output_dir,
        )

    # --------------------------------------------------------------------------
    # LIME
    # --------------------------------------------------------------------------
    create_lime_explanations(
        model=model,
        X_train=X_train,
        X_test=X_test,
        y_true=y_true,
        y_prob=y_prob,
        threshold=threshold,
        horizon=horizon,
        output_dir=output_dir,
        ids=test_ids.to_numpy(),
    )

    # --------------------------------------------------------------------------
    # Basic metadata
    # --------------------------------------------------------------------------
    metadata = {
        "horizon": horizon,
        "model_name": cfg["model_name"],
        "strategy": cfg["strategy"],
        "model_file": str(model_path),
        "x_train_file": str(train_path),
        "x_test_file": str(test_path),
        "prediction_file": str(prediction_path),
        "threshold": threshold,
        "threshold_source": "THRESHOLD_OVERRIDE / Segment 6 validated value",
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "n_features": int(X_test.shape[1]),
        "positive_cases": int(y_true.sum()),
        "negative_cases": int((y_true == 0).sum()),
        "model_feature_count": int(len(X_test.columns)),
        "shap_output_scale": "raw_model_output",
        "shap_base_value": get_base_value(explainer),
        "selected_cases": {
            k: (
                None
                if v is None
                else {
                    "row_index": int(v),
                    "TRR_ID_CODE": str(test_ids.iloc[v]),
                    "y_true": int(y_true[v]),
                    "y_prob": float(y_prob[v]),
                    "y_pred": int(y_pred[v]),
                }
            )
            for k, v in selected.items()
        },
    }

    with open(
        output_dir / "xai_metadata.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            metadata,
            f,
            indent=4,
        )

    print("\nTop features:")
    print(
        shap_table.head(TOP_GLOBAL).to_string(
            index=False
        )
    )

    print(f"\nCompleted XAI for {horizon}.")

    return {
        "model": model,
        "model_path": model_path,
        "X_train": X_train,
        "X_test": X_test,
        "X_train_path": train_path,
        "X_test_path": test_path,
        "prediction_path": prediction_path,
        "prediction_aligned": pred_aligned,
        "test_ids": test_ids,
        "y_true": y_true,
        "y_prob": y_prob,
        "y_pred": y_pred,
        "threshold": threshold,
        "explainer": explainer,
        "shap_values": shap_values,
        "shap_explanation": shap_explanation,
        "shap_table": shap_table,
        "direction_table": direction_table,
    }


# ==============================================================================
# 16. CROSS-HORIZON SHAP COMPARISON
# ==============================================================================

def build_cross_horizon_comparison(results):
    """
    Compare global SHAP importance across horizons.

    Raw SHAP magnitudes are retained for within-model reporting, but the
    cross-horizon comparison uses normalized importance (%) and rank.
    """
    one = results["1yr"]["shap_table"].copy()
    three = results["3yr"]["shap_table"].copy()

    one = one[
        [
            "feature",
            "mean_abs_shap",
            "normalized_importance_pct",
            "rank",
            "mean_shap",
            "direction",
        ]
    ].rename(
        columns={
            "mean_abs_shap": "mean_abs_shap_1yr",
            "normalized_importance_pct": "normalized_importance_pct_1yr",
            "rank": "rank_1yr",
            "mean_shap": "mean_shap_1yr",
            "direction": "direction_1yr",
        }
    )

    three = three[
        [
            "feature",
            "mean_abs_shap",
            "normalized_importance_pct",
            "rank",
            "mean_shap",
            "direction",
        ]
    ].rename(
        columns={
            "mean_abs_shap": "mean_abs_shap_3yr",
            "normalized_importance_pct": "normalized_importance_pct_3yr",
            "rank": "rank_3yr",
            "mean_shap": "mean_shap_3yr",
            "direction": "direction_3yr",
        }
    )

    comparison = pd.merge(
        one,
        three,
        on="feature",
        how="outer",
    )

    max_rank = comparison[["rank_1yr", "rank_3yr"]].max().max()

    if pd.isna(max_rank):
        max_rank = 0

    # Features absent in one model receive rank = number_of_features + 1.
    # This makes rank shift interpretable without pretending the feature
    # actually appeared in the missing model.
    n1 = len(one)
    n3 = len(three)

    comparison["rank_1yr_filled"] = comparison["rank_1yr"].fillna(n1 + 1)
    comparison["rank_3yr_filled"] = comparison["rank_3yr"].fillna(n3 + 1)

    comparison["rank_shift_3yr_minus_1yr"] = (
        comparison["rank_3yr_filled"]
        - comparison["rank_1yr_filled"]
    )

    comparison["absolute_rank_shift"] = (
        comparison["rank_shift_3yr_minus_1yr"]
        .abs()
    )

    comparison["normalized_importance_diff_3yr_minus_1yr_pct"] = (
        comparison["normalized_importance_pct_3yr"].fillna(0.0)
        - comparison["normalized_importance_pct_1yr"].fillna(0.0)
    )

    comparison["direction_agreement"] = np.select(
        [
            comparison["direction_1yr"].isna(),
            comparison["direction_3yr"].isna(),
            (
                comparison["direction_1yr"].isin(["positive", "negative"])
                & comparison["direction_3yr"].isin(["positive", "negative"])
                & (
                    comparison["direction_1yr"]
                    == comparison["direction_3yr"]
                )
            ),
        ],
        [
            "not_present_1yr_or_3yr",
            "not_present_1yr_or_3yr",
            "same",
        ],
        default="different_or_neutral",
    )

    # Average normalized importance across the two horizons
    comparison["mean_normalized_importance_pct"] = (
        comparison["normalized_importance_pct_1yr"].fillna(0.0)
        + comparison["normalized_importance_pct_3yr"].fillna(0.0)
    ) / 2.0

    comparison = comparison.sort_values(
        [
            "mean_normalized_importance_pct",
            "absolute_rank_shift",
        ],
        ascending=[False, False],
    ).reset_index(drop=True)

    comparison.to_csv(
        XAI_ROOT / "cross_horizon_shap_comparison.csv",
        index=False,
    )

    # Rank correlation on features present in BOTH models
    common = comparison[
        comparison["rank_1yr"].notna()
        & comparison["rank_3yr"].notna()
    ].copy()

    rank_corr = {
        "n_common_features": int(len(common)),
        "spearman_rho": None,
        "p_value": None,
    }

    if SCIPY_AVAILABLE and len(common) >= 3:
        rho, p = spearmanr(
            common["rank_1yr"],
            common["rank_3yr"],
        )

        rank_corr["spearman_rho"] = float(rho)
        rank_corr["p_value"] = float(p)

    with open(
        XAI_ROOT / "cross_horizon_rank_correlation.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            rank_corr,
            f,
            indent=4,
        )

    # --------------------------------------------------------------------------
    # Heatmap: normalized importance for top cross-horizon features
    # --------------------------------------------------------------------------
    top_features = (
        comparison
        .head(TOP_COMPARISON)["feature"]
        .tolist()
    )

    heatmap_df = (
        comparison[
            comparison["feature"].isin(top_features)
        ]
        .set_index("feature")[
            [
                "normalized_importance_pct_1yr",
                "normalized_importance_pct_3yr",
            ]
        ]
        .fillna(0.0)
    )

    # Keep descending overall importance order
    heatmap_df = heatmap_df.reindex(top_features)

    plt.figure(
        figsize=(8, max(6, 0.35 * len(heatmap_df)))
    )

    sns.heatmap(
        heatmap_df,
        annot=True,
        fmt=".2f",
        linewidths=0.5,
        cbar_kws={"label": "Normalized mean |SHAP| (%)"},
    )

    plt.xlabel("Horizon")
    plt.ylabel("Feature")
    plt.title(
        "Cross-Horizon SHAP Importance\n"
        "Normalized mean absolute SHAP"
    )

    plt.tight_layout()

    heatmap_path = (
        XAI_ROOT
        / "cross_horizon_shap_heatmap.png"
    )

    plt.savefig(
        heatmap_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    # --------------------------------------------------------------------------
    # Rank-shift table limited to common features
    # --------------------------------------------------------------------------
    rank_shift = (
        comparison[
            comparison["rank_1yr"].notna()
            & comparison["rank_3yr"].notna()
        ]
        [
            [
                "feature",
                "rank_1yr",
                "rank_3yr",
                "rank_shift_3yr_minus_1yr",
                "absolute_rank_shift",
                "normalized_importance_pct_1yr",
                "normalized_importance_pct_3yr",
                "direction_1yr",
                "direction_3yr",
                "direction_agreement",
            ]
        ]
        .sort_values(
            "absolute_rank_shift",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    rank_shift.to_csv(
        XAI_ROOT / "cross_horizon_rank_shift.csv",
        index=False,
    )

    # --------------------------------------------------------------------------
    # Human-readable summary
    # --------------------------------------------------------------------------
    with open(
        XAI_ROOT / "cross_horizon_summary.txt",
        "w",
        encoding="utf-8",
    ) as f:
        f.write("CROSS-HORIZON SHAP SUMMARY\n")
        f.write("=" * 80 + "\n\n")
        f.write("1-year model: XGBoost / S2_BALANCED\n")
        f.write("3-year model: LightGBM / S3_THRESHOLD\n\n")
        f.write(
            f"Common features: {len(common):,}\n"
        )

        if rank_corr["spearman_rho"] is not None:
            f.write(
                f"Spearman rank correlation: "
                f"{rank_corr['spearman_rho']:.6f}\n"
            )
            f.write(
                f"Spearman p-value: "
                f"{rank_corr['p_value']:.6e}\n"
            )
        else:
            f.write(
                "Spearman rank correlation: unavailable\n"
            )

        f.write("\nLargest absolute rank shifts among common features:\n")
        f.write("-" * 80 + "\n")

        f.write(
            rank_shift.head(20).to_string(
                index=False
            )
        )
        f.write("\n")

    print(f"\nSaved: {XAI_ROOT / 'cross_horizon_shap_comparison.csv'}")
    print(f"Saved: {XAI_ROOT / 'cross_horizon_rank_shift.csv'}")
    print(f"Saved: {heatmap_path}")

    if rank_corr["spearman_rho"] is not None:
        print(
            f"Cross-horizon Spearman rho = "
            f"{rank_corr['spearman_rho']:.6f}"
        )

    return comparison, rank_corr


# ==============================================================================
# 17. MAIN
# ==============================================================================

if __name__ == "__main__":

    print("\n")
    print("=" * 100)
    print("SEGMENT 7 — XAI ANALYSIS")
    print("=" * 100)
    print("1-year : XGBoost / S2_BALANCED")
    print("3-year : LightGBM / S3_THRESHOLD")
    print("=" * 100)

    if THRESHOLD_OVERRIDE["3yr"] is None:
        raise ValueError(
            "\nSTOP: THRESHOLD_OVERRIDE['3yr'] is None.\n"
            "Insert the exact 3-year S3_THRESHOLD operating threshold "
            "used by Segment 6 before running the analysis."
        )

    XAI_RESULTS = {}

    for horizon in ("1yr", "3yr"):
        XAI_RESULTS[horizon] = run_horizon(horizon)

    # Cross-horizon comparison
    CROSS_HORIZON_COMPARISON, RANK_CORRELATION = (
        build_cross_horizon_comparison(
            XAI_RESULTS
        )
    )

    print("\n")
    print("=" * 100)
    print("SEGMENT 7 COMPLETED SUCCESSFULLY")
    print("=" * 100)
    print(f"XAI output root: {XAI_ROOT}")
    print("\nKey outputs:")
    print("  1yr/")
    print("     shap_global_importance.csv")
    print("     shap_directionality.csv")
    print("     shap_global_bar.png")
    print("     shap_beeswarm.png")
    print("     dependence/")
    print("     waterfall_TP/TN/FP/FN.png where available")
    print("     LIME/")
    print("     selected_TP_TN_FP_FN_cases.csv")
    print("     shap_values_raw.npy")
    print("     X_test_model_order.parquet")
    print("     xai_metadata.json")
    print("  3yr/")
    print("     same artifact structure")
    print("  Root:")
    print("     cross_horizon_shap_comparison.csv")
    print("     cross_horizon_rank_shift.csv")
    print("     cross_horizon_rank_correlation.json")
    print("     cross_horizon_shap_heatmap.png")
    print("     cross_horizon_summary.txt")

#Segment 7

In [ ]:
# ==============================================================================
# SEGMENT 7 — INTERPRETABILITY FRAMEWORK
# ==============================================================================
#
# PURPOSE
# -------
# Reloads Segment 6 artifacts from Google Drive and performs:
#
#   Phase A — Load model + data
#   Phase B — Global SHAP analysis
#       * SHAP beeswarm
#       * SHAP bar ranking
#       * train/test-independent global explanation on held-out test data
#       * cross-horizon SHAP comparison
#       * bootstrap SHAP rank stability
#
#   Phase C — SHAP case studies
#       * TP / FP / FN / TN
#       * waterfall explanations
#
#   Phase D — LIME case studies
#       * TP / FP / FN / TN
#
#   Phase E — PDP + ICE
#       * top-5 SHAP features
#       * optional ischemic-time × HLA 2D PDP
#
#   Phase F — SHAP-guided iterative pruning
#       * INTERNAL validation only for pruning decisions
#       * SHAP-guided removal
#       * RFE comparison
#       * random-removal comparison
#       * FINAL evaluation on held-out temporal test set
#
#   Phase G — Clinical threshold analysis
#       * descriptive threshold metrics
#       * sensitivity-specificity crossing
#
#
# IMPORTANT METHODOLOGICAL RULE
# -----------------------------
# The temporal X_test/y_test remains the final external evaluation cohort.
# SHAP explanation itself may be computed on X_test after model training.
#
# SHAP-guided PRUNING does NOT use X_test to decide the subset.
# Pruning decisions are made using an internal validation split of X_train.
# The selected subset is then refit on the complete X_train and evaluated ONCE
# on X_test.
#
# ==============================================================================


# ==============================================================================
# 0. IMPORTS
# ==============================================================================

from pathlib import Path
import warnings
import pickle
import copy
import re

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from scipy.special import expit

from sklearn.base import clone
from sklearn.metrics import (
    roc_auc_score,
    roc_curve,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    balanced_accuracy_score
)
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.inspection import PartialDependenceDisplay

import shap


# ------------------------------------------------------------------------------
# LIME
# ------------------------------------------------------------------------------
#
# If not installed in Colab, run separately:
#
# !pip install -q lime
#
# ------------------------------------------------------------------------------

try:
    from lime.lime_tabular import LimeTabularExplainer
except ImportError as exc:
    raise ImportError(
        "LIME is not installed. Run:\n"
        "!pip install -q lime\n"
        "then rerun Segment 7."
    ) from exc


# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

MODEL_READY_ROOT = (
    BASE / "model_ready"
)

MODELS_ROOT = (
    BASE / "models"
)

RESULTS_ROOT = (
    BASE / "results"
)

XAI_ROOT = (
    RESULTS_ROOT / "interpretability"
)

FIG_DIR = (
    XAI_ROOT / "figures"
)

TABLE_DIR = (
    XAI_ROOT / "tables"
)

CASE_DIR = (
    XAI_ROOT / "case_studies"
)

PRUNING_DIR = (
    XAI_ROOT / "pruning"
)


for directory in [
    XAI_ROOT,
    FIG_DIR,
    TABLE_DIR,
    CASE_DIR,
    PRUNING_DIR
]:

    directory.mkdir(
        parents=True,
        exist_ok=True
    )


# ==============================================================================
# HORIZONS
# ==============================================================================

HORIZONS = [

    "3yr"
]


# ==============================================================================
# MODEL SELECTION
# ==============================================================================
#
# AUTO_BEST_TREE_SINGLE:
#     Select highest-AUROC non-ensemble tree model from all_metrics.csv.
#
# FIXED:
#     Use MODEL_NAME and STRATEGY exactly as specified.
#
# For final publication, once your model is locked, FIXED is preferable because
# it prevents accidental selection changes if all_metrics is regenerated.
# ==============================================================================

MODEL_SELECTION_MODE = "AUTO_BEST_TREE_SINGLE"


XAI_MODEL_CONFIG = {

    "1yr": {
        "mode": "AUTO_BEST_TREE_SINGLE",
        "model": None,
        "strategy": None,
    },

    "3yr": {
        "mode": "AUTO_BEST_TREE_SINGLE",
        "model": None,
        "strategy": None,
    }
}


TREE_MODEL_NAMES = {
    "randomforest",
    "randomforestclassifier",
    "lightgbm",
    "lgbm",
    "xgboost",
    "xgb",
    "adaboost",
    "adaboostclassifier",
    "catboost",
    "catboostclassifier"
}


# ==============================================================================
# SHAP SETTINGS
# ==============================================================================

SHAP_BACKGROUND_SIZE = 200

# None = explain every X_test row.
# Example: 5000 = faster exploratory run.
SHAP_MAX_SAMPLES = None

SHAP_TOP_N = 20

SHAP_STABILITY_BOOTSTRAPS = 100

SHAP_STABILITY_SAMPLE_SIZE = 1000


# ==============================================================================
# LIME SETTINGS
# ==============================================================================

LIME_BACKGROUND_SIZE = 5000
LIME_NUM_FEATURES = 15
LIME_NUM_SAMPLES = 5000


# ==============================================================================
# CASE-STUDY THRESHOLD
# ==============================================================================
#
# "MAX_MCC_TEST"
#     Descriptive threshold derived from test predictions.
#     DO NOT use this to select/tune the predictive model.
#
# "SENS_SPEC_CROSSING"
#     Threshold where sensitivity and specificity are closest.
#
# "FIXED"
#     Use CASE_FIXED_THRESHOLD.
#
# ==============================================================================

CASE_THRESHOLD_MODE = "MAX_MCC_TEST"
CASE_FIXED_THRESHOLD = 0.50


# ==============================================================================
# PDP / ICE
# ==============================================================================

PDP_ICE_SUBSAMPLE = 1000
PDP_GRID_RESOLUTION = 20

HLA_CANDIDATES = [
    "HLA_total_mismatch_weighted",
    "HLAMIS",
    "HLA_MISMATCH",
    "HLA_total_mismatch"
]

ISCHTIME_CANDIDATES = [
    "ISCHTIME",
    "ischemic_time"
]


# ==============================================================================
# SHAP GUIDED PRUNING
# ==============================================================================

RUN_SHAP_PRUNING = True

PRUNING_STEP = 5

PRUNING_DELTA = 0.01

PRUNING_MIN_FEATURES = 10

PRUNING_VALIDATION_SIZE = 0.20

PRUNING_RANDOM_STATE = 42

PRUNING_SHAP_BACKGROUND_SIZE = 100

PRUNING_SHAP_SAMPLES = 1000

RANDOM_BASELINE_REPEATS = 10

RANDOM_BASELINE_SEED = 42


# ==============================================================================
# CPU SAFETY FOR REFITTING
# ==============================================================================

# If a serialized model was originally trained with GPU parameters, pruning
# refits on a CPU-only runtime can fail. This flag changes only the device
# setting; model hyperparameters remain otherwise unchanged.
FORCE_CPU_FOR_PRUNING = True


# ==============================================================================
# 2. BASIC HELPERS
# ==============================================================================

def normalize_name(value):
    """
    Normalize a model/strategy name for robust filesystem matching.
    """

    return re.sub(
        r"[^a-z0-9]+",
        "",
        str(value).lower()
    )


def load_dataframe(path):
    """
    Load a Parquet dataframe with an existence check.
    """

    path = Path(path)

    if not path.exists():

        raise FileNotFoundError(
            f"Required file does not exist:\n{path}"
        )

    return pd.read_parquet(
        path,
        engine="pyarrow"
    )


def load_target(path):
    """
    Load y dataframe and return a 1D integer numpy array.
    """

    df = load_dataframe(path)

    if df.shape[1] == 0:

        raise ValueError(
            f"Target file contains no columns:\n{path}"
        )

    # Segment 6 generally saves y under column 'y'.
    if "y" in df.columns:

        y = df["y"]

    else:

        y = df.iloc[:, 0]

    return (
        pd.to_numeric(
            y,
            errors="raise"
        )
        .astype(int)
        .to_numpy()
    )


def predict_probability(
    model,
    X
):
    """
    Unified positive-class probability.
    """

    if hasattr(
        model,
        "predict_proba"
    ):

        prob = model.predict_proba(X)

        prob = np.asarray(prob)

        if prob.ndim == 2:

            if prob.shape[1] == 1:

                return prob[:, 0]

            return prob[:, 1]

        return prob.reshape(-1)


    if hasattr(
        model,
        "decision_function"
    ):

        score = np.asarray(
            model.decision_function(X)
        )

        return expit(score)


    pred = np.asarray(
        model.predict(X)
    )

    return pred.astype(float)


def unwrap_model(obj):
    """
    Handle common serialized structures:
        estimator
        {'model': estimator}
        {'estimator': estimator}
    """

    if hasattr(
        obj,
        "predict_proba"
    ) or hasattr(
        obj,
        "predict"
    ):

        return obj


    if isinstance(
        obj,
        dict
    ):

        for key in [
            "model",
            "estimator",
            "classifier",
            "best_model"
        ]:

            if key in obj:

                candidate = obj[key]

                if (
                    hasattr(candidate, "predict")
                    or hasattr(candidate, "predict_proba")
                ):

                    return candidate


    raise TypeError(
        "Serialized artifact does not contain a recognizable fitted model."
    )


def find_model_file(
    horizon,
    model_name,
    strategy
):
    """
    Search models/{horizon} recursively for the fitted model corresponding
    to model_name + strategy.
    """

    model_dir = (
        MODELS_ROOT / horizon
    )

    if not model_dir.exists():

        raise FileNotFoundError(
            f"Model directory does not exist:\n{model_dir}"
        )


    model_norm = normalize_name(
        model_name
    )

    strategy_norm = normalize_name(
        strategy
    )


    candidates = []


    allowed_suffixes = {
        ".pkl",
        ".pickle",
        ".joblib"
    }


    for path in model_dir.rglob("*"):

        if (
            not path.is_file()
            or path.suffix.lower()
            not in allowed_suffixes
        ):

            continue


        stem_norm = normalize_name(
            path.stem
        )


        if (
            model_norm in stem_norm
            and strategy_norm in stem_norm
        ):

            candidates.append(path)


    # Fallback: model only
    if not candidates:

        for path in model_dir.rglob("*"):

            if (
                not path.is_file()
                or path.suffix.lower()
                not in allowed_suffixes
            ):

                continue


            stem_norm = normalize_name(
                path.stem
            )


            if model_norm in stem_norm:

                candidates.append(path)


    if not candidates:

        raise FileNotFoundError(
            "Could not locate a serialized fitted model for:\n"
            f"  horizon  = {horizon}\n"
            f"  model    = {model_name}\n"
            f"  strategy = {strategy}\n"
            f"  searched = {model_dir}"
        )


    # Prefer files whose names contain the strategy.
    candidates.sort(
        key=lambda p: (
            strategy_norm not in normalize_name(p.stem),
            len(p.name)
        )
    )

    return candidates[0]


def load_serialized_model(path):
    """
    Load pickle/joblib model.
    """

    path = Path(path)


    try:

        import joblib

        obj = joblib.load(path)

        return unwrap_model(obj)

    except Exception:

        with open(
            path,
            "rb"
        ) as f:

            obj = pickle.load(f)

        return unwrap_model(obj)


def has_tree_model_name(
    model_name
):
    return (
        normalize_name(model_name)
        in TREE_MODEL_NAMES
    )


# ==============================================================================
# 3. SELECT XAI MODEL
# ==============================================================================

def select_xai_model(
    horizon
):

    results_dir = (
        RESULTS_ROOT / horizon
    )

    metrics_path = (
        results_dir / "all_metrics.csv"
    )


    config = XAI_MODEL_CONFIG[
        horizon
    ]


    mode = config.get(
        "mode",
        MODEL_SELECTION_MODE
    )


    # --------------------------------------------------------------------------
    # FIXED MODEL
    # --------------------------------------------------------------------------

    if mode.upper() == "FIXED":

        model_name = config.get(
            "model"
        )

        strategy = config.get(
            "strategy"
        )


        if not model_name or not strategy:

            raise ValueError(
                f"{horizon}: FIXED mode requires "
                "'model' and 'strategy'."
            )


        metrics = pd.read_csv(
            metrics_path
        )


        row = metrics.loc[
            (
                metrics["model"]
                .astype(str)
                == str(model_name)
            )
            &
            (
                metrics["strategy"]
                .astype(str)
                == str(strategy)
            )
        ]


        if row.empty:

            raise ValueError(
                f"{horizon}: fixed model/strategy not found "
                f"in {metrics_path}"
            )


        selected = row.iloc[0]


    # --------------------------------------------------------------------------
    # AUTO BEST TREE SINGLE
    # --------------------------------------------------------------------------

    else:

        metrics = pd.read_csv(
            metrics_path
        )


        metrics = metrics.copy()


        metrics["auroc"] = pd.to_numeric(
            metrics["auroc"],
            errors="coerce"
        )


        metrics = metrics.loc[
            metrics["auroc"].notna()
        ].copy()


        # Exclude ensembles
        metrics = metrics.loc[
            ~metrics["model"]
            .astype(str)
            .str.startswith(
                "Ensemble",
                na=False
            )
        ].copy()


        # Keep tree models
        metrics = metrics.loc[
            metrics["model"]
            .map(has_tree_model_name)
        ].copy()


        if metrics.empty:

            raise ValueError(
                f"{horizon}: no tree-based single model "
                f"found in {metrics_path}"
            )


        selected = (
            metrics
            .sort_values(
                "auroc",
                ascending=False
            )
            .iloc[0]
        )


        model_name = selected["model"]
        strategy = selected["strategy"]


    model_name = str(
        selected["model"]
    )

    strategy = str(
        selected["strategy"]
    )

    model_path = find_model_file(
        horizon,
        model_name,
        strategy
    )

    model = load_serialized_model(
        model_path
    )


    return {
        "model_name": model_name,
        "strategy": strategy,
        "auroc": float(
            selected["auroc"]
        ),
        "model_path": model_path,
        "model": model
    }


# ==============================================================================
# 4. LOAD HORIZON ARTIFACTS
# ==============================================================================

def load_horizon_artifacts(
    horizon
):

    model_ready_dir = (
        MODEL_READY_ROOT / horizon
    )

    results_dir = (
        RESULTS_ROOT / horizon
    )


    x_train_path = (
        model_ready_dir
        / "X_train_tree.parquet"
    )

    x_test_path = (
        model_ready_dir
        / "X_test_tree.parquet"
    )

    y_train_path = (
        model_ready_dir
        / "y_train.parquet"
    )

    y_test_path = (
        model_ready_dir
        / "y_test.parquet"
    )


    X_train = load_dataframe(
        x_train_path
    )

    X_test = load_dataframe(
        x_test_path
    )

    y_train = load_target(
        y_train_path
    )

    y_test = load_target(
        y_test_path
    )


    xai_model = select_xai_model(
        horizon
    )

    model = xai_model["model"]


    # --------------------------------------------------------------------------
    # Feature alignment
    # --------------------------------------------------------------------------

    if hasattr(
        model,
        "feature_names_in_"
    ):

        model_features = list(
            model.feature_names_in_
        )

        missing = [
            c
            for c in model_features
            if c not in X_test.columns
        ]

        extra = [
            c
            for c in X_test.columns
            if c not in model_features
        ]


        if missing:

            raise ValueError(
                f"{horizon}: model expects features missing "
                f"from X_test:\n{missing[:20]}"
            )


        # Reorder to model order.
        X_train = X_train[
            model_features
        ].copy()

        X_test = X_test[
            model_features
        ].copy()


    else:

        if X_train.shape[1] != X_test.shape[1]:

            raise ValueError(
                f"{horizon}: train/test feature counts differ."
            )


    # --------------------------------------------------------------------------
    # Explicit Segment 6 prediction file
    # --------------------------------------------------------------------------

    prediction_path = PREDICTION_FILES.get(
        horizon
    )

    if prediction_path is not None:

        prediction_path = Path(
            prediction_path
        )

        if not prediction_path.exists():

            raise FileNotFoundError(
                f"{horizon}: explicitly specified prediction file does not exist:\n"
                f"{prediction_path}"
            )

        pred_df = pd.read_csv(
            prediction_path
        )

        if "y_prob" not in pred_df.columns:

            raise ValueError(
                f"{horizon}: prediction file must contain a 'y_prob' column:\n"
                f"{prediction_path}"
            )

        y_prob = pred_df[
            "y_prob"
        ].to_numpy()

        print(
            f"  ✓ Prediction file loaded directly:"
            f"\n    {prediction_path}"
        )

    else:

        # Fallback: calculate predictions from the loaded model.
        y_prob = predict_probability(
            model,
            X_test
        )

        print(
            "  ✓ No explicit prediction file configured; "
            "predictions generated from loaded model."
        )

        # --------------------------------------------------------------------------
    # Return all horizon artifacts
    # --------------------------------------------------------------------------

    return {
        "horizon": horizon,

        "model_name":
            xai_model["model_name"],

        "strategy":
            xai_model["strategy"],

        "segment6_auroc":
            xai_model["auroc"],

        "model_path":
            xai_model["model_path"],

        "model":
            model,

        "X_train":
            X_train,

        "X_test":
            X_test,

        "y_train":
            y_train,

        "y_test":
            y_test,

        "y_prob":
            y_prob
    }

# ==============================================================================
# 5. SHAP HELPERS
# ==============================================================================

def choose_shap_samples(
    X,
    max_samples,
    random_state=42
):

    if (
        max_samples is None
        or len(X) <= max_samples
    ):

        return X.copy()


    return X.sample(
        n=max_samples,
        random_state=random_state
    ).copy()


def build_tree_shap_explainer(
    model,
    background
):
    """
    Prefer probability-scale SHAP using interventional Tree SHAP.
    Fall back to raw-output Tree SHAP if a model does not support
    probability-scale output.
    """

    try:

        explainer = shap.TreeExplainer(
            model,
            data=background,
            feature_perturbation="interventional",
            model_output="probability"
        )

        return (
            explainer,
            "probability"
        )

    except Exception as first_error:

        warnings.warn(
            "Probability-scale Tree SHAP could not be initialized. "
            "Falling back to raw model-output SHAP.\n"
            f"Reason: {first_error}"
        )


        explainer = shap.TreeExplainer(
            model
        )

        return (
            explainer,
            "raw"
        )


def compute_tree_shap(
    model,
    X,
    background_size=200,
    max_samples=None
):

    X_explain = choose_shap_samples(
        X,
        max_samples=max_samples
    )


    if (
        background_size is not None
        and len(X) > background_size
    ):

        background = X.sample(
            n=background_size,
            random_state=42
        )

    else:

        background = X.copy()


    explainer, output_scale = (
        build_tree_shap_explainer(
            model,
            background
        )
    )


    try:

        explanation = explainer(
            X_explain,
            check_additivity=False
        )

    except TypeError:

        explanation = explainer(
            X_explain
        )


    shap_values = np.asarray(
        explanation.values
    )


    # Binary-class compatibility
    if shap_values.ndim == 3:

        if shap_values.shape[2] >= 2:

            shap_values = shap_values[:, :, 1]

        else:

            shap_values = shap_values[:, :, 0]


    if shap_values.ndim != 2:

        raise ValueError(
            f"Unexpected SHAP value shape: "
            f"{shap_values.shape}"
        )


    return {
        "X": X_explain,
        "background": background,
        "explainer": explainer,
        "explanation": explanation,
        "values": shap_values,
        "output_scale": output_scale
    }


def make_shap_ranking(
    shap_values,
    feature_names
):

    mean_abs = (
        np.abs(shap_values)
        .mean(
            axis=0
        )
    )


    ranking = pd.DataFrame(
        {
            "feature": feature_names,
            "mean_abs_shap": mean_abs
        }
    )


    ranking = (
        ranking
        .sort_values(
            "mean_abs_shap",
            ascending=False
        )
        .reset_index(
            drop=True
        )
    )


    ranking["rank"] = (
        np.arange(
            1,
            len(ranking) + 1
        )
    )


    return ranking


# ==============================================================================
# 6. GLOBAL SHAP ANALYSIS
# ==============================================================================

def global_shap_analysis(
    artifacts
):

    horizon = artifacts["horizon"]

    model = artifacts["model"]

    X_test = artifacts["X_test"]


    print(
        "\n"
        + "=" * 70
    )

    print(
        f"GLOBAL SHAP ANALYSIS — {horizon.upper()}"
    )

    print(
        "=" * 70
    )


    print(
        f"  Model: "
        f"{artifacts['model_name']}/"
        f"{artifacts['strategy']}"
    )


    print(
        f"  Test patients available: "
        f"{len(X_test):,}"
    )


    print(
        f"  Test features: "
        f"{X_test.shape[1]:,}"
    )


    print(
        "  Computing SHAP values..."
    )


    shap_result = compute_tree_shap(
        model=model,
        X=X_test,
        background_size=SHAP_BACKGROUND_SIZE,
        max_samples=SHAP_MAX_SAMPLES
    )


    X_shap = shap_result["X"]

    shap_values = shap_result["values"]

    ranking = make_shap_ranking(
        shap_values,
        X_shap.columns
    )


    print(
        f"  ✓ SHAP values computed. "
        f"Shape: {shap_values.shape}"
    )


    # --------------------------------------------------------------------------
    # Save raw SHAP values
    # --------------------------------------------------------------------------

    shap_values_df = pd.DataFrame(
        shap_values,
        columns=X_shap.columns
    )

    shap_values_df.to_parquet(
        TABLE_DIR
        / f"shap_values_{horizon}.parquet",
        engine="pyarrow"
    )


    # --------------------------------------------------------------------------
    # Ranking
    # --------------------------------------------------------------------------

    ranking.to_csv(
        TABLE_DIR
        / f"shap_ranking_{horizon}.csv",
        index=False
    )


    print(
        f"\n  Top {min(10, len(ranking))} features:"
    )


    for _, row in ranking.head(10).iterrows():

        print(
            f"     {int(row['rank']):2d}. "
            f"{row['feature']:<45} "
            f"mean|SHAP| = "
            f"{row['mean_abs_shap']:.4f}"
        )


    # --------------------------------------------------------------------------
    # Beeswarm
    # --------------------------------------------------------------------------

    plt.figure(
        figsize=(10, 8)
    )

    shap.summary_plot(
        shap_values,
        X_shap,
        max_display=SHAP_TOP_N,
        show=False
    )

    plt.title(
        f"Global SHAP Summary — {horizon.upper()}"
    )

    plt.tight_layout()


    beeswarm_path = (
        FIG_DIR
        / f"shap_beeswarm_{horizon}.png"
    )


    plt.savefig(
        beeswarm_path,
        dpi=180,
        bbox_inches="tight"
    )

    plt.close()


    print(
        f"  ✓ Beeswarm saved → "
        f"{beeswarm_path}"
    )


    # --------------------------------------------------------------------------
    # Bar ranking
    # --------------------------------------------------------------------------

    plt.figure(
        figsize=(9, 8)
    )

    shap.summary_plot(
        shap_values,
        X_shap,
        plot_type="bar",
        max_display=SHAP_TOP_N,
        show=False
    )

    plt.title(
        f"Global SHAP Importance — {horizon.upper()}"
    )

    plt.tight_layout()


    bar_path = (
        FIG_DIR
        / f"shap_bar_{horizon}.png"
    )


    plt.savefig(
        bar_path,
        dpi=180,
        bbox_inches="tight"
    )

    plt.close()


    print(
        f"  ✓ Bar plot saved → "
        f"{bar_path}"
    )


    # --------------------------------------------------------------------------
    # Save stability-ready object
    # --------------------------------------------------------------------------

    return {
        "shap": shap_result,
        "ranking": ranking
    }


# ==============================================================================
# 7. BOOTSTRAP SHAP RANK STABILITY
# ==============================================================================

def shap_rank_stability(
    global_result,
    horizon
):

    shap_values = (
        global_result["shap"]["values"]
    )

    features = (
        global_result["shap"]["X"].columns.tolist()
    )


    n = len(shap_values)

    sample_size = min(
        SHAP_STABILITY_SAMPLE_SIZE,
        n
    )


    records = []


    for b in range(
        SHAP_STABILITY_BOOTSTRAPS
    ):

        rng = np.random.default_rng(
            1000 + b
        )


        idx = rng.choice(
            n,
            size=sample_size,
            replace=True
        )


        mean_abs = (
            np.abs(
                shap_values[idx]
            )
            .mean(
                axis=0
            )
        )


        order = np.argsort(
            -mean_abs
        )


        rank_vector = np.empty(
            len(features),
            dtype=int
        )


        rank_vector[
            order
        ] = np.arange(
            1,
            len(features) + 1
        )


        for j, feature in enumerate(
            features
        ):

            records.append(
                {
                    "bootstrap": b,
                    "feature": feature,
                    "rank": int(
                        rank_vector[j]
                    ),
                    "mean_abs_shap":
                        float(mean_abs[j])
                }
            )


    stability_raw = pd.DataFrame(
        records
    )


    stability = (
        stability_raw
        .groupby(
            "feature"
        )
        .agg(
            mean_rank=(
                "rank",
                "mean"
            ),
            sd_rank=(
                "rank",
                "std"
            ),
            median_rank=(
                "rank",
                "median"
            ),
            min_rank=(
                "rank",
                "min"
            ),
            max_rank=(
                "rank",
                "max"
            ),
            mean_abs_shap=(
                "mean_abs_shap",
                "mean"
            )
        )
        .reset_index()
    )


    # Frequency of appearing in top 10
    top10_counts = (
        stability_raw
        .assign(
            top10=lambda d:
                d["rank"] <= 10
        )
        .groupby(
            "feature"
        )["top10"]
        .mean()
        .reset_index(
            name="top10_frequency"
        )
    )


    stability = stability.merge(
        top10_counts,
        on="feature",
        how="left"
    )


    stability = (
        stability
        .sort_values(
            [
                "mean_rank",
                "sd_rank"
            ],
            ascending=[
                True,
                True
            ]
        )
        .reset_index(drop=True)
    )


    stability.to_csv(
        TABLE_DIR
        / f"shap_rank_stability_{horizon}.csv",
        index=False
    )


    return stability


# ==============================================================================
# 8. CROSS-HORIZON SHAP COMPARISON
# ==============================================================================

def cross_horizon_comparison(
    result_1y,
    result_3y
):

    r1 = (
        result_1y["ranking"]
        .rename(
            columns={
                "rank": "rank_1yr",
                "mean_abs_shap":
                    "mean_abs_shap_1yr"
            }
        )
    )


    r3 = (
        result_3y["ranking"]
        .rename(
            columns={
                "rank": "rank_3yr",
                "mean_abs_shap":
                    "mean_abs_shap_3yr"
            }
        )
    )


    comparison = r1[
        [
            "feature",
            "rank_1yr",
            "mean_abs_shap_1yr"
        ]
    ].merge(
        r3[
            [
                "feature",
                "rank_3yr",
                "mean_abs_shap_3yr"
            ]
        ],
        on="feature",
        how="outer"
    )


    comparison["rank_shift_1yr_to_3yr"] = (
        comparison["rank_1yr"]
        - comparison["rank_3yr"]
    )


    comparison["absolute_rank_shift"] = (
        comparison[
            "rank_shift_1yr_to_3yr"
        ].abs()
    )


    comparison = comparison.sort_values(
        "absolute_rank_shift",
        ascending=False
    )


    comparison.to_csv(
        TABLE_DIR
        / "shap_cross_horizon_comparison.csv",
        index=False
    )


    # --------------------------------------------------------------------------
    # Plot common features by rank
    # --------------------------------------------------------------------------

    common = comparison.dropna(
        subset=[
            "rank_1yr",
            "rank_3yr"
        ]
    ).copy()


    if not common.empty:

        plot_df = common.head(30)


        plt.figure(
            figsize=(8, 8)
        )


        plt.scatter(
            plot_df["rank_1yr"],
            plot_df["rank_3yr"]
        )


        max_rank = max(
            plot_df["rank_1yr"].max(),
            plot_df["rank_3yr"].max()
        )


        plt.plot(
            [1, max_rank],
            [1, max_rank],
            linestyle="--",
            linewidth=1
        )


        for _, row in plot_df.head(15).iterrows():

            plt.annotate(
                row["feature"],
                (
                    row["rank_1yr"],
                    row["rank_3yr"]
                ),
                fontsize=7
            )


        plt.xlabel(
            "1-year SHAP rank"
        )

        plt.ylabel(
            "3-year SHAP rank"
        )

        plt.title(
            "Cross-Horizon SHAP Rank Comparison"
        )

        plt.tight_layout()


        path = (
            FIG_DIR
            / "shap_cross_horizon_comparison.png"
        )


        plt.savefig(
            path,
            dpi=180,
            bbox_inches="tight"
        )

        plt.close()


    # --------------------------------------------------------------------------
    # Print rank shifts
    # --------------------------------------------------------------------------

    print(
        "\n"
        + "-" * 80
    )

    print(
        "TOP 10 CROSS-HORIZON SHAP RANK SHIFTS"
    )

    print(
        "-" * 80
    )


    for _, row in (
        common
        .sort_values(
            "absolute_rank_shift",
            ascending=False
        )
        .head(10)
        .iterrows()
    ):

        shift = row[
            "rank_shift_1yr_to_3yr"
        ]


        direction = (
            "↑"
            if shift > 0
            else "↓"
            if shift < 0
            else "="
        )


        print(
            f"  {row['feature']:<45} "
            f"rank {int(row['rank_1yr']):3d} → "
            f"{int(row['rank_3yr']):3d} "
            f"{direction} "
            f"{abs(shift):.0f}"
        )


    return comparison


# ==============================================================================
# 9. THRESHOLD ANALYSIS
# ==============================================================================

def threshold_metrics(
    y_true,
    y_prob,
    thresholds
):

    rows = []


    for threshold in thresholds:

        pred = (
            y_prob >= threshold
        ).astype(int)


        tn, fp, fn, tp = (
            confusion_matrix(
                y_true,
                pred,
                labels=[0, 1]
            )
            .ravel()
        )


        sensitivity = (
            tp / (tp + fn)
            if (tp + fn) > 0
            else np.nan
        )


        specificity = (
            tn / (tn + fp)
            if (tn + fp) > 0
            else np.nan
        )


        ppv = (
            tp / (tp + fp)
            if (tp + fp) > 0
            else np.nan
        )


        npv = (
            tn / (tn + fn)
            if (tn + fn) > 0
            else np.nan
        )


        precision = (
            precision_score(
                y_true,
                pred,
                zero_division=0
            )
        )


        recall = (
            recall_score(
                y_true,
                pred,
                zero_division=0
            )
        )


        f1 = (
            f1_score(
                y_true,
                pred,
                zero_division=0
            )
        )


        mcc = (
            matthews_corrcoef(
                y_true,
                pred
            )
        )


        rows.append(
            {
                "threshold": threshold,
                "sensitivity": sensitivity,
                "specificity": specificity,
                "ppv": ppv,
                "npv": npv,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "mcc": mcc
            }
        )


    return pd.DataFrame(
        rows
    )


def select_descriptive_threshold(
    y_true,
    y_prob
):

    thresholds = np.arange(
        0.01,
        0.991,
        0.001
    )


    metrics = threshold_metrics(
        y_true,
        y_prob,
        thresholds
    )


    if CASE_THRESHOLD_MODE == "FIXED":

        threshold = (
            CASE_FIXED_THRESHOLD
        )

        return (
            threshold,
            metrics
        )


    if (
        CASE_THRESHOLD_MODE
        == "SENS_SPEC_CROSSING"
    ):

        metrics["distance"] = (
            (
                metrics["sensitivity"]
                -
                metrics["specificity"]
            )
            .abs()
        )


        row = (
            metrics
            .sort_values(
                [
                    "distance",
                    "threshold"
                ]
            )
            .iloc[0]
        )


    else:

        # MAX_MCC_TEST
        row = (
            metrics
            .sort_values(
                [
                    "mcc",
                    "threshold"
                ],
                ascending=[
                    False,
                    True
                ]
            )
            .iloc[0]
        )


    return (
        float(row["threshold"]),
        metrics
    )


def plot_threshold_analysis(
    metrics,
    horizon
):

    plt.figure(
        figsize=(8, 6)
    )


    plt.plot(
        metrics["threshold"],
        metrics["sensitivity"],
        label="Sensitivity"
    )


    plt.plot(
        metrics["threshold"],
        metrics["specificity"],
        label="Specificity"
    )


    plt.plot(
        metrics["threshold"],
        metrics["ppv"],
        label="PPV"
    )


    plt.plot(
        metrics["threshold"],
        metrics["npv"],
        label="NPV"
    )


    plt.xlabel(
        "Decision threshold"
    )

    plt.ylabel(
        "Metric"
    )

    plt.ylim(
        0,
        1
    )

    plt.title(
        f"Clinical Threshold Analysis — "
        f"{horizon.upper()}"
    )

    plt.legend()

    plt.tight_layout()


    path = (
        FIG_DIR
        / f"threshold_analysis_{horizon}.png"
    )


    plt.savefig(
        path,
        dpi=180,
        bbox_inches="tight"
    )

    plt.close()


    return path


# ==============================================================================
# 10. CASE-STUDY SELECTION
# ==============================================================================

def select_case_indices(
    y_true,
    y_prob,
    threshold
):

    pred = (
        y_prob >= threshold
    ).astype(int)


    tp = np.where(
        (y_true == 1)
        & (pred == 1)
    )[0]


    fp = np.where(
        (y_true == 0)
        & (pred == 1)
    )[0]


    fn = np.where(
        (y_true == 1)
        & (pred == 0)
    )[0]


    tn = np.where(
        (y_true == 0)
        & (pred == 0)
    )[0]


    cases = {}


    # Most confident examples
    if len(tp):
        cases["TP"] = int(
            tp[
                np.argmax(
                    y_prob[tp]
                )
            ]
        )
    else:
        cases["TP"] = None


    if len(fp):
        cases["FP"] = int(
            fp[
                np.argmax(
                    y_prob[fp]
                )
            ]
        )
    else:
        cases["FP"] = None


    if len(fn):
        cases["FN"] = int(
            fn[
                np.argmin(
                    y_prob[fn]
                )
            ]
        )
    else:
        cases["FN"] = None


    if len(tn):
        cases["TN"] = int(
            tn[
                np.argmin(
                    y_prob[tn]
                )
            ]
        )
    else:
        cases["TN"] = None


    return cases


# ==============================================================================
# 11. SHAP WATERFALL CASE STUDIES
# ==============================================================================

def shap_case_studies(
    artifacts,
    global_result,
    threshold
):

    horizon = artifacts["horizon"]

    X_test = artifacts["X_test"]

    y_test = artifacts["y_test"]

    y_prob = artifacts["y_prob"]

    ranking = global_result["ranking"]

    shap_result = global_result["shap"]

    X_shap = shap_result["X"]

    shap_values = shap_result["values"]


    # --------------------------------------------------------------------------
    # Important:
    # Global SHAP may be subsampled. Map back using X index.
    # --------------------------------------------------------------------------

    common_case_indices = (
        X_test.index
        .intersection(
            X_shap.index
        )
    )


    if len(common_case_indices) == 0:

        # Recompute SHAP for the entire test set so that case studies are exact.
        print(
            "  Global SHAP was subsampled; recomputing exact case-study SHAP."
        )


        exact = compute_tree_shap(
            artifacts["model"],
            X_test,
            background_size=SHAP_BACKGROUND_SIZE,
            max_samples=None
        )


        X_case_shap = exact["X"]

        case_shap_values = exact["values"]

    else:

        X_case_shap = X_shap

        case_shap_values = shap_values


    # --------------------------------------------------------------------------
    # Reset positional mapping
    # --------------------------------------------------------------------------

    X_case_shap_reset = (
        X_case_shap.reset_index(
            drop=True
        )
    )


    # If exact full X_test is available, use original positions.
    case_values = case_shap_values


    cases = select_case_indices(
        y_test,
        y_prob,
        threshold
    )


    case_rows = []


    for case_type, idx in cases.items():

        if idx is None:

            print(
                f"  No {case_type} case available."
            )

            continue


        # ----------------------------------------------------------------------
        # SHAP explanation position
        # ----------------------------------------------------------------------

        if len(X_case_shap) == len(X_test):

            shap_position = idx

        else:

            # Match original index
            original_index = X_test.index[idx]

            matches = np.where(
                X_case_shap.index
                == original_index
            )[0]

            if len(matches) == 0:

                continue

            shap_position = int(
                matches[0]
            )


        values = case_values[
            shap_position
        ]


        x_values = X_test.iloc[
            idx
        ]


        feature_df = pd.DataFrame(
            {
                "feature":
                    X_test.columns,
                "value":
                    x_values.to_numpy(),
                "shap_value":
                    values,
                "abs_shap":
                    np.abs(values)
            }
        )


        feature_df = (
            feature_df
            .sort_values(
                "abs_shap",
                ascending=False
            )
            .reset_index(drop=True)
        )


        feature_df["shap_rank"] = (
            np.arange(
                1,
                len(feature_df) + 1
            )
        )


        feature_df["case_type"] = (
            case_type
        )

        feature_df["patient_index"] = (
            idx
        )

        feature_df["predicted_probability"] = (
            y_prob[idx]
        )

        feature_df["actual"] = (
            y_test[idx]
        )

        feature_df["decision_threshold"] = (
            threshold
        )


        case_rows.append(
            feature_df
        )


        # ----------------------------------------------------------------------
        # Waterfall
        # ----------------------------------------------------------------------

        explanation = shap.Explanation(
            values=values,
            base_values=(
                0.5
            ),
            data=x_values.to_numpy(),
            feature_names=X_test.columns.tolist()
        )


        try:

            plt.figure(
                figsize=(10, 8)
            )


            shap.plots.waterfall(
                explanation,
                max_display=15,
                show=False
            )


            plt.title(
                f"{horizon.upper()} — "
                f"{case_type} case "
                f"(p={y_prob[idx]:.3f})"
            )


            plt.tight_layout()


            path = (
                FIG_DIR
                / (
                    f"shap_waterfall_"
                    f"{case_type.lower()}_"
                    f"{horizon}.png"
                )
            )


            plt.savefig(
                path,
                dpi=180,
                bbox_inches="tight"
            )

            plt.close()

        except Exception as exc:

            warnings.warn(
                f"Waterfall plot failed for "
                f"{case_type}: {exc}"
            )


        print(
            f"  {case_type}: "
            f"patient index {idx} "
            f"predicted={y_prob[idx]:.3f} "
            f"actual={y_test[idx]}"
        )


    # --------------------------------------------------------------------------
    # Combined CSV
    # --------------------------------------------------------------------------

    if case_rows:

        case_data = pd.concat(
            case_rows,
            ignore_index=True
        )


        case_data.to_csv(
            CASE_DIR
            / f"shap_case_study_data_{horizon}.csv",
            index=False
        )


    # Case summary
    summary_rows = []


    for case_type, idx in cases.items():

        if idx is None:
            continue


        predicted = (
            int(
                y_prob[idx] >= threshold
            )
        )


        summary_rows.append(
            {
                "horizon": horizon,
                "case_type": case_type,
                "patient_index": idx,
                "predicted_probability":
                    y_prob[idx],
                "threshold":
                    threshold,
                "predicted_class":
                    predicted,
                "actual_class":
                    int(y_test[idx])
            }
        )


    pd.DataFrame(
        summary_rows
    ).to_csv(
        CASE_DIR
        / f"case_summary_{horizon}.csv",
        index=False
    )


    return cases


# ==============================================================================
# 12. LIME CASE STUDIES
# ==============================================================================

def lime_case_studies(
    artifacts,
    cases,
    threshold
):

    horizon = artifacts["horizon"]

    model = artifacts["model"]

    X_train = artifacts["X_train"]

    X_test = artifacts["X_test"]

    y_test = artifacts["y_test"]

    y_prob = artifacts["y_prob"]


    print(
        "\n"
        + "-" * 80
    )

    print(
        f"LIME CASE STUDIES — {horizon.upper()}"
    )

    print(
        "-" * 80
    )


    # --------------------------------------------------------------------------
    # Background
    # --------------------------------------------------------------------------

    if len(X_train) > LIME_BACKGROUND_SIZE:

        background = (
            X_train
            .sample(
                LIME_BACKGROUND_SIZE,
                random_state=42
            )
            .to_numpy()
        )

    else:

        background = X_train.to_numpy()


    lime_explainer = LimeTabularExplainer(
        training_data=background,
        feature_names=X_train.columns.tolist(),
        class_names=[
            "No rejection",
            "Rejection"
        ],
        mode="classification",
        discretize_continuous=True,
        random_state=42
    )


    def lime_predict(
        arr
    ):

        arr_df = pd.DataFrame(
            arr,
            columns=X_train.columns
        )

        return model.predict_proba(
            arr_df
        )


    for case_type, idx in cases.items():

        if idx is None:
            continue


        instance = (
            X_test
            .iloc[idx]
            .to_numpy()
        )


        try:

            explanation = lime_explainer.explain_instance(
                instance,
                lime_predict,
                labels=[1],
                num_features=LIME_NUM_FEATURES,
                num_samples=LIME_NUM_SAMPLES
            )

        except Exception as exc:

            warnings.warn(
                f"LIME failed for "
                f"{case_type}: {exc}"
            )

            continue


        lime_list = (
            explanation
            .as_list(
                label=1
            )
        )


        lime_df = pd.DataFrame(
            lime_list,
            columns=[
                "feature_rule",
                "lime_weight"
            ]
        )


        lime_df["case_type"] = (
            case_type
        )

        lime_df["patient_index"] = (
            idx
        )

        lime_df["predicted_probability"] = (
            y_prob[idx]
        )

        lime_df["actual"] = (
            y_test[idx]
        )

        lime_df["threshold"] = (
            threshold
        )


        lime_df.to_csv(
            CASE_DIR
            / (
                f"lime_"
                f"{case_type.lower()}_"
                f"{horizon}.csv"
            ),
            index=False
        )


        # ----------------------------------------------------------------------
        # LIME horizontal bar
        # ----------------------------------------------------------------------

        plot_df = (
            lime_df
            .sort_values(
                "lime_weight"
            )
        )


        plt.figure(
            figsize=(9, 6)
        )


        plt.barh(
            plot_df[
                "feature_rule"
            ],
            plot_df[
                "lime_weight"
            ]
        )


        plt.axvline(
            0,
            linestyle="--",
            linewidth=1
        )


        plt.xlabel(
            "LIME local weight"
        )


        plt.title(
            f"{horizon.upper()} LIME — "
            f"{case_type} "
            f"(p={y_prob[idx]:.3f})"
        )


        plt.tight_layout()


        png_path = (
            FIG_DIR
            / (
                f"lime_"
                f"{case_type.lower()}_"
                f"{horizon}.png"
            )
        )


        plt.savefig(
            png_path,
            dpi=180,
            bbox_inches="tight"
        )


        plt.close()


        # ----------------------------------------------------------------------
        # HTML explanation
        # ----------------------------------------------------------------------

        html_path = (
            CASE_DIR
            / (
                f"lime_"
                f"{case_type.lower()}_"
                f"{horizon}.html"
            )
        )


        explanation.save_to_file(
            str(html_path)
        )


        print(
            f"  ✓ LIME {case_type} saved"
        )


# ==============================================================================
# 13. PDP + ICE
# ==============================================================================

def find_feature(
    columns,
    candidates
):

    lookup = {
        normalize_name(c): c
        for c in columns
    }


    for candidate in candidates:

        key = normalize_name(
            candidate
        )

        if key in lookup:

            return lookup[key]


    return None


def pdp_ice_analysis(
    artifacts,
    ranking
):

    horizon = artifacts["horizon"]

    model = artifacts["model"]

    X_test = artifacts["X_test"]


    top_features = (
        ranking
        .head(5)
        ["feature"]
        .tolist()
    )


    print(
        "\n"
        + "-" * 80
    )

    print(
        f"PDP + ICE — {horizon.upper()}"
    )

    print(
        "-" * 80
    )


    print(
        f"  Top-5 features for PDP/ICE: "
        f"{top_features}"
    )


    for feature in top_features:

        if feature not in X_test.columns:
            continue


        try:

            fig, ax = plt.subplots(
                figsize=(7, 6)
            )


            PartialDependenceDisplay.from_estimator(
                model,
                X_test,
                [feature],
                kind="both",
                subsample=PDP_ICE_SUBSAMPLE,
                random_state=42,
                grid_resolution=PDP_GRID_RESOLUTION,
                ax=ax
            )


            fig.suptitle(
                f"{horizon.upper()} PDP + ICE — {feature}"
            )


            fig.tight_layout()


            path = (
                FIG_DIR
                / (
                    f"pdp_ice_"
                    f"{normalize_name(feature)}_"
                    f"{horizon}.png"
                )
            )


            fig.savefig(
                path,
                dpi=180,
                bbox_inches="tight"
            )


            plt.close(fig)


        except Exception as exc:

            warnings.warn(
                f"PDP/ICE failed for {feature}: "
                f"{exc}"
            )


    # --------------------------------------------------------------------------
    # 2D ischemic-time × HLA
    # --------------------------------------------------------------------------

    ischemic_feature = find_feature(
        X_test.columns,
        ISCHTIME_CANDIDATES
    )


    hla_feature = find_feature(
        X_test.columns,
        HLA_CANDIDATES
    )


    if (
        ischemic_feature
        and hla_feature
    ):

        try:

            fig, ax = plt.subplots(
                figsize=(8, 7)
            )


            PartialDependenceDisplay.from_estimator(
                model,
                X_test,
                [
                    (
                        ischemic_feature,
                        hla_feature
                    )
                ],
                kind="average",
                grid_resolution=20,
                subsample=PDP_ICE_SUBSAMPLE,
                random_state=42,
                ax=ax
            )


            fig.suptitle(
                f"{horizon.upper()} 2D PDP — "
                f"{ischemic_feature} × {hla_feature}"
            )


            fig.tight_layout()


            path = (
                FIG_DIR
                / (
                    f"pdp_2d_"
                    f"ischtime_hla_"
                    f"{horizon}.png"
                )
            )


            fig.savefig(
                path,
                dpi=180,
                bbox_inches="tight"
            )


            plt.close(fig)


            print(
                f"  ✓ 2D PDP saved → {path}"
            )


        except Exception as exc:

            warnings.warn(
                f"2D PDP failed: {exc}"
            )

    else:

        print(
            "  2D ischemic-time × HLA PDP skipped: "
            "required feature names were not found."
        )


# ==============================================================================
# 14. MODEL REFIT SAFETY
# ==============================================================================

def make_refit_estimator(
    template
):

    try:

        estimator = clone(
            template
        )

    except Exception:

        estimator = copy.deepcopy(
            template
        )


    if FORCE_CPU_FOR_PRUNING:

        try:

            params = estimator.get_params()

        except Exception:

            params = {}


        overrides = {}


        # XGBoost
        if "device" in params:

            device = str(
                params["device"]
            ).lower()

            if device in {
                "cuda",
                "gpu"
            }:

                overrides["device"] = "cpu"


        if (
            "tree_method" in params
            and "gpu"
            in str(
                params["tree_method"]
            ).lower()
        ):

            overrides["tree_method"] = "hist"


        # CatBoost
        if "task_type" in params:

            if str(
                params["task_type"]
            ).upper() == "GPU":

                overrides["task_type"] = "CPU"


        # LightGBM
        if "device_type" in params:

            if str(
                params["device_type"]
            ).lower() in {
                "gpu",
                "cuda"
            }:

                overrides["device_type"] = "cpu"


        if overrides:

            try:

                estimator.set_params(
                    **overrides
                )

            except Exception:

                pass


    return estimator


def fit_and_score(
    template,
    X_fit,
    y_fit,
    X_eval,
    y_eval
):

    estimator = make_refit_estimator(
        template
    )


    estimator.fit(
        X_fit,
        y_fit
    )


    prob = predict_probability(
        estimator,
        X_eval
    )


    auc = roc_auc_score(
        y_eval,
        prob
    )


    return (
        estimator,
        prob,
        auc
    )


# ==============================================================================
# 15. SHAP-GUIDED PRUNING
# ==============================================================================

def shap_guided_pruning(
    artifacts
):

    horizon = artifacts["horizon"]

    template_model = artifacts["model"]

    X_train = artifacts["X_train"]

    y_train = artifacts["y_train"]

    X_test = artifacts["X_test"]

    y_test = artifacts["y_test"]


    print(
        "\n"
        + "=" * 70
    )

    print(
        f"SHAP-GUIDED ITERATIVE PRUNING — "
        f"{horizon.upper()}"
    )

    print(
        "=" * 70
    )


    # --------------------------------------------------------------------------
    # Internal development split
    # --------------------------------------------------------------------------

    (
        X_dev,
        X_val,
        y_dev,
        y_val
    ) = train_test_split(
        X_train,
        y_train,
        test_size=PRUNING_VALIDATION_SIZE,
        stratify=y_train,
        random_state=PRUNING_RANDOM_STATE
    )


    # --------------------------------------------------------------------------
    # Baseline validation model
    # --------------------------------------------------------------------------

    baseline_model, _, baseline_auc = (
        fit_and_score(
            template_model,
            X_dev,
            y_dev,
            X_val,
            y_val
        )
    )


    print(
        f"  Baseline: "
        f"{X_train.shape[1]} features "
        f"→ validation AUROC="
        f"{baseline_auc:.4f}"
    )


    current_features = (
        X_train.columns.tolist()
    )


    current_model = (
        baseline_model
    )

    current_auc = (
        baseline_auc
    )


    trajectory = [
        {
            "n_features":
                len(current_features),
            "validation_auroc":
                current_auc,
            "delta_from_baseline":
                0.0,
            "removed_features":
                ""
        }
    ]


    selected_features = (
        current_features.copy()
    )


    # --------------------------------------------------------------------------
    # Iterative pruning
    # --------------------------------------------------------------------------

    while (
        len(current_features)
        > PRUNING_MIN_FEATURES
    ):

        current_X_val = (
            X_val[
                current_features
            ]
        )

        current_X_dev = (
            X_dev[
                current_features
            ]
        )


        # SHAP on validation data
        shap_result = compute_tree_shap(
            model=current_model,
            X=current_X_val,
            background_size=PRUNING_SHAP_BACKGROUND_SIZE,
            max_samples=PRUNING_SHAP_SAMPLES
        )


        current_shap = (
            shap_result["values"]
        )


        mean_abs = (
            np.abs(
                current_shap
            )
            .mean(
                axis=0
            )
        )


        importance = pd.DataFrame(
            {
                "feature":
                    current_features,
                "mean_abs_shap":
                    mean_abs
            }
        ).sort_values(
            "mean_abs_shap"
        )


        n_remove = min(
            PRUNING_STEP,
            len(current_features)
            - PRUNING_MIN_FEATURES
        )


        remove_features = (
            importance
            .head(
                n_remove
            )
            ["feature"]
            .tolist()
        )


        candidate_features = [
            c
            for c in current_features
            if c not in remove_features
        ]


        candidate_model, _, candidate_auc = (
            fit_and_score(
                template_model,
                current_X_dev[
                    candidate_features
                ],
                y_dev,
                X_val[
                    candidate_features
                ],
                y_val
            )
        )


        delta = (
            candidate_auc
            - baseline_auc
        )


        print(
            f"    {len(candidate_features):3d} features "
            f"→ AUROC={candidate_auc:.4f} "
            f"(removed: "
            f"{', '.join(remove_features[:3])}"
            f"{'...' if len(remove_features) > 3 else ''})"
        )


        trajectory.append(
            {
                "n_features":
                    len(candidate_features),
                "validation_auroc":
                    candidate_auc,
                "delta_from_baseline":
                    delta,
                "removed_features":
                    ";".join(
                        remove_features
                    )
            }
        )


        # ----------------------------------------------------------------------
        # Stop after a validation deterioration > allowed delta
        # ----------------------------------------------------------------------

        if (
            baseline_auc
            - candidate_auc
            > PRUNING_DELTA
        ):

            print(
                f"  ✓ Stopping: validation AUROC drop "
                f"{baseline_auc - candidate_auc:.4f} "
                f"> {PRUNING_DELTA}"
            )

            break


        # Accept candidate
        selected_features = (
            candidate_features.copy()
        )

        current_features = (
            candidate_features.copy()
        )

        current_model = (
            candidate_model
        )

        current_auc = (
            candidate_auc
        )


    trajectory_df = pd.DataFrame(
        trajectory
    )


    trajectory_df.to_csv(
        PRUNING_DIR
        / f"shap_pruning_trajectory_{horizon}.csv",
        index=False
    )


    # --------------------------------------------------------------------------
    # Determine selected subset
    # --------------------------------------------------------------------------

    selected_n = (
        len(selected_features)
    )


    selected_val_model, _, selected_val_auc = (
        fit_and_score(
            template_model,
            X_dev[
                selected_features
            ],
            y_dev,
            X_val[
                selected_features
            ],
            y_val
        )
    )


    print(
        f"\n  ✓ SHAP-guided selected subset: "
        f"{selected_n} features "
        f"(validation AUROC="
        f"{selected_val_auc:.4f}, "
        f"baseline="
        f"{baseline_auc:.4f})"
    )


    # --------------------------------------------------------------------------
    # Final external temporal-test evaluation
    #
    # Refit on ALL training-period patients.
    # --------------------------------------------------------------------------

    final_shap_model, final_shap_prob, final_shap_test_auc = (
        fit_and_score(
            template_model,
            X_train[
                selected_features
            ],
            y_train,
            X_test[
                selected_features
            ],
            y_test
        )
    )


    original_test_prob = predict_probability(
        artifacts["model"],
        X_test
    )


    original_test_auc = roc_auc_score(
        y_test,
        original_test_prob
    )


    test_auc_drop = (
        original_test_auc
        - final_shap_test_auc
    )


    # --------------------------------------------------------------------------
    # RFE comparison
    # --------------------------------------------------------------------------

    rfe_auc = np.nan

    rfe_features = []


    try:

        rfe_estimator = make_refit_estimator(
            template_model
        )


        rfe = RFE(
            estimator=rfe_estimator,
            n_features_to_select=selected_n,
            step=PRUNING_STEP,
            importance_getter="auto"
        )


        rfe.fit(
            X_dev,
            y_dev
        )


        rfe_features = (
            X_train.columns[
                rfe.support_
            ]
            .tolist()
        )


        rfe_model, _, rfe_auc = (
            fit_and_score(
                template_model,
                X_dev[
                    rfe_features
                ],
                y_dev,
                X_val[
                    rfe_features
                ],
                y_val
            )
        )


    except Exception as exc:

        warnings.warn(
            f"RFE comparison failed: {exc}"
        )


    # --------------------------------------------------------------------------
    # Random feature-removal comparison
    # --------------------------------------------------------------------------

    random_results = []


    rng = np.random.default_rng(
        RANDOM_BASELINE_SEED
    )


    for repeat in range(
        RANDOM_BASELINE_REPEATS
    ):

        selected_random = (
            rng.choice(
                X_train.columns.to_numpy(),
                size=selected_n,
                replace=False
            )
            .tolist()
        )


        try:

            random_model, _, random_auc = (
                fit_and_score(
                    template_model,
                    X_dev[
                        selected_random
                    ],
                    y_dev,
                    X_val[
                        selected_random
                    ],
                    y_val
                )
            )


            random_results.append(
                {
                    "repeat":
                        repeat + 1,
                    "n_features":
                        selected_n,
                    "validation_auroc":
                        random_auc,
                    "feature_set":
                        ";".join(
                            selected_random
                        )
                }
            )

        except Exception as exc:

            random_results.append(
                {
                    "repeat":
                        repeat + 1,
                    "n_features":
                        selected_n,
                    "validation_auroc":
                        np.nan,
                    "feature_set":
                        f"ERROR: {exc}"
                }
            )


    random_df = pd.DataFrame(
        random_results
    )


    random_df.to_csv(
        PRUNING_DIR
        / f"random_removal_baseline_{horizon}.csv",
        index=False
    )


    # --------------------------------------------------------------------------
    # Final external-test RFE
    # --------------------------------------------------------------------------

    rfe_test_auc = np.nan


    if rfe_features:

        try:

            final_rfe_model, _, rfe_test_auc = (
                fit_and_score(
                    template_model,
                    X_train[
                        rfe_features
                    ],
                    y_train,
                    X_test[
                        rfe_features
                    ],
                    y_test
                )
            )

        except Exception as exc:

            warnings.warn(
                f"RFE final test refit failed: {exc}"
            )


    # --------------------------------------------------------------------------
    # Final external random subset comparison
    # --------------------------------------------------------------------------

    random_final_results = []


    for row in random_results:

        if (
            "ERROR"
            in str(
                row["feature_set"]
            )
        ):

            continue


        random_features = (
            row[
                "feature_set"
            ]
            .split(";")
        )


        try:

            _, _, auc = (
                fit_and_score(
                    template_model,
                    X_train[
                        random_features
                    ],
                    y_train,
                    X_test[
                        random_features
                    ],
                    y_test
                )
            )


            random_final_results.append(
                {
                    "repeat":
                        row["repeat"],
                    "n_features":
                        selected_n,
                    "test_auroc":
                        auc
                }
            )

        except Exception as exc:

            random_final_results.append(
                {
                    "repeat":
                        row["repeat"],
                    "n_features":
                        selected_n,
                    "test_auroc":
                        np.nan
                }
            )


    random_final_df = pd.DataFrame(
        random_final_results
    )


    random_final_df.to_csv(
        PRUNING_DIR
        / f"random_removal_final_test_{horizon}.csv",
        index=False
    )


    # --------------------------------------------------------------------------
    # Save final selected feature list
    # --------------------------------------------------------------------------

    pd.DataFrame(
        {
            "feature":
                selected_features
        }
    ).to_csv(
        PRUNING_DIR
        / (
            f"shap_selected_features_"
            f"{horizon}.csv"
        ),
        index=False
    )


    # --------------------------------------------------------------------------
    # Pruning comparison summary
    # --------------------------------------------------------------------------

    comparison = pd.DataFrame(
        [
            {
                "method":
                    "Baseline",
                "n_features":
                    len(X_train.columns),
                "validation_auroc":
                    baseline_auc,
                "test_auroc":
                    original_test_auc
            },

            {
                "method":
                    "SHAP_guided",
                "n_features":
                    selected_n,
                "validation_auroc":
                    selected_val_auc,
                "test_auroc":
                    final_shap_test_auc
            },

            {
                "method":
                    "RFE",
                "n_features":
                    len(rfe_features)
                    if rfe_features
                    else np.nan,
                "validation_auroc":
                    rfe_auc,
                "test_auroc":
                    rfe_test_auc
            },

            {
                "method":
                    "Random_mean",
                "n_features":
                    selected_n,
                "validation_auroc":
                    random_df[
                        "validation_auroc"
                    ].mean()
                    if not random_df.empty
                    else np.nan,
                "test_auroc":
                    random_final_df[
                        "test_auroc"
                    ].mean()
                    if not random_final_df.empty
                    else np.nan
            }
        ]
    )


    comparison[
        "test_auroc_drop_vs_original"
    ] = (
        original_test_auc
        - comparison["test_auroc"]
    )


    comparison.to_csv(
        PRUNING_DIR
        / (
            f"shap_pruning_comparison_"
            f"{horizon}.csv"
        ),
        index=False
    )


    # --------------------------------------------------------------------------
    # Plot pruning comparison
    # --------------------------------------------------------------------------

    plt.figure(
        figsize=(8, 6)
    )


    plt.plot(
        trajectory_df["n_features"],
        trajectory_df["validation_auroc"],
        marker="o",
        label="SHAP-guided"
    )


    if not random_df.empty:

        random_summary = (
            random_df
            .groupby(
                "n_features"
            )["validation_auroc"]
            .mean()
            .reset_index()
        )


        plt.axhline(
            random_summary[
                "validation_auroc"
            ].mean(),
            linestyle="--",
            label="Random removal"
        )


    if not np.isnan(rfe_auc):

        plt.axhline(
            rfe_auc,
            linestyle=":",
            label="RFE"
        )


    plt.axhline(
        baseline_auc,
        linestyle="-.",
        label="Baseline"
    )


    plt.gca().invert_xaxis()

    plt.xlabel(
        "Number of features"
    )

    plt.ylabel(
        "Internal validation AUROC"
    )

    plt.title(
        f"SHAP-Guided Feature Pruning — "
        f"{horizon.upper()}"
    )

    plt.legend()

    plt.tight_layout()


    path = (
        FIG_DIR
        / (
            f"shap_pruning_comparison_"
            f"{horizon}.png"
        )
    )


    plt.savefig(
        path,
        dpi=180,
        bbox_inches="tight"
    )


    plt.close()


    return {
        "trajectory":
            trajectory_df,
        "selected_features":
            selected_features,
        "selected_n":
            selected_n,
        "validation_baseline_auc":
            baseline_auc,
        "validation_selected_auc":
            selected_val_auc,
        "test_baseline_auc":
            original_test_auc,
        "test_selected_auc":
            final_shap_test_auc,
        "test_auc_drop":
            test_auc_drop,
        "rfe_features":
            rfe_features,
        "rfe_validation_auc":
            rfe_auc,
        "rfe_test_auc":
            rfe_test_auc,
        "random_validation":
            random_df,
        "random_test":
            random_final_df,
        "comparison":
            comparison
    }


# ==============================================================================
# 16. RUN ONE HORIZON
# ==============================================================================

def run_horizon(
    horizon
):

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"SEGMENT 7 — {horizon.upper()}"
    )

    print(
        "=" * 70
    )


    # --------------------------------------------------------------------------
    # Phase A
    # --------------------------------------------------------------------------

    print(
        "\nPHASE A — Loading models and data..."
    )


    artifacts = load_horizon_artifacts(
        horizon
    )


    print(
        f"  ✓ Model loaded: "
        f"{artifacts['model_name']}/"
        f"{artifacts['strategy']}"
    )


    print(
        f"  ✓ Segment 6 AUROC: "
        f"{artifacts['segment6_auroc']:.4f}"
    )


    print(
        f"  ✓ X_train_tree: "
        f"{artifacts['X_train'].shape}"
    )


    print(
        f"  ✓ X_test_tree: "
        f"{artifacts['X_test'].shape}"
    )


    # --------------------------------------------------------------------------
    # Phase G threshold is needed for case studies
    # --------------------------------------------------------------------------

    threshold, threshold_df = (
        select_descriptive_threshold(
            artifacts["y_test"],
            artifacts["y_prob"]
        )
    )


    threshold_df.to_csv(
        TABLE_DIR
        / (
            f"threshold_analysis_"
            f"{horizon}.csv"
        ),
        index=False
    )


    threshold_plot = (
        plot_threshold_analysis(
            threshold_df,
            horizon
        )
    )


    crossing_row = (
        threshold_df
        .assign(
            distance=lambda d:
                (
                    d["sensitivity"]
                    -
                    d["specificity"]
                ).abs()
        )
        .sort_values(
            [
                "distance",
                "threshold"
            ]
        )
        .iloc[0]
    )


    max_mcc_row = (
        threshold_df
        .sort_values(
            "mcc",
            ascending=False
        )
        .iloc[0]
    )


    print(
        f"  Descriptive optimal threshold: "
        f"{threshold:.3f}"
    )


    print(
        f"  Sens=Spec crossing: "
        f"threshold="
        f"{crossing_row['threshold']:.3f} "
        f"sensitivity="
        f"{crossing_row['sensitivity']:.3f} "
        f"specificity="
        f"{crossing_row['specificity']:.3f}"
    )


    # --------------------------------------------------------------------------
    # Phase B — Global SHAP
    # --------------------------------------------------------------------------

    print(
        "\nPHASE B — GLOBAL SHAP ANALYSIS"
    )


    global_result = global_shap_analysis(
        artifacts
    )


    stability = shap_rank_stability(
        global_result,
        horizon
    )


    # --------------------------------------------------------------------------
    # Phase C — SHAP cases
    # --------------------------------------------------------------------------

    print(
        "\nPHASE C — SHAP CASE STUDIES"
    )


    cases = shap_case_studies(
        artifacts,
        global_result,
        threshold
    )


    # --------------------------------------------------------------------------
    # Phase D — LIME
    # --------------------------------------------------------------------------

    print(
        "\nPHASE D — LIME CASE STUDIES"
    )


    lime_case_studies(
        artifacts,
        cases,
        threshold
    )


    # --------------------------------------------------------------------------
    # Phase E — PDP + ICE
    # --------------------------------------------------------------------------

    print(
        "\nPHASE E — PDP + ICE"
    )


    pdp_ice_analysis(
        artifacts,
        global_result["ranking"]
    )


    # --------------------------------------------------------------------------
    # Phase F — pruning
    # --------------------------------------------------------------------------

    pruning_result = None


    if RUN_SHAP_PRUNING:

        print(
            "\nPHASE F — SHAP-GUIDED ITERATIVE PRUNING"
        )


        try:

            pruning_result = (
                shap_guided_pruning(
                    artifacts
                )
            )

        except Exception as exc:

            warnings.warn(
                "SHAP-guided pruning failed. "
                "Core interpretability outputs will remain available.\n"
                f"Reason: {exc}"
            )


    # --------------------------------------------------------------------------
    # Save horizon manifest
    # --------------------------------------------------------------------------

    manifest = []


    for path in sorted(
        FIG_DIR.glob(
            f"*{horizon}*.png"
        )
    ):

        manifest.append(
            {
                "file":
                    path.name,
                "path":
                    str(path),
                "horizon":
                    horizon
            }
        )


    pd.DataFrame(
        manifest
    ).to_csv(
        TABLE_DIR
        / (
            f"output_manifest_"
            f"{horizon}.csv"
        ),
        index=False
    )


    return {
        "artifacts":
            artifacts,
        "global":
            global_result,
        "stability":
            stability,
        "cases":
            cases,
        "threshold":
            threshold,
        "threshold_table":
            threshold_df,
        "pruning":
            pruning_result
    }


# ==============================================================================
# 17. RUN BOTH HORIZONS
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "SEGMENT 7: INTERPRETABILITY FRAMEWORK"
)

print(
    "=" * 70
)


results = {}


for horizon in HORIZONS:

    results[horizon] = run_horizon(
        horizon
    )


# ==============================================================================
# 18. FINAL CROSS-HORIZON COMPARISON
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "CROSS-HORIZON INTERPRETABILITY COMPARISON"
)

print(
    "=" * 70
)


cross_horizon = cross_horizon_comparison(
    results["1yr"]["global"],
    results["3yr"]["global"]
)


# ==============================================================================
# 19. FINAL OUTPUT MANIFEST
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "SEGMENT 7 COMPLETE — OUTPUT MANIFEST"
)

print(
    "=" * 70
)


all_outputs = []


for root in [
    FIG_DIR,
    TABLE_DIR,
    CASE_DIR,
    PRUNING_DIR
]:

    if root.exists():

        for path in sorted(
            root.rglob("*")
        ):

            if path.is_file():

                all_outputs.append(
                    {
                        "file":
                            path.name,
                        "directory":
                            root.name,
                        "path":
                            str(path)
                    }
                )


manifest_df = pd.DataFrame(
    all_outputs
)


manifest_df.to_csv(
    XAI_ROOT
    / "segment7_output_manifest.csv",
    index=False
)


print(
    "\nFigures:"
)


for path in sorted(
    FIG_DIR.glob("*.png")
):

    print(
        f"  ✓ {path.name}"
    )


print(
    "\nTables:"
)


for path in sorted(
    TABLE_DIR.glob("*.csv")
):

    print(
        f"  ✓ {path.name}"
    )


print(
    "\nCase studies:"
)


for path in sorted(
    CASE_DIR.glob("*")
):

    if path.is_file():

        print(
            f"  ✓ {path.name}"
        )


print(
    "\nPruning:"
)


for path in sorted(
    PRUNING_DIR.glob("*")
):

    if path.is_file():

        print(
            f"  ✓ {path.name}"
        )


# ==============================================================================
# 20. KEY THESIS NUMBERS
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "KEY THESIS NUMBERS"
)

print(
    "=" * 70
)


for horizon in HORIZONS:

    res = results[horizon]

    ranking = (
        res["global"]["ranking"]
    )

    print(
        f"\n{horizon.upper()}:"
    )


    print(
        f"  Model:"
        f" {res['artifacts']['model_name']}/"
        f"{res['artifacts']['strategy']}"
    )


    print(
        f"  Segment 6 AUROC:"
        f" {res['artifacts']['segment6_auroc']:.4f}"
    )


    print(
        f"  Test patients explained:"
        f" {len(res['global']['shap']['X']):,}"
    )


    print(
        f"  Number of features:"
        f" {len(ranking):,}"
    )


    print(
        f"  #1 SHAP feature:"
        f" {ranking.iloc[0]['feature']}"
    )


    print(
        f"  #1 mean|SHAP|:"
        f" {ranking.iloc[0]['mean_abs_shap']:.4f}"
    )


    print(
        f"  Descriptive threshold:"
        f" {res['threshold']:.3f}"
    )


    crossing = (
        res["threshold_table"]
        .assign(
            distance=lambda d:
                (
                    d["sensitivity"]
                    -
                    d["specificity"]
                ).abs()
        )
        .sort_values(
            [
                "distance",
                "threshold"
            ]
        )
        .iloc[0]
    )


    print(
        f"  Sens=Spec crossing:"
        f" {crossing['threshold']:.3f}"
    )


    if res["pruning"] is not None:

        print(
            f"  SHAP selected features:"
            f" {res['pruning']['selected_n']}"
        )


        print(
            f"  Pruned test AUROC:"
            f" {res['pruning']['test_selected_auc']:.4f}"
        )


        print(
            f"  Test AUROC drop:"
            f" {res['pruning']['test_auc_drop']:.4f}"
        )


print(
    "\n"
    + "=" * 70
)

print(
    "ALL SEGMENT 7 OUTPUTS:"
)

print(
    f"  {XAI_ROOT}"
)

print(
    "=" * 70
)

======================================================================
SEGMENT 7: INTERPRETABILITY FRAMEWORK
======================================================================

======================================================================
SEGMENT 7 — 3YR
======================================================================

PHASE A — Loading models and data...
  ✓ No explicit prediction file configured; predictions generated from loaded model.
  ✓ Model loaded: LightGBM/S3_THRESHOLD
  ✓ Segment 6 AUROC: 0.6664
  ✓ X_train_tree: (28596, 269)
  ✓ X_test_tree: (7568, 269)

Background dataset has 200 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=200 when initializing the masker.

  Descriptive optimal threshold: 0.455
  Sens=Spec crossing: threshold=0.467 sensitivity=0.623 specificity=0.624

PHASE B — GLOBAL SHAP ANALYSIS

======================================================================
GLOBAL SHAP ANALYSIS — 3YR
======================================================================
  Model: LightGBM/S3_THRESHOLD
  Test patients available: 7,568
  Test features: 269
  Computing SHAP values...

100%|===================| 7540/7568 [02:55<00:00]

  ✓ SHAP values computed. Shape: (7568, 269)

  Top 10 features:
      1. PERM_STATE                                    mean|SHAP| = 0.0333
      2. AGE                                           mean|SHAP| = 0.0227
      3. DON_RETYP                                     mean|SHAP| = 0.0101
      4. DQ1                                           mean|SHAP| = 0.0077
      5. HOME_STATE_DON                                mean|SHAP| = 0.0067
      6. GENDER                                        mean|SHAP| = 0.0066
      7. IABP_TRR                                      mean|SHAP| = 0.0063
      8. FUNC_STAT_TRR                                 mean|SHAP| = 0.0054
      9. SHARE_TY                                      mean|SHAP| = 0.0043
     10. DRMIS                                         mean|SHAP| = 0.0041
  ✓ Beeswarm saved → D:\Thesis\Thesis_parquet\results\interpretability\figures\shap_beeswarm_3yr.png
  ✓ Bar plot saved → D:\Thesis\Thesis_parquet\results\interpretability\figures\shap_bar_3yr.png

PHASE C — SHAP CASE STUDIES
  TP: patient index 2939 predicted=0.699 actual=1
  FP: patient index 7276 predicted=0.682 actual=0
  FN: patient index 4711 predicted=0.211 actual=1
  TN: patient index 1410 predicted=0.205 actual=0

PHASE D — LIME CASE STUDIES

--------------------------------------------------------------------------------
LIME CASE STUDIES — 3YR
--------------------------------------------------------------------------------
  ✓ LIME TP saved
  ✓ LIME FP saved
  ✓ LIME FN saved
  ✓ LIME TN saved

PHASE E — PDP + ICE

--------------------------------------------------------------------------------
PDP + ICE — 3YR
--------------------------------------------------------------------------------
  Top-5 features for PDP/ICE: ['PERM_STATE', 'AGE', 'DON_RETYP', 'DQ1', 'HOME_STATE_DON']

PHASE F — SHAP-GUIDED ITERATIVE PRUNING

======================================================================
SHAP-GUIDED ITERATIVE PRUNING — 3YR
======================================================================
  Baseline: 269 features → validation AUROC=0.7020

 97%|=================== | 966/1000 [00:26<00:00]

    264 features → AUROC=0.7041 (removed: HIST_HYPERTENS_DON_MISSING, PT_T4_DON_MISSING, PT_STEROIDS_DON_MISSING...)

 98%|===================| 983/1000 [00:27<00:00]

    259 features → AUROC=0.7033 (removed: PT_T3_DON_MISSING, HOME_STATE_DON_MISSING, HIST_MI_MISSING...)

 98%|===================| 981/1000 [00:26<00:00]

    254 features → AUROC=0.7022 (removed: TBILI_DON_MISSING, SGPT_DON_MISSING, DIAL_PRIOR_TX_MISSING...)

 97%|=================== | 970/1000 [00:27<00:00]

    249 features → AUROC=0.7026 (removed: CRSMATCH_DONE_MISSING, CLIN_INFECT_DON_MISSING, HIST_COCAINE_DON_MISSING...)

 97%|=================== | 973/1000 [00:26<00:00]

    244 features → AUROC=0.7036 (removed: CREAT_TRR_MISSING, STEROID_MISSING, INOTROP_VASO_CO_TCR_MISSING...)

 97%|=================== | 974/1000 [00:26<00:00]

    239 features → AUROC=0.7035 (removed: TBILI_MISSING, HBV_CORE_DON, COD_CAD_DON_MISSING...)

 97%|=================== | 973/1000 [00:26<00:00]

    234 features → AUROC=0.7028 (removed: VAD_DEVICE_TY_TCR_MISSING, HEMO_SYS_TCR_MISSING, HEP_C_ANTI_DON...)

 97%|=================== | 973/1000 [00:26<00:00]

    229 features → AUROC=0.7028 (removed: HEMO_CO_TCR_MISSING, DIABETES_DON, VENTILATOR_TRR...)

 98%|===================| 976/1000 [00:26<00:00]

    224 features → AUROC=0.7022 (removed: INOTROP_VASO_SYS_TCR_MISSING, PT_T3_DON, HIST_CANCER_DON...)

 98%|===================| 983/1000 [00:26<00:00]

    219 features → AUROC=0.7032 (removed: MALIG, ETHNICITY, CARDARREST_NEURO...)

 99%|===================| 992/1000 [00:27<00:00]

    214 features → AUROC=0.7024 (removed: WORK_INCOME_TCR_MISSING, VENTILATOR_TCR, HIST_DIABETES_DON...)

 96%|=================== | 964/1000 [00:26<00:00]

    209 features → AUROC=0.7038 (removed: LV_EJECT_MISSING, ISCHTIME_MISSING, MALIG_TCR_MISSING...)

 97%|=================== | 966/1000 [00:26<00:00]

    204 features → AUROC=0.7019 (removed: ARGININE_DON_MISSING, HEMO_PA_DIA_TCR_MISSING, EBV_IGG_CAD_DON_MISSING...)

100%|===================| 997/1000 [00:26<00:00]

    199 features → AUROC=0.7014 (removed: PRIOR_CARD_SURG_TYPE_TCR_MISSING, HEMO_PCW_TCR_MISSING, OTHER_INF_DON...)

 99%|===================| 993/1000 [00:27<00:00]

    194 features → AUROC=0.7037 (removed: HIST_OTH_DRUG_DON, LV_EJECT_METH_MISSING, CONTIN_OTH_DRUG_DON_MISSING...)

 99%|===================| 989/1000 [00:28<00:00]

    189 features → AUROC=0.7025 (removed: OTHER_INF_DON_MISSING, HIST_CIG_DON, INOTROP_VASO_PCW_TCR_MISSING...)

 98%|===================| 985/1000 [00:27<00:00]

    184 features → AUROC=0.7008 (removed: TATTOOS, CDC_RISK_HIV_DON_MISSING, AMIS...)

100%|===================| 996/1000 [00:27<00:00]

    179 features → AUROC=0.7030 (removed: HBV_SUR_ANTIGEN, HEMO_PA_DIA_TRR_MISSING, WORK_INCOME_TCR...)

 97%|=================== | 968/1000 [00:26<00:00]

    174 features → AUROC=0.7028 (removed: PROTEIN_URINE, PT_DIURETICS_DON, DIAL_AFTER_LIST...)

 99%|===================| 990/1000 [00:28<00:00]

    169 features → AUROC=0.7033 (removed: INOTROP_VASO_MN_TCR_MISSING, HEMO_CO_TRR_MISSING, CLIN_INFECT_DON...)

 97%|=================== | 968/1000 [00:26<00:00]

    164 features → AUROC=0.7056 (removed: CDC_RISK_HIV_DON, CHEST_XRAY_DON_MISSING, BLOOD_INF_DON...)

 97%|=================== | 971/1000 [00:26<00:00]

    159 features → AUROC=0.7040 (removed: HEPARIN_DON_MISSING, HIST_HYPERTENS_DON, HEMO_PA_MN_TRR_MISSING...)

 98%|===================| 978/1000 [00:26<00:00]

    154 features → AUROC=0.7023 (removed: CORONARY_ANGIO, SENSITIZATION_TIER_MISSING, PO2_DONE_DON_MISSING...)

 98%|===================| 982/1000 [00:26<00:00]

    149 features → AUROC=0.7029 (removed: DIAB, HEMO_PCW_TRR_MISSING, VASODIL_DON...)

 97%|=================== | 974/1000 [00:28<00:00]

    144 features → AUROC=0.7037 (removed: AMIS_MISSING, GENDER_DON, HLAMIS_MISSING...)

100%|===================| 995/1000 [00:28<00:00]

    139 features → AUROC=0.7036 (removed: PO2_MISSING, FUNC_STAT_TRR_MISSING, HEMO_PA_MN_TCR_MISSING...)

 99%|===================| 993/1000 [00:28<00:00]

    134 features → AUROC=0.7019 (removed: TCR_DUR_ABSTAIN_MISSING, PH_DON_MISSING, MED_COND_TRR...)

100%|===================| 999/1000 [00:28<00:00]

    129 features → AUROC=0.7030 (removed: DDR1, DEATH_MECH_DON, ALCOHOL_HEAVY_DON...)

 97%|=================== | 971/1000 [00:28<00:00]

    124 features → AUROC=0.7015 (removed: DB2, DA2, EXERCISE_O2_MISSING...)

 97%|=================== | 971/1000 [00:28<00:00]

    119 features → AUROC=0.7005 (removed: FUNC_STAT_TCR_MISSING, DA1, INSULIN_DON_MISSING...)

 97%|=================== | 971/1000 [00:28<00:00]

    114 features → AUROC=0.7009 (removed: SENSITIZATION_PEAK_MISSING, HEMATOCRIT_DON_MISSING, DR52...)

 96%|=================== | 963/1000 [00:26<00:00]

    109 features → AUROC=0.6997 (removed: PO2_DONE_DON, BMIS_MISSING, IABP_TRR...)

100%|===================| 998/1000 [00:27<00:00]

    104 features → AUROC=0.6966 (removed: CIG_USE_MISSING, LV_EJECT, HEPARIN_DON...)

 99%|===================| 988/1000 [00:27<00:00]

     99 features → AUROC=0.6989 (removed: SGOT_DON, SUD_DEATH, TRANSFUSIONS...)

 97%|=================== | 973/1000 [00:27<00:00]

     94 features → AUROC=0.6984 (removed: INOTROPES_TCR, LIFE_SUP_TCR, DR51...)

 98%|===================| 975/1000 [00:28<00:00]

     89 features → AUROC=0.7009 (removed: INOTROP_SUPPORT_DON_MISSING, HEMO_PA_MN_TCR, BUN_DON...)

 97%|=================== | 972/1000 [00:26<00:00]

     84 features → AUROC=0.7013 (removed: CRSMATCH_DONE, PCO2_DON, WGT_KG_DON_CALC...)

100%|===================| 995/1000 [00:28<00:00]

     79 features → AUROC=0.7002 (removed: ABO, END_STAT, EBV_SEROSTATUS_MISSING...)

 97%|=================== | 974/1000 [00:26<00:00]

     74 features → AUROC=0.7030 (removed: DDR2, HEMO_PCW_TCR, PH_DON...)

 98%|===================| 979/1000 [00:27<00:00]

     69 features → AUROC=0.7006 (removed: OTH_LIFE_SUP_TRR, PRI_PAYMENT_TCR, PO2_FIO2_DON...)

 98%|===================| 981/1000 [00:28<00:00]

     64 features → AUROC=0.6989 (removed: HEMO_PA_MN_TRR, INSULIN_DON, C2...)

 98%|===================| 977/1000 [00:25<00:00]

     59 features → AUROC=0.7011 (removed: HEMO_SYS_TCR, DAYSWAIT_CHRON, THORACIC_DGN...)

100%|===================| 998/1000 [00:26<00:00]

     54 features → AUROC=0.7017 (removed: TRANSFUS_TERM_DON_MISSING, INIT_STAT, CREAT_DON...)

 99%|===================| 986/1000 [00:25<00:00]

     49 features → AUROC=0.7002 (removed: DQ2, C1, OTH_LIFE_SUP_TCR...)

 99%|===================| 987/1000 [00:26<00:00]

     44 features → AUROC=0.7009 (removed: HEMATOCRIT_DON, SENSITIZATION_SOURCE, HEMO_PCW_TRR...)

 96%|=================== | 962/1000 [00:26<00:01]

     39 features → AUROC=0.7021 (removed: HEMO_CO_TCR, TRANSFUS_TERM_DON, BW4...)

 98%|===================| 981/1000 [00:25<00:00]

     34 features → AUROC=0.7021 (removed: AGE_DON, HGT_CM_DON_CALC, INO_PROCURE_AGENT_1...)

 98%|===================| 981/1000 [00:25<00:00]

     29 features → AUROC=0.7049 (removed: HBV_CORE, TCR_DGN, TOT_SERUM_ALBUM...)

 98%|===================| 983/1000 [00:25<00:00]

     24 features → AUROC=0.7008 (removed: SHARE_TY, DISTANCE, EDUCATION...)

 96%|=================== | 962/1000 [00:24<00:00]

     19 features → AUROC=0.6999 (removed: SENSITIZATION_TIER, HEMO_PA_DIA_TRR, DB1...)

 97%|=================== | 968/1000 [00:24<00:00]

     14 features → AUROC=0.6985 (removed: PRIOR_CARD_SURG_TYPE_TCR, FUNC_STAT_TCR, HEMO_CO_TRR...)

 99%|===================| 990/1000 [00:23<00:00]

     10 features → AUROC=0.6972 (removed: DQ1, PRI_PAYMENT_TRR, WGT_KG_TCR...)

  ✓ SHAP-guided selected subset: 10 features (validation AUROC=0.6972, baseline=0.7020)

======================================================================
CROSS-HORIZON INTERPRETABILITY COMPARISON
======================================================================

KeyError: '1yr'

In [ ]:
# ==============================================================================
# CROSS-HORIZON SHAP COMPARISON ONLY
# ==============================================================================
#
# This cell:
#   1. Does NOT load the 1-year model
#   2. Does NOT load the 3-year model
#   3. Does NOT run SHAP
#   4. Does NOT run LIME
#   5. Does NOT run PDP/ICE
#   6. Does NOT run pruning
#
# It ONLY:
#   - loads saved 1-year SHAP ranking
#   - loads saved 3-year SHAP ranking
#   - compares SHAP ranks
#   - compares mean |SHAP|
#   - saves comparison CSV
#   - saves comparison figure
# ==============================================================================


from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ==============================================================================
# 1. PATHS
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

RESULTS_ROOT = (
    BASE / "results"
)

XAI_ROOT = (
    RESULTS_ROOT / "interpretability"
)

FIG_DIR = (
    XAI_ROOT / "figures"
)

TABLE_DIR = (
    XAI_ROOT / "tables"
)


FIG_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TABLE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ==============================================================================
# 2. INPUT FILES
# ==============================================================================

ranking_1yr_path = (
    TABLE_DIR
    / "shap_ranking_1yr.csv"
)

ranking_3yr_path = (
    TABLE_DIR
    / "shap_ranking_3yr.csv"
)


# ==============================================================================
# 3. CHECK FILES
# ==============================================================================

if not ranking_1yr_path.exists():

    raise FileNotFoundError(
        "1-year SHAP ranking not found:\n"
        f"{ranking_1yr_path}"
    )


if not ranking_3yr_path.exists():

    raise FileNotFoundError(
        "3-year SHAP ranking not found:\n"
        f"{ranking_3yr_path}"
    )


# ==============================================================================
# 4. LOAD SAVED RANKINGS
# ==============================================================================

ranking_1yr = pd.read_csv(
    ranking_1yr_path
)

ranking_3yr = pd.read_csv(
    ranking_3yr_path
)


print(
    "\n"
    + "=" * 70
)

print(
    "CROSS-HORIZON SHAP COMPARISON ONLY"
)

print(
    "=" * 70
)

print(
    f"\n✓ Loaded 1-year ranking:"
    f"\n  {ranking_1yr_path}"
)

print(
    f"\n✓ Loaded 3-year ranking:"
    f"\n  {ranking_3yr_path}"
)

print(
    f"\n1-year features: {len(ranking_1yr):,}"
)

print(
    f"3-year features: {len(ranking_3yr):,}"
)


# ==============================================================================
# 5. VALIDATE REQUIRED COLUMNS
# ==============================================================================

required_columns = {
    "feature",
    "rank",
    "mean_abs_shap"
}


missing_1yr = (
    required_columns
    - set(ranking_1yr.columns)
)

missing_3yr = (
    required_columns
    - set(ranking_3yr.columns)
)


if missing_1yr:

    raise ValueError(
        "1-year ranking is missing columns:\n"
        f"{sorted(missing_1yr)}"
    )


if missing_3yr:

    raise ValueError(
        "3-year ranking is missing columns:\n"
        f"{sorted(missing_3yr)}"
    )


# ==============================================================================
# 6. PREPARE RANKINGS
# ==============================================================================

r1 = (
    ranking_1yr[
        [
            "feature",
            "rank",
            "mean_abs_shap"
        ]
    ]
    .rename(
        columns={
            "rank":
                "rank_1yr",

            "mean_abs_shap":
                "mean_abs_shap_1yr"
        }
    )
)


r3 = (
    ranking_3yr[
        [
            "feature",
            "rank",
            "mean_abs_shap"
        ]
    ]
    .rename(
        columns={
            "rank":
                "rank_3yr",

            "mean_abs_shap":
                "mean_abs_shap_3yr"
        }
    )
)


# ==============================================================================
# 7. MERGE 1-YEAR AND 3-YEAR
# ==============================================================================

comparison = (
    r1
    .merge(
        r3,
        on="feature",
        how="outer"
    )
)


# ==============================================================================
# 8. CALCULATE RANK SHIFTS
# ==============================================================================

comparison["rank_shift_1yr_to_3yr"] = (
    comparison["rank_1yr"]
    - comparison["rank_3yr"]
)


comparison["absolute_rank_shift"] = (
    comparison[
        "rank_shift_1yr_to_3yr"
    ]
    .abs()
)


# ==============================================================================
# 9. SORT BY LARGEST RANK CHANGE
# ==============================================================================

comparison = (
    comparison
    .sort_values(
        "absolute_rank_shift",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


# ==============================================================================
# 10. SAVE FULL COMPARISON TABLE
# ==============================================================================

comparison_path = (
    TABLE_DIR
    / "shap_cross_horizon_comparison.csv"
)


comparison.to_csv(
    comparison_path,
    index=False
)


# ==============================================================================
# 11. COMMON FEATURES ONLY FOR PLOT
# ==============================================================================

common = (
    comparison
    .dropna(
        subset=[
            "rank_1yr",
            "rank_3yr"
        ]
    )
    .copy()
)


print(
    f"\n✓ Common features: {len(common):,}"
)


# ==============================================================================
# 12. CROSS-HORIZON RANK PLOT
# ==============================================================================

if not common.empty:

    plot_df = (
        common
        .sort_values(
            "absolute_rank_shift",
            ascending=False
        )
        .head(30)
    )


    plt.figure(
        figsize=(9, 9)
    )


    plt.scatter(
        plot_df["rank_1yr"],
        plot_df["rank_3yr"]
    )


    max_rank = max(
        plot_df["rank_1yr"].max(),
        plot_df["rank_3yr"].max()
    )


    plt.plot(
        [1, max_rank],
        [1, max_rank],
        linestyle="--",
        linewidth=1
    )


    for _, row in (
        plot_df
        .head(15)
        .iterrows()
    ):

        plt.annotate(
            row["feature"],
            (
                row["rank_1yr"],
                row["rank_3yr"]
            ),
            fontsize=7
        )


    plt.xlabel(
        "1-year SHAP rank"
    )

    plt.ylabel(
        "3-year SHAP rank"
    )

    plt.title(
        "Cross-Horizon SHAP Rank Comparison"
    )

    plt.tight_layout()


    comparison_plot_path = (
        FIG_DIR
        / "shap_cross_horizon_comparison.png"
    )


    plt.savefig(
        comparison_plot_path,
        dpi=180,
        bbox_inches="tight"
    )


    plt.close()


else:

    comparison_plot_path = None


# ==============================================================================
# 13. PRINT TOP 10 RANK SHIFTS
# ==============================================================================

print(
    "\n"
    + "-" * 80
)

print(
    "TOP 10 CROSS-HORIZON SHAP RANK SHIFTS"
)

print(
    "-" * 80
)


for _, row in (
    common
    .sort_values(
        "absolute_rank_shift",
        ascending=False
    )
    .head(10)
    .iterrows()
):

    shift = (
        row["rank_shift_1yr_to_3yr"]
    )


    direction = (
        "↑"
        if shift > 0

        else "↓"
        if shift < 0

        else "="
    )


    print(
        f"  {row['feature']:<45} "
        f"rank {int(row['rank_1yr']):3d} → "
        f"{int(row['rank_3yr']):3d} "
        f"{direction} "
        f"{abs(shift):.0f}"
    )


# ==============================================================================
# 14. FINAL OUTPUT
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "CROSS-HORIZON COMPARISON COMPLETE"
)

print(
    "=" * 70
)

print(
    "\n✓ Comparison table:"
)

print(
    f"  {comparison_path}"
)

if comparison_plot_path is not None:

    print(
        "\n✓ Comparison figure:"
    )

    print(
        f"  {comparison_plot_path}"
    )

======================================================================
CROSS-HORIZON SHAP COMPARISON ONLY
======================================================================

✓ Loaded 1-year ranking:
  D:\Thesis\Thesis_parquet\results\interpretability\tables\shap_ranking_1yr.csv

✓ Loaded 3-year ranking:
  D:\Thesis\Thesis_parquet\results\interpretability\tables\shap_ranking_3yr.csv

1-year features: 266
3-year features: 269

✓ Common features: 264

--------------------------------------------------------------------------------
TOP 10 CROSS-HORIZON SHAP RANK SHIFTS
--------------------------------------------------------------------------------
  WORK_INCOME_TRR_MISSING                       rank 205 →  88 ↑ 117
  WORK_INCOME_TRR                               rank 135 →  43 ↑ 92
  BMIS                                          rank 128 →  42 ↑ 86
  INOTROP_VASO_PCW_TCR_MISSING                  rank 169 →  86 ↑ 83
  GENDER_DON                                    rank  81 → 157 ↓ 76
  ALCOHOL_HEAVY_DON                             rank  71 → 141 ↓ 70
  INOTROP_VASO_PCW_TCR                          rank 116 →  47 ↑ 69
  CDC_RISK_HIV_DON                              rank  98 → 164 ↓ 66
  SENSITIZATION_PEAK_MISSING                    rank 154 →  95 ↑ 59
  WGT_KG_DON_CALC                               rank  43 → 102 ↓ 59

======================================================================
CROSS-HORIZON COMPARISON COMPLETE
======================================================================

✓ Comparison table:
  D:\Thesis\Thesis_parquet\results\interpretability\tables\shap_cross_horizon_comparison.csv

✓ Comparison figure:
  D:\Thesis\Thesis_parquet\results\interpretability\figures\shap_cross_horizon_comparison.png

In [ ]:
# ==============================================================================
# XAI ANALYSIS — 1-YEAR XGBOOST + 3-YEAR LIGHTGBM
# ==============================================================================
# Purpose:
#   1. SHAP global feature importance
#   2. SHAP beeswarm
#   3. SHAP directionality
#   4. SHAP dependence plots
#   5. TP/TN/FP/FN SHAP waterfall plots
#   6. LIME local explanations
#   7. Direct 1-year vs 3-year SHAP comparison
#   8. Feature rank-shift analysis
#   9. Horizon comparison heatmap
#
# PRIMARY XAI MODELS:
#   1-year : XGBoost / S2_BALANCED
#   3-year : LightGBM / S3_THRESHOLD
#
# META_LR / STACKING IS NOT USED FOR FEATURE-LEVEL XAI.
# ==============================================================================

from pathlib import Path
import warnings
import pickle
import joblib
import json
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import shap

warnings.filterwarnings("ignore")

try:
    from lime.lime_tabular import LimeTabularExplainer
    LIME_AVAILABLE = True
except ImportError:
    LIME_AVAILABLE = False
    print("WARNING: LIME is not installed.")
    print("Install with: pip install lime")


# ==============================================================================
# 1. PATHS
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

RESULT_DIR = BASE / "results"
XAI_ROOT = RESULT_DIR / "XAI"

XAI_ROOT.mkdir(parents=True, exist_ok=True)

for horizon in ["3yr"]:
    (XAI_ROOT / horizon).mkdir(parents=True, exist_ok=True)


# ==============================================================================
# 2. MODEL CONFIGURATION
# ==============================================================================

CONFIG = {

    "1yr": {
        "result_dir": RESULT_DIR / "1yr",

        "model_name": "XGBoost",
        "strategy": "S2_BALANCED",

        "prediction_file":
            "predictions_XGBoost_S2_BALANCED.csv",

        "label": "1-Year Rejection",

        "expected_test_n": 13796,
    },

    "3yr": {
        "result_dir": RESULT_DIR / "3yr",

        "model_name": "LightGBM",
        "strategy": "S3_THRESHOLD",

        "prediction_file":
            "predictions_LightGBM_S3_THRESHOLD.csv",

        "label": "3-Year Rejection",

        "expected_test_n": 7568,
    }
}
# ==============================================================================
# EXPLICIT SEGMENT 6 PREDICTION FILES
# ==============================================================================

PREDICTION_FILES = {
    "1yr": BASE / "results" / "1yr" / "predictions_XGBoost_S2_BALANCED.csv",

    # Set the exact 3-year prediction file here when available.
    # Example:
    # "3yr": BASE / "results" / "3yr" / "predictions_LightGBM_S3_THRESHOLD.csv",
}

# ==============================================================================
# 3. OPTIONAL: SET EXACT MODEL-READY X_TEST FILES HERE
# ==============================================================================
#
# IMPORTANT:
# If your Segment 5 code already saved X_test matrices, put their exact
# filenames here.
#
# Example:
#
# X_TEST_OVERRIDE = {
#     "1yr": BASE / "results" / "1yr" / "X_test.parquet",
#     "3yr": BASE / "results" / "3yr" / "X_test.parquet",
# }
#
# If you do not know the filenames, leave them as None.
# The discovery section below will search automatically.

X_TEST_OVERRIDE = {
    "3yr": None,
}


# ==============================================================================
# 4. MODEL FILE SEARCH
# ==============================================================================

def find_model_file(result_dir, model_name, strategy):

    patterns = [
        f"*{model_name}*{strategy}*.pkl",
        f"*{model_name}*{strategy}*.joblib",
        f"*{strategy}*{model_name}*.pkl",
        f"*{strategy}*{model_name}*.joblib",
    ]

    candidates = []

    for pattern in patterns:
        candidates.extend(result_dir.rglob(pattern))

    candidates = list(dict.fromkeys(candidates))

    if not candidates:
        raise FileNotFoundError(
            f"\nCould not find model:\n"
            f"  {model_name} / {strategy}\n"
            f"in:\n  {result_dir}\n\n"
            f"Search the directory for the saved model file."
        )

    print(f"\nCandidate model files for {model_name}/{strategy}:")
    for p in candidates:
        print("  ", p)

    # Prefer files with obvious model naming
    preferred = [
        p for p in candidates
        if "model" in p.name.lower()
        or "best" in p.name.lower()
    ]

    if preferred:
        return preferred[0]

    return candidates[0]


# ==============================================================================
# 5. LOAD MODEL
# ==============================================================================

def load_model(path):

    print(f"\nLoading model:")
    print(path)

    try:
        model = joblib.load(path)
    except Exception:
        with open(path, "rb") as f:
            model = pickle.load(f)

    print("Model type:", type(model))

    return model


# ==============================================================================
# 6. MODEL-READY X_TEST DISCOVERY
# ==============================================================================

def load_table(path):

    suffix = path.suffix.lower()

    if suffix == ".parquet":
        return pd.read_parquet(path)

    if suffix == ".csv":
        return pd.read_csv(path)

    if suffix in [".pkl", ".pickle"]:
        return pd.read_pickle(path)

    if suffix == ".joblib":
        return joblib.load(path)

    return None


def is_likely_x_test(path):

    name = path.name.lower()

    # Avoid obvious non-X files
    bad_words = [
        "prediction",
        "metric",
        "result",
        "importance",
        "shap",
        "lime",
        "outcome",
        "target",
        "label",
        "y_test",
        "ytrain",
        "y_train",
    ]

    if any(x in name for x in bad_words):
        return False

    # Prefer filenames containing X/test terminology
    good_words = [
        "x_test",
        "xtest",
        "test_x",
        "testset",
        "test_set",
        "model_ready",
        "modelready",
        "features_test",
        "test_features",
    ]

    return any(x in name for x in good_words)


def discover_x_test(horizon, expected_n):

    print("\n" + "=" * 80)
    print(f"SEARCHING MODEL-READY X_TEST — {horizon}")
    print("=" * 80)

    # --------------------------------------------------------------------------
    # First: exact override
    # --------------------------------------------------------------------------

    override = X_TEST_OVERRIDE.get(horizon)

    if override is not None:

        override = Path(override)

        if not override.exists():
            raise FileNotFoundError(
                f"Specified X_TEST_OVERRIDE does not exist:\n{override}"
            )

        print("Using explicit X_TEST_OVERRIDE:")
        print(override)

        X = load_table(override)

        if X is None:
            raise ValueError(f"Unsupported X_test file: {override}")

        print("Shape:", X.shape)

        return X, override

    # --------------------------------------------------------------------------
    # Automatic discovery
    # --------------------------------------------------------------------------

    search_roots = [
        RESULT_DIR / horizon,
        BASE,
    ]

    extensions = {
        ".parquet",
        ".csv",
        ".pkl",
        ".pickle",
        ".joblib",
    }

    candidates = []

    for root in search_roots:

        if not root.exists():
            continue

        for path in root.rglob("*"):

            if not path.is_file():
                continue

            if path.suffix.lower() not in extensions:
                continue

            if is_likely_x_test(path):
                candidates.append(path)

    candidates = list(dict.fromkeys(candidates))

    if not candidates:

        raise FileNotFoundError(
            f"\nNo obvious model-ready X_test file was found for {horizon}.\n\n"
            f"Your XAI code needs the SAME model-ready test matrix used when "
            f"training/evaluating the saved model.\n\n"
            f"Set:\n"
            f"X_TEST_OVERRIDE['{horizon}'] = Path(r'EXACT_FILE_PATH')"
        )

    print("\nPotential X_test files:")

    valid = []

    for path in candidates:

        try:
            df = load_table(path)

            if not isinstance(df, pd.DataFrame):
                continue

            print(
                f"  {path}\n"
                f"      shape = {df.shape}"
            )

            # Strong check: expected test-set size
            if len(df) == expected_n:
                valid.append((path, df))

        except Exception as e:
            print(
                f"  Could not read {path.name}: {e}"
            )

    # --------------------------------------------------------------------------
    # Exactly one matching test size
    # --------------------------------------------------------------------------

    if len(valid) == 1:

        path, X = valid[0]

        print("\nAutomatically selected:")
        print(path)
        print("Shape:", X.shape)

        return X, path

    # --------------------------------------------------------------------------
    # Multiple candidates
    # --------------------------------------------------------------------------

    if len(valid) > 1:

        print(
            "\nMultiple files have the expected test-set size.\n"
            "For safety, specify the exact file manually:\n"
        )

        for path, df in valid:
            print(
                f"  X_TEST_OVERRIDE['{horizon}'] = "
                f"Path(r'{path}')"
            )

        raise RuntimeError(
            f"Ambiguous X_test discovery for {horizon}."
        )

    # --------------------------------------------------------------------------
    # No matching row count
    # --------------------------------------------------------------------------

    raise RuntimeError(
        f"\nCandidate X_test files were found, but none has the expected "
        f"{expected_n} rows for {horizon}.\n\n"
        f"Do NOT use raw t_df3/tf_df3 here unless they are exactly the "
        f"model-ready test matrix.\n\n"
        f"Set X_TEST_OVERRIDE['{horizon}'] manually."
    )


# ==============================================================================
# 7. FEATURE NAME EXTRACTION
# ==============================================================================

def get_model_feature_names(model):

    # sklearn-style wrapper
    if hasattr(model, "feature_names_in_"):
        names = list(model.feature_names_in_)

        if len(names) > 0:
            return names

    # Some XGBoost models
    if hasattr(model, "get_booster"):

        try:
            names = model.get_booster().feature_names

            if names is not None:
                return list(names)

        except Exception:
            pass

    # Some LightGBM models
    if hasattr(model, "feature_name_"):

        try:
            names = list(model.feature_name_)

            if len(names) > 0:
                return names

        except Exception:
            pass

    if hasattr(model, "booster_"):

        try:
            names = model.booster_.feature_name()

            if names is not None:
                return list(names)

        except Exception:
            pass

    return None


# ==============================================================================
# 8. ALIGN X_TEST TO MODEL
# ==============================================================================

def align_X_to_model(X, model):

    print("\nAligning X_test to model...")

    model_features = get_model_feature_names(model)

    print("X_test shape:", X.shape)

    if model_features is not None:

        print(
            "Number of model features:",
            len(model_features)
        )

        missing = [
            f for f in model_features
            if f not in X.columns
        ]

        extra = [
            f for f in X.columns
            if f not in model_features
        ]

        if missing:

            raise ValueError(
                "\nX_test is missing model features.\n\n"
                f"Missing ({len(missing)}):\n"
                f"{missing[:30]}\n\n"
                "This means the supplied X_test is NOT the correct "
                "model-ready matrix."
            )

        # Keep exact model order
        X = X.loc[:, model_features]

        print(
            f"Aligned to {len(model_features)} model features."
        )

        if extra:
            print(
                f"Dropped {len(extra)} extra columns."
            )

    else:

        print(
            "\nWARNING: Could not retrieve model feature names."
        )

        # Check model's generic feature count
        n_features = None

        if hasattr(model, "n_features_in_"):
            n_features = model.n_features_in_

        if n_features is not None:

            print(
                "Model expects:",
                n_features,
                "features"
            )

            if X.shape[1] != n_features:

                raise ValueError(
                    f"X_test has {X.shape[1]} features but model "
                    f"expects {n_features}."
                )

        else:

            raise ValueError(
                "\nCannot safely determine model feature ordering.\n"
                "Load the exact model-ready X_test matrix used during "
                "evaluation, together with its feature order."
            )

    return X


# ==============================================================================
# 9. NUMERIC CHECK
# ==============================================================================

def ensure_numeric(X):

    non_numeric = X.select_dtypes(
        exclude=[np.number]
    ).columns.tolist()

    if non_numeric:

        raise TypeError(
            "\nX_test still contains non-numeric columns:\n"
            f"{non_numeric[:50]}\n\n"
            "Do NOT blindly convert them to category codes.\n"
            "The XAI matrix must use the same encoding/preprocessing "
            "that was used during model training."
        )

    X = X.astype(np.float32)

    return X


# ==============================================================================
# 10. SHAP CALCULATION
# ==============================================================================

def calculate_shap(model, X):

    print("\nCalculating SHAP values...")

    explainer = shap.TreeExplainer(model)

    shap_values = explainer.shap_values(X)

    # --------------------------------------------------------------------------
    # Newer SHAP / some model configurations
    # --------------------------------------------------------------------------

    if isinstance(shap_values, list):

        if len(shap_values) == 2:
            shap_values = shap_values[1]

        else:
            shap_values = shap_values[-1]

    # --------------------------------------------------------------------------
    # Possible Explanation object
    # --------------------------------------------------------------------------

    if hasattr(shap_values, "values"):
        shap_values = shap_values.values

    shap_values = np.asarray(shap_values)

    # --------------------------------------------------------------------------
    # Defensive handling of 3D outputs
    # --------------------------------------------------------------------------

    if shap_values.ndim == 3:

        # Typical binary shape:
        # samples × features × classes

        if shap_values.shape[-1] == 2:
            shap_values = shap_values[:, :, 1]

        else:
            shap_values = shap_values[:, :, -1]

    if shap_values.ndim != 2:

        raise ValueError(
            f"Unexpected SHAP shape: {shap_values.shape}"
        )

    print(
        "SHAP shape:",
        shap_values.shape
    )

    print(
        "X shape:",
        X.shape
    )

    if shap_values.shape != X.shape:

        raise ValueError(
            "SHAP and X dimensions do not match."
        )

    return explainer, shap_values


# ==============================================================================
# 11. GLOBAL SHAP TABLE
# ==============================================================================

def create_shap_table(X, shap_values):

    mean_abs = np.mean(
        np.abs(shap_values),
        axis=0
    )

    mean_signed = np.mean(
        shap_values,
        axis=0
    )

    positive_fraction = np.mean(
        shap_values > 0,
        axis=0
    )

    negative_fraction = np.mean(
        shap_values < 0,
        axis=0
    )

    table = pd.DataFrame({
        "feature": X.columns,
        "mean_abs_shap": mean_abs,
        "mean_shap": mean_signed,
        "positive_fraction": positive_fraction,
        "negative_fraction": negative_fraction,
    })

    table = table.sort_values(
        "mean_abs_shap",
        ascending=False
    ).reset_index(drop=True)

    table["rank"] = np.arange(
        1,
        len(table) + 1
    )

    return table


# ==============================================================================
# 12. SAVE SHAP TABLE
# ==============================================================================

def save_shap_table(table, output_dir):

    path = output_dir / "shap_global_importance.csv"

    table.to_csv(
        path,
        index=False
    )

    print(
        "Saved:",
        path
    )


# ==============================================================================
# 13. SHAP BAR PLOT
# ==============================================================================

def plot_shap_bar(
    shap_values,
    X,
    horizon,
    model_name,
    output_dir,
    max_display=20
):

    plt.figure(
        figsize=(10, 8)
    )

    shap.summary_plot(
        shap_values,
        X,
        plot_type="bar",
        max_display=max_display,
        show=False
    )

    plt.title(
        f"{horizon} — SHAP Global Feature Importance\n"
        f"{model_name}"
    )

    plt.tight_layout()

    path = output_dir / "shap_global_bar.png"

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(
        "Saved:",
        path
    )


# ==============================================================================
# 14. SHAP BEESWARM
# ==============================================================================

def plot_shap_beeswarm(
    shap_values,
    X,
    horizon,
    model_name,
    output_dir,
    max_display=20
):

    plt.figure(
        figsize=(10, 9)
    )

    shap.summary_plot(
        shap_values,
        X,
        max_display=max_display,
        show=False
    )

    plt.title(
        f"{horizon} — SHAP Beeswarm\n"
        f"{model_name}"
    )

    plt.tight_layout()

    path = output_dir / "shap_beeswarm.png"

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(
        "Saved:",
        path
    )


# ==============================================================================
# 15. SHAP DIRECTIONAL ANALYSIS
# ==============================================================================

def create_direction_table(
    shap_values,
    X
):

    rows = []

    for i, feature in enumerate(X.columns):

        values = shap_values[:, i]

        rows.append({
            "feature": feature,

            "mean_shap":
                np.mean(values),

            "mean_abs_shap":
                np.mean(np.abs(values)),

            "median_shap":
                np.median(values),

            "positive_fraction":
                np.mean(values > 0),

            "negative_fraction":
                np.mean(values < 0),

            "zero_fraction":
                np.mean(values == 0),
        })

    df = pd.DataFrame(rows)

    df = df.sort_values(
        "mean_abs_shap",
        ascending=False
    )

    return df.reset_index(drop=True)


# ==============================================================================
# 16. SHAP DEPENDENCE PLOTS
# ==============================================================================

def create_dependence_plots(
    model,
    shap_values,
    X,
    shap_table,
    horizon,
    output_dir,
    n_features=6
):

    top_features = shap_table.head(
        n_features
    )["feature"].tolist()

    dep_dir = output_dir / "dependence"

    dep_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    for feature in top_features:

        try:

            plt.figure(
                figsize=(8, 6)
            )

            shap.dependence_plot(
                feature,
                shap_values,
                X,
                interaction_index="auto",
                show=False
            )

            plt.title(
                f"{horizon} — SHAP Dependence\n{feature}"
            )

            plt.tight_layout()

            safe_name = re.sub(
                r"[^A-Za-z0-9_.-]+",
                "_",
                str(feature)
            )

            path = (
                dep_dir /
                f"{safe_name}_dependence.png"
            )

            plt.savefig(
                path,
                dpi=300,
                bbox_inches="tight"
            )

            plt.close()

            print(
                "Saved:",
                path
            )

        except Exception as e:

            print(
                f"Dependence plot failed for {feature}: {e}"
            )


# ==============================================================================
# 17. LOAD PREDICTION FILE
# ==============================================================================

def load_predictions(
    horizon
):

    cfg = CONFIG[horizon]

    path = (
        cfg["result_dir"] /
        cfg["prediction_file"]
    )

    if not path.exists():

        raise FileNotFoundError(
            f"\nPrediction file not found:\n{path}"
        )

    pred = pd.read_csv(path)

    print(
        f"\n{horizon} prediction file:",
        path
    )

    print(
        "Shape:",
        pred.shape
    )

    print(
        "Columns:",
        list(pred.columns)
    )

    return pred


# ==============================================================================
# 18. FINAL CROSS-HORIZON COMPARISON
# ==============================================================================

print(
    "\n"
    + "=" * 70
)

print(
    "CROSS-HORIZON INTERPRETABILITY COMPARISON"
)

print(
    "=" * 70
)


# ------------------------------------------------------------------------------
# IMPORTANT:
# 1-year analysis was completed in a previous run.
# Its SHAP ranking is already saved to Drive.
#
# We therefore DO NOT rerun 1-year.
# We simply reload the saved 1-year ranking and compare it with the
# newly generated 3-year ranking.
# ------------------------------------------------------------------------------

ONE_YEAR_RANKING_PATH = (
    TABLE_DIR
    / "shap_ranking_1yr.csv"
)


if not ONE_YEAR_RANKING_PATH.exists():

    raise FileNotFoundError(
        "Existing 1-year SHAP ranking was not found:\n"
        f"{ONE_YEAR_RANKING_PATH}\n\n"
        "Expected file:\n"
        "shap_ranking_1yr.csv"
    )


# Load previously completed 1-year SHAP ranking
ranking_1yr = pd.read_csv(
    ONE_YEAR_RANKING_PATH
)


# Newly generated 3-year ranking
ranking_3yr = (
    results["3yr"]["global"]["ranking"]
)


# Convert both rankings into the same structure expected by
# cross_horizon_comparison().
result_1yr_saved = {
    "ranking": ranking_1yr
}

result_3yr_current = {
    "ranking": ranking_3yr
}


cross_horizon = cross_horizon_comparison(
    result_1yr_saved,
    result_3yr_current
)


print(
    "\n✓ Cross-horizon comparison completed."
)

print(
    f"  Existing 1-year ranking: "
    f"{ONE_YEAR_RANKING_PATH}"
)

print(
    "  New 3-year ranking: generated in this run."
)


# ==============================================================================
# 19. ALIGN PREDICTIONS WITH X_TEST
# ==============================================================================

def align_predictions(
    X,
    pred
):

    y_true_col, y_prob_col = (
        identify_prediction_columns(pred)
    )

    if len(X) != len(pred):

        raise ValueError(
            f"\nX_test has {len(X)} rows but prediction file "
            f"has {len(pred)} rows.\n"
            "Do not calculate local explanations until the rows are aligned."
        )

    y_true = (
        pred[y_true_col]
        .astype(int)
        .to_numpy()
    )

    y_prob = (
        pred[y_prob_col]
        .astype(float)
        .to_numpy()
    )

    return y_true, y_prob


# ==============================================================================
# 20. CONFUSION-MATRIX CASE SELECTION
# ==============================================================================

def select_cases(
    y_true,
    y_prob,
    n_cases=1
):

    threshold = 0.5

    y_pred = (
        y_prob >= threshold
    ).astype(int)

    tp = np.where(
        (y_true == 1) &
        (y_pred == 1)
    )[0]

    tn = np.where(
        (y_true == 0) &
        (y_pred == 0)
    )[0]

    fp = np.where(
        (y_true == 0) &
        (y_pred == 1)
    )[0]

    fn = np.where(
        (y_true == 1) &
        (y_pred == 0)
    )[0]

    cases = {
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn,
    }

    # Pick the most confident example available
    selected = {}

    for case, indices in cases.items():

        if len(indices) == 0:
            selected[case] = None
            continue

        if case in ["TP", "TN"]:

            confidence = np.abs(
                y_prob[indices] - 0.5
            )

            selected[case] = indices[
                np.argmax(confidence)
            ]

        else:

            confidence = np.abs(
                y_prob[indices] - 0.5
            )

            selected[case] = indices[
                np.argmax(confidence)
            ]

    return selected


# ==============================================================================
# 21. NORMALIZE SHAP BASE VALUE
# ==============================================================================

def get_base_value(
    explainer
):

    value = explainer.expected_value

    value = np.asarray(value)

    if value.ndim == 0:
        return float(value)

    if value.size == 1:
        return float(value.ravel()[0])

    # Binary classification
    return float(value.ravel()[-1])


# ==============================================================================
# 22. SHAP WATERFALL
# ==============================================================================

def create_waterfall(
    explainer,
    shap_values,
    X,
    row_idx,
    horizon,
    case_name,
    output_dir,
    max_display=15
):

    base_value = get_base_value(
        explainer
    )

    explanation = shap.Explanation(
        values=shap_values[row_idx],
        base_values=base_value,
        data=X.iloc[row_idx].to_numpy(),
        feature_names=X.columns.tolist(),
    )

    plt.figure(
        figsize=(10, 8)
    )

    shap.plots.waterfall(
        explanation,
        max_display=max_display,
        show=False
    )

    plt.title(
        f"{horizon} — {case_name} SHAP Waterfall"
    )

    plt.tight_layout()

    path = (
        output_dir /
        f"waterfall_{case_name}.png"
    )

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(
        "Saved:",
        path
    )


# ==============================================================================
# 23. LIME LOCAL EXPLANATIONS
# ==============================================================================

def create_lime_explanations(
    model,
    X,
    y_true,
    y_prob,
    horizon,
    output_dir,
    n_features=15
):

    if not LIME_AVAILABLE:
        print(
            "\nSkipping LIME because package is not installed."
        )
        return

    selected = select_cases(
        y_true,
        y_prob
    )

    lime_dir = (
        output_dir /
        "LIME"
    )

    lime_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    feature_names = X.columns.tolist()

    explainer = LimeTabularExplainer(
        X.to_numpy(),
        feature_names=feature_names,
        class_names=[
            "No Rejection",
            "Rejection"
        ],
        mode="classification",
        discretize_continuous=True,
        random_state=42,
    )

    def predict_fn(data):

        data = np.asarray(
            data,
            dtype=np.float32
        )

        probs = model.predict_proba(
            data
        )

        return probs

    for case, row_idx in selected.items():

        if row_idx is None:
            print(
                f"No {case} example available."
            )
            continue

        print(
            f"\nGenerating LIME: "
            f"{horizon} / {case}"
        )

        explanation = explainer.explain_instance(
            X.iloc[row_idx].to_numpy(),
            predict_fn,
            num_features=n_features,
            top_labels=2,
        )

        html_path = (
            lime_dir /
            f"LIME_{case}.html"
        )

        explanation.save_to_file(
            str(html_path)
        )

        txt_path = (
            lime_dir /
            f"LIME_{case}.csv"
        )

        local_exp = explanation.as_list(
            label=1
        )

        lime_df = pd.DataFrame(
            local_exp,
            columns=[
                "feature",
                "lime_weight"
            ]
        )

        lime_df.to_csv(
            txt_path,
            index=False
        )

        print(
            "Saved:",
            html_path
        )

        print(
            "Saved:",
            txt_path
        )


# ==============================================================================
# 24. RUN ONE HORIZON
# ==============================================================================

def run_horizon(
    horizon
):

    cfg = CONFIG[horizon]

    print("\n\n")
    print("=" * 100)
    print(
        f"XAI ANALYSIS — {horizon.upper()}"
    )
    print("=" * 100)

    output_dir = (
        XAI_ROOT /
        horizon
    )

    # --------------------------------------------------------------------------
    # Model
    # --------------------------------------------------------------------------

    model_path = find_model_file(
        cfg["result_dir"],
        cfg["model_name"],
        cfg["strategy"]
    )

    model = load_model(
        model_path
    )

    # --------------------------------------------------------------------------
    # X_test
    # --------------------------------------------------------------------------

    X, X_path = discover_x_test(
        horizon,
        cfg["expected_test_n"]
    )

    # --------------------------------------------------------------------------
    # Align features
    # --------------------------------------------------------------------------

    X = align_X_to_model(
        X,
        model
    )

    X = ensure_numeric(
        X
    )

    # --------------------------------------------------------------------------
    # Predictions
    # --------------------------------------------------------------------------

    pred = load_predictions(
        horizon
    )

    y_true, y_prob = align_predictions(
        X,
        pred
    )

    # --------------------------------------------------------------------------
    # SHAP
    # --------------------------------------------------------------------------

    explainer, shap_values = calculate_shap(
        model,
        X
    )

    # --------------------------------------------------------------------------
    # Global table
    # --------------------------------------------------------------------------

    shap_table = create_shap_table(
        X,
        shap_values
    )

    direction_table = create_direction_table(
        shap_values,
        X
    )

    shap_table.to_csv(
        output_dir /
        "shap_global_importance.csv",
        index=False
    )

    direction_table.to_csv(
        output_dir /
        "shap_directionality.csv",
        index=False
    )

    # --------------------------------------------------------------------------
    # Plots
    # --------------------------------------------------------------------------

    plot_shap_bar(
        shap_values,
        X,
        horizon,
        cfg["model_name"],
        output_dir
    )

    plot_shap_beeswarm(
        shap_values,
        X,
        horizon,
        cfg["model_name"],
        output_dir
    )

    # --------------------------------------------------------------------------
    # Dependence plots
    # --------------------------------------------------------------------------

    create_dependence_plots(
        model,
        shap_values,
        X,
        shap_table,
        horizon,
        output_dir,
        n_features=6
    )

    # --------------------------------------------------------------------------
    # Waterfalls
    # --------------------------------------------------------------------------

    selected = select_cases(
        y_true,
        y_prob
    )

    for case, row_idx in selected.items():

        if row_idx is None:
            continue

        create_waterfall(
            explainer,
            shap_values,
            X,
            row_idx,
            horizon,
            case,
            output_dir
        )

    # --------------------------------------------------------------------------
    # LIME
    # --------------------------------------------------------------------------

    create_lime_explanations(
        model,
        X,
        y_true,
        y_prob,
        horizon,
        output_dir
    )

    # --------------------------------------------------------------------------
    # Save metadata
    # --------------------------------------------------------------------------

    metadata = {
        "horizon": horizon,
        "model_name": cfg["model_name"],
        "strategy": cfg["strategy"],
        "model_file": str(model_path),
        "x_test_file": str(X_path),
        "n_test": int(len(X)),
        "n_features": int(X.shape[1]),
        "positive_cases": int(y_true.sum()),
        "negative_cases": int((y_true == 0).sum()),
    }

    with open(
        output_dir / "xai_metadata.json",
        "w"
    ) as f:

        json.dump(
            metadata,
            f,
            indent=4
        )

    print(
        "\nTop 20 features:"
    )

    print(
        shap_table.head(20).to_string(
            index=False
        )
    )

    print(
        f"\nCompleted XAI for {horizon}."
    )

    return {
        "model": model,
        "model_path": model_path,
        "X": X,
        "X_path": X_path,
        "pred": pred,
        "y_true": y_true,
        "y_prob": y_prob,
        "explainer": explainer,
        "shap_values": shap_values,
        "shap_table": shap_table,
        "direction_table": direction_table,
    }


# ==============================================================================
# 25. RUN BOTH HORIZONS
# ==============================================================================

XAI_RESULTS = {}

for horizon in ["1yr", "3yr"]:

    XAI_RESULTS[horizon] = run_horizon(
        horizon
    )


print("\n\n")
print("=" * 100)
print("BOTH HORIZONS COMPLETED")
print("=" * 100)

====================================================================================================
XAI ANALYSIS — 1YR
====================================================================================================

FileNotFoundError:
Could not find model:
  XGBoost / S2_BALANCED
in:
  D:\Thesis\Thesis_parquet\results\1yr

Search the directory for the saved model file.

In [ ]:
# ==============================================================================
# FINAL THESIS XAI BLOCK
# 1-YEAR + 3-YEAR POST-HEART-TRANSPLANT REJECTION
#
# PRIMARY XAI TARGET:
#     Ensemble_Stacking / META_LR
#
# Generates:
#
# A. GLOBAL SHAP
#    - Mean absolute SHAP feature importance
#    - Relative SHAP importance
#    - Mean signed SHAP
#    - Positive/negative contribution frequency
#    - SHAP bar plot
#    - SHAP beeswarm plot
#    - SHAP dependence plots for top features
#
# B. LOCAL SHAP
#    - TP / TN / FP / FN representative cases
#    - SHAP waterfall plots
#    - Individual SHAP contribution CSVs
#
# C. LIME
#    - TP / TN / FP / FN explanations
#    - HTML explanations
#    - CSV explanations
#
# D. 1-YEAR vs 3-YEAR FEATURE SHIFT
#    - Feature importance comparison
#    - Relative importance shift
#    - Rank shift
#    - Top-feature overlap
#    - Spearman rank correlation
#    - Direct feature-importance scatter
#    - Dumbbell comparison
#    - Feature-rank-shift plot
#
# E. SHAP vs LIME CONSISTENCY
#    - Top-k overlap
#    - Jaccard similarity
#
# F. COMPLETE XAI CSV SUMMARY
#
# ==============================================================================


# ==============================================================================
# 0. IMPORTS
# ==============================================================================

from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

import os
import pickle
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats

import shap
from lime.lime_tabular import LimeTabularExplainer


# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

RESULT_DIRS = {
    "1yr": BASE / "results" / "1yr",
    "3yr": BASE / "results" / "3yr"
}

XAI_ROOT = BASE / "results" / "XAI"
XAI_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

for horizon in ["1yr", "3yr"]:
    (XAI_ROOT / horizon).mkdir(
        parents=True,
        exist_ok=True
    )

COMBINED_XAI_DIR = XAI_ROOT / "combined"
COMBINED_XAI_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------------------------
# MANUAL OVERRIDES
#
# Put exact paths here when automatic discovery cannot identify your files.
#
# Example:
#
# X_TEST_FILE_OVERRIDE["1yr"] =
#     BASE / "results" / "1yr" / "X_test.parquet"
#
# X_TRAIN_FILE_OVERRIDE["1yr"] =
#     BASE / "results" / "1yr" / "X_train.parquet"
#
# STACK_MODEL_FILE_OVERRIDE["1yr"] =
#     BASE / "results" / "1yr" / "stacking_model.pkl"
# ------------------------------------------------------------------------------

X_TEST_FILE_OVERRIDE = {
    "1yr": None,
    "3yr": None
}

X_TRAIN_FILE_OVERRIDE = {
    "1yr": None,
    "3yr": None
}

STACK_MODEL_FILE_OVERRIDE = {
    "1yr": None,
    "3yr": None
}


# ------------------------------------------------------------------------------
# SHAP SETTINGS
# ------------------------------------------------------------------------------

RANDOM_STATE = 42

# Number of TEST patients used for global SHAP
#
# Increase to 500-1000 for the final run if runtime permits.
SHAP_GLOBAL_N = 300

# Training background sample.
SHAP_BACKGROUND_N = 100

# Number of permutation cycles.
#
# Larger = more stable approximation, slower runtime.
SHAP_N_PERMUTATIONS = 5

# Top features shown in publication figures
TOP_N = 20

# Dependence plots for top features
N_DEPENDENCE = 5


# ------------------------------------------------------------------------------
# LIME SETTINGS
# ------------------------------------------------------------------------------

LIME_N_SAMPLES = 5000
LIME_TOP_N = 15

# If your model matrix is entirely numeric / encoded:
LIME_CATEGORICAL_FEATURES = []


# ------------------------------------------------------------------------------
# LOCAL CASES
#
# Representative cases are selected as the nearest-to-threshold patient
# within TP / TN / FP / FN.
# ------------------------------------------------------------------------------

LOCAL_CASES = [
    "TP",
    "TN",
    "FP",
    "FN"
]

WATERFALL_MAX_DISPLAY = 15


# ==============================================================================
# 2. REPRODUCIBILITY
# ==============================================================================

np.random.seed(RANDOM_STATE)


# ==============================================================================
# 3. BASIC HELPERS
# ==============================================================================

def model_label(row):
    model = str(row["model"])
    strategy = row.get("strategy", np.nan)

    if pd.isna(strategy):
        return model

    strategy = str(strategy)

    if strategy.lower() in {
        "nan",
        "none",
        ""
    }:
        return model

    return f"{model} / {strategy}"


def load_any_file(path):

    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(path)

    suffix = path.suffix.lower()

    if suffix == ".parquet":
        return pd.read_parquet(path)

    if suffix == ".csv":
        return pd.read_csv(path)

    if suffix in [".pkl", ".pickle"]:
        try:
            return joblib.load(path)
        except Exception:
            with open(path, "rb") as f:
                return pickle.load(f)

    if suffix == ".npy":
        return np.load(
            path,
            allow_pickle=True
        )

    if suffix == ".npz":
        return np.load(
            path,
            allow_pickle=True
        )

    raise ValueError(
        f"Unsupported file type: {suffix}"
    )


def find_existing_file(
    out_dir,
    explicit_path,
    candidates
):

    if explicit_path is not None:

        explicit_path = Path(
            explicit_path
        )

        if not explicit_path.exists():

            raise FileNotFoundError(
                f"Explicit XAI path does not exist:\n"
                f"{explicit_path}"
            )

        return explicit_path

    for candidate in candidates:

        p = Path(candidate)

        if p.exists():
            return p

    return None


# ==============================================================================
# 4. MODEL FILE DISCOVERY
# ==============================================================================

def recursive_contains_stacking(obj):
    """
    Determine whether a loaded object appears to contain a stacking model.
    """

    if hasattr(obj, "predict_proba"):
        class_name = type(obj).__name__.lower()

        if "stack" in class_name:
            return True

        if hasattr(obj, "final_estimator_"):
            return True

        if hasattr(obj, "estimators_"):
            return True

    if isinstance(obj, dict):

        keys = [
            str(k).lower()
            for k in obj.keys()
        ]

        preferred = [
            "ensemble_stacking",
            "stacking",
            "stacked",
            "meta_model",
            "meta_estimator",
            "base_models"
        ]

        if any(
            any(p in k for p in preferred)
            for k in keys
        ):
            return True

        for value in obj.values():

            if isinstance(
                value,
                (
                    dict,
                    list,
                    tuple
                )
            ):

                try:
                    if recursive_contains_stacking(
                        value
                    ):
                        return True
                except Exception:
                    pass

    if isinstance(
        obj,
        (list, tuple)
    ):

        for value in obj:

            try:

                if recursive_contains_stacking(
                    value
                ):
                    return True

            except Exception:
                pass

    return False


def find_stacking_model_file(
    horizon
):

    out_dir = RESULT_DIRS[horizon]

    preferred_names = [
        "stacking_model.pkl",
        "ensemble_stacking.pkl",
        "Ensemble_Stacking.pkl",
        "trained_models.pkl",
        "models.pkl",
        "best_params.pkl"
    ]

    candidates = []

    for name in preferred_names:

        p = out_dir / name

        if p.exists():
            candidates.append(p)

    # Also inspect any PKL in result directory.
    candidates.extend(
        sorted(
            out_dir.glob("*.pkl")
        )
    )

    # Remove duplicates while preserving order
    candidates = list(
        dict.fromkeys(candidates)
    )

    scored = []

    for path in candidates:

        try:

            obj = load_any_file(
                path
            )

            filename_score = 0

            lname = path.name.lower()

            if "stack" in lname:
                filename_score += 5

            if "ensemble" in lname:
                filename_score += 3

            if "model" in lname:
                filename_score += 1

            contains = recursive_contains_stacking(
                obj
            )

            if contains:
                filename_score += 10

            if filename_score > 0:

                scored.append(
                    (
                        filename_score,
                        path,
                        obj
                    )
                )

        except Exception:
            continue

    if not scored:

        return None, None

    scored.sort(
        key=lambda x: x[0],
        reverse=True
    )

    _, path, obj = scored[0]

    return path, obj


# ==============================================================================
# 5. EXTRACT STACKING ESTIMATOR
# ==============================================================================

def extract_stacking_estimator(
    obj
):
    """
    Try to locate the actual fitted stacking predictor.

    Supported structures include:
        - fitted StackingClassifier
        - sklearn Pipeline wrapping StackingClassifier
        - dictionary containing Ensemble_Stacking
        - dictionary containing stacking_model
        - dictionary containing meta_model + base_models
    """

    # ----------------------------------------------------------
    # Direct estimator
    # ----------------------------------------------------------

    if hasattr(
        obj,
        "predict_proba"
    ):

        return obj


    # ----------------------------------------------------------
    # Dictionary
    # ----------------------------------------------------------

    if isinstance(
        obj,
        dict
    ):

        preferred_keys = [
            "Ensemble_Stacking",
            "ensemble_stacking",
            "stacking",
            "stacking_model",
            "stacked_model",
            "stack_model"
        ]

        for key in preferred_keys:

            if key in obj:

                try:

                    return extract_stacking_estimator(
                        obj[key]
                    )

                except Exception:
                    pass


        # Search all dictionary values
        for key, value in obj.items():

            key_lower = str(key).lower()

            if (
                "stack" in key_lower
                or "ensemble" in key_lower
                or "meta" in key_lower
            ):

                try:

                    result = extract_stacking_estimator(
                        value
                    )

                    if result is not None:
                        return result

                except Exception:
                    pass


    # ----------------------------------------------------------
    # List / tuple
    # ----------------------------------------------------------

    if isinstance(
        obj,
        (list, tuple)
    ):

        for value in obj:

            try:

                result = extract_stacking_estimator(
                    value
                )

                if result is not None:
                    return result

            except Exception:
                pass

    return None


# ==============================================================================
# 6. GENERIC PREDICTOR WRAPPER
# ==============================================================================

class StackingPredictor:

    def __init__(
        self,
        estimator
    ):

        self.estimator = estimator


    def _single_probability(
        self,
        estimator,
        X
    ):

        # ----------------------------------------------------------
        # predict_proba
        # ----------------------------------------------------------

        if hasattr(
            estimator,
            "predict_proba"
        ):

            pred = estimator.predict_proba(X)

            pred = np.asarray(
                pred
            )

            if pred.ndim == 2:

                if pred.shape[1] == 2:
                    return pred[:, 1]

                if pred.shape[1] == 1:
                    return pred[:, 0]

            if pred.ndim == 1:
                return pred

        # ----------------------------------------------------------
        # decision_function
        # ----------------------------------------------------------

        if hasattr(
            estimator,
            "decision_function"
        ):

            decision = np.asarray(
                estimator.decision_function(X)
            )

            if decision.ndim > 1:
                decision = decision[:, -1]

            # Logistic transformation
            return 1.0 / (
                1.0 +
                np.exp(
                    -np.clip(
                        decision,
                        -50,
                        50
                    )
                )
            )

        # ----------------------------------------------------------
        # predict
        # ----------------------------------------------------------

        if hasattr(
            estimator,
            "predict"
        ):

            return np.asarray(
                estimator.predict(X),
                dtype=float
            )

        raise TypeError(
            f"Object {type(estimator)} "
            f"cannot generate predictions."
        )


    def predict_proba(
        self,
        X
    ):

        return self._single_probability(
            self.estimator,
            X
        )


    def predict(
        self,
        X
    ):

        prob = self.predict_proba(
            X
        )

        return (
            prob >= 0.5
        ).astype(int)


# ==============================================================================
# 7. LOAD X MATRICES
# ==============================================================================

def discover_X_file(
    horizon,
    split
):

    out_dir = RESULT_DIRS[horizon]

    if split == "test":

        override = X_TEST_FILE_OVERRIDE[horizon]

        candidates = [
            out_dir / "X_test.parquet",
            out_dir / "X_test.pkl",
            out_dir / "X_test_tree.parquet",
            out_dir / "X_test_tree.pkl",
            out_dir / f"X_test_{horizon}.parquet",
            out_dir / f"X_test_{horizon}.pkl"
        ]

    else:

        override = X_TRAIN_FILE_OVERRIDE[horizon]

        candidates = [
            out_dir / "X_train.parquet",
            out_dir / "X_train.pkl",
            out_dir / "X_train_tree.parquet",
            out_dir / "X_train_tree.pkl",
            out_dir / f"X_train_{horizon}.parquet",
            out_dir / f"X_train_{horizon}.pkl"
        ]

    found = find_existing_file(
        out_dir,
        override,
        candidates
    )

    return found


def normalize_X_object(
    obj,
    split_name
):

    if isinstance(
        obj,
        pd.DataFrame
    ):

        return obj.copy()

    if isinstance(
        obj,
        dict
    ):

        preferred = [
            f"X_{split_name}",
            split_name,
            f"X_{split_name}_tree"
        ]

        for key in preferred:

            if key in obj:

                value = obj[key]

                if isinstance(
                    value,
                    pd.DataFrame
                ):

                    return value.copy()

        # Search DataFrame values
        for value in obj.values():

            if isinstance(
                value,
                pd.DataFrame
            ):

                return value.copy()

    if isinstance(
        obj,
        np.ndarray
    ):

        if obj.ndim == 2:

            return pd.DataFrame(
                obj
            )

    raise TypeError(
        f"Could not convert loaded "
        f"{split_name} matrix to DataFrame. "
        f"Loaded type: {type(obj)}"
    )


# ==============================================================================
# 8. LOAD SAVED PREDICTIONS
# ==============================================================================

def load_selected_prediction(
    horizon
):

    out_dir = RESULT_DIRS[horizon]

    pred_path = (
        out_dir /
        "predictions_Ensemble_Stacking.csv"
    )

    if not pred_path.exists():

        raise FileNotFoundError(
            f"Required prediction file missing:\n"
            f"{pred_path}"
        )

    pred_df = pd.read_csv(
        pred_path
    )

    required = {
        "y_true",
        "y_prob"
    }

    missing = required - set(
        pred_df.columns
    )

    if missing:

        raise ValueError(
            f"{pred_path.name} missing: {missing}"
        )

    pred_df["y_true"] = (
        pd.to_numeric(
            pred_df["y_true"],
            errors="coerce"
        )
    )

    pred_df["y_prob"] = (
        pd.to_numeric(
            pred_df["y_prob"],
            errors="coerce"
        )
    )

    if (
        pred_df["y_true"].isna().any()
        or
        pred_df["y_prob"].isna().any()
    ):

        raise ValueError(
            f"Missing y_true/y_prob in "
            f"{pred_path.name}"
        )

    return pred_df


# ==============================================================================
# 9. ALIGN X TO PREDICTION ORDER
# ==============================================================================

def align_X_to_predictions(
    X,
    pred_df
):

    X = X.copy()

    # ----------------------------------------------------------
    # Best case: TRR_ID_CODE is available
    # ----------------------------------------------------------

    if "TRR_ID_CODE" in pred_df.columns:

        ids = pred_df[
            "TRR_ID_CODE"
        ].astype(str)

        if "TRR_ID_CODE" in X.columns:

            X = X.copy()

            X["_ALIGN_ID_"] = (
                X["TRR_ID_CODE"]
                .astype(str)
            )

            X = (
                X.set_index("_ALIGN_ID_")
                .reindex(ids)
                .reset_index(drop=True)
            )

            X = X.drop(
                columns=[
                    "TRR_ID_CODE"
                ],
                errors="ignore"
            )

            if X.isna().all(
                axis=None
            ):

                raise ValueError(
                    "TRR_ID_CODE alignment failed."
                )

            return X

        if (
            X.index.name
            == "TRR_ID_CODE"
        ):

            X = X.copy()
            X.index = (
                X.index.astype(str)
            )

            X = (
                X.reindex(ids)
                .reset_index(drop=True)
            )

            return X

    # ----------------------------------------------------------
    # Fallback: same order
    # ----------------------------------------------------------

    if len(X) != len(pred_df):

        raise ValueError(
            f"X has {len(X):,} rows but "
            f"prediction file has {len(pred_df):,} rows."
        )

    print(
        "WARNING: X/prediction alignment "
        "uses row order because no TRR_ID_CODE "
        "alignment field was available."
    )

    return X.reset_index(
        drop=True
    )


# ==============================================================================
# 10. GET THRESHOLD
# ==============================================================================

def get_model_threshold(
    horizon
):

    metrics = pd.read_csv(
        RESULT_DIRS[horizon] /
        "all_metrics.csv"
    )

    rows = metrics[
        (
            metrics["model"].astype(str)
            == "Ensemble_Stacking"
        )
        &
        (
            metrics["strategy"].astype(str)
            == "META_LR"
        )
    ]

    if len(rows) == 0:

        print(
            f"{horizon}: META_LR row not found. "
            f"Using threshold=0.5."
        )

        return 0.5

    row = rows.iloc[0]

    possible_columns = [
        "threshold",
        "optimal_threshold",
        "best_threshold",
        "decision_threshold",
        "optimal_cutoff",
        "cutoff",
        "classification_threshold"
    ]

    for column in possible_columns:

        if column in row.index:

            value = pd.to_numeric(
                row[column],
                errors="coerce"
            )

            if pd.notna(value):

                value = float(value)

                if 0 < value < 1:

                    return value

    # Some prediction CSVs may store y_pred.
    pred_path = (
        RESULT_DIRS[horizon]
        /
        "predictions_Ensemble_Stacking.csv"
    )

    pred_df = pd.read_csv(
        pred_path
    )

    if "y_pred" in pred_df.columns:

        # Threshold itself cannot reliably be reconstructed
        # from y_pred alone, so retain standard 0.5.
        pass

    print(
        f"{horizon}: no saved META_LR threshold found. "
        f"Using threshold=0.5 for local-case categorization."
    )

    return 0.5


# ==============================================================================
# 11. REPRESENTATIVE CASE SELECTION
# ==============================================================================

def select_representative_cases(
    pred_df,
    threshold
):

    y_true = (
        pred_df["y_true"]
        .to_numpy(dtype=int)
    )

    y_prob = (
        pred_df["y_prob"]
        .to_numpy(dtype=float)
    )

    y_pred = (
        y_prob >= threshold
    ).astype(int)

    case_type = np.full(
        len(y_true),
        "UNKNOWN",
        dtype=object
    )

    case_type[
        (y_true == 1)
        &
        (y_pred == 1)
    ] = "TP"

    case_type[
        (y_true == 0)
        &
        (y_pred == 0)
    ] = "TN"

    case_type[
        (y_true == 0)
        &
        (y_pred == 1)
    ] = "FP"

    case_type[
        (y_true == 1)
        &
        (y_pred == 0)
    ] = "FN"

    pred_df = pred_df.copy()

    pred_df["y_pred_xai"] = y_pred
    pred_df["case_type"] = case_type
    pred_df["distance_to_threshold"] = (
        np.abs(
            y_prob - threshold
        )
    )

    selected = []

    for case in LOCAL_CASES:

        subset = pred_df[
            pred_df["case_type"] == case
        ]

        if len(subset) == 0:
            continue

        row = subset.loc[
            subset[
                "distance_to_threshold"
            ].idxmin()
        ]

        selected.append({
            "case_type": case,
            "row_position": int(row.name),
            "y_true": int(row["y_true"]),
            "y_prob": float(row["y_prob"]),
            "y_pred": int(row["y_pred_xai"]),
            "distance_to_threshold":
                float(
                    row[
                        "distance_to_threshold"
                    ]
                )
        })

    return (
        pred_df,
        pd.DataFrame(selected)
    )


# ==============================================================================
# 12. PREDICT FUNCTION
# ==============================================================================

def make_predict_function(
    predictor,
    feature_names
):

    def predict_probability(
        X
    ):

        # SHAP may pass DataFrame
        # and LIME passes ndarray.
        if isinstance(
            X,
            pd.DataFrame
        ):

            X_df = X.copy()

        else:

            X = np.asarray(
                X
            )

            X_df = pd.DataFrame(
                X,
                columns=feature_names
            )

        probs = predictor.predict_proba(
            X_df
        )

        probs = np.asarray(
            probs,
            dtype=float
        ).reshape(-1)

        probs = np.clip(
            probs,
            1e-7,
            1 - 1e-7
        )

        return probs

    return predict_probability


# ==============================================================================
# 13. RUN SHAP
# ==============================================================================

def run_shap(
    horizon,
    X_train,
    X_test,
    pred_df,
    predictor
):

    out_dir = XAI_ROOT / horizon

    feature_names = (
        X_test.columns
        .astype(str)
        .tolist()
    )

    # ----------------------------------------------------------
    # Verify numeric / model-ready input
    # ----------------------------------------------------------

    non_numeric = [
        c for c in X_test.columns
        if not pd.api.types.is_numeric_dtype(
            X_test[c]
        )
    ]

    if non_numeric:

        raise TypeError(
            f"{horizon}: XAI matrix contains "
            f"non-numeric features:\n"
            f"{non_numeric[:30]}\n\n"
            f"The SHAP/LIME layer should use the same "
            f"numeric model-ready matrix used by the "
            f"saved stacking model."
        )

    if X_test.isna().any().any():

        raise ValueError(
            f"{horizon}: X_test contains NaN values. "
            f"Use the final model-ready/imputed X_test matrix."
        )

    if X_train is not None:

        if X_train.isna().any().any():

            raise ValueError(
                f"{horizon}: X_train contains NaN values."
            )

        if list(
            X_train.columns.astype(str)
        ) != feature_names:

            X_train = X_train[
                X_test.columns
            ].copy()

    # ----------------------------------------------------------
    # Select background
    # ----------------------------------------------------------

    rng = np.random.RandomState(
        RANDOM_STATE
    )

    bg_n = min(
        SHAP_BACKGROUND_N,
        len(X_train)
        if X_train is not None
        else len(X_test)
    )

    if X_train is not None:

        background_idx = rng.choice(
            len(X_train),
            size=bg_n,
            replace=False
        )

        X_background = (
            X_train.iloc[
                background_idx
            ]
            .copy()
        )

    else:

        print(
            f"WARNING {horizon}: X_train unavailable. "
            f"Using test data as SHAP background."
        )

        background_idx = rng.choice(
            len(X_test),
            size=bg_n,
            replace=False
        )

        X_background = (
            X_test.iloc[
                background_idx
            ]
            .copy()
        )

    # ----------------------------------------------------------
    # Select global SHAP sample
    # ----------------------------------------------------------

    global_n = min(
        SHAP_GLOBAL_N,
        len(X_test)
    )

    global_idx = rng.choice(
        len(X_test),
        size=global_n,
        replace=False
    )

    X_shap = (
        X_test.iloc[
            global_idx
        ]
        .copy()
    )

    # ----------------------------------------------------------
    # Predict function
    # ----------------------------------------------------------

    predict_fn = make_predict_function(
        predictor,
        feature_names
    )

    # ----------------------------------------------------------
    # SHAP masker
    # ----------------------------------------------------------

    masker = shap.maskers.Independent(
        X_background
    )

    explainer = shap.PermutationExplainer(
        predict_fn,
        masker,
        feature_names=feature_names,
        seed=RANDOM_STATE
    )

    print("\n" + "=" * 90)
    print(f"SHAP ANALYSIS — {horizon.upper()}")
    print("=" * 90)

    print(
        f"Background rows : {len(X_background):,}"
    )

    print(
        f"Explained rows   : {len(X_shap):,}"
    )

    print(
        f"Features         : {len(feature_names):,}"
    )

    print(
        f"Permutation cycles: "
        f"{SHAP_N_PERMUTATIONS}"
    )

    # ----------------------------------------------------------
    # Calculate SHAP
    # ----------------------------------------------------------

    shap_values = explainer.shap_values(
        X_shap,
        npermutations=SHAP_N_PERMUTATIONS,
        silent=False
    )

    shap_values = np.asarray(
        shap_values,
        dtype=float
    )

    if shap_values.ndim != 2:

        raise ValueError(
            f"{horizon}: unexpected SHAP shape "
            f"{shap_values.shape}"
        )

    # ----------------------------------------------------------
    # Base value
    # ----------------------------------------------------------

    expected_value = np.asarray(
        explainer.expected_value
    ).reshape(-1)

    if len(expected_value) == 0:

        raise ValueError(
            "SHAP expected value could not be obtained."
        )

    base_value = float(
        expected_value[0]
    )

    # ----------------------------------------------------------
    # GLOBAL IMPORTANCE
    # ----------------------------------------------------------

    mean_abs_shap = np.mean(
        np.abs(shap_values),
        axis=0
    )

    mean_signed_shap = np.mean(
        shap_values,
        axis=0
    )

    positive_fraction = np.mean(
        shap_values > 0,
        axis=0
    )

    negative_fraction = np.mean(
        shap_values < 0,
        axis=0
    )

    relative_importance = (
        mean_abs_shap
        /
        np.sum(mean_abs_shap)
    )

    importance_df = pd.DataFrame({

        "feature":
            feature_names,

        "mean_abs_shap":
            mean_abs_shap,

        "relative_importance":
            relative_importance,

        "mean_signed_shap":
            mean_signed_shap,

        "positive_fraction":
            positive_fraction,

        "negative_fraction":
            negative_fraction
    })

    importance_df = (
        importance_df
        .sort_values(
            "mean_abs_shap",
            ascending=False
        )
        .reset_index(drop=True)
    )

    importance_df["rank"] = (
        np.arange(
            len(importance_df)
        )
        + 1
    )

    importance_df.to_csv(
        out_dir /
        f"shap_feature_importance_{horizon}.csv",
        index=False
    )

    # ----------------------------------------------------------
    # SAVE RAW SHAP MATRIX
    # ----------------------------------------------------------

    np.savez_compressed(
        out_dir /
        f"shap_values_{horizon}.npz",
        shap_values=shap_values,
        expected_value=np.array(
            [base_value]
        ),
        row_positions=global_idx,
        feature_names=np.array(
            feature_names,
            dtype=str
        )
    )

    # ----------------------------------------------------------
    # SHAP EXPLANATION OBJECT
    # ----------------------------------------------------------

    explanation = shap.Explanation(
        values=shap_values,
        base_values=np.repeat(
            base_value,
            len(X_shap)
        ),
        data=X_shap.to_numpy(),
        feature_names=feature_names
    )

    # ----------------------------------------------------------
    # ADDITIVITY CHECK
    # ----------------------------------------------------------

    shap_sum_prediction = (
        base_value
        +
        shap_values.sum(
            axis=1
        )
    )

    actual_predictions = predict_fn(
        X_shap
    )

    additivity_error = (
        shap_sum_prediction
        -
        actual_predictions
    )

    additivity_summary = {
        "horizon": horizon,
        "base_value": base_value,
        "mean_abs_additivity_error":
            float(
                np.mean(
                    np.abs(
                        additivity_error
                    )
                )
            ),
        "max_abs_additivity_error":
            float(
                np.max(
                    np.abs(
                        additivity_error
                    )
                )
            ),
        "rmse_additivity_error":
            float(
                np.sqrt(
                    np.mean(
                        additivity_error ** 2
                    )
                )
            )
    }

    pd.DataFrame(
        [additivity_summary]
    ).to_csv(
        out_dir /
        f"shap_additivity_check_{horizon}.csv",
        index=False
    )

    print(
        "Mean |SHAP additivity error| = "
        f"{additivity_summary['mean_abs_additivity_error']:.6f}"
    )

    # ==============================================================================
    # SHAP BAR
    # ==============================================================================

    plt.figure(
        figsize=(10, 7)
    )

    shap.plots.bar(
        explanation,
        max_display=TOP_N,
        show=False
    )

    plt.title(
        f"SHAP Global Feature Importance — {horizon}"
    )

    plt.tight_layout()

    plt.savefig(
        out_dir /
        f"shap_bar_{horizon}.png",
        dpi=250,
        bbox_inches="tight"
    )

    plt.close()

    # ==============================================================================
    # SHAP BEESWARM
    # ==============================================================================

    plt.figure(
        figsize=(10, 8)
    )

    shap.plots.beeswarm(
        explanation,
        max_display=TOP_N,
        show=False
    )

    plt.title(
        f"SHAP Summary — {horizon} Rejection"
    )

    plt.tight_layout()

    plt.savefig(
        out_dir /
        f"shap_beeswarm_{horizon}.png",
        dpi=250,
        bbox_inches="tight"
    )

    plt.close()

    # ==============================================================================
    # SHAP DEPENDENCE PLOTS
    # ==============================================================================

    top_features = (
        importance_df
        .head(N_DEPENDENCE)
        ["feature"]
        .tolist()
    )

    for feature in top_features:

        try:

            plt.figure(
                figsize=(7, 5)
            )

            shap.plots.scatter(
                explanation[:, feature],
                show=False
            )

            plt.title(
                f"SHAP Dependence — {feature}\n{horizon}"
            )

            plt.tight_layout()

            safe_name = (
                str(feature)
                .replace(
                    "/",
                    "_"
                )
                .replace(
                    "\\",
                    "_"
                )
                .replace(
                    " ",
                    "_"
                )
            )

            plt.savefig(
                out_dir /
                f"shap_dependence_{horizon}_{safe_name}.png",
                dpi=220,
                bbox_inches="tight"
            )

            plt.close()

        except Exception as e:

            print(
                f"WARNING: dependence plot failed "
                f"for {feature}: {e}"
            )

    return {
        "importance_df": importance_df,
        "explanation": explanation,
        "X_shap": X_shap,
        "global_idx": global_idx,
        "predict_fn": predict_fn,
        "base_value": base_value
    }


# ==============================================================================
# 14. SHAP WATERFALLS
# ==============================================================================

def run_waterfalls(
    horizon,
    shap_result,
    case_df
):

    out_dir = XAI_ROOT / horizon

    if len(case_df) == 0:
        return

    explanation = shap_result[
        "explanation"
    ]

    X_shap = shap_result[
        "X_shap"
    ]

    # Map original test row position -> SHAP explanation row
    global_positions = (
        shap_result[
            "global_idx"
        ]
    )

    position_to_shap_index = {
        int(original):
            int(i)
        for i, original in enumerate(
            global_positions
        )
    }

    # ------------------------------------------------------------------
    # If a selected local case is not in global SHAP sample,
    # calculate a dedicated one-row SHAP explanation.
    # ------------------------------------------------------------------

    for _, case in case_df.iterrows():

        case_type = case[
            "case_type"
        ]

        original_position = int(
            case[
                "row_position"
            ]
        )

        if (
            original_position
            in position_to_shap_index
        ):

            shap_index = position_to_shap_index[
                original_position
            ]

            local_explanation = (
                explanation[
                    shap_index
                ]
            )

        else:

            # Create a one-row explainer
            local_explanation = None

            print(
                f"{horizon}: generating dedicated "
                f"SHAP explanation for {case_type}."
            )

            # This requires the original X_test row.
            # It is obtained from the stored test matrix.
            X_test_full = shap_result.get(
                "X_test_full"
            )

            if X_test_full is None:
                continue

            X_case = X_test_full.iloc[
                [original_position]
            ]

            local_explainer = (
                shap.PermutationExplainer(
                    shap_result["predict_fn"],
                    shap_result.get(
                        "masker",
                        shap.maskers.Independent(
                            X_test_full.iloc[
                                :min(
                                    SHAP_BACKGROUND_N,
                                    len(X_test_full)
                                )
                            ]
                        )
                    ),
                    feature_names=X_test_full.columns.astype(str).tolist(),
                    seed=RANDOM_STATE
                )
            )

            local_values = local_explainer.shap_values(
                X_case,
                npermutations=SHAP_N_PERMUTATIONS
            )

            local_values = np.asarray(
                local_values
            ).reshape(
                1,
                -1
            )

            local_base = np.asarray(
                local_explainer.expected_value
            ).reshape(-1)[0]

            local_explanation = shap.Explanation(
                values=local_values[0],
                base_values=float(
                    local_base
                ),
                data=X_case.iloc[0].to_numpy(),
                feature_names=
                    X_test_full.columns.astype(
                        str
                    ).tolist()
            )

        # --------------------------------------------------------------
        # Waterfall figure
        # --------------------------------------------------------------

        plt.figure(
            figsize=(10, 8)
        )

        shap.plots.waterfall(
            local_explanation,
            max_display=WATERFALL_MAX_DISPLAY,
            show=False
        )

        plt.title(
            f"{horizon} Rejection — "
            f"{case_type} Case\n"
            f"Predicted P(rejection)={case['y_prob']:.3f}"
        )

        plt.tight_layout()

        plt.savefig(
            out_dir /
            f"waterfall_{horizon}_{case_type}.png",
            dpi=250,
            bbox_inches="tight"
        )

        plt.close()

        # --------------------------------------------------------------
        # Save local SHAP CSV
        # --------------------------------------------------------------

        local_values = np.asarray(
            local_explanation.values
        )

        local_features = (
            pd.DataFrame({
                "feature":
                    local_explanation.feature_names,

                "feature_value":
                    local_explanation.data,

                "shap_value":
                    local_values,

                "abs_shap":
                    np.abs(
                        local_values
                    )
            })
            .sort_values(
                "abs_shap",
                ascending=False
            )
            .reset_index(
                drop=True
            )
        )

        local_features["rank"] = (
            np.arange(
                len(local_features)
            )
            + 1
        )

        local_features.to_csv(
            out_dir /
            f"waterfall_values_{horizon}_{case_type}.csv",
            index=False
        )


# ==============================================================================
# 15. IMPROVED WATERFALL FUNCTION
# ==============================================================================

def generate_local_waterfalls(
    horizon,
    result,
    X_test,
    case_df
):

    out_dir = XAI_ROOT / horizon

    predictor = result["predict_fn"]

    feature_names = (
        X_test.columns
        .astype(str)
        .tolist()
    )

    # Use training/test background for dedicated local SHAP.
    # Since global SHAP already has the required background information,
    # reuse it where possible.

    background = X_test.iloc[
        :min(
            SHAP_BACKGROUND_N,
            len(X_test)
        )
    ].copy()

    masker = shap.maskers.Independent(
        background
    )

    local_explainer = shap.PermutationExplainer(
        predictor,
        masker,
        feature_names=feature_names,
        seed=RANDOM_STATE
    )

    local_rows = []

    for _, case in case_df.iterrows():

        case_type = case[
            "case_type"
        ]

        position = int(
            case[
                "row_position"
            ]
        )

        X_case = X_test.iloc[
            [position]
        ]

        shap_case = local_explainer.shap_values(
            X_case,
            npermutations=SHAP_N_PERMUTATIONS
        )

        shap_case = np.asarray(
            shap_case,
            dtype=float
        ).reshape(1, -1)

        base_value = float(
            np.asarray(
                local_explainer.expected_value
            ).reshape(-1)[0]
        )

        local_exp = shap.Explanation(
            values=shap_case[0],
            base_values=base_value,
            data=X_case.iloc[0].to_numpy(),
            feature_names=feature_names
        )

        # --------------------------------------------------------------
        # Waterfall
        # --------------------------------------------------------------

        plt.figure(
            figsize=(10, 8)
        )

        shap.plots.waterfall(
            local_exp,
            max_display=WATERFALL_MAX_DISPLAY,
            show=False
        )

        plt.title(
            f"{horizon.upper()} Rejection — "
            f"{case_type} Representative Case\n"
            f"Observed={int(case['y_true'])}, "
            f"Predicted Probability={case['y_prob']:.3f}"
        )

        plt.tight_layout()

        plt.savefig(
            out_dir /
            f"waterfall_{horizon}_{case_type}.png",
            dpi=250,
            bbox_inches="tight"
        )

        plt.close()

        # --------------------------------------------------------------
        # CSV
        # --------------------------------------------------------------

        values = shap_case[0]

        local_df = pd.DataFrame({
            "feature":
                feature_names,

            "feature_value":
                X_case.iloc[0].to_numpy(),

            "shap_value":
                values,

            "abs_shap":
                np.abs(values)
        })

        local_df = (
            local_df
            .sort_values(
                "abs_shap",
                ascending=False
            )
            .reset_index(drop=True)
        )

        local_df["rank"] = (
            np.arange(
                len(local_df)
            )
            + 1
        )

        local_df.to_csv(
            out_dir /
            f"waterfall_values_{horizon}_{case_type}.csv",
            index=False
        )

        local_rows.append({
            "horizon": horizon,
            "case_type": case_type,
            "row_position": position,
            "y_true": int(
                case["y_true"]
            ),
            "y_pred": int(
                case["y_pred"]
            ),
            "predicted_probability":
                float(
                    case["y_prob"]
                ),
            "threshold_distance":
                float(
                    case[
                        "distance_to_threshold"
                    ]
                ),
            "base_value":
                base_value
        })

    pd.DataFrame(
        local_rows
    ).to_csv(
        out_dir /
        f"local_case_summary_{horizon}.csv",
        index=False
    )


# ==============================================================================
# 16. LIME EXPLANATIONS
# ==============================================================================

def run_lime(
    horizon,
    X_train,
    X_test,
    pred_df,
    predictor,
    case_df
):

    out_dir = XAI_ROOT / horizon

    feature_names = (
        X_test.columns
        .astype(str)
        .tolist()
    )

    # ----------------------------------------------------------
    # LIME background
    # ----------------------------------------------------------

    if X_train is not None:

        train_data = (
            X_train
            .to_numpy(
                dtype=float
            )
        )

    else:

        print(
            f"WARNING {horizon}: X_train unavailable "
            f"for LIME. Using X_test."
        )

        train_data = (
            X_test
            .to_numpy(
                dtype=float
            )
        )

    # ----------------------------------------------------------
    # LIME prediction wrapper
    # ----------------------------------------------------------

    def lime_predict_fn(
        X_numpy
    ):

        X_numpy = np.asarray(
            X_numpy,
            dtype=float
        )

        X_df = pd.DataFrame(
            X_numpy,
            columns=feature_names
        )

        p = predictor.predict_proba(
            X_df
        )

        p = np.clip(
            np.asarray(
                p,
                dtype=float
            ).reshape(-1),
            1e-7,
            1 - 1e-7
        )

        return np.column_stack([
            1 - p,
            p
        ])

    explainer = LimeTabularExplainer(

        training_data=train_data,

        feature_names=feature_names,

        class_names=[
            "No rejection",
            "Rejection"
        ],

        categorical_features=
            LIME_CATEGORICAL_FEATURES,

        mode="classification",

        discretize_continuous=False,

        random_state=RANDOM_STATE
    )

    all_rows = []

    for _, case in case_df.iterrows():

        case_type = case[
            "case_type"
        ]

        position = int(
            case[
                "row_position"
            ]
        )

        X_case = (
            X_test
            .iloc[
                position
            ]
            .to_numpy(
                dtype=float
            )
        )

        explanation = explainer.explain_instance(

            X_case,

            lime_predict_fn,

            num_features=LIME_TOP_N,

            num_samples=LIME_N_SAMPLES,

            labels=(1,)
        )

        # ----------------------------------------------------------
        # HTML
        # ----------------------------------------------------------

        html_path = (
            out_dir /
            f"lime_{horizon}_{case_type}.html"
        )

        explanation.save_to_file(
            str(html_path)
        )

        # ----------------------------------------------------------
        # CSV
        # ----------------------------------------------------------

        lime_list = explanation.as_list(
            label=1
        )

        lime_df = pd.DataFrame(
            lime_list,
            columns=[
                "feature",
                "lime_weight"
            ]
        )

        lime_df["abs_lime"] = (
            np.abs(
                lime_df[
                    "lime_weight"
                ]
            )
        )

        lime_df["rank"] = (
            np.arange(
                len(lime_df)
            )
            + 1
        )

        lime_df.to_csv(
            out_dir /
            f"lime_values_{horizon}_{case_type}.csv",
            index=False
        )

        # ----------------------------------------------------------
        # Summary
        # ----------------------------------------------------------

        all_rows.append({

            "horizon":
                horizon,

            "case_type":
                case_type,

            "row_position":
                position,

            "y_true":
                int(
                    case["y_true"]
                ),

            "y_pred":
                int(
                    case["y_pred"]
                ),

            "predicted_probability":
                float(
                    case["y_prob"]
                ),

            "top_lime_feature":
                (
                    lime_df.iloc[0]["feature"]
                    if len(lime_df)
                    else None
                ),

            "top_lime_weight":
                (
                    lime_df.iloc[0]["lime_weight"]
                    if len(lime_df)
                    else np.nan
                )
        })

    pd.DataFrame(
        all_rows
    ).to_csv(
        out_dir /
        f"lime_case_summary_{horizon}.csv",
        index=False
    )


# ==============================================================================
# 17. SHAP-LIME AGREEMENT
# ==============================================================================

def compute_xai_agreement(
    horizon
):

    out_dir = XAI_ROOT / horizon

    rows = []

    for case_type in LOCAL_CASES:

        shap_path = (
            out_dir /
            f"waterfall_values_{horizon}_{case_type}.csv"
        )

        lime_path = (
            out_dir /
            f"lime_values_{horizon}_{case_type}.csv"
        )

        if (
            not shap_path.exists()
            or
            not lime_path.exists()
        ):
            continue

        shap_df = pd.read_csv(
            shap_path
        )

        lime_df = pd.read_csv(
            lime_path
        )

        shap_top = set(
            shap_df
            .sort_values(
                "abs_shap",
                ascending=False
            )
            .head(10)
            ["feature"]
            .astype(str)
        )

        lime_top = set(
            lime_df
            .sort_values(
                "abs_lime",
                ascending=False
            )
            .head(10)
            ["feature"]
            .astype(str)
        )

        intersection = (
            shap_top
            &
            lime_top
        )

        union = (
            shap_top
            |
            lime_top
        )

        jaccard = (
            len(intersection)
            /
            len(union)
            if len(union)
            else np.nan
        )

        rows.append({
            "horizon":
                horizon,

            "case_type":
                case_type,

            "shap_top10":
                len(shap_top),

            "lime_top10":
                len(lime_top),

            "overlap_count":
                len(intersection),

            "jaccard_similarity":
                jaccard,

            "shared_features":
                "; ".join(
                    sorted(
                        intersection
                    )
                )
        })

    agreement_df = pd.DataFrame(
        rows
    )

    agreement_df.to_csv(
        out_dir /
        f"shap_lime_agreement_{horizon}.csv",
        index=False
    )

    return agreement_df


# ==============================================================================
# 18. COMPLETE HORIZON XAI PIPELINE
# ==============================================================================

def run_horizon_xai(
    horizon
):

    print("\n" + "=" * 100)
    print(
        f"STARTING XAI PIPELINE — "
        f"{horizon.upper()}"
    )
    print("=" * 100)

    # ----------------------------------------------------------
    # Load prediction file
    # ----------------------------------------------------------

    pred_df = load_selected_prediction(
        horizon
    )

    # ----------------------------------------------------------
    # Load X_test
    # ----------------------------------------------------------

    X_test_path = discover_X_file(
        horizon,
        "test"
    )

    if X_test_path is None:

        raise FileNotFoundError(
            f"\nCould not automatically locate X_test for {horizon}.\n"
            f"Set X_TEST_FILE_OVERRIDE['{horizon}'] "
            f"to the exact model-ready X_test file."
        )

    print(
        f"X_test file: {X_test_path}"
    )

    X_test_obj = load_any_file(
        X_test_path
    )

    X_test = normalize_X_object(
        X_test_obj,
        "test"
    )

    # ----------------------------------------------------------
    # Align to stacking prediction order
    # ----------------------------------------------------------

    X_test = align_X_to_predictions(
        X_test,
        pred_df
    )

    print(
        f"X_test shape: {X_test.shape}"
    )

    # ----------------------------------------------------------
    # Load X_train for background / LIME
    # ----------------------------------------------------------

    X_train = None

    X_train_path = discover_X_file(
        horizon,
        "train"
    )

    if X_train_path is not None:

        print(
            f"X_train file: {X_train_path}"
        )

        X_train_obj = load_any_file(
            X_train_path
        )

        X_train = normalize_X_object(
            X_train_obj,
            "train"
        )

        if len(X_train) > 0:

            # Only align by feature columns, not
            # prediction rows, because X_train has
            # no test prediction ordering.
            X_train = X_train[
                X_test.columns
            ].copy()

    else:

        print(
            f"WARNING {horizon}: X_train file was not found."
        )

    # ----------------------------------------------------------
    # Load actual stacking model
    # ----------------------------------------------------------

    if STACK_MODEL_FILE_OVERRIDE[horizon] is not None:

        model_path = Path(
            STACK_MODEL_FILE_OVERRIDE[horizon]
        )

        model_obj = load_any_file(
            model_path
        )

    else:

        model_path, model_obj = (
            find_stacking_model_file(
                horizon
            )
        )

    if model_obj is None:

        raise FileNotFoundError(

            f"\nCould not locate a fitted stacking model "
            f"for {horizon}.\n\n"

            f"The model used for SHAP/LIME must be the "
            f"actual trained Ensemble_Stacking / META_LR "
            f"predictor.\n\n"

            f"Set STACK_MODEL_FILE_OVERRIDE['{horizon}'] "
            f"to its exact .pkl/.pickle file."
        )

    print(
        f"Candidate model file: "
        f"{model_path}"
    )

    stacking_estimator = (
        extract_stacking_estimator(
            model_obj
        )
    )

    if stacking_estimator is None:

        raise TypeError(

            f"\nA possible model file was found:\n"
            f"{model_path}\n\n"

            f"But the file does not expose a usable "
            f"fitted stacking predictor.\n\n"

            f"This usually means the file contains "
            f"hyperparameters or metrics instead of "
            f"the trained model."
        )

    print(
        f"Loaded stacking estimator: "
        f"{type(stacking_estimator).__name__}"
    )

    predictor = StackingPredictor(
        stacking_estimator
    )

    # ----------------------------------------------------------
    # Verify prediction agreement with saved prediction file
    # ----------------------------------------------------------

    fresh_prob = predictor.predict_proba(
        X_test
    )

    saved_prob = (
        pred_df["y_prob"]
        .to_numpy(
            dtype=float
        )
    )

    if len(fresh_prob) != len(saved_prob):

        raise ValueError(
            f"{horizon}: loaded model produces "
            f"{len(fresh_prob):,} predictions but "
            f"saved prediction file contains "
            f"{len(saved_prob):,}."
        )

    prediction_mae = float(
        np.mean(
            np.abs(
                fresh_prob
                -
                saved_prob
            )
        )
    )

    prediction_max_error = float(
        np.max(
            np.abs(
                fresh_prob
                -
                saved_prob
            )
        )
    )

    print(
        f"Prediction agreement MAE  : "
        f"{prediction_mae:.10f}"
    )

    print(
        f"Prediction agreement max   : "
        f"{prediction_max_error:.10f}"
    )

    pd.DataFrame([
        {
            "horizon":
                horizon,

            "prediction_mae":
                prediction_mae,

            "prediction_max_abs_error":
                prediction_max_error
        }
    ]).to_csv(
        XAI_ROOT /
        horizon /
        f"prediction_reproducibility_{horizon}.csv",
        index=False
    )

    if prediction_mae > 1e-6:

        raise ValueError(

            f"\nCRITICAL: The loaded stacking model "
            f"does NOT reproduce the saved prediction "
            f"CSV.\n\n"

            f"MAE={prediction_mae:.10f}\n"
            f"Max error={prediction_max_error:.10f}\n\n"

            f"Do NOT continue with SHAP/LIME until the "
            f"exact model/preprocessing pipeline used to "
            f"generate predictions is loaded."
        )

    # ----------------------------------------------------------
    # Threshold and representative cases
    # ----------------------------------------------------------

    threshold = get_model_threshold(
        horizon
    )

    pred_df_with_cases, case_df = (
        select_representative_cases(
            pred_df,
            threshold
        )
    )

    case_df["threshold"] = threshold

    case_df.to_csv(
        XAI_ROOT /
        horizon /
        f"representative_cases_{horizon}.csv",
        index=False
    )

    print(
        f"XAI threshold: {threshold:.4f}"
    )

    print(
        "\nRepresentative cases:"
    )

    print(
        case_df.to_string(
            index=False
        )
    )

    # ----------------------------------------------------------
    # SHAP
    # ----------------------------------------------------------

    shap_result = run_shap(
        horizon,
        X_train,
        X_test,
        pred_df,
        predictor
    )

    # Keep the complete test matrix for local explanations
    shap_result["X_test_full"] = X_test

    # Keep predictor and background available
    shap_result["predictor"] = predictor

    generate_local_waterfalls(
        horizon,
        shap_result,
        X_test,
        case_df
    )

    # ----------------------------------------------------------
    # LIME
    # ----------------------------------------------------------

    run_lime(
        horizon,
        X_train,
        X_test,
        pred_df,
        predictor,
        case_df
    )

    # ----------------------------------------------------------
    # SHAP vs LIME
    # ----------------------------------------------------------

    agreement_df = (
        compute_xai_agreement(
            horizon
        )
    )

    return {
        "horizon": horizon,
        "X_test": X_test,
        "X_train": X_train,
        "pred_df": pred_df,
        "case_df": case_df,
        "importance_df":
            shap_result["importance_df"],
        "shap_result":
            shap_result,
        "agreement_df":
            agreement_df
    }


# ==============================================================================
# 19. RUN BOTH HORIZONS
# ==============================================================================

xai_1yr = run_horizon_xai(
    "1yr"
)

xai_3yr = run_horizon_xai(
    "3yr"
)


# ==============================================================================
# 20. DIRECT 1-YEAR VS 3-YEAR SHAP COMPARISON
# ==============================================================================

imp1 = (
    xai_1yr["importance_df"]
    .copy()
)

imp3 = (
    xai_3yr["importance_df"]
    .copy()
)

imp1 = imp1.rename(
    columns={
        "mean_abs_shap":
            "mean_abs_shap_1yr",

        "relative_importance":
            "relative_importance_1yr",

        "mean_signed_shap":
            "mean_signed_shap_1yr",

        "positive_fraction":
            "positive_fraction_1yr",

        "negative_fraction":
            "negative_fraction_1yr",

        "rank":
            "rank_1yr"
    }
)

imp3 = imp3.rename(
    columns={
        "mean_abs_shap":
            "mean_abs_shap_3yr",

        "relative_importance":
            "relative_importance_3yr",

        "mean_signed_shap":
            "mean_signed_shap_3yr",

        "positive_fraction":
            "positive_fraction_3yr",

        "negative_fraction":
            "negative_fraction_3yr",

        "rank":
            "rank_3yr"
    }
)

comparison = pd.merge(
    imp1,
    imp3,
    on="feature",
    how="outer"
)

comparison[
    [
        c for c in comparison.columns
        if c != "feature"
    ]
] = comparison[
    [
        c for c in comparison.columns
        if c != "feature"
    ]
].fillna(0)

# ----------------------------------------------------------
# Importance shifts
# ----------------------------------------------------------

comparison[
    "raw_importance_change_1yr_to_3yr"
] = (
    comparison[
        "mean_abs_shap_3yr"
    ]
    -
    comparison[
        "mean_abs_shap_1yr"
    ]
)

comparison[
    "relative_importance_change_1yr_to_3yr"
] = (
    comparison[
        "relative_importance_3yr"
    ]
    -
    comparison[
        "relative_importance_1yr"
    ]
)

# Positive means feature became more important:
#
# rank 1 = most important
# rank 20 = less important
#
# Example:
# 1-year rank = 15
# 3-year rank = 3
#
# rank_shift = +12
#
# Therefore positive = moved UP in importance.
comparison[
    "rank_shift_1yr_to_3yr"
] = (
    comparison["rank_1yr"]
    -
    comparison["rank_3yr"]
)

comparison[
    "absolute_rank_shift"
] = np.abs(
    comparison[
        "rank_shift_1yr_to_3yr"
    ]
)

comparison[
    "directional_mean_shap_change"
] = (
    comparison[
        "mean_signed_shap_3yr"
    ]
    -
    comparison[
        "mean_signed_shap_1yr"
    ]
)

comparison["max_relative_importance"] = (
    comparison[
        [
            "relative_importance_1yr",
            "relative_importance_3yr"
        ]
    ].max(axis=1)
)

comparison = (
    comparison
    .sort_values(
        "max_relative_importance",
        ascending=False
    )
    .reset_index(drop=True)
)

comparison.to_csv(
    COMBINED_XAI_DIR /
    "shap_feature_horizon_comparison.csv",
    index=False
)


# ==============================================================================
# 21. TOP-K OVERLAP + SPEARMAN RANK CORRELATION
# ==============================================================================

shared_features = sorted(
    set(
        imp1["feature"]
    )
    &
    set(
        imp3["feature"]
    )
)

rank1 = (
    imp1
    .set_index("feature")
    .loc[shared_features]["rank"]
)

rank3 = (
    imp3
    .set_index("feature")
    .loc[shared_features]["rank"]
)

spearman_rho, spearman_p = (
    stats.spearmanr(
        rank1,
        rank3
    )
)

stats_rows = []

for k in [
    5,
    10,
    20
]:

    top1 = set(
        imp1
        .head(k)
        ["feature"]
    )

    top3 = set(
        imp3
        .head(k)
        ["feature"]
    )

    intersection = (
        top1 & top3
    )

    union = (
        top1 | top3
    )

    stats_rows.append({

        "metric":
            f"Top-{k} overlap",

        "value":
            len(intersection),

        "additional_value":
            (
                len(intersection)
                /
                k
            ),

        "jaccard":
            (
                len(intersection)
                /
                len(union)
                if len(union)
                else np.nan
            )
    })


stats_rows.append({

    "metric":
        "Spearman rank correlation",

    "value":
        spearman_rho,

    "additional_value":
        spearman_p,

    "jaccard":
        np.nan
})

pd.DataFrame(
    stats_rows
).to_csv(
    COMBINED_XAI_DIR /
    "shap_horizon_comparison_statistics.csv",
    index=False
)

print("\n" + "=" * 100)
print("SHAP HORIZON COMPARISON")
print("=" * 100)

print(
    f"Shared features: "
    f"{len(shared_features):,}"
)

print(
    f"Spearman rank correlation: "
    f"rho={spearman_rho:.4f}, "
    f"p={spearman_p:.6g}"
)


# ==============================================================================
# 22. DIRECT 1-YEAR VS 3-YEAR IMPORTANCE SCATTER
# ==============================================================================

scatter_df = comparison.copy()

plt.figure(
    figsize=(8, 8)
)

plt.scatter(
    scatter_df[
        "relative_importance_1yr"
    ],
    scatter_df[
        "relative_importance_3yr"
    ],
    alpha=0.65,
    s=35
)

max_value = max(
    scatter_df[
        "relative_importance_1yr"
    ].max(),
    scatter_df[
        "relative_importance_3yr"
    ].max()
)

plt.plot(
    [0, max_value],
    [0, max_value],
    "--"
)

# Label top 15 by maximum importance
label_df = (
    scatter_df
    .nlargest(
        15,
        "max_relative_importance"
    )
)

for _, row in label_df.iterrows():

    plt.annotate(
        str(
            row["feature"]
        ),
        (
            row[
                "relative_importance_1yr"
            ],
            row[
                "relative_importance_3yr"
            ]
        ),
        fontsize=8,
        xytext=(4, 4),
        textcoords="offset points"
    )

plt.xlabel(
    "Relative SHAP importance — 1-year"
)

plt.ylabel(
    "Relative SHAP importance — 3-year"
)

plt.title(
    "Direct SHAP Feature-Importance Comparison\n"
    "1-Year vs 3-Year Rejection"
)

plt.grid(
    alpha=0.2
)

plt.tight_layout()

plt.savefig(
    COMBINED_XAI_DIR /
    "shap_direct_1yr_vs_3yr_scatter.png",
    dpi=250,
    bbox_inches="tight"
)

plt.close()


# ==============================================================================
# 23. DUMBBELL PLOT — FEATURE IMPORTANCE SHIFT
# ==============================================================================

plot_df = (
    comparison
    .nlargest(
        TOP_N,
        "max_relative_importance"
    )
    .sort_values(
        "relative_importance_3yr"
    )
)

y = np.arange(
    len(plot_df)
)

plt.figure(
    figsize=(10, 9)
)

for i, (_, row) in enumerate(
    plot_df.iterrows()
):

    plt.plot(
        [
            row[
                "relative_importance_1yr"
            ],
            row[
                "relative_importance_3yr"
            ]
        ],
        [
            i,
            i
        ],
        "-"
    )

plt.scatter(
    plot_df[
        "relative_importance_1yr"
    ],
    y,
    s=55,
    label="1-year"
)

plt.scatter(
    plot_df[
        "relative_importance_3yr"
    ],
    y,
    s=55,
    label="3-year"
)

plt.yticks(
    y,
    plot_df["feature"]
)

plt.xlabel(
    "Relative mean |SHAP|"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "Feature-Importance Shift from 1-Year to 3-Year Rejection"
)

plt.legend()

plt.grid(
    axis="x",
    alpha=0.2
)

plt.tight_layout()

plt.savefig(
    COMBINED_XAI_DIR /
    "shap_feature_importance_shift_1yr_to_3yr.png",
    dpi=250,
    bbox_inches="tight"
)

plt.close()


# ==============================================================================
# 24. RANK-SHIFT FIGURE
# ==============================================================================

rank_df = (
    comparison
    .nlargest(
        TOP_N,
        "absolute_rank_shift"
    )
    .sort_values(
        "rank_shift_1yr_to_3yr"
    )
)

plt.figure(
    figsize=(10, 9)
)

plt.barh(
    np.arange(
        len(rank_df)
    ),
    rank_df[
        "rank_shift_1yr_to_3yr"
    ]
)

plt.axvline(
    0,
    linestyle="--"
)

plt.yticks(
    np.arange(
        len(rank_df)
    ),
    rank_df["feature"]
)

plt.xlabel(
    "Rank shift (positive = moved up in importance)"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "SHAP Feature-Rank Shift: 1-Year → 3-Year"
)

plt.grid(
    axis="x",
    alpha=0.2
)

plt.tight_layout()

plt.savefig(
    COMBINED_XAI_DIR /
    "shap_feature_rank_shift_1yr_to_3yr.png",
    dpi=250,
    bbox_inches="tight"
)

plt.close()


# ==============================================================================
# 25. TOP FEATURE HEATMAP
# ==============================================================================

heat_df = (
    comparison
    .nlargest(
        TOP_N,
        "max_relative_importance"
    )
    .set_index("feature")
    [
        [
            "relative_importance_1yr",
            "relative_importance_3yr"
        ]
    ]
)

plt.figure(
    figsize=(8, 10)
)

plt.imshow(
    heat_df.to_numpy(),
    aspect="auto"
)

plt.colorbar(
    label="Relative mean |SHAP|"
)

plt.xticks(
    [0, 1],
    ["1-year", "3-year"]
)

plt.yticks(
    np.arange(
        len(heat_df)
    ),
    heat_df.index
)

plt.title(
    "Top SHAP Feature Importance Across Prediction Horizons"
)

plt.tight_layout()

plt.savefig(
    COMBINED_XAI_DIR /
    "shap_top_feature_heatmap_1yr_vs_3yr.png",
    dpi=250,
    bbox_inches="tight"
)

plt.close()


# ==============================================================================
# 26. TOP FEATURES THAT INCREASE IN IMPORTANCE
# ==============================================================================

increase_df = (
    comparison
    .sort_values(
        "relative_importance_change_1yr_to_3yr",
        ascending=False
    )
    .head(TOP_N)
    [
        [
            "feature",
            "relative_importance_1yr",
            "relative_importance_3yr",
            "relative_importance_change_1yr_to_3yr",
            "rank_1yr",
            "rank_3yr",
            "rank_shift_1yr_to_3yr"
        ]
    ]
)

increase_df.to_csv(
    COMBINED_XAI_DIR /
    "shap_features_increasing_1yr_to_3yr.csv",
    index=False
)


# ==============================================================================
# 27. TOP FEATURES THAT DECREASE IN IMPORTANCE
# ==============================================================================

decrease_df = (
    comparison
    .sort_values(
        "relative_importance_change_1yr_to_3yr",
        ascending=True
    )
    .head(TOP_N)
    [
        [
            "feature",
            "relative_importance_1yr",
            "relative_importance_3yr",
            "relative_importance_change_1yr_to_3yr",
            "rank_1yr",
            "rank_3yr",
            "rank_shift_1yr_to_3yr"
        ]
    ]
)

decrease_df.to_csv(
    COMBINED_XAI_DIR /
    "shap_features_decreasing_1yr_to_3yr.csv",
    index=False
)


# ==============================================================================
# 28. COMBINED XAI SUMMARY
# ==============================================================================

summary_rows = []

for horizon, result in [
    ("1yr", xai_1yr),
    ("3yr", xai_3yr)
]:

    imp = result[
        "importance_df"
    ]

    for _, row in imp.head(TOP_N).iterrows():

        summary_rows.append({

            "horizon":
                horizon,

            "feature":
                row["feature"],

            "rank":
                int(
                    row["rank"]
                ),

            "mean_abs_shap":
                row["mean_abs_shap"],

            "relative_importance":
                row["relative_importance"],

            "mean_signed_shap":
                row["mean_signed_shap"],

            "positive_fraction":
                row["positive_fraction"],

            "negative_fraction":
                row["negative_fraction"]
        })

pd.DataFrame(
    summary_rows
).to_csv(
    COMBINED_XAI_DIR /
    "xai_top20_feature_summary_both_horizons.csv",
    index=False
)


# ==============================================================================
# 29. FINAL OUTPUT REPORT
# ==============================================================================

print("\n" + "=" * 100)
print("XAI PIPELINE COMPLETE")
print("=" * 100)

print("\n1-YEAR XAI OUTPUTS:")

for p in sorted(
    (XAI_ROOT / "1yr").glob("*")
):

    print(
        " ",
        p.name
    )

print("\n3-YEAR XAI OUTPUTS:")

for p in sorted(
    (XAI_ROOT / "3yr").glob("*")
):

    print(
        " ",
        p.name
    )

print("\nCOMBINED XAI OUTPUTS:")

for p in sorted(
    COMBINED_XAI_DIR.glob("*")
):

    print(
        " ",
        p.name
    )

print("\n" + "=" * 100)
print("TOP 15 SHAP FEATURES — 1-YEAR")
print("=" * 100)

print(
    xai_1yr[
        "importance_df"
    ]
    [
        [
            "rank",
            "feature",
            "mean_abs_shap",
            "relative_importance",
            "mean_signed_shap",
            "positive_fraction"
        ]
    ]
    .head(15)
    .to_string(index=False)
)

print("\n" + "=" * 100)
print("TOP 15 SHAP FEATURES — 3-YEAR")
print("=" * 100)

print(
    xai_3yr[
        "importance_df"
    ]
    [
        [
            "rank",
            "feature",
            "mean_abs_shap",
            "relative_importance",
            "mean_signed_shap",
            "positive_fraction"
        ]
    ]
    .head(15)
    .to_string(index=False)
)

print("\n" + "=" * 100)
print("1-YEAR → 3-YEAR FEATURE-IMPORTANCE SHIFT")
print("=" * 100)

print(
    comparison[
        [
            "feature",
            "rank_1yr",
            "rank_3yr",
            "rank_shift_1yr_to_3yr",
            "relative_importance_1yr",
            "relative_importance_3yr",
            "relative_importance_change_1yr_to_3yr"
        ]
    ]
    .head(20)
    .to_string(index=False)
)

print("\nAll XAI analyses completed.")

====================================================================================================
STARTING XAI PIPELINE — 1YR
====================================================================================================

FileNotFoundError:
Could not automatically locate X_test for 1yr.
Set X_TEST_FILE_OVERRIDE['1yr'] to the exact model-ready X_test file.

In [ ]:
# ==============================================================================
# STANDALONE SHAP-GUIDED PRUNING
# ==============================================================================
#
# PURPOSE
# -------
# Re-runs ONLY the SHAP-guided iterative feature-pruning experiment.
#
# 1-YEAR PRIMARY MODEL
# --------------------
# XGBoost / S2_BALANCED
#
# 3-YEAR PRIMARY MODEL
# --------------------
# LightGBM / S3_THRESHOLD
#
# INPUTS
# ------
#   model_ready/1yr/X_train_tree.parquet
#   model_ready/1yr/X_test_tree.parquet
#   model_ready/1yr/y_train.parquet
#   model_ready/1yr/y_test.parquet
#   fitted 1Y XGBoost/S2 model
#
#   model_ready/3yr/X_train_tree.parquet
#   model_ready/3yr/X_test_tree.parquet
#   model_ready/3yr/y_train.parquet
#   model_ready/3yr/y_test.parquet
#   fitted 3Y LightGBM/S3 model
#
#
# METHODOLOGY
# -----------
# STEP 1
#   Split X_train/y_train into internal development and validation subsets.
#
# STEP 2
#   Fit the baseline model on internal development data.
#
# STEP 3
#   Compute SHAP importance using the internal validation set.
#
# STEP 4
#   Remove the least important features in blocks of PRUNING_STEP.
#
# STEP 5
#   Refit on internal development data and evaluate on internal validation.
#
# STEP 6
#   Continue until validation AUROC falls more than PRUNING_DELTA below
#   the baseline.
#
# STEP 7
#   Freeze the last stable feature subset.
#
# STEP 8
#   Refit the selected subset on ALL original X_train/y_train.
#
# STEP 9
#   Evaluate ONCE on the held-out temporal X_test/y_test.
#
#
# IMPORTANT
# ---------
# X_test/y_test NEVER determine the pruning stopping point.
#
# ==============================================================================


# ==============================================================================
# 0. IMPORTS
# ==============================================================================

from pathlib import Path
import re
import pickle
import copy
import warnings

import numpy as np
import pandas as pd

import shap

from sklearn.base import clone
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score


# ==============================================================================
# 1. PATHS
# ==============================================================================

BASE = Path(r"D:\Thesis\Thesis_parquet")

MODEL_READY_ROOT = (
    BASE / "model_ready"
)

MODELS_ROOT = (
    BASE / "models"
)

PRUNING_ROOT = (
    BASE
    / "results"
    / "interpretability"
    / "pruning"
)

PRUNING_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# ==============================================================================
# 2. PRIMARY MODEL CONFIGURATION
# ==============================================================================

PRIMARY_MODELS = {

    "1yr": {
        "model_name": "XGBoost",
        "strategy": "S2_BALANCED"
    },

    "3yr": {
        "model_name": "LightGBM",
        "strategy": "S3_THRESHOLD"
    }
}


# ==============================================================================
# 3. PRUNING CONFIGURATION
# ==============================================================================

# Remove the least important features in blocks of five.
PRUNING_STEP = 5


# Stop when validation AUROC drops by MORE than this amount
# relative to the original baseline.
PRUNING_DELTA = 0.01


# Never prune below this number of features.
PRUNING_MIN_FEATURES = 10


# Internal development/validation split.
VALIDATION_SIZE = 0.20


# Reproducibility.
RANDOM_STATE = 42


# Number of observations used for SHAP importance at each iteration.
SHAP_EVAL_SAMPLES = 1000


# Number of background observations for Tree SHAP.
SHAP_BACKGROUND_SIZE = 100


# Force CPU during refits if original model used GPU.
FORCE_CPU_FOR_PRUNING = True


# ==============================================================================
# 4. HELPERS
# ==============================================================================

def normalize_name(value):
    """
    Normalize strings for robust filename/model matching.
    """

    return re.sub(
        r"[^a-z0-9]+",
        "",
        str(value).lower()
    )


def load_dataframe(path):
    """
    Load Parquet with existence validation.
    """

    path = Path(path)

    if not path.exists():

        raise FileNotFoundError(
            f"Required file not found:\n{path}"
        )

    return pd.read_parquet(
        path,
        engine="pyarrow"
    )


def load_target(path):
    """
    Load Segment 5/6 y parquet and return 1D numpy array.
    """

    df = load_dataframe(path)


    if "y" in df.columns:

        y = df["y"]

    else:

        if df.shape[1] != 1:

            raise ValueError(
                f"Could not determine target column in:\n{path}"
            )

        y = df.iloc[:, 0]


    y = pd.to_numeric(
        y,
        errors="raise"
    )


    if y.isna().any():

        raise ValueError(
            f"Target contains missing values:\n{path}"
        )


    y = y.astype(int).to_numpy()


    if len(np.unique(y)) != 2:

        raise ValueError(
            f"Expected binary target, found classes: "
            f"{np.unique(y)}"
        )


    return y


def unwrap_model(obj):
    """
    Support direct estimators and common dictionary-wrapped models.
    """

    if (
        hasattr(obj, "fit")
        and hasattr(obj, "predict")
    ):

        return obj


    if isinstance(
        obj,
        dict
    ):

        for key in [
            "model",
            "estimator",
            "classifier",
            "best_model"
        ]:

            candidate = obj.get(
                key,
                None
            )

            if (
                candidate is not None
                and hasattr(candidate, "fit")
                and hasattr(candidate, "predict")
            ):

                return candidate


    raise TypeError(
        "Serialized file does not contain a recognizable fitted estimator."
    )


def load_model(path):
    """
    Load pickle/joblib estimator.
    """

    path = Path(path)


    # First try joblib because most sklearn-compatible model artifacts
    # are commonly serialized that way.
    try:

        import joblib

        obj = joblib.load(
            path
        )

        return unwrap_model(
            obj
        )

    except Exception:

        pass


    # Fallback to pickle.
    with open(
        path,
        "rb"
    ) as f:

        obj = pickle.load(
            f
        )


    return unwrap_model(
        obj
    )


def find_model_file(
    horizon,
    model_name,
    strategy
):
    """
    Locate the fitted model in models/{horizon}.
    """

    model_dir = (
        MODELS_ROOT
        / horizon
    )


    if not model_dir.exists():

        raise FileNotFoundError(
            f"Model directory not found:\n{model_dir}"
        )


    model_norm = normalize_name(
        model_name
    )

    strategy_norm = normalize_name(
        strategy
    )


    extensions = {
        ".pkl",
        ".pickle",
        ".joblib"
    }


    exact_matches = []
    model_matches = []


    for path in model_dir.rglob("*"):

        if (
            not path.is_file()
            or path.suffix.lower()
            not in extensions
        ):

            continue


        stem_norm = normalize_name(
            path.stem
        )


        if (
            model_norm in stem_norm
            and strategy_norm in stem_norm
        ):

            exact_matches.append(
                path
            )


        elif model_norm in stem_norm:

            model_matches.append(
                path
            )


    if exact_matches:

        exact_matches.sort(
            key=lambda p: len(p.name)
        )

        return exact_matches[0]


    if model_matches:

        model_matches.sort(
            key=lambda p: len(p.name)
        )

        warnings.warn(
            f"Could not find exact model+strategy filename for "
            f"{model_name}/{strategy}. "
            f"Using:\n{model_matches[0]}"
        )

        return model_matches[0]


    raise FileNotFoundError(
        f"Could not locate fitted model for:\n"
        f"  horizon  = {horizon}\n"
        f"  model    = {model_name}\n"
        f"  strategy = {strategy}\n"
        f"searched = {model_dir}"
    )


def predict_probability(
    model,
    X
):
    """
    Return positive-class probability.
    """

    if hasattr(
        model,
        "predict_proba"
    ):

        p = np.asarray(
            model.predict_proba(X)
        )


        if p.ndim == 2:

            if p.shape[1] >= 2:

                return p[:, 1]

            return p[:, 0]


        return p.reshape(-1)


    if hasattr(
        model,
        "decision_function"
    ):

        from scipy.special import expit

        score = np.asarray(
            model.decision_function(X)
        )

        return expit(score)


    pred = np.asarray(
        model.predict(X)
    )

    return pred.astype(float)


def prepare_refit_model(
    fitted_model
):
    """
    Clone the fitted model so that each pruning iteration starts from the
    same hyperparameter configuration but is freshly trained.
    """

    try:

        model = clone(
            fitted_model
        )

    except Exception:

        model = copy.deepcopy(
            fitted_model
        )


    if not FORCE_CPU_FOR_PRUNING:

        return model


    # --------------------------------------------------------------------------
    # Safely change common GPU settings to CPU for XGBoost / LightGBM /
    # CatBoost when those parameters exist.
    # --------------------------------------------------------------------------

    try:

        params = model.get_params()

    except Exception:

        return model


    cpu_params = {}


    # XGBoost
    if "device" in params:

        device = str(
            params["device"]
        ).lower()

        if device in {
            "cuda",
            "gpu"
        }:

            cpu_params["device"] = "cpu"


    if "tree_method" in params:

        tree_method = str(
            params["tree_method"]
        ).lower()

        if "gpu" in tree_method:

            cpu_params["tree_method"] = "hist"


    # LightGBM
    if "device_type" in params:

        if str(
            params["device_type"]
        ).lower() in {
            "gpu",
            "cuda"
        }:

            cpu_params[
                "device_type"
            ] = "cpu"


    # CatBoost
    if "task_type" in params:

        if str(
            params["task_type"]
        ).upper() == "GPU":

            cpu_params[
                "task_type"
            ] = "CPU"


    if cpu_params:

        try:

            model.set_params(
                **cpu_params
            )

        except Exception as exc:

            warnings.warn(
                f"Could not apply CPU overrides: {exc}"
            )


    return model


def validate_model_feature_alignment(
    model,
    X_train,
    X_test
):
    """
    Make sure the loaded model and model-ready data agree on features.
    """

    if hasattr(
        model,
        "feature_names_in_"
    ):

        expected = list(
            model.feature_names_in_
        )


        missing_train = [
            c for c in expected
            if c not in X_train.columns
        ]


        missing_test = [
            c for c in expected
            if c not in X_test.columns
        ]


        if missing_train:

            raise ValueError(
                "Model expects training features that are missing:\n"
                + "\n".join(
                    missing_train[:50]
                )
            )


        if missing_test:

            raise ValueError(
                "Model expects test features that are missing:\n"
                + "\n".join(
                    missing_test[:50]
                )
            )


        X_train = X_train[
            expected
        ].copy()


        X_test = X_test[
            expected
        ].copy()


    else:

        if (
            X_train.shape[1]
            != X_test.shape[1]
        ):

            raise ValueError(
                "X_train and X_test have different numbers of columns."
            )


    return (
        X_train,
        X_test
    )


# ==============================================================================
# 5. TREE SHAP
# ==============================================================================

def calculate_shap_importance(
    model,
    X,
    background_size,
    eval_samples
):
    """
    Calculate mean absolute Tree SHAP for the current feature set.

    Importance is calculated on the INTERNAL VALIDATION DATA, never on
    the final temporal test set.
    """

    # --------------------------------------------------------------------------
    # SHAP evaluation sample
    # --------------------------------------------------------------------------

    if (
        eval_samples is not None
        and len(X) > eval_samples
    ):

        X_eval = X.sample(
            n=eval_samples,
            random_state=RANDOM_STATE
        )

    else:

        X_eval = X.copy()


    # --------------------------------------------------------------------------
    # Background
    # --------------------------------------------------------------------------

    if (
        background_size is not None
        and len(X) > background_size
    ):

        background = X.sample(
            n=background_size,
            random_state=RANDOM_STATE
        )

    else:

        background = X.copy()


    # --------------------------------------------------------------------------
    # Preferred probability-scale Tree SHAP
    # --------------------------------------------------------------------------

    try:

        explainer = shap.TreeExplainer(
            model,
            data=background,
            feature_perturbation="interventional",
            model_output="probability"
        )


        try:

            explanation = explainer(
                X_eval,
                check_additivity=False
            )

        except TypeError:

            explanation = explainer(
                X_eval
            )


        values = np.asarray(
            explanation.values
        )


    except Exception as exc:

        warnings.warn(
            "Probability-scale Tree SHAP failed; "
            "falling back to model-native Tree SHAP.\n"
            f"Reason: {exc}"
        )


        explainer = shap.TreeExplainer(
            model
        )


        try:

            explanation = explainer(
                X_eval,
                check_additivity=False
            )

        except TypeError:

            explanation = explainer(
                X_eval
            )


        values = np.asarray(
            explanation.values
        )


    # --------------------------------------------------------------------------
    # Binary-output compatibility
    # --------------------------------------------------------------------------

    if values.ndim == 3:

        if values.shape[2] >= 2:

            values = values[:, :, 1]

        else:

            values = values[:, :, 0]


    if values.ndim != 2:

        raise ValueError(
            f"Unexpected SHAP shape: {values.shape}"
        )


    if values.shape[1] != X_eval.shape[1]:

        raise ValueError(
            "Number of SHAP features does not match X_eval."
        )


    mean_abs_shap = (
        np.abs(values)
        .mean(axis=0)
    )


    importance = pd.DataFrame(
        {
            "feature":
                X_eval.columns.tolist(),
            "mean_abs_shap":
                mean_abs_shap
        }
    )


    importance = (
        importance
        .sort_values(
            "mean_abs_shap",
            ascending=False
        )
        .reset_index(
            drop=True
        )
    )


    importance["rank"] = (
        np.arange(
            1,
            len(importance) + 1
        )
    )


    return (
        importance,
        X_eval
    )


# ==============================================================================
# 6. FIT + VALIDATE
# ==============================================================================

def fit_and_validate(
    template_model,
    X_fit,
    y_fit,
    X_val,
    y_val
):

    model = prepare_refit_model(
        template_model
    )


    model.fit(
        X_fit,
        y_fit
    )


    probabilities = predict_probability(
        model,
        X_val
    )


    auc = roc_auc_score(
        y_val,
        probabilities
    )


    return (
        model,
        probabilities,
        float(auc)
    )


# ==============================================================================
# 7. SINGLE-HORIZON SHAP PRUNING
# ==============================================================================

def run_shap_pruning(
    horizon
):

    config = PRIMARY_MODELS[
        horizon
    ]


    model_name = config[
        "model_name"
    ]

    strategy = config[
        "strategy"
    ]


    # ==========================================================================
    # DIRECTORIES
    # ==========================================================================

    model_ready_dir = (
        MODEL_READY_ROOT
        / horizon
    )


    output_dir = (
        PRUNING_ROOT
        / horizon
    )


    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    # ==========================================================================
    # LOAD DATA
    # ==========================================================================

    print(
        "\n"
        + "=" * 80
    )

    print(
        f"SHAP-GUIDED PRUNING — {horizon.upper()}"
    )

    print(
        "=" * 80
    )


    X_train = load_dataframe(
        model_ready_dir
        / "X_train_tree.parquet"
    )


    X_test = load_dataframe(
        model_ready_dir
        / "X_test_tree.parquet"
    )


    y_train = load_target(
        model_ready_dir
        / "y_train.parquet"
    )


    y_test = load_target(
        model_ready_dir
        / "y_test.parquet"
    )


    # ==========================================================================
    # ROW ALIGNMENT
    # ==========================================================================

    if len(X_train) != len(y_train):

        raise ValueError(
            f"{horizon}: X_train/y_train row mismatch."
        )


    if len(X_test) != len(y_test):

        raise ValueError(
            f"{horizon}: X_test/y_test row mismatch."
        )


    print(
        f"  X_train: {X_train.shape}"
    )

    print(
        f"  X_test : {X_test.shape}"
    )


    print(
        f"  y_train positive rate: "
        f"{y_train.mean():.4f}"
    )

    print(
        f"  y_test positive rate : "
        f"{y_test.mean():.4f}"
    )


    # ==========================================================================
    # LOAD FITTED SEGMENT 6 MODEL
    # ==========================================================================

    model_path = find_model_file(
        horizon,
        model_name,
        strategy
    )


    original_model = load_model(
        model_path
    )


    print(
        f"\n  Model: "
        f"{model_name}/{strategy}"
    )

    print(
        f"  Model file: "
        f"{model_path}"
    )


    # ==========================================================================
    # ALIGN MODEL FEATURES
    # ==========================================================================

    X_train, X_test = (
        validate_model_feature_alignment(
            original_model,
            X_train,
            X_test
        )
    )


    feature_names = (
        X_train.columns.tolist()
    )


    # ==========================================================================
    # SAVE FEATURE INPUT AUDIT
    # ==========================================================================

    pd.DataFrame(
        {
            "feature":
                feature_names
        }
    ).to_csv(
        output_dir
        / "baseline_feature_list.csv",
        index=False
    )


    # ==========================================================================
    # INTERNAL TRAIN / VALIDATION SPLIT
    #
    # This is inside the development/training period.
    # It is NOT the temporal test set.
    # ==========================================================================

    (
        X_dev,
        X_val,
        y_dev,
        y_val
    ) = train_test_split(
        X_train,
        y_train,
        test_size=VALIDATION_SIZE,
        stratify=y_train,
        random_state=RANDOM_STATE
    )


    print(
        f"\n  Internal development rows : "
        f"{len(X_dev):,}"
    )

    print(
        f"  Internal validation rows : "
        f"{len(X_val):,}"
    )


    # Save validation index information for auditability.
    pd.DataFrame(
        {
            "original_train_index":
                X_dev.index,
            "split":
                "internal_development"
        }
    ).to_csv(
        output_dir
        / "internal_development_indices.csv",
        index=False
    )


    pd.DataFrame(
        {
            "original_train_index":
                X_val.index,
            "split":
                "internal_validation"
        }
    ).to_csv(
        output_dir
        / "internal_validation_indices.csv",
        index=False
    )


    # ==========================================================================
    # BASELINE
    # ==========================================================================

    print(
        "\n"
        + "-" * 80
    )

    print(
        "BASELINE — INTERNAL VALIDATION"
    )

    print(
        "-" * 80
    )


    baseline_model, baseline_prob, baseline_auc = (
        fit_and_validate(
            original_model,
            X_dev,
            y_dev,
            X_val,
            y_val
        )
    )


    baseline_n_features = (
        len(feature_names)
    )


    print(
        f"  Baseline: "
        f"{baseline_n_features} features "
        f"→ validation AUROC="
        f"{baseline_auc:.4f}"
    )


    # ==========================================================================
    # PRUNING INITIALIZATION
    # ==========================================================================

    current_features = (
        feature_names.copy()
    )


    current_model = (
        baseline_model
    )


    stable_features = (
        current_features.copy()
    )


    stable_validation_auc = (
        baseline_auc
    )


    trajectory = [
        {
            "iteration": 0,
            "n_features":
                len(current_features),
            "validation_auroc":
                baseline_auc,
            "auroc_drop_vs_baseline":
                0.0,
            "removed_features":
                "",
            "status":
                "baseline"
        }
    ]


    iteration = 0


    # ==========================================================================
    # ITERATIVE SHAP PRUNING
    # ==========================================================================

    print(
        "\n"
        + "-" * 80
    )

    print(
        "ITERATIVE SHAP PRUNING"
    )

    print(
        "-" * 80
    )


    while (
        len(current_features)
        > PRUNING_MIN_FEATURES
    ):

        iteration += 1


        # ----------------------------------------------------------------------
        # Calculate SHAP importance on INTERNAL VALIDATION SET
        # ----------------------------------------------------------------------

        importance, X_shap_eval = (
            calculate_shap_importance(
                model=current_model,
                X=X_val[
                    current_features
                ],
                background_size=SHAP_BACKGROUND_SIZE,
                eval_samples=SHAP_EVAL_SAMPLES
            )
        )


        # Save importance for every iteration.
        importance.to_csv(
            output_dir
            / (
                f"shap_importance_iteration_"
                f"{iteration:02d}.csv"
            ),
            index=False
        )


        # ----------------------------------------------------------------------
        # Select least-important block
        # ----------------------------------------------------------------------

        n_remove = min(
            PRUNING_STEP,
            len(current_features)
            - PRUNING_MIN_FEATURES
        )


        remove_features = (
            importance
            .tail(
                n_remove
            )["feature"]
            .tolist()
        )


        candidate_features = [
            f
            for f in current_features
            if f not in remove_features
        ]


        # ----------------------------------------------------------------------
        # Refit candidate model
        # ----------------------------------------------------------------------

        candidate_model, candidate_prob, candidate_auc = (
            fit_and_validate(
                original_model,
                X_dev[
                    candidate_features
                ],
                y_dev,
                X_val[
                    candidate_features
                ],
                y_val
            )
        )


        candidate_drop = (
            baseline_auc
            - candidate_auc
        )


        # ----------------------------------------------------------------------
        # PRINT
        # ----------------------------------------------------------------------

        print(
            f"  Iteration {iteration:02d}: "
            f"{len(current_features):3d} → "
            f"{len(candidate_features):3d} features   "
            f"validation AUROC="
            f"{candidate_auc:.4f}   "
            f"drop="
            f"{candidate_drop:.4f}"
        )


        print(
            "      Removed:",
            ", ".join(
                remove_features
            )
        )


        # ----------------------------------------------------------------------
        # Stopping decision
        # ----------------------------------------------------------------------

        if (
            candidate_drop
            > PRUNING_DELTA
        ):

            trajectory.append(
                {
                    "iteration":
                        iteration,
                    "n_features":
                        len(candidate_features),
                    "validation_auroc":
                        candidate_auc,
                    "auroc_drop_vs_baseline":
                        candidate_drop,
                    "removed_features":
                        ";".join(
                            remove_features
                        ),
                    "status":
                        "rejected_stop"
                }
            )


            print(
                f"      STOP: validation AUROC drop "
                f"{candidate_drop:.4f} "
                f"> {PRUNING_DELTA:.4f}"
            )


            break


        # ----------------------------------------------------------------------
        # Candidate accepted
        # ----------------------------------------------------------------------

        trajectory.append(
            {
                "iteration":
                    iteration,
                "n_features":
                    len(candidate_features),
                "validation_auroc":
                    candidate_auc,
                "auroc_drop_vs_baseline":
                    candidate_drop,
                "removed_features":
                    ";".join(
                        remove_features
                    ),
                "status":
                    "accepted"
            }
        )


        stable_features = (
            candidate_features.copy()
        )


        stable_validation_auc = (
            candidate_auc
        )


        current_features = (
            candidate_features.copy()
        )


        current_model = (
            candidate_model
        )


        # ----------------------------------------------------------------------
        # If minimum feature count reached
        # ----------------------------------------------------------------------

        if (
            len(current_features)
            <= PRUNING_MIN_FEATURES
        ):

            print(
                "      STOP: minimum feature count reached."
            )

            break


    # ==========================================================================
    # SAVE TRAJECTORY
    # ==========================================================================

    trajectory_df = pd.DataFrame(
        trajectory
    )


    trajectory_df.to_csv(
        output_dir
        / "shap_pruning_trajectory.csv",
        index=False
    )


    # ==========================================================================
    # SHAP-STABLE FEATURE LIST
    # ==========================================================================

    selected_features = (
        stable_features
    )


    selected_n = (
        len(selected_features)
    )


    print(
        "\n"
        + "-" * 80
    )

    print(
        "SHAP-STABLE FEATURE SUBSET"
    )

    print(
        "-" * 80
    )


    print(
        f"  Selected features : "
        f"{selected_n}"
    )

    print(
        f"  Validation AUROC  : "
        f"{stable_validation_auc:.4f}"
    )

    print(
        f"  Baseline AUROC    : "
        f"{baseline_auc:.4f}"
    )

    print(
        f"  Validation drop   : "
        f"{baseline_auc - stable_validation_auc:.4f}"
    )


    selected_feature_df = pd.DataFrame(
        {
            "rank_in_full_model":
                [
                    feature_names.index(f) + 1
                    for f in selected_features
                ],
            "feature":
                selected_features
        }
    )


    selected_feature_df.to_csv(
        output_dir
        / "shap_selected_features.csv",
        index=False
    )


    # ==========================================================================
    # FINAL REFIT ON COMPLETE X_train
    #
    # This is the first point at which the FULL development/training data
    # is used with the selected subset.
    # ==========================================================================

    print(
        "\n"
        + "-" * 80
    )

    print(
        "FINAL PRUNED MODEL — TEMPORAL TEST EVALUATION"
    )

    print(
        "-" * 80
    )


    final_model = prepare_refit_model(
        original_model
    )


    final_model.fit(
        X_train[
            selected_features
        ],
        y_train
    )


    final_test_prob = predict_probability(
        final_model,
        X_test[
            selected_features
        ]
    )


    final_test_auc = roc_auc_score(
        y_test,
        final_test_prob
    )


    # ==========================================================================
    # ORIGINAL FULL MODEL — TEST AUROC
    #
    # This is the fitted Segment 6 model evaluated on the same temporal test.
    # It is used only as a reference for the final pruning comparison.
    # ==========================================================================

    original_test_prob = predict_probability(
        original_model,
        X_test
    )


    original_test_auc = roc_auc_score(
        y_test,
        original_test_prob
    )


    test_auc_drop = (
        original_test_auc
        - final_test_auc
    )


    print(
        f"  Original full model : "
        f"{baseline_n_features} features"
    )

    print(
        f"  Original test AUROC : "
        f"{original_test_auc:.4f}"
    )

    print(
        f"  Pruned model        : "
        f"{selected_n} features"
    )

    print(
        f"  Pruned test AUROC   : "
        f"{final_test_auc:.4f}"
    )

    print(
        f"  Test AUROC change   : "
        f"{final_test_auc - original_test_auc:+.4f}"
    )

    print(
        f"  Test AUROC drop     : "
        f"{test_auc_drop:.4f}"
    )


    # ==========================================================================
    # SAVE FINAL TEST PREDICTIONS
    # ==========================================================================

    final_predictions = pd.DataFrame(
        {
            "y_true":
                y_test,
            "y_prob_original":
                original_test_prob,
            "y_prob_pruned":
                final_test_prob
        }
    )


    final_predictions.to_csv(
        output_dir
        / "pruned_vs_original_test_predictions.csv",
        index=False
    )


    # ==========================================================================
    # SAVE FINAL MODEL
    # ==========================================================================

    final_model_path = (
        output_dir
        / (
            f"shap_pruned_model_"
            f"{horizon}.pkl"
        )
    )


    with open(
        final_model_path,
        "wb"
    ) as f:

        pickle.dump(
            final_model,
            f
        )


    # ==========================================================================
    # SUMMARY TABLE
    # ==========================================================================

    summary = pd.DataFrame(
        [
            {
                "horizon":
                    horizon,
                "model":
                    model_name,
                "strategy":
                    strategy,
                "baseline_n_features":
                    baseline_n_features,
                "selected_n_features":
                    selected_n,
                "features_removed":
                    baseline_n_features
                    - selected_n,
                "internal_validation_baseline_auroc":
                    baseline_auc,
                "internal_validation_pruned_auroc":
                    stable_validation_auc,
                "internal_validation_auroc_drop":
                    baseline_auc
                    - stable_validation_auc,
                "temporal_test_original_auroc":
                    original_test_auc,
                "temporal_test_pruned_auroc":
                    final_test_auc,
                "temporal_test_auroc_change":
                    final_test_auc
                    - original_test_auc,
                "temporal_test_auroc_drop":
                    test_auc_drop,
                "pruning_step":
                    PRUNING_STEP,
                "pruning_delta":
                    PRUNING_DELTA,
                "minimum_features":
                    PRUNING_MIN_FEATURES,
                "validation_size":
                    VALIDATION_SIZE,
                "random_state":
                    RANDOM_STATE
            }
        ]
    )


    summary.to_csv(
        output_dir
        / "shap_pruning_summary.csv",
        index=False
    )


    # ==========================================================================
    # SAVE A HUMAN-READABLE OUTCOME TXT
    # ==========================================================================

    outcome_text = f"""
SHAP-GUIDED PRUNING OUTCOME
===========================

Horizon                 : {horizon}
Model                   : {model_name}
Strategy                : {strategy}

Baseline features      : {baseline_n_features}
Selected features      : {selected_n}
Features removed       : {baseline_n_features - selected_n}

Internal validation
-------------------
Baseline AUROC         : {baseline_auc:.6f}
Pruned AUROC           : {stable_validation_auc:.6f}
AUROC drop             : {baseline_auc - stable_validation_auc:.6f}

Held-out temporal test
----------------------
Original model AUROC   : {original_test_auc:.6f}
Pruned model AUROC     : {final_test_auc:.6f}
AUROC change           : {final_test_auc - original_test_auc:+.6f}
AUROC drop             : {test_auc_drop:.6f}

Pruning configuration
---------------------
Step                    : {PRUNING_STEP}
Maximum allowed drop    : {PRUNING_DELTA}
Minimum features        : {PRUNING_MIN_FEATURES}
Internal validation     : {VALIDATION_SIZE:.0%}
Random state             : {RANDOM_STATE}

IMPORTANT:
The pruning stopping decision was made using internal validation
within the development/training cohort. The held-out temporal test
set was not used to determine the selected feature count.
"""


    with open(
        output_dir
        / "shap_pruning_outcome.txt",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            outcome_text.strip()
        )


    # ==========================================================================
    # RETURN
    # ==========================================================================

    return {
        "horizon":
            horizon,
        "model":
            model_name,
        "strategy":
            strategy,
        "baseline_features":
            baseline_n_features,
        "selected_features":
            selected_features,
        "selected_n":
            selected_n,
        "baseline_validation_auc":
            baseline_auc,
        "selected_validation_auc":
            stable_validation_auc,
        "original_test_auc":
            original_test_auc,
        "pruned_test_auc":
            final_test_auc,
        "test_auc_change":
            final_test_auc
            - original_test_auc,
        "test_auc_drop":
            test_auc_drop,
        "output_dir":
            output_dir
    }


# ==============================================================================
# 8. RUN 1-YEAR
# ==============================================================================

result_1y = run_shap_pruning(
    "1yr"
)


# ==============================================================================
# 9. RUN 3-YEAR
# ==============================================================================

result_3y = run_shap_pruning(
    "3yr"
)


# ==============================================================================
# 10. COMBINED SUMMARY
# ==============================================================================

combined = pd.DataFrame(
    [
        {
            "horizon":
                result_1y["horizon"],
            "model":
                result_1y["model"],
            "strategy":
                result_1y["strategy"],
            "baseline_features":
                result_1y["baseline_features"],
            "selected_features":
                result_1y["selected_n"],
            "features_removed":
                (
                    result_1y["baseline_features"]
                    - result_1y["selected_n"]
                ),
            "internal_validation_baseline_auc":
                result_1y["baseline_validation_auc"],
            "internal_validation_pruned_auc":
                result_1y["selected_validation_auc"],
            "temporal_test_original_auc":
                result_1y["original_test_auc"],
            "temporal_test_pruned_auc":
                result_1y["pruned_test_auc"],
            "temporal_test_auc_change":
                result_1y["test_auc_change"]
        },

        {
            "horizon":
                result_3y["horizon"],
            "model":
                result_3y["model"],
            "strategy":
                result_3y["strategy"],
            "baseline_features":
                result_3y["baseline_features"],
            "selected_features":
                result_3y["selected_n"],
            "features_removed":
                (
                    result_3y["baseline_features"]
                    - result_3y["selected_n"]
                ),
            "internal_validation_baseline_auc":
                result_3y["baseline_validation_auc"],
            "internal_validation_pruned_auc":
                result_3y["selected_validation_auc"],
            "temporal_test_original_auc":
                result_3y["original_test_auc"],
            "temporal_test_pruned_auc":
                result_3y["pruned_test_auc"],
            "temporal_test_auc_change":
                result_3y["test_auc_change"]
        }
    ]
)


combined.to_csv(
    PRUNING_ROOT
    / "shap_pruning_combined_summary.csv",
    index=False
)


print(
    "\n"
    + "=" * 80
)

print(
    "SHAP-GUIDED PRUNING COMPLETE"
)

print(
    "=" * 80
)


print(
    combined.to_string(
        index=False
    )
)


print(
    "\nOutputs:"
)

print(
    f"  1Y → {PRUNING_ROOT / '1yr'}"
)

print(
    f"  3Y → {PRUNING_ROOT / '3yr'}"
)

print(
    f"  Combined summary → "
    f"{PRUNING_ROOT / 'shap_pruning_combined_summary.csv'}"
)

================================================================================
SHAP-GUIDED PRUNING — 1YR
================================================================================
  X_train: (27431, 266)
  X_test : (13796, 266)
  y_train positive rate: 0.3671
  y_test positive rate : 0.3002

  Model: XGBoost/S2_BALANCED
  Model file: D:\Thesis\Thesis_parquet\models\1yr\model_XGBoost_S2_BALANCED.pkl

  Internal development rows : 21,944
  Internal validation rows : 5,487

--------------------------------------------------------------------------------
BASELINE — INTERNAL VALIDATION
--------------------------------------------------------------------------------
  Baseline: 266 features → validation AUROC=0.6938

--------------------------------------------------------------------------------
ITERATIVE SHAP PRUNING
--------------------------------------------------------------------------------
  Iteration 01: 266 → 261 features   validation AUROC=0.6928   drop=0.0010
      Removed: THORACIC_DGN_MISSING, DIAL_AFTER_LIST_MISSING, HIST_MI_MISSING, PERM_STATE_MISSING, HIST_HYPERTENS_DON_MISSING
  Iteration 02: 261 → 256 features   validation AUROC=0.6924   drop=0.0014
      Removed: PROTEIN_URINE_MISSING, PT_T4_DON_MISSING, HOME_STATE_DON_MISSING, DIAL_PRIOR_TX_MISSING, MALIG_TCR_MISSING
  Iteration 03: 256 → 251 features   validation AUROC=0.6924   drop=0.0014
      Removed: HIST_COCAINE_DON_MISSING, LV_EJECT_METH_MISSING, HIST_CIG_DON_MISSING, PT_DIURETICS_DON_MISSING, PT_T3_DON_MISSING
  Iteration 04: 251 → 246 features   validation AUROC=0.6928   drop=0.0010
      Removed: VENTILATOR_TRR, ECMO_TCR, DON_RETYP_MISSING, HIST_OTH_DRUG_DON_MISSING, LV_EJECT_MISSING
  Iteration 05: 246 → 241 features   validation AUROC=0.6943   drop=-0.0005
      Removed: COD_CAD_DON_MISSING, VENTILATOR_TCR, DIAL_TY_TCR, HIST_MI, PT_STEROIDS_DON_MISSING
  Iteration 06: 241 → 236 features   validation AUROC=0.6934   drop=0.0004
      Removed: HEMO_SYS_TCR_MISSING, DIAL_PRIOR_TX, HIST_CANCER_DON, INSULIN_DON_MISSING, CRSMATCH_DONE_MISSING
  Iteration 07: 236 → 231 features   validation AUROC=0.6918   drop=0.0020
      Removed: VDRL_DON_MISSING, ARGININE_DON_MISSING, TRANSFUS_TERM_DON_MISSING, CITIZENSHIP, INOTROP_VASO_SYS_TCR_MISSING
  Iteration 08: 231 → 226 features   validation AUROC=0.6939   drop=-0.0001
      Removed: DIAL_AFTER_LIST, VENT_SUPPORT_AFTER_LIST_MISSING, LV_EJECT_METH, ISCHTIME_MISSING, TBILI_MISSING
  Iteration 09: 226 → 221 features   validation AUROC=0.6930   drop=0.0008
      Removed: INOTROP_VASO_CO_TCR_MISSING, CITIZENSHIP_DON_MISSING, STEROID_MISSING, HEPARIN_DON_MISSING, CLIN_INFECT_DON_MISSING
  Iteration 10: 221 → 216 features   validation AUROC=0.6930   drop=0.0008
      Removed: HEMO_CO_TCR_MISSING, VAD_DEVICE_TY_TCR_MISSING, HEMO_PA_DIA_TCR_MISSING, HEP_C_ANTI_DON, CITIZENSHIP_DON
  Iteration 11: 216 → 211 features   validation AUROC=0.6933   drop=0.0004
      Removed: CDC_RISK_HIV_DON_MISSING, ETHNICITY, CIG_USE_MISSING, PT_T3_DON, IMPL_DEFIBRIL_MISSING
  Iteration 12: 211 → 206 features   validation AUROC=0.6933   drop=0.0004
      Removed: PCO2_DON_MISSING, WORK_INCOME_TCR_MISSING, HIST_DIABETES_DON, VDRL_DON, INFECT_IV_DRUG_TRR_MISSING
  Iteration 13: 206 → 201 features   validation AUROC=0.6932   drop=0.0006
      Removed: TRANSFUSIONS_MISSING, ALCOHOL_HEAVY_DON_MISSING, MALIG_TCR, ECD_DONOR, FUNC_STAT_TCR_MISSING
  Iteration 14: 201 → 196 features   validation AUROC=0.6935   drop=0.0003
      Removed: HBV_CORE_DON, HEMO_PCW_TCR_MISSING, PRIOR_CARD_SURG_TCR_MISSING, INOTROP_VASO_PCW_TCR_MISSING, CARDARREST_NEURO
  Iteration 15: 196 → 191 features   validation AUROC=0.6935   drop=0.0003
      Removed: DIABETES_DON, HEMATOCRIT_DON_MISSING, MALIG, HEMO_PA_DIA_TRR_MISSING, HCV_SEROSTATUS_MISSING
  Iteration 16: 191 → 186 features   validation AUROC=0.6936   drop=0.0002
      Removed: OTHER_INF_DON_MISSING, PO2_MISSING, FUNC_STAT_TRR_MISSING, OTHER_INF_DON, PH_DON_MISSING
  Iteration 17: 186 → 181 features   validation AUROC=0.6927   drop=0.0011
      Removed: CHEST_XRAY_DON_MISSING, HIST_HYPERTENS_DON, CANCER_SITE_DON, BLOOD_INF_DON, DRMIS_MISSING
  Iteration 18: 181 → 176 features   validation AUROC=0.6941   drop=-0.0003
      Removed: HEMO_PCW_TRR_MISSING, HIST_OTH_DRUG_DON, URINE_INF_DON, HCV_SEROSTATUS, HBV_SUR_ANTIGEN_MISSING
  Iteration 19: 176 → 171 features   validation AUROC=0.6930   drop=0.0008
      Removed: ABO_MAT, WORK_INCOME_TCR, EBV_IGG_CAD_DON_MISSING, INOTROP_VASO_MN_TCR_MISSING, PO2_DONE_DON_MISSING
  Iteration 20: 171 → 166 features   validation AUROC=0.6936   drop=0.0002
      Removed: CONTIN_OTH_DRUG_DON_MISSING, INOTROP_SUPPORT_DON_MISSING, SENSITIZATION_PEAK_MISSING, ANTIHYPE_DON, IABP_TCR
  Iteration 21: 166 → 161 features   validation AUROC=0.6933   drop=0.0005
      Removed: BRONCHO_RT_DON, BRONCHO_LT_DON, INFECT_IV_DRUG_TRR, HEPARIN_DON, BRONCHO_RT_DON_MISSING
  Iteration 22: 161 → 156 features   validation AUROC=0.6949   drop=-0.0011
      Removed: CLIN_INFECT_DON, EDUCATION_MISSING, COD_CAD_DON, VASODIL_DON, HEMO_CO_TRR_MISSING
  Iteration 23: 156 → 151 features   validation AUROC=0.6924   drop=0.0014
      Removed: HIST_COCAINE_DON, STEROID, WORK_INCOME_TRR_MISSING, PULM_CATH_DON, PT_DIURETICS_DON
  Iteration 24: 151 → 146 features   validation AUROC=0.6920   drop=0.0018
      Removed: SENSITIZATION_RECENT_MISSING, PO2_FIO2_DON_MISSING, MED_COND_TRR, TATTOOS, AMIS
  Iteration 25: 146 → 141 features   validation AUROC=0.6917   drop=0.0021
      Removed: CDC_RISK_HIV_DON, HEMO_PA_MN_TCR_MISSING, CORONARY_ANGIO, IMPL_DEFIBRIL, HEMO_SYS_TRR_MISSING
  Iteration 26: 141 → 136 features   validation AUROC=0.6899   drop=0.0039
      Removed: VAD_DEVICE_TY_TCR, VENT_SUPPORT_AFTER_LIST, PO2_DONE_DON, EBV_IGG_CAD_DON, ARGININE_DON
  Iteration 27: 136 → 131 features   validation AUROC=0.6887   drop=0.0050
      Removed: OTH_LIFE_SUP_TCR, HBV_CORE_MISSING, PRIOR_CARD_SURG_TYPE_TCR_MISSING, PROTEIN_URINE, HBV_SUR_ANTIGEN
  Iteration 28: 131 → 126 features   validation AUROC=0.6896   drop=0.0041
      Removed: INOTROP_VASO_PCW_TCR, DEATH_CIRCUM_DON, EXERCISE_O2_MISSING, DR53, TCR_DUR_ABSTAIN_MISSING
  Iteration 29: 126 → 121 features   validation AUROC=0.6911   drop=0.0027
      Removed: INOTROP_VASO_CO_TCR, HIST_CIG_DON, CONTIN_OTH_DRUG_DON, BRONCHO_LT_DON_MISSING, BMIS_MISSING
  Iteration 30: 121 → 116 features   validation AUROC=0.6917   drop=0.0021
      Removed: DA1, DEATH_MECH_DON, INSULIN_DON, DDAVP_DON, ABO
  Iteration 31: 116 → 111 features   validation AUROC=0.6920   drop=0.0018
      Removed: LV_EJECT, DR52, GENDER_DON, WORK_INCOME_TRR, CRSMATCH_DONE
  Iteration 32: 111 → 106 features   validation AUROC=0.6892   drop=0.0046
      Removed: INOTROPES_TCR, PULM_INF_DON, BMIS, INOTROP_VASO_MN_TCR, PT_T4_DON
  Iteration 33: 106 → 101 features   validation AUROC=0.6885   drop=0.0053
      Removed: PRI_PAYMENT_TCR, SENSITIZATION_TIER_MISSING, INOTROP_VASO_SYS_TCR, PO2_FIO2_DON, TRANSFUS_TERM_DON
  Iteration 34: 101 →  96 features   validation AUROC=0.6887   drop=0.0051
      Removed: INOTROP_SUPPORT_DON, TRANSFUSIONS, DDR1, AMIS_MISSING, HLAMIS_MISSING
  Iteration 35:  96 →  91 features   validation AUROC=0.6875   drop=0.0063
      Removed: ETHCAT, HBV_CORE, DB2, PROC_TY_HR, PCO2_DON
  Iteration 36:  91 →  86 features   validation AUROC=0.6891   drop=0.0047
      Removed: EBV_IGM_CAD_DON, DA2, HEMO_PA_MN_TRR_MISSING, EDUCATION, DIAB
  Iteration 37:  86 →  81 features   validation AUROC=0.6871   drop=0.0067
      Removed: TBILI, INO_PROCURE_AGENT_1_MISSING, HEMO_PA_DIA_TCR, BW4, SGPT_DON
  Iteration 38:  81 →  76 features   validation AUROC=0.6864   drop=0.0074
      Removed: ABO_DON, DDR2, AGE_DON, THORACIC_DGN, ETHCAT_DON
  Iteration 39:  76 →  71 features   validation AUROC=0.6857   drop=0.0081
      Removed: C1, SGOT_DON, HEMO_SYS_TCR, EBV_SEROSTATUS_MISSING, PRIOR_CARD_SURG_TCR
  Iteration 40:  71 →  66 features   validation AUROC=0.6857   drop=0.0081
      Removed: BMI_DON_CALC, PH_DON, EXERCISE_O2, RA1, DR51
  Iteration 41:  66 →  61 features   validation AUROC=0.6855   drop=0.0083
      Removed: HEMATOCRIT_DON, SENSITIZATION_RECENT, BUN_DON, SENSITIZATION_TIER, HEMO_PCW_TRR
  Iteration 42:  61 →  56 features   validation AUROC=0.6864   drop=0.0074
      Removed: ALCOHOL_HEAVY_DON, CIG_USE, IABP_TRR, LIFE_SUP_TCR, INO_PROCURE_AGENT_1
  Iteration 43:  56 →  51 features   validation AUROC=0.6840   drop=0.0098
      Removed: INIT_STAT, END_STAT, CREAT_DON, OTH_LIFE_SUP_TRR, EBV_IGM_CAD_DON_MISSING
  Iteration 44:  51 →  46 features   validation AUROC=0.6824   drop=0.0114
      Removed: DIAG, TBILI_DON, BW6, TOT_SERUM_ALBUM, FUNC_STAT_TCR
      STOP: validation AUROC drop 0.0114 > 0.0100

--------------------------------------------------------------------------------
SHAP-STABLE FEATURE SUBSET
--------------------------------------------------------------------------------
  Selected features : 51
  Validation AUROC  : 0.6840
  Baseline AUROC    : 0.6938
  Validation drop   : 0.0098

--------------------------------------------------------------------------------
FINAL PRUNED MODEL — TEMPORAL TEST EVALUATION
--------------------------------------------------------------------------------
  Original full model : 266 features
  Original test AUROC : 0.6276
  Pruned model        : 51 features
  Pruned test AUROC   : 0.6279
  Test AUROC change   : +0.0003
  Test AUROC drop     : -0.0003

================================================================================
SHAP-GUIDED PRUNING — 3YR
================================================================================
  X_train: (28596, 269)
  X_test : (7568, 269)
  y_train positive rate: 0.4404
  y_test positive rate : 0.3932

  Model: LightGBM/S3_THRESHOLD
  Model file: D:\Thesis\Thesis_parquet\models\3yr\model_LightGBM_S3_THRESHOLD.pkl

  Internal development rows : 22,876
  Internal validation rows : 5,720

--------------------------------------------------------------------------------
BASELINE — INTERNAL VALIDATION
--------------------------------------------------------------------------------
  Baseline: 269 features → validation AUROC=0.7020

--------------------------------------------------------------------------------
ITERATIVE SHAP PRUNING
--------------------------------------------------------------------------------

 98%|===================| 984/1000 [00:26<00:00]

  Iteration 01: 269 → 264 features   validation AUROC=0.7041   drop=-0.0021
      Removed: PT_STEROIDS_DON_MISSING, LV_EJECT_METH, PT_DIURETICS_DON_MISSING, PT_T4_DON_MISSING, HIST_HYPERTENS_DON_MISSING

 97%|=================== | 971/1000 [00:25<00:00]

  Iteration 02: 264 → 259 features   validation AUROC=0.7033   drop=-0.0013
      Removed: PROTEIN_URINE_MISSING, HIST_OTH_DRUG_DON_MISSING, PT_T3_DON_MISSING, HOME_STATE_DON_MISSING, HIST_MI_MISSING

 97%|=================== | 972/1000 [00:25<00:00]

  Iteration 03: 259 → 254 features   validation AUROC=0.7022   drop=-0.0002
      Removed: HIST_CIG_DON_MISSING, DIAL_PRIOR_TX_MISSING, DIAL_AFTER_LIST_MISSING, SGPT_DON_MISSING, TBILI_DON_MISSING

 99%|===================| 994/1000 [00:26<00:00]

  Iteration 04: 254 → 249 features   validation AUROC=0.7026   drop=-0.0007
      Removed: VDRL_DON_MISSING, HIST_MI, HIST_COCAINE_DON_MISSING, CLIN_INFECT_DON_MISSING, CRSMATCH_DONE_MISSING

 97%|=================== | 968/1000 [00:28<00:00]

  Iteration 05: 249 → 244 features   validation AUROC=0.7036   drop=-0.0017
      Removed: DON_RETYP_MISSING, VENT_SUPPORT_AFTER_LIST_MISSING, INOTROP_VASO_CO_TCR_MISSING, STEROID_MISSING, CREAT_TRR_MISSING

 98%|===================| 978/1000 [00:25<00:00]

  Iteration 06: 244 → 239 features   validation AUROC=0.7035   drop=-0.0015
      Removed: CANCER_SITE_DON, DIAL_TY_TCR, COD_CAD_DON_MISSING, HBV_CORE_DON, TBILI_MISSING

 97%|=================== | 969/1000 [00:27<00:00]

  Iteration 07: 239 → 234 features   validation AUROC=0.7028   drop=-0.0009
      Removed: CITIZENSHIP_DON_MISSING, CITIZENSHIP, HEP_C_ANTI_DON, HEMO_SYS_TCR_MISSING, VAD_DEVICE_TY_TCR_MISSING

100%|===================| 997/1000 [00:28<00:00]

  Iteration 08: 234 → 229 features   validation AUROC=0.7028   drop=-0.0008
      Removed: THORACIC_DGN_MISSING, TRANSFUSIONS_MISSING, VENTILATOR_TRR, DIABETES_DON, HEMO_CO_TCR_MISSING

100%|===================| 999/1000 [00:27<00:00]

  Iteration 09: 229 → 224 features   validation AUROC=0.7022   drop=-0.0002
      Removed: INFECT_IV_DRUG_TRR_MISSING, VDRL_DON, HIST_CANCER_DON, PT_T3_DON, INOTROP_VASO_SYS_TCR_MISSING

 99%|===================| 987/1000 [00:27<00:00]

  Iteration 10: 224 → 219 features   validation AUROC=0.7032   drop=-0.0012
      Removed: HBV_SUR_ANTIGEN_MISSING, DRMIS_MISSING, CARDARREST_NEURO, ETHNICITY, MALIG

 97%|=================== | 968/1000 [00:27<00:00]

  Iteration 11: 219 → 214 features   validation AUROC=0.7024   drop=-0.0005
      Removed: ANTIHYPE_DON, IABP_TCR, HIST_DIABETES_DON, VENTILATOR_TCR, WORK_INCOME_TCR_MISSING

100%|===================| 999/1000 [00:27<00:00]

  Iteration 12: 214 → 209 features   validation AUROC=0.7038   drop=-0.0018
      Removed: CITIZENSHIP_DON, URINE_INF_DON, MALIG_TCR_MISSING, ISCHTIME_MISSING, LV_EJECT_MISSING

 97%|=================== | 972/1000 [00:27<00:00]

  Iteration 13: 209 → 204 features   validation AUROC=0.7019   drop=0.0001
      Removed: BRONCHO_RT_DON_MISSING, ECD_DONOR, EBV_IGG_CAD_DON_MISSING, HEMO_PA_DIA_TCR_MISSING, ARGININE_DON_MISSING

 98%|===================| 975/1000 [00:27<00:00]

  Iteration 14: 204 → 199 features   validation AUROC=0.7014   drop=0.0006
      Removed: ALCOHOL_HEAVY_DON_MISSING, DIAL_PRIOR_TX, OTHER_INF_DON, HEMO_PCW_TCR_MISSING, PRIOR_CARD_SURG_TYPE_TCR_MISSING

 97%|=================== | 966/1000 [00:26<00:00]

  Iteration 15: 199 → 194 features   validation AUROC=0.7037   drop=-0.0017
      Removed: HEMO_SYS_TRR_MISSING, ABO_MAT, CONTIN_OTH_DRUG_DON_MISSING, LV_EJECT_METH_MISSING, HIST_OTH_DRUG_DON

 97%|=================== | 970/1000 [00:27<00:00]

  Iteration 16: 194 → 189 features   validation AUROC=0.7025   drop=-0.0005
      Removed: EDUCATION_MISSING, MALIG_TCR, INOTROP_VASO_PCW_TCR_MISSING, HIST_CIG_DON, OTHER_INF_DON_MISSING

 99%|===================| 993/1000 [00:27<00:00]

  Iteration 17: 189 → 184 features   validation AUROC=0.7008   drop=0.0011
      Removed: HIST_COCAINE_DON, BRONCHO_LT_DON_MISSING, AMIS, CDC_RISK_HIV_DON_MISSING, TATTOOS

 99%|===================| 991/1000 [00:27<00:00]

  Iteration 18: 184 → 179 features   validation AUROC=0.7030   drop=-0.0010
      Removed: BRONCHO_RT_DON, BRONCHO_LT_DON, WORK_INCOME_TCR, HEMO_PA_DIA_TRR_MISSING, HBV_SUR_ANTIGEN

 97%|=================== | 969/1000 [00:26<00:00]

  Iteration 19: 179 → 174 features   validation AUROC=0.7028   drop=-0.0008
      Removed: INOTROP_VASO_CO_TCR, INFECT_IV_DRUG_TRR, DIAL_AFTER_LIST, PT_DIURETICS_DON, PROTEIN_URINE

 97%|=================== | 971/1000 [00:28<00:00]

  Iteration 20: 174 → 169 features   validation AUROC=0.7033   drop=-0.0013
      Removed: IMPL_DEFIBRIL_MISSING, COD_CAD_DON, CLIN_INFECT_DON, HEMO_CO_TRR_MISSING, INOTROP_VASO_MN_TCR_MISSING

 97%|=================== | 967/1000 [00:27<00:00]

  Iteration 21: 169 → 164 features   validation AUROC=0.7056   drop=-0.0037
      Removed: INOTROP_VASO_SYS_TCR, INO_PROCURE_AGENT_1_MISSING, BLOOD_INF_DON, CHEST_XRAY_DON_MISSING, CDC_RISK_HIV_DON

 98%|===================| 982/1000 [00:28<00:00]

  Iteration 22: 164 → 159 features   validation AUROC=0.7040   drop=-0.0020
      Removed: CHEST_XRAY_DON, CONTIN_OTH_DRUG_DON, HEMO_PA_MN_TRR_MISSING, HIST_HYPERTENS_DON, HEPARIN_DON_MISSING

 97%|=================== | 969/1000 [00:28<00:00]

  Iteration 23: 159 → 154 features   validation AUROC=0.7023   drop=-0.0003
      Removed: HCV_SEROSTATUS_MISSING, STEROID, PO2_DONE_DON_MISSING, SENSITIZATION_TIER_MISSING, CORONARY_ANGIO

 98%|===================| 977/1000 [00:28<00:00]

  Iteration 24: 154 → 149 features   validation AUROC=0.7029   drop=-0.0009
      Removed: DDAVP_DON, EBV_IGG_CAD_DON, VASODIL_DON, HEMO_PCW_TRR_MISSING, DIAB

 98%|===================| 980/1000 [00:28<00:00]

  Iteration 25: 149 → 144 features   validation AUROC=0.7037   drop=-0.0017
      Removed: SUD_DEATH_MISSING, PT_T4_DON, HLAMIS_MISSING, GENDER_DON, AMIS_MISSING

100%|===================| 996/1000 [00:28<00:00]

  Iteration 26: 144 → 139 features   validation AUROC=0.7036   drop=-0.0016
      Removed: PRIOR_CARD_SURG_TCR_MISSING, PULM_INF_DON, HEMO_PA_MN_TCR_MISSING, FUNC_STAT_TRR_MISSING, PO2_MISSING

 97%|=================== | 972/1000 [00:27<00:00]

  Iteration 27: 139 → 134 features   validation AUROC=0.7019   drop=0.0000
      Removed: ARGININE_DON, PULM_CATH_DON, MED_COND_TRR, PH_DON_MISSING, TCR_DUR_ABSTAIN_MISSING

 98%|===================| 975/1000 [00:26<00:00]

  Iteration 28: 134 → 129 features   validation AUROC=0.7030   drop=-0.0011
      Removed: DEATH_CIRCUM_DON, INOTROP_VASO_PCW_TCR, ALCOHOL_HEAVY_DON, DEATH_MECH_DON, DDR1

 99%|===================| 989/1000 [00:26<00:00]

  Iteration 29: 129 → 124 features   validation AUROC=0.7015   drop=0.0005
      Removed: HEMO_PA_DIA_TCR, VENT_SUPPORT_AFTER_LIST, EXERCISE_O2_MISSING, DA2, DB2

 97%|=================== | 974/1000 [00:28<00:00]

  Iteration 30: 124 → 119 features   validation AUROC=0.7005   drop=0.0015
      Removed: ETHCAT_DON, HCV_SEROSTATUS, INSULIN_DON_MISSING, DA1, FUNC_STAT_TCR_MISSING

100%|===================| 996/1000 [00:27<00:00]

  Iteration 31: 119 → 114 features   validation AUROC=0.7009   drop=0.0011
      Removed: PROC_TY_HR, INOTROP_VASO_MN_TCR, DR52, HEMATOCRIT_DON_MISSING, SENSITIZATION_PEAK_MISSING

 97%|=================== | 971/1000 [00:26<00:00]

  Iteration 32: 114 → 109 features   validation AUROC=0.6997   drop=0.0023
      Removed: SENSITIZATION_RECENT, VAD_DEVICE_TY_TCR, IABP_TRR, BMIS_MISSING, PO2_DONE_DON

 98%|===================| 982/1000 [00:26<00:00]

  Iteration 33: 109 → 104 features   validation AUROC=0.6966   drop=0.0054
      Removed: IMPL_DEFIBRIL, EBV_IGM_CAD_DON_MISSING, HEPARIN_DON, LV_EJECT, CIG_USE_MISSING

 98%|===================| 982/1000 [00:28<00:00]

  Iteration 34: 104 →  99 features   validation AUROC=0.6989   drop=0.0030
      Removed: ABO_DON, HEMO_SYS_TRR, TRANSFUSIONS, SUD_DEATH, SGOT_DON

 98%|===================| 975/1000 [00:27<00:00]

  Iteration 35:  99 →  94 features   validation AUROC=0.6984   drop=0.0036
      Removed: EBV_IGM_CAD_DON, RB1, DR51, LIFE_SUP_TCR, INOTROPES_TCR

 99%|===================| 990/1000 [00:27<00:00]

  Iteration 36:  94 →  89 features   validation AUROC=0.7009   drop=0.0011
      Removed: SGPT_DON, TBILI, BUN_DON, HEMO_PA_MN_TCR, INOTROP_SUPPORT_DON_MISSING

 97%|=================== | 970/1000 [00:28<00:00]

  Iteration 37:  89 →  84 features   validation AUROC=0.7013   drop=0.0007
      Removed: RDR1, EXERCISE_O2, WGT_KG_DON_CALC, PCO2_DON, CRSMATCH_DONE

 97%|=================== | 974/1000 [00:26<00:00]

  Iteration 38:  84 →  79 features   validation AUROC=0.7002   drop=0.0017
      Removed: HBV_CORE_MISSING, SENSITIZATION_RECENT_MISSING, EBV_SEROSTATUS_MISSING, END_STAT, ABO

 99%|===================| 986/1000 [00:29<00:00]

  Iteration 39:  79 →  74 features   validation AUROC=0.7030   drop=-0.0011
      Removed: DIAG, CREAT_TRR, PH_DON, HEMO_PCW_TCR, DDR2

 97%|=================== | 966/1000 [00:28<00:00]

  Iteration 40:  74 →  69 features   validation AUROC=0.7006   drop=0.0013
      Removed: RDR2, SENSITIZATION_PEAK, PO2_FIO2_DON, PRI_PAYMENT_TCR, OTH_LIFE_SUP_TRR

100%|===================| 999/1000 [00:30<00:00]

  Iteration 41:  69 →  64 features   validation AUROC=0.6989   drop=0.0031
      Removed: ETHCAT, PO2_FIO2_DON_MISSING, C2, INSULIN_DON, HEMO_PA_MN_TRR

100%|===================| 997/1000 [00:31<00:00]

  Iteration 42:  64 →  59 features   validation AUROC=0.7011   drop=0.0009
      Removed: CIG_USE, BMIS, THORACIC_DGN, DAYSWAIT_CHRON, HEMO_SYS_TCR

 97%|=================== | 974/1000 [00:26<00:00]

  Iteration 43:  59 →  54 features   validation AUROC=0.7017   drop=0.0002
      Removed: RA1, BMI_DON_CALC, CREAT_DON, INIT_STAT, TRANSFUS_TERM_DON_MISSING

 98%|===================| 984/1000 [00:29<00:00]

  Iteration 44:  54 →  49 features   validation AUROC=0.7002   drop=0.0018
      Removed: DR53, INOTROP_SUPPORT_DON, OTH_LIFE_SUP_TCR, C1, DQ2

 98%|===================| 984/1000 [00:26<00:00]

  Iteration 45:  49 →  44 features   validation AUROC=0.7009   drop=0.0011
      Removed: LIFE_SUP_TRR, RB2, HEMO_PCW_TRR, SENSITIZATION_SOURCE, HEMATOCRIT_DON

 98%|===================| 975/1000 [00:26<00:00]

  Iteration 46:  44 →  39 features   validation AUROC=0.7021   drop=-0.0001
      Removed: PRIOR_CARD_SURG_TCR, TBILI_DON, BW4, TRANSFUS_TERM_DON, HEMO_CO_TCR

 99%|===================| 991/1000 [00:26<00:00]

  Iteration 47:  39 →  34 features   validation AUROC=0.7021   drop=-0.0002
      Removed: WORK_INCOME_TRR_MISSING, TCR_DUR_ABSTAIN, INO_PROCURE_AGENT_1, HGT_CM_DON_CALC, AGE_DON

 96%|=================== | 963/1000 [00:25<00:00]

  Iteration 48:  34 →  29 features   validation AUROC=0.7049   drop=-0.0030
      Removed: HLAMIS, PO2, TOT_SERUM_ALBUM, TCR_DGN, HBV_CORE

100%|===================| 999/1000 [00:26<00:00]

  Iteration 49:  29 →  24 features   validation AUROC=0.7008   drop=0.0011
      Removed: PT_STEROIDS_DON, RA2, EDUCATION, DISTANCE, SHARE_TY

 96%|=================== | 961/1000 [00:25<00:01]

  Iteration 50:  24 →  19 features   validation AUROC=0.6999   drop=0.0020
      Removed: WGT_KG_CALC, DRMIS, DB1, HEMO_PA_DIA_TRR, SENSITIZATION_TIER

 99%|===================| 992/1000 [00:25<00:00]

  Iteration 51:  19 →  14 features   validation AUROC=0.6985   drop=0.0034
      Removed: BW6, TOT_SERUM_ALBUM_MISSING, HEMO_CO_TRR, FUNC_STAT_TCR, PRIOR_CARD_SURG_TYPE_TCR

 98%|===================| 984/1000 [00:24<00:00]

  Iteration 52:  14 →  10 features   validation AUROC=0.6972   drop=0.0048
      Removed: ISCHTIME, WGT_KG_TCR, PRI_PAYMENT_TRR, DQ1
      STOP: minimum feature count reached.

--------------------------------------------------------------------------------
SHAP-STABLE FEATURE SUBSET
--------------------------------------------------------------------------------
  Selected features : 10
  Validation AUROC  : 0.6972
  Baseline AUROC    : 0.7020
  Validation drop   : 0.0048

--------------------------------------------------------------------------------
FINAL PRUNED MODEL — TEMPORAL TEST EVALUATION
--------------------------------------------------------------------------------
  Original full model : 269 features
  Original test AUROC : 0.6664
  Pruned model        : 10 features
  Pruned test AUROC   : 0.6412
  Test AUROC change   : -0.0252
  Test AUROC drop     : 0.0252

================================================================================
SHAP-GUIDED PRUNING COMPLETE
================================================================================
horizon    model     strategy  baseline_features  selected_features  features_removed  internal_validation_baseline_auc  internal_validation_pruned_auc  temporal_test_original_auc  temporal_test_pruned_auc  temporal_test_auc_change
    1yr  XGBoost  S2_BALANCED                266                 51               215                          0.693789                        0.683978                    0.627626                  0.627937                  0.000311
    3yr LightGBM S3_THRESHOLD                269                 10               259                          0.701956                        0.697194                    0.666403                  0.641154                 -0.025249

Outputs:
  1Y → D:\Thesis\Thesis_parquet\results\interpretability\pruning\1yr
  3Y → D:\Thesis\Thesis_parquet\results\interpretability\pruning\3yr
  Combined summary → D:\Thesis\Thesis_parquet\results\interpretability\pruning\shap_pruning_combined_summary.csv

In [ ]:
# ==============================================================================
# SPEARMAN rho + p-VALUES + FIGURES
# ==============================================================================
#
# PURPOSE
# -------
# Calculate train-only:
#   1. Spearman's rho
#   2. Two-sided p-value
#   3. Pairwise complete sample size (n)
#   4. Benjamini-Hochberg FDR q-value
#
# FIGURES
# -------
#   A. Top Spearman correlation heatmap
#   B. Top correlated feature-pair bar chart
#   C. |rho| vs -log10(p) significance plot
#
# IMPORTANT
# ---------
# This uses the PRE-CORRELATION predictor data.
# It does NOT use X_train_tree because that matrix contains transformed
# categorical variables and missingness indicators.
#
# Feature-removal decisions remain separate from this analysis.
# ==============================================================================

import os
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import spearmanr


# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

BASE = Path(
    "/content/drive/MyDrive/Thesis_parquet"
)

OUTPUT_ROOT = (
    BASE
    / "results"
    / "correlation_p_values"
)

OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


SPLIT_DATE = pd.Timestamp(
    "2018-10-18"
)

MISSING_THRESHOLD = 0.75

CORRELATION_THRESHOLD = 0.80

P_VALUE_ALPHA = 0.05

TOP_HEATMAP_FEATURES = 25

TOP_PAIRS_TO_PLOT = 20

FIG_DPI = 300


# Use the same FORCE_CATEGORICAL_COLS from Segment 5 if it exists.
FORCE_CATEGORICAL_COLS = globals().get(
    "FORCE_CATEGORICAL_COLS",
    set()
)


# ==============================================================================
# 2. BENJAMINI-HOCHBERG FDR
# ==============================================================================

def benjamini_hochberg(p_values):

    p_values = np.asarray(
        p_values,
        dtype=float
    )

    q_values = np.full(
        len(p_values),
        np.nan
    )

    valid = np.isfinite(
        p_values
    )

    if not valid.any():
        return q_values

    p = p_values[valid]

    order = np.argsort(
        p
    )

    ranked = p[order]

    m = len(ranked)

    q_sorted = (
        ranked
        * m
        / np.arange(
            1,
            m + 1
        )
    )

    # Enforce monotonicity from the largest p-value backwards.
    q_sorted = np.minimum.accumulate(
        q_sorted[::-1]
    )[::-1]

    q_sorted = np.clip(
        q_sorted,
        0,
        1
    )

    q_original_order = np.empty_like(
        q_sorted
    )

    q_original_order[order] = (
        q_sorted
    )

    q_values[valid] = (
        q_original_order
    )

    return q_values


# ==============================================================================
# 3. RECONSTRUCT PRE-CORRELATION TRAIN DATA
# ==============================================================================

def prepare_pre_corr_train(
    df,
    outcome_col,
    horizon_label
):

    df = df.copy()


    # --------------------------------------------------------------------------
    # Ensure TX_DATE is datetime
    # --------------------------------------------------------------------------

    df["TX_DATE"] = pd.to_datetime(
        df["TX_DATE"],
        errors="coerce"
    )


    # --------------------------------------------------------------------------
    # Temporal split
    # --------------------------------------------------------------------------

    train_mask = (
        df["TX_DATE"]
        < SPLIT_DATE
    )


    # --------------------------------------------------------------------------
    # Remove identifiers, dates, and outcome
    #
    # This mirrors the shared Segment 5 split stage.
    # --------------------------------------------------------------------------

    id_cols = [
        c
        for c in [
            "TRR_ID_CODE",
            "PT_CODE",
            "DONOR_ID",
            "INIT_OPO_CTR_CODE",
            "END_OPO_CTR_CODE",
            "LISTING_CTR_CODE"
        ]
        if c in df.columns
    ]


    date_cols = (
        df
        .select_dtypes(
            include=[
                "datetime64[ns]",
                "datetime64[ns, UTC]"
            ]
        )
        .columns
        .tolist()
    )


    drop_cols = list(
        set(
            id_cols
            + date_cols
            + [outcome_col]
        )
    )


    X_train = (
        df.loc[
            train_mask
        ]
        .drop(
            columns=drop_cols,
            errors="ignore"
        )
        .reset_index(
            drop=True
        )
    )


    # --------------------------------------------------------------------------
    # Train-only >75% missingness screening
    #
    # This is done BEFORE the correlation analysis, matching Segment 5.
    # --------------------------------------------------------------------------

    train_missing_rate = (
        X_train.isna()
        .mean()
    )


    high_missing = (
        train_missing_rate[
            train_missing_rate
            > MISSING_THRESHOLD
        ]
        .index
        .tolist()
    )


    X_train = X_train.drop(
        columns=high_missing,
        errors="ignore"
    )


    # --------------------------------------------------------------------------
    # Remove semantically categorical numeric columns from Spearman.
    # --------------------------------------------------------------------------

    numeric_cols = (
        X_train
        .select_dtypes(
            include=np.number
        )
        .columns
        .tolist()
    )


    numeric_cols = [
        c
        for c in numeric_cols
        if c not in FORCE_CATEGORICAL_COLS
    ]


    print(
        f"\n{horizon_label}"
    )

    print(
        f"  Training rows                 : "
        f"{len(X_train):,}"
    )

    print(
        f"  >75% missingness removed      : "
        f"{len(high_missing)}"
    )

    print(
        f"  Numeric variables for Spearman: "
        f"{len(numeric_cols)}"
    )


    return (
        X_train,
        numeric_cols,
        high_missing
    )


# ==============================================================================
# 4. CALCULATE SPEARMAN rho + p-VALUE
# ==============================================================================

def calculate_spearman_results(
    X_train,
    numeric_cols
):

    records = []


    # --------------------------------------------------------------------------
    # Pairwise complete observations
    # --------------------------------------------------------------------------

    for i, feature_1 in enumerate(
        numeric_cols
    ):

        for feature_2 in numeric_cols[
            i + 1:
        ]:

            pair = (
                X_train[
                    [
                        feature_1,
                        feature_2
                    ]
                ]
                .dropna()
            )


            n = len(
                pair
            )


            # Need at least 3 observations.
            if n < 3:

                rho = np.nan
                p_value = np.nan

            # Constant variables cannot have a defined Spearman correlation.
            elif (
                pair[feature_1]
                .nunique()
                < 2
                or
                pair[feature_2]
                .nunique()
                < 2
            ):

                rho = np.nan
                p_value = np.nan

            else:

                try:

                    result = spearmanr(
                        pair[feature_1],
                        pair[feature_2],
                        alternative="two-sided"
                    )


                    rho = float(
                        result.statistic
                    )

                    p_value = float(
                        result.pvalue
                    )

                except Exception:

                    rho = np.nan
                    p_value = np.nan


            records.append(
                {
                    "feature_1":
                        feature_1,

                    "feature_2":
                        feature_2,

                    "n":
                        n,

                    "spearman_rho":
                        rho,

                    "absolute_rho":
                        abs(rho)
                        if pd.notna(rho)
                        else np.nan,

                    "p_value":
                        p_value
                }
            )


    results = pd.DataFrame(
        records
    )


    if results.empty:

        return results


    # --------------------------------------------------------------------------
    # FDR correction
    # --------------------------------------------------------------------------

    results[
        "q_value_fdr_bh"
    ] = benjamini_hochberg(
        results["p_value"].to_numpy()
    )


    # --------------------------------------------------------------------------
    # Significance flags
    # --------------------------------------------------------------------------

    results[
        "p_value_significant"
    ] = (
        results["p_value"]
        < P_VALUE_ALPHA
    )


    results[
        "fdr_significant"
    ] = (
        results["q_value_fdr_bh"]
        < P_VALUE_ALPHA
    )


    results[
        "high_correlation"
    ] = (
        results["absolute_rho"]
        >= CORRELATION_THRESHOLD
    )


    results[
        "high_corr_and_fdr_significant"
    ] = (
        results["high_correlation"]
        &
        results["fdr_significant"]
    )


    # --------------------------------------------------------------------------
    # Sort strongest associations first
    # --------------------------------------------------------------------------

    results = (
        results
        .sort_values(
            [
                "absolute_rho",
                "q_value_fdr_bh"
            ],
            ascending=[
                False,
                True
            ]
        )
        .reset_index(
            drop=True
        )
    )


    return results


# ==============================================================================
# 5. CORRELATION MATRICES
# ==============================================================================

def build_matrices(
    X_train,
    numeric_cols
):

    rho_matrix = (
        X_train[
            numeric_cols
        ]
        .corr(
            method="spearman"
        )
    )


    # P-value matrix.
    p_matrix = pd.DataFrame(
        np.nan,
        index=numeric_cols,
        columns=numeric_cols
    )


    np.fill_diagonal(
        p_matrix.values,
        0.0
    )


    for i, feature_1 in enumerate(
        numeric_cols
    ):

        for feature_2 in numeric_cols[
            i + 1:
        ]:

            pair = (
                X_train[
                    [
                        feature_1,
                        feature_2
                    ]
                ]
                .dropna()
            )


            if (
                len(pair) < 3
                or pair[feature_1].nunique() < 2
                or pair[feature_2].nunique() < 2
            ):

                p = np.nan

            else:

                try:

                    p = spearmanr(
                        pair[feature_1],
                        pair[feature_2],
                        alternative="two-sided"
                    ).pvalue

                except Exception:

                    p = np.nan


            p_matrix.loc[
                feature_1,
                feature_2
            ] = p

            p_matrix.loc[
                feature_2,
                feature_1
            ] = p


    return (
        rho_matrix,
        p_matrix
    )


# ==============================================================================
# 6. HEATMAP OF TOP VARIABLES
# ==============================================================================

def plot_spearman_heatmap(
    rho_matrix,
    results,
    output_path,
    horizon_label
):

    if results.empty:
        return


    # --------------------------------------------------------------------------
    # Identify variables appearing most often among strongest pairs.
    # --------------------------------------------------------------------------

    top_pairs = results.head(
        TOP_PAIRS_TO_PLOT
    )


    top_features = pd.unique(
        top_pairs[
            [
                "feature_1",
                "feature_2"
            ]
        ].values.ravel()
    )


    # Keep matrix manageable.
    top_features = top_features[
        :TOP_HEATMAP_FEATURES
    ]


    matrix = rho_matrix.loc[
        top_features,
        top_features
    ]


    fig_size = max(
        9,
        len(top_features) * 0.42
    )


    fig, ax = plt.subplots(
        figsize=(
            fig_size,
            fig_size
        )
    )


    image = ax.imshow(
        matrix.values,
        interpolation="nearest",
        aspect="auto"
    )


    ax.set_xticks(
        np.arange(
            len(top_features)
        )
    )

    ax.set_yticks(
        np.arange(
            len(top_features)
        )
    )


    ax.set_xticklabels(
        top_features,
        rotation=90,
        fontsize=7
    )

    ax.set_yticklabels(
        top_features,
        fontsize=7
    )


    ax.set_title(
        f"{horizon_label}: Top Spearman Correlations"
    )


    cbar = fig.colorbar(
        image,
        ax=ax
    )

    cbar.set_label(
        "Spearman ρ"
    )


    fig.tight_layout()


    fig.savefig(
        output_path,
        dpi=FIG_DPI,
        bbox_inches="tight"
    )


    plt.close(
        fig
    )


# ==============================================================================
# 7. TOP FEATURE-PAIR BAR CHART
# ==============================================================================

def plot_top_pairs(
    results,
    output_path,
    horizon_label
):

    if results.empty:
        return


    top = (
        results
        .head(
            TOP_PAIRS_TO_PLOT
        )
        .copy()
        .sort_values(
            "spearman_rho"
        )
    )


    labels = (
        top["feature_1"]
        + " ↔ "
        + top["feature_2"]
    )


    fig_height = max(
        7,
        len(top) * 0.38
    )


    fig, ax = plt.subplots(
        figsize=(
            11,
            fig_height
        )
    )


    bars = ax.barh(
        labels,
        top["spearman_rho"]
    )


    ax.axvline(
        0,
        linewidth=0.8
    )


    ax.set_xlabel(
        "Spearman ρ"
    )


    ax.set_ylabel(
        "Feature pair"
    )


    ax.set_title(
        f"{horizon_label}: Strongest Spearman Feature Pairs"
    )


    # --------------------------------------------------------------------------
    # Annotate rho and FDR q-value.
    # --------------------------------------------------------------------------

    for bar, (_, row) in zip(
        bars,
        top.iterrows()
    ):

        value = row[
            "spearman_rho"
        ]

        q = row[
            "q_value_fdr_bh"
        ]


        if pd.notna(
            q
        ):

            q_text = (
                f"ρ={value:.2f}, "
                f"q={q:.2e}"
            )

        else:

            q_text = (
                f"ρ={value:.2f}"
            )


        ax.text(
            value
            + (
                0.015
                if value >= 0
                else -0.015
            ),
            bar.get_y()
            + bar.get_height() / 2,
            q_text,
            va="center",
            ha=(
                "left"
                if value >= 0
                else "right"
            ),
            fontsize=8
        )


    fig.tight_layout()


    fig.savefig(
        output_path,
        dpi=FIG_DPI,
        bbox_inches="tight"
    )


    plt.close(
        fig
    )


# ==============================================================================
# 8. SIGNIFICANCE / EFFECT-SIZE FIGURE
# ==============================================================================

def plot_rho_pvalue(
    results,
    output_path,
    horizon_label
):

    if results.empty:
        return


    plot_df = (
        results
        .dropna(
            subset=[
                "absolute_rho",
                "p_value"
            ]
        )
        .copy()
    )


    if plot_df.empty:
        return


    plot_df["minus_log10_p"] = (
        -np.log10(
            np.maximum(
                plot_df["p_value"],
                np.finfo(float).tiny
            )
        )
    )


    fig, ax = plt.subplots(
        figsize=(
            10,
            7
        )
    )


    ax.scatter(
        plot_df["absolute_rho"],
        plot_df["minus_log10_p"],
        s=10,
        alpha=0.55
    )


    # --------------------------------------------------------------------------
    # High-correlation threshold
    # --------------------------------------------------------------------------

    ax.axvline(
        CORRELATION_THRESHOLD,
        linestyle="--",
        linewidth=1
    )


    # --------------------------------------------------------------------------
    # Raw p-value threshold
    # --------------------------------------------------------------------------

    p_line = (
        -np.log10(
            P_VALUE_ALPHA
        )
    )


    ax.axhline(
        p_line,
        linestyle="--",
        linewidth=1
    )


    ax.set_xlabel(
        "|Spearman ρ|"
    )


    ax.set_ylabel(
        "−log10(p-value)"
    )


    ax.set_title(
        f"{horizon_label}: Spearman Effect Size and Statistical Significance"
    )


    # --------------------------------------------------------------------------
    # Label strongest correlations that also pass FDR.
    # --------------------------------------------------------------------------

    labels_df = (
        plot_df[
            plot_df[
                "high_corr_and_fdr_significant"
            ]
        ]
        .head(15)
    )


    for _, row in labels_df.iterrows():

        label = (
            f"{row['feature_1']} ↔ "
            f"{row['feature_2']}"
        )


        ax.annotate(
            label,
            (
                row["absolute_rho"],
                row["minus_log10_p"]
            ),
            xytext=(
                5,
                5
            ),
            textcoords="offset points",
            fontsize=7
        )


    fig.tight_layout()


    fig.savefig(
        output_path,
        dpi=FIG_DPI,
        bbox_inches="tight"
    )


    plt.close(
        fig
    )


# ==============================================================================
# 9. RUN ONE HORIZON
# ==============================================================================

def run_spearman_analysis(
    df,
    outcome_col,
    horizon_label,
    output_folder_name
):

    output_dir = (
        OUTPUT_ROOT
        / output_folder_name
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    print(
        "\n"
        + "=" * 80
    )

    print(
        f"SPEARMAN ANALYSIS — {horizon_label}"
    )

    print(
        "=" * 80
    )


    # --------------------------------------------------------------------------
    # Prepare exact pre-correlation training predictors
    # --------------------------------------------------------------------------

    (
        X_train,
        numeric_cols,
        high_missing
    ) = prepare_pre_corr_train(
        df=df,
        outcome_col=outcome_col,
        horizon_label=horizon_label
    )


    # --------------------------------------------------------------------------
    # Calculate pairwise rho + p-values
    # --------------------------------------------------------------------------

    print(
        "\n  Calculating pairwise Spearman rho and p-values..."
    )


    results = calculate_spearman_results(
        X_train=X_train,
        numeric_cols=numeric_cols
    )


    # --------------------------------------------------------------------------
    # Save long-form results
    # --------------------------------------------------------------------------

    results_path = (
        output_dir
        / "spearman_rho_pvalues_fdr.csv"
    )


    results.to_csv(
        results_path,
        index=False
    )


    # --------------------------------------------------------------------------
    # Save only high-correlation pairs
    # --------------------------------------------------------------------------

    high = (
        results[
            results["absolute_rho"]
            >= CORRELATION_THRESHOLD
        ]
        .copy()
    )


    high_path = (
        output_dir
        / "spearman_high_correlation_pairs.csv"
    )


    high.to_csv(
        high_path,
        index=False
    )


    # --------------------------------------------------------------------------
    # Build matrices
    # --------------------------------------------------------------------------

    print(
        "  Building rho and p-value matrices..."
    )


    (
        rho_matrix,
        p_matrix
    ) = build_matrices(
        X_train=X_train,
        numeric_cols=numeric_cols
    )


    rho_matrix.to_csv(
        output_dir
        / "spearman_rho_matrix.csv"
    )


    p_matrix.to_csv(
        output_dir
        / "spearman_pvalue_matrix.csv"
    )


    # --------------------------------------------------------------------------
    # Significant pair-only table
    # --------------------------------------------------------------------------

    significant = (
        results[
            results["fdr_significant"]
        ]
        .copy()
    )


    significant.to_csv(
        output_dir
        / "spearman_fdr_significant_pairs.csv",
        index=False
    )


    # --------------------------------------------------------------------------
    # FIGURE 1: heatmap
    # --------------------------------------------------------------------------

    plot_spearman_heatmap(
        rho_matrix=rho_matrix,
        results=results,
        output_path=(
            output_dir
            / "figure_1_spearman_heatmap.png"
        ),
        horizon_label=horizon_label
    )


    # --------------------------------------------------------------------------
    # FIGURE 2: strongest pairs
    # --------------------------------------------------------------------------

    plot_top_pairs(
        results=results,
        output_path=(
            output_dir
            / "figure_2_top_spearman_pairs.png"
        ),
        horizon_label=horizon_label
    )


    # --------------------------------------------------------------------------
    # FIGURE 3: rho vs p-value
    # --------------------------------------------------------------------------

    plot_rho_pvalue(
        results=results,
        output_path=(
            output_dir
            / "figure_3_spearman_significance.png"
        ),
        horizon_label=horizon_label
    )


    # --------------------------------------------------------------------------
    # Summary
    # --------------------------------------------------------------------------

    print(
        "\n"
        + "-" * 80
    )

    print(
        "RESULTS"
    )

    print(
        "-" * 80
    )


    print(
        f"  Numeric variables       : "
        f"{len(numeric_cols)}"
    )

    print(
        f"  Feature pairs evaluated : "
        f"{len(results):,}"
    )

    print(
        f"  High-correlation pairs  : "
        f"{len(high):,}"
    )

    print(
        f"  FDR-significant pairs   : "
        f"{len(significant):,}"
    )


    print(
        "\n  Top 10 Spearman pairs:"
    )


    display_cols = [
        "feature_1",
        "feature_2",
        "n",
        "spearman_rho",
        "p_value",
        "q_value_fdr_bh"
    ]


    print(
        results[
            display_cols
        ]
        .head(10)
        .to_string(
            index=False
        )
    )


    print(
        "\n  Output directory:"
    )

    print(
        f"  {output_dir}"
    )


    return {
        "X_train":
            X_train,

        "numeric_cols":
            numeric_cols,

        "results":
            results,

        "high":
            high,

        "significant":
            significant,

        "rho_matrix":
            rho_matrix,

        "p_matrix":
            p_matrix,

        "output_dir":
            output_dir
    }


# ==============================================================================
# 10. RUN 1-YEAR
# ==============================================================================

spearman_1y = run_spearman_analysis(
    df=dataset_1y,
    outcome_col="OUTCOME_1Y",
    horizon_label="1-YEAR",
    output_folder_name="1yr"
)


# ==============================================================================
# 11. RUN 3-YEAR
# ==============================================================================

spearman_3y = run_spearman_analysis(
    df=dataset_3y,
    outcome_col="OUTCOME_3Y",
    horizon_label="3-YEAR",
    output_folder_name="3yr"
)


# ==============================================================================
# 12. FINAL COMBINED PRINT
# ==============================================================================

print(
    "\n"
    + "=" * 80
)

print(
    "SPEARMAN ANALYSIS COMPLETE"
)

print(
    "=" * 80
)

print(
    f"1-YEAR OUTPUTS: "
    f"{OUTPUT_ROOT / '1yr'}"
)

print(
    f"3-YEAR OUTPUTS: "
    f"{OUTPUT_ROOT / '3yr'}"
)

NameError: name 'dataset_1y' is not defined

In [ ]:
print(
    f"\n1-YEAR PRUNING OUTPUTS:\n"
    f"{PRUNING_ROOT / '1yr'}\n"
    f"  - shap_pruning_trajectory.csv\n"
    f"  - shap_selected_features.csv\n"
    f"  - shap_pruning_summary.csv\n"
    f"  - shap_pruning_outcome.txt\n"
    f"  - pruned_vs_original_test_predictions.csv\n"
    f"  - shap_pruned_model_1yr.pkl\n"
)

print(
    f"\n3-YEAR PRUNING OUTPUTS:\n"
    f"{PRUNING_ROOT / '3yr'}\n"
    f"  - shap_pruning_trajectory.csv\n"
    f"  - shap_selected_features.csv\n"
    f"  - shap_pruning_summary.csv\n"
    f"  - shap_pruning_outcome.txt\n"
    f"  - pruned_vs_original_test_predictions.csv\n"
    f"  - shap_pruned_model_3yr.pkl\n"
    f"\nCOMBINED SUMMARY:\n"
    f"{PRUNING_ROOT / 'shap_pruning_combined_summary.csv'}"
)

# Segment 7 - old

In [ ]:
# ==============================================================================
# SEGMENT 7 — PART 1
# ==============================================================================
from pathlib import Path
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
import shap
import xgboost as xgb
import lightgbm as lgb

BASE = Path(r"D:\Thesis\Thesis_parquet")
SPLIT_DATE = pd.Timestamp('2018-10-18')
FIG_DIR_1Y = BASE / "results" / "1yr" / "figures"
FIG_DIR_3Y = BASE / "results" / "3yr" / "figures"
FIG_DIR_1Y.mkdir(parents=True, exist_ok=True)
FIG_DIR_3Y.mkdir(parents=True, exist_ok=True)

MODEL_1Y_NAME, MODEL_1Y_STRATEGY = 'LightGBM', 'S2_BALANCED'
MODEL_3Y_NAME, MODEL_3Y_STRATEGY = 'LightGBM', 'S3_THRESHOLD'

# ------------------------------------------------------------------------------
# PHASE 0A — LOAD MODELS, UNWRAP PIPELINE IF PRESENT
# ------------------------------------------------------------------------------
def load_model(horizon, name, strategy):
    path = BASE / "models" / horizon / f"model_{name}_{strategy}.pkl"
    with open(path, 'rb') as f:
        obj = pickle.load(f)
    if hasattr(obj, 'named_steps'):          # S1_SMOTE models are wrapped in an ImblearnPipeline
        return obj.named_steps['model']
    return obj

model_1y = load_model("1yr", MODEL_1Y_NAME, MODEL_1Y_STRATEGY)
model_3y = load_model("3yr", MODEL_3Y_NAME, MODEL_3Y_STRATEGY)
print(f"Loaded 1yr model: {MODEL_1Y_NAME}/{MODEL_1Y_STRATEGY} -> {type(model_1y).__name__}")
print(f"Loaded 3yr model: {MODEL_3Y_NAME}/{MODEL_3Y_STRATEGY} -> {type(model_3y).__name__}")

# ------------------------------------------------------------------------------
# PHASE 0B — LOAD FEATURE MATRICES
# ------------------------------------------------------------------------------
Xtr_1y = pd.read_parquet(BASE / "model_ready" / "1yr" / "X_train_tree.parquet")
Xte_1y = pd.read_parquet(BASE / "model_ready" / "1yr" / "X_test_tree.parquet")
ytr_1y = pd.read_parquet(BASE / "model_ready" / "1yr" / "y_train.parquet").squeeze().astype(int)
yte_1y = pd.read_parquet(BASE / "model_ready" / "1yr" / "y_test.parquet").squeeze().astype(int)

Xtr_3y = pd.read_parquet(BASE / "model_ready" / "3yr" / "X_train_tree.parquet")
Xte_3y = pd.read_parquet(BASE / "model_ready" / "3yr" / "X_test_tree.parquet")
ytr_3y = pd.read_parquet(BASE / "model_ready" / "3yr" / "y_train.parquet").squeeze().astype(int)
yte_3y = pd.read_parquet(BASE / "model_ready" / "3yr" / "y_test.parquet").squeeze().astype(int)

print(f"1yr test: {Xte_1y.shape}, positive rate {yte_1y.mean():.4f}")
print(f"3yr test: {Xte_3y.shape}, positive rate {yte_3y.mean():.4f}")

# ------------------------------------------------------------------------------
# PHASE 0C — RECONSTRUCT REAL TRR_ID_CODE FOR EACH TEST ROW (the fix)
# Deterministic re-derivation of Segment 5's train/test split: t_df3 (left,
# preserves row order) inner-joined to the outcome file (right), then the
# same TX_DATE >= SPLIT_DATE boolean mask Segment 5 applied. No shuffling
# occurs anywhere in this chain, so this reproduces the exact row order
# X_test_tree.parquet was built in -- verified below, not assumed.
# ------------------------------------------------------------------------------
t_df3 = pd.read_parquet(BASE / "t_df3.parquet")

def recover_test_ids(outcome_path, outcome_col, y_test_actual, extra_cols=None):
    outcome_df = pd.read_parquet(BASE / outcome_path)
    cols = ['TRR_ID_CODE', outcome_col] + (extra_cols or [])
    merged = t_df3[['TRR_ID_CODE', 'TX_DATE']].merge(outcome_df[cols], on='TRR_ID_CODE', how='inner')
    test_rows = merged.loc[merged['TX_DATE'] >= SPLIT_DATE].reset_index(drop=True)

    assert len(test_rows) == len(y_test_actual), (
        f"Row count mismatch: reconstructed {len(test_rows)} vs actual {len(y_test_actual)} — "
        f"STOP, do not trust any ID-based join below until this is resolved."
    )
    match = (test_rows[outcome_col].values == y_test_actual.values).all()
    assert match, (
        "Reconstructed outcome column does not match the actual saved y_test array "
        "element-for-element — the row-order assumption is wrong. STOP."
    )
    print(f"  ID recovery verified: {len(test_rows):,} rows, exact element-wise match against saved y_test.")
    return test_rows

print("\nRecovering 1-year test-set patient IDs...")
ids_1y = recover_test_ids("outcome_1y.parquet", "OUTCOME_1Y", yte_1y)

print("Recovering 3-year test-set patient IDs (with OUTCOME_1Y for incident-subgroup filtering)...")
ids_3y = recover_test_ids("outcome_3y.parquet", "OUTCOME_3Y", yte_3y, extra_cols=["OUTCOME_1Y"])

# The population this thesis's central cross-horizon claim depends on:
# confirmed rejection-free at 1 year, now being assessed for NEW rejection by year 3.
clean_incident_mask = (ids_3y["OUTCOME_1Y"] == 0).values
print(f"\nClean incident subgroup within 3yr test set: {clean_incident_mask.sum():,} / {len(ids_3y):,} "
      f"patients, positive rate {yte_3y.values[clean_incident_mask].mean():.4f}")

# ------------------------------------------------------------------------------
# PHASE A — GLOBAL SHAP, WITH MANDATORY ADDITIVITY SELF-CHECK
# A SHAP explanation that doesn't reconstruct the model's own output is not
# trustworthy, regardless of how plausible the resulting ranking looks --
# same self-verification discipline as Segment 6's DeLong implementation.
# ------------------------------------------------------------------------------
def _logit(p, eps=1e-9):
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))

def verify_shap_additivity(explainer, shap_values, X_sample, model, n_check=10):
    base = explainer.expected_value
    if isinstance(base, (list, np.ndarray)):
        base = float(np.atleast_1d(base)[-1])
    reconstructed_margin = base + shap_values[:n_check].sum(axis=1)
    actual_margin = _logit(model.predict_proba(X_sample.iloc[:n_check])[:, 1])
    diff = np.abs(reconstructed_margin - actual_margin)
    ok = bool(np.all(diff < 1e-2))
    print(f"    Additivity check: max diff (margin space) = {diff.max():.5f}  "
          f"{'OK' if ok else '!! MISMATCH — do not trust this ranking until resolved'}")
    return ok

def compute_global_shap(model, X, label, fig_dir):
    print(f"\n--- {label}: computing SHAP ---")
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X)
    if isinstance(shap_values, list):
        shap_values = shap_values[1]
    verify_shap_additivity(explainer, shap_values, X, model)

    mean_abs_shap = pd.Series(np.abs(shap_values).mean(axis=0), index=X.columns)
    ranking = mean_abs_shap.sort_values(ascending=False)
    print(f"  Top 15 features:\n{ranking.head(15).to_string()}")

    shap.summary_plot(shap_values, X, show=False, max_display=20)
    plt.title(f"{label} — SHAP Summary")
    plt.tight_layout()
    plt.savefig(fig_dir / f"shap_summary_{label.lower().replace(' ', '_')}.png", dpi=150, bbox_inches='tight')
    plt.close()
    return explainer, shap_values, ranking

explainer_1y, shap_1y, ranking_1y = compute_global_shap(model_1y, Xte_1y, "1-Year", FIG_DIR_1Y)
explainer_3y, shap_3y, ranking_3y = compute_global_shap(model_3y, Xte_3y, "3-Year (full cohort)", FIG_DIR_3Y)

# Restricted SHAP: same fitted 3-year model, evaluated ONLY on the clean
# incident subgroup -- no retraining needed, SHAP explains predictions on
# whatever rows you hand it.
Xte_3y_incident = Xte_3y.loc[clean_incident_mask].reset_index(drop=True)
print(f"\n--- 3-Year INCIDENT subgroup (n={len(Xte_3y_incident):,}): computing SHAP ---")
shap_3y_incident = explainer_3y.shap_values(Xte_3y_incident)
if isinstance(shap_3y_incident, list):
    shap_3y_incident = shap_3y_incident[1]
verify_shap_additivity(explainer_3y, shap_3y_incident, Xte_3y_incident, model_3y)
ranking_3y_incident = pd.Series(np.abs(shap_3y_incident).mean(axis=0), index=Xte_3y_incident.columns).sort_values(ascending=False)
print(f"  Top 15 features (incident subgroup):\n{ranking_3y_incident.head(15).to_string()}")
shap.summary_plot(shap_3y_incident, Xte_3y_incident, show=False, max_display=20)
plt.title("3-Year Incident Subgroup — SHAP Summary")
plt.tight_layout()
plt.savefig(FIG_DIR_3Y / "shap_summary_3yr_incident.png", dpi=150, bbox_inches='tight')
plt.close()

# ------------------------------------------------------------------------------
# PHASE B — DOMAIN-GROUPED SHAP
# ------------------------------------------------------------------------------
DOMAIN_MAP = {
    'donor_organ_quality': ['AGE_DON', 'COD_CAD_DON', 'ISCHTIME', 'CREAT_DON', 'ECD_DONOR',
                             'CARD_IDX_DELTA_DON', 'CARDIAC_OUTPUT_DELTA_DON', 'CVP_DELTA_DON',
                             'DIAST_PA_DELTA_DON', 'MAP_DELTA_DON', 'PCWP_DELTA_DON',
                             'SVR_DELTA_DON', 'SYST_PA_DELTA_DON'],
    'recipient_acute_severity': ['ECMO_TRR', 'VENTILATOR_TRR', 'IABP_TRR', 'INOTROPES_TRR',
                                  'FUNC_STAT_TRR', 'TBILI', 'CREAT_TRR', 'LIFE_SUP_TRR',
                                  'PRIOR_CARD_SURG_TRR', 'PRIOR_CARD_SURG_TCR'],
    'immunologic_sensitization': ['SENSITIZATION_TIER', 'SENSITIZATION_PEAK', 'SENSITIZATION_RECENT',
                                   'AMIS', 'BMIS', 'DRMIS', 'HLAMIS', 'ABO_MAT'],
    'infectious_serology': ['CMV_STATUS_UNIFIED', 'HBV_CORE', 'HBV_SUR_ANTIGEN',
                             'HCV_SEROSTATUS', 'EBV_SEROSTATUS'],
    'socioeconomic_access_proxy': ['EDUCATION', 'CITIZENSHIP', 'PRI_PAYMENT_TCR', 'PRI_PAYMENT_TRR',
                                    'WORK_INCOME_TCR', 'WORK_INCOME_TRR', 'PERM_STATE',
                                    'PERM_STATE_TRR', 'DISTANCE'],
    'perioperative_surgical': ['STERNOTOMY_TRR', 'TRANSFUSIONS'],
}

def domain_summary(ranking, label):
    rows, mapped = [], set()
    for domain, cols in DOMAIN_MAP.items():
        present = [c for c in cols if c in ranking.index]
        mapped.update(present)
        if present:
            rows.append({'domain': domain, 'total_mean_abs_shap': ranking[present].sum(), 'n_features': len(present)})
    unmapped = [c for c in ranking.index if c not in mapped]
    df = pd.DataFrame(rows).sort_values('total_mean_abs_shap', ascending=False)
    df['share'] = df['total_mean_abs_shap'] / ranking.sum()
    print(f"\n--- {label}: domain-level SHAP contribution ---")
    print(df.to_string(index=False))
    print(f"  Unmapped features (assign these by hand, {len(unmapped)}): {unmapped[:15]}")
    return df

domains_1y = domain_summary(ranking_1y, "1-Year")
domains_3y_full = domain_summary(ranking_3y, "3-Year (full)")
domains_3y_incident = domain_summary(ranking_3y_incident, "3-Year (incident subgroup)")

fig, ax = plt.subplots(figsize=(8, 5))
merged_domains = domains_1y.set_index('domain')['share'].to_frame('1-Year').join(
    domains_3y_incident.set_index('domain')['share'].to_frame('3-Year Incident'), how='outer').fillna(0)
merged_domains.plot(kind='barh', ax=ax)
ax.set_xlabel("Share of total mean |SHAP|"); ax.set_title("Domain-Level SHAP: 1-Year vs. 3-Year Incident")
plt.tight_layout(); plt.savefig(FIG_DIR_3Y / "domain_shap_comparison.png", dpi=150, bbox_inches='tight'); plt.close()

# ------------------------------------------------------------------------------
# PHASE C — CROSS-HORIZON RANK COMPARISON (the central novelty test)
# TWO versions, reported separately: full-population (contamination risk
# flagged explicitly) and incident-restricted (the mechanistically clean one).
# ------------------------------------------------------------------------------
def cross_horizon_comparison(ranking_a, ranking_b, label):
    shared = [c for c in ranking_a.index if c in ranking_b.index]
    ra, rb = ranking_a[shared].rank(ascending=False), ranking_b[shared].rank(ascending=False)
    rho, p = spearmanr(ra, rb)
    print(f"\n--- Cross-horizon comparison: {label} ---")
    print(f"  Spearman rho = {rho:.3f}, p = {p:.4g}  (n shared features = {len(shared)})")
    if rho > 0.7:
        print("  -> STRONG agreement: risk architecture stable across horizons.")
    elif rho > 0.3:
        print("  -> MODERATE agreement: partial overlap, partial divergence.")
    else:
        print("  -> WEAK agreement: risk architecture appears to genuinely diverge.")
    shift = pd.DataFrame({'rank_a': ra, 'rank_b': rb})
    shift['rank_shift'] = shift['rank_a'] - shift['rank_b']
    print("  Biggest movers:")
    print(shift.sort_values('rank_shift', key=abs, ascending=False).head(10).to_string())
    return rho, p, shift

rho_full, p_full, shift_full = cross_horizon_comparison(ranking_1y, ranking_3y, "1yr vs 3yr FULL cohort (contamination risk — secondary)")
rho_inc, p_inc, shift_inc = cross_horizon_comparison(ranking_1y, ranking_3y_incident, "1yr vs 3yr INCIDENT subgroup (PRIMARY comparison)")

print(f"\n{'='*70}\nPART 1 COMPLETE — use rho_inc ({rho_inc:.3f}) to decide abstract wording, not rho_full.\n{'='*70}")

Loaded 1yr model: LightGBM/S2_BALANCED -> LGBMClassifier
Loaded 3yr model: LightGBM/S3_THRESHOLD -> LGBMClassifier
1yr test: (13796, 266), positive rate 0.3002
3yr test: (7568, 269), positive rate 0.3932

Recovering 1-year test-set patient IDs...
  ID recovery verified: 13,796 rows, exact element-wise match against saved y_test.
Recovering 3-year test-set patient IDs (with OUTCOME_1Y for incident-subgroup filtering)...
  ID recovery verified: 7,568 rows, exact element-wise match against saved y_test.

Clean incident subgroup within 3yr test set: 4,785 / 7,568 patients, positive rate 0.0842

--- 1-Year: computing SHAP ---
    Additivity check: max diff (margin space) = 0.00000  OK
  Top 15 features:
PERM_STATE                 0.150574
AGE                        0.077564
DON_RETYP                  0.044095
GENDER                     0.036603
FUNC_STAT_TRR              0.034418
DQ1                        0.031465
HOME_STATE_DON             0.027635
HEMO_CO_TRR                0.025749
DQ2                        0.024254
TOT_SERUM_ALBUM_MISSING    0.016756
DRMIS                      0.016623
LISTYR                     0.015873
WGT_KG_TCR                 0.015673
END_STAT                   0.015393
EBV_SEROSTATUS             0.014562

--- 3-Year (full cohort): computing SHAP ---
    Additivity check: max diff (margin space) = 0.00000  OK
  Top 15 features:
PERM_STATE                 0.132238
AGE                        0.106456
DON_RETYP                  0.043229
HOME_STATE_DON             0.030037
FUNC_STAT_TRR              0.030014
GENDER                     0.025909
TOT_SERUM_ALBUM_MISSING    0.025429
DQ1                        0.021294
LISTYR                     0.018423
DRMIS                      0.017589
WORK_INCOME_TRR            0.017136
SHARE_TY                   0.016568
IABP_TRR                   0.015281
DISTANCE                   0.014326
WGT_KG_TCR                 0.013865

--- 3-Year INCIDENT subgroup (n=4,785): computing SHAP ---
    Additivity check: max diff (margin space) = 0.00000  OK
  Top 15 features (incident subgroup):
PERM_STATE                 0.127643
AGE                        0.107088
DON_RETYP                  0.042648
HOME_STATE_DON             0.031147
FUNC_STAT_TRR              0.029612
GENDER                     0.025715
TOT_SERUM_ALBUM_MISSING    0.025189
DQ1                        0.021450
LISTYR                     0.019494
DRMIS                      0.018191
WORK_INCOME_TRR            0.016238
SHARE_TY                   0.016112
IABP_TRR                   0.014907
WGT_KG_TCR                 0.013773
DISTANCE                   0.013696

--- 1-Year: domain-level SHAP contribution ---
                    domain  total_mean_abs_shap  n_features    share
socioeconomic_access_proxy             0.174314           8 0.164987
  recipient_acute_severity             0.067737           7 0.064113
 immunologic_sensitization             0.054323           8 0.051416
       infectious_serology             0.017632           4 0.016689
       donor_organ_quality             0.014860           5 0.014065
    perioperative_surgical             0.001165           1 0.001103
  Unmapped features (assign these by hand, 233): ['AGE', 'DON_RETYP', 'GENDER', 'DQ1', 'HOME_STATE_DON', 'HEMO_CO_TRR', 'DQ2', 'TOT_SERUM_ALBUM_MISSING', 'LISTYR', 'WGT_KG_TCR', 'END_STAT', 'DB1', 'SHARE_TY', 'WGT_KG_CALC', 'PT_STEROIDS_DON']

--- 3-Year (full): domain-level SHAP contribution ---
                    domain  total_mean_abs_shap  n_features    share
socioeconomic_access_proxy             0.184053           8 0.172066
  recipient_acute_severity             0.058863           7 0.055029
 immunologic_sensitization             0.053253           8 0.049785
       infectious_serology             0.019542           4 0.018269
       donor_organ_quality             0.016346           5 0.015282
    perioperative_surgical             0.001264           1 0.001182
  Unmapped features (assign these by hand, 236): ['AGE', 'DON_RETYP', 'HOME_STATE_DON', 'GENDER', 'TOT_SERUM_ALBUM_MISSING', 'DQ1', 'LISTYR', 'SHARE_TY', 'WGT_KG_TCR', 'HEMO_CO_TRR', 'TCR_DUR_ABSTAIN', 'WGT_KG_CALC', 'DQ2', 'PT_STEROIDS_DON', 'DB1']

--- 3-Year (incident subgroup): domain-level SHAP contribution ---
                    domain  total_mean_abs_shap  n_features    share
socioeconomic_access_proxy             0.176788           8 0.166169
  recipient_acute_severity             0.057835           7 0.054361
 immunologic_sensitization             0.053565           8 0.050348
       infectious_serology             0.019845           4 0.018653
       donor_organ_quality             0.016264           5 0.015287
    perioperative_surgical             0.001233           1 0.001159
  Unmapped features (assign these by hand, 236): ['AGE', 'DON_RETYP', 'HOME_STATE_DON', 'GENDER', 'TOT_SERUM_ALBUM_MISSING', 'DQ1', 'LISTYR', 'SHARE_TY', 'WGT_KG_TCR', 'HEMO_CO_TRR', 'DQ2', 'TCR_DUR_ABSTAIN', 'WGT_KG_CALC', 'PT_STEROIDS_DON', 'C1']

--- Cross-horizon comparison: 1yr vs 3yr FULL cohort (contamination risk — secondary) ---
  Spearman rho = 0.878, p = 6.152e-86  (n shared features = 264)
  -> STRONG agreement: risk architecture stable across horizons.
  Biggest movers:
                           rank_a  rank_b  rank_shift
INSULIN_DON_MISSING         251.5    60.0       191.5
PCO2_DON_MISSING            236.0    54.0       182.0
WORK_INCOME_TRR_MISSING     187.0    30.0       157.0
TRANSFUS_TERM_DON_MISSING   251.5   140.0       111.5
TRANSFUS_TERM_DON           160.0    53.0       107.0
HEP_C_ANTI_DON              217.0   116.0       101.0
BMIS                        147.0    59.0        88.0
INSULIN_DON                 119.0    32.0        87.0
HCV_SEROSTATUS              214.0   128.0        86.0
CIG_USE_MISSING             190.0   106.0        84.0

--- Cross-horizon comparison: 1yr vs 3yr INCIDENT subgroup (PRIMARY comparison) ---
  Spearman rho = 0.880, p = 8.375e-87  (n shared features = 264)
  -> STRONG agreement: risk architecture stable across horizons.
  Biggest movers:
                           rank_a  rank_b  rank_shift
INSULIN_DON_MISSING         251.5    65.0       186.5
PCO2_DON_MISSING            236.0    56.0       180.0
WORK_INCOME_TRR_MISSING     187.0    31.0       156.0
TRANSFUS_TERM_DON           160.0    51.0       109.0
TRANSFUS_TERM_DON_MISSING   251.5   147.0       104.5
HEP_C_ANTI_DON              217.0   115.0       102.0
BMIS                        147.0    57.0        90.0
HCV_SEROSTATUS              214.0   125.0        89.0
INSULIN_DON                 119.0    35.0        84.0
WORK_INCOME_TRR              94.0    11.0        83.0

======================================================================
PART 1 COMPLETE — use rho_inc (0.880) to decide abstract wording, not rho_full.
======================================================================

In [ ]:
!pip install lime

Requirement already satisfied: lime in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.2.0.1)
Requirement already satisfied: matplotlib in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (3.11.2)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (2.5.3)
Requirement already satisfied: scipy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (1.18.1)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (4.70.1)
Requirement already satisfied: scikit-learn>=0.18 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (1.9.1)
Requirement already satisfied: scikit-image>=0.12 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from lime) (0.26.0)
Requirement already satisfied: networkx>=3.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-image>=0.12->lime) (3.7)
Requirement already satisfied: pillow>=10.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-image>=0.12->lime) (12.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-image>=0.12->lime) (2.37.4)
Requirement already satisfied: tifffile>=2022.8.12 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-image>=0.12->lime) (2026.9.20)
Requirement already satisfied: packaging>=21 in .\AppData\Roaming\Python\Python314\site-packages (from scikit-image>=0.12->lime) (26.2)
Requirement already satisfied: lazy-loader>=0.4 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-image>=0.12->lime) (0.6)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=0.18->lime) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=0.18->lime) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=0.18->lime) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from joblib>=1.4.0->scikit-learn>=0.18->lime) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->lime) (1.4.0)
Requirement already satisfied: cycler>=0.10 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->lime) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->lime) (1.5.1)
Requirement already satisfied: pyparsing>=3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->lime) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib->lime) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib->lime) (1.17.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python314\site-packages (from tqdm->lime) (0.4.6)

In [ ]:
# ==============================================================================
# SEGMENT 7 — PART 2
# Assumes Part 1 has been run in the same session (model_1y, model_3y,
# explainer_3y, Xte_1y/Xte_3y/Xte_3y_incident, ids_1y/ids_3y, ranking_1y,
# yte_1y/yte_3y all already in memory). If running fresh, re-run Part 1 first.
# ==============================================================================
from lime.lime_tabular import LimeTabularExplainer

rng = np.random.RandomState(42)
N_BOOTSTRAP_SHAP = 50     # deliberately lighter than the metric-CI bootstrap (N=1000) —
SUBSAMPLE_SIZE = 1500     # SHAP recomputation per resample is far more expensive per call

# ------------------------------------------------------------------------------
# PHASE D — BOOTSTRAP SHAP-RANK STABILITY
# Run on BOTH the 1-year model and, critically, the smaller 3-year incident
# subgroup, where sampling noise is the biggest concern given its reduced n.
# ------------------------------------------------------------------------------
def bootstrap_shap_stability(model, X, n_boot=N_BOOTSTRAP_SHAP, sample_size=SUBSAMPLE_SIZE, label=""):
    print(f"\nBootstrapping SHAP stability: {label} ({n_boot} resamples)...")
    explainer = shap.TreeExplainer(model)
    rank_records = []
    n = min(sample_size, len(X))
    for i in range(n_boot):
        idx = rng.choice(len(X), size=n, replace=True)
        sv = explainer.shap_values(X.iloc[idx])
        if isinstance(sv, list):
            sv = sv[1]
        mean_abs = pd.Series(np.abs(sv).mean(axis=0), index=X.columns)
        rank_records.append(mean_abs.rank(ascending=False))
        if (i + 1) % 10 == 0:
            print(f"  {i+1}/{n_boot} done")
    rank_df = pd.DataFrame(rank_records)
    stability = pd.DataFrame({
        'median_rank': rank_df.median(),
        'ci_low': rank_df.quantile(0.025),
        'ci_high': rank_df.quantile(0.975),
    }).sort_values('median_rank')
    stability['ci_width'] = stability['ci_high'] - stability['ci_low']
    print(stability.head(15).to_string())
    return stability

stability_1y = bootstrap_shap_stability(model_1y, Xte_1y, label="1-Year")
stability_3y_incident = bootstrap_shap_stability(model_3y, Xte_3y_incident, label="3-Year Incident subgroup")

# ------------------------------------------------------------------------------
# PHASE E — LIME CROSS-VALIDATION AGAINST TOP SHAP FEATURES (1-year model)
# ------------------------------------------------------------------------------
print("\n--- LIME cross-validation (1-year model) ---")
lime_explainer = LimeTabularExplainer(
    training_data=Xtr_1y.values, feature_names=Xtr_1y.columns.tolist(),
    class_names=['no_rejection', 'rejection'], mode='classification', random_state=42
)
lime_importance = pd.Series(0.0, index=Xte_1y.columns)
sample_idx = rng.choice(len(Xte_1y), size=min(200, len(Xte_1y)), replace=False)
for i in sample_idx:
    exp = lime_explainer.explain_instance(Xte_1y.iloc[i].values, model_1y.predict_proba, num_features=20)
    for feat_desc, weight in exp.as_list():
        for col in Xte_1y.columns:
            if col in feat_desc:
                lime_importance[col] += abs(weight)
                break
lime_ranking = lime_importance.sort_values(ascending=False)
overlap = set(ranking_1y.head(20).index) & set(lime_ranking.head(20).index)
print(f"SHAP/LIME top-20 overlap: {len(overlap)}/20 -> {overlap}")

# ------------------------------------------------------------------------------
# PHASE F — LOCAL CASE STUDIES (1-year: one positive, one negative)
# ------------------------------------------------------------------------------
pos_row = np.where(yte_1y.values == 1)[0][0]
neg_row = np.where(yte_1y.values == 0)[0][0]
for row, tag in [(pos_row, "confirmed_positive"), (neg_row, "confirmed_negative")]:
    base = explainer_1y.expected_value
    base = float(np.atleast_1d(base)[-1]) if isinstance(base, (list, np.ndarray)) else base
    shap.waterfall_plot(shap.Explanation(
        values=shap_1y[row], base_values=base,
        data=Xte_1y.iloc[row], feature_names=Xte_1y.columns.tolist()
    ), show=False)
    plt.title(f"1-Year — {tag} (patient TRR_ID_CODE={ids_1y.iloc[row]['TRR_ID_CODE']})")
    plt.tight_layout()
    plt.savefig(FIG_DIR_1Y / f"case_1yr_{tag}.png", dpi=150, bbox_inches='tight')
    plt.close()
print(f"\nLocal case studies saved -> {FIG_DIR_1Y}")

# ------------------------------------------------------------------------------
# PHASE G — LIGHT FAIRNESS LENS
# ------------------------------------------------------------------------------
print("\n--- Fairness lens: subgroup AUROC (1-year model) ---")
from sklearn.metrics import roc_auc_score
demo_cols = [c for c in ['GENDER', 'ETHCAT', 'PRI_PAYMENT_TCR'] if c in t_df3.columns]
demo = t_df3[['TRR_ID_CODE'] + demo_cols]
fairness_df = ids_1y[['TRR_ID_CODE']].merge(demo, on='TRR_ID_CODE', how='left')
probs_1y = model_1y.predict_proba(Xte_1y)[:, 1]

for col in demo_cols:
    print(f"\n  By {col}:")
    for g, sub_idx in fairness_df.groupby(col).groups.items():
        pos = fairness_df.index.isin(sub_idx)
        if yte_1y.values[pos].sum() > 0 and (yte_1y.values[pos] == 0).sum() > 0:
            auc = roc_auc_score(yte_1y.values[pos], probs_1y[pos])
            print(f"    {col}={g}: n={pos.sum():,}, AUROC={auc:.3f}")
        else:
            print(f"    {col}={g}: n={pos.sum():,}, AUROC undefined (single class)")

print(f"\n{'='*70}\nSEGMENT 7 COMPLETE — Part 1 + Part 2.\n{'='*70}")

Bootstrapping SHAP stability: 1-Year (50 resamples)...
  10/50 done
  20/50 done
  30/50 done
  40/50 done
  50/50 done
                         median_rank  ci_low  ci_high  ci_width
PERM_STATE                       1.0   1.000    1.000     0.000
AGE                              2.0   2.000    2.000     0.000
DON_RETYP                        3.0   3.000    3.000     0.000
GENDER                           4.0   4.000    4.775     0.775
FUNC_STAT_TRR                    5.0   4.225    5.000     0.775
DQ1                              6.0   6.000    6.000     0.000
HOME_STATE_DON                   7.0   7.000    7.000     0.000
HEMO_CO_TRR                      8.0   8.000    8.000     0.000
DQ2                              9.0   9.000    9.000     0.000
DRMIS                           10.5  10.000   14.000     4.000
TOT_SERUM_ALBUM_MISSING         11.0  10.000   12.000     2.000
WGT_KG_TCR                      12.0  11.000   14.000     3.000
LISTYR                          12.0  11.000   14.000     3.000
END_STAT                        14.0  13.000   14.000     1.000
EBV_SEROSTATUS                  15.0  14.225   15.775     1.550

Bootstrapping SHAP stability: 3-Year Incident subgroup (50 resamples)...
  10/50 done
  20/50 done
  30/50 done
  40/50 done
  50/50 done
                         median_rank  ci_low  ci_high  ci_width
PERM_STATE                       1.0   1.000      1.0     0.000
AGE                              2.0   2.000      2.0     0.000
DON_RETYP                        3.0   3.000      3.0     0.000
HOME_STATE_DON                   4.0   4.000      4.0     0.000
FUNC_STAT_TRR                    5.0   5.000      5.0     0.000
GENDER                           6.0   6.000      7.0     1.000
TOT_SERUM_ALBUM_MISSING          7.0   6.000      7.0     1.000
DQ1                              8.0   8.000      8.0     0.000
LISTYR                           9.0   9.000     10.0     1.000
DRMIS                           10.0   9.000     10.0     1.000
WORK_INCOME_TRR                 11.0  11.000     12.0     1.000
SHARE_TY                        12.0  11.000     12.0     1.000
IABP_TRR                        13.0  13.000     14.0     1.000
WGT_KG_TCR                      14.0  13.225     16.0     2.775
DISTANCE                        15.0  13.000     16.0     3.000

--- LIME cross-validation (1-year model) ---
SHAP/LIME top-20 overlap: 8/20 -> {'DQ1', 'GENDER', 'FUNC_STAT_TRR', 'PERM_STATE', 'DQ2', 'HOME_STATE_DON', 'DON_RETYP', 'AGE'}

Local case studies saved -> D:\Thesis\Thesis_parquet\results\1yr\figures

--- Fairness lens: subgroup AUROC (1-year model) ---

  By GENDER:
    GENDER=F: n=3,778, AUROC=0.615
    GENDER=M: n=10,018, AUROC=0.632

  By ETHCAT:
    ETHCAT=1.0: n=8,374, AUROC=0.638
    ETHCAT=2.0: n=3,338, AUROC=0.621
    ETHCAT=4.0: n=1,419, AUROC=0.600
    ETHCAT=5.0: n=500, AUROC=0.634
    ETHCAT=6.0: n=63, AUROC=0.628
    ETHCAT=7.0: n=29, AUROC=0.678

  By PRI_PAYMENT_TCR:
    PRI_PAYMENT_TCR=1.0: n=6,843, AUROC=0.627
    PRI_PAYMENT_TCR=2.0: n=2,129, AUROC=0.638
    PRI_PAYMENT_TCR=3.0: n=2,018, AUROC=0.639
    PRI_PAYMENT_TCR=4.0: n=2,150, AUROC=0.622
    PRI_PAYMENT_TCR=5.0: n=7, AUROC undefined (single class)
    PRI_PAYMENT_TCR=6.0: n=309, AUROC=0.626
    PRI_PAYMENT_TCR=7.0: n=256, AUROC=0.613
    PRI_PAYMENT_TCR=8.0: n=25, AUROC=0.847
    PRI_PAYMENT_TCR=10.0: n=14, AUROC=0.923
    PRI_PAYMENT_TCR=11.0: n=11, AUROC=0.417
    PRI_PAYMENT_TCR=12.0: n=31, AUROC=0.740

======================================================================
SEGMENT 7 COMPLETE — Part 1 + Part 2.
======================================================================

In [ ]:
# ==============================================================================
# SEGMENT 7 — PART 3: Diagnosing the geography/administrative-dominance finding
# Assumes Parts 1-2 already run in this session.
# ==============================================================================
from sklearn.inspection import permutation_importance

# ------------------------------------------------------------------------------
# PHASE H — CARDINALITY OF THE DISPUTED TOP FEATURES
# ------------------------------------------------------------------------------
disputed = ['PERM_STATE', 'REGION', 'PERM_STATE_TRR', 'HOME_STATE_DON', 'DON_RETYP', 'LISTYR', 'END_STAT', 'INIT_STAT']
geo_check = ids_1y[['TRR_ID_CODE']].merge(
    t_df3[['TRR_ID_CODE'] + [c for c in disputed if c in t_df3.columns]], on='TRR_ID_CODE', how='left'
)
print("--- Cardinality of disputed top features (real values, test set) ---")
for c in disputed:
    if c in geo_check.columns:
        print(f"  {c}: {geo_check[c].nunique()} unique values, {geo_check[c].isna().sum()} missing")

# ------------------------------------------------------------------------------
# PHASE I — IS REGION A NEAR-DETERMINISTIC FUNCTION OF PERM_STATE?
# ------------------------------------------------------------------------------
if 'REGION' in geo_check.columns and 'PERM_STATE' in geo_check.columns:
    region_per_state = geo_check.dropna(subset=['PERM_STATE', 'REGION']).groupby('PERM_STATE')['REGION'].nunique()
    ambiguous = (region_per_state > 1).sum()
    print(f"\n--- REGION vs PERM_STATE redundancy check ---")
    print(f"  States mapping to more than one REGION value: {ambiguous} / {len(region_per_state)}")
    print(f"  {'-> REGION is essentially redundant with PERM_STATE — treat their combined SHAP as ONE geographic signal, not two.' if ambiguous <= 2 else '-> REGION carries information beyond PERM_STATE alone — the two are more independent than expected.'}")

# ------------------------------------------------------------------------------
# PHASE J — PERMUTATION IMPORTANCE CROSS-CHECK (independent method, held-out data)
# A feature's SHAP rank should be corroborated by an independent importance
# measure computed a completely different way. Divergence between the two on
# specifically the high-cardinality features is the strongest available signal
# of an encoding artifact rather than genuine predictive value.
# ------------------------------------------------------------------------------
print("\n--- Permutation importance (1-year model, 10 repeats, held-out test set) ---")
perm_result = permutation_importance(model_1y, Xte_1y, yte_1y, scoring='roc_auc',
                                      n_repeats=10, random_state=42, n_jobs=-1)
perm_ranking = pd.Series(perm_result.importances_mean, index=Xte_1y.columns).sort_values(ascending=False)
perm_std = pd.Series(perm_result.importances_std, index=Xte_1y.columns)
compare = pd.DataFrame({
    'shap_rank': ranking_1y.rank(ascending=False),
    'perm_rank': perm_ranking.rank(ascending=False),
    'perm_importance': perm_ranking, 'perm_std': perm_std,
}).loc[ranking_1y.head(15).index].sort_values('shap_rank')
print(compare.to_string())
print("  Large shap_rank vs perm_rank gaps on PERM_STATE/REGION/HOME_STATE_DON specifically "
      "would support the high-cardinality-artifact hypothesis; close agreement supports genuine signal.")

# ------------------------------------------------------------------------------
# PHASE K — REAL-CATEGORY SHAP BREAKDOWN (bypasses the ordinal-code opacity
# problem entirely by joining back to t_df3's real labels, not the encoded ints)
# ------------------------------------------------------------------------------
def real_category_shap_summary(shap_values, feature_name, X, real_vals_series, label):
    feat_idx = X.columns.get_loc(feature_name)
    df = pd.DataFrame({'real_value': real_vals_series.values, 'shap': shap_values[:, feat_idx]})
    summary = df.groupby('real_value')['shap'].agg(['mean', 'std', 'count']).sort_values('mean', ascending=False)
    print(f"\n{label} — {feature_name} SHAP by real category:")
    print(summary.to_string())
    small_n = summary[summary['count'] < 30]
    if len(small_n) > 0:
        print(f"  !! {len(small_n)} categories have n<30 — their extreme means are likely noise, not signal.")
    return summary

for feat in ['PERM_STATE', 'REGION']:
    if feat in geo_check.columns:
        real_category_shap_summary(shap_1y, feat, Xte_1y, geo_check[feat], "1-Year")

# ------------------------------------------------------------------------------
# PHASE L — REFINED DOMAIN MAP: separate geography and temporal/administrative
# from the socioeconomic domain, so the equity narrative isn't accidentally
# built on unexamined category-splitting artifacts.
# ------------------------------------------------------------------------------
DOMAIN_MAP_REFINED = dict(DOMAIN_MAP)
DOMAIN_MAP_REFINED['geographic_access'] = ['PERM_STATE', 'PERM_STATE_TRR', 'REGION', 'HOME_STATE_DON', 'DISTANCE']
DOMAIN_MAP_REFINED['socioeconomic_access_proxy'] = ['EDUCATION', 'CITIZENSHIP', 'PRI_PAYMENT_TCR',
                                                     'PRI_PAYMENT_TRR', 'WORK_INCOME_TCR', 'WORK_INCOME_TRR']
DOMAIN_MAP_REFINED['temporal_administrative'] = ['LISTYR', 'END_STAT', 'INIT_STAT', 'DON_RETYP']

domains_1y_refined = domain_summary(ranking_1y, "1-Year (refined domain map)")
domains_3y_incident_refined = domain_summary(ranking_3y_incident, "3-Year Incident (refined domain map)")

# ------------------------------------------------------------------------------
# PHASE M — RE-RAISED: END_STAT/INIT_STAT era-consistency check (flagged
# BEFORE training as a risk, now empirically load-bearing given the SHAP
# ranking above — run this if you have not already)
# ------------------------------------------------------------------------------
print("\n--- END_STAT / INIT_STAT era-consistency check ---")
t_df3['ERA'] = np.where(t_df3['TX_DATE'] < SPLIT_DATE, 'pre_2018', 'post_2018')
for col in ['INIT_STAT', 'END_STAT']:
    if col in t_df3.columns:
        print(f"\n{col} by era:")
        print(pd.crosstab(t_df3[col], t_df3['ERA'], dropna=False))

--- Cardinality of disputed top features (real values, test set) ---
  PERM_STATE: 53 unique values, 48 missing
  HOME_STATE_DON: 52 unique values, 113 missing
  DON_RETYP: 2 unique values, 98 missing
  LISTYR: 17 unique values, 0 missing
  END_STAT: 9 unique values, 0 missing
  INIT_STAT: 10 unique values, 0 missing

--- Permutation importance (1-year model, 10 repeats, held-out test set) ---
                         shap_rank  perm_rank  perm_importance  perm_std
PERM_STATE                     1.0        1.0         0.065516  0.003123
AGE                            2.0        2.0         0.010984  0.001887
DON_RETYP                      3.0        4.0         0.005266  0.001115
GENDER                         4.0        5.0         0.005113  0.001097
FUNC_STAT_TRR                  5.0       30.0         0.000372  0.000486
DQ1                            6.0        3.0         0.009889  0.001435
HOME_STATE_DON                 7.0        8.0         0.002395  0.000375
HEMO_CO_TRR                    8.0      252.0        -0.000320  0.000319
DQ2                            9.0        7.0         0.003244  0.001126
TOT_SERUM_ALBUM_MISSING       10.0       70.0         0.000085  0.000024
DRMIS                         11.0        6.0         0.003487  0.000851
LISTYR                        12.0      227.0        -0.000047  0.000070
WGT_KG_TCR                    13.0       63.0         0.000109  0.000329
END_STAT                      14.0      228.0        -0.000050  0.000039
EBV_SEROSTATUS                15.0       78.0         0.000062  0.000200
  Large shap_rank vs perm_rank gaps on PERM_STATE/REGION/HOME_STATE_DON specifically would support the high-cardinality-artifact hypothesis; close agreement supports genuine signal.

1-Year — PERM_STATE SHAP by real category:
                mean       std  count
real_value
FL          0.271158  0.060232    956
CO          0.240345  0.034402    178
ZZ          0.236099  0.038268      3
OH          0.215840  0.095237    483
WY          0.200219  0.102717     11
WV          0.199095  0.064653     75
NY          0.196472  0.070189    912
NC          0.186548  0.081849    604
OR          0.178585  0.038337    132
WI          0.159503  0.114627    349
OK          0.158960  0.036426     99
DE          0.116851  0.038033     45
DC          0.113646  0.043529     37
CT          0.100936  0.047600    285
AL          0.092948  0.103970    122
NJ          0.084643  0.033534    340
NM          0.083116  0.029582     45
NV          0.073555  0.026162     89
PA          0.060574  0.025627    557
NE          0.057098  0.022821    124
AK          0.043644  0.110241     18
SC          0.035094  0.022013    301
GA          0.033672  0.037400    418
RI          0.033200  0.023656     40
SD          0.031144  0.022511     25
IA          0.029059  0.029225    127
TN          0.026308  0.021385    416
MA          0.018188  0.025153    308
ID          0.017159  0.031780     43
ME          0.016237  0.023480     60
MD          0.010963  0.049050    323
IL          0.008577  0.035760    535
NH          0.005705  0.028982     52
HI          0.005092  0.028682     28
PR         -0.003034  0.025569     14
MI         -0.012925  0.022351    333
MS         -0.019123  0.037149     88
UT         -0.019126  0.022635    117
MT         -0.020832  0.033564     30
TX         -0.021073  0.034818   1108
VA         -0.029533  0.031238    470
VI         -0.037878  0.024100      3
VT         -0.053974  0.040028     21
MN         -0.054640  0.023542    217
KY         -0.109981  0.036610    189
IN         -0.119546  0.036245    285
KS         -0.126031  0.037419    194
LA         -0.144723  0.031900    111
AR         -0.158408  0.105046     85
AZ         -0.159714  0.106184    235
MO         -0.248935  0.055102    286
CA         -0.404647  0.067197   1551
WA         -0.421941  0.052579    271
  !! 8 categories have n<30 — their extreme means are likely noise, not signal.

--- 1-Year (refined domain map): domain-level SHAP contribution ---
                    domain  total_mean_abs_shap  n_features    share
socioeconomic_access_proxy             0.174314           8 0.164987
  recipient_acute_severity             0.067737           7 0.064113
 immunologic_sensitization             0.054323           8 0.051416
       infectious_serology             0.017632           4 0.016689
       donor_organ_quality             0.014860           5 0.014065
    perioperative_surgical             0.001165           1 0.001103
  Unmapped features (assign these by hand, 233): ['AGE', 'DON_RETYP', 'GENDER', 'DQ1', 'HOME_STATE_DON', 'HEMO_CO_TRR', 'DQ2', 'TOT_SERUM_ALBUM_MISSING', 'LISTYR', 'WGT_KG_TCR', 'END_STAT', 'DB1', 'SHARE_TY', 'WGT_KG_CALC', 'PT_STEROIDS_DON']

--- 3-Year Incident (refined domain map): domain-level SHAP contribution ---
                    domain  total_mean_abs_shap  n_features    share
socioeconomic_access_proxy             0.176788           8 0.166169
  recipient_acute_severity             0.057835           7 0.054361
 immunologic_sensitization             0.053565           8 0.050348
       infectious_serology             0.019845           4 0.018653
       donor_organ_quality             0.016264           5 0.015287
    perioperative_surgical             0.001233           1 0.001159
  Unmapped features (assign these by hand, 236): ['AGE', 'DON_RETYP', 'HOME_STATE_DON', 'GENDER', 'TOT_SERUM_ALBUM_MISSING', 'DQ1', 'LISTYR', 'SHARE_TY', 'WGT_KG_TCR', 'HEMO_CO_TRR', 'DQ2', 'TCR_DUR_ABSTAIN', 'WGT_KG_CALC', 'PT_STEROIDS_DON', 'C1']

--- END_STAT / INIT_STAT era-consistency check ---

INIT_STAT by era:
ERA        post_2018  pre_2018
INIT_STAT
2010.0           224      8290
2020.0           694     14295
2030.0           571     12871
2090.0             0        34
2110.0           790         0
2120.0          4405         0
2130.0          1691         0
2140.0          4404         0
2150.0            17         0
2160.0          2412         0
2999.0           145       660
NaN                0         3

END_STAT by era:
ERA       post_2018  pre_2018
END_STAT
2010.0           55     18601
2020.0           26     13163
2030.0            9      4386
2110.0         1559         0
2120.0         7670         0
2130.0         2456         0
2140.0         2769         0
2150.0           11         0
2160.0          798         0
2999.0            0         3

In [ ]:
# ==============================================================================
# SEGMENT 7 — PART 4: Final figures and export tables
# ==============================================================================

# ------------------------------------------------------------------------------
# FIGURE 1 — Rank-shift slope chart (1yr rank -> 3yr-incident rank)
# ------------------------------------------------------------------------------
top_shared = ranking_1y.head(20).index.intersection(ranking_3y_incident.index)
slope_df = pd.DataFrame({
    'rank_1y': ranking_1y[top_shared].rank(ascending=False),
    'rank_3y_incident': ranking_3y_incident[top_shared].rank(ascending=False),
}, index=top_shared)

fig, ax = plt.subplots(figsize=(6, 9))
for feat in slope_df.index:
    ax.plot([0, 1], [slope_df.loc[feat, 'rank_1y'], slope_df.loc[feat, 'rank_3y_incident']],
            marker='o', color='steelblue', alpha=0.7)
    ax.text(-0.05, slope_df.loc[feat, 'rank_1y'], feat, ha='right', va='center', fontsize=8)
    ax.text(1.05, slope_df.loc[feat, 'rank_3y_incident'], feat, ha='left', va='center', fontsize=8)
ax.set_xticks([0, 1]); ax.set_xticklabels(['1-Year Model', '3-Year Incident Model'])
ax.invert_yaxis(); ax.set_ylabel("SHAP importance rank (1 = most important)")
ax.set_title(f"Cross-Horizon Feature-Rank Shift (Spearman ρ = {rho_inc:.3f})")
ax.set_xlim(-0.5, 1.5)
plt.tight_layout(); plt.savefig(FIG_DIR_3Y / "rank_shift_slope.png", dpi=150, bbox_inches='tight'); plt.close()

# ------------------------------------------------------------------------------
# FIGURE 2 — Bootstrap SHAP-rank stability forest plot
# ------------------------------------------------------------------------------
def plot_stability_forest(stability_df, label, fig_dir, top_n=15):
    d = stability_df.head(top_n).iloc[::-1]
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.errorbar(d['median_rank'], range(len(d)),
                xerr=[d['median_rank'] - d['ci_low'], d['ci_high'] - d['median_rank']],
                fmt='o', color='darkred', ecolor='gray', capsize=3)
    ax.set_yticks(range(len(d))); ax.set_yticklabels(d.index)
    ax.set_xlabel("Feature rank (bootstrap median, 95% CI)")
    ax.set_title(f"SHAP-Rank Stability — {label}")
    plt.tight_layout(); plt.savefig(fig_dir / f"stability_forest_{label.lower().replace(' ', '_')}.png",
                                     dpi=150, bbox_inches='tight'); plt.close()

plot_stability_forest(stability_1y, "1-Year", FIG_DIR_1Y)
plot_stability_forest(stability_3y_incident, "3-Year Incident", FIG_DIR_3Y)

# ------------------------------------------------------------------------------
# FIGURE 3 — Refined domain-share comparison
# ------------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 5))
merged_refined = domains_1y_refined.set_index('domain')['share'].to_frame('1-Year').join(
    domains_3y_incident_refined.set_index('domain')['share'].to_frame('3-Year Incident'), how='outer').fillna(0)
merged_refined.plot(kind='barh', ax=ax)
ax.set_xlabel("Share of total mean |SHAP|"); ax.set_title("Domain-Level SHAP (Refined Mapping): 1-Year vs. 3-Year Incident")
plt.tight_layout(); plt.savefig(FIG_DIR_3Y / "domain_shap_comparison_refined.png", dpi=150, bbox_inches='tight'); plt.close()

# ------------------------------------------------------------------------------
# TABLE — Consolidated top-15, both horizons, with bootstrap CI, for direct
# thesis insertion
# ------------------------------------------------------------------------------
export_table = pd.DataFrame({
    '1yr_mean_abs_shap': ranking_1y, '1yr_rank': ranking_1y.rank(ascending=False),
}).join(pd.DataFrame({
    '3yr_incident_mean_abs_shap': ranking_3y_incident, '3yr_incident_rank': ranking_3y_incident.rank(ascending=False),
}), how='outer').join(stability_1y[['ci_low', 'ci_high']].rename(
    columns={'ci_low': '1yr_rank_ci_low', 'ci_high': '1yr_rank_ci_high'}), how='left'
).sort_values('1yr_rank').head(20)
export_table.to_csv(BASE / "results" / "shap_summary_table_for_thesis.csv")
print("Exported -> shap_summary_table_for_thesis.csv")

print(f"\n{'='*70}\nSEGMENT 7 COMPLETE — Parts 1-4.\n{'='*70}")

Exported -> shap_summary_table_for_thesis.csv

======================================================================
SEGMENT 7 COMPLETE — Parts 1-4.
======================================================================

In [ ]:
# ==============================================================================
# SEGMENT 7: INTERPRETABILITY FRAMEWORK
# ==============================================================================
#
# Five-layer pipeline:
#   Layer 1 — Global SHAP (beeswarm, bar, interaction) for best model, both horizons
#   Layer 2 — SHAP waterfall case studies (TP, FP, FN, TN)
#   Layer 3 — LIME local case studies
#   Layer 4 — Partial Dependence + ICE for top-5 SHAP features
#   Layer 5 — Option B: SHAP-guided iterative feature pruning (CS novelty)
#
# Cross-horizon comparison: top-10 feature rankings at 1yr vs 3yr
# ==============================================================================

# ── Installs ──────────────────────────────────────────────────────────────────
import subprocess
subprocess.run(["pip", "install", "shap", "lime", "--quiet"], capture_output=True)

import shap
import lime
import lime.lime_tabular
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import numpy as np
import pandas as pd
import pickle
import os
import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics         import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.inspection      import PartialDependenceDisplay
from sklearn.feature_selection import RFE

# ==============================================================================
# CONFIGURATION
# ==============================================================================

BASE    = "/content/drive/MyDrive/Thesis_parquet"
OUT_DIR = f"{BASE}/results"
MDL_DIR = f"{BASE}/models"
FIG_DIR = f"{BASE}/results/figures"
OUT_3YR = f"{BASE}/results_3yr"
MDL_3YR = f"{BASE}/models_3yr"
os.makedirs(FIG_DIR, exist_ok=True)

PRIMARY_STRATEGY   = 'S2_BALANCED'
SHAP_BEST_STRATEGY = 'S3_THRESHOLD'  # plain model, easiest for TreeExplainer
RANDOM_STATE       = 42
N_ICE_SAMPLES      = 200             # ICE curves: 200 random patients
SHAP_INTERACTION_N = 500             # patients for interaction computation

print("=" * 70)
print("SEGMENT 7: INTERPRETABILITY FRAMEWORK")
print("=" * 70)

# ==============================================================================
# PHASE A — LOAD MODELS AND DATA
# ==============================================================================

print("\nPhase A — Loading models and data...")

# Feature matrices
X_train_tree = pd.read_parquet(f"{BASE}/X_train_tree.parquet")
X_test_tree  = pd.read_parquet(f"{BASE}/X_test_tree.parquet")
y_train = pd.read_parquet(f"{BASE}/y_train.parquet").squeeze().astype(int)
y_test  = pd.read_parquet(f"{BASE}/y_test.parquet").squeeze().astype(int)

Xt_train  = X_train_tree.values.astype('float32')
Xt_test   = X_test_tree.values.astype('float32')
yt_arr    = y_train.values
ytest_arr = y_test.values
feature_names = X_train_tree.columns.tolist()
n_features = len(feature_names)

# 3-year matrices (if available)
try:
    X_train_tree_3yr = pd.read_parquet(f"{BASE}/X_train_tree_3yr.parquet")
    X_test_tree_3yr  = pd.read_parquet(f"{BASE}/X_test_tree_3yr.parquet")
    y_train_3yr = pd.read_parquet(f"{BASE}/y_train_3yr.parquet").squeeze().astype(int)
    y_test_3yr  = pd.read_parquet(f"{BASE}/y_test_3yr.parquet").squeeze().astype(int)
    Xt_train_3  = X_train_tree_3yr.values.astype('float32')
    Xt_test_3   = X_test_tree_3yr.values.astype('float32')
    yt3_arr     = y_train_3yr.values
    ytest3_arr  = y_test_3yr.values
    HAS_3YR = True
    print(f"  ✓ 3-year data loaded")
except FileNotFoundError:
    HAS_3YR = False
    print(f"  ⚠ 3-year data not found — skipping cross-horizon analysis")

# Load best model for 1-year
best_model_name = 'CatBoost'  # change if your Segment 6 found different best
model_1yr_path  = f"{MDL_DIR}/model_{best_model_name}_{SHAP_BEST_STRATEGY}.pkl"

with open(model_1yr_path, 'rb') as f:
    model_1yr = pickle.load(f)

# Extract estimator if model is inside ImblearnPipeline
def extract_estimator(model):
    """Extract the base estimator from an imblearn pipeline if needed."""
    if hasattr(model, 'named_steps'):
        return model.named_steps.get('model', model)
    return model

estimator_1yr = extract_estimator(model_1yr)

# Get test set predictions
y_prob_1yr = model_1yr.predict_proba(Xt_test)[:, 1]
auroc_1yr  = roc_auc_score(ytest_arr, y_prob_1yr)
print(f"\n  1yr model loaded: {best_model_name}/{SHAP_BEST_STRATEGY}  "
      f"AUROC={auroc_1yr:.4f}")

# Determine optimal threshold (from Segment 6 results or recalculate)
results_csv = pd.read_csv(f"{OUT_DIR}/table_primary_results.csv")
thr_row = results_csv[
    (results_csv['model'] == best_model_name) &
    (results_csv['strategy'] == SHAP_BEST_STRATEGY)
]
if len(thr_row) > 0:
    OPTIMAL_THRESHOLD_1YR = float(thr_row.iloc[0]['threshold'])
else:
    OPTIMAL_THRESHOLD_1YR = 0.5
y_pred_1yr = (y_prob_1yr >= OPTIMAL_THRESHOLD_1YR).astype(int)
print(f"  Optimal threshold (1yr): {OPTIMAL_THRESHOLD_1YR:.3f}")

# Load 3yr model if available
if HAS_3YR:
    model_3yr_path = f"{MDL_3YR}/model_{best_model_name}_{SHAP_BEST_STRATEGY}_3yr.pkl"
    if os.path.exists(model_3yr_path):
        with open(model_3yr_path, 'rb') as f:
            model_3yr = pickle.load(f)
        estimator_3yr = extract_estimator(model_3yr)
        y_prob_3yr    = model_3yr.predict_proba(Xt_test_3)[:, 1]
        y_pred_3yr    = (y_prob_3yr >= 0.5).astype(int)
        print(f"  3yr model loaded: AUROC={roc_auc_score(ytest3_arr, y_prob_3yr):.4f}")
    else:
        HAS_3YR = False
        print(f"  ⚠ 3yr model pickle not found")

# ==============================================================================
# PHASE B — GLOBAL SHAP ANALYSIS
# ==============================================================================

print("\n" + "="*70)
print("PHASE B — GLOBAL SHAP ANALYSIS (Layer 1)")
print("="*70)

def compute_shap_values(estimator, X_data, feature_names_list):
    """
    Compute SHAP values using TreeExplainer.
    Returns shap_values (n_samples, n_features) — positive class.
    """
    print(f"  Computing SHAP values for {len(X_data):,} patients "
          f"({X_data.shape[1]} features)...")
    explainer  = shap.TreeExplainer(estimator)
    shap_vals  = explainer.shap_values(X_data)
    base_value = float(np.mean(explainer.expected_value)) \
                 if hasattr(explainer.expected_value, '__len__') \
                 else float(explainer.expected_value)

    # Handle list output (binary classifiers sometimes return [class0, class1])
    if isinstance(shap_vals, list):
        shap_vals = shap_vals[1]

    print(f"  ✓ SHAP values computed. Shape: {shap_vals.shape}")
    return shap_vals, explainer, base_value


# ── 1-year SHAP ───────────────────────────────────────────────────────────────
shap_values_1yr, explainer_1yr, base_val_1yr = compute_shap_values(
    estimator_1yr, Xt_test, feature_names)

# Mean |SHAP| for feature ranking
mean_shap_1yr = np.abs(shap_values_1yr).mean(axis=0)
top_idx_1yr   = np.argsort(mean_shap_1yr)[::-1]
top_names_1yr = [feature_names[i] for i in top_idx_1yr]

print(f"\n  Top 10 features by |SHAP| (1-year):")
for rank, (idx, name) in enumerate(zip(top_idx_1yr[:10], top_names_1yr[:10]), 1):
    print(f"    {rank:2d}. {name:40s}  mean|SHAP| = {mean_shap_1yr[idx]:.4f}")

# Save SHAP values for downstream use
np.save(f"{OUT_DIR}/shap_values_1yr.npy", shap_values_1yr)
np.save(f"{OUT_DIR}/shap_base_value_1yr.npy", np.array([base_val_1yr]))

# ── Beeswarm plot (global importance with direction) ──────────────────────────
plt.figure(figsize=(12, 8))
shap.summary_plot(
    shap_values_1yr,
    pd.DataFrame(Xt_test, columns=feature_names),
    plot_type="dot",
    max_display=20,
    show=False
)
plt.title(f"Global SHAP Feature Importance — {best_model_name} (1-Year Rejection)",
          fontsize=13, pad=12)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/shap_beeswarm_1yr.png", dpi=200, bbox_inches='tight')
plt.close()
print(f"\n  ✓ Beeswarm plot saved → shap_beeswarm_1yr.png")

# ── Bar plot (clean ranking) ──────────────────────────────────────────────────
plt.figure(figsize=(10, 8))
shap.summary_plot(
    shap_values_1yr,
    pd.DataFrame(Xt_test, columns=feature_names),
    plot_type="bar",
    max_display=20,
    show=False
)
plt.title(f"Mean |SHAP| Feature Ranking — {best_model_name} (1-Year Rejection)",
          fontsize=13, pad=12)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/shap_bar_1yr.png", dpi=200, bbox_inches='tight')
plt.close()
print(f"  ✓ Bar plot saved → shap_bar_1yr.png")

# ── SHAP feature ranking to CSV ───────────────────────────────────────────────
shap_rank_1yr = pd.DataFrame({
    'feature':    feature_names,
    'mean_abs_shap_1yr': mean_shap_1yr,
    'rank_1yr':   pd.Series(mean_shap_1yr).rank(ascending=False).astype(int).values
}).sort_values('mean_abs_shap_1yr', ascending=False)

# ── 3-year SHAP (if available) ────────────────────────────────────────────────
if HAS_3YR:
    shap_values_3yr, explainer_3yr, base_val_3yr = compute_shap_values(
        estimator_3yr, Xt_test_3, feature_names)
    mean_shap_3yr = np.abs(shap_values_3yr).mean(axis=0)
    top_idx_3yr   = np.argsort(mean_shap_3yr)[::-1]
    top_names_3yr = [feature_names[i] for i in top_idx_3yr]

    np.save(f"{OUT_3YR}/shap_values_3yr.npy", shap_values_3yr)

    plt.figure(figsize=(12, 8))
    shap.summary_plot(
        shap_values_3yr,
        pd.DataFrame(Xt_test_3, columns=feature_names),
        plot_type="dot", max_display=20, show=False
    )
    plt.title(f"Global SHAP Feature Importance — {best_model_name} (3-Year Rejection)",
              fontsize=13, pad=12)
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/shap_beeswarm_3yr.png", dpi=200, bbox_inches='tight')
    plt.close()
    print(f"  ✓ 3yr beeswarm saved → shap_beeswarm_3yr.png")

    # ── Cross-horizon feature ranking comparison ──────────────────────────────
    shap_rank_3yr = pd.DataFrame({
        'feature':           feature_names,
        'mean_abs_shap_3yr': mean_shap_3yr,
        'rank_3yr': pd.Series(mean_shap_3yr).rank(ascending=False).astype(int).values
    })

    horizon_compare = shap_rank_1yr.merge(shap_rank_3yr, on='feature')
    horizon_compare['rank_shift'] = horizon_compare['rank_1yr'] - horizon_compare['rank_3yr']
    horizon_compare = horizon_compare.sort_values('mean_abs_shap_1yr', ascending=False)
    horizon_compare.to_csv(f"{FIG_DIR}/shap_cross_horizon_comparison.csv", index=False)

    # Cross-horizon comparison figure
    top15 = horizon_compare.head(15)['feature'].values
    hc_sub = horizon_compare[horizon_compare['feature'].isin(top15)].copy()

    fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=False)
    colors_1 = ['#d62728' if r <= 5 else '#1f77b4' if r <= 10 else '#aec7e8'
                for r in hc_sub.sort_values('rank_1yr')['rank_1yr']]
    colors_3 = ['#d62728' if r <= 5 else '#1f77b4' if r <= 10 else '#aec7e8'
                for r in hc_sub.sort_values('rank_3yr')['rank_3yr']]

    hc_1yr = hc_sub.sort_values('mean_abs_shap_1yr', ascending=True)
    hc_3yr = hc_sub.sort_values('mean_abs_shap_3yr', ascending=True)

    axes[0].barh(hc_1yr['feature'], hc_1yr['mean_abs_shap_1yr'], color='#1f77b4')
    axes[0].set_title('1-Year Rejection\nFeature Importance (SHAP)', fontsize=12)
    axes[0].set_xlabel('Mean |SHAP value|')

    axes[1].barh(hc_3yr['feature'], hc_3yr['mean_abs_shap_3yr'], color='#ff7f0e')
    axes[1].set_title('3-Year Rejection\nFeature Importance (SHAP)', fontsize=12)
    axes[1].set_xlabel('Mean |SHAP value|')

    plt.suptitle(f'Cross-Horizon SHAP Comparison — {best_model_name}',
                 fontsize=13, y=1.02)
    plt.tight_layout()
    plt.savefig(f"{FIG_DIR}/shap_cross_horizon_comparison.png",
                dpi=200, bbox_inches='tight')
    plt.close()
    print(f"  ✓ Cross-horizon comparison saved")

    print(f"\n  Top 10 rank shifts (1yr → 3yr):")
    shifts = horizon_compare.sort_values('rank_shift', key=abs, ascending=False).head(10)
    for _, row in shifts.iterrows():
        arrow = "↑" if row['rank_shift'] > 0 else "↓"
        print(f"    {row['feature']:40s}  rank {int(row['rank_1yr']):2d} → "
              f"{int(row['rank_3yr']):2d}  {arrow} {abs(int(row['rank_shift']))}")

# ==============================================================================
# PHASE C — SHAP CASE STUDIES (WATERFALL PLOTS)
# ==============================================================================

print("\n" + "="*70)
print("PHASE C — SHAP CASE STUDIES — Layer 2")
print("="*70)

# Identify four representative patients
tp_idx = np.where((y_pred_1yr == 1) & (ytest_arr == 1))[0]
fp_idx = np.where((y_pred_1yr == 1) & (ytest_arr == 0))[0]
fn_idx = np.where((y_pred_1yr == 0) & (ytest_arr == 1))[0]
tn_idx = np.where((y_pred_1yr == 0) & (ytest_arr == 0))[0]

# Most informative cases
case_tp = tp_idx[np.argmax(y_prob_1yr[tp_idx])]   if len(tp_idx) > 0 else None
case_fp = fp_idx[np.argmax(y_prob_1yr[fp_idx])]   if len(fp_idx) > 0 else None
case_fn = fn_idx[np.argmin(y_prob_1yr[fn_idx])]   if len(fn_idx) > 0 else None
case_tn = tn_idx[np.argmin(y_prob_1yr[tn_idx])]   if len(tn_idx) > 0 else None

print(f"  Case study patients:")
for label, idx in [('TP',case_tp),('FP',case_fp),('FN',case_fn),('TN',case_tn)]:
    if idx is not None:
        print(f"    {label}: patient index {idx}  "
              f"predicted={y_prob_1yr[idx]:.3f}  "
              f"actual={'REJECTED' if ytest_arr[idx]==1 else 'no rejection'}")

# Build shap.Explanation object for waterfall plots
explanation_1yr = shap.Explanation(
    values      = shap_values_1yr,
    base_values = np.full(len(Xt_test), base_val_1yr),
    data        = Xt_test,
    feature_names = feature_names
)

case_labels = {'TP': case_tp, 'FP': case_fp, 'FN': case_fn, 'TN': case_tn}

fig, axes = plt.subplots(2, 2, figsize=(20, 14))
axes = axes.flatten()

for ax_idx, (case_name, patient_idx) in enumerate(case_labels.items()):
    if patient_idx is None:
        axes[ax_idx].text(0.5, 0.5, f'No {case_name} cases found',
                          ha='center', va='center', transform=axes[ax_idx].transAxes)
        continue

    plt.sca(axes[ax_idx])
    shap.plots.waterfall(explanation_1yr[patient_idx], max_display=15, show=False)
    actual   = "Rejected" if ytest_arr[patient_idx] == 1 else "Not Rejected"
    pred_dir = "HIGH RISK" if y_pred_1yr[patient_idx] == 1 else "LOW RISK"
    axes[ax_idx].set_title(
        f"{case_name} — {pred_dir} (p={y_prob_1yr[patient_idx]:.3f}) | Actual: {actual}",
        fontsize=11, fontweight='bold'
    )

plt.suptitle(f"SHAP Waterfall Case Studies — {best_model_name} (1-Year Rejection)",
             fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/shap_waterfall_cases_1yr.png", dpi=200, bbox_inches='tight')
plt.close()
print(f"\n  ✓ Waterfall case studies saved → shap_waterfall_cases_1yr.png")

# Save case study data as CSV for thesis table
case_data = []
for case_name, patient_idx in case_labels.items():
    if patient_idx is not None:
        top5_feat_idx = np.argsort(np.abs(shap_values_1yr[patient_idx]))[::-1][:5]
        for rank, fi in enumerate(top5_feat_idx, 1):
            case_data.append({
                'case_type':      case_name,
                'patient_index':  int(patient_idx),
                'predicted_prob': round(float(y_prob_1yr[patient_idx]), 4),
                'actual_label':   int(ytest_arr[patient_idx]),
                'shap_rank':      rank,
                'feature':        feature_names[fi],
                'shap_value':     round(float(shap_values_1yr[patient_idx, fi]), 4),
                'feature_value':  round(float(Xt_test[patient_idx, fi]), 4),
            })
pd.DataFrame(case_data).to_csv(f"{FIG_DIR}/shap_case_study_data.csv", index=False)
print(f"  ✓ Case study data saved → shap_case_study_data.csv")

# ==============================================================================
# PHASE D — LIME CASE STUDIES (Layer 3)
# ==============================================================================

print("\n" + "="*70)
print("PHASE D — LIME CASE STUDIES — Layer 3")
print("="*70)

lime_explainer = lime.lime_tabular.LimeTabularExplainer(
    Xt_train,
    feature_names    = feature_names,
    class_names      = ['No Rejection', 'Rejection'],
    mode             = 'classification',
    discretize_continuous = True,
    random_state     = RANDOM_STATE
)

lime_results = {}

fig, axes = plt.subplots(2, 2, figsize=(22, 16))
axes = axes.flatten()

for ax_idx, (case_name, patient_idx) in enumerate(case_labels.items()):
    if patient_idx is None:
        axes[ax_idx].text(0.5, 0.5, f'No {case_name} cases',
                          ha='center', va='center', transform=axes[ax_idx].transAxes)
        continue

    try:
        lime_exp = lime_explainer.explain_instance(
            Xt_test[patient_idx],
            model_1yr.predict_proba,
            num_features = 15,
            num_samples  = 500
        )
        lime_results[case_name] = lime_exp

        # Plot
        lime_exp.as_pyplot_figure()
        fig_lime = plt.gcf()
        actual   = "Rejected" if ytest_arr[patient_idx] == 1 else "Not Rejected"
        pred_dir = "HIGH" if y_pred_1yr[patient_idx] == 1 else "LOW"
        fig_lime.suptitle(
            f"{case_name} — Predicted {pred_dir} RISK (p={y_prob_1yr[patient_idx]:.3f}) | "
            f"Actual: {actual}", fontsize=11, fontweight='bold'
        )
        fig_lime.tight_layout()
        fig_lime.savefig(f"{FIG_DIR}/lime_{case_name.lower()}_1yr.png",
                         dpi=200, bbox_inches='tight')
        plt.close(fig_lime)

        # Save LIME explanation as CSV
        lime_df = pd.DataFrame(lime_exp.as_list(),
                               columns=['feature_condition', 'weight'])
        lime_df['case_type']     = case_name
        lime_df['patient_index'] = int(patient_idx)
        lime_df['predicted_prob']= round(float(y_prob_1yr[patient_idx]), 4)
        lime_df['actual_label']  = int(ytest_arr[patient_idx])
        lime_df.to_csv(f"{FIG_DIR}/lime_{case_name.lower()}_data.csv", index=False)

        print(f"  ✓ LIME {case_name} saved")
    except Exception as e:
        print(f"  ⚠ LIME {case_name} failed: {e}")

# ==============================================================================
# PHASE E — PARTIAL DEPENDENCE + ICE PLOTS (Layer 4)
# ==============================================================================

print("\n" + "="*70)
print("PHASE E — PDP + ICE — Layer 4")
print("="*70)

top5_feat_idx   = top_idx_1yr[:5]
top5_feat_names = top_names_1yr[:5]

print(f"  Top-5 features for PDP/ICE: {top5_feat_names}")

fig, axes = plt.subplots(1, 5, figsize=(28, 5))

for ax_i, (feat_idx, feat_name) in enumerate(zip(top5_feat_idx, top5_feat_names)):
    try:
        PartialDependenceDisplay.from_estimator(
            estimator_1yr,
            Xt_train,
            features        = [feat_idx],
            kind            = 'both',     # PDP + ICE together
            subsample       = N_ICE_SAMPLES,
            ax              = axes[ax_i],
            random_state    = RANDOM_STATE,
            ice_lines_kw    = {'alpha': 0.05, 'color': '#aec7e8'},
            pd_line_kw      = {'color': '#d62728', 'linewidth': 2.5},
            feature_names   = feature_names
        )
        axes[ax_i].set_title(feat_name.replace('_',' '), fontsize=9, fontweight='bold')
        axes[ax_i].set_xlabel('')
    except Exception as e:
        axes[ax_i].text(0.5, 0.5, f'PDP failed\n{str(e)[:50]}',
                        ha='center', va='center', transform=axes[ax_i].transAxes,
                        fontsize=7)

plt.suptitle(f"Partial Dependence + ICE Plots — {best_model_name} (1-Year Rejection)\n"
             f"Top-5 SHAP Features | ICE={N_ICE_SAMPLES} patients | PDP=red line",
             fontsize=11, y=1.03)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/pdp_ice_top5_1yr.png", dpi=200, bbox_inches='tight')
plt.close()
print(f"  ✓ PDP/ICE plot saved → pdp_ice_top5_1yr.png")

# ── 2D PDP for interaction pair (ischaemic time × HLA) ───────────────────────
interaction_features = ['ISCHTIME', 'HLA_total_mismatch_weighted']
interaction_idx = [feature_names.index(f) for f in interaction_features
                   if f in feature_names]

if len(interaction_idx) == 2:
    try:
        fig, ax = plt.subplots(figsize=(8, 6))
        PartialDependenceDisplay.from_estimator(
            estimator_1yr, Xt_train,
            features     = [tuple(interaction_idx)],
            kind         = 'average',
            ax           = ax,
            feature_names= feature_names
        )
        ax.set_title("2D PDP: Ischaemic Time × Weighted HLA Mismatch\n"
                     f"{best_model_name} (1-Year Rejection)", fontsize=11)
        plt.tight_layout()
        plt.savefig(f"{FIG_DIR}/pdp_2d_ischtime_hla_1yr.png",
                    dpi=200, bbox_inches='tight')
        plt.close()
        print(f"  ✓ 2D PDP (ischaemic time × HLA) saved")
    except Exception as e:
        print(f"  ⚠ 2D PDP failed: {e}")

# ==============================================================================
# PHASE F — OPTION B: SHAP-GUIDED ITERATIVE FEATURE PRUNING (CS NOVELTY)
# ==============================================================================

print("\n" + "="*70)
print("PHASE F — SHAP-GUIDED ITERATIVE PRUNING — CS Novelty (Option B)")
print("="*70)
print("  Algorithm: iteratively remove the least important features by SHAP,")
print("  retrain, measure AUROC drop. Compare to RFE and random removal.")
print("  Thesis claim: SHAP-guided pruning identifies a minimal stable feature")
print("  subset that retains near-baseline AUROC with fewer features than RFE.")

from catboost import CatBoostClassifier
from sklearn.feature_selection import RFECV

# Use a validation fold (20% of training set) for pruning decisions — NOT test set
X_prune_train, X_prune_val, y_prune_train, y_prune_val = train_test_split(
    Xt_train, yt_arr,
    test_size    = 0.20,
    stratify     = yt_arr,
    random_state = RANDOM_STATE
)

# Load best CatBoost params from Segment 6
with open(f"{MDL_DIR}/best_params.pkl", 'rb') as f:
    best_params_all = pickle.load(f)

cb_best_p = {k: v for k, v in
             best_params_all.get(('CatBoost', 'S3_THRESHOLD'), {}).items()}
cb_fixed  = {'random_seed': RANDOM_STATE, 'verbose': 0,
             'eval_metric': 'AUC', 'thread_count': -1}
cb_params = {**cb_fixed, **cb_best_p}

PRUNE_STEP  = 5    # remove 5 features per iteration
DELTA_AUROC = 0.01 # stop if AUROC drops more than 1% below baseline
MIN_FEATURES = 10  # never go below 10 features

def run_shap_pruning(X_tr, y_tr, X_va, y_va, feature_names_list, params,
                     prune_step, delta, min_features):
    """SHAP-guided iterative feature pruning."""
    results   = []
    active    = list(range(len(feature_names_list)))
    fn_arr    = np.array(feature_names_list)

    # Baseline: train on all features
    model = CatBoostClassifier(**params)
    model.fit(X_tr[:, active], y_tr)
    baseline_prob  = model.predict_proba(X_va[:, active])[:, 1]
    baseline_auroc = roc_auc_score(y_va, baseline_prob)

    results.append({'n_features': len(active), 'auroc': baseline_auroc,
                    'method': 'SHAP-guided', 'removed': 'none'})
    print(f"    Baseline: {len(active)} features → AUROC={baseline_auroc:.4f}")

    while len(active) > min_features:
        # Compute SHAP on pruned training set
        expl = shap.TreeExplainer(model)
        sv   = expl.shap_values(X_tr[:, active])
        if isinstance(sv, list):
            sv = sv[1]

        local_importance = np.abs(sv).mean(axis=0)
        worst_local_idx  = np.argsort(local_importance)[:prune_step]
        worst_global_idx = [active[i] for i in worst_local_idx]
        removed_names    = fn_arr[worst_global_idx].tolist()

        active = [f for f in active if f not in worst_global_idx]

        model = CatBoostClassifier(**params)
        model.fit(X_tr[:, active], y_tr)
        prob  = model.predict_proba(X_va[:, active])[:, 1]
        auroc = roc_auc_score(y_va, prob)

        results.append({'n_features': len(active), 'auroc': auroc,
                        'method': 'SHAP-guided',
                        'removed': ', '.join(removed_names[:3])})

        print(f"    {len(active):3d} features → AUROC={auroc:.4f}  "
              f"(removed: {removed_names[0]}...)")

        if baseline_auroc - auroc > delta:
            print(f"    ✓ Stopping: AUROC drop {baseline_auroc - auroc:.4f} > {delta}")
            break

    return pd.DataFrame(results)


def run_random_pruning(X_tr, y_tr, X_va, y_va, n_features, params,
                       prune_step, min_features, seed):
    """Random feature removal baseline."""
    rng     = np.random.RandomState(seed)
    results = []
    active  = list(range(n_features))
    rng.shuffle(active)

    while len(active) >= min_features:
        model = CatBoostClassifier(**params)
        model.fit(X_tr[:, active], y_tr)
        prob  = model.predict_proba(X_va[:, active])[:, 1]
        auroc = roc_auc_score(y_va, prob)
        results.append({'n_features': len(active), 'auroc': auroc,
                        'method': 'Random removal', 'removed': '-'})
        active = active[prune_step:]

    return pd.DataFrame(results)


print(f"\n  Running SHAP-guided pruning "
      f"(step={PRUNE_STEP}, delta={DELTA_AUROC}, min_features={MIN_FEATURES})...")
shap_prune_df = run_shap_pruning(
    X_prune_train, y_prune_train,
    X_prune_val,   y_prune_val,
    feature_names, cb_params,
    PRUNE_STEP, DELTA_AUROC, MIN_FEATURES
)

# Find minimal feature set: most aggressive pruning before AUROC drops
if len(shap_prune_df) > 1:
    baseline_row   = shap_prune_df.iloc[0]
    pruning_floor  = shap_prune_df[
        shap_prune_df['auroc'] >= baseline_row['auroc'] - DELTA_AUROC
    ]
    optimal_row    = pruning_floor.iloc[-1]   # last row still above threshold
    print(f"\n  ✓ SHAP-stable minimal feature set: "
          f"{int(optimal_row['n_features'])} features "
          f"(AUROC={optimal_row['auroc']:.4f}, "
          f"baseline={baseline_row['auroc']:.4f}, "
          f"drop={baseline_row['auroc'] - optimal_row['auroc']:.4f})")
    MINIMAL_FEATURE_N = int(optimal_row['n_features'])
else:
    MINIMAL_FEATURE_N = n_features

print(f"\n  Running random removal baseline...")
random_prune_df = run_random_pruning(
    X_prune_train, y_prune_train,
    X_prune_val,   y_prune_val,
    n_features, cb_params,
    PRUNE_STEP, MIN_FEATURES, RANDOM_STATE
)

# Combine all pruning results
all_prune = pd.concat([shap_prune_df, random_prune_df], ignore_index=True)
all_prune.to_csv(f"{FIG_DIR}/shap_pruning_results.csv", index=False)

# ── Pruning comparison figure ─────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 6))

colors = {'SHAP-guided': '#d62728', 'Random removal': '#aec7e8'}
for method, grp in all_prune.groupby('method'):
    grp_sorted = grp.sort_values('n_features')
    ax.plot(grp_sorted['n_features'], grp_sorted['auroc'],
            marker='o', markersize=4, linewidth=2,
            label=method, color=colors.get(method, 'grey'))

# Mark baseline and optimal feature set
ax.axhline(y=shap_prune_df.iloc[0]['auroc'], color='grey',
           linestyle='--', alpha=0.7, label='Baseline (all features)')
ax.axhline(y=shap_prune_df.iloc[0]['auroc'] - DELTA_AUROC, color='orange',
           linestyle=':', alpha=0.7, label=f'Acceptable drop threshold (Δ={DELTA_AUROC})')
ax.axvline(x=MINIMAL_FEATURE_N, color='#d62728',
           linestyle=':', alpha=0.6, label=f'SHAP-stable minimum ({MINIMAL_FEATURE_N} features)')

ax.set_xlabel('Number of Features', fontsize=12)
ax.set_ylabel('AUROC (Validation Fold)', fontsize=12)
ax.set_title(f'SHAP-Guided Iterative Feature Pruning — {best_model_name}\n'
             f'CS Novelty: Minimal stable feature set identification',
             fontsize=12, fontweight='bold')
ax.legend(fontsize=9)
ax.set_xlim(left=MIN_FEATURES - 2)
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/shap_pruning_comparison.png", dpi=200, bbox_inches='tight')
plt.close()
print(f"\n  ✓ Pruning comparison saved → shap_pruning_comparison.png")

# ==============================================================================
# PHASE G — THRESHOLD ANALYSIS (Layer 5 supplement)
# ==============================================================================

print("\n" + "="*70)
print("PHASE G — CLINICAL THRESHOLD ANALYSIS — Layer 5")
print("="*70)

thresholds = np.linspace(0.01, 0.99, 200)
sensitivity_vals = []
specificity_vals = []

for t in thresholds:
    pred    = (y_prob_1yr >= t).astype(int)
    tp = ((pred==1) & (ytest_arr==1)).sum()
    fn = ((pred==0) & (ytest_arr==1)).sum()
    tn = ((pred==0) & (ytest_arr==0)).sum()
    fp = ((pred==1) & (ytest_arr==0)).sum()
    sensitivity_vals.append(tp / (tp+fn+1e-12))
    specificity_vals.append(tn / (tn+fp+1e-12))

sensitivity_arr = np.array(sensitivity_vals)
specificity_arr = np.array(specificity_vals)

# Find crossing point
diff      = np.abs(sensitivity_arr - specificity_arr)
cross_idx = np.argmin(diff)
cross_thr = float(thresholds[cross_idx])
cross_sen = float(sensitivity_arr[cross_idx])

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(thresholds, sensitivity_arr, 'b-', linewidth=2, label='Sensitivity (Recall)')
ax.plot(thresholds, specificity_arr, 'r-', linewidth=2, label='Specificity')
ax.axvline(x=cross_thr, color='green', linestyle='--', linewidth=1.5,
           label=f'Sens=Spec crossing: threshold={cross_thr:.3f}  '
                 f'sens/spec={cross_sen:.3f}')
ax.axvline(x=OPTIMAL_THRESHOLD_1YR, color='orange', linestyle=':', linewidth=1.5,
           label=f'F1-optimal threshold={OPTIMAL_THRESHOLD_1YR:.3f}')
ax.set_xlabel('Decision Threshold', fontsize=12)
ax.set_ylabel('Metric Value', fontsize=12)
ax.set_title(f'Clinical Threshold Analysis — {best_model_name} (1-Year Rejection)',
             fontsize=12, fontweight='bold')
ax.legend(fontsize=9)
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/threshold_analysis_1yr.png", dpi=200, bbox_inches='tight')
plt.close()

threshold_df = pd.DataFrame({
    'threshold':   thresholds,
    'sensitivity': sensitivity_arr,
    'specificity': specificity_arr
})
threshold_df.to_csv(f"{FIG_DIR}/threshold_analysis_data_1yr.csv", index=False)
print(f"  ✓ Threshold analysis saved")
print(f"  Sens=Spec crossing: threshold={cross_thr:.3f}  "
      f"sensitivity=specificity={cross_sen:.3f}")

# ==============================================================================
# PHASE H — FINAL SUMMARY AND OUTPUT MANIFEST
# ==============================================================================

print(f"\n{'='*70}")
print("SEGMENT 7 COMPLETE — OUTPUT MANIFEST")
print(f"{'='*70}")

outputs = [
    ("shap_beeswarm_1yr.png",            "Fig 1: Global SHAP beeswarm (1yr)"),
    ("shap_bar_1yr.png",                  "Fig 2: SHAP bar ranking (1yr)"),
    ("shap_beeswarm_3yr.png",             "Fig 3: Global SHAP beeswarm (3yr) — if 3yr run"),
    ("shap_cross_horizon_comparison.png", "Fig 4: Cross-horizon feature comparison"),
    ("shap_waterfall_cases_1yr.png",      "Fig 5: Waterfall case studies (TP/FP/FN/TN)"),
    ("lime_tp_1yr.png",                   "Fig 6: LIME TP case study"),
    ("lime_fp_1yr.png",                   "Fig 7: LIME FP case study"),
    ("lime_fn_1yr.png",                   "Fig 8: LIME FN case study"),
    ("lime_tn_1yr.png",                   "Fig 9: LIME TN case study"),
    ("pdp_ice_top5_1yr.png",              "Fig 10: PDP+ICE top-5 features"),
    ("pdp_2d_ischtime_hla_1yr.png",       "Fig 11: 2D PDP ischaemic time × HLA"),
    ("shap_pruning_comparison.png",       "Fig 12: SHAP-guided pruning (CS Novelty)"),
    ("threshold_analysis_1yr.png",        "Fig 13: Clinical threshold analysis"),
]

print(f"\n  {'File':<45} {'Thesis Use'}")
print(f"  {'-'*44} {'-'*35}")
for fname, use in outputs:
    fpath = f"{FIG_DIR}/{fname}"
    status = "✓" if os.path.exists(fpath) else "—"
    print(f"  {status} {fname:<44} {use}")

print(f"\n  All figures → {FIG_DIR}")
print(f"\n  KEY THESIS NUMBERS TO FILL IN:")
print(f"    Best 1yr AUROC           : {auroc_1yr:.4f} ({best_model_name}/{SHAP_BEST_STRATEGY})")
print(f"    #1 SHAP feature (1yr)    : {top_names_1yr[0]}")
print(f"    #1 SHAP feature (3yr)    : {top_names_3yr[0] if HAS_3YR else 'N/A'}")
print(f"    SHAP-stable min features : {MINIMAL_FEATURE_N}")
print(f"    Threshold (sens=spec)    : {cross_thr:.3f}")
print(f"    Sensitivity at crossing  : {cross_sen:.3f}")

======================================================================
SEGMENT 7: INTERPRETABILITY FRAMEWORK
======================================================================

Phase A — Loading models and data...

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Thesis_parquet/X_train_tree.parquet'